TRUNCATE table bronze_bec_ods_stg.fa_transaction_headers;
INSERT INTO bronze_bec_ods_stg.fa_transaction_headers (
  TRANSACTION_HEADER_ID,
  BOOK_TYPE_CODE,
  ASSET_ID,
  TRANSACTION_TYPE_CODE,
  TRANSACTION_DATE_ENTERED,
  DATE_EFFECTIVE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  TRANSACTION_NAME,
  INVOICE_TRANSACTION_ID,
  SOURCE_TRANSACTION_HEADER_ID,
  MASS_REFERENCE_ID,
  LAST_UPDATE_LOGIN,
  TRANSACTION_SUBTYPE,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE_CATEGORY_CODE,
  TRANSACTION_KEY,
  AMORTIZATION_START_DATE,
  CALLING_INTERFACE,
  MASS_TRANSACTION_ID,
  MEMBER_TRANSACTION_HEADER_ID,
  TRX_REFERENCE_ID,
  EVENT_ID,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    TRANSACTION_HEADER_ID,
    BOOK_TYPE_CODE,
    ASSET_ID,
    TRANSACTION_TYPE_CODE,
    TRANSACTION_DATE_ENTERED,
    DATE_EFFECTIVE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    TRANSACTION_NAME,
    INVOICE_TRANSACTION_ID,
    SOURCE_TRANSACTION_HEADER_ID,
    MASS_REFERENCE_ID,
    LAST_UPDATE_LOGIN,
    TRANSACTION_SUBTYPE,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE_CATEGORY_CODE,
    TRANSACTION_KEY,
    AMORTIZATION_START_DATE,
    CALLING_INTERFACE,
    MASS_TRANSACTION_ID,
    MEMBER_TRANSACTION_HEADER_ID,
    TRX_REFERENCE_ID,
    EVENT_ID,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.fa_transaction_headers
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(TRANSACTION_HEADER_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(TRANSACTION_HEADER_ID, 0) AS TRANSACTION_HEADER_ID,
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.fa_transaction_headers
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(TRANSACTION_HEADER_ID, 0)
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'fa_transaction_headers'
    )
);