TRUNCATE table bronze_bec_ods_stg.BOM_OPERATIONAL_ROUTINGS;
INSERT INTO bronze_bec_ods_stg.bom_operational_routings (
  ROUTING_SEQUENCE_ID,
  ASSEMBLY_ITEM_ID,
  ORGANIZATION_ID,
  ALTERNATE_ROUTING_DESIGNATOR,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  ROUTING_TYPE,
  COMMON_ASSEMBLY_ITEM_ID,
  COMMON_ROUTING_SEQUENCE_ID,
  ROUTING_COMMENT,
  COMPLETION_SUBINVENTORY,
  COMPLETION_LOCATOR_ID,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  LINE_ID,
  CFM_ROUTING_FLAG,
  MIXED_MODEL_MAP_FLAG,
  PRIORITY,
  TOTAL_PRODUCT_CYCLE_TIME,
  CTP_FLAG,
  PROJECT_ID,
  TASK_ID,
  PENDING_FROM_ECN,
  ORIGINAL_SYSTEM_REFERENCE,
  SERIALIZATION_START_OP,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    ROUTING_SEQUENCE_ID,
    ASSEMBLY_ITEM_ID,
    ORGANIZATION_ID,
    ALTERNATE_ROUTING_DESIGNATOR,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    ROUTING_TYPE,
    COMMON_ASSEMBLY_ITEM_ID,
    COMMON_ROUTING_SEQUENCE_ID,
    ROUTING_COMMENT,
    COMPLETION_SUBINVENTORY,
    COMPLETION_LOCATOR_ID,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    LINE_ID,
    CFM_ROUTING_FLAG,
    MIXED_MODEL_MAP_FLAG,
    PRIORITY,
    TOTAL_PRODUCT_CYCLE_TIME,
    CTP_FLAG,
    PROJECT_ID,
    TASK_ID,
    PENDING_FROM_ECN,
    ORIGINAL_SYSTEM_REFERENCE,
    SERIALIZATION_START_OP,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.bom_operational_routings
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(ROUTING_SEQUENCE_ID, '0'), kca_seq_id) IN (
      SELECT
        COALESCE(ROUTING_SEQUENCE_ID, '0') AS ROUTING_SEQUENCE_ID,
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.bom_operational_routings
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(ROUTING_SEQUENCE_ID, '0')
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'bom_operational_routings'
    )
);