TRUNCATE table
	table bronze_bec_ods_stg.CSF_DEBRIEF_HEADERS;
INSERT INTO bronze_bec_ods_stg.CSF_DEBRIEF_HEADERS (
  DEBRIEF_HEADER_ID,
  DEBRIEF_NUMBER,
  DEBRIEF_DATE,
  DEBRIEF_STATUS_ID,
  TASK_ASSIGNMENT_ID,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE_CATEGORY,
  SECURITY_GROUP_ID,
  STATISTICS_UPDATED,
  PROCESSED_FLAG,
  TRAVEL_START_TIME,
  TRAVEL_END_TIME,
  OBJECT_VERSION_NUMBER,
  TRAVEL_DISTANCE_IN_KM,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    DEBRIEF_HEADER_ID,
    DEBRIEF_NUMBER,
    DEBRIEF_DATE,
    DEBRIEF_STATUS_ID,
    TASK_ASSIGNMENT_ID,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE_CATEGORY,
    SECURITY_GROUP_ID,
    STATISTICS_UPDATED,
    PROCESSED_FLAG,
    TRAVEL_START_TIME,
    TRAVEL_END_TIME,
    OBJECT_VERSION_NUMBER,
    TRAVEL_DISTANCE_IN_KM,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.CSF_DEBRIEF_HEADERS
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(DEBRIEF_HEADER_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(DEBRIEF_HEADER_ID, 0) AS DEBRIEF_HEADER_ID,
        MAX(kca_seq_id) AS kca_seq_id
      FROM bec_raw_dl_ext.CSF_DEBRIEF_HEADERS
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(DEBRIEF_HEADER_ID, 0)
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'csf_debrief_headers'
    )
);