TRUNCATE table
	table bronze_bec_ods_stg.hr_all_organization_units;
INSERT INTO bronze_bec_ods_stg.hr_all_organization_units (
  ORGANIZATION_ID,
  BUSINESS_GROUP_ID,
  COST_ALLOCATION_KEYFLEX_ID,
  LOCATION_ID,
  SOFT_CODING_KEYFLEX_ID,
  DATE_FROM,
  NAME,
  DATE_TO,
  INTERNAL_EXTERNAL_FLAG,
  INTERNAL_ADDRESS_LINE,
  TYPE,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE16,
  ATTRIBUTE17,
  ATTRIBUTE18,
  ATTRIBUTE19,
  ATTRIBUTE20,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  CREATED_BY,
  CREATION_DATE,
  OBJECT_VERSION_NUMBER,
  PARTY_ID,
  ATTRIBUTE21,
  ATTRIBUTE22,
  ATTRIBUTE23,
  ATTRIBUTE24,
  ATTRIBUTE25,
  ATTRIBUTE26,
  ATTRIBUTE27,
  ATTRIBUTE28,
  ATTRIBUTE29,
  ATTRIBUTE30,
  COMMENTS,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    ORGANIZATION_ID,
    BUSINESS_GROUP_ID,
    COST_ALLOCATION_KEYFLEX_ID,
    LOCATION_ID,
    SOFT_CODING_KEYFLEX_ID,
    DATE_FROM,
    NAME,
    DATE_TO,
    INTERNAL_EXTERNAL_FLAG,
    INTERNAL_ADDRESS_LINE,
    TYPE,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE16,
    ATTRIBUTE17,
    ATTRIBUTE18,
    ATTRIBUTE19,
    ATTRIBUTE20,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATED_BY,
    CREATION_DATE,
    OBJECT_VERSION_NUMBER,
    PARTY_ID,
    ATTRIBUTE21,
    ATTRIBUTE22,
    ATTRIBUTE23,
    ATTRIBUTE24,
    ATTRIBUTE25,
    ATTRIBUTE26,
    ATTRIBUTE27,
    ATTRIBUTE28,
    ATTRIBUTE29,
    ATTRIBUTE30,
    COMMENTS,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.hr_all_organization_units
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (organization_id, kca_seq_id) IN (
      SELECT
        organization_id,
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.hr_all_organization_units
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        organization_id
    )
    AND (
      kca_seq_date > (
        SELECT
          (
            executebegints - prune_days
          )
        FROM bec_etl_ctrl.batch_ods_info
        WHERE
          ods_table_name = 'hr_all_organization_units'
      )
    )
);