TRUNCATE table bronze_bec_ods_stg.MTL_CATEGORY_SETS_B;
INSERT INTO bronze_bec_ods_stg.MTL_CATEGORY_SETS_B (
  CATEGORY_SET_ID, /* ,CATEGORY_SET_NAME    */
  STRUCTURE_ID,
  VALIDATE_FLAG,
  CONTROL_LEVEL, /* ,DESCRIPTION    */
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  DEFAULT_CATEGORY_ID,
  MULT_ITEM_CAT_ASSIGN_FLAG,
  CONTROL_LEVEL_UPDATEABLE_FLAG,
  MULT_ITEM_CAT_UPDATEABLE_FLAG,
  HIERARCHY_ENABLED,
  VALIDATE_FLAG_UPDATEABLE_FLAG,
  USER_CREATION_ALLOWED_FLAG,
  RAISE_ITEM_CAT_ASSIGN_EVENT,
  RAISE_ALT_CAT_HIER_CHG_EVENT,
  RAISE_CATALOG_CAT_CHG_EVENT,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
SELECT
  CATEGORY_SET_ID, /* ,CATEGORY_SET_NAME    */
  STRUCTURE_ID,
  VALIDATE_FLAG,
  CONTROL_LEVEL, /* ,DESCRIPTION    */
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  DEFAULT_CATEGORY_ID,
  MULT_ITEM_CAT_ASSIGN_FLAG,
  CONTROL_LEVEL_UPDATEABLE_FLAG,
  MULT_ITEM_CAT_UPDATEABLE_FLAG,
  HIERARCHY_ENABLED,
  VALIDATE_FLAG_UPDATEABLE_FLAG,
  USER_CREATION_ALLOWED_FLAG,
  RAISE_ITEM_CAT_ASSIGN_EVENT,
  RAISE_ALT_CAT_HIER_CHG_EVENT,
  RAISE_CATALOG_CAT_CHG_EVENT,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
FROM bec_raw_dl_ext.mtl_category_sets_b
WHERE
  kca_operation <> 'DELETE'
  AND COALESCE(kca_seq_id, '') <> ''
  AND (CATEGORY_SET_ID, kca_seq_id) IN (
    SELECT
      CATEGORY_SET_ID,
      MAX(kca_seq_id)
    FROM bec_raw_dl_ext.mtl_category_sets_b
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
    GROUP BY
      CATEGORY_SET_ID
  )
  AND (
    kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'mtl_category_sets_b'
    )
  );