TRUNCATE table bronze_bec_ods_stg.GL_LEDGER_RELATIONSHIPS;
INSERT INTO bronze_bec_ods_stg.GL_LEDGER_RELATIONSHIPS (
  RELATIONSHIP_ID,
  SOURCE_LEDGER_ID,
  TARGET_LEDGER_ID,
  SLA_LEDGER_ID,
  PRIMARY_LEDGER_ID,
  TARGET_CURRENCY_CODE,
  TARGET_LEDGER_NAME,
  TARGET_LEDGER_SHORT_NAME,
  TARGET_LEDGER_CATEGORY_CODE,
  RELATIONSHIP_TYPE_CODE,
  RELATIONSHIP_ENABLED_FLAG,
  INHERIT_CREATION_USER_FLAG,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  GL_JE_CONVERSION_SET_ID,
  SL_COA_MAPPING_ID,
  AUTOMATIC_POST_FLAG,
  ALC_DEFAULT_CONV_RATE_TYPE,
  ALC_NO_RATE_ACTION_CODE,
  ALC_MAX_DAYS_ROLL_RATE,
  ALC_INHERIT_CONVERSION_TYPE,
  ALC_INIT_CONV_OPTION_CODE,
  ALC_INIT_PERIOD,
  ALC_INIT_DATE,
  ALC_INITIALIZING_RATE_DATE,
  ALC_INITIALIZING_RATE_TYPE,
  ALC_PERIOD_AVERAGE_RATE_TYPE,
  ALC_PERIOD_END_RATE_TYPE,
  APPLICATION_ID,
  ORG_ID,
  DISABLE_CONVERSION_DATE,
  STATUS_CODE,
  HIST_CONV_STATUS_CODE,
  KCA_OPERATION,
  KCA_SEQ_ID,
  kca_seq_date
)
(
  SELECT
    RELATIONSHIP_ID,
    SOURCE_LEDGER_ID,
    TARGET_LEDGER_ID,
    SLA_LEDGER_ID,
    PRIMARY_LEDGER_ID,
    TARGET_CURRENCY_CODE,
    TARGET_LEDGER_NAME,
    TARGET_LEDGER_SHORT_NAME,
    TARGET_LEDGER_CATEGORY_CODE,
    RELATIONSHIP_TYPE_CODE,
    RELATIONSHIP_ENABLED_FLAG,
    INHERIT_CREATION_USER_FLAG,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    GL_JE_CONVERSION_SET_ID,
    SL_COA_MAPPING_ID,
    AUTOMATIC_POST_FLAG,
    ALC_DEFAULT_CONV_RATE_TYPE,
    ALC_NO_RATE_ACTION_CODE,
    ALC_MAX_DAYS_ROLL_RATE,
    ALC_INHERIT_CONVERSION_TYPE,
    ALC_INIT_CONV_OPTION_CODE,
    ALC_INIT_PERIOD,
    ALC_INIT_DATE,
    ALC_INITIALIZING_RATE_DATE,
    ALC_INITIALIZING_RATE_TYPE,
    ALC_PERIOD_AVERAGE_RATE_TYPE,
    ALC_PERIOD_END_RATE_TYPE,
    APPLICATION_ID,
    ORG_ID,
    DISABLE_CONVERSION_DATE,
    STATUS_CODE,
    HIST_CONV_STATUS_CODE,
    KCA_OPERATION,
    KCA_SEQ_ID,
    kca_seq_date
  FROM bec_raw_dl_ext.GL_LEDGER_RELATIONSHIPS
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (RELATIONSHIP_ID, KCA_SEQ_ID) IN (
      SELECT
        RELATIONSHIP_ID,
        MAX(KCA_SEQ_ID)
      FROM bec_raw_dl_ext.GL_LEDGER_RELATIONSHIPS
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        RELATIONSHIP_ID
    )
    AND (
      kca_seq_date > (
        SELECT
          (
            executebegints - prune_days
          )
        FROM bec_etl_ctrl.batch_ods_info
        WHERE
          ods_table_name = 'gl_ledger_relationships'
      )
    )
);