TRUNCATE table bronze_bec_ods_stg.WIP_TRANSACTION_ACCOUNTS;
INSERT INTO bronze_bec_ods_stg.WIP_TRANSACTION_ACCOUNTS (
  TRANSACTION_ID,
  REFERENCE_ACCOUNT,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  ORGANIZATION_ID,
  TRANSACTION_DATE,
  WIP_ENTITY_ID,
  REPETITIVE_SCHEDULE_ID,
  ACCOUNTING_LINE_TYPE,
  TRANSACTION_VALUE,
  BASE_TRANSACTION_VALUE,
  CONTRA_SET_ID,
  PRIMARY_QUANTITY,
  RATE_OR_AMOUNT,
  BASIS_TYPE,
  RESOURCE_ID,
  COST_ELEMENT_ID,
  ACTIVITY_ID,
  CURRENCY_CODE,
  CURRENCY_CONVERSION_DATE,
  CURRENCY_CONVERSION_TYPE,
  CURRENCY_CONVERSION_RATE,
  OVERHEAD_BASIS_FACTOR,
  BASIS_RESOURCE_ID,
  GL_BATCH_ID,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  GL_SL_LINK_ID,
  WIP_SUB_LEDGER_ID,
  ENCUMBRANCE_TYPE_ID,
  KCA_OPERATION,
  kca_seq_id,
  KCA_SEQ_DATE
)
(
  SELECT
    TRANSACTION_ID,
    REFERENCE_ACCOUNT,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    ORGANIZATION_ID,
    TRANSACTION_DATE,
    WIP_ENTITY_ID,
    REPETITIVE_SCHEDULE_ID,
    ACCOUNTING_LINE_TYPE,
    TRANSACTION_VALUE,
    BASE_TRANSACTION_VALUE,
    CONTRA_SET_ID,
    PRIMARY_QUANTITY,
    RATE_OR_AMOUNT,
    BASIS_TYPE,
    RESOURCE_ID,
    COST_ELEMENT_ID,
    ACTIVITY_ID,
    CURRENCY_CODE,
    CURRENCY_CONVERSION_DATE,
    CURRENCY_CONVERSION_TYPE,
    CURRENCY_CONVERSION_RATE,
    OVERHEAD_BASIS_FACTOR,
    BASIS_RESOURCE_ID,
    GL_BATCH_ID,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    GL_SL_LINK_ID,
    WIP_SUB_LEDGER_ID,
    ENCUMBRANCE_TYPE_ID,
    KCA_OPERATION,
    kca_seq_id,
    KCA_SEQ_DATE
  FROM bec_raw_dl_ext.WIP_TRANSACTION_ACCOUNTS
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(TRANSACTION_ID, 0), COALESCE(REFERENCE_ACCOUNT, 0), COALESCE(WIP_SUB_LEDGER_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(TRANSACTION_ID, 0),
        COALESCE(REFERENCE_ACCOUNT, 0),
        COALESCE(WIP_SUB_LEDGER_ID, 0),
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.WIP_TRANSACTION_ACCOUNTS
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(TRANSACTION_ID, 0),
        COALESCE(REFERENCE_ACCOUNT, 0),
        COALESCE(WIP_SUB_LEDGER_ID, 0)
    )
    AND (
      KCA_SEQ_DATE > (
        SELECT
          (
            executebegints - prune_days
          )
        FROM bec_etl_ctrl.batch_ods_info
        WHERE
          ods_table_name = 'wip_transaction_accounts'
      )
    )
);