TRUNCATE table
	table bronze_bec_ods_stg.hr_organization_information;
INSERT INTO bronze_bec_ods_stg.hr_organization_information (
  ORG_INFORMATION_ID,
  ORG_INFORMATION_CONTEXT,
  ORGANIZATION_ID,
  ORG_INFORMATION1,
  ORG_INFORMATION10,
  ORG_INFORMATION11,
  ORG_INFORMATION12,
  ORG_INFORMATION13,
  ORG_INFORMATION14,
  ORG_INFORMATION15,
  ORG_INFORMATION16,
  ORG_INFORMATION17,
  ORG_INFORMATION18,
  ORG_INFORMATION19,
  ORG_INFORMATION2,
  ORG_INFORMATION20,
  ORG_INFORMATION3,
  ORG_INFORMATION4,
  ORG_INFORMATION5,
  ORG_INFORMATION6,
  ORG_INFORMATION7,
  ORG_INFORMATION8,
  ORG_INFORMATION9,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE16,
  ATTRIBUTE17,
  ATTRIBUTE18,
  ATTRIBUTE19,
  ATTRIBUTE20,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  CREATED_BY,
  CREATION_DATE,
  OBJECT_VERSION_NUMBER,
  PARTY_ID,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    ORG_INFORMATION_ID,
    ORG_INFORMATION_CONTEXT,
    ORGANIZATION_ID,
    ORG_INFORMATION1,
    ORG_INFORMATION10,
    ORG_INFORMATION11,
    ORG_INFORMATION12,
    ORG_INFORMATION13,
    ORG_INFORMATION14,
    ORG_INFORMATION15,
    ORG_INFORMATION16,
    ORG_INFORMATION17,
    ORG_INFORMATION18,
    ORG_INFORMATION19,
    ORG_INFORMATION2,
    ORG_INFORMATION20,
    ORG_INFORMATION3,
    ORG_INFORMATION4,
    ORG_INFORMATION5,
    ORG_INFORMATION6,
    ORG_INFORMATION7,
    ORG_INFORMATION8,
    ORG_INFORMATION9,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE16,
    ATTRIBUTE17,
    ATTRIBUTE18,
    ATTRIBUTE19,
    ATTRIBUTE20,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATED_BY,
    CREATION_DATE,
    OBJECT_VERSION_NUMBER,
    PARTY_ID,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.hr_organization_information
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (ORG_INFORMATION_ID, kca_seq_id) IN (
      SELECT
        ORG_INFORMATION_ID,
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.hr_organization_information
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        ORG_INFORMATION_ID
    )
    AND (
      kca_seq_date > (
        SELECT
          (
            executebegints - prune_days
          )
        FROM bec_etl_ctrl.batch_ods_info
        WHERE
          ods_table_name = 'hr_organization_information'
      )
    )
);