DROP TABLE IF EXISTS bronze_bec_ods_stg.OE_HOLD_AUTHORIZATIONS;
CREATE TABLE bronze_bec_ods_stg.OE_HOLD_AUTHORIZATIONS AS
SELECT
  *
FROM bec_raw_dl_ext.OE_HOLD_AUTHORIZATIONS
WHERE
  kca_operation <> 'DELETE';