TRUNCATE table
	table bronze_bec_ods_stg.CSI_COUNTER_ASSOCIATIONS;
INSERT INTO bronze_bec_ods_stg.CSI_COUNTER_ASSOCIATIONS (
  INSTANCE_ASSOCIATION_ID,
  SOURCE_OBJECT_CODE,
  SOURCE_OBJECT_ID,
  COUNTER_ID,
  START_DATE_ACTIVE,
  END_DATE_ACTIVE,
  SECURITY_GROUP_ID,
  OBJECT_VERSION_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  MIGRATED_FLAG,
  MAINT_ORGANIZATION_ID,
  PRIMARY_FAILURE_FLAG,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    INSTANCE_ASSOCIATION_ID,
    SOURCE_OBJECT_CODE,
    SOURCE_OBJECT_ID,
    COUNTER_ID,
    START_DATE_ACTIVE,
    END_DATE_ACTIVE,
    SECURITY_GROUP_ID,
    OBJECT_VERSION_NUMBER,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    MIGRATED_FLAG,
    MAINT_ORGANIZATION_ID,
    PRIMARY_FAILURE_FLAG,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.CSI_COUNTER_ASSOCIATIONS
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(INSTANCE_ASSOCIATION_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(INSTANCE_ASSOCIATION_ID, 0) AS INSTANCE_ASSOCIATION_ID,
        MAX(kca_seq_id) AS kca_seq_id
      FROM bec_raw_dl_ext.CSI_COUNTER_ASSOCIATIONS
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(INSTANCE_ASSOCIATION_ID, 0)
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'csi_counter_associations'
    )
);