TRUNCATE table bronze_bec_ods_stg.OE_HOLD_SOURCES_ALL;
INSERT INTO bronze_bec_ods_stg.OE_HOLD_SOURCES_ALL (
  HOLD_SOURCE_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  CREATION_DATE,
  CREATED_BY,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  REQUEST_ID,
  HOLD_ID,
  HOLD_ENTITY_CODE,
  HOLD_ENTITY_ID,
  HOLD_ENTITY_CODE2,
  HOLD_ENTITY_ID2,
  HOLD_UNTIL_DATE,
  RELEASED_FLAG,
  HOLD_COMMENT,
  ORG_ID,
  CONTEXT,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  HOLD_RELEASE_ID,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    HOLD_SOURCE_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATION_DATE,
    CREATED_BY,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    REQUEST_ID,
    HOLD_ID,
    HOLD_ENTITY_CODE,
    HOLD_ENTITY_ID,
    HOLD_ENTITY_CODE2,
    HOLD_ENTITY_ID2,
    HOLD_UNTIL_DATE,
    RELEASED_FLAG,
    HOLD_COMMENT,
    ORG_ID,
    CONTEXT,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    HOLD_RELEASE_ID,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.OE_HOLD_SOURCES_ALL
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(HOLD_SOURCE_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(HOLD_SOURCE_ID, 0),
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.OE_HOLD_SOURCES_ALL
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(HOLD_SOURCE_ID, 0)
    )
    AND (
      kca_seq_date > (
        SELECT
          (
            executebegints - prune_days
          )
        FROM bec_etl_ctrl.batch_ods_info
        WHERE
          ods_table_name = 'oe_hold_sources_all'
      )
    )
);