TRUNCATE table bronze_bec_ods_stg.MTL_TRANSACTION_ACCOUNTS;
INSERT INTO bronze_bec_ods_stg.MTL_TRANSACTION_ACCOUNTS (
  TRANSACTION_ID,
  REFERENCE_ACCOUNT,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  INVENTORY_ITEM_ID,
  ORGANIZATION_ID,
  TRANSACTION_DATE,
  TRANSACTION_SOURCE_ID,
  TRANSACTION_SOURCE_TYPE_ID,
  TRANSACTION_VALUE,
  PRIMARY_QUANTITY,
  GL_BATCH_ID,
  ACCOUNTING_LINE_TYPE,
  BASE_TRANSACTION_VALUE,
  CONTRA_SET_ID,
  RATE_OR_AMOUNT,
  BASIS_TYPE,
  RESOURCE_ID,
  COST_ELEMENT_ID,
  ACTIVITY_ID,
  CURRENCY_CODE,
  CURRENCY_CONVERSION_DATE,
  CURRENCY_CONVERSION_TYPE,
  CURRENCY_CONVERSION_RATE,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ENCUMBRANCE_TYPE_ID,
  REPETITIVE_SCHEDULE_ID,
  GL_SL_LINK_ID,
  USSGL_TRANSACTION_CODE,
  INV_SUB_LEDGER_ID,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    TRANSACTION_ID,
    REFERENCE_ACCOUNT,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    INVENTORY_ITEM_ID,
    ORGANIZATION_ID,
    TRANSACTION_DATE,
    TRANSACTION_SOURCE_ID,
    TRANSACTION_SOURCE_TYPE_ID,
    TRANSACTION_VALUE,
    PRIMARY_QUANTITY,
    GL_BATCH_ID,
    ACCOUNTING_LINE_TYPE,
    BASE_TRANSACTION_VALUE,
    CONTRA_SET_ID,
    RATE_OR_AMOUNT,
    BASIS_TYPE,
    RESOURCE_ID,
    COST_ELEMENT_ID,
    ACTIVITY_ID,
    CURRENCY_CODE,
    CURRENCY_CONVERSION_DATE,
    CURRENCY_CONVERSION_TYPE,
    CURRENCY_CONVERSION_RATE,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ENCUMBRANCE_TYPE_ID,
    REPETITIVE_SCHEDULE_ID,
    GL_SL_LINK_ID,
    USSGL_TRANSACTION_CODE,
    INV_SUB_LEDGER_ID,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.MTL_TRANSACTION_ACCOUNTS
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(TRANSACTION_ID, 0), COALESCE(REFERENCE_ACCOUNT, 0), COALESCE(COST_ELEMENT_ID, 0), COALESCE(PRIMARY_QUANTITY, 0), COALESCE(RESOURCE_ID, 0), COALESCE(ACCOUNTING_LINE_TYPE, 0), COALESCE(BASE_TRANSACTION_VALUE, 0), kca_seq_id) IN (
      SELECT
        COALESCE(TRANSACTION_ID, 0),
        COALESCE(REFERENCE_ACCOUNT, 0),
        COALESCE(COST_ELEMENT_ID, 0),
        COALESCE(PRIMARY_QUANTITY, 0),
        COALESCE(RESOURCE_ID, 0),
        COALESCE(ACCOUNTING_LINE_TYPE, 0),
        COALESCE(BASE_TRANSACTION_VALUE, 0),
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.MTL_TRANSACTION_ACCOUNTS
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(TRANSACTION_ID, 0),
        COALESCE(REFERENCE_ACCOUNT, 0),
        COALESCE(COST_ELEMENT_ID, 0),
        COALESCE(PRIMARY_QUANTITY, 0),
        COALESCE(RESOURCE_ID, 0),
        COALESCE(ACCOUNTING_LINE_TYPE, 0),
        COALESCE(BASE_TRANSACTION_VALUE, 0)
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'mtl_transaction_accounts'
    )
);