TRUNCATE table bronze_bec_ods_stg.fa_adjustments;
INSERT INTO bronze_bec_ods_stg.fa_adjustments (
  TRANSACTION_HEADER_ID,
  SOURCE_TYPE_CODE,
  ADJUSTMENT_TYPE,
  DEBIT_CREDIT_FLAG,
  CODE_COMBINATION_ID,
  BOOK_TYPE_CODE,
  ASSET_ID,
  ADJUSTMENT_AMOUNT,
  DISTRIBUTION_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  ANNUALIZED_ADJUSTMENT,
  JE_HEADER_ID,
  JE_LINE_NUM,
  PERIOD_COUNTER_ADJUSTED,
  PERIOD_COUNTER_CREATED,
  ASSET_INVOICE_ID,
  GLOBAL_ATTRIBUTE1,
  GLOBAL_ATTRIBUTE2,
  GLOBAL_ATTRIBUTE3,
  GLOBAL_ATTRIBUTE4,
  GLOBAL_ATTRIBUTE5,
  GLOBAL_ATTRIBUTE6,
  GLOBAL_ATTRIBUTE7,
  GLOBAL_ATTRIBUTE8,
  GLOBAL_ATTRIBUTE9,
  GLOBAL_ATTRIBUTE10,
  GLOBAL_ATTRIBUTE11,
  GLOBAL_ATTRIBUTE12,
  GLOBAL_ATTRIBUTE13,
  GLOBAL_ATTRIBUTE14,
  GLOBAL_ATTRIBUTE15,
  GLOBAL_ATTRIBUTE16,
  GLOBAL_ATTRIBUTE17,
  GLOBAL_ATTRIBUTE18,
  GLOBAL_ATTRIBUTE19,
  GLOBAL_ATTRIBUTE20,
  GLOBAL_ATTRIBUTE_CATEGORY,
  DEPRN_OVERRIDE_FLAG,
  TRACK_MEMBER_FLAG,
  ADJUSTMENT_LINE_ID,
  SOURCE_LINE_ID,
  SOURCE_DEST_CODE,
  INSERTION_ORDER,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    TRANSACTION_HEADER_ID,
    SOURCE_TYPE_CODE,
    ADJUSTMENT_TYPE,
    DEBIT_CREDIT_FLAG,
    CODE_COMBINATION_ID,
    BOOK_TYPE_CODE,
    ASSET_ID,
    ADJUSTMENT_AMOUNT,
    DISTRIBUTION_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    ANNUALIZED_ADJUSTMENT,
    JE_HEADER_ID,
    JE_LINE_NUM,
    PERIOD_COUNTER_ADJUSTED,
    PERIOD_COUNTER_CREATED,
    ASSET_INVOICE_ID,
    GLOBAL_ATTRIBUTE1,
    GLOBAL_ATTRIBUTE2,
    GLOBAL_ATTRIBUTE3,
    GLOBAL_ATTRIBUTE4,
    GLOBAL_ATTRIBUTE5,
    GLOBAL_ATTRIBUTE6,
    GLOBAL_ATTRIBUTE7,
    GLOBAL_ATTRIBUTE8,
    GLOBAL_ATTRIBUTE9,
    GLOBAL_ATTRIBUTE10,
    GLOBAL_ATTRIBUTE11,
    GLOBAL_ATTRIBUTE12,
    GLOBAL_ATTRIBUTE13,
    GLOBAL_ATTRIBUTE14,
    GLOBAL_ATTRIBUTE15,
    GLOBAL_ATTRIBUTE16,
    GLOBAL_ATTRIBUTE17,
    GLOBAL_ATTRIBUTE18,
    GLOBAL_ATTRIBUTE19,
    GLOBAL_ATTRIBUTE20,
    GLOBAL_ATTRIBUTE_CATEGORY,
    DEPRN_OVERRIDE_FLAG,
    TRACK_MEMBER_FLAG,
    ADJUSTMENT_LINE_ID,
    SOURCE_LINE_ID,
    SOURCE_DEST_CODE,
    INSERTION_ORDER,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.fa_adjustments
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(TRANSACTION_HEADER_ID, 0), COALESCE(ADJUSTMENT_LINE_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(TRANSACTION_HEADER_ID, 0) AS TRANSACTION_HEADER_ID,
        COALESCE(ADJUSTMENT_LINE_ID, 0) AS ADJUSTMENT_LINE_ID,
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.fa_adjustments
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(TRANSACTION_HEADER_ID, 0),
        COALESCE(ADJUSTMENT_LINE_ID, 0)
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'fa_adjustments'
    )
);