TRUNCATE table bronze_bec_ods_stg.MSC_BOMS;
INSERT INTO bronze_bec_ods_stg.MSC_BOMS (
  PLAN_ID,
  BILL_SEQUENCE_ID,
  SR_INSTANCE_ID,
  ASSEMBLY_TYPE,
  ALTERNATE_BOM_DESIGNATOR,
  SPECIFIC_ASSEMBLY_COMMENT,
  PENDING_FROM_ECN,
  SCALING_TYPE,
  ASSEMBLY_QUANTITY,
  UOM,
  ORGANIZATION_ID,
  ASSEMBLY_ITEM_ID,
  REFRESH_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  YIELDING_OP_SEQ_NUM,
  NEW_PLAN_ID,
  NEW_PLAN_LIST,
  APPLIED,
  SIMULATION_SET_ID,
  REPAIRABLE,
  ACTIVITY_ITEM_ID,
  `alternate_bom_designator#1`,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    PLAN_ID,
    BILL_SEQUENCE_ID,
    SR_INSTANCE_ID,
    ASSEMBLY_TYPE,
    ALTERNATE_BOM_DESIGNATOR,
    SPECIFIC_ASSEMBLY_COMMENT,
    PENDING_FROM_ECN,
    SCALING_TYPE,
    ASSEMBLY_QUANTITY,
    UOM,
    ORGANIZATION_ID,
    ASSEMBLY_ITEM_ID,
    REFRESH_NUMBER,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    YIELDING_OP_SEQ_NUM,
    NEW_PLAN_ID,
    NEW_PLAN_LIST,
    APPLIED,
    SIMULATION_SET_ID,
    REPAIRABLE,
    ACTIVITY_ITEM_ID,
    `alternate_bom_designator#1`,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.MSC_BOMS
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (PLAN_ID, SR_INSTANCE_ID, BILL_SEQUENCE_ID, KCA_SEQ_ID) IN (
      SELECT
        PLAN_ID,
        SR_INSTANCE_ID,
        BILL_SEQUENCE_ID,
        MAX(KCA_SEQ_ID)
      FROM bec_raw_dl_ext.MSC_BOMS
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        PLAN_ID,
        SR_INSTANCE_ID,
        BILL_SEQUENCE_ID
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'msc_boms'
    )
);