TRUNCATE table bronze_bec_ods_stg.MSC_SUB_INVENTORIES;
INSERT INTO bronze_bec_ods_stg.MSC_SUB_INVENTORIES (
  PLAN_ID,
  ORGANIZATION_ID,
  SUB_INVENTORY_CODE,
  NETTING_TYPE,
  SR_INSTANCE_ID,
  DESCRIPTION,
  REFRESH_NUMBER,
  INVENTORY_ATP_CODE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  INCLUDE_NON_NETTABLE,
  SR_RESOURCE_NAME,
  SR_CUSTOMER_ACCT_ID,
  CONDITION_TYPE,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    PLAN_ID,
    ORGANIZATION_ID,
    SUB_INVENTORY_CODE,
    NETTING_TYPE,
    SR_INSTANCE_ID,
    DESCRIPTION,
    REFRESH_NUMBER,
    INVENTORY_ATP_CODE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    INCLUDE_NON_NETTABLE,
    SR_RESOURCE_NAME,
    SR_CUSTOMER_ACCT_ID,
    CONDITION_TYPE,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.MSC_SUB_INVENTORIES
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(PLAN_ID, 0), COALESCE(SR_INSTANCE_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(SUB_INVENTORY_CODE, 'NA'), KCA_SEQ_ID) IN (
      SELECT
        COALESCE(PLAN_ID, 0) AS PLAN_ID,
        COALESCE(SR_INSTANCE_ID, 0) AS SR_INSTANCE_ID,
        COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
        COALESCE(SUB_INVENTORY_CODE, 'NA') AS SUB_INVENTORY_CODE,
        MAX(KCA_SEQ_ID)
      FROM bec_raw_dl_ext.MSC_SUB_INVENTORIES
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(PLAN_ID, 0),
        COALESCE(SR_INSTANCE_ID, 0),
        COALESCE(ORGANIZATION_ID, 0),
        COALESCE(SUB_INVENTORY_CODE, 'NA')
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'msc_sub_inventories'
    )
);