TRUNCATE table
	table bronze_bec_ods_stg.BOM_STANDARD_OPERATIONS;
INSERT INTO bronze_bec_ods_stg.bom_standard_operations (
  SEQUENCE_NUM,
  LINE_ID,
  OPERATION_TYPE,
  STANDARD_OPERATION_ID,
  OPERATION_CODE,
  ORGANIZATION_ID,
  DEPARTMENT_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  MINIMUM_TRANSFER_QUANTITY,
  COUNT_POINT_TYPE,
  OPERATION_DESCRIPTION,
  OPTION_DEPENDENT_FLAG,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  BACKFLUSH_FLAG,
  WMS_TASK_TYPE,
  INCLUDE_IN_ROLLUP,
  YIELD,
  OPERATION_YIELD_ENABLED,
  SHUTDOWN_TYPE,
  ACTUAL_IPK,
  CRITICAL_TO_QUALITY,
  VALUE_ADDED,
  DEFAULT_SUBINVENTORY,
  DEFAULT_LOCATOR_ID,
  LOWEST_ACCEPTABLE_YIELD,
  USE_ORG_SETTINGS,
  QUEUE_MANDATORY_FLAG,
  RUN_MANDATORY_FLAG,
  TO_MOVE_MANDATORY_FLAG,
  SHOW_NEXT_OP_BY_DEFAULT,
  SHOW_SCRAP_CODE,
  SHOW_LOT_ATTRIB,
  TRACK_MULTIPLE_RES_USAGE_DATES,
  CHECK_SKILL,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    SEQUENCE_NUM,
    LINE_ID,
    OPERATION_TYPE,
    STANDARD_OPERATION_ID,
    OPERATION_CODE,
    ORGANIZATION_ID,
    DEPARTMENT_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    MINIMUM_TRANSFER_QUANTITY,
    COUNT_POINT_TYPE,
    OPERATION_DESCRIPTION,
    OPTION_DEPENDENT_FLAG,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    BACKFLUSH_FLAG,
    WMS_TASK_TYPE,
    INCLUDE_IN_ROLLUP,
    YIELD,
    OPERATION_YIELD_ENABLED,
    SHUTDOWN_TYPE,
    ACTUAL_IPK,
    CRITICAL_TO_QUALITY,
    VALUE_ADDED,
    DEFAULT_SUBINVENTORY,
    DEFAULT_LOCATOR_ID,
    LOWEST_ACCEPTABLE_YIELD,
    USE_ORG_SETTINGS,
    QUEUE_MANDATORY_FLAG,
    RUN_MANDATORY_FLAG,
    TO_MOVE_MANDATORY_FLAG,
    SHOW_NEXT_OP_BY_DEFAULT,
    SHOW_SCRAP_CODE,
    SHOW_LOT_ATTRIB,
    TRACK_MULTIPLE_RES_USAGE_DATES,
    CHECK_SKILL,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.bom_standard_operations
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(LINE_ID, 0), COALESCE(OPERATION_TYPE, 0), COALESCE(STANDARD_OPERATION_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(LINE_ID, 0) AS LINE_ID,
        COALESCE(OPERATION_TYPE, 0) AS OPERATION_TYPE,
        COALESCE(STANDARD_OPERATION_ID, 0) AS STANDARD_OPERATION_ID,
        MAX(kca_seq_id) AS kca_seq_id
      FROM bec_raw_dl_ext.bom_standard_operations
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(LINE_ID, 0),
        COALESCE(OPERATION_TYPE, 0),
        COALESCE(STANDARD_OPERATION_ID, 0)
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'bom_standard_operations'
    )
);