TRUNCATE table bronze_bec_ods_stg.fa_deprn_summary;
INSERT INTO bronze_bec_ods_stg.fa_deprn_summary (
  BOOK_TYPE_CODE,
  ASSET_ID,
  DEPRN_RUN_DATE,
  DEPRN_AMOUNT,
  YTD_DEPRN,
  DEPRN_RESERVE,
  DEPRN_SOURCE_CODE,
  ADJUSTED_COST,
  BONUS_RATE,
  LTD_PRODUCTION,
  PERIOD_COUNTER,
  PRODUCTION,
  REVAL_AMORTIZATION,
  REVAL_AMORTIZATION_BASIS,
  REVAL_DEPRN_EXPENSE,
  REVAL_RESERVE,
  YTD_PRODUCTION,
  YTD_REVAL_DEPRN_EXPENSE,
  PRIOR_FY_EXPENSE,
  BONUS_DEPRN_AMOUNT,
  BONUS_YTD_DEPRN,
  BONUS_DEPRN_RESERVE,
  PRIOR_FY_BONUS_EXPENSE,
  DEPRN_OVERRIDE_FLAG,
  SYSTEM_DEPRN_AMOUNT,
  SYSTEM_BONUS_DEPRN_AMOUNT,
  EVENT_ID,
  DEPRN_RUN_ID,
  DEPRN_ADJUSTMENT_AMOUNT,
  BONUS_DEPRN_ADJUSTMENT_AMOUNT,
  IMPAIRMENT_AMOUNT,
  YTD_IMPAIRMENT,
  IMPAIRMENT_RESERVE,
  CAPITAL_ADJUSTMENT,
  GENERAL_FUND,
  REVAL_LOSS_BALANCE,
  UNREVALUED_COST,
  HISTORICAL_NBV,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    BOOK_TYPE_CODE,
    ASSET_ID,
    DEPRN_RUN_DATE,
    DEPRN_AMOUNT,
    YTD_DEPRN,
    DEPRN_RESERVE,
    DEPRN_SOURCE_CODE,
    ADJUSTED_COST,
    BONUS_RATE,
    LTD_PRODUCTION,
    PERIOD_COUNTER,
    PRODUCTION,
    REVAL_AMORTIZATION,
    REVAL_AMORTIZATION_BASIS,
    REVAL_DEPRN_EXPENSE,
    REVAL_RESERVE,
    YTD_PRODUCTION,
    YTD_REVAL_DEPRN_EXPENSE,
    PRIOR_FY_EXPENSE,
    BONUS_DEPRN_AMOUNT,
    BONUS_YTD_DEPRN,
    BONUS_DEPRN_RESERVE,
    PRIOR_FY_BONUS_EXPENSE,
    DEPRN_OVERRIDE_FLAG,
    SYSTEM_DEPRN_AMOUNT,
    SYSTEM_BONUS_DEPRN_AMOUNT,
    EVENT_ID,
    DEPRN_RUN_ID,
    DEPRN_ADJUSTMENT_AMOUNT,
    BONUS_DEPRN_ADJUSTMENT_AMOUNT,
    IMPAIRMENT_AMOUNT,
    YTD_IMPAIRMENT,
    IMPAIRMENT_RESERVE,
    CAPITAL_ADJUSTMENT,
    GENERAL_FUND,
    REVAL_LOSS_BALANCE,
    UNREVALUED_COST,
    HISTORICAL_NBV,
    KCA_OPERATION,
    kca_seq_id,
    kca_seq_date
  FROM bec_raw_dl_ext.fa_deprn_summary
  WHERE
    kca_operation <> 'DELETE'
    AND COALESCE(kca_seq_id, '') <> ''
    AND (COALESCE(BOOK_TYPE_CODE, 'NA'), COALESCE(ASSET_ID, 0), COALESCE(PERIOD_COUNTER, 0), kca_seq_id) IN (
      SELECT
        COALESCE(BOOK_TYPE_CODE, 'NA') AS BOOK_TYPE_CODE,
        COALESCE(ASSET_ID, 0) AS ASSET_ID,
        COALESCE(PERIOD_COUNTER, 0) AS PERIOD_COUNTER,
        MAX(kca_seq_id)
      FROM bec_raw_dl_ext.fa_deprn_summary
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
      GROUP BY
        COALESCE(BOOK_TYPE_CODE, 'NA'),
        COALESCE(ASSET_ID, 0),
        COALESCE(PERIOD_COUNTER, 0)
    )
    AND kca_seq_date > (
      SELECT
        (
          executebegints - prune_days
        )
      FROM bec_etl_ctrl.batch_ods_info
      WHERE
        ods_table_name = 'fa_deprn_summary'
    )
);