TRUNCATE table
	table bronze_bec_ods_stg.CE_PAYMENT_DOCUMENTS;
INSERT INTO bronze_bec_ods_stg.CE_PAYMENT_DOCUMENTS (
  PAYMENT_DOCUMENT_ID,
  PAYMENT_DOC_CATEGORY,
  PAYMENT_DOCUMENT_NAME,
  PAYMENT_INSTRUCTION_ID,
  INTERNAL_BANK_ACCOUNT_ID,
  PAPER_STOCK_TYPE,
  ATTACHED_REMITTANCE_STUB_FLAG,
  NUMBER_OF_LINES_PER_REMIT_STUB,
  NUMBER_OF_SETUP_DOCUMENTS,
  FORMAT_CODE,
  FIRST_AVAILABLE_DOCUMENT_NUM,
  LAST_AVAILABLE_DOCUMENT_NUMBER,
  LAST_ISSUED_DOCUMENT_NUMBER,
  MANUAL_PAYMENTS_ONLY_FLAG,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  INACTIVE_DATE,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  OBJECT_VERSION_NUMBER,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
)
SELECT
  PAYMENT_DOCUMENT_ID,
  PAYMENT_DOC_CATEGORY,
  PAYMENT_DOCUMENT_NAME,
  PAYMENT_INSTRUCTION_ID,
  INTERNAL_BANK_ACCOUNT_ID,
  PAPER_STOCK_TYPE,
  ATTACHED_REMITTANCE_STUB_FLAG,
  NUMBER_OF_LINES_PER_REMIT_STUB,
  NUMBER_OF_SETUP_DOCUMENTS,
  FORMAT_CODE,
  FIRST_AVAILABLE_DOCUMENT_NUM,
  LAST_AVAILABLE_DOCUMENT_NUMBER,
  LAST_ISSUED_DOCUMENT_NUMBER,
  MANUAL_PAYMENTS_ONLY_FLAG,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  INACTIVE_DATE,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  OBJECT_VERSION_NUMBER,
  KCA_OPERATION,
  kca_seq_id,
  kca_seq_date
FROM bec_raw_dl_ext.CE_PAYMENT_DOCUMENTS
WHERE
  kca_operation <> 'DELETE'
  AND COALESCE(kca_seq_id, '') <> ''
  AND (PAYMENT_DOCUMENT_ID, kca_seq_id) IN (
    SELECT
      PAYMENT_DOCUMENT_ID,
      MAX(kca_seq_id)
    FROM bec_raw_dl_ext.CE_PAYMENT_DOCUMENTS
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') <> ''
    GROUP BY
      PAYMENT_DOCUMENT_ID
  )
  AND kca_seq_date > (
    SELECT
      (
        executebegints - prune_days
      )
    FROM bec_etl_ctrl.batch_ods_info
    WHERE
      ods_table_name = 'ce_payment_documents'
  );