DROP table IF EXISTS silver_bec_ods.MTL_UNIT_TRANSACTIONS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_UNIT_TRANSACTIONS (
  transaction_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  serial_number STRING,
  inventory_item_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  subinventory_code STRING,
  locator_id DECIMAL(15, 0),
  transaction_date TIMESTAMP,
  transaction_source_id DECIMAL(15, 0),
  transaction_source_type_id DECIMAL(15, 0),
  transaction_source_name STRING,
  receipt_issue_type DECIMAL(15, 0),
  customer_id DECIMAL(15, 0),
  ship_id DECIMAL(15, 0),
  serial_attribute_category STRING,
  origination_date TIMESTAMP,
  c_attribute1 STRING,
  c_attribute2 STRING,
  c_attribute3 STRING,
  c_attribute4 STRING,
  c_attribute5 STRING,
  c_attribute6 STRING,
  c_attribute7 STRING,
  c_attribute8 STRING,
  c_attribute9 STRING,
  c_attribute10 STRING,
  c_attribute11 STRING,
  c_attribute12 STRING,
  c_attribute13 STRING,
  c_attribute14 STRING,
  c_attribute15 STRING,
  c_attribute16 STRING,
  c_attribute17 STRING,
  c_attribute18 STRING,
  c_attribute19 STRING,
  c_attribute20 STRING,
  d_attribute1 TIMESTAMP,
  d_attribute2 TIMESTAMP,
  d_attribute3 TIMESTAMP,
  d_attribute4 TIMESTAMP,
  d_attribute5 TIMESTAMP,
  d_attribute6 TIMESTAMP,
  d_attribute7 TIMESTAMP,
  d_attribute8 TIMESTAMP,
  d_attribute9 TIMESTAMP,
  d_attribute10 TIMESTAMP,
  n_attribute1 DECIMAL(15, 0),
  n_attribute2 DECIMAL(15, 0),
  n_attribute3 DECIMAL(15, 0),
  n_attribute4 DECIMAL(15, 0),
  n_attribute5 DECIMAL(15, 0),
  n_attribute6 DECIMAL(15, 0),
  n_attribute7 DECIMAL(15, 0),
  n_attribute8 DECIMAL(15, 0),
  n_attribute9 DECIMAL(15, 0),
  n_attribute10 DECIMAL(15, 0),
  status_id DECIMAL(15, 0),
  territory_code STRING,
  time_since_new DECIMAL(15, 0),
  cycles_since_new DECIMAL(15, 0),
  time_since_overhaul DECIMAL(15, 0),
  cycles_since_overhaul DECIMAL(15, 0),
  time_since_repair DECIMAL(15, 0),
  cycles_since_repair DECIMAL(15, 0),
  time_since_visit DECIMAL(15, 0),
  cycles_since_visit DECIMAL(15, 0),
  time_since_mark DECIMAL(15, 0),
  cycles_since_mark DECIMAL(15, 0),
  number_of_repairs DECIMAL(15, 0),
  product_code STRING,
  product_transaction_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  parent_object_type DECIMAL(15, 0),
  parent_object_id DECIMAL(15, 0),
  parent_object_number STRING,
  parent_item_id DECIMAL(15, 0),
  parent_object_type2 DECIMAL(15, 0),
  parent_object_id2 DECIMAL(15, 0),
  parent_object_number2 STRING,
  c_attribute21 STRING,
  c_attribute22 STRING,
  c_attribute23 STRING,
  c_attribute24 STRING,
  c_attribute25 STRING,
  c_attribute26 STRING,
  c_attribute27 STRING,
  c_attribute28 STRING,
  c_attribute29 STRING,
  c_attribute30 STRING,
  d_attribute11 TIMESTAMP,
  d_attribute12 TIMESTAMP,
  d_attribute13 TIMESTAMP,
  d_attribute14 TIMESTAMP,
  d_attribute15 TIMESTAMP,
  d_attribute16 TIMESTAMP,
  d_attribute17 TIMESTAMP,
  d_attribute18 TIMESTAMP,
  d_attribute19 TIMESTAMP,
  d_attribute20 TIMESTAMP,
  d_attribute21 TIMESTAMP,
  d_attribute22 TIMESTAMP,
  d_attribute23 TIMESTAMP,
  d_attribute24 TIMESTAMP,
  d_attribute25 TIMESTAMP,
  d_attribute26 TIMESTAMP,
  d_attribute27 TIMESTAMP,
  d_attribute28 TIMESTAMP,
  d_attribute29 TIMESTAMP,
  d_attribute30 TIMESTAMP,
  n_attribute11 DECIMAL(15, 0),
  n_attribute12 DECIMAL(15, 0),
  n_attribute13 DECIMAL(15, 0),
  n_attribute14 DECIMAL(15, 0),
  n_attribute15 DECIMAL(15, 0),
  n_attribute16 DECIMAL(15, 0),
  n_attribute17 DECIMAL(15, 0),
  n_attribute18 DECIMAL(15, 0),
  n_attribute19 DECIMAL(15, 0),
  n_attribute20 DECIMAL(15, 0),
  n_attribute21 DECIMAL(15, 0),
  n_attribute22 DECIMAL(15, 0),
  n_attribute23 DECIMAL(15, 0),
  n_attribute24 DECIMAL(15, 0),
  n_attribute25 DECIMAL(15, 0),
  n_attribute26 DECIMAL(15, 0),
  n_attribute27 DECIMAL(15, 0),
  n_attribute28 DECIMAL(15, 0),
  n_attribute29 DECIMAL(15, 0),
  n_attribute30 DECIMAL(15, 0),
  country_of_origin STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_UNIT_TRANSACTIONS (
  transaction_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  serial_number,
  inventory_item_id,
  organization_id,
  subinventory_code,
  locator_id,
  transaction_date,
  transaction_source_id,
  transaction_source_type_id,
  transaction_source_name,
  receipt_issue_type,
  customer_id,
  ship_id,
  serial_attribute_category,
  origination_date,
  c_attribute1,
  c_attribute2,
  c_attribute3,
  c_attribute4,
  c_attribute5,
  c_attribute6,
  c_attribute7,
  c_attribute8,
  c_attribute9,
  c_attribute10,
  c_attribute11,
  c_attribute12,
  c_attribute13,
  c_attribute14,
  c_attribute15,
  c_attribute16,
  c_attribute17,
  c_attribute18,
  c_attribute19,
  c_attribute20,
  d_attribute1,
  d_attribute2,
  d_attribute3,
  d_attribute4,
  d_attribute5,
  d_attribute6,
  d_attribute7,
  d_attribute8,
  d_attribute9,
  d_attribute10,
  n_attribute1,
  n_attribute2,
  n_attribute3,
  n_attribute4,
  n_attribute5,
  n_attribute6,
  n_attribute7,
  n_attribute8,
  n_attribute9,
  n_attribute10,
  status_id,
  territory_code,
  time_since_new,
  cycles_since_new,
  time_since_overhaul,
  cycles_since_overhaul,
  time_since_repair,
  cycles_since_repair,
  time_since_visit,
  cycles_since_visit,
  time_since_mark,
  cycles_since_mark,
  number_of_repairs,
  product_code,
  product_transaction_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  parent_object_type,
  parent_object_id,
  parent_object_number,
  parent_item_id,
  parent_object_type2,
  parent_object_id2,
  parent_object_number2,
  c_attribute21,
  c_attribute22,
  c_attribute23,
  c_attribute24,
  c_attribute25,
  c_attribute26,
  c_attribute27,
  c_attribute28,
  c_attribute29,
  c_attribute30,
  d_attribute11,
  d_attribute12,
  d_attribute13,
  d_attribute14,
  d_attribute15,
  d_attribute16,
  d_attribute17,
  d_attribute18,
  d_attribute19,
  d_attribute20,
  d_attribute21,
  d_attribute22,
  d_attribute23,
  d_attribute24,
  d_attribute25,
  d_attribute26,
  d_attribute27,
  d_attribute28,
  d_attribute29,
  d_attribute30,
  n_attribute11,
  n_attribute12,
  n_attribute13,
  n_attribute14,
  n_attribute15,
  n_attribute16,
  n_attribute17,
  n_attribute18,
  n_attribute19,
  n_attribute20,
  n_attribute21,
  n_attribute22,
  n_attribute23,
  n_attribute24,
  n_attribute25,
  n_attribute26,
  n_attribute27,
  n_attribute28,
  n_attribute29,
  n_attribute30,
  country_of_origin,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    transaction_id,
    last_update_date,
    last_updated_by,
    creation_date,
    created_by,
    last_update_login,
    serial_number,
    inventory_item_id,
    organization_id,
    subinventory_code,
    locator_id,
    transaction_date,
    transaction_source_id,
    transaction_source_type_id,
    transaction_source_name,
    receipt_issue_type,
    customer_id,
    ship_id,
    serial_attribute_category,
    origination_date,
    c_attribute1,
    c_attribute2,
    c_attribute3,
    c_attribute4,
    c_attribute5,
    c_attribute6,
    c_attribute7,
    c_attribute8,
    c_attribute9,
    c_attribute10,
    c_attribute11,
    c_attribute12,
    c_attribute13,
    c_attribute14,
    c_attribute15,
    c_attribute16,
    c_attribute17,
    c_attribute18,
    c_attribute19,
    c_attribute20,
    d_attribute1,
    d_attribute2,
    d_attribute3,
    d_attribute4,
    d_attribute5,
    d_attribute6,
    d_attribute7,
    d_attribute8,
    d_attribute9,
    d_attribute10,
    n_attribute1,
    n_attribute2,
    n_attribute3,
    n_attribute4,
    n_attribute5,
    n_attribute6,
    n_attribute7,
    n_attribute8,
    n_attribute9,
    n_attribute10,
    status_id,
    territory_code,
    time_since_new,
    cycles_since_new,
    time_since_overhaul,
    cycles_since_overhaul,
    time_since_repair,
    cycles_since_repair,
    time_since_visit,
    cycles_since_visit,
    time_since_mark,
    cycles_since_mark,
    number_of_repairs,
    product_code,
    product_transaction_id,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    parent_object_type,
    parent_object_id,
    parent_object_number,
    parent_item_id,
    parent_object_type2,
    parent_object_id2,
    parent_object_number2,
    c_attribute21,
    c_attribute22,
    c_attribute23,
    c_attribute24,
    c_attribute25,
    c_attribute26,
    c_attribute27,
    c_attribute28,
    c_attribute29,
    c_attribute30,
    d_attribute11,
    d_attribute12,
    d_attribute13,
    d_attribute14,
    d_attribute15,
    d_attribute16,
    d_attribute17,
    d_attribute18,
    d_attribute19,
    d_attribute20,
    d_attribute21,
    d_attribute22,
    d_attribute23,
    d_attribute24,
    d_attribute25,
    d_attribute26,
    d_attribute27,
    d_attribute28,
    d_attribute29,
    d_attribute30,
    n_attribute11,
    n_attribute12,
    n_attribute13,
    n_attribute14,
    n_attribute15,
    n_attribute16,
    n_attribute17,
    n_attribute18,
    n_attribute19,
    n_attribute20,
    n_attribute21,
    n_attribute22,
    n_attribute23,
    n_attribute24,
    n_attribute25,
    n_attribute26,
    n_attribute27,
    n_attribute28,
    n_attribute29,
    n_attribute30,
    country_of_origin,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MTL_UNIT_TRANSACTIONS
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_unit_transactions';