DROP TABLE IF EXISTS silver_bec_ods.QP_PRICING_ATTRIBUTES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.QP_PRICING_ATTRIBUTES (
  pricing_attribute_id DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  list_line_id DECIMAL(15, 0),
  excluder_flag STRING,
  accumulate_flag STRING,
  product_attribute_context STRING,
  product_attribute STRING,
  product_attr_value STRING,
  product_uom_code STRING,
  pricing_attribute_context STRING,
  pricing_attribute STRING,
  pricing_attr_value_from STRING,
  pricing_attr_value_to STRING,
  attribute_grouping_no DECIMAL(15, 0),
  product_attribute_datatype STRING,
  pricing_attribute_datatype STRING,
  comparison_operator_code STRING,
  context STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  list_header_id DECIMAL(15, 0),
  pricing_phase_id DECIMAL(15, 0),
  qualification_ind DECIMAL(15, 0),
  pricing_attr_value_from_number DECIMAL(28, 10),
  pricing_attr_value_to_number DECIMAL(28, 10),
  distinct_row_count DECIMAL(28, 10),
  search_ind DECIMAL(28, 10),
  pattern_value_from_positive STRING,
  pattern_value_to_positive STRING,
  pattern_value_from_negative STRING,
  pattern_value_to_negative STRING,
  product_segment_id DECIMAL(15, 0),
  pricing_segment_id DECIMAL(15, 0),
  orig_sys_line_ref STRING,
  orig_sys_pricing_attr_ref STRING,
  orig_sys_header_ref STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.QP_PRICING_ATTRIBUTES (
  pricing_attribute_id,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  list_line_id,
  excluder_flag,
  accumulate_flag,
  product_attribute_context,
  product_attribute,
  product_attr_value,
  product_uom_code,
  pricing_attribute_context,
  pricing_attribute,
  pricing_attr_value_from,
  pricing_attr_value_to,
  attribute_grouping_no,
  product_attribute_datatype,
  pricing_attribute_datatype,
  comparison_operator_code,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  list_header_id,
  pricing_phase_id,
  qualification_ind,
  pricing_attr_value_from_number,
  pricing_attr_value_to_number,
  distinct_row_count,
  search_ind,
  pattern_value_from_positive,
  pattern_value_to_positive,
  pattern_value_from_negative,
  pattern_value_to_negative,
  product_segment_id,
  pricing_segment_id,
  orig_sys_line_ref,
  orig_sys_pricing_attr_ref,
  orig_sys_header_ref,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  pricing_attribute_id,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  list_line_id,
  excluder_flag,
  accumulate_flag,
  product_attribute_context,
  product_attribute,
  product_attr_value,
  product_uom_code,
  pricing_attribute_context,
  pricing_attribute,
  pricing_attr_value_from,
  pricing_attr_value_to,
  attribute_grouping_no,
  product_attribute_datatype,
  pricing_attribute_datatype,
  comparison_operator_code,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  list_header_id,
  pricing_phase_id,
  qualification_ind,
  pricing_attr_value_from_number,
  pricing_attr_value_to_number,
  distinct_row_count,
  search_ind,
  pattern_value_from_positive,
  pattern_value_to_positive,
  pattern_value_from_negative,
  pattern_value_to_negative,
  product_segment_id,
  pricing_segment_id,
  orig_sys_line_ref,
  orig_sys_pricing_attr_ref,
  orig_sys_header_ref,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.QP_PRICING_ATTRIBUTES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'qp_pricing_attributes';