DROP TABLE IF EXISTS silver_bec_ods.IBY_EXTERNAL_PAYEES_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.IBY_EXTERNAL_PAYEES_ALL (
  ext_payee_id DECIMAL(15, 0),
  payee_party_id DECIMAL(15, 0),
  payment_function STRING,
  exclusive_payment_flag STRING,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  object_version_number DECIMAL(15, 0),
  party_site_id DECIMAL(15, 0),
  supplier_site_id DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  org_type STRING,
  default_payment_method_code STRING,
  ece_tp_location_code STRING,
  bank_charge_bearer STRING,
  bank_instruction1_code STRING,
  bank_instruction2_code STRING,
  bank_instruction_details STRING,
  payment_reason_code STRING,
  payment_reason_comments STRING,
  inactive_date TIMESTAMP,
  payment_text_message1 STRING,
  payment_text_message2 STRING,
  payment_text_message3 STRING,
  delivery_channel_code STRING,
  payment_format_code STRING,
  settlement_priority STRING,
  remit_advice_delivery_method STRING,
  remit_advice_email STRING,
  remit_advice_fax STRING,
  service_level_code STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.IBY_EXTERNAL_PAYEES_ALL (
  ext_payee_id,
  payee_party_id,
  payment_function,
  exclusive_payment_flag,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  object_version_number,
  party_site_id,
  supplier_site_id,
  org_id,
  org_type,
  default_payment_method_code,
  ece_tp_location_code,
  bank_charge_bearer,
  bank_instruction1_code,
  bank_instruction2_code,
  bank_instruction_details,
  payment_reason_code,
  payment_reason_comments,
  inactive_date,
  payment_text_message1,
  payment_text_message2,
  payment_text_message3,
  delivery_channel_code,
  payment_format_code,
  settlement_priority,
  remit_advice_delivery_method,
  remit_advice_email,
  remit_advice_fax,
  service_level_code,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  ext_payee_id,
  payee_party_id,
  payment_function,
  exclusive_payment_flag,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  object_version_number,
  party_site_id,
  supplier_site_id,
  org_id,
  org_type,
  default_payment_method_code,
  ece_tp_location_code,
  bank_charge_bearer,
  bank_instruction1_code,
  bank_instruction2_code,
  bank_instruction_details,
  payment_reason_code,
  payment_reason_comments,
  inactive_date,
  payment_text_message1,
  payment_text_message2,
  payment_text_message3,
  delivery_channel_code,
  payment_format_code,
  settlement_priority,
  remit_advice_delivery_method,
  remit_advice_email,
  remit_advice_fax,
  service_level_code,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.IBY_EXTERNAL_PAYEES_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'iby_external_payees_all';