DROP TABLE IF EXISTS silver_bec_ods.MTL_ONHAND_QUANTITIES_DETAIL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_ONHAND_QUANTITIES_DETAIL (
  inventory_item_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  date_received TIMESTAMP,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  primary_transaction_quantity DECIMAL(28, 10),
  subinventory_code STRING,
  revision STRING,
  locator_id DECIMAL(15, 0),
  create_transaction_id DECIMAL(15, 0),
  update_transaction_id DECIMAL(15, 0),
  lot_number STRING,
  orig_date_received TIMESTAMP,
  cost_group_id DECIMAL(15, 0),
  containerized_flag DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  onhand_quantities_id DECIMAL(15, 0),
  organization_type DECIMAL(15, 0),
  owning_organization_id DECIMAL(15, 0),
  owning_tp_type DECIMAL(15, 0),
  planning_organization_id DECIMAL(15, 0),
  planning_tp_type DECIMAL(15, 0),
  transaction_uom_code STRING,
  transaction_quantity DECIMAL(28, 10),
  secondary_uom_code STRING,
  secondary_transaction_quantity DECIMAL(28, 10),
  is_consigned DECIMAL(15, 0),
  lpn_id DECIMAL(15, 0),
  status_id DECIMAL(15, 0),
  mcc_code STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_ONHAND_QUANTITIES_DETAIL (
  inventory_item_id,
  organization_id,
  date_received,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  primary_transaction_quantity,
  subinventory_code,
  revision,
  locator_id,
  create_transaction_id,
  update_transaction_id,
  lot_number,
  orig_date_received,
  cost_group_id,
  containerized_flag,
  project_id,
  task_id,
  onhand_quantities_id,
  organization_type,
  owning_organization_id,
  owning_tp_type,
  planning_organization_id,
  planning_tp_type,
  transaction_uom_code,
  transaction_quantity,
  secondary_uom_code,
  secondary_transaction_quantity,
  is_consigned,
  lpn_id,
  status_id,
  mcc_code,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  inventory_item_id,
  organization_id,
  date_received,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  primary_transaction_quantity,
  subinventory_code,
  revision,
  locator_id,
  create_transaction_id,
  update_transaction_id,
  lot_number,
  orig_date_received,
  cost_group_id,
  containerized_flag,
  project_id,
  task_id,
  onhand_quantities_id,
  organization_type,
  owning_organization_id,
  owning_tp_type,
  planning_organization_id,
  planning_tp_type,
  transaction_uom_code,
  transaction_quantity,
  secondary_uom_code,
  secondary_transaction_quantity,
  is_consigned,
  lpn_id,
  status_id,
  mcc_code,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_ONHAND_QUANTITIES_DETAIL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_onhand_quantities_detail';