DROP TABLE IF EXISTS silver_bec_ods.ap_invoice_distributions_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_invoice_distributions_all (
  accounting_date TIMESTAMP,
  accounting_event_id DECIMAL(15, 0),
  accrual_posted_flag STRING,
  accts_pay_code_combination_id DECIMAL(15, 0),
  adjustment_reason STRING,
  amount DECIMAL(28, 10),
  amount_at_prepay_pay_xrate DECIMAL(28, 10),
  amount_at_prepay_xrate DECIMAL(28, 10),
  amount_encumbered DECIMAL(28, 10),
  amount_includes_tax_flag STRING,
  amount_to_post DECIMAL(28, 10),
  amount_variance DECIMAL(28, 10),
  asset_book_type_code STRING,
  asset_category_id DECIMAL(15, 0),
  assets_addition_flag STRING,
  assets_tracking_flag STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  award_id DECIMAL(15, 0),
  awt_flag STRING,
  awt_gross_amount DECIMAL(28, 10),
  awt_group_id DECIMAL(15, 0),
  awt_invoice_id DECIMAL(15, 0),
  awt_invoice_payment_id DECIMAL(15, 0),
  awt_origin_group_id DECIMAL(15, 0),
  awt_related_id DECIMAL(15, 0),
  awt_tax_rate_id DECIMAL(15, 0),
  awt_withheld_amt DECIMAL(28, 10),
  base_amount DECIMAL(28, 10),
  base_amount_encumbered DECIMAL(28, 10),
  base_amount_to_post DECIMAL(28, 10),
  base_amount_variance DECIMAL(28, 10),
  base_invoice_price_variance DECIMAL(28, 10),
  base_quantity_variance DECIMAL(28, 10),
  batch_id DECIMAL(15, 0),
  bc_event_id DECIMAL(15, 0),
  cancellation_flag STRING,
  cancelled_flag STRING,
  cash_basis_final_app_rounding DECIMAL(28, 10),
  cash_je_batch_id DECIMAL(15, 0),
  cash_posted_flag STRING,
  cc_reversal_flag STRING,
  charge_applicable_to_dist_id DECIMAL(15, 0),
  company_prepaid_invoice_id DECIMAL(15, 0),
  corrected_invoice_dist_id DECIMAL(15, 0),
  corrected_quantity DECIMAL(28, 10),
  country_of_supply STRING,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  credit_card_trx_id DECIMAL(15, 0),
  daily_amount DECIMAL(28, 10),
  description STRING,
  detail_tax_dist_id DECIMAL(15, 0),
  dist_code_combination_id DECIMAL(15, 0),
  dist_match_type STRING,
  distribution_class STRING,
  distribution_line_number DECIMAL(15, 0),
  earliest_settlement_date TIMESTAMP,
  encumbered_flag STRING,
  end_expense_date TIMESTAMP,
  exchange_date TIMESTAMP,
  exchange_rate DECIMAL(28, 10),
  exchange_rate_type STRING,
  exchange_rate_variance DECIMAL(28, 10),
  expenditure_item_date TIMESTAMP,
  expenditure_organization_id DECIMAL(15, 0),
  expenditure_type STRING,
  expense_group STRING,
  extra_po_erv DECIMAL(28, 10),
  final_application_rounding DECIMAL(28, 10),
  final_match_flag STRING,
  final_payment_rounding DECIMAL(28, 10),
  final_release_rounding DECIMAL(28, 10),
  fully_paid_acctd_flag STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute2 STRING,
  global_attribute20 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  gms_burdenable_raw_cost DECIMAL(22, 5),
  historical_flag STRING,
  income_tax_region STRING,
  intended_use STRING,
  inventory_transfer_status STRING,
  invoice_distribution_id DECIMAL(15, 0),
  invoice_id DECIMAL(15, 0),
  invoice_includes_prepay_flag STRING,
  invoice_line_number DECIMAL(28, 10),
  invoice_price_variance DECIMAL(28, 10),
  je_batch_id DECIMAL(15, 0),
  justification STRING,
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  line_group_number DECIMAL(15, 0),
  line_type_lookup_code STRING,
  match_status_flag STRING,
  matched_uom_lookup_code STRING,
  merchant_document_number STRING,
  merchant_name STRING,
  merchant_reference STRING,
  merchant_tax_reg_number STRING,
  merchant_taxpayer_id STRING,
  mrc_accrual_posted_flag STRING,
  mrc_amount STRING,
  mrc_amount_to_post STRING,
  mrc_base_amount STRING,
  mrc_base_amount_to_post STRING,
  mrc_base_inv_price_variance STRING,
  mrc_cash_je_batch_id STRING,
  mrc_cash_posted_flag STRING,
  mrc_dist_code_combination_id STRING,
  mrc_exchange_date STRING,
  mrc_exchange_rate STRING,
  mrc_exchange_rate_type STRING,
  mrc_exchange_rate_variance STRING,
  mrc_je_batch_id STRING,
  mrc_posted_amount STRING,
  mrc_posted_base_amount STRING,
  mrc_posted_flag STRING,
  mrc_program_application_id STRING,
  mrc_program_id STRING,
  mrc_program_update_date STRING,
  mrc_rate_var_ccid STRING,
  mrc_receipt_conversion_rate STRING,
  mrc_request_id STRING,
  old_dist_line_number DECIMAL(15, 0),
  old_distribution_id DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  other_invoice_id DECIMAL(15, 0),
  pa_addition_flag STRING,
  pa_cc_ar_invoice_id DECIMAL(15, 0),
  pa_cc_ar_invoice_line_num DECIMAL(15, 0),
  pa_cc_processed_code STRING,
  pa_cmt_xface_flag STRING,
  pa_quantity DECIMAL(22, 5),
  packet_id DECIMAL(15, 0),
  parent_invoice_id DECIMAL(15, 0),
  parent_reversal_id DECIMAL(15, 0),
  pay_awt_group_id DECIMAL(15, 0),
  period_name STRING,
  po_distribution_id DECIMAL(15, 0),
  posted_amount DECIMAL(28, 10),
  posted_base_amount DECIMAL(28, 10),
  posted_flag STRING,
  prepay_amount_remaining DECIMAL(28, 10),
  prepay_distribution_id DECIMAL(15, 0),
  prepay_tax_diff_amount DECIMAL(28, 10),
  prepay_tax_parent_id DECIMAL(15, 0),
  price_adjustment_flag STRING,
  price_correct_inv_id DECIMAL(15, 0),
  price_correct_qty DECIMAL(28, 10),
  price_var_code_combination_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  project_accounting_context STRING,
  project_id DECIMAL(15, 0),
  quantity_invoiced DECIMAL(28, 10),
  quantity_unencumbered DECIMAL(28, 10),
  quantity_variance DECIMAL(28, 10),
  rate_var_code_combination_id DECIMAL(15, 0),
  rcv_charge_addition_flag STRING,
  rcv_transaction_id DECIMAL(15, 0),
  rec_nrec_rate DECIMAL(28, 10),
  receipt_conversion_rate DECIMAL(28, 10),
  receipt_currency_amount DECIMAL(28, 10),
  receipt_currency_code STRING,
  receipt_missing_flag STRING,
  receipt_required_flag STRING,
  receipt_verified_flag STRING,
  recovery_rate_code STRING,
  recovery_rate_id DECIMAL(15, 0),
  recovery_rate_name STRING,
  recovery_type_code STRING,
  recurring_payment_id DECIMAL(15, 0),
  reference_1 STRING,
  reference_2 STRING,
  related_id DECIMAL(15, 0),
  related_retainage_dist_id DECIMAL(15, 0),
  release_inv_dist_derived_from DECIMAL(15, 0),
  req_distribution_id DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  retained_amount_remaining DECIMAL(28, 10),
  retained_invoice_dist_id DECIMAL(15, 0),
  reversal_flag STRING,
  root_distribution_id DECIMAL(15, 0),
  rounding_amt DECIMAL(28, 10),
  set_of_books_id DECIMAL(15, 0),
  start_expense_date TIMESTAMP,
  stat_amount DECIMAL(28, 10),
  summary_tax_line_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  tax_already_distributed_flag STRING,
  tax_calculated_flag STRING,
  tax_code_id DECIMAL(15, 0),
  tax_code_override_flag STRING,
  tax_recoverable_flag STRING,
  tax_recovery_override_flag STRING,
  tax_recovery_rate DECIMAL(28, 10),
  taxable_amount DECIMAL(28, 10),
  taxable_base_amount DECIMAL(28, 10),
  total_dist_amount DECIMAL(28, 10),
  total_dist_base_amount DECIMAL(28, 10),
  type_1099 STRING,
  unit_price DECIMAL(28, 10),
  upgrade_base_posted_amt DECIMAL(28, 10),
  upgrade_posted_amt DECIMAL(28, 10),
  ussgl_transaction_code STRING,
  ussgl_trx_code_context STRING,
  vat_code STRING,
  web_parameter_id DECIMAL(15, 0),
  withholding_tax_code_id DECIMAL(15, 0),
  xinv_parent_reversal_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_invoice_distributions_all (
  accounting_date,
  accounting_event_id,
  accrual_posted_flag,
  accts_pay_code_combination_id,
  adjustment_reason,
  amount,
  amount_at_prepay_pay_xrate,
  amount_at_prepay_xrate,
  amount_encumbered,
  amount_includes_tax_flag,
  amount_to_post,
  amount_variance,
  asset_book_type_code,
  asset_category_id,
  assets_addition_flag,
  assets_tracking_flag,
  attribute_category,
  attribute1,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  award_id,
  awt_flag,
  awt_gross_amount,
  awt_group_id,
  awt_invoice_id,
  awt_invoice_payment_id,
  awt_origin_group_id,
  awt_related_id,
  awt_tax_rate_id,
  AWT_WITHHELD_AMT,
  base_amount,
  base_amount_encumbered,
  base_amount_to_post,
  base_amount_variance,
  base_invoice_price_variance,
  base_quantity_variance,
  batch_id,
  bc_event_id,
  cancellation_flag,
  cancelled_flag,
  cash_basis_final_app_rounding,
  cash_je_batch_id,
  cash_posted_flag,
  cc_reversal_flag,
  charge_applicable_to_dist_id,
  company_prepaid_invoice_id,
  corrected_invoice_dist_id,
  corrected_quantity,
  country_of_supply,
  created_by,
  creation_date,
  credit_card_trx_id,
  daily_amount,
  description,
  detail_tax_dist_id,
  dist_code_combination_id,
  dist_match_type,
  distribution_class,
  distribution_line_number,
  earliest_settlement_date,
  encumbered_flag,
  end_expense_date,
  exchange_date,
  exchange_rate,
  exchange_rate_type,
  exchange_rate_variance,
  expenditure_item_date,
  expenditure_organization_id,
  expenditure_type,
  expense_group,
  extra_po_erv,
  final_application_rounding,
  final_match_flag,
  final_payment_rounding,
  final_release_rounding,
  fully_paid_acctd_flag,
  global_attribute_category,
  global_attribute1,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute2,
  global_attribute20,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  gms_burdenable_raw_cost,
  historical_flag,
  income_tax_region,
  intended_use,
  inventory_transfer_status,
  invoice_distribution_id,
  invoice_id,
  invoice_includes_prepay_flag,
  invoice_line_number,
  invoice_price_variance,
  je_batch_id,
  justification,
  last_update_date,
  last_update_login,
  last_updated_by,
  line_group_number,
  line_type_lookup_code,
  match_status_flag,
  matched_uom_lookup_code,
  merchant_document_number,
  merchant_name,
  merchant_reference,
  merchant_tax_reg_number,
  merchant_taxpayer_id,
  mrc_accrual_posted_flag,
  mrc_amount,
  mrc_amount_to_post,
  mrc_base_amount,
  mrc_base_amount_to_post,
  mrc_base_inv_price_variance,
  mrc_cash_je_batch_id,
  mrc_cash_posted_flag,
  mrc_dist_code_combination_id,
  mrc_exchange_date,
  mrc_exchange_rate,
  mrc_exchange_rate_type,
  mrc_exchange_rate_variance,
  mrc_je_batch_id,
  mrc_posted_amount,
  mrc_posted_base_amount,
  mrc_posted_flag,
  mrc_program_application_id,
  mrc_program_id,
  mrc_program_update_date,
  mrc_rate_var_ccid,
  mrc_receipt_conversion_rate,
  mrc_request_id,
  old_dist_line_number,
  old_distribution_id,
  org_id,
  other_invoice_id,
  pa_addition_flag,
  pa_cc_ar_invoice_id,
  pa_cc_ar_invoice_line_num,
  pa_cc_processed_code,
  pa_cmt_xface_flag,
  pa_quantity,
  packet_id,
  parent_invoice_id,
  parent_reversal_id,
  pay_awt_group_id,
  period_name,
  po_distribution_id,
  posted_amount,
  posted_base_amount,
  posted_flag,
  prepay_amount_remaining,
  prepay_distribution_id,
  prepay_tax_diff_amount,
  prepay_tax_parent_id,
  price_adjustment_flag,
  price_correct_inv_id,
  price_correct_qty,
  price_var_code_combination_id,
  program_application_id,
  program_id,
  program_update_date,
  project_accounting_context,
  project_id,
  quantity_invoiced,
  quantity_unencumbered,
  quantity_variance,
  rate_var_code_combination_id,
  rcv_charge_addition_flag,
  rcv_transaction_id,
  rec_nrec_rate,
  receipt_conversion_rate,
  receipt_currency_amount,
  receipt_currency_code,
  receipt_missing_flag,
  receipt_required_flag,
  receipt_verified_flag,
  recovery_rate_code,
  recovery_rate_id,
  recovery_rate_name,
  recovery_type_code,
  recurring_payment_id,
  reference_1,
  reference_2,
  related_id,
  related_retainage_dist_id,
  release_inv_dist_derived_from,
  req_distribution_id,
  request_id,
  retained_amount_remaining,
  retained_invoice_dist_id,
  reversal_flag,
  root_distribution_id,
  rounding_amt,
  set_of_books_id,
  start_expense_date,
  stat_amount,
  summary_tax_line_id,
  task_id,
  tax_already_distributed_flag,
  tax_calculated_flag,
  tax_code_id,
  tax_code_override_flag,
  tax_recoverable_flag,
  tax_recovery_override_flag,
  tax_recovery_rate,
  taxable_amount,
  taxable_base_amount,
  total_dist_amount,
  total_dist_base_amount,
  type_1099,
  unit_price,
  upgrade_base_posted_amt,
  upgrade_posted_amt,
  ussgl_transaction_code,
  ussgl_trx_code_context,
  vat_code,
  web_parameter_id,
  withholding_tax_code_id,
  xinv_parent_reversal_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  kca_seq_date
)
(
  SELECT
    accounting_date,
    accounting_event_id,
    accrual_posted_flag,
    accts_pay_code_combination_id,
    adjustment_reason,
    amount,
    amount_at_prepay_pay_xrate,
    amount_at_prepay_xrate,
    amount_encumbered,
    amount_includes_tax_flag,
    amount_to_post,
    amount_variance,
    asset_book_type_code,
    asset_category_id,
    assets_addition_flag,
    assets_tracking_flag,
    attribute_category,
    attribute1,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    award_id,
    awt_flag,
    awt_gross_amount,
    awt_group_id,
    awt_invoice_id,
    awt_invoice_payment_id,
    awt_origin_group_id,
    awt_related_id,
    awt_tax_rate_id,
    AWT_WITHHELD_AMT,
    base_amount,
    base_amount_encumbered,
    base_amount_to_post,
    base_amount_variance,
    base_invoice_price_variance,
    base_quantity_variance,
    batch_id,
    bc_event_id,
    cancellation_flag,
    cancelled_flag,
    cash_basis_final_app_rounding,
    cash_je_batch_id,
    cash_posted_flag,
    cc_reversal_flag,
    charge_applicable_to_dist_id,
    company_prepaid_invoice_id,
    corrected_invoice_dist_id,
    corrected_quantity,
    country_of_supply,
    created_by,
    creation_date,
    credit_card_trx_id,
    daily_amount,
    description,
    detail_tax_dist_id,
    dist_code_combination_id,
    dist_match_type,
    distribution_class,
    distribution_line_number,
    earliest_settlement_date,
    encumbered_flag,
    end_expense_date,
    exchange_date,
    exchange_rate,
    exchange_rate_type,
    exchange_rate_variance,
    expenditure_item_date,
    expenditure_organization_id,
    expenditure_type,
    expense_group,
    extra_po_erv,
    final_application_rounding,
    final_match_flag,
    final_payment_rounding,
    final_release_rounding,
    fully_paid_acctd_flag,
    global_attribute_category,
    global_attribute1,
    global_attribute10,
    global_attribute11,
    global_attribute12,
    global_attribute13,
    global_attribute14,
    global_attribute15,
    global_attribute16,
    global_attribute17,
    global_attribute18,
    global_attribute19,
    global_attribute2,
    global_attribute20,
    global_attribute3,
    global_attribute4,
    global_attribute5,
    global_attribute6,
    global_attribute7,
    global_attribute8,
    global_attribute9,
    gms_burdenable_raw_cost,
    historical_flag,
    income_tax_region,
    intended_use,
    inventory_transfer_status,
    invoice_distribution_id,
    invoice_id,
    invoice_includes_prepay_flag,
    invoice_line_number,
    invoice_price_variance,
    je_batch_id,
    justification,
    last_update_date,
    last_update_login,
    last_updated_by,
    line_group_number,
    line_type_lookup_code,
    match_status_flag,
    matched_uom_lookup_code,
    merchant_document_number,
    merchant_name,
    merchant_reference,
    merchant_tax_reg_number,
    merchant_taxpayer_id,
    mrc_accrual_posted_flag,
    mrc_amount,
    mrc_amount_to_post,
    mrc_base_amount,
    mrc_base_amount_to_post,
    mrc_base_inv_price_variance,
    mrc_cash_je_batch_id,
    mrc_cash_posted_flag,
    mrc_dist_code_combination_id,
    mrc_exchange_date,
    mrc_exchange_rate,
    mrc_exchange_rate_type,
    mrc_exchange_rate_variance,
    mrc_je_batch_id,
    mrc_posted_amount,
    mrc_posted_base_amount,
    mrc_posted_flag,
    mrc_program_application_id,
    mrc_program_id,
    mrc_program_update_date,
    mrc_rate_var_ccid,
    mrc_receipt_conversion_rate,
    mrc_request_id,
    old_dist_line_number,
    old_distribution_id,
    org_id,
    other_invoice_id,
    pa_addition_flag,
    pa_cc_ar_invoice_id,
    pa_cc_ar_invoice_line_num,
    pa_cc_processed_code,
    pa_cmt_xface_flag,
    pa_quantity,
    packet_id,
    parent_invoice_id,
    parent_reversal_id,
    pay_awt_group_id,
    period_name,
    po_distribution_id,
    posted_amount,
    posted_base_amount,
    posted_flag,
    prepay_amount_remaining,
    prepay_distribution_id,
    prepay_tax_diff_amount,
    prepay_tax_parent_id,
    price_adjustment_flag,
    price_correct_inv_id,
    price_correct_qty,
    price_var_code_combination_id,
    program_application_id,
    program_id,
    program_update_date,
    project_accounting_context,
    project_id,
    quantity_invoiced,
    quantity_unencumbered,
    quantity_variance,
    rate_var_code_combination_id,
    rcv_charge_addition_flag,
    rcv_transaction_id,
    rec_nrec_rate,
    receipt_conversion_rate,
    receipt_currency_amount,
    receipt_currency_code,
    receipt_missing_flag,
    receipt_required_flag,
    receipt_verified_flag,
    recovery_rate_code,
    recovery_rate_id,
    recovery_rate_name,
    recovery_type_code,
    recurring_payment_id,
    reference_1,
    reference_2,
    related_id,
    related_retainage_dist_id,
    release_inv_dist_derived_from,
    req_distribution_id,
    request_id,
    retained_amount_remaining,
    retained_invoice_dist_id,
    reversal_flag,
    root_distribution_id,
    rounding_amt,
    set_of_books_id,
    start_expense_date,
    stat_amount,
    summary_tax_line_id,
    task_id,
    tax_already_distributed_flag,
    tax_calculated_flag,
    tax_code_id,
    tax_code_override_flag,
    tax_recoverable_flag,
    tax_recovery_override_flag,
    tax_recovery_rate,
    taxable_amount,
    taxable_base_amount,
    total_dist_amount,
    total_dist_base_amount,
    type_1099,
    unit_price,
    upgrade_base_posted_amt,
    upgrade_posted_amt,
    ussgl_transaction_code,
    ussgl_trx_code_context,
    vat_code,
    web_parameter_id,
    withholding_tax_code_id,
    xinv_parent_reversal_id,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.ap_invoice_distributions_all
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_invoice_distributions_all';