DROP TABLE IF EXISTS silver_bec_ods.OE_ORDER_HEADERS_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.OE_ORDER_HEADERS_ALL (
  header_id DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  order_type_id DECIMAL(15, 0),
  order_number DECIMAL(15, 0),
  version_number DECIMAL(15, 0),
  expiration_date TIMESTAMP,
  order_source_id DECIMAL(15, 0),
  source_document_type_id DECIMAL(15, 0),
  orig_sys_document_ref STRING,
  source_document_id DECIMAL(15, 0),
  ordered_date TIMESTAMP,
  request_date TIMESTAMP,
  pricing_date TIMESTAMP,
  shipment_priority_code STRING,
  demand_class_code STRING,
  price_list_id DECIMAL(15, 0),
  tax_exempt_flag STRING,
  tax_exempt_number STRING,
  tax_exempt_reason_code STRING,
  conversion_rate DECIMAL(28, 10),
  conversion_type_code STRING,
  conversion_rate_date TIMESTAMP,
  partial_shipments_allowed STRING,
  ship_tolerance_above DECIMAL(28, 10),
  ship_tolerance_below DECIMAL(28, 10),
  transactional_curr_code STRING,
  agreement_id DECIMAL(15, 0),
  tax_point_code STRING,
  cust_po_number STRING,
  invoicing_rule_id DECIMAL(15, 0),
  accounting_rule_id DECIMAL(15, 0),
  payment_term_id DECIMAL(15, 0),
  shipping_method_code STRING,
  freight_carrier_code STRING,
  fob_point_code STRING,
  freight_terms_code STRING,
  sold_from_org_id DECIMAL(15, 0),
  sold_to_org_id DECIMAL(15, 0),
  ship_from_org_id DECIMAL(15, 0),
  ship_to_org_id DECIMAL(15, 0),
  invoice_to_org_id DECIMAL(15, 0),
  deliver_to_org_id DECIMAL(15, 0),
  sold_to_contact_id DECIMAL(15, 0),
  ship_to_contact_id DECIMAL(15, 0),
  invoice_to_contact_id DECIMAL(15, 0),
  deliver_to_contact_id DECIMAL(36, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  context STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  cancelled_flag STRING,
  open_flag STRING,
  booked_flag STRING,
  salesrep_id DECIMAL(15, 0),
  return_reason_code STRING,
  order_date_type_code STRING,
  earliest_schedule_limit DECIMAL(15, 0),
  latest_schedule_limit DECIMAL(15, 0),
  payment_type_code STRING,
  payment_amount DECIMAL(28, 10),
  check_number STRING,
  credit_card_code STRING,
  credit_card_holder_name STRING,
  credit_card_number STRING,
  credit_card_expiration_date TIMESTAMP,
  credit_card_approval_code STRING,
  sales_channel_code STRING,
  first_ack_code STRING,
  first_ack_date TIMESTAMP,
  last_ack_code STRING,
  last_ack_date TIMESTAMP,
  order_category_code STRING,
  change_sequence STRING,
  drop_ship_flag STRING,
  customer_payment_term_id DECIMAL(15, 0),
  shipping_instructions STRING,
  packing_instructions STRING,
  tp_context STRING,
  tp_attribute1 STRING,
  tp_attribute2 STRING,
  tp_attribute3 STRING,
  tp_attribute4 STRING,
  tp_attribute5 STRING,
  tp_attribute6 STRING,
  tp_attribute7 STRING,
  tp_attribute8 STRING,
  tp_attribute9 STRING,
  tp_attribute10 STRING,
  tp_attribute11 STRING,
  tp_attribute12 STRING,
  tp_attribute13 STRING,
  tp_attribute14 STRING,
  tp_attribute15 STRING,
  flow_status_code STRING,
  marketing_source_code_id DECIMAL(15, 0),
  credit_card_approval_date TIMESTAMP,
  upgraded_flag STRING,
  customer_preference_set_code STRING,
  booked_date TIMESTAMP,
  lock_control DECIMAL(15, 0),
  price_request_code STRING,
  batch_id DECIMAL(15, 0),
  xml_message_id DECIMAL(15, 0),
  accounting_rule_duration DECIMAL(15, 0),
  attribute16 STRING,
  attribute17 STRING,
  attribute18 STRING,
  attribute19 STRING,
  attribute20 STRING,
  blanket_number DECIMAL(15, 0),
  sales_document_type_code STRING,
  sold_to_phone_id DECIMAL(15, 0),
  fulfillment_set_name STRING,
  line_set_name STRING,
  default_fulfillment_set STRING,
  transaction_phase_code STRING,
  sales_document_name STRING,
  quote_number DECIMAL(15, 0),
  quote_date TIMESTAMP,
  user_status_code STRING,
  draft_submitted_flag STRING,
  source_document_version_number DECIMAL(15, 0),
  sold_to_site_use_id DECIMAL(15, 0),
  supplier_signature STRING,
  supplier_signature_date TIMESTAMP,
  customer_signature STRING,
  customer_signature_date TIMESTAMP,
  minisite_id DECIMAL(15, 0),
  end_customer_id DECIMAL(15, 0),
  end_customer_contact_id DECIMAL(15, 0),
  end_customer_site_use_id DECIMAL(15, 0),
  ib_owner STRING,
  ib_current_location STRING,
  ib_installed_at_location STRING,
  order_firmed_date TIMESTAMP,
  inst_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.OE_ORDER_HEADERS_ALL (
  header_id,
  org_id,
  order_type_id,
  order_number,
  version_number,
  expiration_date,
  order_source_id,
  source_document_type_id,
  orig_sys_document_ref,
  source_document_id,
  ordered_date,
  request_date,
  pricing_date,
  shipment_priority_code,
  demand_class_code,
  price_list_id,
  tax_exempt_flag,
  tax_exempt_number,
  tax_exempt_reason_code,
  conversion_rate,
  conversion_type_code,
  conversion_rate_date,
  partial_shipments_allowed,
  ship_tolerance_above,
  ship_tolerance_below,
  transactional_curr_code,
  agreement_id,
  tax_point_code,
  cust_po_number,
  invoicing_rule_id,
  accounting_rule_id,
  payment_term_id,
  shipping_method_code,
  freight_carrier_code,
  fob_point_code,
  freight_terms_code,
  sold_from_org_id,
  sold_to_org_id,
  ship_from_org_id,
  ship_to_org_id,
  invoice_to_org_id,
  deliver_to_org_id,
  sold_to_contact_id,
  ship_to_contact_id,
  invoice_to_contact_id,
  deliver_to_contact_id,
  creation_date,
  created_by,
  last_updated_by,
  last_update_date,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  cancelled_flag,
  open_flag,
  booked_flag,
  salesrep_id,
  return_reason_code,
  order_date_type_code,
  earliest_schedule_limit,
  latest_schedule_limit,
  payment_type_code,
  payment_amount,
  check_number,
  credit_card_code,
  credit_card_holder_name,
  credit_card_number,
  credit_card_expiration_date,
  credit_card_approval_code,
  sales_channel_code,
  first_ack_code,
  first_ack_date,
  last_ack_code,
  last_ack_date,
  order_category_code,
  change_sequence,
  drop_ship_flag,
  customer_payment_term_id,
  shipping_instructions,
  packing_instructions,
  tp_context,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  flow_status_code,
  marketing_source_code_id,
  credit_card_approval_date,
  upgraded_flag,
  customer_preference_set_code,
  booked_date,
  lock_control,
  price_request_code,
  batch_id,
  xml_message_id,
  accounting_rule_duration,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  blanket_number,
  sales_document_type_code,
  sold_to_phone_id,
  fulfillment_set_name,
  line_set_name,
  default_fulfillment_set,
  transaction_phase_code,
  sales_document_name,
  quote_number,
  quote_date,
  user_status_code,
  draft_submitted_flag,
  source_document_version_number,
  sold_to_site_use_id,
  supplier_signature,
  supplier_signature_date,
  customer_signature,
  customer_signature_date,
  minisite_id,
  end_customer_id,
  end_customer_contact_id,
  end_customer_site_use_id,
  ib_owner,
  ib_current_location,
  ib_installed_at_location,
  order_firmed_date,
  inst_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  header_id,
  org_id,
  order_type_id,
  order_number,
  version_number,
  expiration_date,
  order_source_id,
  source_document_type_id,
  orig_sys_document_ref,
  source_document_id,
  ordered_date,
  request_date,
  pricing_date,
  shipment_priority_code,
  demand_class_code,
  price_list_id,
  tax_exempt_flag,
  tax_exempt_number,
  tax_exempt_reason_code,
  conversion_rate,
  conversion_type_code,
  conversion_rate_date,
  partial_shipments_allowed,
  ship_tolerance_above,
  ship_tolerance_below,
  transactional_curr_code,
  agreement_id,
  tax_point_code,
  cust_po_number,
  invoicing_rule_id,
  accounting_rule_id,
  payment_term_id,
  shipping_method_code,
  freight_carrier_code,
  fob_point_code,
  freight_terms_code,
  sold_from_org_id,
  sold_to_org_id,
  ship_from_org_id,
  ship_to_org_id,
  invoice_to_org_id,
  deliver_to_org_id,
  sold_to_contact_id,
  ship_to_contact_id,
  invoice_to_contact_id,
  deliver_to_contact_id,
  creation_date,
  created_by,
  last_updated_by,
  last_update_date,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  cancelled_flag,
  open_flag,
  booked_flag,
  salesrep_id,
  return_reason_code,
  order_date_type_code,
  earliest_schedule_limit,
  latest_schedule_limit,
  payment_type_code,
  payment_amount,
  check_number,
  credit_card_code,
  credit_card_holder_name,
  credit_card_number,
  credit_card_expiration_date,
  credit_card_approval_code,
  sales_channel_code,
  first_ack_code,
  first_ack_date,
  last_ack_code,
  last_ack_date,
  order_category_code,
  change_sequence,
  drop_ship_flag,
  customer_payment_term_id,
  shipping_instructions,
  packing_instructions,
  tp_context,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  flow_status_code,
  marketing_source_code_id,
  credit_card_approval_date,
  upgraded_flag,
  customer_preference_set_code,
  booked_date,
  lock_control,
  price_request_code,
  batch_id,
  xml_message_id,
  accounting_rule_duration,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  blanket_number,
  sales_document_type_code,
  sold_to_phone_id,
  fulfillment_set_name,
  line_set_name,
  default_fulfillment_set,
  transaction_phase_code,
  sales_document_name,
  quote_number,
  quote_date,
  user_status_code,
  draft_submitted_flag,
  source_document_version_number,
  sold_to_site_use_id,
  supplier_signature,
  supplier_signature_date,
  customer_signature,
  customer_signature_date,
  minisite_id,
  end_customer_id,
  end_customer_contact_id,
  end_customer_site_use_id,
  ib_owner,
  ib_current_location,
  ib_installed_at_location,
  order_firmed_date,
  inst_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.OE_ORDER_HEADERS_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'oe_order_headers_all';