DROP TABLE IF EXISTS silver_bec_ods.CST_COST_HISTORY_V;
CREATE TABLE IF NOT EXISTS silver_bec_ods.CST_COST_HISTORY_V (
  cost_update_id DECIMAL(15, 0),
  cost_update_id_join DECIMAL(15, 0),
  count DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  item_description STRING,
  padded_item_number STRING,
  uom STRING,
  update_description STRING,
  organization_id DECIMAL(15, 0),
  update_date TIMESTAMP,
  standard_cost DECIMAL(28, 10),
  inv_adj_val_c DECIMAL(28, 10),
  intransit_adj_val_c DECIMAL(28, 10),
  wip_adj_val_c DECIMAL(28, 10),
  inv_adj_qty_c DECIMAL(28, 10),
  intransit_adj_qty_c DECIMAL(28, 10),
  wip_adj_qty_c DECIMAL(28, 10),
  material DECIMAL(28, 10),
  material_overhead DECIMAL(28, 10),
  resource_cost DECIMAL(28, 10),
  outside_processing DECIMAL(28, 10),
  overhead DECIMAL(28, 10),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.CST_COST_HISTORY_V (
  cost_update_id,
  cost_update_id_join,
  count,
  inventory_item_id,
  item_description,
  padded_item_number,
  uom,
  update_description,
  organization_id,
  update_date,
  standard_cost,
  inv_adj_val_c,
  intransit_adj_val_c,
  wip_adj_val_c,
  inv_adj_qty_c,
  intransit_adj_qty_c,
  wip_adj_qty_c,
  material,
  material_overhead,
  resource_cost,
  outside_processing,
  overhead,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cost_update_id,
  cost_update_id_join,
  count,
  inventory_item_id,
  item_description,
  padded_item_number,
  uom,
  update_description,
  organization_id,
  update_date,
  standard_cost,
  inv_adj_val_c,
  intransit_adj_val_c,
  wip_adj_val_c,
  inv_adj_qty_c,
  intransit_adj_qty_c,
  wip_adj_qty_c,
  material,
  material_overhead,
  resource_cost,
  outside_processing,
  overhead,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.CST_COST_HISTORY_V;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cst_cost_history_v';