DROP TABLE IF EXISTS silver_bec_ods.CST_QUANTITY_LAYERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.CST_QUANTITY_LAYERS (
  layer_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  organization_id DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  layer_quantity DECIMAL(28, 10),
  create_transaction_id DECIMAL(15, 0),
  update_transaction_id DECIMAL(15, 0),
  pl_material DECIMAL(28, 10),
  pl_material_overhead DECIMAL(28, 10),
  pl_resource DECIMAL(15, 0),
  pl_outside_processing DECIMAL(28, 10),
  pl_overhead DECIMAL(15, 0),
  tl_material DECIMAL(28, 10),
  tl_material_overhead DECIMAL(28, 10),
  tl_resource DECIMAL(15, 0),
  tl_outside_processing DECIMAL(28, 10),
  tl_overhead DECIMAL(15, 0),
  material_cost DECIMAL(28, 10),
  material_overhead_cost DECIMAL(28, 10),
  resource_cost DECIMAL(28, 10),
  outside_processing_cost DECIMAL(28, 10),
  overhead_cost DECIMAL(28, 10),
  pl_item_cost DECIMAL(28, 10),
  tl_item_cost DECIMAL(28, 10),
  item_cost DECIMAL(28, 10),
  unburdened_cost DECIMAL(28, 10),
  burden_cost DECIMAL(28, 10),
  cost_group_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.CST_QUANTITY_LAYERS (
  layer_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  organization_id,
  inventory_item_id,
  layer_quantity,
  create_transaction_id,
  update_transaction_id,
  pl_material,
  pl_material_overhead,
  pl_resource,
  pl_outside_processing,
  pl_overhead,
  tl_material,
  tl_material_overhead,
  tl_resource,
  tl_outside_processing,
  tl_overhead,
  material_cost,
  material_overhead_cost,
  resource_cost,
  outside_processing_cost,
  overhead_cost,
  pl_item_cost,
  tl_item_cost,
  item_cost,
  unburdened_cost,
  burden_cost,
  cost_group_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  layer_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  organization_id,
  inventory_item_id,
  layer_quantity,
  create_transaction_id,
  update_transaction_id,
  pl_material,
  pl_material_overhead,
  pl_resource,
  pl_outside_processing,
  pl_overhead,
  tl_material,
  tl_material_overhead,
  tl_resource,
  tl_outside_processing,
  tl_overhead,
  material_cost,
  material_overhead_cost,
  resource_cost,
  outside_processing_cost,
  overhead_cost,
  pl_item_cost,
  tl_item_cost,
  item_cost,
  unburdened_cost,
  burden_cost,
  cost_group_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.CST_QUANTITY_LAYERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cst_quantity_layers';