DROP TABLE IF EXISTS silver_bec_ods.RCV_MSH_V;
CREATE TABLE IF NOT EXISTS silver_bec_ods.RCV_MSH_V (
  shipment_header_id DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  ussgl_transaction_code STRING,
  government_context STRING,
  comments STRING,
  bill_of_lading STRING,
  expected_receipt_date TIMESTAMP,
  freight_carrier_code STRING,
  from_organization_name STRING,
  num_of_containers DECIMAL(28, 10),
  from_organization_id DECIMAL(15, 0),
  vendor_name STRING,
  vendor_site STRING,
  packing_slip STRING,
  employee_id DECIMAL(9, 0),
  receipt_num STRING,
  receipt_source_code STRING,
  shipment_num STRING,
  shipped_date TIMESTAMP,
  ship_to_location STRING,
  ship_to_location_id DECIMAL(15, 0),
  waybill_airbill_num STRING,
  asn_type STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  vendor_id DECIMAL(15, 0),
  ship_to_org_id DECIMAL(15, 0),
  vendor_site_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.RCV_MSH_V (
  shipment_header_id,
  last_updated_by,
  last_update_date,
  last_update_login,
  created_by,
  creation_date,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  ussgl_transaction_code,
  government_context,
  comments,
  bill_of_lading,
  expected_receipt_date,
  freight_carrier_code,
  from_organization_name,
  num_of_containers,
  from_organization_id,
  vendor_name,
  vendor_site,
  packing_slip,
  employee_id,
  receipt_num,
  receipt_source_code,
  shipment_num,
  shipped_date,
  ship_to_location,
  ship_to_location_id,
  waybill_airbill_num,
  asn_type,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  vendor_id,
  ship_to_org_id,
  vendor_site_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  shipment_header_id,
  last_updated_by,
  last_update_date,
  last_update_login,
  created_by,
  creation_date,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  ussgl_transaction_code,
  government_context,
  comments,
  bill_of_lading,
  expected_receipt_date,
  freight_carrier_code,
  from_organization_name,
  num_of_containers,
  from_organization_id,
  vendor_name,
  vendor_site,
  packing_slip,
  employee_id,
  receipt_num,
  receipt_source_code,
  shipment_num,
  shipped_date,
  ship_to_location,
  ship_to_location_id,
  waybill_airbill_num,
  asn_type,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  vendor_id,
  ship_to_org_id,
  vendor_site_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.RCV_MSH_V;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'rcv_msh_v';