DROP table IF EXISTS silver_bec_ods.ALR_ACTION_HISTORY;
CREATE TABLE IF NOT EXISTS silver_bec_ods.alr_action_history (
  APPLICATION_ID DECIMAL(15, 0),
  ACTION_HISTORY_ID DECIMAL(15, 0),
  ALERT_ID DECIMAL(15, 0),
  ACTION_SET_ID DECIMAL(15, 0),
  CHECK_ID DECIMAL(15, 0),
  ACTION_ID DECIMAL(15, 0),
  ACTION_SET_MEMBER_ID DECIMAL(15, 0),
  LAST_UPDATE_DATE TIMESTAMP,
  ACTION_LEVEL DECIMAL(15, 0),
  COLUMN_WRAP_FLAG STRING,
  MAXIMUM_SUMMARY_MESSAGE_WIDTH DECIMAL(28, 10),
  ACTION_EXECUTED_FLAG STRING,
  SUCCESS_FLAG STRING,
  VERSION_NUMBER DECIMAL(15, 0),
  MESSAGE_HANDLE DECIMAL(15, 0),
  NODE_HANDLE DECIMAL(15, 0),
  SECURITY_GROUP_ID DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.alr_action_history (
  APPLICATION_ID,
  ACTION_HISTORY_ID,
  ALERT_ID,
  ACTION_SET_ID,
  CHECK_ID,
  ACTION_ID,
  ACTION_SET_MEMBER_ID,
  LAST_UPDATE_DATE,
  ACTION_LEVEL,
  COLUMN_WRAP_FLAG,
  MAXIMUM_SUMMARY_MESSAGE_WIDTH,
  ACTION_EXECUTED_FLAG,
  SUCCESS_FLAG,
  VERSION_NUMBER,
  MESSAGE_HANDLE,
  NODE_HANDLE,
  SECURITY_GROUP_ID,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    APPLICATION_ID,
    ACTION_HISTORY_ID,
    ALERT_ID,
    ACTION_SET_ID,
    CHECK_ID,
    ACTION_ID,
    ACTION_SET_MEMBER_ID,
    LAST_UPDATE_DATE,
    ACTION_LEVEL,
    COLUMN_WRAP_FLAG,
    MAXIMUM_SUMMARY_MESSAGE_WIDTH,
    ACTION_EXECUTED_FLAG,
    SUCCESS_FLAG,
    VERSION_NUMBER,
    MESSAGE_HANDLE,
    NODE_HANDLE,
    SECURITY_GROUP_ID,
    kca_operation,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.alr_action_history
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'alr_action_history';