DROP table IF EXISTS silver_bec_ods.ap_income_tax_regions;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_income_tax_regions (
  region_short_name STRING,
  region_long_name STRING,
  region_code DECIMAL(15, 0),
  reporting_limit DECIMAL(15, 0),
  num_of_payees DECIMAL(15, 0),
  control_total1 DECIMAL(28, 10),
  control_total2 DECIMAL(28, 10),
  control_total3 DECIMAL(28, 10),
  control_total4 DECIMAL(28, 10),
  control_total5 DECIMAL(28, 10),
  control_total6 DECIMAL(28, 10),
  control_total7 DECIMAL(28, 10),
  control_total8 DECIMAL(28, 10),
  control_total9 DECIMAL(28, 10),
  control_total10 DECIMAL(28, 10),
  active_date TIMESTAMP,
  inactive_date TIMESTAMP,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  reporting_limit_method_code STRING,
  control_total13 DECIMAL(28, 10),
  control_total13e DECIMAL(28, 10),
  control_total14 DECIMAL(28, 10),
  control_total15a DECIMAL(28, 10),
  control_total15b DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_income_tax_regions (
  region_short_name,
  region_long_name,
  region_code,
  reporting_limit,
  num_of_payees,
  control_total1,
  control_total2,
  control_total3,
  control_total4,
  control_total5,
  control_total6,
  control_total7,
  control_total8,
  control_total9,
  control_total10,
  active_date,
  inactive_date,
  last_update_date,
  last_updated_by,
  last_update_login,
  creation_date,
  created_by,
  reporting_limit_method_code,
  control_total13,
  control_total13e,
  control_total14,
  control_total15a,
  control_total15b,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  region_short_name,
  region_long_name,
  region_code,
  reporting_limit,
  num_of_payees,
  control_total1,
  control_total2,
  control_total3,
  control_total4,
  control_total5,
  control_total6,
  control_total7,
  control_total8,
  control_total9,
  control_total10,
  active_date,
  inactive_date,
  last_update_date,
  last_updated_by,
  last_update_login,
  creation_date,
  created_by,
  reporting_limit_method_code,
  control_total13,
  control_total13e,
  control_total14,
  control_total15a,
  control_total15b,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ap_income_tax_regions;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_income_tax_regions';