DROP TABLE IF EXISTS silver_bec_ods.ra_contacts;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ra_contacts (
  contact_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  customer_id DECIMAL(15, 0),
  status STRING,
  orig_system_reference STRING,
  last_name STRING,
  last_update_login DECIMAL(15, 0),
  title STRING,
  first_name STRING,
  job_title STRING,
  mail_stop STRING,
  address_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  contact_key STRING,
  contact_personal_information STRING,
  decision_maker_flag STRING,
  job_title_code STRING,
  managed_by DECIMAL(15, 0),
  native_language STRING,
  reference_use_flag STRING,
  contact_number STRING,
  attribute11 STRING,
  attribute25 STRING,
  other_language_1 STRING,
  other_language_2 STRING,
  rank STRING,
  primary_role STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute16 STRING,
  attribute17 STRING,
  attribute18 STRING,
  attribute19 STRING,
  attribute20 STRING,
  attribute21 STRING,
  attribute22 STRING,
  attribute23 STRING,
  attribute24 STRING,
  do_not_mail_flag STRING,
  suffix STRING,
  email_address STRING,
  mailing_address_id DECIMAL(15, 0),
  match_group_id DECIMAL(15, 0),
  sex_code STRING,
  salutation STRING,
  department_code STRING,
  department STRING,
  last_name_alt STRING,
  first_name_alt STRING,
  do_not_email_flag STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ra_contacts (
  contact_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  customer_id,
  status,
  orig_system_reference,
  last_name,
  last_update_login,
  title,
  first_name,
  job_title,
  mail_stop,
  address_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  contact_key,
  contact_personal_information,
  decision_maker_flag,
  job_title_code,
  managed_by,
  native_language,
  reference_use_flag,
  contact_number,
  attribute11,
  attribute25,
  other_language_1,
  other_language_2,
  `rank`,
  primary_role,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  attribute21,
  attribute22,
  attribute23,
  attribute24,
  do_not_mail_flag,
  suffix,
  email_address,
  mailing_address_id,
  match_group_id,
  sex_code,
  salutation,
  department_code,
  department,
  last_name_alt,
  first_name_alt,
  do_not_email_flag,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  contact_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  customer_id,
  status,
  orig_system_reference,
  last_name,
  last_update_login,
  title,
  first_name,
  job_title,
  mail_stop,
  address_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  contact_key,
  contact_personal_information,
  decision_maker_flag,
  job_title_code,
  managed_by,
  native_language,
  reference_use_flag,
  contact_number,
  attribute11,
  attribute25,
  other_language_1,
  other_language_2,
  `rank`,
  primary_role,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  attribute21,
  attribute22,
  attribute23,
  attribute24,
  do_not_mail_flag,
  suffix,
  email_address,
  mailing_address_id,
  match_group_id,
  sex_code,
  salutation,
  department_code,
  department,
  last_name_alt,
  first_name_alt,
  do_not_email_flag,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ra_contacts;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ra_contacts';