DROP TABLE IF EXISTS silver_bec_ods.OKS_BILL_CONT_LINES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.oks_bill_cont_lines (
  id STRING,
  cle_id STRING,
  btn_id STRING,
  date_billed_from TIMESTAMP,
  date_billed_to TIMESTAMP,
  sent_yn STRING,
  object_version_number INT,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  amount DECIMAL(28, 10),
  bill_action STRING,
  date_next_invoice TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  security_group_id DECIMAL(15, 0),
  currency_code STRING,
  averaged_yn STRING,
  settled_yn STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.oks_bill_cont_lines (
  id,
  cle_id,
  btn_id,
  date_billed_from,
  date_billed_to,
  sent_yn,
  object_version_number,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  amount,
  bill_action,
  date_next_invoice,
  last_update_login,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  currency_code,
  averaged_yn,
  settled_yn,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  id,
  cle_id,
  btn_id,
  date_billed_from,
  date_billed_to,
  sent_yn,
  object_version_number,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  amount,
  bill_action,
  date_next_invoice,
  last_update_login,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  currency_code,
  averaged_yn,
  settled_yn,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.oks_bill_cont_lines;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'oks_bill_cont_lines';