DROP TABLE IF EXISTS silver_bec_ods.PO_REQUISITION_HEADERS_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.PO_REQUISITION_HEADERS_ALL (
  requisition_header_id DECIMAL(15, 0),
  preparer_id DECIMAL(9, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  segment1 STRING,
  summary_flag STRING,
  enabled_flag STRING,
  segment2 STRING,
  segment3 STRING,
  segment4 STRING,
  segment5 STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  description STRING,
  authorization_status STRING,
  note_to_authorizer STRING,
  type_lookup_code STRING,
  transferred_to_oe_flag STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  on_line_flag STRING,
  preliminary_research_flag STRING,
  research_complete_flag STRING,
  preparer_finished_flag STRING,
  preparer_finished_date TIMESTAMP,
  agent_return_flag STRING,
  agent_return_note STRING,
  cancel_flag STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  ussgl_transaction_code STRING,
  government_context STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  interface_source_code STRING,
  interface_source_line_id DECIMAL(15, 0),
  closed_code STRING,
  org_id DECIMAL(15, 0),
  wf_item_type STRING,
  wf_item_key STRING,
  emergency_po_num STRING,
  pcard_id DECIMAL(15, 0),
  apps_source_code STRING,
  cbc_accounting_date TIMESTAMP,
  change_pending_flag STRING,
  active_shopping_cart_flag STRING,
  contractor_status STRING,
  contractor_requisition_flag STRING,
  supplier_notified_flag STRING,
  emergency_po_org_id DECIMAL(15, 0),
  approved_date TIMESTAMP,
  tax_attribute_update_code STRING,
  first_approver_id DECIMAL(15, 0),
  first_position_id DECIMAL(15, 0),
  AMENDMENT_REASON STRING,
  AMENDMENT_STATUS STRING,
  AMENDMENT_TYPE STRING,
  CLM_ASSIST_CONTACT STRING,
  CLM_ASSIST_OFFICE DECIMAL(15, 0),
  CLM_COTR_CONTACT STRING,
  CLM_COTR_OFFICE STRING,
  CLM_ISSUING_OFFICE STRING,
  CLM_MIPR_ACKNOWLEDGED_FLAG STRING,
  CLM_MIPR_PREPARED_DATE TIMESTAMP,
  CLM_MIPR_REF_NUM STRING,
  CLM_MIPR_TYPE STRING,
  CLM_PRIORITY_CODE STRING,
  CLM_REQ_CONTACT STRING,
  CLM_REQ_OFFICE DECIMAL(15, 0),
  CONFORMED_HEADER_ID DECIMAL(15, 0),
  FEDERAL_FLAG STRING, /* ,IGT_DOCUMENT_FLAG string   */
  NOTIFY_REQUESTER_FLAG STRING,
  PAR_DRAFT_ID DECIMAL(15, 0),
  PAR_FLAG STRING,
  REVISION_NUM DECIMAL(15, 0),
  SUGGESTED_AWARD_NO STRING,
  UDA_TEMPLATE_DATE TIMESTAMP,
  UDA_TEMPLATE_ID DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.PO_REQUISITION_HEADERS_ALL (
  requisition_header_id,
  preparer_id,
  last_update_date,
  last_updated_by,
  segment1,
  summary_flag,
  enabled_flag,
  segment2,
  segment3,
  segment4,
  segment5,
  start_date_active,
  end_date_active,
  last_update_login,
  creation_date,
  created_by,
  description,
  authorization_status,
  note_to_authorizer,
  type_lookup_code,
  transferred_to_oe_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  on_line_flag,
  preliminary_research_flag,
  research_complete_flag,
  preparer_finished_flag,
  preparer_finished_date,
  agent_return_flag,
  agent_return_note,
  cancel_flag,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  ussgl_transaction_code,
  government_context,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  interface_source_code,
  interface_source_line_id,
  closed_code,
  org_id,
  wf_item_type,
  wf_item_key,
  emergency_po_num,
  pcard_id,
  apps_source_code,
  cbc_accounting_date,
  change_pending_flag,
  active_shopping_cart_flag,
  contractor_status,
  contractor_requisition_flag,
  supplier_notified_flag,
  emergency_po_org_id,
  approved_date,
  tax_attribute_update_code,
  first_approver_id,
  first_position_id,
  amendment_reason,
  amendment_status,
  amendment_type,
  clm_assist_contact,
  clm_assist_office,
  clm_cotr_contact,
  clm_cotr_office,
  clm_issuing_office,
  clm_mipr_acknowledged_flag,
  clm_mipr_prepared_date,
  clm_mipr_ref_num,
  clm_mipr_type,
  clm_priority_code,
  clm_req_contact,
  clm_req_office,
  conformed_header_id,
  federal_flag,
  notify_requester_flag,
  par_draft_id,
  par_flag,
  revision_num,
  suggested_award_no,
  uda_template_date,
  uda_template_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  requisition_header_id,
  preparer_id,
  last_update_date,
  last_updated_by,
  segment1,
  summary_flag,
  enabled_flag,
  segment2,
  segment3,
  segment4,
  segment5,
  start_date_active,
  end_date_active,
  last_update_login,
  creation_date,
  created_by,
  description,
  authorization_status,
  note_to_authorizer,
  type_lookup_code,
  transferred_to_oe_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  on_line_flag,
  preliminary_research_flag,
  research_complete_flag,
  preparer_finished_flag,
  preparer_finished_date,
  agent_return_flag,
  agent_return_note,
  cancel_flag,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  ussgl_transaction_code,
  government_context,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  interface_source_code,
  interface_source_line_id,
  closed_code,
  org_id,
  wf_item_type,
  wf_item_key,
  emergency_po_num,
  pcard_id,
  apps_source_code,
  cbc_accounting_date,
  change_pending_flag,
  active_shopping_cart_flag,
  contractor_status,
  contractor_requisition_flag,
  supplier_notified_flag,
  emergency_po_org_id,
  approved_date,
  tax_attribute_update_code,
  first_approver_id,
  first_position_id,
  amendment_reason,
  amendment_status,
  amendment_type,
  clm_assist_contact,
  clm_assist_office,
  clm_cotr_contact,
  clm_cotr_office,
  clm_issuing_office,
  clm_mipr_acknowledged_flag,
  clm_mipr_prepared_date,
  clm_mipr_ref_num,
  clm_mipr_type,
  clm_priority_code,
  clm_req_contact,
  clm_req_office,
  conformed_header_id,
  federal_flag,
  notify_requester_flag, /* igt_document_flag, */
  par_draft_id,
  par_flag,
  revision_num,
  suggested_award_no,
  uda_template_date,
  uda_template_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.PO_REQUISITION_HEADERS_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'po_requisition_headers_all';