DROP TABLE IF EXISTS silver_bec_ods.MSC_TRADING_PARTNER_SITES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MSC_TRADING_PARTNER_SITES (
  partner_site_id DECIMAL(15, 0),
  sr_tp_site_id DECIMAL(15, 0),
  sr_instance_id DECIMAL(15, 0),
  partner_id DECIMAL(15, 0),
  partner_address STRING,
  tp_site_code STRING,
  sr_tp_id DECIMAL(15, 0),
  `location` STRING,
  partner_type DECIMAL(15, 0),
  deleted_flag DECIMAL(15, 0),
  longitude DECIMAL(10, 7),
  latitude DECIMAL(10, 7),
  refresh_number DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  operating_unit_name STRING,
  country STRING,
  state STRING,
  city STRING,
  postal_code STRING,
  shipping_control STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MSC_TRADING_PARTNER_SITES (
  partner_site_id,
  sr_tp_site_id,
  sr_instance_id,
  partner_id,
  partner_address,
  tp_site_code,
  sr_tp_id,
  `location`,
  partner_type,
  deleted_flag,
  longitude,
  latitude,
  refresh_number,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  operating_unit_name,
  country,
  state,
  city,
  postal_code,
  shipping_control,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  partner_site_id,
  sr_tp_site_id,
  sr_instance_id,
  partner_id,
  partner_address,
  tp_site_code,
  sr_tp_id,
  `location`,
  partner_type,
  deleted_flag,
  longitude,
  latitude,
  refresh_number,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  operating_unit_name,
  country,
  state,
  city,
  postal_code,
  shipping_control,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MSC_TRADING_PARTNER_SITES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_trading_partner_sites';