DROP TABLE IF EXISTS silver_bec_ods.OKC_K_HEADERS_TL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.OKC_K_HEADERS_TL (
  id DECIMAL(15, 0),
  `language` STRING,
  source_lang STRING,
  sfwt_flag STRING,
  short_description STRING,
  comments STRING,
  description STRING,
  cognomen STRING,
  non_response_reason STRING,
  non_response_explain STRING,
  set_aside_reason STRING,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  security_group_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.OKC_K_HEADERS_TL (
  id,
  `language`,
  source_lang,
  sfwt_flag,
  short_description,
  comments,
  description,
  cognomen,
  non_response_reason,
  non_response_explain,
  set_aside_reason,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  security_group_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  id,
  `language`,
  source_lang,
  sfwt_flag,
  short_description,
  comments,
  description,
  cognomen,
  non_response_reason,
  non_response_explain,
  set_aside_reason,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  security_group_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.OKC_K_HEADERS_TL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'okc_k_headers_tl';