DROP TABLE IF EXISTS silver_bec_ods.hz_cust_acct_sites_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.hz_cust_acct_sites_all (
  cust_acct_site_id DECIMAL(15, 0),
  cust_account_id DECIMAL(15, 0),
  party_site_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  wh_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute16 STRING,
  attribute17 STRING,
  attribute18 STRING,
  attribute19 STRING,
  attribute20 STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  orig_system_reference STRING,
  status STRING,
  org_id DECIMAL(15, 0),
  bill_to_flag STRING,
  market_flag STRING,
  ship_to_flag STRING,
  customer_category_code STRING,
  `language` STRING,
  key_account_flag STRING,
  tp_header_id DECIMAL(15, 0),
  ece_tp_location_code STRING,
  service_territory_id DECIMAL(15, 0),
  primary_specialist_id DECIMAL(15, 0),
  secondary_specialist_id DECIMAL(15, 0),
  territory_id DECIMAL(15, 0),
  address_text STRING,
  territory STRING,
  translated_customer_name STRING,
  object_version_number DECIMAL(15, 0),
  created_by_module STRING,
  application_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.hz_cust_acct_sites_all (
  cust_acct_site_id,
  cust_account_id,
  party_site_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wh_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  orig_system_reference,
  status,
  org_id,
  bill_to_flag,
  market_flag,
  ship_to_flag,
  customer_category_code,
  `language`,
  key_account_flag,
  tp_header_id,
  ece_tp_location_code,
  service_territory_id,
  primary_specialist_id,
  secondary_specialist_id,
  territory_id,
  address_text,
  territory,
  translated_customer_name,
  object_version_number,
  created_by_module,
  application_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cust_acct_site_id,
  cust_account_id,
  party_site_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wh_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  orig_system_reference,
  status,
  org_id,
  bill_to_flag,
  market_flag,
  ship_to_flag,
  customer_category_code,
  `language`,
  key_account_flag,
  tp_header_id,
  ece_tp_location_code,
  service_territory_id,
  primary_specialist_id,
  secondary_specialist_id,
  territory_id,
  address_text,
  territory,
  translated_customer_name,
  object_version_number,
  created_by_module,
  application_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.HZ_CUST_ACCT_SITES_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'hz_cust_acct_sites_all';