DROP table IF EXISTS silver_bec_ods.QP_LIST_LINES_V;
CREATE TABLE IF NOT EXISTS silver_bec_ods.QP_LIST_LINES_V (
  list_line_id DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  list_header_id DECIMAL(15, 0),
  pa_list_header_id DECIMAL(15, 0),
  product_attribute_context STRING,
  product_attribute STRING,
  product_attr_value STRING,
  product_uom_code STRING,
  list_price DECIMAL(15, 0),
  percent_price DECIMAL(15, 0),
  price_by_formula_id DECIMAL(15, 0),
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  context STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  primary_uom_flag STRING,
  revision STRING,
  revision_date TIMESTAMP,
  revision_reason_code STRING,
  comments STRING,
  list_line_type_code STRING,
  automatic_flag STRING,
  modifier_level_code STRING,
  list_price_uom_code STRING,
  inventory_item_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  related_item_id DECIMAL(15, 0),
  number_effective_periods DECIMAL(28, 10),
  effective_period_uom STRING,
  arithmetic_operator STRING,
  incompatibility_grp_code STRING,
  list_line_no STRING,
  pricing_group_sequence DECIMAL(15, 0),
  relationship_type_id DECIMAL(15, 0),
  substitution_context STRING,
  substitution_attribute STRING,
  substitution_value STRING,
  price_break_type_code STRING,
  operand DECIMAL(28, 10),
  override_flag STRING,
  print_on_invoice_flag STRING,
  rebate_transaction_type_code STRING,
  base_qty DECIMAL(28, 10),
  base_uom_code STRING,
  accrual_qty DECIMAL(28, 10),
  accrual_uom_code STRING,
  estim_accrual_rate DECIMAL(28, 10),
  generate_using_formula_id DECIMAL(15, 0),
  accrual_flag STRING,
  reprice_flag STRING,
  pricing_phase_id DECIMAL(15, 0),
  product_precedence DECIMAL(15, 0),
  customer_item_id DECIMAL(15, 0),
  pricing_attribute_context STRING,
  pricing_attribute STRING,
  pricing_attr_value_from STRING,
  pricing_attr_value_to STRING,
  product_attr_val_disp STRING,
  product_id STRING,
  pricing_attribute_id DECIMAL(15, 0),
  product_attribute_datatype STRING,
  pricing_attribute_datatype STRING,
  comparison_operator_code STRING,
  attr_list_line_id DECIMAL(15, 0),
  attr_creation_date TIMESTAMP,
  attr_created_by DECIMAL(15, 0),
  attr_last_update_date TIMESTAMP,
  attr_last_updated_by DECIMAL(15, 0),
  attr_last_update_login DECIMAL(15, 0),
  attr_program_application_id DECIMAL(15, 0),
  attr_program_id DECIMAL(15, 0),
  attr_program_update_date TIMESTAMP,
  attr_request_id DECIMAL(15, 0),
  attr_context STRING,
  attr_attribute1 STRING,
  attr_attribute2 STRING,
  attr_attribute3 STRING,
  attr_attribute4 STRING,
  attr_attribute5 STRING,
  attr_attribute6 STRING,
  attr_attribute7 STRING,
  attr_attribute8 STRING,
  attr_attribute9 STRING,
  attr_attribute10 STRING,
  attr_attribute11 STRING,
  attr_attribute12 STRING,
  attr_attribute13 STRING,
  attr_attribute14 STRING,
  attr_attribute15 STRING,
  break_uom_code STRING,
  break_uom_context STRING,
  break_uom_attribute STRING,
  accum_attribute STRING,
  continuous_price_break_flag STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.QP_LIST_LINES_V (
  list_line_id,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  list_header_id,
  pa_list_header_id,
  product_attribute_context,
  product_attribute,
  product_attr_value,
  product_uom_code,
  list_price,
  percent_price,
  price_by_formula_id,
  start_date_active,
  end_date_active,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  primary_uom_flag,
  revision,
  revision_date,
  revision_reason_code,
  comments,
  list_line_type_code,
  automatic_flag,
  modifier_level_code,
  list_price_uom_code,
  inventory_item_id,
  organization_id,
  related_item_id,
  number_effective_periods,
  effective_period_uom,
  arithmetic_operator,
  incompatibility_grp_code,
  list_line_no,
  pricing_group_sequence,
  relationship_type_id,
  substitution_context,
  substitution_attribute,
  substitution_value,
  price_break_type_code,
  operand,
  override_flag,
  print_on_invoice_flag,
  rebate_transaction_type_code,
  base_qty,
  base_uom_code,
  accrual_qty,
  accrual_uom_code,
  estim_accrual_rate,
  generate_using_formula_id,
  accrual_flag,
  reprice_flag,
  pricing_phase_id,
  product_precedence,
  customer_item_id,
  pricing_attribute_context,
  pricing_attribute,
  pricing_attr_value_from,
  pricing_attr_value_to,
  product_attr_val_disp,
  product_id,
  pricing_attribute_id,
  product_attribute_datatype,
  pricing_attribute_datatype,
  comparison_operator_code,
  attr_list_line_id,
  attr_creation_date,
  attr_created_by,
  attr_last_update_date,
  attr_last_updated_by,
  attr_last_update_login,
  attr_program_application_id,
  attr_program_id,
  attr_program_update_date,
  attr_request_id,
  attr_context,
  attr_attribute1,
  attr_attribute2,
  attr_attribute3,
  attr_attribute4,
  attr_attribute5,
  attr_attribute6,
  attr_attribute7,
  attr_attribute8,
  attr_attribute9,
  attr_attribute10,
  attr_attribute11,
  attr_attribute12,
  attr_attribute13,
  attr_attribute14,
  attr_attribute15,
  break_uom_code,
  break_uom_context,
  break_uom_attribute,
  accum_attribute,
  continuous_price_break_flag,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    list_line_id,
    creation_date,
    created_by,
    last_update_date,
    last_updated_by,
    last_update_login,
    program_application_id,
    program_id,
    program_update_date,
    request_id,
    list_header_id,
    pa_list_header_id,
    product_attribute_context,
    product_attribute,
    product_attr_value,
    product_uom_code,
    list_price,
    percent_price,
    price_by_formula_id,
    start_date_active,
    end_date_active,
    context,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    primary_uom_flag,
    revision,
    revision_date,
    revision_reason_code,
    comments,
    list_line_type_code,
    automatic_flag,
    modifier_level_code,
    list_price_uom_code,
    inventory_item_id,
    organization_id,
    related_item_id,
    number_effective_periods,
    effective_period_uom,
    arithmetic_operator,
    incompatibility_grp_code,
    list_line_no,
    pricing_group_sequence,
    relationship_type_id,
    substitution_context,
    substitution_attribute,
    substitution_value,
    price_break_type_code,
    operand,
    override_flag,
    print_on_invoice_flag,
    rebate_transaction_type_code,
    base_qty,
    base_uom_code,
    accrual_qty,
    accrual_uom_code,
    estim_accrual_rate,
    generate_using_formula_id,
    accrual_flag,
    reprice_flag,
    pricing_phase_id,
    product_precedence,
    customer_item_id,
    pricing_attribute_context,
    pricing_attribute,
    pricing_attr_value_from,
    pricing_attr_value_to,
    product_attr_val_disp,
    product_id,
    pricing_attribute_id,
    product_attribute_datatype,
    pricing_attribute_datatype,
    comparison_operator_code,
    attr_list_line_id,
    attr_creation_date,
    attr_created_by,
    attr_last_update_date,
    attr_last_updated_by,
    attr_last_update_login,
    attr_program_application_id,
    attr_program_id,
    attr_program_update_date,
    attr_request_id,
    attr_context,
    attr_attribute1,
    attr_attribute2,
    attr_attribute3,
    attr_attribute4,
    attr_attribute5,
    attr_attribute6,
    attr_attribute7,
    attr_attribute8,
    attr_attribute9,
    attr_attribute10,
    attr_attribute11,
    attr_attribute12,
    attr_attribute13,
    attr_attribute14,
    attr_attribute15,
    break_uom_code,
    break_uom_context,
    break_uom_attribute,
    accum_attribute,
    continuous_price_break_flag,
    kca_operation,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.QP_LIST_LINES_V
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'qp_list_lines_v';