DROP TABLE IF EXISTS silver_bec_ods.AR_DISTRIBUTIONS_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ar_distributions_all (
  line_id DECIMAL(15, 0),
  source_id DECIMAL(15, 0),
  source_table STRING,
  source_type STRING,
  code_combination_id DECIMAL(15, 0),
  amount_dr DECIMAL(28, 10),
  amount_cr DECIMAL(28, 10),
  acctd_amount_dr DECIMAL(28, 10),
  acctd_amount_cr DECIMAL(28, 10),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  source_table_secondary STRING,
  source_id_secondary DECIMAL(15, 0),
  currency_code STRING,
  currency_conversion_rate DECIMAL(28, 10),
  currency_conversion_type STRING,
  currency_conversion_date TIMESTAMP,
  taxable_entered_dr DECIMAL(28, 10),
  taxable_entered_cr DECIMAL(28, 10),
  taxable_accounted_dr DECIMAL(28, 10),
  taxable_accounted_cr DECIMAL(28, 10),
  tax_link_id DECIMAL(15, 0),
  third_party_id DECIMAL(15, 0),
  third_party_sub_id DECIMAL(15, 0),
  reversed_source_id DECIMAL(15, 0),
  tax_code_id DECIMAL(15, 0),
  location_segment_id DECIMAL(15, 0),
  source_type_secondary STRING,
  tax_group_code_id DECIMAL(15, 0),
  ref_customer_trx_line_id DECIMAL(15, 0),
  ref_cust_trx_line_gl_dist_id DECIMAL(15, 0),
  ref_account_class STRING,
  activity_bucket STRING,
  ref_line_id DECIMAL(15, 0),
  from_amount_dr DECIMAL(28, 10),
  from_amount_cr DECIMAL(28, 10),
  from_acctd_amount_dr DECIMAL(28, 10),
  from_acctd_amount_cr DECIMAL(28, 10),
  ref_mf_dist_flag STRING,
  ref_dist_ccid DECIMAL(15, 0),
  REF_PREV_CUST_TRX_LINE_ID DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.AR_DISTRIBUTIONS_ALL (
  line_id,
  source_id,
  source_table,
  source_type,
  code_combination_id,
  amount_dr,
  amount_cr,
  acctd_amount_dr,
  acctd_amount_cr,
  creation_date,
  created_by,
  last_updated_by,
  last_update_date,
  last_update_login,
  org_id,
  source_table_secondary,
  source_id_secondary,
  currency_code,
  currency_conversion_rate,
  currency_conversion_type,
  currency_conversion_date,
  taxable_entered_dr,
  taxable_entered_cr,
  taxable_accounted_dr,
  taxable_accounted_cr,
  tax_link_id,
  third_party_id,
  third_party_sub_id,
  reversed_source_id,
  tax_code_id,
  location_segment_id,
  source_type_secondary,
  tax_group_code_id,
  ref_customer_trx_line_id,
  ref_cust_trx_line_gl_dist_id,
  ref_account_class,
  activity_bucket,
  ref_line_id,
  from_amount_dr,
  from_amount_cr,
  from_acctd_amount_dr,
  from_acctd_amount_cr,
  ref_mf_dist_flag,
  ref_dist_ccid,
  REF_PREV_CUST_TRX_LINE_ID,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  line_id,
  source_id,
  source_table,
  source_type,
  code_combination_id,
  amount_dr,
  amount_cr,
  acctd_amount_dr,
  acctd_amount_cr,
  creation_date,
  created_by,
  last_updated_by,
  last_update_date,
  last_update_login,
  org_id,
  source_table_secondary,
  source_id_secondary,
  currency_code,
  currency_conversion_rate,
  currency_conversion_type,
  currency_conversion_date,
  taxable_entered_dr,
  taxable_entered_cr,
  taxable_accounted_dr,
  taxable_accounted_cr,
  tax_link_id,
  third_party_id,
  third_party_sub_id,
  reversed_source_id,
  tax_code_id,
  location_segment_id,
  source_type_secondary,
  tax_group_code_id,
  ref_customer_trx_line_id,
  ref_cust_trx_line_gl_dist_id,
  ref_account_class,
  activity_bucket,
  ref_line_id,
  from_amount_dr,
  from_amount_cr,
  from_acctd_amount_dr,
  from_acctd_amount_cr,
  ref_mf_dist_flag,
  ref_dist_ccid,
  REF_PREV_CUST_TRX_LINE_ID,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.AR_DISTRIBUTIONS_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ar_distributions_all';