DROP TABLE IF EXISTS silver_bec_ods.PO_VENDORS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.PO_VENDORS (
  vendor_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  vendor_name STRING,
  vendor_name_alt STRING,
  segment1 STRING,
  summary_flag STRING,
  enabled_flag STRING,
  segment2 STRING,
  segment3 STRING,
  segment4 STRING,
  segment5 STRING,
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  employee_id DECIMAL(15, 0),
  vendor_type_lookup_code STRING,
  customer_num STRING,
  one_time_flag STRING,
  parent_vendor_id DECIMAL(15, 0),
  min_order_amount DECIMAL(28, 10),
  terms_id DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  always_take_disc_flag STRING,
  pay_date_basis_lookup_code STRING,
  pay_group_lookup_code STRING,
  payment_priority DECIMAL(28, 10),
  invoice_currency_code STRING,
  payment_currency_code STRING,
  invoice_amount_limit DECIMAL(28, 10),
  hold_all_payments_flag STRING,
  hold_future_payments_flag STRING,
  hold_reason STRING,
  num_1099 STRING,
  individual_1099 STRING,
  type_1099 STRING,
  withholding_status_lookup_code STRING,
  withholding_start_date TIMESTAMP,
  organization_type_lookup_code STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  minority_group_lookup_code STRING,
  women_owned_flag STRING,
  small_business_flag STRING,
  standard_industry_class STRING,
  hold_flag STRING,
  purchasing_hold_reason STRING,
  hold_by DECIMAL(9, 0),
  hold_date TIMESTAMP,
  terms_date_basis STRING,
  inspection_required_flag STRING,
  receipt_required_flag STRING,
  qty_rcv_tolerance DECIMAL(28, 10),
  qty_rcv_exception_code STRING,
  enforce_ship_to_location_code STRING,
  days_early_receipt_allowed DECIMAL(15, 0),
  days_late_receipt_allowed DECIMAL(15, 0),
  receipt_days_exception_code STRING,
  receiving_routing_id DECIMAL(15, 0),
  allow_substitute_receipts_flag STRING,
  allow_unordered_receipts_flag STRING,
  hold_unmatched_invoices_flag STRING,
  tax_verification_date TIMESTAMP,
  name_control STRING,
  state_reportable_flag STRING,
  federal_reportable_flag STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  vat_registration_num STRING,
  auto_calculate_interest_flag STRING,
  validation_number DECIMAL(15, 0),
  exclude_freight_from_discount STRING,
  tax_reporting_name STRING,
  check_digits STRING,
  allow_awt_flag STRING,
  awt_group_id DECIMAL(15, 0),
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute_category STRING,
  bank_charge_bearer STRING,
  match_option STRING,
  create_debit_memo_flag STRING,
  party_id DECIMAL(15, 0),
  parent_party_id DECIMAL(15, 0),
  ni_number STRING,
  party_number STRING,
  pay_awt_group_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.PO_VENDORS (
  vendor_id,
  last_update_date,
  last_updated_by,
  vendor_name,
  vendor_name_alt,
  segment1,
  summary_flag,
  enabled_flag,
  segment2,
  segment3,
  segment4,
  segment5,
  last_update_login,
  creation_date,
  created_by,
  employee_id,
  vendor_type_lookup_code,
  customer_num,
  one_time_flag,
  parent_vendor_id,
  min_order_amount,
  terms_id,
  set_of_books_id,
  always_take_disc_flag,
  pay_date_basis_lookup_code,
  pay_group_lookup_code,
  payment_priority,
  invoice_currency_code,
  payment_currency_code,
  invoice_amount_limit,
  hold_all_payments_flag,
  hold_future_payments_flag,
  hold_reason,
  num_1099,
  individual_1099,
  type_1099,
  withholding_status_lookup_code,
  withholding_start_date,
  organization_type_lookup_code,
  start_date_active,
  end_date_active,
  minority_group_lookup_code,
  women_owned_flag,
  small_business_flag,
  standard_industry_class,
  hold_flag,
  purchasing_hold_reason,
  hold_by,
  hold_date,
  terms_date_basis,
  inspection_required_flag,
  receipt_required_flag,
  qty_rcv_tolerance,
  qty_rcv_exception_code,
  enforce_ship_to_location_code,
  days_early_receipt_allowed,
  days_late_receipt_allowed,
  receipt_days_exception_code,
  receiving_routing_id,
  allow_substitute_receipts_flag,
  allow_unordered_receipts_flag,
  hold_unmatched_invoices_flag,
  tax_verification_date,
  name_control,
  state_reportable_flag,
  federal_reportable_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  vat_registration_num,
  auto_calculate_interest_flag,
  validation_number,
  exclude_freight_from_discount,
  tax_reporting_name,
  check_digits,
  allow_awt_flag,
  awt_group_id,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  bank_charge_bearer,
  match_option,
  create_debit_memo_flag,
  party_id,
  parent_party_id,
  ni_number,
  party_number,
  pay_awt_group_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  vendor_id,
  last_update_date,
  last_updated_by,
  vendor_name,
  vendor_name_alt,
  segment1,
  summary_flag,
  enabled_flag,
  segment2,
  segment3,
  segment4,
  segment5,
  last_update_login,
  creation_date,
  created_by,
  employee_id,
  vendor_type_lookup_code,
  customer_num,
  one_time_flag,
  parent_vendor_id,
  min_order_amount,
  terms_id,
  set_of_books_id,
  always_take_disc_flag,
  pay_date_basis_lookup_code,
  pay_group_lookup_code,
  payment_priority,
  invoice_currency_code,
  payment_currency_code,
  invoice_amount_limit,
  hold_all_payments_flag,
  hold_future_payments_flag,
  hold_reason,
  num_1099,
  individual_1099,
  type_1099,
  withholding_status_lookup_code,
  withholding_start_date,
  organization_type_lookup_code,
  start_date_active,
  end_date_active,
  minority_group_lookup_code,
  women_owned_flag,
  small_business_flag,
  standard_industry_class,
  hold_flag,
  purchasing_hold_reason,
  hold_by,
  hold_date,
  terms_date_basis,
  inspection_required_flag,
  receipt_required_flag,
  qty_rcv_tolerance,
  qty_rcv_exception_code,
  enforce_ship_to_location_code,
  days_early_receipt_allowed,
  days_late_receipt_allowed,
  receipt_days_exception_code,
  receiving_routing_id,
  allow_substitute_receipts_flag,
  allow_unordered_receipts_flag,
  hold_unmatched_invoices_flag,
  tax_verification_date,
  name_control,
  state_reportable_flag,
  federal_reportable_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  vat_registration_num,
  auto_calculate_interest_flag,
  validation_number,
  exclude_freight_from_discount,
  tax_reporting_name,
  check_digits,
  allow_awt_flag,
  awt_group_id,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  bank_charge_bearer,
  match_option,
  create_debit_memo_flag,
  party_id,
  parent_party_id,
  ni_number,
  party_number,
  pay_awt_group_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.PO_VENDORS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'po_vendors';