DROP TABLE IF EXISTS silver_bec_ods.CST_STANDARD_COSTS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.CST_STANDARD_COSTS (
  cost_update_id DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  standard_cost_revision_date TIMESTAMP,
  standard_cost DECIMAL(28, 10),
  inventory_adjustment_quantity DECIMAL(28, 10),
  inventory_adjustment_value DECIMAL(28, 10),
  intransit_adjustment_quantity DECIMAL(28, 10),
  intransit_adjustment_value DECIMAL(28, 10),
  wip_adjustment_quantity DECIMAL(28, 10),
  wip_adjustment_value DECIMAL(28, 10),
  last_cost_update_id DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.CST_STANDARD_COSTS (
  cost_update_id,
  inventory_item_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  standard_cost_revision_date,
  standard_cost,
  inventory_adjustment_quantity,
  inventory_adjustment_value,
  intransit_adjustment_quantity,
  intransit_adjustment_value,
  wip_adjustment_quantity,
  wip_adjustment_value,
  last_cost_update_id,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cost_update_id,
  inventory_item_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  standard_cost_revision_date,
  standard_cost,
  inventory_adjustment_quantity,
  inventory_adjustment_value,
  intransit_adjustment_quantity,
  intransit_adjustment_value,
  wip_adjustment_quantity,
  wip_adjustment_value,
  last_cost_update_id,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.CST_STANDARD_COSTS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cst_standard_costs';