DROP TABLE IF EXISTS silver_bec_ods.GL_LEDGER_NORM_SEG_VALS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.GL_LEDGER_NORM_SEG_VALS (
  ledger_id DECIMAL(15, 0),
  segment_type_code STRING,
  segment_value STRING,
  segment_value_type_code STRING,
  record_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  status_code STRING,
  request_id DECIMAL(15, 0),
  legal_entity_id DECIMAL(15, 0),
  sla_sequencing_flag STRING,
  context STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.GL_LEDGER_NORM_SEG_VALS (
  ledger_id,
  segment_type_code,
  segment_value,
  segment_value_type_code,
  record_id,
  last_update_date,
  last_updated_by,
  last_update_login,
  creation_date,
  created_by,
  start_date,
  end_date,
  status_code,
  request_id,
  legal_entity_id,
  sla_sequencing_flag,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  ledger_id,
  segment_type_code,
  segment_value,
  segment_value_type_code,
  record_id,
  last_update_date,
  last_updated_by,
  last_update_login,
  creation_date,
  created_by,
  start_date,
  end_date,
  status_code,
  request_id,
  legal_entity_id,
  sla_sequencing_flag,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.GL_LEDGER_NORM_SEG_VALS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_ledger_norm_seg_vals';