DROP TABLE IF EXISTS silver_bec_ods.RCV_TRANSACTIONS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.RCV_TRANSACTIONS (
  transaction_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  transaction_type STRING,
  transaction_date TIMESTAMP,
  quantity DECIMAL(28, 10),
  unit_of_measure STRING,
  shipment_header_id DECIMAL(15, 0),
  shipment_line_id DECIMAL(15, 0),
  user_entered_flag STRING,
  interface_source_code STRING,
  interface_source_line_id DECIMAL(15, 0),
  inv_transaction_id DECIMAL(15, 0),
  source_document_code STRING,
  destination_type_code STRING,
  primary_quantity DECIMAL(28, 10),
  primary_unit_of_measure STRING,
  uom_code STRING,
  employee_id DECIMAL(9, 0),
  parent_transaction_id DECIMAL(15, 0),
  po_header_id DECIMAL(15, 0),
  po_release_id DECIMAL(15, 0),
  po_line_id DECIMAL(15, 0),
  po_line_location_id DECIMAL(15, 0),
  po_distribution_id DECIMAL(15, 0),
  po_revision_num DECIMAL(15, 0),
  requisition_line_id DECIMAL(15, 0),
  po_unit_price DECIMAL(28, 10),
  currency_code STRING,
  currency_conversion_type STRING,
  currency_conversion_rate DECIMAL(28, 10),
  currency_conversion_date TIMESTAMP,
  routing_header_id DECIMAL(15, 0),
  routing_step_id DECIMAL(15, 0),
  deliver_to_person_id DECIMAL(9, 0),
  deliver_to_location_id DECIMAL(15, 0),
  vendor_id DECIMAL(15, 0),
  vendor_site_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  subinventory STRING,
  locator_id DECIMAL(15, 0),
  wip_entity_id DECIMAL(15, 0),
  wip_line_id DECIMAL(15, 0),
  wip_repetitive_schedule_id DECIMAL(15, 0),
  wip_operation_seq_num DECIMAL(15, 0),
  wip_resource_seq_num DECIMAL(15, 0),
  bom_resource_id DECIMAL(15, 0),
  location_id DECIMAL(15, 0),
  substitute_unordered_code STRING,
  receipt_exception_flag STRING,
  inspection_status_code STRING,
  accrual_status_code STRING,
  inspection_quality_code STRING,
  vendor_lot_num STRING,
  rma_reference STRING,
  comments STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  req_distribution_id DECIMAL(15, 0),
  department_code STRING,
  reason_id DECIMAL(15, 0),
  destination_context STRING,
  locator_attribute STRING,
  child_inspection_flag STRING,
  source_doc_unit_of_measure STRING,
  source_doc_quantity DECIMAL(28, 10),
  interface_transaction_id DECIMAL(15, 0),
  group_id DECIMAL(15, 0),
  movement_id DECIMAL(15, 0),
  invoice_id DECIMAL(15, 0),
  invoice_status_code STRING,
  qa_collection_id DECIMAL(15, 0),
  mrc_currency_conversion_type STRING,
  mrc_currency_conversion_date STRING,
  mrc_currency_conversion_rate STRING,
  country_of_origin_code STRING,
  mvt_stat_status STRING,
  quantity_billed DECIMAL(28, 10),
  match_flag STRING,
  amount_billed DECIMAL(28, 10),
  match_option STRING,
  oe_order_header_id DECIMAL(15, 0),
  oe_order_line_id DECIMAL(15, 0),
  customer_id DECIMAL(15, 0),
  customer_site_id DECIMAL(15, 0),
  lpn_id DECIMAL(15, 0),
  transfer_lpn_id DECIMAL(15, 0),
  mobile_txn STRING,
  secondary_quantity DECIMAL(28, 10),
  secondary_unit_of_measure STRING,
  qc_grade STRING,
  secondary_uom_code STRING,
  pa_addition_flag STRING,
  consigned_flag STRING,
  source_transaction_num STRING,
  from_subinventory STRING,
  from_locator_id DECIMAL(15, 0),
  amount DECIMAL(28, 10),
  dropship_type_code DECIMAL(15, 0),
  lpn_group_id DECIMAL(15, 0),
  job_id DECIMAL(15, 0),
  timecard_id DECIMAL(15, 0),
  timecard_ovn DECIMAL(28, 10),
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  requested_amount DECIMAL(28, 10),
  material_stored_amount DECIMAL(28, 10),
  replenish_order_line_id DECIMAL(15, 0),
  lcm_shipment_line_id DECIMAL(15, 0),
  unit_landed_cost DECIMAL(28, 10),
  receipt_confirmation_extracted STRING,
  lcm_adjustment_num DECIMAL(15, 0),
  xml_document_id DECIMAL(15, 0),
  `comments#1` STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.RCV_TRANSACTIONS (
  transaction_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  transaction_type,
  transaction_date,
  quantity,
  unit_of_measure,
  shipment_header_id,
  shipment_line_id,
  user_entered_flag,
  interface_source_code,
  interface_source_line_id,
  inv_transaction_id,
  source_document_code,
  destination_type_code,
  primary_quantity,
  primary_unit_of_measure,
  uom_code,
  employee_id,
  parent_transaction_id,
  po_header_id,
  po_release_id,
  po_line_id,
  po_line_location_id,
  po_distribution_id,
  po_revision_num,
  requisition_line_id,
  po_unit_price,
  currency_code,
  currency_conversion_type,
  currency_conversion_rate,
  currency_conversion_date,
  routing_header_id,
  routing_step_id,
  deliver_to_person_id,
  deliver_to_location_id,
  vendor_id,
  vendor_site_id,
  organization_id,
  subinventory,
  locator_id,
  wip_entity_id,
  wip_line_id,
  wip_repetitive_schedule_id,
  wip_operation_seq_num,
  wip_resource_seq_num,
  bom_resource_id,
  location_id,
  substitute_unordered_code,
  receipt_exception_flag,
  inspection_status_code,
  accrual_status_code,
  inspection_quality_code,
  vendor_lot_num,
  rma_reference,
  comments,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  req_distribution_id,
  department_code,
  reason_id,
  destination_context,
  locator_attribute,
  child_inspection_flag,
  source_doc_unit_of_measure,
  source_doc_quantity,
  interface_transaction_id,
  group_id,
  movement_id,
  invoice_id,
  invoice_status_code,
  qa_collection_id,
  mrc_currency_conversion_type,
  mrc_currency_conversion_date,
  mrc_currency_conversion_rate,
  country_of_origin_code,
  mvt_stat_status,
  quantity_billed,
  match_flag,
  amount_billed,
  match_option,
  oe_order_header_id,
  oe_order_line_id,
  customer_id,
  customer_site_id,
  lpn_id,
  transfer_lpn_id,
  mobile_txn,
  secondary_quantity,
  secondary_unit_of_measure,
  qc_grade,
  secondary_uom_code,
  pa_addition_flag,
  consigned_flag,
  source_transaction_num,
  from_subinventory,
  from_locator_id,
  amount,
  dropship_type_code,
  lpn_group_id,
  job_id,
  timecard_id,
  timecard_ovn,
  project_id,
  task_id,
  requested_amount,
  material_stored_amount,
  replenish_order_line_id,
  lcm_shipment_line_id,
  unit_landed_cost,
  receipt_confirmation_extracted,
  lcm_adjustment_num,
  xml_document_id,
  `comments#1`,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  transaction_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  transaction_type,
  transaction_date,
  quantity,
  unit_of_measure,
  shipment_header_id,
  shipment_line_id,
  user_entered_flag,
  interface_source_code,
  interface_source_line_id,
  inv_transaction_id,
  source_document_code,
  destination_type_code,
  primary_quantity,
  primary_unit_of_measure,
  uom_code,
  employee_id,
  parent_transaction_id,
  po_header_id,
  po_release_id,
  po_line_id,
  po_line_location_id,
  po_distribution_id,
  po_revision_num,
  requisition_line_id,
  po_unit_price,
  currency_code,
  currency_conversion_type,
  currency_conversion_rate,
  currency_conversion_date,
  routing_header_id,
  routing_step_id,
  deliver_to_person_id,
  deliver_to_location_id,
  vendor_id,
  vendor_site_id,
  organization_id,
  subinventory,
  locator_id,
  wip_entity_id,
  wip_line_id,
  wip_repetitive_schedule_id,
  wip_operation_seq_num,
  wip_resource_seq_num,
  bom_resource_id,
  location_id,
  substitute_unordered_code,
  receipt_exception_flag,
  inspection_status_code,
  accrual_status_code,
  inspection_quality_code,
  vendor_lot_num,
  rma_reference,
  comments,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  req_distribution_id,
  department_code,
  reason_id,
  destination_context,
  locator_attribute,
  child_inspection_flag,
  source_doc_unit_of_measure,
  source_doc_quantity,
  interface_transaction_id,
  group_id,
  movement_id,
  invoice_id,
  invoice_status_code,
  qa_collection_id,
  mrc_currency_conversion_type,
  mrc_currency_conversion_date,
  mrc_currency_conversion_rate,
  country_of_origin_code,
  mvt_stat_status,
  quantity_billed,
  match_flag,
  amount_billed,
  match_option,
  oe_order_header_id,
  oe_order_line_id,
  customer_id,
  customer_site_id,
  lpn_id,
  transfer_lpn_id,
  mobile_txn,
  secondary_quantity,
  secondary_unit_of_measure,
  qc_grade,
  secondary_uom_code,
  pa_addition_flag,
  consigned_flag,
  source_transaction_num,
  from_subinventory,
  from_locator_id,
  amount,
  dropship_type_code,
  lpn_group_id,
  job_id,
  timecard_id,
  timecard_ovn,
  project_id,
  task_id,
  requested_amount,
  material_stored_amount,
  replenish_order_line_id,
  lcm_shipment_line_id,
  unit_landed_cost,
  receipt_confirmation_extracted,
  lcm_adjustment_num,
  xml_document_id,
  comments#1,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.RCV_TRANSACTIONS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'rcv_transactions';