DROP TABLE IF EXISTS silver_bec_ods.FA_MC_BOOKS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.FA_MC_BOOKS (
  set_of_books_id DECIMAL(15, 0),
  asset_id DECIMAL(15, 0),
  book_type_code STRING,
  transaction_header_id_in DECIMAL(15, 0),
  transaction_header_id_out DECIMAL(15, 0),
  adjusted_cost DECIMAL(28, 10),
  cost DECIMAL(28, 10),
  source_cost DECIMAL(28, 10),
  original_cost DECIMAL(28, 10),
  source_original_cost DECIMAL(28, 10),
  salvage_value DECIMAL(28, 10),
  adjustment_required_status STRING,
  retirement_pending_flag STRING,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  itc_amount DECIMAL(28, 10),
  itc_basis DECIMAL(28, 10),
  recoverable_cost DECIMAL(28, 10),
  last_update_login DECIMAL(15, 0),
  reval_ceiling DECIMAL(28, 10),
  period_counter_fully_reserved DECIMAL(15, 0),
  unrevalued_cost DECIMAL(28, 10),
  allowed_deprn_limit_amount DECIMAL(28, 10),
  period_counter_life_complete DECIMAL(15, 0),
  adjusted_recoverable_cost DECIMAL(28, 10),
  converted_flag STRING,
  annual_deprn_rounding_flag STRING,
  eofy_adj_cost DECIMAL(28, 10),
  old_adjusted_cost DECIMAL(28, 10),
  eofy_formula_factor DECIMAL(28, 10),
  formula_factor DECIMAL(28, 10),
  remaining_life1 DECIMAL(4, 0),
  remaining_life2 DECIMAL(4, 0),
  short_fiscal_year_flag STRING,
  group_asset_id DECIMAL(15, 0),
  reval_amortization_basis DECIMAL(28, 10),
  itc_amount_id DECIMAL(15, 0),
  retirement_id DECIMAL(15, 0),
  tax_request_id DECIMAL(15, 0),
  basic_rate DECIMAL(28, 10),
  adjusted_rate DECIMAL(28, 10),
  bonus_rule STRING,
  ceiling_name STRING,
  adjusted_capacity DECIMAL(28, 10),
  fully_rsvd_revals_counter DECIMAL(15, 0),
  idled_flag STRING,
  period_counter_capitalized DECIMAL(15, 0),
  period_counter_fully_retired DECIMAL(15, 0),
  production_capacity DECIMAL(28, 10),
  unit_of_measure STRING,
  percent_salvage_value DECIMAL(28, 10),
  allowed_deprn_limit DECIMAL(28, 10),
  annual_rounding_flag STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute_category STRING,
  date_placed_in_service TIMESTAMP,
  date_effective TIMESTAMP,
  deprn_start_date TIMESTAMP,
  deprn_method_code STRING,
  life_in_months DECIMAL(15, 0),
  rate_adjustment_factor DECIMAL(28, 10),
  prorate_convention_code STRING,
  prorate_date TIMESTAMP,
  cost_change_flag STRING,
  capitalize_flag STRING,
  depreciate_flag STRING,
  date_ineffective TIMESTAMP,
  conversion_date TIMESTAMP,
  original_deprn_start_date TIMESTAMP,
  salvage_type STRING,
  deprn_limit_type STRING,
  reduction_rate DECIMAL(28, 10),
  reduce_addition_flag STRING,
  reduce_adjustment_flag STRING,
  reduce_retirement_flag STRING,
  recognize_gain_loss STRING,
  recapture_reserve_flag STRING,
  limit_proceeds_flag STRING,
  terminal_gain_loss STRING,
  tracking_method STRING,
  exclude_fully_rsv_flag STRING,
  excess_allocation_option STRING,
  depreciation_option STRING,
  member_rollup_flag STRING,
  allocate_to_fully_rsv_flag STRING,
  allocate_to_fully_ret_flag STRING,
  terminal_gain_loss_amount DECIMAL(28, 10),
  cip_cost DECIMAL(28, 10),
  ytd_proceeds DECIMAL(28, 10),
  ltd_proceeds DECIMAL(28, 10),
  ltd_cost_of_removal DECIMAL(28, 10),
  eofy_reserve DECIMAL(28, 10),
  prior_eofy_reserve DECIMAL(28, 10),
  eop_adj_cost DECIMAL(28, 10),
  eop_formula_factor DECIMAL(28, 10),
  exclude_proceeds_from_basis STRING,
  retirement_deprn_option STRING,
  terminal_gain_loss_flag STRING,
  super_group_id DECIMAL(15, 0),
  over_depreciate_option STRING,
  disabled_flag STRING,
  old_adjusted_capacity DECIMAL(28, 10),
  dry_hole_flag STRING,
  cash_generating_unit_id DECIMAL(15, 0),
  contract_id DECIMAL(15, 0),
  rate_in_use DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.FA_MC_BOOKS (
  set_of_books_id,
  asset_id,
  book_type_code,
  transaction_header_id_in,
  transaction_header_id_out,
  adjusted_cost,
  cost,
  source_cost,
  original_cost,
  source_original_cost,
  salvage_value,
  adjustment_required_status,
  retirement_pending_flag,
  last_update_date,
  last_updated_by,
  itc_amount,
  itc_basis,
  recoverable_cost,
  last_update_login,
  reval_ceiling,
  period_counter_fully_reserved,
  unrevalued_cost,
  allowed_deprn_limit_amount,
  period_counter_life_complete,
  adjusted_recoverable_cost,
  converted_flag,
  annual_deprn_rounding_flag,
  eofy_adj_cost,
  old_adjusted_cost,
  eofy_formula_factor,
  formula_factor,
  remaining_life1,
  remaining_life2,
  short_fiscal_year_flag,
  group_asset_id,
  reval_amortization_basis,
  itc_amount_id,
  retirement_id,
  tax_request_id,
  basic_rate,
  adjusted_rate,
  bonus_rule,
  ceiling_name,
  adjusted_capacity,
  fully_rsvd_revals_counter,
  idled_flag,
  period_counter_capitalized,
  period_counter_fully_retired,
  production_capacity,
  unit_of_measure,
  percent_salvage_value,
  allowed_deprn_limit,
  annual_rounding_flag,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  date_placed_in_service,
  date_effective,
  deprn_start_date,
  deprn_method_code,
  life_in_months,
  rate_adjustment_factor,
  prorate_convention_code,
  prorate_date,
  cost_change_flag,
  capitalize_flag,
  depreciate_flag,
  date_ineffective,
  conversion_date,
  original_deprn_start_date,
  salvage_type,
  deprn_limit_type,
  reduction_rate,
  reduce_addition_flag,
  reduce_adjustment_flag,
  reduce_retirement_flag,
  recognize_gain_loss,
  recapture_reserve_flag,
  limit_proceeds_flag,
  terminal_gain_loss,
  tracking_method,
  exclude_fully_rsv_flag,
  excess_allocation_option,
  depreciation_option,
  member_rollup_flag,
  allocate_to_fully_rsv_flag,
  allocate_to_fully_ret_flag,
  terminal_gain_loss_amount,
  cip_cost,
  ytd_proceeds,
  ltd_proceeds,
  ltd_cost_of_removal,
  eofy_reserve,
  prior_eofy_reserve,
  eop_adj_cost,
  eop_formula_factor,
  exclude_proceeds_from_basis,
  retirement_deprn_option,
  terminal_gain_loss_flag,
  super_group_id,
  over_depreciate_option,
  disabled_flag,
  old_adjusted_capacity,
  dry_hole_flag,
  cash_generating_unit_id,
  contract_id,
  rate_in_use,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  set_of_books_id,
  asset_id,
  book_type_code,
  transaction_header_id_in,
  transaction_header_id_out,
  adjusted_cost,
  cost,
  source_cost,
  original_cost,
  source_original_cost,
  salvage_value,
  adjustment_required_status,
  retirement_pending_flag,
  last_update_date,
  last_updated_by,
  itc_amount,
  itc_basis,
  recoverable_cost,
  last_update_login,
  reval_ceiling,
  period_counter_fully_reserved,
  unrevalued_cost,
  allowed_deprn_limit_amount,
  period_counter_life_complete,
  adjusted_recoverable_cost,
  converted_flag,
  annual_deprn_rounding_flag,
  eofy_adj_cost,
  old_adjusted_cost,
  eofy_formula_factor,
  formula_factor,
  remaining_life1,
  remaining_life2,
  short_fiscal_year_flag,
  group_asset_id,
  reval_amortization_basis,
  itc_amount_id,
  retirement_id,
  tax_request_id,
  basic_rate,
  adjusted_rate,
  bonus_rule,
  ceiling_name,
  adjusted_capacity,
  fully_rsvd_revals_counter,
  idled_flag,
  period_counter_capitalized,
  period_counter_fully_retired,
  production_capacity,
  unit_of_measure,
  percent_salvage_value,
  allowed_deprn_limit,
  annual_rounding_flag,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  date_placed_in_service,
  date_effective,
  deprn_start_date,
  deprn_method_code,
  life_in_months,
  rate_adjustment_factor,
  prorate_convention_code,
  prorate_date,
  cost_change_flag,
  capitalize_flag,
  depreciate_flag,
  date_ineffective,
  conversion_date,
  original_deprn_start_date,
  salvage_type,
  deprn_limit_type,
  reduction_rate,
  reduce_addition_flag,
  reduce_adjustment_flag,
  reduce_retirement_flag,
  recognize_gain_loss,
  recapture_reserve_flag,
  limit_proceeds_flag,
  terminal_gain_loss,
  tracking_method,
  exclude_fully_rsv_flag,
  excess_allocation_option,
  depreciation_option,
  member_rollup_flag,
  allocate_to_fully_rsv_flag,
  allocate_to_fully_ret_flag,
  terminal_gain_loss_amount,
  cip_cost,
  ytd_proceeds,
  ltd_proceeds,
  ltd_cost_of_removal,
  eofy_reserve,
  prior_eofy_reserve,
  eop_adj_cost,
  eop_formula_factor,
  exclude_proceeds_from_basis,
  retirement_deprn_option,
  terminal_gain_loss_flag,
  super_group_id,
  over_depreciate_option,
  disabled_flag,
  old_adjusted_capacity,
  dry_hole_flag,
  cash_generating_unit_id,
  contract_id,
  rate_in_use,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.FA_MC_BOOKS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fa_mc_books';