DROP TABLE IF EXISTS silver_bec_ods.jtf_rs_salesreps;
CREATE TABLE IF NOT EXISTS silver_bec_ods.jtf_rs_salesreps (
  salesrep_id DECIMAL(15, 0),
  resource_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  sales_credit_type_id DECIMAL(15, 0),
  name STRING,
  status STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  gl_id_rev DECIMAL(15, 0),
  gl_id_freight DECIMAL(15, 0),
  gl_id_rec DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  salesrep_number STRING,
  org_id DECIMAL(15, 0),
  email_address STRING,
  wh_update_date TIMESTAMP,
  person_id DECIMAL(15, 0),
  sales_tax_geocode STRING,
  sales_tax_inside_city_limits STRING,
  object_version_number DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  security_group_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.jtf_rs_salesreps (
  salesrep_id,
  resource_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  sales_credit_type_id,
  `name`,
  status,
  start_date_active,
  end_date_active,
  gl_id_rev,
  gl_id_freight,
  gl_id_rec,
  set_of_books_id,
  salesrep_number,
  org_id,
  email_address,
  wh_update_date,
  person_id,
  sales_tax_geocode,
  sales_tax_inside_city_limits,
  object_version_number,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  salesrep_id,
  resource_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  sales_credit_type_id,
  `name`,
  status,
  start_date_active,
  end_date_active,
  gl_id_rev,
  gl_id_freight,
  gl_id_rec,
  set_of_books_id,
  salesrep_number,
  org_id,
  email_address,
  wh_update_date,
  person_id,
  sales_tax_geocode,
  sales_tax_inside_city_limits,
  object_version_number,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.jtf_rs_salesreps;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'jtf_rs_salesreps';