DROP TABLE IF EXISTS silver_bec_ods.CS_INCIDENTS_ALL_B;
CREATE TABLE IF NOT EXISTS silver_bec_ods.CS_INCIDENTS_ALL_B (
  incident_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  creation_time STRING,
  incident_number STRING,
  incident_date TIMESTAMP,
  open_flag STRING,
  service_entity_id DECIMAL(15, 0),
  incident_status_id DECIMAL(15, 0),
  incident_type_id DECIMAL(15, 0),
  incident_urgency_id DECIMAL(15, 0),
  incident_severity_id DECIMAL(15, 0),
  summary STRING,
  responsible_group_id DECIMAL(15, 0),
  security_level_code STRING,
  incident_owner_id DECIMAL(15, 0),
  classification_code STRING,
  inventory_item_id DECIMAL(15, 0),
  component_inventory_item_id DECIMAL(15, 0),
  customer_id DECIMAL(15, 0),
  original_customer_id DECIMAL(15, 0),
  customer_name STRING,
  bill_to_site_use_id DECIMAL(15, 0),
  purchase_order_num STRING,
  identification_number STRING,
  service_inventory_item_id DECIMAL(15, 0),
  employee_id DECIMAL(15, 0),
  filed_by_employee_flag STRING,
  billable_flag STRING,
  ship_to_site_use_id DECIMAL(15, 0),
  problem_code STRING,
  expected_resolution_date TIMESTAMP,
  actual_resolution_date TIMESTAMP,
  problem_description STRING,
  resolution_description STRING,
  running_totals DECIMAL(28, 10),
  current_contact_person_id DECIMAL(15, 0),
  initiating_person_id DECIMAL(15, 0),
  current_contact_name STRING,
  current_contact_area_code STRING,
  current_contact_telephone STRING,
  current_contact_extension STRING,
  current_contact_email_address STRING,
  current_contact_time_diff DECIMAL(28, 10),
  current_contact_fax_area_code STRING,
  current_contact_fax_number STRING,
  represented_by_employee STRING,
  represented_by_name STRING,
  represented_by_time_difference DECIMAL(28, 10),
  represented_by_area_code STRING,
  represented_by_telephone STRING,
  represented_by_extension STRING,
  represented_by_fax_area_code STRING,
  represented_by_fax_number STRING,
  represented_by_email_address STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  internal_contact_id DECIMAL(15, 0),
  hours_after_gmt DECIMAL(28, 10),
  initiating_time_difference DECIMAL(28, 10),
  customer_product_id DECIMAL(15, 0),
  cp_service_id DECIMAL(15, 0),
  currently_serviced_flag STRING,
  last_customer_callback_time STRING,
  preventive_maintenance_flag STRING,
  bill_to_title STRING,
  bill_to_customer STRING,
  bill_to_address_line_1 STRING,
  bill_to_address_line_2 STRING,
  bill_to_address_line_3 STRING,
  bill_to_contact STRING,
  ship_to_title STRING,
  ship_to_customer STRING,
  ship_to_address_line_1 STRING,
  ship_to_address_line_2 STRING,
  ship_to_address_line_3 STRING,
  ship_to_contact STRING,
  install_title STRING,
  install_customer STRING,
  install_address_line_1 STRING,
  install_address_line_2 STRING,
  install_address_line_3 STRING,
  install_site_use_id DECIMAL(15, 0),
  bill_to_contact_id DECIMAL(15, 0),
  ship_to_contact_id DECIMAL(15, 0),
  initiating_name STRING,
  initiating_area_code STRING,
  initiating_telephone STRING,
  initiating_extension STRING,
  initiating_fax_area_code STRING,
  initiating_fax_number STRING,
  product_name STRING,
  product_description STRING,
  current_serial_number STRING,
  product_revision STRING,
  customer_number STRING,
  system_id DECIMAL(15, 0),
  incident_attribute_1 STRING,
  incident_attribute_2 STRING,
  incident_attribute_3 STRING,
  incident_attribute_4 STRING,
  incident_attribute_5 STRING,
  incident_attribute_6 STRING,
  incident_attribute_7 STRING,
  incident_attribute_8 STRING,
  incident_attribute_9 STRING,
  incident_attribute_10 STRING,
  incident_attribute_11 STRING,
  incident_attribute_12 STRING,
  incident_attribute_13 STRING,
  incident_attribute_14 STRING,
  incident_attribute_15 STRING,
  incident_context STRING,
  record_is_valid_flag STRING,
  incident_comments STRING,
  resolution_code STRING,
  rma_number DECIMAL(15, 0),
  rma_header_id DECIMAL(15, 0),
  rma_flag STRING,
  org_id DECIMAL(15, 0),
  original_order_number DECIMAL(28, 10),
  workflow_process_id DECIMAL(15, 0),
  web_entry_flag STRING,
  close_date TIMESTAMP,
  publish_flag STRING,
  make_public_problem STRING,
  make_public_resolution STRING,
  estimate_id DECIMAL(15, 0),
  estimate_business_group_id DECIMAL(15, 0),
  interfaced_to_depot_flag STRING,
  qa_collection_id DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  contract_id DECIMAL(15, 0),
  contract_number STRING,
  contract_service_id DECIMAL(15, 0),
  resource_type STRING,
  resource_subtype_id DECIMAL(15, 0),
  account_id DECIMAL(15, 0),
  kb_type STRING,
  kb_solution_id STRING,
  time_zone_id DECIMAL(15, 0),
  time_difference DECIMAL(28, 10),
  customer_po_number STRING,
  owner_group_id DECIMAL(28, 10),
  customer_ticket_number STRING,
  obligation_date TIMESTAMP,
  site_id DECIMAL(15, 0),
  customer_site_id DECIMAL(15, 0),
  caller_type STRING,
  platform_version_id DECIMAL(15, 0),
  object_version_number INT,
  cp_component_id DECIMAL(15, 0),
  cp_component_version_id DECIMAL(15, 0),
  cp_subcomponent_id DECIMAL(15, 0),
  cp_subcomponent_version_id DECIMAL(15, 0),
  platform_id DECIMAL(15, 0),
  language_id DECIMAL(15, 0),
  territory_id DECIMAL(15, 0),
  cp_revision_id DECIMAL(15, 0),
  inv_item_revision STRING,
  inv_component_id DECIMAL(15, 0),
  inv_component_version STRING,
  inv_subcomponent_id DECIMAL(15, 0),
  inv_subcomponent_version STRING,
  inv_organization_id DECIMAL(15, 0),
  security_group_id DECIMAL(15, 0),
  upgraded_status_flag1 STRING,
  upgraded_status_flag2 STRING,
  upgraded_status_flag3 STRING,
  orig_system_reference STRING,
  orig_system_reference_id DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  project_number STRING,
  platform_version STRING,
  db_version STRING,
  cust_pref_lang_id DECIMAL(15, 0),
  tier STRING,
  tier_version STRING,
  category_id DECIMAL(15, 0),
  operating_system STRING,
  operating_system_version STRING,
  `database` STRING,
  group_type STRING,
  group_territory_id DECIMAL(15, 0),
  owner_assigned_time TIMESTAMP,
  owner_assigned_flag STRING,
  inv_platform_org_id DECIMAL(15, 0),
  component_version STRING,
  subcomponent_version STRING,
  comm_pref_code STRING,
  last_update_channel STRING,
  cust_pref_lang_code STRING,
  ERROR_CODE STRING,
  CATEGORY_SET_ID DECIMAL(15, 0),
  EXTERNAL_REFERENCE STRING,
  INCIDENT_OCCURRED_DATE TIMESTAMP,
  INCIDENT_RESOLVED_DATE TIMESTAMP,
  INC_RESPONDED_BY_DATE TIMESTAMP,
  INCIDENT_LOCATION_ID DECIMAL(15, 0),
  INCIDENT_ADDRESS STRING,
  INCIDENT_CITY STRING,
  INCIDENT_STATE STRING,
  INCIDENT_COUNTRY STRING,
  INCIDENT_PROVINCE STRING,
  INCIDENT_POSTAL_CODE STRING,
  INCIDENT_COUNTY STRING,
  SR_CREATION_CHANNEL STRING,
  DEF_DEFECT_ID DECIMAL(15, 0),
  DEF_DEFECT_ID2 DECIMAL(15, 0),
  CREDIT_CARD_NUMBER STRING,
  CREDIT_CARD_TYPE_CODE STRING,
  CREDIT_CARD_EXPIRATION_DATE TIMESTAMP,
  CREDIT_CARD_HOLDER_FNAME STRING,
  CREDIT_CARD_HOLDER_MNAME STRING,
  CREDIT_CARD_HOLDER_LNAME STRING,
  CREDIT_CARD_ID DECIMAL(15, 0),
  EXTERNAL_ATTRIBUTE_1 STRING,
  EXTERNAL_ATTRIBUTE_2 STRING,
  EXTERNAL_ATTRIBUTE_3 STRING,
  EXTERNAL_ATTRIBUTE_4 STRING,
  EXTERNAL_ATTRIBUTE_5 STRING,
  EXTERNAL_ATTRIBUTE_6 STRING,
  EXTERNAL_ATTRIBUTE_7 STRING,
  EXTERNAL_ATTRIBUTE_8 STRING,
  EXTERNAL_ATTRIBUTE_9 STRING,
  EXTERNAL_ATTRIBUTE_10 STRING,
  EXTERNAL_ATTRIBUTE_11 STRING,
  EXTERNAL_ATTRIBUTE_12 STRING,
  EXTERNAL_ATTRIBUTE_13 STRING,
  EXTERNAL_ATTRIBUTE_14 STRING,
  EXTERNAL_ATTRIBUTE_15 STRING,
  EXTERNAL_CONTEXT STRING,
  LAST_UPDATE_PROGRAM_CODE STRING,
  CREATION_PROGRAM_CODE STRING,
  COVERAGE_TYPE STRING,
  BILL_TO_ACCOUNT_ID DECIMAL(15, 0),
  SHIP_TO_ACCOUNT_ID DECIMAL(15, 0),
  CUSTOMER_EMAIL_ID DECIMAL(15, 0),
  CUSTOMER_PHONE_ID DECIMAL(15, 0),
  BILL_TO_PARTY_ID DECIMAL(15, 0),
  SHIP_TO_PARTY_ID DECIMAL(15, 0),
  BILL_TO_SITE_ID DECIMAL(15, 0),
  SHIP_TO_SITE_ID DECIMAL(15, 0),
  PROGRAM_LOGIN_ID DECIMAL(15, 0),
  STATUS_FLAG STRING,
  PRIMARY_CONTACT_ID DECIMAL(15, 0),
  INCIDENT_POINT_OF_INTEREST STRING,
  INCIDENT_CROSS_STREET STRING,
  INCIDENT_DIRECTION_QUALIFIER STRING,
  INCIDENT_DISTANCE_QUALIFIER STRING,
  INCIDENT_DISTANCE_QUAL_UOM STRING,
  INCIDENT_ADDRESS2 STRING,
  INCIDENT_ADDRESS3 STRING,
  INCIDENT_ADDRESS4 STRING,
  INCIDENT_ADDRESS_STYLE STRING,
  INCIDENT_ADDR_LINES_PHONETIC STRING,
  INCIDENT_PO_BOX_NUMBER STRING,
  INCIDENT_HOUSE_NUMBER STRING,
  INCIDENT_STREET_SUFFIX STRING,
  INCIDENT_STREET STRING,
  INCIDENT_STREET_NUMBER STRING,
  INCIDENT_FLOOR STRING,
  INCIDENT_SUITE STRING,
  INCIDENT_POSTAL_PLUS4_CODE STRING,
  INCIDENT_POSITION STRING,
  INCIDENT_LOCATION_DIRECTIONS STRING,
  INCIDENT_LOCATION_DESCRIPTION STRING,
  INSTALL_SITE_ID DECIMAL(15, 0),
  OWNING_DEPARTMENT_ID DECIMAL(15, 0),
  ITEM_SERIAL_NUMBER STRING,
  INCIDENT_LOCATION_TYPE STRING,
  INCIDENT_LAST_MODIFIED_DATE TIMESTAMP,
  UNASSIGNED_INDICATOR STRING,
  MAINT_ORGANIZATION_ID DECIMAL(15, 0),
  INSTRUMENT_PAYMENT_USE_ID DECIMAL(15, 0),
  PROJECT_TASK_ID DECIMAL(15, 0),
  SLA_DATE_1 TIMESTAMP,
  SLA_DATE_2 TIMESTAMP,
  SLA_DATE_3 TIMESTAMP,
  SLA_DATE_4 TIMESTAMP,
  SLA_DATE_5 TIMESTAMP,
  SLA_DATE_6 TIMESTAMP,
  SLA_DURATION_1 DECIMAL(15, 2),
  SLA_DURATION_2 DECIMAL(15, 2),
  PRICE_LIST_HEADER_ID DECIMAL(15, 0),
  EXPENDITURE_ORG_ID DECIMAL(15, 0),
  BUSINESS_PROCESS_ID DECIMAL(15, 0),
  ORDER_HEADER_ID DECIMAL(15, 0),
  REC_PROBLEM_CODE STRING,
  REC_RESOLUTION_CODE STRING,
  TEMPLATE_ID DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.CS_INCIDENTS_ALL_B (
  incident_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  creation_time,
  incident_number,
  incident_date,
  open_flag,
  service_entity_id,
  incident_status_id,
  incident_type_id,
  incident_urgency_id,
  incident_severity_id,
  summary,
  responsible_group_id,
  security_level_code,
  incident_owner_id,
  classification_code,
  inventory_item_id,
  component_inventory_item_id,
  customer_id,
  original_customer_id,
  customer_name,
  bill_to_site_use_id,
  purchase_order_num,
  identification_number,
  service_inventory_item_id,
  employee_id,
  filed_by_employee_flag,
  billable_flag,
  ship_to_site_use_id,
  problem_code,
  expected_resolution_date,
  actual_resolution_date,
  problem_description,
  resolution_description,
  running_totals,
  current_contact_person_id,
  initiating_person_id,
  current_contact_name,
  current_contact_area_code,
  current_contact_telephone,
  current_contact_extension,
  current_contact_email_address,
  current_contact_time_diff,
  current_contact_fax_area_code,
  current_contact_fax_number,
  represented_by_employee,
  represented_by_name,
  represented_by_time_difference,
  represented_by_area_code,
  represented_by_telephone,
  represented_by_extension,
  represented_by_fax_area_code,
  represented_by_fax_number,
  represented_by_email_address,
  start_date_active,
  end_date_active,
  internal_contact_id,
  hours_after_gmt,
  initiating_time_difference,
  customer_product_id,
  cp_service_id,
  currently_serviced_flag,
  last_customer_callback_time,
  preventive_maintenance_flag,
  bill_to_title,
  bill_to_customer,
  bill_to_address_line_1,
  bill_to_address_line_2,
  bill_to_address_line_3,
  bill_to_contact,
  ship_to_title,
  ship_to_customer,
  ship_to_address_line_1,
  ship_to_address_line_2,
  ship_to_address_line_3,
  ship_to_contact,
  install_title,
  install_customer,
  install_address_line_1,
  install_address_line_2,
  install_address_line_3,
  install_site_use_id,
  bill_to_contact_id,
  ship_to_contact_id,
  initiating_name,
  initiating_area_code,
  initiating_telephone,
  initiating_extension,
  initiating_fax_area_code,
  initiating_fax_number,
  product_name,
  product_description,
  current_serial_number,
  product_revision,
  customer_number,
  system_id,
  incident_attribute_1,
  incident_attribute_2,
  incident_attribute_3,
  incident_attribute_4,
  incident_attribute_5,
  incident_attribute_6,
  incident_attribute_7,
  incident_attribute_8,
  incident_attribute_9,
  incident_attribute_10,
  incident_attribute_11,
  incident_attribute_12,
  incident_attribute_13,
  incident_attribute_14,
  incident_attribute_15,
  incident_context,
  record_is_valid_flag,
  incident_comments,
  resolution_code,
  rma_number,
  rma_header_id,
  rma_flag,
  org_id,
  original_order_number,
  workflow_process_id,
  web_entry_flag,
  close_date,
  publish_flag,
  make_public_problem,
  make_public_resolution,
  estimate_id,
  estimate_business_group_id,
  interfaced_to_depot_flag,
  qa_collection_id,
  project_id,
  task_id,
  contract_id,
  contract_number,
  contract_service_id,
  resource_type,
  resource_subtype_id,
  account_id,
  kb_type,
  kb_solution_id,
  time_zone_id,
  time_difference,
  customer_po_number,
  owner_group_id,
  customer_ticket_number,
  obligation_date,
  site_id,
  customer_site_id,
  caller_type,
  platform_version_id,
  object_version_number,
  cp_component_id,
  cp_component_version_id,
  cp_subcomponent_id,
  cp_subcomponent_version_id,
  platform_id,
  language_id,
  territory_id,
  cp_revision_id,
  inv_item_revision,
  inv_component_id,
  inv_component_version,
  inv_subcomponent_id,
  inv_subcomponent_version,
  inv_organization_id,
  security_group_id,
  upgraded_status_flag1,
  upgraded_status_flag2,
  upgraded_status_flag3,
  orig_system_reference,
  orig_system_reference_id,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  project_number,
  platform_version,
  db_version,
  cust_pref_lang_id,
  tier,
  tier_version,
  category_id,
  operating_system,
  operating_system_version,
  `database`,
  group_type,
  group_territory_id,
  owner_assigned_time,
  owner_assigned_flag,
  inv_platform_org_id,
  component_version,
  subcomponent_version,
  comm_pref_code,
  last_update_channel,
  cust_pref_lang_code,
  error_code,
  category_set_id,
  external_reference,
  incident_occurred_date,
  incident_resolved_date,
  inc_responded_by_date,
  incident_location_id,
  incident_address,
  incident_city,
  incident_state,
  incident_country,
  incident_province,
  incident_postal_code,
  incident_county,
  sr_creation_channel,
  def_defect_id,
  def_defect_id2,
  credit_card_number,
  credit_card_type_code,
  credit_card_expiration_date,
  credit_card_holder_fname,
  credit_card_holder_mname,
  credit_card_holder_lname,
  credit_card_id,
  external_attribute_1,
  external_attribute_2,
  external_attribute_3,
  external_attribute_4,
  external_attribute_5,
  external_attribute_6,
  external_attribute_7,
  external_attribute_8,
  external_attribute_9,
  external_attribute_10,
  external_attribute_11,
  external_attribute_12,
  external_attribute_13,
  external_attribute_14,
  external_attribute_15,
  external_context,
  last_update_program_code,
  creation_program_code,
  coverage_type,
  bill_to_account_id,
  ship_to_account_id,
  customer_email_id,
  customer_phone_id,
  bill_to_party_id,
  ship_to_party_id,
  bill_to_site_id,
  ship_to_site_id,
  program_login_id,
  status_flag,
  primary_contact_id,
  incident_point_of_interest,
  incident_cross_street,
  incident_direction_qualifier,
  incident_distance_qualifier,
  incident_distance_qual_uom,
  incident_address2,
  incident_address3,
  incident_address4,
  incident_address_style,
  incident_addr_lines_phonetic,
  incident_po_box_number,
  incident_house_number,
  incident_street_suffix,
  incident_street,
  incident_street_number,
  incident_floor,
  incident_suite,
  incident_postal_plus4_code,
  incident_position,
  incident_location_directions,
  incident_location_description,
  install_site_id,
  owning_department_id,
  item_serial_number,
  incident_location_type,
  incident_last_modified_date,
  unassigned_indicator,
  maint_organization_id,
  instrument_payment_use_id,
  project_task_id,
  sla_date_1,
  sla_date_2,
  sla_date_3,
  sla_date_4,
  sla_date_5,
  sla_date_6,
  sla_duration_1,
  sla_duration_2,
  price_list_header_id,
  expenditure_org_id,
  business_process_id,
  order_header_id,
  rec_problem_code,
  rec_resolution_code,
  template_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  incident_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  creation_time,
  incident_number,
  incident_date,
  open_flag,
  service_entity_id,
  incident_status_id,
  incident_type_id,
  incident_urgency_id,
  incident_severity_id,
  summary,
  responsible_group_id,
  security_level_code,
  incident_owner_id,
  classification_code,
  inventory_item_id,
  component_inventory_item_id,
  customer_id,
  original_customer_id,
  customer_name,
  bill_to_site_use_id,
  purchase_order_num,
  identification_number,
  service_inventory_item_id,
  employee_id,
  filed_by_employee_flag,
  billable_flag,
  ship_to_site_use_id,
  problem_code,
  expected_resolution_date,
  actual_resolution_date,
  problem_description,
  resolution_description,
  running_totals,
  current_contact_person_id,
  initiating_person_id,
  current_contact_name,
  current_contact_area_code,
  current_contact_telephone,
  current_contact_extension,
  current_contact_email_address,
  current_contact_time_diff,
  current_contact_fax_area_code,
  current_contact_fax_number,
  represented_by_employee,
  represented_by_name,
  represented_by_time_difference,
  represented_by_area_code,
  represented_by_telephone,
  represented_by_extension,
  represented_by_fax_area_code,
  represented_by_fax_number,
  represented_by_email_address,
  start_date_active,
  end_date_active,
  internal_contact_id,
  hours_after_gmt,
  initiating_time_difference,
  customer_product_id,
  cp_service_id,
  currently_serviced_flag,
  last_customer_callback_time,
  preventive_maintenance_flag,
  bill_to_title,
  bill_to_customer,
  bill_to_address_line_1,
  bill_to_address_line_2,
  bill_to_address_line_3,
  bill_to_contact,
  ship_to_title,
  ship_to_customer,
  ship_to_address_line_1,
  ship_to_address_line_2,
  ship_to_address_line_3,
  ship_to_contact,
  install_title,
  install_customer,
  install_address_line_1,
  install_address_line_2,
  install_address_line_3,
  install_site_use_id,
  bill_to_contact_id,
  ship_to_contact_id,
  initiating_name,
  initiating_area_code,
  initiating_telephone,
  initiating_extension,
  initiating_fax_area_code,
  initiating_fax_number,
  product_name,
  product_description,
  current_serial_number,
  product_revision,
  customer_number,
  system_id,
  incident_attribute_1,
  incident_attribute_2,
  incident_attribute_3,
  incident_attribute_4,
  incident_attribute_5,
  incident_attribute_6,
  incident_attribute_7,
  incident_attribute_8,
  incident_attribute_9,
  incident_attribute_10,
  incident_attribute_11,
  incident_attribute_12,
  incident_attribute_13,
  incident_attribute_14,
  incident_attribute_15,
  incident_context,
  record_is_valid_flag,
  incident_comments,
  resolution_code,
  rma_number,
  rma_header_id,
  rma_flag,
  org_id,
  original_order_number,
  workflow_process_id,
  web_entry_flag,
  close_date,
  publish_flag,
  make_public_problem,
  make_public_resolution,
  estimate_id,
  estimate_business_group_id,
  interfaced_to_depot_flag,
  qa_collection_id,
  project_id,
  task_id,
  contract_id,
  contract_number,
  contract_service_id,
  resource_type,
  resource_subtype_id,
  account_id,
  kb_type,
  kb_solution_id,
  time_zone_id,
  time_difference,
  customer_po_number,
  owner_group_id,
  customer_ticket_number,
  obligation_date,
  site_id,
  customer_site_id,
  caller_type,
  platform_version_id,
  object_version_number,
  cp_component_id,
  cp_component_version_id,
  cp_subcomponent_id,
  cp_subcomponent_version_id,
  platform_id,
  language_id,
  territory_id,
  cp_revision_id,
  inv_item_revision,
  inv_component_id,
  inv_component_version,
  inv_subcomponent_id,
  inv_subcomponent_version,
  inv_organization_id,
  security_group_id,
  upgraded_status_flag1,
  upgraded_status_flag2,
  upgraded_status_flag3,
  orig_system_reference,
  orig_system_reference_id,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  project_number,
  platform_version,
  db_version,
  cust_pref_lang_id,
  tier,
  tier_version,
  category_id,
  operating_system,
  operating_system_version,
  `database`,
  group_type,
  group_territory_id,
  owner_assigned_time,
  owner_assigned_flag,
  inv_platform_org_id,
  component_version,
  subcomponent_version,
  comm_pref_code,
  last_update_channel,
  cust_pref_lang_code,
  error_code,
  category_set_id,
  external_reference,
  incident_occurred_date,
  incident_resolved_date,
  inc_responded_by_date,
  incident_location_id,
  incident_address,
  incident_city,
  incident_state,
  incident_country,
  incident_province,
  incident_postal_code,
  incident_county,
  sr_creation_channel,
  def_defect_id,
  def_defect_id2,
  credit_card_number,
  credit_card_type_code,
  credit_card_expiration_date,
  credit_card_holder_fname,
  credit_card_holder_mname,
  credit_card_holder_lname,
  credit_card_id,
  external_attribute_1,
  external_attribute_2,
  external_attribute_3,
  external_attribute_4,
  external_attribute_5,
  external_attribute_6,
  external_attribute_7,
  external_attribute_8,
  external_attribute_9,
  external_attribute_10,
  external_attribute_11,
  external_attribute_12,
  external_attribute_13,
  external_attribute_14,
  external_attribute_15,
  external_context,
  last_update_program_code,
  creation_program_code,
  coverage_type,
  bill_to_account_id,
  ship_to_account_id,
  customer_email_id,
  customer_phone_id,
  bill_to_party_id,
  ship_to_party_id,
  bill_to_site_id,
  ship_to_site_id,
  program_login_id,
  status_flag,
  primary_contact_id,
  incident_point_of_interest,
  incident_cross_street,
  incident_direction_qualifier,
  incident_distance_qualifier,
  incident_distance_qual_uom,
  incident_address2,
  incident_address3,
  incident_address4,
  incident_address_style,
  incident_addr_lines_phonetic,
  incident_po_box_number,
  incident_house_number,
  incident_street_suffix,
  incident_street,
  incident_street_number,
  incident_floor,
  incident_suite,
  incident_postal_plus4_code,
  incident_position,
  incident_location_directions,
  incident_location_description,
  install_site_id,
  owning_department_id,
  item_serial_number,
  incident_location_type,
  incident_last_modified_date,
  unassigned_indicator,
  maint_organization_id,
  instrument_payment_use_id,
  project_task_id,
  sla_date_1,
  sla_date_2,
  sla_date_3,
  sla_date_4,
  sla_date_5,
  sla_date_6,
  sla_duration_1,
  sla_duration_2,
  price_list_header_id,
  expenditure_org_id,
  business_process_id,
  order_header_id,
  rec_problem_code,
  rec_resolution_code,
  template_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(kca_seq_id, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.CS_INCIDENTS_ALL_B;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cs_incidents_all_b';