DROP TABLE IF EXISTS silver_bec_ods.MSC_PLANS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MSC_PLANS (
  PLAN_ID DECIMAL(15, 0),
  COMPILE_DESIGNATOR STRING,
  SR_INSTANCE_ID DECIMAL(15, 0),
  APPEND_PLANNED_ORDERS DECIMAL(15, 0),
  ASSIGNMENT_SET_ID DECIMAL(15, 0),
  CURR_APPEND_PLANNED_ORDERS DECIMAL(15, 0),
  CURR_ASSIGNMENT_SET_ID DECIMAL(15, 0),
  CURR_BILL_OF_RESOURCES STRING,
  CURR_CONSIDER_PO DECIMAL(15, 0),
  CURR_CONSIDER_RESERVATIONS DECIMAL(15, 0),
  CURR_CONSIDER_WIP DECIMAL(15, 0),
  CURR_CUTOFF_DATE TIMESTAMP,
  CURR_DEMAND_TIME_FENCE_FLAG DECIMAL(15, 0),
  CURR_HARD_PEGGING_LEVEL DECIMAL(15, 0),
  CURR_FULL_PEGGING DECIMAL(15, 0),
  CURR_INCLUDED_ITEMS DECIMAL(15, 0),
  CURR_OPERATION_SCHEDULE_TYPE DECIMAL(15, 0),
  CURR_OVERWRITE_OPTION DECIMAL(15, 0),
  CURR_PART_INCLUDE_TYPE DECIMAL(15, 0),
  CURR_PLANNING_TIME_FENCE_FLAG DECIMAL(15, 0),
  CURR_PLAN_CAPACITY_FLAG DECIMAL(15, 0),
  CURR_PLAN_SAFETY_STOCK DECIMAL(15, 0),
  CURR_PLAN_TYPE DECIMAL(15, 0),
  CURR_RESERVATION_LEVEL DECIMAL(15, 0),
  CURR_SCHEDULE_DESIGNATOR STRING,
  CURR_SCHEDULE_TYPE DECIMAL(15, 0),
  CURR_SIMULATION_SET STRING,
  CURR_SNAPSHOT_LOCK DECIMAL(15, 0),
  CURR_SPLIT_DEMANDS DECIMAL(15, 0),
  CURR_START_DATE TIMESTAMP,
  CUTOFF_DATE TIMESTAMP,
  DAILY_CUTOFF_BUCKET DECIMAL(15, 0),
  DAILY_ITEM_AGGREGATION_LEVEL DECIMAL(15, 0),
  DAILY_MATERIAL_CONSTRAINTS DECIMAL(15, 0),
  DAILY_RESOURCE_CONSTRAINTS DECIMAL(15, 0),
  DAILY_RES_AGGREGATION_LEVEL DECIMAL(15, 0),
  DAILY_TRANS_CONSTRAINTS DECIMAL(15, 0),
  DATA_COMPLETION_DATE TIMESTAMP,
  DATA_START_DATE TIMESTAMP,
  DEMAND_TIME_FENCE_FLAG DECIMAL(15, 0),
  DESCRIPTION STRING,
  DMD_LATENESS_PENALTY_COST DECIMAL(15, 0),
  HARD_PEGGING_LEVEL DECIMAL(15, 0),
  FULL_PEGGING DECIMAL(15, 0),
  HOUR_CUTOFF_BUCKET DECIMAL(15, 0),
  INCLUDED_ITEMS DECIMAL(15, 0),
  MIN_CUTOFF_BUCKET DECIMAL(15, 0),
  MONTHLY_CUTOFF_BUCKET DECIMAL(15, 0),
  OBJECTIVE_WEIGHT_1 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_10 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_2 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_3 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_4 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_5 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_6 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_7 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_8 DECIMAL(28, 10),
  OBJECTIVE_WEIGHT_9 DECIMAL(28, 10),
  OPERATION_SCHEDULE_TYPE DECIMAL(15, 0),
  ORGANIZATION_ID DECIMAL(15, 0),
  ORGANIZATION_SELECTION DECIMAL(15, 0),
  OVERWRITE_OPTION DECIMAL(15, 0),
  PART_INCLUDE_TYPE DECIMAL(15, 0),
  PENALTY_COST_1 DECIMAL(28, 10),
  PENALTY_COST_10 DECIMAL(28, 10),
  PENALTY_COST_2 DECIMAL(28, 10),
  PENALTY_COST_3 DECIMAL(28, 10),
  PENALTY_COST_4 DECIMAL(28, 10),
  PENALTY_COST_5 DECIMAL(28, 10),
  PENALTY_COST_6 DECIMAL(28, 10),
  PENALTY_COST_7 DECIMAL(28, 10),
  PENALTY_COST_8 DECIMAL(28, 10),
  PENALTY_COST_9 DECIMAL(28, 10),
  PLANNED_REFRESHES STRING,
  PLANNING_TIME_FENCE_FLAG DECIMAL(15, 0),
  PLAN_CAPACITY_FLAG DECIMAL(15, 0),
  PLAN_COMPLETION_DATE TIMESTAMP,
  PLAN_START_DATE TIMESTAMP,
  PLAN_TYPE DECIMAL(15, 0),
  QTRLY_CUTOFF_BUCKET DECIMAL(15, 0),
  RESERVATION_LEVEL DECIMAL(15, 0),
  RESOURCE_OVER_UTIL_COST DECIMAL(28, 10),
  SCHEDULE_DESIGNATOR STRING,
  SCHEDULE_TYPE DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_1 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_10 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_2 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_3 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_4 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_5 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_6 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_7 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_8 DECIMAL(15, 0),
  SLACK_ALLOWED_FLAG_9 DECIMAL(15, 0),
  SNAPSHOT_LOCK DECIMAL(15, 0),
  SPLIT_DEMANDS DECIMAL(15, 0),
  START_DATE TIMESTAMP,
  SUPPLIER_CAP_OVER_UTIL_COST DECIMAL(15, 0),
  WEEKLY_CUTOFF_BUCKET DECIMAL(15, 0),
  WEEKLY_ITEM_AGGREGATION_LEVEL DECIMAL(15, 0),
  WEEKLY_MATERIAL_CONSTRAINTS DECIMAL(15, 0),
  WEEKLY_RESOURCE_CONSTRAINTS DECIMAL(15, 0),
  WEEKLY_RES_AGGREGATION_LEVEL DECIMAL(15, 0),
  WEEKLY_TRANS_CONSTRAINTS DECIMAL(15, 0),
  OPTIMIZE_FLAG DECIMAL(15, 0),
  SCHEDULE_FLAG DECIMAL(15, 0),
  ONLINE_PLANNER_START_DATE TIMESTAMP,
  ONLINE_PLANNER_COMPLETION_DATE TIMESTAMP,
  TRANSPORT_CAP_OVER_UTIL_COST DECIMAL(28, 10),
  BILL_OF_RESOURCES STRING,
  SIMULATION_SET STRING,
  CONSIDER_WIP DECIMAL(15, 0),
  CONSIDER_PO DECIMAL(15, 0),
  PLAN_SAFETY_STOCK DECIMAL(28, 10),
  CONSIDER_RESERVATIONS DECIMAL(15, 0),
  CURR_ENFORCE_DEM_DUE_DATES DECIMAL(15, 0),
  ENFORCE_DEM_DUE_DATES DECIMAL(15, 0),
  PLANNED_RESOURCES DECIMAL(15, 0),
  CURR_PLANNED_RESOURCES DECIMAL(15, 0),
  DEM_PRIORITY_RULE_ID DECIMAL(15, 0),
  CURR_DEM_PRIORITY_RULE_ID DECIMAL(15, 0),
  DAILY_RTG_AGGREGATION_LEVEL DECIMAL(15, 0),
  WEEKLY_RTG_AGGREGATION_LEVEL DECIMAL(15, 0),
  PERIOD_RTG_AGGREGATION_LEVEL DECIMAL(15, 0),
  PERIOD_CUTOFF_BUCKET DECIMAL(15, 0),
  LOT_FOR_LOT_FLAG DECIMAL(15, 0),
  ENFORCE_CAP_CONSTRAINTS DECIMAL(15, 0),
  CURR_ENFORCE_CAP_CONSTRAINTS DECIMAL(15, 0),
  SERVICE_LEVEL DECIMAL(15, 0),
  BOTTLENECK_RES_GROUP STRING,
  CURR_BOTTLENECK_RES_GROUP STRING,
  PERIOD_MATERIAL_CONSTRAINTS DECIMAL(15, 0),
  PERIOD_RESOURCE_CONSTRAINTS DECIMAL(15, 0),
  PERIOD_TRANS_CONSTRAINTS DECIMAL(15, 0),
  PERIOD_ITEM_AGGREGATION_LEVEL DECIMAL(15, 0),
  PERIOD_RES_AGGREGATION_LEVEL DECIMAL(15, 0),
  LAST_UPDATE_DATE TIMESTAMP,
  LAST_UPDATED_BY DECIMAL(15, 0),
  CREATION_DATE TIMESTAMP,
  LOT_FOR_LOT DECIMAL(15, 0),
  CREATED_BY DECIMAL(15, 0),
  LAST_UPDATE_LOGIN DECIMAL(15, 0),
  ATTRIBUTE1 STRING,
  ATTRIBUTE2 STRING,
  ATTRIBUTE3 STRING,
  ATTRIBUTE4 STRING,
  ATTRIBUTE5 STRING,
  ATTRIBUTE6 STRING,
  ATTRIBUTE7 STRING,
  ATTRIBUTE8 STRING,
  ATTRIBUTE9 STRING,
  ATTRIBUTE10 STRING,
  ATTRIBUTE11 STRING,
  ATTRIBUTE12 STRING,
  ATTRIBUTE13 STRING,
  ATTRIBUTE14 STRING,
  ATTRIBUTE15 STRING,
  ATTRIBUTE_CATEGORY STRING,
  REQUEST_ID DECIMAL(15, 0),
  PROGRAM_APPLICATION_ID DECIMAL(15, 0),
  PROGRAM_ID DECIMAL(15, 0),
  PROGRAM_UPDATE_DATE TIMESTAMP,
  MIN_WF_EXCEPT_ID DECIMAL(15, 0),
  MAX_WF_EXCEPT_ID DECIMAL(15, 0),
  ONLINE_REPLAN DECIMAL(15, 0),
  REFRESH_NUMBER DECIMAL(15, 0),
  REVISION STRING,
  PARENT_PLAN_ID DECIMAL(15, 0),
  STATUS DECIMAL(15, 0),
  PRODUCTION_FLAG DECIMAL(15, 0),
  COMPANY_AGG_LEVEL DECIMAL(15, 0),
  TP_AGG_LEVEL DECIMAL(15, 0),
  PRODUCT_AGG_LEVEL DECIMAL(15, 0),
  PURGE DECIMAL(15, 0),
  ENFORCE_SL_CONSTRAINTS DECIMAL(15, 0),
  CURR_ENFORCE_SL_CONSTRAINTS DECIMAL(15, 0),
  PLAN_INVENTORY_POINT DECIMAL(15, 0),
  ENABLE_CLOSEST_QTY_PEGGING DECIMAL(15, 0),
  CURR_CLOSEST_QTY_PEG DECIMAL(15, 0),
  ENABLE_PRIORITY_PEGGING DECIMAL(15, 0),
  CURR_PRIORITY_PEGGING DECIMAL(15, 0),
  ENFORCE_SRC_CONSTRAINTS DECIMAL(15, 0),
  CURR_ENFORCE_SRC_CONSTRAINTS DECIMAL(15, 0),
  BACKWARD_DAYS DECIMAL(15, 0),
  CURR_BACKWARD_DAYS DECIMAL(15, 0),
  FORWARD_DAYS DECIMAL(15, 0),
  CURR_FORWARD_DAYS DECIMAL(15, 0),
  SUMMARY_FLAG DECIMAL(15, 0),
  USE_ALTERNATE_RESOURCES DECIMAL(15, 0),
  USE_END_ITEM_SUBSTITUTIONS DECIMAL(15, 0),
  USE_ALTERNATE_BOM_ROUTING DECIMAL(15, 0),
  USE_SUBSTITUTE_COMPONENTS DECIMAL(15, 0),
  USE_ALTERNATE_SOURCES DECIMAL(15, 0),
  SUBSTITUTION_DESIGNATOR STRING,
  KPI_REFRESH DECIMAL(15, 0),
  DISPLAY_KPI DECIMAL(15, 0),
  FORECAST_ALLOCATION_METHOD DECIMAL(15, 0),
  FORECAST_CONSUMPTION_METHOD DECIMAL(15, 0),
  COPY_PLAN_ID DECIMAL(15, 0),
  EXPLODE_FORECAST DECIMAL(15, 0),
  FORECAST_ASSIGNMENT_SET_ID DECIMAL(15, 0),
  ENFORCE_SUP_CAP_CONSTRAINTS DECIMAL(15, 0),
  ENFORCE_PUR_LT_CONSTRAINTS DECIMAL(15, 0),
  TGT_TL_UTIL_PCT DECIMAL(15, 0),
  MIN_TL_UTIL_PCT DECIMAL(15, 0),
  LOAD_SCHED_TIME_FENCE_DAYS DECIMAL(15, 0),
  LOAD_SCHEDULING_DAYS DECIMAL(15, 0),
  DAILY_ALLOC_BUCKETS DECIMAL(15, 0),
  WKS_PER_WKLY_ALLOC_BUCKET DECIMAL(15, 0),
  DMD_PRI_RULE_SET_ID DECIMAL(15, 0),
  CIRC_SRCING_SURPLUS_DAYS DECIMAL(15, 0),
  SUPPLY_SCHED_ITF DECIMAL(15, 0),
  INCLUDE_CRITICAL_COMPONENTS DECIMAL(15, 0),
  SCHEDULE_BY DECIMAL(15, 0),
  PUBLISH_FCST_VERSION DECIMAL(15, 0),
  RELEASE_RESCHEDULES DECIMAL(15, 0),
  SAFETY_STK_CHANGE_INTERVAL DECIMAL(15, 0),
  SAFETY_STK_THRESHOLD_PCT DECIMAL(15, 0),
  COPY_PLAN DECIMAL(15, 0),
  ENFORCE_USER_SAFETY_STOCKS DECIMAL(15, 0),
  ENFORCE_BUDGET_CONSTRAINTS DECIMAL(15, 0),
  BUDGET_ID DECIMAL(15, 0),
  BUDGET_VALUE DECIMAL(15, 0),
  LATEST_REFRESH_NUMBER DECIMAL(15, 0),
  SUPPLIER_ALLOC_METHOD DECIMAL(15, 0),
  CUSTOMER_ALLOC_METHOD DECIMAL(15, 0),
  DEFAULT_ALLOC_METHOD DECIMAL(15, 0),
  USE_FIXED_PERIOD_BKTS STRING,
  SHIPMENT_CONSOLIDATION_DAYS DECIMAL(15, 0),
  ITF_HORIZ_DAYS DECIMAL(15, 0),
  USE_ORG_PRIORITY_OVERRIDE STRING,
  USE_FIXED_PERIOD_ALLOC_BKTS STRING,
  SCHEDULE_BY_DATE_TYPE DECIMAL(15, 0),
  DS_SUBSET_HORIZON_DAYS DECIMAL(15, 0),
  SCHEDULE_DAYS_BEFORE DECIMAL(15, 0),
  SCHEDULE_START_TIME DECIMAL(15, 0),
  SCHEDULE_SUBSET_TYPE DECIMAL(15, 0),
  INCLUDE_WO DECIMAL(15, 0),
  ENFORCE_PURCH_LEAD_TIME DECIMAL(15, 0),
  USER_UPDATE_FIRM DECIMAL(15, 0),
  DEMAND_PRIORITY_SENSITIVITY DECIMAL(15, 0),
  EARLY_BUILD_PENALTY DECIMAL(15, 0),
  AUTO_RELEASE_TIME_FENCE DECIMAL(15, 0),
  SUBSET_DESIGNATOR_ID DECIMAL(15, 0),
  INCLUDE_PLANNED_ORDER DECIMAL(15, 0),
  CURR_INCLUDE_PLANNED_ORDER DECIMAL(15, 0),
  CURR_INCLUDE_WO DECIMAL(15, 0),
  CURR_DS_HORIZON_DAYS DECIMAL(15, 0),
  CURR_SCHEDULE_SUBSET_TYPE DECIMAL(15, 0),
  CURR_SUBSET_DESIGNATOR_ID DECIMAL(15, 0),
  CALCULATE_SDS_DAYS_TIME DECIMAL(15, 0),
  CALCULATE_SDS_WEEKS_TIME DECIMAL(15, 0),
  CALCULATE_SDS_PERIODS_TIME DECIMAL(15, 0),
  FIRM_OUTSIDE_SUBSET DECIMAL(15, 0),
  ENABLE_SO_SPLIT DECIMAL(15, 0),
  DS_HORIZON_DAYS DECIMAL(15, 0),
  PLANNING_MODE DECIMAL(15, 0),
  SDS_DMD_PENALTY DECIMAL(15, 0),
  CURR_OLS_HORIZON_DAYS DECIMAL(15, 0),
  OLS_FROZEN_HORIZON_DAYS DECIMAL(15, 0),
  CALCULATE_LIABILITY DECIMAL(15, 0),
  CURR_ENF_FULFILLMENT_LT DECIMAL(15, 0),
  ENFORCE_FULFILLMENT_LT DECIMAL(15, 0),
  DEMAND_FULFILLMENT_LT DECIMAL(15, 0),
  MFG_LT_VAR_PERCENT DECIMAL(15, 0),
  SUP_LT_VAR_PERCENT DECIMAL(15, 0),
  TRANSIT_LT_VAR_PERCENT DECIMAL(15, 0),
  SERVICE_LEVEL_SET_ID DECIMAL(15, 0),
  CURR_SERVICE_LEVEL_SET_ID DECIMAL(15, 0),
  PLAN_RUN_DATE TIMESTAMP,
  ITEM_SIMULATION_SET_ID DECIMAL(15, 0),
  PUBLISH_SUPPLY_COMMIT_VERSION DECIMAL(15, 0),
  PLANNED_BUCKET DECIMAL(15, 0),
  PLANNED_BUCKET_TYPE DECIMAL(15, 0),
  ASSIGNMENT_SET_OUT_ID DECIMAL(15, 0),
  CATEGORY_SET_ID DECIMAL(15, 0),
  SOP_ENABLED DECIMAL(15, 0),
  CONSTRAINED_MODE DECIMAL(15, 0),
  MANUAL_FCST_OVERWRITE_OPTION DECIMAL(15, 0),
  ENFORCE_CONSTRAINTS DECIMAL(15, 0),
  SAFETY_STOCK_VALUE_TYPE DECIMAL(15, 0),
  REALLOC_SURPLUS_DAYS DECIMAL(15, 0),
  PERFORM_FAIR_SHARE_ALLOC DECIMAL(15, 0),
  INCLUDE_ALL_ITEMS DECIMAL(15, 0),
  INCLUDE_ALL_CATEGORIES DECIMAL(15, 0),
  AUTO_RELEASE_METHOD DECIMAL(15, 0),
  INCLUDE_RESCHEDULES DECIMAL(15, 0),
  CALENDAR_TYPE DECIMAL(15, 0),
  HISTORY_RANGE DECIMAL(15, 0),
  HISTORY_RANGE_UOM DECIMAL(15, 0),
  FORECAST DECIMAL(15, 0),
  FORECAST_UOM DECIMAL(15, 0),
  FORECAST_BUCKET DECIMAL(15, 0),
  FORECAST_BUCKET_UOM DECIMAL(15, 0),
  GENERATE_INLINE_FORECAST DECIMAL(15, 0),
  CIRCULAR_SRC DECIMAL(15, 0),
  ARCHIVE_FLAG DECIMAL(15, 0),
  APPLIED DECIMAL(15, 0),
  BASE_PLAN_ID DECIMAL(15, 0),
  HAS_RUN DECIMAL(15, 0),
  LOADED_FLAG DECIMAL(15, 0),
  NEW_PLAN_ID DECIMAL(15, 0),
  NEW_PLAN_LIST STRING,
  PLANNING_ENGINE_TYPE DECIMAL(15, 0),
  PREVIOUS_RUN_PLAN_ID DECIMAL(15, 0),
  SAVED_FLAG DECIMAL(15, 0),
  SIMULATION_SET_ID DECIMAL(15, 0),
  COMPUTE_SS_EOQ DECIMAL(15, 0),
  PRIVATE_PLAN DECIMAL(15, 0),
  RELEASE_FLAG STRING,
  SAVE_TO_DB DECIMAL(15, 0),
  COMPUTE_CONSTRAINTS DECIMAL(15, 0),
  BUILD_READY_PCT DECIMAL(15, 0),
  RELEASE_SO DECIMAL(15, 0),
  AUTO_RELEASE_RP DECIMAL(15, 0),
  PLAN_VERSION DECIMAL(15, 0),
  RP_USER_ID DECIMAL(15, 0),
  DERIVE_RETURN_FCST_FROM_WO DECIMAL(15, 0),
  EXCEP_GROUP_ID DECIMAL(15, 0),
  DAILY_MWO_AGGR_LVL DECIMAL(15, 0),
  WEEKLY_MWO_AGGR_LVL DECIMAL(15, 0),
  PERIOD_MWO_AGGR_LVL DECIMAL(15, 0),
  PUB_CAP_TO_CMRO DECIMAL(15, 0),
  ENFORCE_WRH_CPTY DECIMAL(15, 0),
  PRIVATE_PLAN#1 DECIMAL(15, 0),
  ASCP_PLAN_ID DECIMAL(15, 0),
  ASCP_PLAN_VERSION DECIMAL(15, 0),
  SNAPSHOT_SOURCE DECIMAL(15, 0),
  GENERATE_WORKSHEET DECIMAL(15, 0),
  SUPPLY_INCLUSION_OPTION DECIMAL(15, 0),
  CRITERIA_CHANGED DECIMAL(15, 0),
  ENABLE_SAFETY_STOCK_RES DECIMAL(15, 0),
  ENFORCE_CATEGORY_LEVEL DECIMAL(15, 0),
  RUN_BATCH_SIMULATION DECIMAL(15, 0),
  LAST_PLAN_ACTION DECIMAL(15, 0),
  LAST_ACTION_BY DECIMAL(15, 0),
  LAST_ACTION_SESSION_ID STRING,
  WAREHOUSE_CAP_GRANULARITY DECIMAL(15, 0),
  PRIORITIZE_EXST_SUPPLIES DECIMAL(15, 0),
  ARCHIVE_DETAILS DECIMAL(15, 0),
  MAX_RESOURCE_UTILIZATION DECIMAL(15, 0),
  APPLY_ORDER_MODIFIERS DECIMAL(15, 0),
  COMMON_SUPPLY_DEMANDS DECIMAL(15, 0),
  FAIR_SHARE_BANDING DECIMAL(15, 0) DEFAULT 1,
  DEMAND_COLLECTIONS_DATE TIMESTAMP,
  POLICY_PLAN DECIMAL(15, 0),
  POLICY_PARAM_SET_ID DECIMAL(15, 0),
  REPLENISHMENT_ORD_GEN DECIMAL(15, 0),
  MPS_RECALC_FLAG DECIMAL(15, 0),
  MPS_BOR_ID DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MSC_PLANS (
  plan_id,
  compile_designator,
  sr_instance_id,
  append_planned_orders,
  assignment_set_id,
  curr_append_planned_orders,
  curr_assignment_set_id,
  curr_bill_of_resources,
  curr_consider_po,
  curr_consider_reservations,
  curr_consider_wip,
  curr_cutoff_date,
  curr_demand_time_fence_flag,
  curr_hard_pegging_level,
  curr_full_pegging,
  curr_included_items,
  curr_operation_schedule_type,
  curr_overwrite_option,
  curr_part_include_type,
  curr_planning_time_fence_flag,
  curr_plan_capacity_flag,
  curr_plan_safety_stock,
  curr_plan_type,
  curr_reservation_level,
  curr_schedule_designator,
  curr_schedule_type,
  curr_simulation_set,
  curr_snapshot_lock,
  curr_split_demands,
  curr_start_date,
  cutoff_date,
  daily_cutoff_bucket,
  daily_item_aggregation_level,
  daily_material_constraints,
  daily_resource_constraints,
  daily_res_aggregation_level,
  daily_trans_constraints,
  data_completion_date,
  data_start_date,
  demand_time_fence_flag,
  description,
  dmd_lateness_penalty_cost,
  hard_pegging_level,
  full_pegging,
  hour_cutoff_bucket,
  included_items,
  min_cutoff_bucket,
  monthly_cutoff_bucket,
  objective_weight_1,
  objective_weight_10,
  objective_weight_2,
  objective_weight_3,
  objective_weight_4,
  objective_weight_5,
  objective_weight_6,
  objective_weight_7,
  objective_weight_8,
  objective_weight_9,
  operation_schedule_type,
  organization_id,
  organization_selection,
  overwrite_option,
  part_include_type,
  penalty_cost_1,
  penalty_cost_10,
  penalty_cost_2,
  penalty_cost_3,
  penalty_cost_4,
  penalty_cost_5,
  penalty_cost_6,
  penalty_cost_7,
  penalty_cost_8,
  penalty_cost_9,
  planned_refreshes,
  planning_time_fence_flag,
  plan_capacity_flag,
  plan_completion_date,
  plan_start_date,
  plan_type,
  qtrly_cutoff_bucket,
  reservation_level,
  resource_over_util_cost,
  schedule_designator,
  schedule_type,
  slack_allowed_flag_1,
  slack_allowed_flag_10,
  slack_allowed_flag_2,
  slack_allowed_flag_3,
  slack_allowed_flag_4,
  slack_allowed_flag_5,
  slack_allowed_flag_6,
  slack_allowed_flag_7,
  slack_allowed_flag_8,
  slack_allowed_flag_9,
  snapshot_lock,
  split_demands,
  start_date,
  supplier_cap_over_util_cost,
  weekly_cutoff_bucket,
  weekly_item_aggregation_level,
  weekly_material_constraints,
  weekly_resource_constraints,
  weekly_res_aggregation_level,
  weekly_trans_constraints,
  optimize_flag,
  schedule_flag,
  online_planner_start_date,
  online_planner_completion_date,
  transport_cap_over_util_cost,
  bill_of_resources,
  simulation_set,
  consider_wip,
  consider_po,
  plan_safety_stock,
  consider_reservations,
  curr_enforce_dem_due_dates,
  enforce_dem_due_dates,
  planned_resources,
  curr_planned_resources,
  dem_priority_rule_id,
  curr_dem_priority_rule_id,
  daily_rtg_aggregation_level,
  weekly_rtg_aggregation_level,
  period_rtg_aggregation_level,
  period_cutoff_bucket,
  lot_for_lot_flag,
  enforce_cap_constraints,
  curr_enforce_cap_constraints,
  service_level,
  bottleneck_res_group,
  curr_bottleneck_res_group,
  period_material_constraints,
  period_resource_constraints,
  period_trans_constraints,
  period_item_aggregation_level,
  period_res_aggregation_level,
  last_update_date,
  last_updated_by,
  creation_date,
  lot_for_lot,
  created_by,
  last_update_login,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  min_wf_except_id,
  max_wf_except_id,
  online_replan,
  refresh_number,
  revision,
  parent_plan_id,
  status,
  production_flag,
  company_agg_level,
  tp_agg_level,
  product_agg_level,
  purge,
  enforce_sl_constraints,
  curr_enforce_sl_constraints,
  plan_inventory_point,
  enable_closest_qty_pegging,
  curr_closest_qty_peg,
  enable_priority_pegging,
  curr_priority_pegging,
  enforce_src_constraints,
  curr_enforce_src_constraints,
  backward_days,
  curr_backward_days,
  forward_days,
  curr_forward_days,
  summary_flag,
  use_alternate_resources,
  use_end_item_substitutions,
  use_alternate_bom_routing,
  use_substitute_components,
  use_alternate_sources,
  substitution_designator,
  kpi_refresh,
  display_kpi,
  forecast_allocation_method,
  forecast_consumption_method,
  copy_plan_id,
  explode_forecast,
  forecast_assignment_set_id,
  enforce_sup_cap_constraints,
  enforce_pur_lt_constraints,
  tgt_tl_util_pct,
  min_tl_util_pct,
  load_sched_time_fence_days,
  load_scheduling_days,
  daily_alloc_buckets,
  wks_per_wkly_alloc_bucket,
  dmd_pri_rule_set_id,
  circ_srcing_surplus_days,
  supply_sched_itf,
  include_critical_components,
  schedule_by,
  publish_fcst_version,
  release_reschedules,
  safety_stk_change_interval,
  safety_stk_threshold_pct,
  copy_plan,
  enforce_user_safety_stocks,
  enforce_budget_constraints,
  budget_id,
  budget_value,
  latest_refresh_number,
  supplier_alloc_method,
  customer_alloc_method,
  default_alloc_method,
  use_fixed_period_bkts,
  shipment_consolidation_days,
  itf_horiz_days,
  use_org_priority_override,
  use_fixed_period_alloc_bkts,
  schedule_by_date_type,
  ds_subset_horizon_days,
  schedule_days_before,
  schedule_start_time,
  schedule_subset_type,
  include_wo,
  enforce_purch_lead_time,
  user_update_firm,
  demand_priority_sensitivity,
  early_build_penalty,
  auto_release_time_fence,
  subset_designator_id,
  include_planned_order,
  curr_include_planned_order,
  curr_include_wo,
  curr_ds_horizon_days,
  curr_schedule_subset_type,
  curr_subset_designator_id,
  calculate_sds_days_time,
  calculate_sds_weeks_time,
  calculate_sds_periods_time,
  firm_outside_subset,
  enable_so_split,
  ds_horizon_days,
  planning_mode,
  sds_dmd_penalty,
  curr_ols_horizon_days,
  ols_frozen_horizon_days,
  calculate_liability,
  curr_enf_fulfillment_lt,
  enforce_fulfillment_lt,
  demand_fulfillment_lt,
  mfg_lt_var_percent,
  sup_lt_var_percent,
  transit_lt_var_percent,
  service_level_set_id,
  curr_service_level_set_id,
  plan_run_date,
  item_simulation_set_id,
  publish_supply_commit_version,
  planned_bucket,
  planned_bucket_type,
  assignment_set_out_id,
  category_set_id,
  sop_enabled,
  constrained_mode,
  manual_fcst_overwrite_option,
  enforce_constraints,
  safety_stock_value_type,
  realloc_surplus_days,
  perform_fair_share_alloc,
  include_all_items,
  include_all_categories,
  auto_release_method,
  include_reschedules,
  calendar_type,
  history_range,
  history_range_uom,
  forecast,
  forecast_uom,
  forecast_bucket,
  forecast_bucket_uom,
  generate_inline_forecast,
  circular_src,
  archive_flag,
  applied,
  base_plan_id,
  has_run,
  loaded_flag,
  new_plan_id,
  new_plan_list,
  planning_engine_type,
  previous_run_plan_id,
  saved_flag,
  simulation_set_id,
  compute_ss_eoq,
  private_plan,
  release_flag,
  save_to_db,
  compute_constraints,
  build_ready_pct,
  release_so,
  auto_release_rp,
  plan_version,
  rp_user_id,
  derive_return_fcst_from_wo,
  excep_group_id,
  daily_mwo_aggr_lvl,
  weekly_mwo_aggr_lvl,
  period_mwo_aggr_lvl,
  pub_cap_to_cmro,
  enforce_wrh_cpty,
  `private_plan#1`,
  ascp_plan_id,
  ascp_plan_version,
  snapshot_source,
  generate_worksheet,
  supply_inclusion_option,
  criteria_changed,
  enable_safety_stock_res,
  enforce_category_level,
  run_batch_simulation,
  last_plan_action,
  last_action_by,
  last_action_session_id,
  warehouse_cap_granularity,
  prioritize_exst_supplies,
  archive_details,
  max_resource_utilization,
  apply_order_modifiers,
  common_supply_demands,
  fair_share_banding,
  demand_collections_date,
  policy_plan,
  policy_param_set_id,
  replenishment_ord_gen,
  mps_recalc_flag,
  mps_bor_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  plan_id,
  compile_designator,
  sr_instance_id,
  append_planned_orders,
  assignment_set_id,
  curr_append_planned_orders,
  curr_assignment_set_id,
  curr_bill_of_resources,
  curr_consider_po,
  curr_consider_reservations,
  curr_consider_wip,
  curr_cutoff_date,
  curr_demand_time_fence_flag,
  curr_hard_pegging_level,
  curr_full_pegging,
  curr_included_items,
  curr_operation_schedule_type,
  curr_overwrite_option,
  curr_part_include_type,
  curr_planning_time_fence_flag,
  curr_plan_capacity_flag,
  curr_plan_safety_stock,
  curr_plan_type,
  curr_reservation_level,
  curr_schedule_designator,
  curr_schedule_type,
  curr_simulation_set,
  curr_snapshot_lock,
  curr_split_demands,
  curr_start_date,
  cutoff_date,
  daily_cutoff_bucket,
  daily_item_aggregation_level,
  daily_material_constraints,
  daily_resource_constraints,
  daily_res_aggregation_level,
  daily_trans_constraints,
  data_completion_date,
  data_start_date,
  demand_time_fence_flag,
  description,
  dmd_lateness_penalty_cost,
  hard_pegging_level,
  full_pegging,
  hour_cutoff_bucket,
  included_items,
  min_cutoff_bucket,
  monthly_cutoff_bucket,
  objective_weight_1,
  objective_weight_10,
  objective_weight_2,
  objective_weight_3,
  objective_weight_4,
  objective_weight_5,
  objective_weight_6,
  objective_weight_7,
  objective_weight_8,
  objective_weight_9,
  operation_schedule_type,
  organization_id,
  organization_selection,
  overwrite_option,
  part_include_type,
  penalty_cost_1,
  penalty_cost_10,
  penalty_cost_2,
  penalty_cost_3,
  penalty_cost_4,
  penalty_cost_5,
  penalty_cost_6,
  penalty_cost_7,
  penalty_cost_8,
  penalty_cost_9,
  planned_refreshes,
  planning_time_fence_flag,
  plan_capacity_flag,
  plan_completion_date,
  plan_start_date,
  plan_type,
  qtrly_cutoff_bucket,
  reservation_level,
  resource_over_util_cost,
  schedule_designator,
  schedule_type,
  slack_allowed_flag_1,
  slack_allowed_flag_10,
  slack_allowed_flag_2,
  slack_allowed_flag_3,
  slack_allowed_flag_4,
  slack_allowed_flag_5,
  slack_allowed_flag_6,
  slack_allowed_flag_7,
  slack_allowed_flag_8,
  slack_allowed_flag_9,
  snapshot_lock,
  split_demands,
  start_date,
  supplier_cap_over_util_cost,
  weekly_cutoff_bucket,
  weekly_item_aggregation_level,
  weekly_material_constraints,
  weekly_resource_constraints,
  weekly_res_aggregation_level,
  weekly_trans_constraints,
  optimize_flag,
  schedule_flag,
  online_planner_start_date,
  online_planner_completion_date,
  transport_cap_over_util_cost,
  bill_of_resources,
  simulation_set,
  consider_wip,
  consider_po,
  plan_safety_stock,
  consider_reservations,
  curr_enforce_dem_due_dates,
  enforce_dem_due_dates,
  planned_resources,
  curr_planned_resources,
  dem_priority_rule_id,
  curr_dem_priority_rule_id,
  daily_rtg_aggregation_level,
  weekly_rtg_aggregation_level,
  period_rtg_aggregation_level,
  period_cutoff_bucket,
  lot_for_lot_flag,
  enforce_cap_constraints,
  curr_enforce_cap_constraints,
  service_level,
  bottleneck_res_group,
  curr_bottleneck_res_group,
  period_material_constraints,
  period_resource_constraints,
  period_trans_constraints,
  period_item_aggregation_level,
  period_res_aggregation_level,
  last_update_date,
  last_updated_by,
  creation_date,
  lot_for_lot,
  created_by,
  last_update_login,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  min_wf_except_id,
  max_wf_except_id,
  online_replan,
  refresh_number,
  revision,
  parent_plan_id,
  status,
  production_flag,
  company_agg_level,
  tp_agg_level,
  product_agg_level,
  purge,
  enforce_sl_constraints,
  curr_enforce_sl_constraints,
  plan_inventory_point,
  enable_closest_qty_pegging,
  curr_closest_qty_peg,
  enable_priority_pegging,
  curr_priority_pegging,
  enforce_src_constraints,
  curr_enforce_src_constraints,
  backward_days,
  curr_backward_days,
  forward_days,
  curr_forward_days,
  summary_flag,
  use_alternate_resources,
  use_end_item_substitutions,
  use_alternate_bom_routing,
  use_substitute_components,
  use_alternate_sources,
  substitution_designator,
  kpi_refresh,
  display_kpi,
  forecast_allocation_method,
  forecast_consumption_method,
  copy_plan_id,
  explode_forecast,
  forecast_assignment_set_id,
  enforce_sup_cap_constraints,
  enforce_pur_lt_constraints,
  tgt_tl_util_pct,
  min_tl_util_pct,
  load_sched_time_fence_days,
  load_scheduling_days,
  daily_alloc_buckets,
  wks_per_wkly_alloc_bucket,
  dmd_pri_rule_set_id,
  circ_srcing_surplus_days,
  supply_sched_itf,
  include_critical_components,
  schedule_by,
  publish_fcst_version,
  release_reschedules,
  safety_stk_change_interval,
  safety_stk_threshold_pct,
  copy_plan,
  enforce_user_safety_stocks,
  enforce_budget_constraints,
  budget_id,
  budget_value,
  latest_refresh_number,
  supplier_alloc_method,
  customer_alloc_method,
  default_alloc_method,
  use_fixed_period_bkts,
  shipment_consolidation_days,
  itf_horiz_days,
  use_org_priority_override,
  use_fixed_period_alloc_bkts,
  schedule_by_date_type,
  ds_subset_horizon_days,
  schedule_days_before,
  schedule_start_time,
  schedule_subset_type,
  include_wo,
  enforce_purch_lead_time,
  user_update_firm,
  demand_priority_sensitivity,
  early_build_penalty,
  auto_release_time_fence,
  subset_designator_id,
  include_planned_order,
  curr_include_planned_order,
  curr_include_wo,
  curr_ds_horizon_days,
  curr_schedule_subset_type,
  curr_subset_designator_id,
  calculate_sds_days_time,
  calculate_sds_weeks_time,
  calculate_sds_periods_time,
  firm_outside_subset,
  enable_so_split,
  ds_horizon_days,
  planning_mode,
  sds_dmd_penalty,
  curr_ols_horizon_days,
  ols_frozen_horizon_days,
  calculate_liability,
  curr_enf_fulfillment_lt,
  enforce_fulfillment_lt,
  demand_fulfillment_lt,
  mfg_lt_var_percent,
  sup_lt_var_percent,
  transit_lt_var_percent,
  service_level_set_id,
  curr_service_level_set_id,
  plan_run_date,
  item_simulation_set_id,
  publish_supply_commit_version,
  planned_bucket,
  planned_bucket_type,
  assignment_set_out_id,
  category_set_id,
  sop_enabled,
  constrained_mode,
  manual_fcst_overwrite_option,
  enforce_constraints,
  safety_stock_value_type,
  realloc_surplus_days,
  perform_fair_share_alloc,
  include_all_items,
  include_all_categories,
  auto_release_method,
  include_reschedules,
  calendar_type,
  history_range,
  history_range_uom,
  forecast,
  forecast_uom,
  forecast_bucket,
  forecast_bucket_uom,
  generate_inline_forecast,
  circular_src,
  archive_flag,
  applied,
  base_plan_id,
  has_run,
  loaded_flag,
  new_plan_id,
  new_plan_list,
  planning_engine_type,
  previous_run_plan_id,
  saved_flag,
  simulation_set_id,
  compute_ss_eoq,
  private_plan,
  release_flag,
  save_to_db,
  compute_constraints,
  build_ready_pct,
  release_so,
  auto_release_rp,
  plan_version,
  rp_user_id,
  derive_return_fcst_from_wo,
  excep_group_id,
  daily_mwo_aggr_lvl,
  weekly_mwo_aggr_lvl,
  period_mwo_aggr_lvl,
  pub_cap_to_cmro,
  enforce_wrh_cpty,
  `private_plan#1`,
  ascp_plan_id,
  ascp_plan_version,
  snapshot_source,
  generate_worksheet,
  supply_inclusion_option,
  criteria_changed,
  enable_safety_stock_res,
  enforce_category_level,
  run_batch_simulation,
  last_plan_action,
  last_action_by,
  last_action_session_id,
  warehouse_cap_granularity,
  prioritize_exst_supplies,
  archive_details,
  max_resource_utilization,
  apply_order_modifiers,
  common_supply_demands,
  fair_share_banding,
  demand_collections_date,
  policy_plan,
  policy_param_set_id,
  replenishment_ord_gen,
  mps_recalc_flag,
  mps_bor_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MSC_PLANS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_plans';