DROP TABLE IF EXISTS silver_bec_ods.ra_cust_trx_line_gl_dist_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ra_cust_trx_line_gl_dist_all (
  cust_trx_line_gl_dist_id DECIMAL(15, 0),
  customer_trx_line_id DECIMAL(15, 0),
  code_combination_id DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  `percent` DECIMAL(28, 10),
  amount DECIMAL(28, 10),
  gl_date TIMESTAMP,
  gl_posted_date TIMESTAMP,
  cust_trx_line_salesrep_id DECIMAL(15, 0),
  comments STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  concatenated_segments STRING,
  original_gl_date TIMESTAMP,
  post_request_id DECIMAL(15, 0),
  posting_control_id DECIMAL(15, 0),
  account_class STRING,
  ra_post_loop_number DECIMAL(15, 0),
  customer_trx_id DECIMAL(15, 0),
  account_set_flag STRING,
  acctd_amount DECIMAL(28, 10),
  ussgl_transaction_code STRING,
  ussgl_transaction_code_context STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  latest_rec_flag STRING,
  org_id DECIMAL(15, 0),
  mrc_account_class STRING,
  mrc_customer_trx_id STRING,
  mrc_amount STRING,
  mrc_gl_posted_date STRING,
  mrc_posting_control_id STRING,
  mrc_acctd_amount STRING,
  collected_tax_ccid DECIMAL(15, 0),
  collected_tax_concat_seg STRING,
  revenue_adjustment_id DECIMAL(15, 0),
  rev_adj_class_temp STRING,
  rec_offset_flag STRING,
  event_id DECIMAL(15, 0),
  user_generated_flag STRING,
  rounding_correction_flag STRING,
  cogs_request_id DECIMAL(15, 0),
  ccid_change_flag STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute21 STRING,
  global_attribute22 STRING,
  global_attribute23 STRING,
  global_attribute24 STRING,
  global_attribute25 STRING,
  global_attribute26 STRING,
  global_attribute27 STRING,
  global_attribute28 STRING,
  global_attribute29 STRING,
  global_attribute30 STRING,
  global_attribute_category STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ra_cust_trx_line_gl_dist_all (
  cust_trx_line_gl_dist_id,
  customer_trx_line_id,
  code_combination_id,
  set_of_books_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  `percent`,
  amount,
  gl_date,
  gl_posted_date,
  cust_trx_line_salesrep_id,
  comments,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  concatenated_segments,
  original_gl_date,
  post_request_id,
  posting_control_id,
  account_class,
  ra_post_loop_number,
  customer_trx_id,
  account_set_flag,
  acctd_amount,
  ussgl_transaction_code,
  ussgl_transaction_code_context,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  latest_rec_flag,
  org_id,
  mrc_account_class,
  mrc_customer_trx_id,
  mrc_amount,
  mrc_gl_posted_date,
  mrc_posting_control_id,
  mrc_acctd_amount,
  collected_tax_ccid,
  collected_tax_concat_seg,
  revenue_adjustment_id,
  rev_adj_class_temp,
  rec_offset_flag,
  event_id,
  user_generated_flag,
  rounding_correction_flag,
  cogs_request_id,
  ccid_change_flag,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute21,
  global_attribute22,
  global_attribute23,
  global_attribute24,
  global_attribute25,
  global_attribute26,
  global_attribute27,
  global_attribute28,
  global_attribute29,
  global_attribute30,
  global_attribute_category,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cust_trx_line_gl_dist_id,
  customer_trx_line_id,
  code_combination_id,
  set_of_books_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  `percent`,
  amount,
  gl_date,
  gl_posted_date,
  cust_trx_line_salesrep_id,
  comments,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  concatenated_segments,
  original_gl_date,
  post_request_id,
  posting_control_id,
  account_class,
  ra_post_loop_number,
  customer_trx_id,
  account_set_flag,
  acctd_amount,
  ussgl_transaction_code,
  ussgl_transaction_code_context,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  latest_rec_flag,
  org_id,
  mrc_account_class,
  mrc_customer_trx_id,
  mrc_amount,
  mrc_gl_posted_date,
  mrc_posting_control_id,
  mrc_acctd_amount,
  collected_tax_ccid,
  collected_tax_concat_seg,
  revenue_adjustment_id,
  rev_adj_class_temp,
  rec_offset_flag,
  event_id,
  user_generated_flag,
  rounding_correction_flag,
  cogs_request_id,
  ccid_change_flag,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute21,
  global_attribute22,
  global_attribute23,
  global_attribute24,
  global_attribute25,
  global_attribute26,
  global_attribute27,
  global_attribute28,
  global_attribute29,
  global_attribute30,
  global_attribute_category,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ra_cust_trx_line_gl_dist_all;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ra_cust_trx_line_gl_dist_all';