DROP TABLE IF EXISTS silver_bec_ods.PO_APPROVED_SUPPLIER_LIST;
CREATE TABLE IF NOT EXISTS silver_bec_ods.PO_APPROVED_SUPPLIER_LIST (
  asl_id DECIMAL(15, 0),
  using_organization_id DECIMAL(15, 0),
  owning_organization_id DECIMAL(15, 0),
  vendor_business_type STRING,
  asl_status_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  manufacturer_id DECIMAL(15, 0),
  vendor_id DECIMAL(15, 0),
  item_id DECIMAL(15, 0),
  category_id DECIMAL(15, 0),
  vendor_site_id DECIMAL(15, 0),
  primary_vendor_item STRING,
  manufacturer_asl_id DECIMAL(15, 0),
  review_by_date TIMESTAMP,
  comments STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  DISABLE_FLAG STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.PO_APPROVED_SUPPLIER_LIST (
  asl_id,
  using_organization_id,
  owning_organization_id,
  vendor_business_type,
  asl_status_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  manufacturer_id,
  vendor_id,
  item_id,
  category_id,
  vendor_site_id,
  primary_vendor_item,
  manufacturer_asl_id,
  review_by_date,
  comments,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  DISABLE_FLAG,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  asl_id,
  using_organization_id,
  owning_organization_id,
  vendor_business_type,
  asl_status_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  manufacturer_id,
  vendor_id,
  item_id,
  category_id,
  vendor_site_id,
  primary_vendor_item,
  manufacturer_asl_id,
  review_by_date,
  comments,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  DISABLE_FLAG,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.PO_APPROVED_SUPPLIER_LIST;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'po_approved_supplier_list';