DROP TABLE IF EXISTS silver_bec_ods.PO_REQ_DISTRIBUTIONS_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.PO_REQ_DISTRIBUTIONS_ALL (
  distribution_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  requisition_line_id DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  code_combination_id DECIMAL(15, 0),
  req_line_quantity DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  encumbered_flag STRING,
  gl_encumbered_date TIMESTAMP,
  gl_encumbered_period_name STRING,
  gl_cancelled_date TIMESTAMP,
  failed_funds_lookup_code STRING,
  encumbered_amount DECIMAL(28, 10),
  budget_account_id DECIMAL(15, 0),
  accrual_account_id DECIMAL(15, 0),
  variance_account_id DECIMAL(15, 0),
  prevent_encumbrance_flag STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  ussgl_transaction_code STRING,
  government_context STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  expenditure_type STRING,
  project_accounting_context STRING,
  expenditure_organization_id DECIMAL(15, 0),
  gl_closed_date TIMESTAMP,
  source_req_distribution_id DECIMAL(15, 0),
  distribution_num DECIMAL(15, 0),
  project_related_flag STRING,
  expenditure_item_date TIMESTAMP,
  org_id DECIMAL(15, 0),
  allocation_type STRING,
  allocation_value DECIMAL(28, 10),
  award_id DECIMAL(15, 0),
  end_item_unit_number STRING,
  recoverable_tax DECIMAL(28, 10),
  nonrecoverable_tax DECIMAL(28, 10),
  recovery_rate DECIMAL(28, 10),
  tax_recovery_override_flag STRING,
  oke_contract_line_id DECIMAL(15, 0),
  oke_contract_deliverable_id DECIMAL(15, 0),
  req_line_amount DECIMAL(28, 10),
  req_line_currency_amount DECIMAL(28, 10),
  req_award_id DECIMAL(15, 0),
  event_id DECIMAL(15, 0),
  ACRN STRING,
  AMENDMENT_STATUS STRING,
  AMENDMENT_TYPE STRING,
  AMOUNT_FUNDED DECIMAL(28, 10),
  CHANGE_IN_FUNDED_VALUE DECIMAL(15, 0),
  CLM_AGENCY_ACCT_IDENTIFIER STRING,
  CLM_DEFENCE_FUNDING STRING,
  CLM_FMS_CASE_NUMBER STRING,
  CLM_MISC_LOA STRING,
  CONFORMED_DIST_ID DECIMAL(15, 0),
  FUNDED_VALUE DECIMAL(28, 10),
  FUNDS_LIQUIDATED DECIMAL(28, 10),
  INFO_LINE_ID DECIMAL(15, 0),
  PAR_DISTRIBUTION_ID DECIMAL(15, 0),
  PAR_DRAFT_ID DECIMAL(15, 0),
  PARTIAL_FUNDED_FLAG STRING,
  QUANTITY_FUNDED DECIMAL(15, 0),
  UDA_TEMPLATE_ID DECIMAL(15, 0),
  UNENCUMBERED_AMOUNT DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.PO_REQ_DISTRIBUTIONS_ALL (
  distribution_id,
  last_update_date,
  last_updated_by,
  requisition_line_id,
  set_of_books_id,
  code_combination_id,
  req_line_quantity,
  last_update_login,
  creation_date,
  created_by,
  encumbered_flag,
  gl_encumbered_date,
  gl_encumbered_period_name,
  gl_cancelled_date,
  failed_funds_lookup_code,
  encumbered_amount,
  budget_account_id,
  accrual_account_id,
  variance_account_id,
  prevent_encumbrance_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  ussgl_transaction_code,
  government_context,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  project_id,
  task_id,
  expenditure_type,
  project_accounting_context,
  expenditure_organization_id,
  gl_closed_date,
  source_req_distribution_id,
  distribution_num,
  project_related_flag,
  expenditure_item_date,
  org_id,
  allocation_type,
  allocation_value,
  award_id,
  end_item_unit_number,
  recoverable_tax,
  nonrecoverable_tax,
  recovery_rate,
  tax_recovery_override_flag,
  oke_contract_line_id,
  oke_contract_deliverable_id,
  req_line_amount,
  req_line_currency_amount,
  req_award_id,
  event_id,
  acrn,
  amendment_status,
  amendment_type,
  amount_funded,
  change_in_funded_value,
  clm_agency_acct_identifier,
  clm_defence_funding,
  clm_fms_case_number,
  clm_misc_loa,
  conformed_dist_id,
  funded_value,
  funds_liquidated,
  info_line_id,
  par_distribution_id,
  par_draft_id,
  partial_funded_flag,
  quantity_funded,
  uda_template_id,
  unencumbered_amount,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  distribution_id,
  last_update_date,
  last_updated_by,
  requisition_line_id,
  set_of_books_id,
  code_combination_id,
  req_line_quantity,
  last_update_login,
  creation_date,
  created_by,
  encumbered_flag,
  gl_encumbered_date,
  gl_encumbered_period_name,
  gl_cancelled_date,
  failed_funds_lookup_code,
  encumbered_amount,
  budget_account_id,
  accrual_account_id,
  variance_account_id,
  prevent_encumbrance_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  ussgl_transaction_code,
  government_context,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  project_id,
  task_id,
  expenditure_type,
  project_accounting_context,
  expenditure_organization_id,
  gl_closed_date,
  source_req_distribution_id,
  distribution_num,
  project_related_flag,
  expenditure_item_date,
  org_id,
  allocation_type,
  allocation_value,
  award_id,
  end_item_unit_number,
  recoverable_tax,
  nonrecoverable_tax,
  recovery_rate,
  tax_recovery_override_flag,
  oke_contract_line_id,
  oke_contract_deliverable_id,
  req_line_amount,
  req_line_currency_amount,
  req_award_id,
  event_id,
  acrn,
  amendment_status,
  amendment_type,
  amount_funded,
  change_in_funded_value,
  clm_agency_acct_identifier,
  clm_defence_funding,
  clm_fms_case_number,
  clm_misc_loa,
  conformed_dist_id,
  funded_value,
  funds_liquidated,
  info_line_id,
  par_distribution_id,
  par_draft_id,
  partial_funded_flag,
  quantity_funded,
  uda_template_id,
  unencumbered_amount,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.PO_REQ_DISTRIBUTIONS_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'po_req_distributions_all';