DROP TABLE IF EXISTS silver_bec_ods.QP_QUALIFIERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.QP_QUALIFIERS (
  qualifier_id DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  qualifier_grouping_no DECIMAL(15, 0),
  qualifier_context STRING,
  qualifier_attribute STRING,
  qualifier_attr_value STRING,
  comparison_operator_code STRING,
  excluder_flag STRING,
  qualifier_rule_id DECIMAL(15, 0),
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  created_from_rule_id DECIMAL(15, 0),
  qualifier_precedence DECIMAL(15, 0),
  list_header_id DECIMAL(15, 0),
  list_line_id DECIMAL(15, 0),
  qualifier_datatype STRING,
  qualifier_attr_value_to STRING,
  context STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  active_flag STRING,
  list_type_code STRING,
  qual_attr_value_from_number DECIMAL(15, 0),
  qual_attr_value_to_number DECIMAL(15, 0),
  search_ind DECIMAL(15, 0),
  qualifier_group_cnt DECIMAL(15, 0),
  header_quals_exist_flag STRING,
  distinct_row_count DECIMAL(15, 0),
  others_group_cnt DECIMAL(15, 0),
  segment_id DECIMAL(15, 0),
  orig_sys_qualifier_ref STRING,
  orig_sys_header_ref STRING,
  orig_sys_line_ref STRING,
  qualify_hier_descendents_flag STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.QP_QUALIFIERS (
  qualifier_id,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  last_update_login,
  qualifier_grouping_no,
  qualifier_context,
  qualifier_attribute,
  qualifier_attr_value,
  comparison_operator_code,
  excluder_flag,
  qualifier_rule_id,
  start_date_active,
  end_date_active,
  created_from_rule_id,
  qualifier_precedence,
  list_header_id,
  list_line_id,
  qualifier_datatype,
  qualifier_attr_value_to,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  active_flag,
  list_type_code,
  qual_attr_value_from_number,
  qual_attr_value_to_number,
  search_ind,
  qualifier_group_cnt,
  header_quals_exist_flag,
  distinct_row_count,
  others_group_cnt,
  segment_id,
  orig_sys_qualifier_ref,
  orig_sys_header_ref,
  orig_sys_line_ref,
  qualify_hier_descendents_flag,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  qualifier_id,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  last_update_login,
  qualifier_grouping_no,
  qualifier_context,
  qualifier_attribute,
  qualifier_attr_value,
  comparison_operator_code,
  excluder_flag,
  qualifier_rule_id,
  start_date_active,
  end_date_active,
  created_from_rule_id,
  qualifier_precedence,
  list_header_id,
  list_line_id,
  qualifier_datatype,
  qualifier_attr_value_to,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  active_flag,
  list_type_code,
  qual_attr_value_from_number,
  qual_attr_value_to_number,
  search_ind,
  qualifier_group_cnt,
  header_quals_exist_flag,
  distinct_row_count,
  others_group_cnt,
  segment_id,
  orig_sys_qualifier_ref,
  orig_sys_header_ref,
  orig_sys_line_ref,
  qualify_hier_descendents_flag,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.QP_QUALIFIERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'qp_qualifiers';