DROP TABLE IF EXISTS silver_bec_ods.ap_aging_period_lines;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_aging_period_lines (
  aging_period_line_id DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  aging_period_id DECIMAL(15, 0),
  period_sequence_num DECIMAL(15, 0),
  days_start DECIMAL(15, 0),
  days_to DECIMAL(15, 0),
  type STRING,
  report_heading1 STRING,
  report_heading2 STRING,
  report_heading3 STRING,
  new_line STRING,
  base_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  last_update_login DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_aging_period_lines (
  aging_period_line_id,
  last_updated_by,
  last_update_date,
  created_by,
  creation_date,
  aging_period_id,
  period_sequence_num,
  days_start,
  days_to,
  type,
  report_heading1,
  report_heading2,
  report_heading3,
  new_line,
  base_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  aging_period_line_id,
  last_updated_by,
  last_update_date,
  created_by,
  creation_date,
  aging_period_id,
  period_sequence_num,
  days_start,
  days_to,
  type,
  report_heading1,
  report_heading2,
  report_heading3,
  new_line,
  base_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ap_aging_period_lines;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_aging_period_lines';