DROP TABLE IF EXISTS silver_bec_ods.WIP_OPERATIONS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.WIP_OPERATIONS (
  wip_entity_id DECIMAL(15, 0),
  operation_seq_num DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  repetitive_schedule_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  operation_sequence_id DECIMAL(15, 0),
  standard_operation_id DECIMAL(15, 0),
  department_id DECIMAL(15, 0),
  description STRING,
  scheduled_quantity DECIMAL(28, 10),
  quantity_in_queue DECIMAL(28, 10),
  quantity_running DECIMAL(28, 10),
  quantity_waiting_to_move DECIMAL(28, 10),
  quantity_rejected DECIMAL(28, 10),
  quantity_scrapped DECIMAL(28, 10),
  quantity_completed DECIMAL(28, 10),
  first_unit_start_date TIMESTAMP,
  first_unit_completion_date TIMESTAMP,
  last_unit_start_date TIMESTAMP,
  last_unit_completion_date TIMESTAMP,
  previous_operation_seq_num DECIMAL(15, 0),
  next_operation_seq_num DECIMAL(15, 0),
  count_point_type DECIMAL(15, 0),
  backflush_flag DECIMAL(15, 0),
  minimum_transfer_quantity DECIMAL(28, 10),
  date_last_moved TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  wf_itemtype STRING,
  wf_itemkey STRING,
  operation_yield DECIMAL(28, 10),
  operation_yield_enabled DECIMAL(28, 10),
  pre_split_quantity DECIMAL(28, 10),
  operation_completed STRING,
  shutdown_type STRING,
  x_pos DECIMAL(28, 10),
  y_pos DECIMAL(28, 10),
  previous_operation_seq_id DECIMAL(15, 0),
  skip_flag DECIMAL(15, 0),
  long_description STRING,
  cumulative_scrap_quantity DECIMAL(28, 10),
  disable_date TIMESTAMP,
  recommended STRING,
  progress_percentage DECIMAL(28, 10),
  wsm_op_seq_num DECIMAL(28, 10),
  wsm_bonus_quantity DECIMAL(28, 10),
  employee_id DECIMAL(15, 0),
  actual_start_date TIMESTAMP,
  actual_completion_date TIMESTAMP,
  projected_completion_date TIMESTAMP,
  wsm_update_quantity_txn_id DECIMAL(15, 0),
  wsm_costed_quantity_completed DECIMAL(28, 10),
  lowest_acceptable_yield DECIMAL(28, 10),
  check_skill DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.WIP_OPERATIONS (
  wip_entity_id,
  operation_seq_num,
  organization_id,
  repetitive_schedule_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  operation_sequence_id,
  standard_operation_id,
  department_id,
  description,
  scheduled_quantity,
  quantity_in_queue,
  quantity_running,
  quantity_waiting_to_move,
  quantity_rejected,
  quantity_scrapped,
  quantity_completed,
  first_unit_start_date,
  first_unit_completion_date,
  last_unit_start_date,
  last_unit_completion_date,
  previous_operation_seq_num,
  next_operation_seq_num,
  count_point_type,
  backflush_flag,
  minimum_transfer_quantity,
  date_last_moved,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  wf_itemtype,
  wf_itemkey,
  operation_yield,
  operation_yield_enabled,
  pre_split_quantity,
  operation_completed,
  shutdown_type,
  x_pos,
  y_pos,
  previous_operation_seq_id,
  skip_flag,
  long_description,
  cumulative_scrap_quantity,
  disable_date,
  recommended,
  progress_percentage,
  wsm_op_seq_num,
  wsm_bonus_quantity,
  employee_id,
  actual_start_date,
  actual_completion_date,
  projected_completion_date,
  wsm_update_quantity_txn_id,
  wsm_costed_quantity_completed,
  lowest_acceptable_yield,
  check_skill,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  wip_entity_id,
  operation_seq_num,
  organization_id,
  repetitive_schedule_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  operation_sequence_id,
  standard_operation_id,
  department_id,
  description,
  scheduled_quantity,
  quantity_in_queue,
  quantity_running,
  quantity_waiting_to_move,
  quantity_rejected,
  quantity_scrapped,
  quantity_completed,
  first_unit_start_date,
  first_unit_completion_date,
  last_unit_start_date,
  last_unit_completion_date,
  previous_operation_seq_num,
  next_operation_seq_num,
  count_point_type,
  backflush_flag,
  minimum_transfer_quantity,
  date_last_moved,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  wf_itemtype,
  wf_itemkey,
  operation_yield,
  operation_yield_enabled,
  pre_split_quantity,
  operation_completed,
  shutdown_type,
  x_pos,
  y_pos,
  previous_operation_seq_id,
  skip_flag,
  long_description,
  cumulative_scrap_quantity,
  disable_date,
  recommended,
  progress_percentage,
  wsm_op_seq_num,
  wsm_bonus_quantity,
  employee_id,
  actual_start_date,
  actual_completion_date,
  projected_completion_date,
  wsm_update_quantity_txn_id,
  wsm_costed_quantity_completed,
  lowest_acceptable_yield,
  check_skill,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.WIP_OPERATIONS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wip_operations';