DROP TABLE IF EXISTS silver_bec_ods.WIP_PERIOD_BALANCES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.WIP_PERIOD_BALANCES (
  acct_period_id DECIMAL(15, 0),
  wip_entity_id DECIMAL(15, 0),
  repetitive_schedule_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  class_type DECIMAL(15, 0),
  tl_resource_in DECIMAL(28, 10),
  tl_overhead_in DECIMAL(28, 10),
  tl_outside_processing_in DECIMAL(28, 10),
  pl_material_in DECIMAL(28, 10),
  pl_material_overhead_in DECIMAL(28, 10),
  pl_resource_in DECIMAL(28, 10),
  pl_overhead_in DECIMAL(28, 10),
  pl_outside_processing_in DECIMAL(28, 10),
  tl_material_out DECIMAL(28, 10),
  tl_material_overhead_out DECIMAL(28, 10),
  tl_resource_out DECIMAL(28, 10),
  tl_overhead_out DECIMAL(28, 10),
  tl_outside_processing_out DECIMAL(28, 10),
  pl_material_out DECIMAL(28, 10),
  pl_material_overhead_out DECIMAL(28, 10),
  pl_resource_out DECIMAL(28, 10),
  pl_overhead_out DECIMAL(28, 10),
  pl_outside_processing_out DECIMAL(28, 10),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  tl_material_var DECIMAL(28, 10),
  tl_material_overhead_var DECIMAL(28, 10),
  tl_resource_var DECIMAL(28, 10),
  tl_outside_processing_var DECIMAL(28, 10),
  tl_overhead_var DECIMAL(28, 10),
  pl_material_var DECIMAL(28, 10),
  pl_material_overhead_var DECIMAL(28, 10),
  pl_resource_var DECIMAL(28, 10),
  pl_overhead_var DECIMAL(28, 10),
  pl_outside_processing_var DECIMAL(28, 10),
  tl_scrap_in DECIMAL(28, 10),
  tl_scrap_out DECIMAL(28, 10),
  tl_scrap_var DECIMAL(28, 10),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.WIP_PERIOD_BALANCES (
  acct_period_id,
  wip_entity_id,
  repetitive_schedule_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  organization_id,
  class_type,
  tl_resource_in,
  tl_overhead_in,
  tl_outside_processing_in,
  pl_material_in,
  pl_material_overhead_in,
  pl_resource_in,
  pl_overhead_in,
  pl_outside_processing_in,
  tl_material_out,
  tl_material_overhead_out,
  tl_resource_out,
  tl_overhead_out,
  tl_outside_processing_out,
  pl_material_out,
  pl_material_overhead_out,
  pl_resource_out,
  pl_overhead_out,
  pl_outside_processing_out,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  tl_material_var,
  tl_material_overhead_var,
  tl_resource_var,
  tl_outside_processing_var,
  tl_overhead_var,
  pl_material_var,
  pl_material_overhead_var,
  pl_resource_var,
  pl_overhead_var,
  pl_outside_processing_var,
  tl_scrap_in,
  tl_scrap_out,
  tl_scrap_var,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  acct_period_id,
  wip_entity_id,
  repetitive_schedule_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  organization_id,
  class_type,
  tl_resource_in,
  tl_overhead_in,
  tl_outside_processing_in,
  pl_material_in,
  pl_material_overhead_in,
  pl_resource_in,
  pl_overhead_in,
  pl_outside_processing_in,
  tl_material_out,
  tl_material_overhead_out,
  tl_resource_out,
  tl_overhead_out,
  tl_outside_processing_out,
  pl_material_out,
  pl_material_overhead_out,
  pl_resource_out,
  pl_overhead_out,
  pl_outside_processing_out,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  tl_material_var,
  tl_material_overhead_var,
  tl_resource_var,
  tl_outside_processing_var,
  tl_overhead_var,
  pl_material_var,
  pl_material_overhead_var,
  pl_resource_var,
  pl_overhead_var,
  pl_outside_processing_var,
  tl_scrap_in,
  tl_scrap_out,
  tl_scrap_var,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.WIP_PERIOD_BALANCES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wip_period_balances';