DROP TABLE IF EXISTS silver_bec_ods.GL_CURRENCIES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.GL_CURRENCIES (
  CURRENCY_CODE STRING,
  LAST_UPDATE_DATE TIMESTAMP,
  LAST_UPDATED_BY DECIMAL(15, 0),
  CREATION_DATE TIMESTAMP,
  CREATED_BY DECIMAL(15, 0),
  LAST_UPDATE_LOGIN DECIMAL(15, 0),
  ENABLED_FLAG STRING,
  CURRENCY_FLAG STRING,
  DESCRIPTION STRING,
  ISSUING_TERRITORY_CODE STRING,
  PRECISION DECIMAL(1, 0),
  EXTENDED_PRECISION DECIMAL(2, 0),
  SYMBOL STRING,
  START_DATE_ACTIVE TIMESTAMP,
  END_DATE_ACTIVE TIMESTAMP,
  MINIMUM_ACCOUNTABLE_UNIT DECIMAL(15, 0),
  CONTEXT STRING,
  ISO_FLAG STRING,
  ATTRIBUTE1 STRING,
  ATTRIBUTE2 STRING,
  ATTRIBUTE3 STRING,
  ATTRIBUTE4 STRING,
  ATTRIBUTE5 STRING,
  ATTRIBUTE6 STRING,
  ATTRIBUTE7 STRING,
  ATTRIBUTE8 STRING,
  ATTRIBUTE9 STRING,
  ATTRIBUTE10 STRING,
  ATTRIBUTE11 STRING,
  ATTRIBUTE12 STRING,
  ATTRIBUTE13 STRING,
  ATTRIBUTE14 STRING,
  ATTRIBUTE15 STRING,
  GLOBAL_ATTRIBUTE_CATEGORY STRING,
  GLOBAL_ATTRIBUTE1 STRING,
  GLOBAL_ATTRIBUTE2 STRING,
  GLOBAL_ATTRIBUTE3 STRING,
  GLOBAL_ATTRIBUTE4 STRING,
  GLOBAL_ATTRIBUTE5 STRING,
  GLOBAL_ATTRIBUTE6 STRING,
  GLOBAL_ATTRIBUTE7 STRING,
  GLOBAL_ATTRIBUTE8 STRING,
  GLOBAL_ATTRIBUTE9 STRING,
  GLOBAL_ATTRIBUTE10 STRING,
  GLOBAL_ATTRIBUTE11 STRING,
  GLOBAL_ATTRIBUTE12 STRING,
  GLOBAL_ATTRIBUTE13 STRING,
  GLOBAL_ATTRIBUTE14 STRING,
  GLOBAL_ATTRIBUTE15 STRING,
  GLOBAL_ATTRIBUTE16 STRING,
  GLOBAL_ATTRIBUTE17 STRING,
  GLOBAL_ATTRIBUTE18 STRING,
  GLOBAL_ATTRIBUTE19 STRING,
  GLOBAL_ATTRIBUTE20 STRING,
  DERIVE_EFFECTIVE TIMESTAMP,
  DERIVE_TYPE STRING,
  DERIVE_FACTOR DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.GL_CURRENCIES (
  currency_code,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  enabled_flag,
  currency_flag,
  description,
  issuing_territory_code,
  `precision`,
  extended_precision,
  symbol,
  start_date_active,
  end_date_active,
  minimum_accountable_unit,
  context,
  iso_flag,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  derive_effective,
  derive_type,
  derive_factor,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  currency_code,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  enabled_flag,
  currency_flag,
  description,
  issuing_territory_code,
  `precision`,
  extended_precision,
  symbol,
  start_date_active,
  end_date_active,
  minimum_accountable_unit,
  context,
  iso_flag,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  derive_effective,
  derive_type,
  derive_factor,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.GL_CURRENCIES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_currencies';