DROP TABLE IF EXISTS silver_bec_ods.CST_COST_UPDATES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.CST_COST_UPDATES (
  cost_update_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  status DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  cost_type_id DECIMAL(15, 0),
  update_date TIMESTAMP,
  description STRING,
  range_option DECIMAL(15, 0),
  update_resource_ovhd_flag DECIMAL(15, 0),
  update_activity_flag DECIMAL(15, 0),
  snapshot_saved_flag DECIMAL(15, 0),
  inv_adjustment_account DECIMAL(15, 0),
  single_item DECIMAL(15, 0),
  item_range_low STRING,
  item_range_high STRING,
  category_id DECIMAL(15, 0),
  category_set_id DECIMAL(15, 0),
  inventory_adjustment_value DECIMAL(28, 10),
  intransit_adjustment_value DECIMAL(28, 10),
  wip_adjustment_value DECIMAL(28, 10),
  scrap_adjustment_value DECIMAL(28, 10),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.CST_COST_UPDATES (
  cost_update_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  status,
  organization_id,
  cost_type_id,
  update_date,
  description,
  range_option,
  update_resource_ovhd_flag,
  update_activity_flag,
  snapshot_saved_flag,
  inv_adjustment_account,
  single_item,
  item_range_low,
  item_range_high,
  category_id,
  category_set_id,
  inventory_adjustment_value,
  intransit_adjustment_value,
  wip_adjustment_value,
  scrap_adjustment_value,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cost_update_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  status,
  organization_id,
  cost_type_id,
  update_date,
  description,
  range_option,
  update_resource_ovhd_flag,
  update_activity_flag,
  snapshot_saved_flag,
  inv_adjustment_account,
  single_item,
  item_range_low,
  item_range_high,
  category_id,
  category_set_id,
  inventory_adjustment_value,
  intransit_adjustment_value,
  wip_adjustment_value,
  scrap_adjustment_value,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.CST_COST_UPDATES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cst_cost_updates';