DROP TABLE IF EXISTS silver_bec_ods.BEC_CVMI_CONSUMPTION_VIEW;
CREATE TABLE IF NOT EXISTS silver_bec_ods.BEC_CVMI_CONSUMPTION_VIEW (
  consumption_date TIMESTAMP,
  po_number STRING,
  release_num DECIMAL(15, 0),
  vendor_id DECIMAL(15, 0),
  vendor_name STRING,
  vendor_site_code STRING,
  organization_id DECIMAL(15, 0),
  organization_code STRING,
  organization_name STRING,
  item STRING,
  description STRING,
  consumption_quantity DECIMAL(28, 10),
  unit_price DECIMAL(28, 10),
  consumption_value DECIMAL(28, 10),
  consumption_processed_flag STRING,
  po_distribution_id DECIMAL(15, 00),
  invoice_id DECIMAL(15, 0),
  invoice_num STRING,
  creation_date TIMESTAMP,
  invoice_date TIMESTAMP,
  invoice_line_amount DECIMAL(28, 10),
  invoice_amount DECIMAL(28, 10),
  amount_paid DECIMAL(28, 10),
  material_cost DECIMAL(28, 10),
  extended_cost DECIMAL(28, 10),
  consigned_ppv DECIMAL(28, 10),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.BEC_CVMI_CONSUMPTION_VIEW (
  consumption_date,
  po_number,
  release_num,
  vendor_id,
  vendor_name,
  vendor_site_code,
  organization_id,
  organization_code,
  organization_name,
  item,
  description,
  consumption_quantity,
  unit_price,
  consumption_value,
  consumption_processed_flag,
  po_distribution_id,
  invoice_id,
  invoice_num,
  creation_date,
  invoice_date,
  invoice_line_amount,
  invoice_amount,
  amount_paid,
  material_cost,
  extended_cost,
  consigned_ppv,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  consumption_date,
  po_number,
  release_num,
  vendor_id,
  vendor_name,
  vendor_site_code,
  organization_id,
  organization_code,
  organization_name,
  item,
  description,
  consumption_quantity,
  unit_price,
  consumption_value,
  consumption_processed_flag,
  po_distribution_id,
  invoice_id,
  invoice_num,
  creation_date,
  invoice_date,
  invoice_line_amount,
  invoice_amount,
  amount_paid,
  material_cost,
  extended_cost,
  consigned_ppv,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.BEC_CVMI_CONSUMPTION_VIEW;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'bec_cvmi_consumption_view';