DROP table IF EXISTS silver_bec_ods.MTL_MATERIAL_TRANSACTIONS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_MATERIAL_TRANSACTIONS (
  transaction_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  inventory_item_id DECIMAL(15, 0),
  revision STRING,
  organization_id DECIMAL(15, 0),
  subinventory_code STRING,
  locator_id DECIMAL(15, 0),
  transaction_type_id DECIMAL(15, 0),
  transaction_action_id DECIMAL(15, 0),
  transaction_source_type_id DECIMAL(15, 0),
  transaction_source_id DECIMAL(15, 0),
  transaction_source_name STRING,
  transaction_quantity DECIMAL(28, 10),
  transaction_uom STRING,
  primary_quantity DECIMAL(28, 10),
  transaction_date TIMESTAMP,
  variance_amount DECIMAL(28, 10),
  acct_period_id DECIMAL(15, 0),
  transaction_reference STRING,
  reason_id DECIMAL(15, 0),
  distribution_account_id DECIMAL(15, 0),
  encumbrance_account DECIMAL(15, 0),
  encumbrance_amount DECIMAL(28, 10),
  cost_update_id DECIMAL(15, 0),
  costed_flag STRING,
  invoiced_flag STRING,
  actual_cost DECIMAL(28, 10),
  transaction_cost DECIMAL(38, 10),
  prior_cost DECIMAL(28, 10),
  new_cost DECIMAL(28, 10),
  currency_code STRING,
  currency_conversion_rate DECIMAL(28, 10),
  currency_conversion_type STRING,
  currency_conversion_date TIMESTAMP,
  ussgl_transaction_code STRING,
  quantity_adjusted DECIMAL(28, 10),
  employee_code STRING,
  department_id DECIMAL(15, 0),
  operation_seq_num DECIMAL(15, 0),
  master_schedule_update_code STRING,
  receiving_document STRING,
  picking_line_id DECIMAL(15, 0),
  trx_source_line_id DECIMAL(15, 0),
  trx_source_delivery_id DECIMAL(15, 0),
  repetitive_line_id DECIMAL(15, 0),
  physical_adjustment_id DECIMAL(15, 0),
  cycle_count_id DECIMAL(15, 0),
  rma_line_id DECIMAL(15, 0),
  transfer_transaction_id DECIMAL(15, 0),
  transaction_set_id DECIMAL(15, 0),
  rcv_transaction_id DECIMAL(15, 0),
  move_transaction_id DECIMAL(15, 0),
  completion_transaction_id DECIMAL(15, 0),
  source_code STRING,
  source_line_id DECIMAL(15, 0),
  vendor_lot_number STRING,
  transfer_organization_id DECIMAL(15, 0),
  transfer_subinventory STRING,
  transfer_locator_id DECIMAL(15, 0),
  shipment_number STRING,
  transfer_cost DECIMAL(28, 10),
  transportation_dist_account DECIMAL(28, 10),
  transportation_cost DECIMAL(28, 10),
  transfer_cost_dist_account DECIMAL(28, 10),
  waybill_airbill STRING,
  freight_code STRING,
  number_of_containers DECIMAL(15, 0),
  value_change DECIMAL(15, 0),
  percentage_change DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  movement_id DECIMAL(15, 0),
  transaction_group_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  to_task_id DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  to_project_id DECIMAL(15, 0),
  source_project_id DECIMAL(15, 0),
  pa_expenditure_org_id DECIMAL(15, 0),
  source_task_id DECIMAL(15, 0),
  expenditure_type STRING,
  error_code STRING,
  error_explanation STRING,
  prior_costed_quantity DECIMAL(28, 10),
  final_completion_flag STRING,
  pm_cost_collected STRING,
  pm_cost_collector_group_id DECIMAL(15, 0),
  shipment_costed STRING,
  transfer_percentage DECIMAL(28, 10),
  material_account DECIMAL(28, 10),
  material_overhead_account DECIMAL(28, 10),
  resource_account DECIMAL(28, 10),
  outside_processing_account DECIMAL(28, 10),
  overhead_account DECIMAL(28, 10),
  cost_group_id DECIMAL(15, 0),
  transfer_cost_group_id DECIMAL(15, 0),
  flow_schedule STRING,
  transfer_prior_costed_quantity DECIMAL(28, 10),
  shortage_process_code DECIMAL(15, 0),
  qa_collection_id DECIMAL(15, 0),
  overcompletion_transaction_qty DECIMAL(28, 10),
  overcompletion_primary_qty DECIMAL(28, 10),
  overcompletion_transaction_id DECIMAL(15, 0),
  mvt_stat_status STRING,
  common_bom_seq_id DECIMAL(15, 0),
  common_routing_seq_id DECIMAL(15, 0),
  org_cost_group_id DECIMAL(15, 0),
  cost_type_id DECIMAL(15, 0),
  periodic_primary_quantity DECIMAL(28, 10),
  move_order_line_id DECIMAL(15, 0),
  task_group_id DECIMAL(15, 0),
  pick_slip_number DECIMAL(15, 0),
  lpn_id DECIMAL(15, 0),
  transfer_lpn_id DECIMAL(15, 0),
  pick_strategy_id DECIMAL(15, 0),
  pick_rule_id DECIMAL(15, 0),
  put_away_strategy_id DECIMAL(15, 0),
  put_away_rule_id DECIMAL(15, 0),
  content_lpn_id DECIMAL(15, 0),
  pick_slip_date TIMESTAMP,
  cost_category_id DECIMAL(15, 0),
  organization_type DECIMAL(15, 0),
  transfer_organization_type DECIMAL(15, 0),
  owning_organization_id DECIMAL(15, 0),
  owning_tp_type DECIMAL(15, 0),
  xfr_owning_organization_id DECIMAL(15, 0),
  transfer_owning_tp_type DECIMAL(15, 0),
  planning_organization_id DECIMAL(15, 0),
  planning_tp_type DECIMAL(15, 0),
  xfr_planning_organization_id DECIMAL(15, 0),
  transfer_planning_tp_type DECIMAL(15, 0),
  secondary_uom_code STRING,
  secondary_transaction_quantity DECIMAL(28, 10),
  transaction_group_seq DECIMAL(15, 0),
  ship_to_location_id DECIMAL(15, 0),
  reservation_id DECIMAL(15, 0),
  transaction_mode DECIMAL(15, 0),
  transaction_batch_id DECIMAL(15, 0),
  transaction_batch_seq DECIMAL(15, 0),
  intransit_account DECIMAL(15, 0),
  fob_point DECIMAL(15, 0),
  parent_transaction_id DECIMAL(15, 0),
  logical_trx_type_code DECIMAL(15, 0),
  trx_flow_header_id DECIMAL(15, 0),
  logical_transactions_created DECIMAL(15, 0),
  logical_transaction DECIMAL(15, 0),
  intercompany_cost DECIMAL(15, 0),
  intercompany_pricing_option DECIMAL(15, 0),
  intercompany_currency_code STRING,
  original_transaction_temp_id DECIMAL(15, 0),
  transfer_price DECIMAL(28, 10),
  expense_account_id DECIMAL(15, 0),
  cogs_recognition_percent DECIMAL(15, 0),
  so_issue_account_type DECIMAL(15, 0),
  opm_costed_flag STRING,
  material_expense_account DECIMAL(15, 0),
  MCC_CODE STRING,
  TRANSACTION_EXTRACTED STRING,
  XML_DOCUMENT_ID DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_MATERIAL_TRANSACTIONS (
  transaction_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  inventory_item_id,
  revision,
  organization_id,
  subinventory_code,
  locator_id,
  transaction_type_id,
  transaction_action_id,
  transaction_source_type_id,
  transaction_source_id,
  transaction_source_name,
  transaction_quantity,
  transaction_uom,
  primary_quantity,
  transaction_date,
  variance_amount,
  acct_period_id,
  transaction_reference,
  reason_id,
  distribution_account_id,
  encumbrance_account,
  encumbrance_amount,
  cost_update_id,
  costed_flag,
  invoiced_flag,
  actual_cost,
  transaction_cost,
  prior_cost,
  new_cost,
  currency_code,
  currency_conversion_rate,
  currency_conversion_type,
  currency_conversion_date,
  ussgl_transaction_code,
  quantity_adjusted,
  employee_code,
  department_id,
  operation_seq_num,
  master_schedule_update_code,
  receiving_document,
  picking_line_id,
  trx_source_line_id,
  trx_source_delivery_id,
  repetitive_line_id,
  physical_adjustment_id,
  cycle_count_id,
  rma_line_id,
  transfer_transaction_id,
  transaction_set_id,
  rcv_transaction_id,
  move_transaction_id,
  completion_transaction_id,
  source_code,
  source_line_id,
  vendor_lot_number,
  transfer_organization_id,
  transfer_subinventory,
  transfer_locator_id,
  shipment_number,
  transfer_cost,
  transportation_dist_account,
  transportation_cost,
  transfer_cost_dist_account,
  waybill_airbill,
  freight_code,
  number_of_containers,
  value_change,
  percentage_change,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  movement_id,
  transaction_group_id,
  task_id,
  to_task_id,
  project_id,
  to_project_id,
  source_project_id,
  pa_expenditure_org_id,
  source_task_id,
  expenditure_type,
  error_code,
  error_explanation,
  prior_costed_quantity,
  final_completion_flag,
  pm_cost_collected,
  pm_cost_collector_group_id,
  shipment_costed,
  transfer_percentage,
  material_account,
  material_overhead_account,
  resource_account,
  outside_processing_account,
  overhead_account,
  cost_group_id,
  transfer_cost_group_id,
  flow_schedule,
  transfer_prior_costed_quantity,
  shortage_process_code,
  qa_collection_id,
  overcompletion_transaction_qty,
  overcompletion_primary_qty,
  overcompletion_transaction_id,
  mvt_stat_status,
  common_bom_seq_id,
  common_routing_seq_id,
  org_cost_group_id,
  cost_type_id,
  periodic_primary_quantity,
  move_order_line_id,
  task_group_id,
  pick_slip_number,
  lpn_id,
  transfer_lpn_id,
  pick_strategy_id,
  pick_rule_id,
  put_away_strategy_id,
  put_away_rule_id,
  content_lpn_id,
  pick_slip_date,
  cost_category_id,
  organization_type,
  transfer_organization_type,
  owning_organization_id,
  owning_tp_type,
  xfr_owning_organization_id,
  transfer_owning_tp_type,
  planning_organization_id,
  planning_tp_type,
  xfr_planning_organization_id,
  transfer_planning_tp_type,
  secondary_uom_code,
  secondary_transaction_quantity,
  transaction_group_seq,
  ship_to_location_id,
  reservation_id,
  transaction_mode,
  transaction_batch_id,
  transaction_batch_seq,
  intransit_account,
  fob_point,
  parent_transaction_id,
  logical_trx_type_code,
  trx_flow_header_id,
  logical_transactions_created,
  logical_transaction,
  intercompany_cost,
  intercompany_pricing_option,
  intercompany_currency_code,
  original_transaction_temp_id,
  transfer_price,
  expense_account_id,
  cogs_recognition_percent,
  so_issue_account_type,
  opm_costed_flag,
  material_expense_account,
  MCC_CODE,
  TRANSACTION_EXTRACTED,
  XML_DOCUMENT_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    transaction_id,
    last_update_date,
    last_updated_by,
    creation_date,
    created_by,
    last_update_login,
    request_id,
    program_application_id,
    program_id,
    program_update_date,
    inventory_item_id,
    revision,
    organization_id,
    subinventory_code,
    locator_id,
    transaction_type_id,
    transaction_action_id,
    transaction_source_type_id,
    transaction_source_id,
    transaction_source_name,
    transaction_quantity,
    transaction_uom,
    primary_quantity,
    transaction_date,
    variance_amount,
    acct_period_id,
    transaction_reference,
    reason_id,
    distribution_account_id,
    encumbrance_account,
    encumbrance_amount,
    cost_update_id,
    costed_flag,
    invoiced_flag,
    actual_cost,
    transaction_cost,
    prior_cost,
    new_cost,
    currency_code,
    currency_conversion_rate,
    currency_conversion_type,
    currency_conversion_date,
    ussgl_transaction_code,
    quantity_adjusted,
    employee_code,
    department_id,
    operation_seq_num,
    master_schedule_update_code,
    receiving_document,
    picking_line_id,
    trx_source_line_id,
    trx_source_delivery_id,
    repetitive_line_id,
    physical_adjustment_id,
    cycle_count_id,
    rma_line_id,
    transfer_transaction_id,
    transaction_set_id,
    rcv_transaction_id,
    move_transaction_id,
    completion_transaction_id,
    source_code,
    source_line_id,
    vendor_lot_number,
    transfer_organization_id,
    transfer_subinventory,
    transfer_locator_id,
    shipment_number,
    transfer_cost,
    transportation_dist_account,
    transportation_cost,
    transfer_cost_dist_account,
    waybill_airbill,
    freight_code,
    number_of_containers,
    value_change,
    percentage_change,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    movement_id,
    transaction_group_id,
    task_id,
    to_task_id,
    project_id,
    to_project_id,
    source_project_id,
    pa_expenditure_org_id,
    source_task_id,
    expenditure_type,
    error_code,
    error_explanation,
    prior_costed_quantity,
    final_completion_flag,
    pm_cost_collected,
    pm_cost_collector_group_id,
    shipment_costed,
    transfer_percentage,
    material_account,
    material_overhead_account,
    resource_account,
    outside_processing_account,
    overhead_account,
    cost_group_id,
    transfer_cost_group_id,
    flow_schedule,
    transfer_prior_costed_quantity,
    shortage_process_code,
    qa_collection_id,
    overcompletion_transaction_qty,
    overcompletion_primary_qty,
    overcompletion_transaction_id,
    mvt_stat_status,
    common_bom_seq_id,
    common_routing_seq_id,
    org_cost_group_id,
    cost_type_id,
    periodic_primary_quantity,
    move_order_line_id,
    task_group_id,
    pick_slip_number,
    lpn_id,
    transfer_lpn_id,
    pick_strategy_id,
    pick_rule_id,
    put_away_strategy_id,
    put_away_rule_id,
    content_lpn_id,
    pick_slip_date,
    cost_category_id,
    organization_type,
    transfer_organization_type,
    owning_organization_id,
    owning_tp_type,
    xfr_owning_organization_id,
    transfer_owning_tp_type,
    planning_organization_id,
    planning_tp_type,
    xfr_planning_organization_id,
    transfer_planning_tp_type,
    secondary_uom_code,
    secondary_transaction_quantity,
    transaction_group_seq,
    ship_to_location_id,
    reservation_id,
    transaction_mode,
    transaction_batch_id,
    transaction_batch_seq,
    intransit_account,
    fob_point,
    parent_transaction_id,
    logical_trx_type_code,
    trx_flow_header_id,
    logical_transactions_created,
    logical_transaction,
    intercompany_cost,
    intercompany_pricing_option,
    intercompany_currency_code,
    original_transaction_temp_id,
    transfer_price,
    expense_account_id,
    cogs_recognition_percent,
    so_issue_account_type,
    opm_costed_flag,
    material_expense_account,
    MCC_CODE,
    TRANSACTION_EXTRACTED,
    XML_DOCUMENT_ID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MTL_MATERIAL_TRANSACTIONS
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_material_transactions';