DROP TABLE IF EXISTS silver_bec_ods.PO_ACTION_HISTORY;
CREATE TABLE IF NOT EXISTS silver_bec_ods.PO_ACTION_HISTORY (
  object_id DECIMAL(15, 0),
  object_type_code STRING,
  object_sub_type_code STRING,
  sequence_num DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  action_code STRING,
  action_date TIMESTAMP,
  employee_id DECIMAL(9, 0),
  approval_path_id DECIMAL(15, 0),
  note STRING,
  object_revision_num DECIMAL(15, 0),
  offline_code STRING,
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  program_date TIMESTAMP,
  approval_group_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.PO_ACTION_HISTORY (
  object_id,
  object_type_code,
  object_sub_type_code,
  sequence_num,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  action_code,
  action_date,
  employee_id,
  approval_path_id,
  note,
  object_revision_num,
  offline_code,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  program_date,
  approval_group_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  object_id,
  object_type_code,
  object_sub_type_code,
  sequence_num,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  action_code,
  action_date,
  employee_id,
  approval_path_id,
  note,
  object_revision_num,
  offline_code,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  program_date,
  approval_group_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.PO_ACTION_HISTORY;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'po_action_history ';