DROP TABLE IF EXISTS silver_bec_ods.AR_ADJUSTMENTS_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.AR_ADJUSTMENTS_ALL (
  adjustment_id DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  amount DECIMAL(28, 10),
  apply_date TIMESTAMP,
  gl_date TIMESTAMP,
  set_of_books_id DECIMAL(15, 0),
  code_combination_id DECIMAL(15, 0),
  `type` STRING,
  adjustment_type STRING,
  status STRING,
  line_adjusted DECIMAL(28, 10),
  freight_adjusted DECIMAL(15, 0),
  tax_adjusted DECIMAL(28, 10),
  receivables_charges_adjusted DECIMAL(28, 10),
  associated_cash_receipt_id DECIMAL(15, 0),
  chargeback_customer_trx_id DECIMAL(15, 0),
  batch_id DECIMAL(15, 0),
  customer_trx_id DECIMAL(15, 0),
  customer_trx_line_id DECIMAL(15, 0),
  subsequent_trx_id DECIMAL(15, 0),
  payment_schedule_id DECIMAL(15, 0),
  receivables_trx_id DECIMAL(15, 0),
  distribution_set_id DECIMAL(15, 0),
  gl_posted_date TIMESTAMP,
  comments STRING,
  automatically_generated STRING,
  created_from STRING,
  reason_code STRING,
  postable STRING,
  approved_by DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  posting_control_id DECIMAL(15, 0),
  acctd_amount DECIMAL(28, 10),
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  adjustment_number STRING,
  org_id DECIMAL(15, 0),
  ussgl_transaction_code STRING,
  ussgl_transaction_code_context STRING,
  doc_sequence_value DECIMAL(15, 0),
  doc_sequence_id DECIMAL(15, 0),
  associated_application_id DECIMAL(15, 0),
  cons_inv_id DECIMAL(15, 0),
  mrc_gl_posted_date STRING,
  mrc_posting_control_id STRING,
  mrc_acctd_amount STRING,
  adj_tax_acct_rule STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  link_to_trx_hist_id DECIMAL(15, 0),
  event_id DECIMAL(15, 0),
  upgrade_method STRING,
  ax_accounted_flag STRING,
  interest_header_id DECIMAL(15, 0),
  interest_line_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ar_adjustments_all (
  adjustment_id,
  last_updated_by,
  last_update_date,
  last_update_login,
  created_by,
  creation_date,
  amount,
  apply_date,
  gl_date,
  set_of_books_id,
  code_combination_id,
  `type`,
  adjustment_type,
  status,
  line_adjusted,
  freight_adjusted,
  tax_adjusted,
  receivables_charges_adjusted,
  associated_cash_receipt_id,
  chargeback_customer_trx_id,
  batch_id,
  customer_trx_id,
  customer_trx_line_id,
  subsequent_trx_id,
  payment_schedule_id,
  receivables_trx_id,
  distribution_set_id,
  gl_posted_date,
  comments,
  automatically_generated,
  created_from,
  reason_code,
  postable,
  approved_by,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  posting_control_id,
  acctd_amount,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  adjustment_number,
  org_id,
  ussgl_transaction_code,
  ussgl_transaction_code_context,
  doc_sequence_value,
  doc_sequence_id,
  associated_application_id,
  cons_inv_id,
  mrc_gl_posted_date,
  mrc_posting_control_id,
  mrc_acctd_amount,
  adj_tax_acct_rule,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  link_to_trx_hist_id,
  event_id,
  upgrade_method,
  ax_accounted_flag,
  interest_header_id,
  interest_line_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  adjustment_id,
  last_updated_by,
  last_update_date,
  last_update_login,
  created_by,
  creation_date,
  amount,
  apply_date,
  gl_date,
  set_of_books_id,
  code_combination_id,
  `type`,
  adjustment_type,
  status,
  line_adjusted,
  freight_adjusted,
  tax_adjusted,
  receivables_charges_adjusted,
  associated_cash_receipt_id,
  chargeback_customer_trx_id,
  batch_id,
  customer_trx_id,
  customer_trx_line_id,
  subsequent_trx_id,
  payment_schedule_id,
  receivables_trx_id,
  distribution_set_id,
  gl_posted_date,
  comments,
  automatically_generated,
  created_from,
  reason_code,
  postable,
  approved_by,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  posting_control_id,
  acctd_amount,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  adjustment_number,
  org_id,
  ussgl_transaction_code,
  ussgl_transaction_code_context,
  doc_sequence_value,
  doc_sequence_id,
  associated_application_id,
  cons_inv_id,
  mrc_gl_posted_date,
  mrc_posting_control_id,
  mrc_acctd_amount,
  adj_tax_acct_rule,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  link_to_trx_hist_id,
  event_id,
  upgrade_method,
  ax_accounted_flag,
  interest_header_id,
  interest_line_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ar_adjustments_all;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ar_adjustments_all';