DROP TABLE IF EXISTS silver_bec_ods.ap_system_parameters_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_system_parameters_all (
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  base_currency_code STRING,
  recalc_pay_schedule_flag STRING,
  auto_calculate_interest_flag STRING,
  invoice_currency_code STRING,
  payment_currency_code STRING,
  invoice_net_gross_flag STRING,
  bank_account_id DECIMAL(15, 0),
  check_overflow_lookup_code STRING,
  batch_control_flag STRING,
  terms_id DECIMAL(15, 0),
  always_take_disc_flag STRING,
  pay_date_basis_lookup_code STRING,
  accts_pay_code_combination_id DECIMAL(15, 0),
  sales_tax_code_combination_id DECIMAL(15, 0),
  disc_lost_code_combination_id DECIMAL(15, 0),
  disc_taken_code_combination_id DECIMAL(15, 0),
  hold_gain_code_combination_id DECIMAL(15, 0),
  trans_gain_code_combination_id DECIMAL(15, 0),
  apply_advances_default STRING,
  add_days_settlement_date DECIMAL(15, 0),
  cost_of_money DECIMAL(28, 10),
  days_between_check_cycles DECIMAL(15, 0),
  federal_identification_num STRING,
  location_id DECIMAL(15, 0),
  create_employee_vendor_flag STRING,
  employee_terms_id DECIMAL(15, 0),
  employee_pay_group_lookup_code STRING,
  employee_payment_priority DECIMAL(2, 0),
  prepay_code_combination_id DECIMAL(15, 0),
  confirm_date_as_inv_num_flag STRING,
  update_pay_site_flag STRING,
  default_exchange_rate_type STRING,
  gain_code_combination_id DECIMAL(15, 0),
  loss_code_combination_id DECIMAL(15, 0),
  make_rate_mandatory_flag STRING,
  multi_currency_flag STRING,
  gl_date_from_receipt_flag STRING,
  disc_is_inv_less_tax_flag STRING,
  match_on_tax_flag STRING,
  accounting_method_option STRING,
  expense_post_option STRING,
  discount_taken_post_option STRING,
  gain_loss_post_option STRING,
  cash_post_option STRING,
  future_pay_post_option STRING,
  date_format_lookup_code STRING,
  replace_check_flag STRING,
  online_print_flag STRING,
  eft_user_number STRING,
  max_outlay DECIMAL(28, 10),
  vendor_pay_group_lookup_code STRING,
  require_tax_entry_flag STRING,
  approvals_option STRING,
  post_dated_payments_flag STRING,
  secondary_accounting_method STRING,
  secondary_set_of_books_id DECIMAL(15, 0),
  take_vat_before_discount_flag STRING,
  interest_tolerance_amount DECIMAL(28, 10),
  interest_code_combination_id DECIMAL(15, 0),
  terms_date_basis STRING,
  allow_future_pay_flag STRING,
  auto_tax_calc_flag STRING,
  automatic_offsets_flag STRING,
  liability_post_lookup_code STRING,
  interest_accts_pay_ccid DECIMAL(15, 0),
  liability_post_option STRING,
  discount_distribution_method STRING,
  rate_var_code_combination_id DECIMAL(15, 0),
  combined_filing_flag STRING,
  income_tax_region STRING,
  income_tax_region_flag STRING,
  hold_unmatched_invoices_flag STRING,
  allow_dist_match_flag STRING,
  allow_final_match_flag STRING,
  allow_flex_override_flag STRING,
  allow_paid_invoice_adjust STRING,
  ussgl_transaction_code STRING,
  ussgl_trx_code_context STRING,
  inv_doc_category_override STRING,
  pay_doc_category_override STRING,
  vendor_auto_int_default STRING,
  summary_journals_default STRING,
  rate_var_gain_ccid DECIMAL(15, 0),
  rate_var_loss_ccid DECIMAL(15, 0),
  transfer_desc_flex_flag STRING,
  allow_awt_flag STRING,
  default_awt_group_id DECIMAL(15, 0),
  allow_awt_override STRING,
  create_awt_dists_type STRING,
  create_awt_invoices_type STRING,
  awt_include_discount_amt STRING,
  awt_include_tax_amt STRING,
  org_id DECIMAL(15, 0),
  recon_accounting_flag STRING,
  auto_create_freight_flag STRING,
  freight_code_combination_id DECIMAL(15, 0),
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  allow_supplier_bank_override STRING,
  use_multiple_supplier_banks STRING,
  auto_tax_calc_override STRING,
  amount_includes_tax_flag STRING,
  amount_includes_tax_override STRING,
  vat_code STRING,
  use_bank_charge_flag STRING,
  bank_charge_bearer STRING,
  rounding_error_ccid DECIMAL(15, 0),
  rounding_error_post_option STRING,
  tax_from_po_flag STRING,
  tax_from_vendor_site_flag STRING,
  tax_from_vendor_flag STRING,
  tax_from_account_flag STRING,
  tax_from_system_flag STRING,
  tax_from_inv_header_flag STRING,
  tax_from_template_flag STRING,
  tax_hier_po_shipment DECIMAL(28, 10),
  tax_hier_vendor DECIMAL(28, 10),
  tax_hier_vendor_site DECIMAL(28, 10),
  tax_hier_account DECIMAL(28, 10),
  tax_hier_system DECIMAL(28, 10),
  tax_hier_invoice DECIMAL(28, 10),
  tax_hier_template DECIMAL(28, 10),
  enforce_tax_from_account STRING,
  mrc_base_currency_code STRING,
  mrc_secondary_set_of_books_id STRING,
  match_option STRING,
  gain_loss_calc_level STRING,
  when_to_account_pmt STRING,
  when_to_account_gain_loss STRING,
  future_dated_pmt_acct_source STRING,
  future_dated_pmt_liab_relief STRING,
  gl_transfer_allow_override STRING,
  gl_transfer_process_days DECIMAL(15, 0),
  gl_transfer_mode STRING,
  gl_transfer_submit_journal_imp STRING,
  include_reporting_sob STRING,
  expense_report_id DECIMAL(15, 0),
  prepayment_terms_id DECIMAL(15, 0),
  calc_user_xrate STRING,
  sort_by_alternate_field STRING,
  approval_workflow_flag STRING,
  allow_force_approval_flag STRING,
  validate_before_approval_flag STRING,
  xml_payments_auto_confirm_flag STRING,
  prorate_int_inv_across_dists STRING,
  build_prepayment_accounts_flag STRING,
  enable_1099_on_awt_flag STRING,
  stop_prepay_across_bal_flag STRING,
  automatic_offsets_change_flag STRING,
  tolerance_id DECIMAL(15, 0),
  tax_tolerance DECIMAL(28, 10),
  tax_tol_amt_range DECIMAL(28, 10),
  services_tolerance_id DECIMAL(15, 0),
  prepay_tax_diff_ccid DECIMAL(15, 0),
  ce_bank_acct_use_id DECIMAL(15, 0),
  approval_timing STRING,
  receipt_acceptance_days DECIMAL(15, 0),
  allow_inv_third_party_ovrd STRING,
  allow_pymt_third_party_ovrd STRING,
  WITHHOLDING_DATE_BASIS STRING,
  INVRATE_FOR_PREPAY_TAX STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_system_parameters_all (
  last_update_date,
  last_updated_by,
  set_of_books_id,
  base_currency_code,
  recalc_pay_schedule_flag,
  auto_calculate_interest_flag,
  invoice_currency_code,
  payment_currency_code,
  invoice_net_gross_flag,
  bank_account_id,
  check_overflow_lookup_code,
  batch_control_flag,
  terms_id,
  always_take_disc_flag,
  pay_date_basis_lookup_code,
  accts_pay_code_combination_id,
  sales_tax_code_combination_id,
  disc_lost_code_combination_id,
  disc_taken_code_combination_id,
  hold_gain_code_combination_id,
  trans_gain_code_combination_id,
  apply_advances_default,
  add_days_settlement_date,
  cost_of_money,
  days_between_check_cycles,
  federal_identification_num,
  location_id,
  create_employee_vendor_flag,
  employee_terms_id,
  employee_pay_group_lookup_code,
  employee_payment_priority,
  prepay_code_combination_id,
  confirm_date_as_inv_num_flag,
  update_pay_site_flag,
  default_exchange_rate_type,
  gain_code_combination_id,
  loss_code_combination_id,
  make_rate_mandatory_flag,
  multi_currency_flag,
  gl_date_from_receipt_flag,
  disc_is_inv_less_tax_flag,
  match_on_tax_flag,
  accounting_method_option,
  expense_post_option,
  discount_taken_post_option,
  gain_loss_post_option,
  cash_post_option,
  future_pay_post_option,
  date_format_lookup_code,
  replace_check_flag,
  online_print_flag,
  eft_user_number,
  max_outlay,
  vendor_pay_group_lookup_code,
  require_tax_entry_flag,
  approvals_option,
  post_dated_payments_flag,
  secondary_accounting_method,
  secondary_set_of_books_id,
  take_vat_before_discount_flag,
  interest_tolerance_amount,
  interest_code_combination_id,
  terms_date_basis,
  allow_future_pay_flag,
  auto_tax_calc_flag,
  automatic_offsets_flag,
  liability_post_lookup_code,
  interest_accts_pay_ccid,
  liability_post_option,
  discount_distribution_method,
  rate_var_code_combination_id,
  combined_filing_flag,
  income_tax_region,
  income_tax_region_flag,
  hold_unmatched_invoices_flag,
  allow_dist_match_flag,
  allow_final_match_flag,
  allow_flex_override_flag,
  allow_paid_invoice_adjust,
  ussgl_transaction_code,
  ussgl_trx_code_context,
  inv_doc_category_override,
  pay_doc_category_override,
  vendor_auto_int_default,
  summary_journals_default,
  rate_var_gain_ccid,
  rate_var_loss_ccid,
  transfer_desc_flex_flag,
  allow_awt_flag,
  default_awt_group_id,
  allow_awt_override,
  create_awt_dists_type,
  create_awt_invoices_type,
  awt_include_discount_amt,
  awt_include_tax_amt,
  org_id,
  recon_accounting_flag,
  auto_create_freight_flag,
  freight_code_combination_id,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  allow_supplier_bank_override,
  use_multiple_supplier_banks,
  auto_tax_calc_override,
  amount_includes_tax_flag,
  amount_includes_tax_override,
  vat_code,
  use_bank_charge_flag,
  bank_charge_bearer,
  rounding_error_ccid,
  rounding_error_post_option,
  tax_from_po_flag,
  tax_from_vendor_site_flag,
  tax_from_vendor_flag,
  tax_from_account_flag,
  tax_from_system_flag,
  tax_from_inv_header_flag,
  tax_from_template_flag,
  tax_hier_po_shipment,
  tax_hier_vendor,
  tax_hier_vendor_site,
  tax_hier_account,
  tax_hier_system,
  tax_hier_invoice,
  tax_hier_template,
  enforce_tax_from_account,
  mrc_base_currency_code,
  mrc_secondary_set_of_books_id,
  match_option,
  gain_loss_calc_level,
  when_to_account_pmt,
  when_to_account_gain_loss,
  future_dated_pmt_acct_source,
  future_dated_pmt_liab_relief,
  gl_transfer_allow_override,
  gl_transfer_process_days,
  gl_transfer_mode,
  gl_transfer_submit_journal_imp,
  include_reporting_sob,
  expense_report_id,
  prepayment_terms_id,
  calc_user_xrate,
  sort_by_alternate_field,
  approval_workflow_flag,
  allow_force_approval_flag,
  validate_before_approval_flag,
  xml_payments_auto_confirm_flag,
  prorate_int_inv_across_dists,
  build_prepayment_accounts_flag,
  enable_1099_on_awt_flag,
  stop_prepay_across_bal_flag,
  automatic_offsets_change_flag,
  tolerance_id,
  tax_tolerance,
  tax_tol_amt_range,
  services_tolerance_id,
  prepay_tax_diff_ccid,
  ce_bank_acct_use_id,
  approval_timing,
  receipt_acceptance_days,
  allow_inv_third_party_ovrd,
  allow_pymt_third_party_ovrd,
  WITHHOLDING_DATE_BASIS,
  INVRATE_FOR_PREPAY_TAX,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    last_update_date,
    last_updated_by,
    set_of_books_id,
    base_currency_code,
    recalc_pay_schedule_flag,
    auto_calculate_interest_flag,
    invoice_currency_code,
    payment_currency_code,
    invoice_net_gross_flag,
    bank_account_id,
    check_overflow_lookup_code,
    batch_control_flag,
    terms_id,
    always_take_disc_flag,
    pay_date_basis_lookup_code,
    accts_pay_code_combination_id,
    sales_tax_code_combination_id,
    disc_lost_code_combination_id,
    disc_taken_code_combination_id,
    hold_gain_code_combination_id,
    trans_gain_code_combination_id,
    apply_advances_default,
    add_days_settlement_date,
    cost_of_money,
    days_between_check_cycles,
    federal_identification_num,
    location_id,
    create_employee_vendor_flag,
    employee_terms_id,
    employee_pay_group_lookup_code,
    employee_payment_priority,
    prepay_code_combination_id,
    confirm_date_as_inv_num_flag,
    update_pay_site_flag,
    default_exchange_rate_type,
    gain_code_combination_id,
    loss_code_combination_id,
    make_rate_mandatory_flag,
    multi_currency_flag,
    gl_date_from_receipt_flag,
    disc_is_inv_less_tax_flag,
    match_on_tax_flag,
    accounting_method_option,
    expense_post_option,
    discount_taken_post_option,
    gain_loss_post_option,
    cash_post_option,
    future_pay_post_option,
    date_format_lookup_code,
    replace_check_flag,
    online_print_flag,
    eft_user_number,
    max_outlay,
    vendor_pay_group_lookup_code,
    require_tax_entry_flag,
    approvals_option,
    post_dated_payments_flag,
    secondary_accounting_method,
    secondary_set_of_books_id,
    take_vat_before_discount_flag,
    interest_tolerance_amount,
    interest_code_combination_id,
    terms_date_basis,
    allow_future_pay_flag,
    auto_tax_calc_flag,
    automatic_offsets_flag,
    liability_post_lookup_code,
    interest_accts_pay_ccid,
    liability_post_option,
    discount_distribution_method,
    rate_var_code_combination_id,
    combined_filing_flag,
    income_tax_region,
    income_tax_region_flag,
    hold_unmatched_invoices_flag,
    allow_dist_match_flag,
    allow_final_match_flag,
    allow_flex_override_flag,
    allow_paid_invoice_adjust,
    ussgl_transaction_code,
    ussgl_trx_code_context,
    inv_doc_category_override,
    pay_doc_category_override,
    vendor_auto_int_default,
    summary_journals_default,
    rate_var_gain_ccid,
    rate_var_loss_ccid,
    transfer_desc_flex_flag,
    allow_awt_flag,
    default_awt_group_id,
    allow_awt_override,
    create_awt_dists_type,
    create_awt_invoices_type,
    awt_include_discount_amt,
    awt_include_tax_amt,
    org_id,
    recon_accounting_flag,
    auto_create_freight_flag,
    freight_code_combination_id,
    global_attribute_category,
    global_attribute1,
    global_attribute2,
    global_attribute3,
    global_attribute4,
    global_attribute5,
    global_attribute6,
    global_attribute7,
    global_attribute8,
    global_attribute9,
    global_attribute10,
    global_attribute11,
    global_attribute12,
    global_attribute13,
    global_attribute14,
    global_attribute15,
    global_attribute16,
    global_attribute17,
    global_attribute18,
    global_attribute19,
    global_attribute20,
    allow_supplier_bank_override,
    use_multiple_supplier_banks,
    auto_tax_calc_override,
    amount_includes_tax_flag,
    amount_includes_tax_override,
    vat_code,
    use_bank_charge_flag,
    bank_charge_bearer,
    rounding_error_ccid,
    rounding_error_post_option,
    tax_from_po_flag,
    tax_from_vendor_site_flag,
    tax_from_vendor_flag,
    tax_from_account_flag,
    tax_from_system_flag,
    tax_from_inv_header_flag,
    tax_from_template_flag,
    tax_hier_po_shipment,
    tax_hier_vendor,
    tax_hier_vendor_site,
    tax_hier_account,
    tax_hier_system,
    tax_hier_invoice,
    tax_hier_template,
    enforce_tax_from_account,
    mrc_base_currency_code,
    mrc_secondary_set_of_books_id,
    match_option,
    gain_loss_calc_level,
    when_to_account_pmt,
    when_to_account_gain_loss,
    future_dated_pmt_acct_source,
    future_dated_pmt_liab_relief,
    gl_transfer_allow_override,
    gl_transfer_process_days,
    gl_transfer_mode,
    gl_transfer_submit_journal_imp,
    include_reporting_sob,
    expense_report_id,
    prepayment_terms_id,
    calc_user_xrate,
    sort_by_alternate_field,
    approval_workflow_flag,
    allow_force_approval_flag,
    validate_before_approval_flag,
    xml_payments_auto_confirm_flag,
    prorate_int_inv_across_dists,
    build_prepayment_accounts_flag,
    enable_1099_on_awt_flag,
    stop_prepay_across_bal_flag,
    automatic_offsets_change_flag,
    tolerance_id,
    tax_tolerance,
    tax_tol_amt_range,
    services_tolerance_id,
    prepay_tax_diff_ccid,
    ce_bank_acct_use_id,
    approval_timing,
    receipt_acceptance_days,
    allow_inv_third_party_ovrd,
    allow_pymt_third_party_ovrd,
    WITHHOLDING_DATE_BASIS,
    INVRATE_FOR_PREPAY_TAX,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.ap_system_parameters_all
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_system_parameters_all';