DROP TABLE IF EXISTS silver_bec_ods.WMS_LICENSE_PLATE_NUMBERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.WMS_LICENSE_PLATE_NUMBERS (
  lpn_id DECIMAL(15, 0),
  license_plate_number STRING,
  inventory_item_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  revision STRING,
  lot_number STRING,
  serial_number STRING,
  organization_id DECIMAL(15, 0),
  subinventory_code STRING,
  locator_id DECIMAL(15, 0),
  parent_lpn_id DECIMAL(15, 0),
  gross_weight_uom_code STRING,
  gross_weight DECIMAL(28, 10),
  content_volume_uom_code STRING,
  content_volume DECIMAL(28, 10),
  tare_weight_uom_code STRING,
  tare_weight DECIMAL(28, 10),
  status_id DECIMAL(15, 0),
  lpn_state DECIMAL(28, 10),
  sealed_status DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  cost_group_id DECIMAL(15, 0),
  lpn_context DECIMAL(15, 0),
  lpn_reusability DECIMAL(15, 0),
  outermost_lpn_id DECIMAL(15, 0),
  homogeneous_container DECIMAL(28, 10),
  source_type_id DECIMAL(15, 0),
  source_header_id DECIMAL(15, 0),
  source_line_id DECIMAL(15, 0),
  source_line_detail_id DECIMAL(15, 0),
  source_name STRING,
  container_volume DECIMAL(28, 0),
  container_volume_uom STRING,
  catch_weight_flag STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.WMS_LICENSE_PLATE_NUMBERS (
  lpn_id,
  license_plate_number,
  inventory_item_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  revision,
  lot_number,
  serial_number,
  organization_id,
  subinventory_code,
  locator_id,
  parent_lpn_id,
  gross_weight_uom_code,
  gross_weight,
  content_volume_uom_code,
  content_volume,
  tare_weight_uom_code,
  tare_weight,
  status_id,
  lpn_state,
  sealed_status,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  cost_group_id,
  lpn_context,
  lpn_reusability,
  outermost_lpn_id,
  homogeneous_container,
  source_type_id,
  source_header_id,
  source_line_id,
  source_line_detail_id,
  source_name,
  container_volume,
  container_volume_uom,
  catch_weight_flag,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  lpn_id,
  license_plate_number,
  inventory_item_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  revision,
  lot_number,
  serial_number,
  organization_id,
  subinventory_code,
  locator_id,
  parent_lpn_id,
  gross_weight_uom_code,
  gross_weight,
  content_volume_uom_code,
  content_volume,
  tare_weight_uom_code,
  tare_weight,
  status_id,
  lpn_state,
  sealed_status,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  cost_group_id,
  lpn_context,
  lpn_reusability,
  outermost_lpn_id,
  homogeneous_container,
  source_type_id,
  source_header_id,
  source_line_id,
  source_line_detail_id,
  source_name,
  container_volume,
  container_volume_uom,
  catch_weight_flag,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.WMS_LICENSE_PLATE_NUMBERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wms_license_plate_numbers';