DROP TABLE IF EXISTS silver_bec_ods.FINANCIALS_SYSTEM_PARAMS_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.FINANCIALS_SYSTEM_PARAMS_ALL (
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  payment_method_lookup_code STRING,
  user_defined_vendor_num_code STRING,
  vendor_num_start_num DECIMAL(28, 10),
  ship_to_location_id DECIMAL(15, 0),
  bill_to_location_id DECIMAL(15, 0),
  ship_via_lookup_code STRING,
  fob_lookup_code STRING,
  terms_id DECIMAL(15, 0),
  always_take_disc_flag STRING,
  pay_date_basis_lookup_code STRING,
  invoice_currency_code STRING,
  payment_currency_code STRING,
  accts_pay_code_combination_id DECIMAL(15, 0),
  prepay_code_combination_id DECIMAL(15, 0),
  disc_taken_code_combination_id DECIMAL(15, 0),
  future_period_limit DECIMAL(3, 0),
  reserve_at_completion_flag STRING,
  res_encumb_code_combination_id DECIMAL(15, 0),
  req_encumbrance_flag STRING,
  req_encumbrance_type_id DECIMAL(15, 0),
  purch_encumbrance_flag STRING,
  purch_encumbrance_type_id DECIMAL(15, 0),
  inv_encumbrance_type_id DECIMAL(15, 0),
  manual_vendor_num_type STRING,
  inventory_organization_id DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  freight_terms_lookup_code STRING,
  rfq_only_site_flag STRING,
  receipt_acceptance_days DECIMAL(15, 0),
  business_group_id DECIMAL(15, 0),
  expense_check_address_flag STRING,
  terms_date_basis STRING,
  use_positions_flag STRING,
  rate_var_code_combination_id DECIMAL(15, 0),
  hold_unmatched_invoices_flag STRING,
  exclusive_payment_flag STRING,
  revision_sort_ordering DECIMAL(28, 10),
  vat_registration_num STRING,
  vat_country_code STRING,
  rate_var_gain_ccid DECIMAL(15, 0),
  rate_var_loss_ccid DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  bank_charge_bearer STRING,
  vat_code STRING,
  match_option STRING,
  non_recoverable_tax_flag STRING,
  tax_rounding_rule STRING,
  `precision` DECIMAL(1, 0),
  minimum_accountable_unit DECIMAL(28, 10),
  default_recovery_rate DECIMAL(28, 10),
  cash_basis_enc_nr_tax STRING,
  future_dated_payment_ccid DECIMAL(15, 0),
  expense_clearing_ccid DECIMAL(15, 0),
  misc_charge_ccid DECIMAL(15, 0),
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  retainage_code_combination_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.FINANCIALS_SYSTEM_PARAMS_ALL (
  last_update_date,
  last_updated_by,
  set_of_books_id,
  payment_method_lookup_code,
  user_defined_vendor_num_code,
  vendor_num_start_num,
  ship_to_location_id,
  bill_to_location_id,
  ship_via_lookup_code,
  fob_lookup_code,
  terms_id,
  always_take_disc_flag,
  pay_date_basis_lookup_code,
  invoice_currency_code,
  payment_currency_code,
  accts_pay_code_combination_id,
  prepay_code_combination_id,
  disc_taken_code_combination_id,
  future_period_limit,
  reserve_at_completion_flag,
  res_encumb_code_combination_id,
  req_encumbrance_flag,
  req_encumbrance_type_id,
  purch_encumbrance_flag,
  purch_encumbrance_type_id,
  inv_encumbrance_type_id,
  manual_vendor_num_type,
  inventory_organization_id,
  last_update_login,
  creation_date,
  created_by,
  freight_terms_lookup_code,
  rfq_only_site_flag,
  receipt_acceptance_days,
  business_group_id,
  expense_check_address_flag,
  terms_date_basis,
  use_positions_flag,
  rate_var_code_combination_id,
  hold_unmatched_invoices_flag,
  exclusive_payment_flag,
  revision_sort_ordering,
  vat_registration_num,
  vat_country_code,
  rate_var_gain_ccid,
  rate_var_loss_ccid,
  org_id,
  bank_charge_bearer,
  vat_code,
  match_option,
  non_recoverable_tax_flag,
  tax_rounding_rule,
  `precision`,
  minimum_accountable_unit,
  default_recovery_rate,
  cash_basis_enc_nr_tax,
  future_dated_payment_ccid,
  expense_clearing_ccid,
  misc_charge_ccid,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  retainage_code_combination_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  last_update_date,
  last_updated_by,
  set_of_books_id,
  payment_method_lookup_code,
  user_defined_vendor_num_code,
  vendor_num_start_num,
  ship_to_location_id,
  bill_to_location_id,
  ship_via_lookup_code,
  fob_lookup_code,
  terms_id,
  always_take_disc_flag,
  pay_date_basis_lookup_code,
  invoice_currency_code,
  payment_currency_code,
  accts_pay_code_combination_id,
  prepay_code_combination_id,
  disc_taken_code_combination_id,
  future_period_limit,
  reserve_at_completion_flag,
  res_encumb_code_combination_id,
  req_encumbrance_flag,
  req_encumbrance_type_id,
  purch_encumbrance_flag,
  purch_encumbrance_type_id,
  inv_encumbrance_type_id,
  manual_vendor_num_type,
  inventory_organization_id,
  last_update_login,
  creation_date,
  created_by,
  freight_terms_lookup_code,
  rfq_only_site_flag,
  receipt_acceptance_days,
  business_group_id,
  expense_check_address_flag,
  terms_date_basis,
  use_positions_flag,
  rate_var_code_combination_id,
  hold_unmatched_invoices_flag,
  exclusive_payment_flag,
  revision_sort_ordering,
  vat_registration_num,
  vat_country_code,
  rate_var_gain_ccid,
  rate_var_loss_ccid,
  org_id,
  bank_charge_bearer,
  vat_code,
  match_option,
  non_recoverable_tax_flag,
  tax_rounding_rule,
  `precision`,
  minimum_accountable_unit,
  default_recovery_rate,
  cash_basis_enc_nr_tax,
  future_dated_payment_ccid,
  expense_clearing_ccid,
  misc_charge_ccid,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  retainage_code_combination_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.FINANCIALS_SYSTEM_PARAMS_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'financials_system_params_all';