DROP TABLE IF EXISTS silver_bec_ods.MRP_SR_SOURCE_ORG;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MRP_SR_SOURCE_ORG (
  sr_source_id DECIMAL(15, 0),
  sr_receipt_id DECIMAL(15, 0),
  source_organization_id DECIMAL(15, 0),
  vendor_id DECIMAL(15, 0),
  vendor_site_id DECIMAL(15, 0),
  secondary_inventory STRING,
  source_type DECIMAL(15, 0),
  allocation_percent DECIMAL(28, 10),
  rank DECIMAL(15, 0),
  old_rank DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  ship_method STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MRP_SR_SOURCE_ORG (
  sr_source_id,
  sr_receipt_id,
  source_organization_id,
  vendor_id,
  vendor_site_id,
  secondary_inventory,
  source_type,
  allocation_percent,
  `rank`,
  old_rank,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  ship_method,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  sr_source_id,
  sr_receipt_id,
  source_organization_id,
  vendor_id,
  vendor_site_id,
  secondary_inventory,
  source_type,
  allocation_percent,
  `rank`,
  old_rank,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  ship_method,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MRP_SR_SOURCE_ORG;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mrp_sr_source_org';