DROP TABLE IF EXISTS silver_bec_ods.CS_INCIDENT_SEVERITIES_TL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.CS_INCIDENT_SEVERITIES_TL (
  INCIDENT_SEVERITY_ID DECIMAL(15, 0),
  LANGUAGE STRING,
  SOURCE_LANG STRING,
  LAST_UPDATE_DATE TIMESTAMP,
  LAST_UPDATED_BY DECIMAL(15, 0),
  CREATION_DATE TIMESTAMP,
  CREATED_BY DECIMAL(15, 0),
  LAST_UPDATE_LOGIN DECIMAL(15, 0),
  DESCRIPTION STRING,
  NAME STRING,
  SECURITY_GROUP_ID DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.CS_INCIDENT_SEVERITIES_TL (
  INCIDENT_SEVERITY_ID,
  LANGUAGE,
  SOURCE_LANG,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  DESCRIPTION,
  NAME,
  SECURITY_GROUP_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  INCIDENT_SEVERITY_ID,
  LANGUAGE,
  SOURCE_LANG,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  DESCRIPTION,
  NAME,
  SECURITY_GROUP_ID,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.CS_INCIDENT_SEVERITIES_TL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cs_incident_severities_tl';