DROP TABLE IF EXISTS silver_bec_ods.WSH_DELIVERY_LEGS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.WSH_DELIVERY_LEGS (
  delivery_leg_id DECIMAL(15, 0),
  delivery_id DECIMAL(15, 0),
  sequence_number DECIMAL(15, 0),
  loading_order_flag STRING,
  pick_up_stop_id DECIMAL(15, 0),
  drop_off_stop_id DECIMAL(15, 0),
  gross_weight DECIMAL(28, 10),
  net_weight DECIMAL(28, 10),
  weight_uom_code STRING,
  volume DECIMAL(28, 10),
  volume_uom_code STRING,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  load_tender_status STRING,
  shipper_title STRING,
  shipper_phone STRING,
  pod_flag STRING,
  pod_by STRING,
  pod_date TIMESTAMP,
  expected_pod_date TIMESTAMP,
  booking_office STRING,
  shipper_export_ref STRING,
  carrier_export_ref STRING,
  doc_notify_party STRING,
  aetc_number STRING,
  shipper_signed_by STRING,
  shipper_date TIMESTAMP,
  carrier_signed_by STRING,
  carrier_date TIMESTAMP,
  doc_issue_office STRING,
  doc_issued_by STRING,
  doc_date_issued TIMESTAMP,
  shipper_hm_by STRING,
  shipper_hm_date TIMESTAMP,
  carrier_hm_by STRING,
  carrier_hm_date TIMESTAMP,
  booking_number STRING,
  port_of_loading STRING,
  port_of_discharge STRING,
  service_contract STRING,
  bill_freight_to STRING,
  fte_trip_id DECIMAL(15, 0),
  reprice_required STRING,
  actual_arrival_date TIMESTAMP,
  actual_departure_date TIMESTAMP,
  actual_receipt_date TIMESTAMP,
  tracking_drilldown_flag STRING,
  status_code STRING,
  tracking_remarks STRING,
  carrier_est_departure_date TIMESTAMP,
  carrier_est_arrival_date TIMESTAMP,
  loading_start_datetime TIMESTAMP,
  loading_end_datetime TIMESTAMP,
  unloading_start_datetime TIMESTAMP,
  unloading_end_datetime TIMESTAMP,
  delivered_quantity DECIMAL(28, 10),
  loaded_quantity DECIMAL(28, 10),
  received_quantity DECIMAL(28, 10),
  origin_stop_id DECIMAL(15, 0),
  destination_stop_id DECIMAL(15, 0),
  parent_delivery_leg_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.WSH_DELIVERY_LEGS (
  delivery_leg_id,
  delivery_id,
  sequence_number,
  loading_order_flag,
  pick_up_stop_id,
  drop_off_stop_id,
  gross_weight,
  net_weight,
  weight_uom_code,
  volume,
  volume_uom_code,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  load_tender_status,
  shipper_title,
  shipper_phone,
  pod_flag,
  pod_by,
  pod_date,
  expected_pod_date,
  booking_office,
  shipper_export_ref,
  carrier_export_ref,
  doc_notify_party,
  aetc_number,
  shipper_signed_by,
  shipper_date,
  carrier_signed_by,
  carrier_date,
  doc_issue_office,
  doc_issued_by,
  doc_date_issued,
  shipper_hm_by,
  shipper_hm_date,
  carrier_hm_by,
  carrier_hm_date,
  booking_number,
  port_of_loading,
  port_of_discharge,
  service_contract,
  bill_freight_to,
  fte_trip_id,
  reprice_required,
  actual_arrival_date,
  actual_departure_date,
  actual_receipt_date,
  tracking_drilldown_flag,
  status_code,
  tracking_remarks,
  carrier_est_departure_date,
  carrier_est_arrival_date,
  loading_start_datetime,
  loading_end_datetime,
  unloading_start_datetime,
  unloading_end_datetime,
  delivered_quantity,
  loaded_quantity,
  received_quantity,
  origin_stop_id,
  destination_stop_id,
  parent_delivery_leg_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  delivery_leg_id,
  delivery_id,
  sequence_number,
  loading_order_flag,
  pick_up_stop_id,
  drop_off_stop_id,
  gross_weight,
  net_weight,
  weight_uom_code,
  volume,
  volume_uom_code,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  load_tender_status,
  shipper_title,
  shipper_phone,
  pod_flag,
  pod_by,
  pod_date,
  expected_pod_date,
  booking_office,
  shipper_export_ref,
  carrier_export_ref,
  doc_notify_party,
  aetc_number,
  shipper_signed_by,
  shipper_date,
  carrier_signed_by,
  carrier_date,
  doc_issue_office,
  doc_issued_by,
  doc_date_issued,
  shipper_hm_by,
  shipper_hm_date,
  carrier_hm_by,
  carrier_hm_date,
  booking_number,
  port_of_loading,
  port_of_discharge,
  service_contract,
  bill_freight_to,
  fte_trip_id,
  reprice_required,
  actual_arrival_date,
  actual_departure_date,
  actual_receipt_date,
  tracking_drilldown_flag,
  status_code,
  tracking_remarks,
  carrier_est_departure_date,
  carrier_est_arrival_date,
  loading_start_datetime,
  loading_end_datetime,
  unloading_start_datetime,
  unloading_end_datetime,
  delivered_quantity,
  loaded_quantity,
  received_quantity,
  origin_stop_id,
  destination_stop_id,
  parent_delivery_leg_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.WSH_DELIVERY_LEGS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wsh_delivery_legs';