DROP TABLE IF EXISTS silver_bec_ods.WSH_CARRIERS_V;
CREATE TABLE IF NOT EXISTS silver_bec_ods.WSH_CARRIERS_V (
  carrier_id DECIMAL(15, 0),
  scac_code STRING,
  freight_code STRING,
  manifesting_enabled_flag STRING,
  currency_code STRING,
  carrier_name STRING,
  active STRING,
  party_usg_assignment_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(38, 0),
  max_num_stops_permitted DECIMAL(28, 10),
  max_total_distance DECIMAL(28, 10),
  max_total_time DECIMAL(28, 10),
  allow_intersperse_load STRING,
  max_layover_time DECIMAL(28, 10),
  min_layover_time DECIMAL(28, 10),
  max_total_distance_in_24hr DECIMAL(28, 10),
  max_driving_time_in_24hr DECIMAL(28, 10),
  max_duty_time_in_24hr DECIMAL(28, 10),
  allow_continuous_move STRING,
  max_cm_distance DECIMAL(28, 10),
  max_cm_time DECIMAL(28, 10),
  max_cm_dh_distance DECIMAL(28, 10),
  max_cm_dh_time DECIMAL(28, 10),
  max_size_width DECIMAL(28, 10),
  max_size_height DECIMAL(28, 10),
  max_size_length DECIMAL(28, 10),
  min_size_width DECIMAL(28, 10),
  min_size_height DECIMAL(28, 10),
  min_size_length DECIMAL(28, 10),
  time_uom STRING,
  dimension_uom STRING,
  distance_uom STRING,
  max_out_of_route DECIMAL(28, 10),
  cm_free_dh_mileage DECIMAL(28, 10),
  min_cm_distance DECIMAL(28, 10),
  cm_first_load_discount STRING,
  min_cm_time DECIMAL(28, 10),
  unit_rate_basis STRING,
  weight_uom STRING,
  volume_uom STRING,
  generic_flag STRING,
  freight_bill_auto_approval STRING,
  freight_audit_line_level STRING,
  supplier_id DECIMAL(15, 0),
  supplier_site_id DECIMAL(15, 0),
  cm_rate_variant STRING,
  distance_calculation_method STRING,
  origin_dstn_surcharge_level STRING,
  dim_dimensional_factor DECIMAL(28, 10),
  dim_weight_uom STRING,
  dim_volume_uom STRING,
  dim_dimension_uom STRING,
  dim_min_pack_vol DECIMAL(28, 10),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.WSH_CARRIERS_V (
  carrier_id,
  scac_code,
  freight_code,
  manifesting_enabled_flag,
  currency_code,
  carrier_name,
  active,
  party_usg_assignment_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  max_num_stops_permitted,
  max_total_distance,
  max_total_time,
  allow_intersperse_load,
  max_layover_time,
  min_layover_time,
  max_total_distance_in_24hr,
  max_driving_time_in_24hr,
  max_duty_time_in_24hr,
  allow_continuous_move,
  max_cm_distance,
  max_cm_time,
  max_cm_dh_distance,
  max_cm_dh_time,
  max_size_width,
  max_size_height,
  max_size_length,
  min_size_width,
  min_size_height,
  min_size_length,
  time_uom,
  dimension_uom,
  distance_uom,
  max_out_of_route,
  cm_free_dh_mileage,
  min_cm_distance,
  cm_first_load_discount,
  min_cm_time,
  unit_rate_basis,
  weight_uom,
  volume_uom,
  generic_flag,
  freight_bill_auto_approval,
  freight_audit_line_level,
  supplier_id,
  supplier_site_id,
  cm_rate_variant,
  distance_calculation_method,
  origin_dstn_surcharge_level,
  dim_dimensional_factor,
  dim_weight_uom,
  dim_volume_uom,
  dim_dimension_uom,
  dim_min_pack_vol,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  carrier_id,
  scac_code,
  freight_code,
  manifesting_enabled_flag,
  currency_code,
  carrier_name,
  active,
  party_usg_assignment_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  max_num_stops_permitted,
  max_total_distance,
  max_total_time,
  allow_intersperse_load,
  max_layover_time,
  min_layover_time,
  max_total_distance_in_24hr,
  max_driving_time_in_24hr,
  max_duty_time_in_24hr,
  allow_continuous_move,
  max_cm_distance,
  max_cm_time,
  max_cm_dh_distance,
  max_cm_dh_time,
  max_size_width,
  max_size_height,
  max_size_length,
  min_size_width,
  min_size_height,
  min_size_length,
  time_uom,
  dimension_uom,
  distance_uom,
  max_out_of_route,
  cm_free_dh_mileage,
  min_cm_distance,
  cm_first_load_discount,
  min_cm_time,
  unit_rate_basis,
  weight_uom,
  volume_uom,
  generic_flag,
  freight_bill_auto_approval,
  freight_audit_line_level,
  supplier_id,
  supplier_site_id,
  cm_rate_variant,
  distance_calculation_method,
  origin_dstn_surcharge_level,
  dim_dimensional_factor,
  dim_weight_uom,
  dim_volume_uom,
  dim_dimension_uom,
  dim_min_pack_vol,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.WSH_CARRIERS_V;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wsh_carriers_v';