DROP TABLE IF EXISTS silver_bec_ods.GL_CODE_COMBINATIONS_KFV;
CREATE TABLE IF NOT EXISTS silver_bec_ods.GL_CODE_COMBINATIONS_KFV (
  code_combination_id DECIMAL(15, 0),
  chart_of_accounts_id DECIMAL(15, 0),
  concatenated_segments STRING,
  padded_concatenated_segments STRING,
  gl_account_type STRING,
  gl_control_account STRING,
  reconciliation_flag STRING,
  detail_budgeting_allowed STRING,
  detail_posting_allowed STRING,
  template_id DECIMAL(15, 0),
  ledger_segment STRING,
  attribute1 STRING,
  revaluation_id DECIMAL(15, 0),
  segment_attribute17 STRING,
  segment_attribute18 STRING,
  segment_attribute19 STRING,
  segment_attribute20 STRING,
  segment_attribute21 STRING,
  segment_attribute22 STRING,
  segment_attribute23 STRING,
  segment_attribute24 STRING,
  segment_attribute25 STRING,
  segment_attribute26 STRING,
  segment_attribute27 STRING,
  segment_attribute28 STRING,
  segment_attribute29 STRING,
  segment_attribute30 STRING,
  segment_attribute31 STRING,
  segment_attribute32 STRING,
  segment_attribute33 STRING,
  segment_attribute34 STRING,
  segment_attribute35 STRING,
  segment_attribute36 STRING,
  segment_attribute37 STRING,
  segment_attribute38 STRING,
  segment_attribute39 STRING,
  segment_attribute40 STRING,
  segment_attribute41 STRING,
  segment_attribute42 STRING,
  jgzz_recon_context STRING,
  reference1 STRING,
  reference2 STRING,
  reference4 STRING,
  reference5 STRING,
  preserve_flag STRING,
  refresh_flag STRING,
  igi_balanced_budget_flag STRING,
  company_cost_center_org_id DECIMAL(15, 0),
  alternate_code_combination_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  enabled_flag STRING,
  summary_flag STRING,
  segment1 STRING,
  segment2 STRING,
  segment3 STRING,
  segment4 STRING,
  segment5 STRING,
  segment6 STRING,
  segment7 STRING,
  segment8 STRING,
  segment9 STRING,
  segment10 STRING,
  segment11 STRING,
  segment12 STRING,
  segment13 STRING,
  segment14 STRING,
  segment15 STRING,
  segment16 STRING,
  segment17 STRING,
  segment18 STRING,
  segment19 STRING,
  segment20 STRING,
  segment21 STRING,
  segment22 STRING,
  segment23 STRING,
  segment24 STRING,
  segment25 STRING,
  segment26 STRING,
  segment27 STRING,
  segment28 STRING,
  segment29 STRING,
  segment30 STRING,
  description STRING,
  allocation_create_flag STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  context STRING,
  segment_attribute1 STRING,
  segment_attribute2 STRING,
  segment_attribute3 STRING,
  segment_attribute4 STRING,
  segment_attribute5 STRING,
  segment_attribute6 STRING,
  segment_attribute7 STRING,
  segment_attribute8 STRING,
  segment_attribute9 STRING,
  segment_attribute10 STRING,
  segment_attribute11 STRING,
  segment_attribute12 STRING,
  segment_attribute13 STRING,
  segment_attribute14 STRING,
  segment_attribute15 STRING,
  segment_attribute16 STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.GL_CODE_COMBINATIONS_KFV (
  code_combination_id,
  chart_of_accounts_id,
  concatenated_segments,
  padded_concatenated_segments,
  gl_account_type,
  gl_control_account,
  reconciliation_flag,
  detail_budgeting_allowed,
  detail_posting_allowed,
  template_id,
  ledger_segment,
  attribute1,
  revaluation_id,
  segment_attribute17,
  segment_attribute18,
  segment_attribute19,
  segment_attribute20,
  segment_attribute21,
  segment_attribute22,
  segment_attribute23,
  segment_attribute24,
  segment_attribute25,
  segment_attribute26,
  segment_attribute27,
  segment_attribute28,
  segment_attribute29,
  segment_attribute30,
  segment_attribute31,
  segment_attribute32,
  segment_attribute33,
  segment_attribute34,
  segment_attribute35,
  segment_attribute36,
  segment_attribute37,
  segment_attribute38,
  segment_attribute39,
  segment_attribute40,
  segment_attribute41,
  segment_attribute42,
  jgzz_recon_context,
  reference1,
  reference2,
  reference4,
  reference5,
  preserve_flag,
  refresh_flag,
  igi_balanced_budget_flag,
  company_cost_center_org_id,
  alternate_code_combination_id,
  last_update_date,
  last_updated_by,
  enabled_flag,
  summary_flag,
  segment1,
  segment2,
  segment3,
  segment4,
  segment5,
  segment6,
  segment7,
  segment8,
  segment9,
  segment10,
  segment11,
  segment12,
  segment13,
  segment14,
  segment15,
  segment16,
  segment17,
  segment18,
  segment19,
  segment20,
  segment21,
  segment22,
  segment23,
  segment24,
  segment25,
  segment26,
  segment27,
  segment28,
  segment29,
  segment30,
  description,
  allocation_create_flag,
  start_date_active,
  end_date_active,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  context,
  segment_attribute1,
  segment_attribute2,
  segment_attribute3,
  segment_attribute4,
  segment_attribute5,
  segment_attribute6,
  segment_attribute7,
  segment_attribute8,
  segment_attribute9,
  segment_attribute10,
  segment_attribute11,
  segment_attribute12,
  segment_attribute13,
  segment_attribute14,
  segment_attribute15,
  segment_attribute16,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  code_combination_id,
  chart_of_accounts_id,
  concatenated_segments,
  padded_concatenated_segments,
  gl_account_type,
  gl_control_account,
  reconciliation_flag,
  detail_budgeting_allowed,
  detail_posting_allowed,
  template_id,
  ledger_segment,
  attribute1,
  revaluation_id,
  segment_attribute17,
  segment_attribute18,
  segment_attribute19,
  segment_attribute20,
  segment_attribute21,
  segment_attribute22,
  segment_attribute23,
  segment_attribute24,
  segment_attribute25,
  segment_attribute26,
  segment_attribute27,
  segment_attribute28,
  segment_attribute29,
  segment_attribute30,
  segment_attribute31,
  segment_attribute32,
  segment_attribute33,
  segment_attribute34,
  segment_attribute35,
  segment_attribute36,
  segment_attribute37,
  segment_attribute38,
  segment_attribute39,
  segment_attribute40,
  segment_attribute41,
  segment_attribute42,
  jgzz_recon_context,
  reference1,
  reference2,
  reference4,
  reference5,
  preserve_flag,
  refresh_flag,
  igi_balanced_budget_flag,
  company_cost_center_org_id,
  alternate_code_combination_id,
  last_update_date,
  last_updated_by,
  enabled_flag,
  summary_flag,
  segment1,
  segment2,
  segment3,
  segment4,
  segment5,
  segment6,
  segment7,
  segment8,
  segment9,
  segment10,
  segment11,
  segment12,
  segment13,
  segment14,
  segment15,
  segment16,
  segment17,
  segment18,
  segment19,
  segment20,
  segment21,
  segment22,
  segment23,
  segment24,
  segment25,
  segment26,
  segment27,
  segment28,
  segment29,
  segment30,
  description,
  allocation_create_flag,
  start_date_active,
  end_date_active,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  context,
  segment_attribute1,
  segment_attribute2,
  segment_attribute3,
  segment_attribute4,
  segment_attribute5,
  segment_attribute6,
  segment_attribute7,
  segment_attribute8,
  segment_attribute9,
  segment_attribute10,
  segment_attribute11,
  segment_attribute12,
  segment_attribute13,
  segment_attribute14,
  segment_attribute15,
  segment_attribute16,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.GL_CODE_COMBINATIONS_KFV;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_code_combinations_kfv';