DROP table IF EXISTS silver_bec_ods.MTL_TXN_SOURCE_TYPES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_TXN_SOURCE_TYPES (
  transaction_source_type_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  transaction_source_type_name STRING,
  description STRING,
  disable_date TIMESTAMP,
  user_defined_flag STRING,
  validated_flag STRING,
  descriptive_flex_context_code STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  transaction_source_category STRING,
  transaction_source STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_TXN_SOURCE_TYPES (
  transaction_source_type_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  transaction_source_type_name,
  description,
  disable_date,
  user_defined_flag,
  validated_flag,
  descriptive_flex_context_code,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  transaction_source_category,
  transaction_source,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    transaction_source_type_id,
    last_update_date,
    last_updated_by,
    creation_date,
    created_by,
    transaction_source_type_name,
    description,
    disable_date,
    user_defined_flag,
    validated_flag,
    descriptive_flex_context_code,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    request_id,
    program_application_id,
    program_id,
    program_update_date,
    transaction_source_category,
    transaction_source,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MTL_TXN_SOURCE_TYPES
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_txn_source_types';