DROP table IF EXISTS silver_bec_ods.MTL_SECONDARY_INVENTORIES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_SECONDARY_INVENTORIES (
  secondary_inventory_name STRING,
  organization_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  description STRING,
  disable_date TIMESTAMP,
  inventory_atp_code DECIMAL(15, 0),
  availability_type DECIMAL(15, 0),
  reservable_type DECIMAL(15, 0),
  locator_type DECIMAL(15, 0),
  picking_order DECIMAL(15, 0),
  material_account DECIMAL(15, 0),
  material_overhead_account DECIMAL(15, 0),
  resource_account DECIMAL(15, 0),
  overhead_account DECIMAL(15, 0),
  outside_processing_account DECIMAL(15, 0),
  quantity_tracked DECIMAL(15, 0),
  asset_inventory DECIMAL(15, 0),
  source_type DECIMAL(15, 0),
  source_subinventory STRING,
  source_organization_id DECIMAL(15, 0),
  requisition_approval_type DECIMAL(15, 0),
  expense_account DECIMAL(15, 0),
  encumbrance_account DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  preprocessing_lead_time DECIMAL(15, 0),
  processing_lead_time DECIMAL(15, 0),
  postprocessing_lead_time DECIMAL(15, 0),
  demand_class STRING,
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  subinventory_usage DECIMAL(15, 0),
  notify_list_id DECIMAL(15, 0),
  pick_uom_code STRING,
  depreciable_flag DECIMAL(15, 0),
  location_id DECIMAL(15, 0),
  default_cost_group_id DECIMAL(15, 0),
  status_id DECIMAL(15, 0),
  default_loc_status_id DECIMAL(15, 0),
  lpn_controlled_flag DECIMAL(15, 0),
  pick_methodology DECIMAL(15, 0),
  cartonization_flag DECIMAL(30, 0),
  dropping_order DECIMAL(15, 0),
  subinventory_type DECIMAL(15, 0),
  planning_level DECIMAL(22, 0),
  default_count_type_code DECIMAL(22, 0),
  enable_bulk_pick STRING,
  enable_locator_alias STRING,
  enforce_alias_uniqueness STRING,
  enable_opp_cyc_count STRING,
  opp_cyc_count_days DECIMAL(5, 0),
  opp_cyc_count_header_id DECIMAL(15, 0),
  opp_cyc_count_quantity DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_SECONDARY_INVENTORIES (
  secondary_inventory_name,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  description,
  disable_date,
  inventory_atp_code,
  availability_type,
  reservable_type,
  locator_type,
  picking_order,
  material_account,
  material_overhead_account,
  resource_account,
  overhead_account,
  outside_processing_account,
  quantity_tracked,
  asset_inventory,
  source_type,
  source_subinventory,
  source_organization_id,
  requisition_approval_type,
  expense_account,
  encumbrance_account,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  preprocessing_lead_time,
  processing_lead_time,
  postprocessing_lead_time,
  demand_class,
  project_id,
  task_id,
  subinventory_usage,
  notify_list_id,
  pick_uom_code,
  depreciable_flag,
  location_id,
  default_cost_group_id,
  status_id,
  default_loc_status_id,
  lpn_controlled_flag,
  pick_methodology,
  cartonization_flag,
  dropping_order,
  subinventory_type,
  planning_level,
  default_count_type_code,
  enable_bulk_pick,
  enable_locator_alias,
  enforce_alias_uniqueness,
  enable_opp_cyc_count,
  opp_cyc_count_days,
  opp_cyc_count_header_id,
  opp_cyc_count_quantity,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    secondary_inventory_name,
    organization_id,
    last_update_date,
    last_updated_by,
    creation_date,
    created_by,
    last_update_login,
    description,
    disable_date,
    inventory_atp_code,
    availability_type,
    reservable_type,
    locator_type,
    picking_order,
    material_account,
    material_overhead_account,
    resource_account,
    overhead_account,
    outside_processing_account,
    quantity_tracked,
    asset_inventory,
    source_type,
    source_subinventory,
    source_organization_id,
    requisition_approval_type,
    expense_account,
    encumbrance_account,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    request_id,
    program_application_id,
    program_id,
    program_update_date,
    preprocessing_lead_time,
    processing_lead_time,
    postprocessing_lead_time,
    demand_class,
    project_id,
    task_id,
    subinventory_usage,
    notify_list_id,
    pick_uom_code,
    depreciable_flag,
    location_id,
    default_cost_group_id,
    status_id,
    default_loc_status_id,
    lpn_controlled_flag,
    pick_methodology,
    cartonization_flag,
    dropping_order,
    subinventory_type,
    planning_level,
    default_count_type_code,
    enable_bulk_pick,
    enable_locator_alias,
    enforce_alias_uniqueness,
    enable_opp_cyc_count,
    opp_cyc_count_days,
    opp_cyc_count_header_id,
    opp_cyc_count_quantity,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MTL_SECONDARY_INVENTORIES
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_secondary_inventories';