DROP TABLE IF EXISTS silver_bec_ods.PA_PROJECT_ACCUM_HEADERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.PA_PROJECT_ACCUM_HEADERS (
  project_accum_id DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  accum_period STRING,
  resource_id DECIMAL(15, 0),
  resource_list_assignment_id DECIMAL(15, 0),
  resource_list_id DECIMAL(15, 0),
  resource_list_member_id DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  tasks_restructured_flag STRING,
  sum_exception_code STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.PA_PROJECT_ACCUM_HEADERS (
  PROJECT_ACCUM_ID,
  PROJECT_ID,
  TASK_ID,
  ACCUM_PERIOD,
  RESOURCE_ID,
  RESOURCE_LIST_ASSIGNMENT_ID,
  RESOURCE_LIST_ID,
  RESOURCE_LIST_MEMBER_ID,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  TASKS_RESTRUCTURED_FLAG,
  SUM_EXCEPTION_CODE,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  PROJECT_ACCUM_ID,
  PROJECT_ID,
  TASK_ID,
  ACCUM_PERIOD,
  RESOURCE_ID,
  RESOURCE_LIST_ASSIGNMENT_ID,
  RESOURCE_LIST_ID,
  RESOURCE_LIST_MEMBER_ID,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  TASKS_RESTRUCTURED_FLAG,
  SUM_EXCEPTION_CODE,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.PA_PROJECT_ACCUM_HEADERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'pa_project_accum_headers';