DROP table IF EXISTS silver_bec_ods.FND_FLEX_VALUES_TL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.FND_FLEX_VALUES_TL (
  FLEX_VALUE_ID DECIMAL(15, 0),
  LANGUAGE STRING,
  LAST_UPDATE_DATE TIMESTAMP,
  LAST_UPDATED_BY DECIMAL(15, 0),
  CREATION_DATE TIMESTAMP,
  CREATED_BY DECIMAL(15, 0),
  LAST_UPDATE_LOGIN DECIMAL(15, 0),
  DESCRIPTION STRING,
  SOURCE_LANG STRING,
  FLEX_VALUE_MEANING STRING, /* ,SECURITY_GROUP_ID	NUMERIC(15,0)   */
  ZD_EDITION_NAME STRING,
  ZD_SYNC STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.FND_FLEX_VALUES_TL (
  FLEX_VALUE_ID,
  LANGUAGE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  DESCRIPTION,
  SOURCE_LANG,
  FLEX_VALUE_MEANING,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    FLEX_VALUE_ID,
    LANGUAGE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    DESCRIPTION,
    SOURCE_LANG,
    FLEX_VALUE_MEANING,
    ZD_EDITION_NAME,
    ZD_SYNC,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.FND_FLEX_VALUES_TL
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fnd_flex_values_tl';