DROP TABLE IF EXISTS silver_bec_ods.ap_invoice_lines_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_invoice_lines_all (
  invoice_id DECIMAL(15, 0),
  line_number DECIMAL(28, 10),
  line_type_lookup_code STRING,
  requester_id DECIMAL(15, 0),
  description STRING,
  line_source STRING,
  org_id DECIMAL(15, 0),
  line_group_number DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  item_description STRING,
  serial_number STRING,
  manufacturer STRING,
  model_number STRING,
  warranty_number STRING,
  generate_dists STRING,
  match_type STRING,
  distribution_set_id DECIMAL(15, 0),
  account_segment STRING,
  balancing_segment STRING,
  cost_center_segment STRING,
  overlay_dist_code_concat STRING,
  default_dist_ccid INT,
  prorate_across_all_items STRING,
  accounting_date TIMESTAMP,
  period_name STRING,
  deferred_acctg_flag STRING,
  def_acctg_start_date TIMESTAMP,
  def_acctg_end_date TIMESTAMP,
  def_acctg_number_of_periods DECIMAL(15, 0),
  def_acctg_period_type STRING,
  set_of_books_id DECIMAL(15, 0),
  amount DECIMAL(28, 10),
  base_amount DECIMAL(28, 10),
  rounding_amt DECIMAL(28, 10),
  quantity_invoiced DECIMAL(28, 10),
  unit_meas_lookup_code STRING,
  unit_price DECIMAL(28, 10),
  wfapproval_status STRING,
  ussgl_transaction_code STRING,
  discarded_flag STRING,
  original_amount DECIMAL(28, 10),
  original_base_amount DECIMAL(28, 10),
  original_rounding_amt DECIMAL(28, 10),
  cancelled_flag STRING,
  income_tax_region STRING,
  type_1099 STRING,
  stat_amount DECIMAL(28, 10),
  prepay_invoice_id DECIMAL(15, 0),
  prepay_line_number DECIMAL(15, 0),
  invoice_includes_prepay_flag STRING,
  corrected_inv_id DECIMAL(15, 0),
  corrected_line_number DECIMAL(15, 0),
  po_header_id DECIMAL(15, 0),
  po_line_id DECIMAL(15, 0),
  po_release_id DECIMAL(15, 0),
  po_line_location_id DECIMAL(15, 0),
  po_distribution_id DECIMAL(15, 0),
  rcv_transaction_id DECIMAL(15, 0),
  final_match_flag STRING,
  assets_tracking_flag STRING,
  asset_book_type_code STRING,
  asset_category_id DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  expenditure_type STRING,
  expenditure_item_date TIMESTAMP,
  expenditure_organization_id DECIMAL(15, 0),
  pa_quantity DECIMAL(28, 10),
  pa_cc_ar_invoice_id DECIMAL(15, 0),
  pa_cc_ar_invoice_line_num DECIMAL(15, 0),
  pa_cc_processed_code STRING,
  award_id DECIMAL(15, 0),
  awt_group_id DECIMAL(15, 0),
  reference_1 STRING,
  reference_2 STRING,
  receipt_verified_flag STRING,
  receipt_required_flag STRING,
  receipt_missing_flag STRING,
  justification STRING,
  expense_group STRING,
  start_expense_date TIMESTAMP,
  end_expense_date TIMESTAMP,
  receipt_currency_code STRING,
  receipt_conversion_rate DECIMAL(28, 10),
  receipt_currency_amount DECIMAL(28, 10),
  daily_amount DECIMAL(28, 10),
  web_parameter_id DECIMAL(15, 0),
  adjustment_reason STRING,
  merchant_document_number STRING,
  merchant_name STRING,
  line_owner_role STRING,
  disputable_flag STRING,
  rcv_shipment_line_id DECIMAL(15, 0),
  pay_awt_group_id DECIMAL(15, 0),
  ail_invoice_id DECIMAL(15, 0),
  ail_distribution_line_number DECIMAL(15, 0),
  ail_invoice_id2 DECIMAL(15, 0),
  ail_distribution_line_number2 DECIMAL(15, 0),
  ail_invoice_id3 DECIMAL(15, 0),
  ail_distribution_line_number3 DECIMAL(15, 0),
  ail_invoice_id4 DECIMAL(15, 0),
  merchant_reference STRING,
  merchant_tax_reg_number STRING,
  merchant_taxpayer_id STRING,
  country_of_supply STRING,
  credit_card_trx_id DECIMAL(15, 0),
  company_prepaid_invoice_id DECIMAL(15, 0),
  cc_reversal_flag STRING,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  line_selected_for_appl_flag STRING,
  prepay_appl_request_id DECIMAL(15, 0),
  application_id DECIMAL(15, 0),
  product_table STRING,
  reference_key1 STRING,
  reference_key2 STRING,
  reference_key3 STRING,
  reference_key4 STRING,
  reference_key5 STRING,
  purchasing_category_id DECIMAL(15, 0),
  cost_factor_id DECIMAL(15, 0),
  control_amount DECIMAL(28, 10),
  assessable_value DECIMAL(28, 10),
  total_rec_tax_amount DECIMAL(28, 10),
  total_nrec_tax_amount DECIMAL(28, 10),
  total_rec_tax_amt_funcl_curr DECIMAL(28, 10),
  total_nrec_tax_amt_funcl_curr DECIMAL(28, 10),
  included_tax_amount DECIMAL(28, 10),
  primary_bigintended_use STRING,
  tax_already_calculated_flag STRING,
  ship_to_location_id DECIMAL(15, 0),
  product_type STRING,
  product_category STRING,
  product_fisc_classification STRING,
  user_defined_fisc_class STRING,
  trx_business_category STRING,
  summary_tax_line_id DECIMAL(15, 0),
  tax_regime_code STRING,
  tax STRING,
  tax_jurisdiction_code STRING,
  tax_status_code STRING,
  tax_rate_id DECIMAL(15, 0),
  tax_rate_code STRING,
  tax_rate DECIMAL(28, 10),
  tax_code_id DECIMAL(15, 0),
  historical_flag STRING,
  tax_classification_code STRING,
  source_application_id DECIMAL(15, 0),
  source_event_class_code STRING,
  source_entity_code STRING,
  source_trx_id DECIMAL(15, 0),
  source_line_id DECIMAL(15, 0),
  source_trx_level_type STRING,
  retained_amount DECIMAL(28, 10),
  retained_amount_remaining DECIMAL(28, 10),
  retained_invoice_id DECIMAL(15, 0),
  retained_line_number DECIMAL(15, 0),
  line_selected_for_release_flag STRING,
  `MERCHANT_NAME#1` STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_invoice_lines_all (
  invoice_id,
  line_number,
  line_type_lookup_code,
  requester_id,
  description,
  line_source,
  org_id,
  line_group_number,
  inventory_item_id,
  item_description,
  serial_number,
  manufacturer,
  model_number,
  warranty_number,
  generate_dists,
  match_type,
  distribution_set_id,
  account_segment,
  balancing_segment,
  cost_center_segment,
  overlay_dist_code_concat,
  default_dist_ccid,
  prorate_across_all_items,
  accounting_date,
  period_name,
  deferred_acctg_flag,
  def_acctg_start_date,
  def_acctg_end_date,
  def_acctg_number_of_periods,
  def_acctg_period_type,
  set_of_books_id,
  amount,
  base_amount,
  rounding_amt,
  quantity_invoiced,
  unit_meas_lookup_code,
  unit_price,
  wfapproval_status,
  ussgl_transaction_code,
  discarded_flag,
  original_amount,
  original_base_amount,
  original_rounding_amt,
  cancelled_flag,
  income_tax_region,
  type_1099,
  stat_amount,
  prepay_invoice_id,
  prepay_line_number,
  invoice_includes_prepay_flag,
  corrected_inv_id,
  corrected_line_number,
  po_header_id,
  po_line_id,
  po_release_id,
  po_line_location_id,
  po_distribution_id,
  rcv_transaction_id,
  final_match_flag,
  assets_tracking_flag,
  asset_book_type_code,
  asset_category_id,
  project_id,
  task_id,
  expenditure_type,
  expenditure_item_date,
  expenditure_organization_id,
  pa_quantity,
  pa_cc_ar_invoice_id,
  pa_cc_ar_invoice_line_num,
  pa_cc_processed_code,
  award_id,
  awt_group_id,
  reference_1,
  reference_2,
  receipt_verified_flag,
  receipt_required_flag,
  receipt_missing_flag,
  justification,
  expense_group,
  start_expense_date,
  end_expense_date,
  receipt_currency_code,
  receipt_conversion_rate,
  receipt_currency_amount,
  daily_amount,
  web_parameter_id,
  adjustment_reason,
  merchant_document_number,
  merchant_name,
  line_owner_role,
  disputable_flag,
  rcv_shipment_line_id,
  pay_awt_group_id,
  ail_invoice_id,
  ail_distribution_line_number,
  ail_invoice_id2,
  ail_distribution_line_number2,
  ail_invoice_id3,
  ail_distribution_line_number3,
  ail_invoice_id4,
  merchant_reference,
  merchant_tax_reg_number,
  merchant_taxpayer_id,
  country_of_supply,
  credit_card_trx_id,
  company_prepaid_invoice_id,
  cc_reversal_flag,
  creation_date,
  created_by,
  last_updated_by,
  last_update_date,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  line_selected_for_appl_flag,
  prepay_appl_request_id,
  application_id,
  product_table,
  reference_key1,
  reference_key2,
  reference_key3,
  reference_key4,
  reference_key5,
  purchasing_category_id,
  cost_factor_id,
  control_amount,
  assessable_value,
  total_rec_tax_amount,
  total_nrec_tax_amount,
  total_rec_tax_amt_funcl_curr,
  total_nrec_tax_amt_funcl_curr,
  included_tax_amount,
  tax_already_calculated_flag,
  ship_to_location_id,
  product_type,
  product_category,
  product_fisc_classification,
  user_defined_fisc_class,
  trx_business_category,
  summary_tax_line_id,
  tax_regime_code,
  tax,
  tax_jurisdiction_code,
  tax_status_code,
  tax_rate_id,
  tax_rate_code,
  tax_rate,
  tax_code_id,
  historical_flag,
  tax_classification_code,
  source_application_id,
  source_event_class_code,
  source_entity_code,
  source_trx_id,
  source_line_id,
  source_trx_level_type,
  retained_amount,
  retained_amount_remaining,
  retained_invoice_id,
  retained_line_number,
  line_selected_for_release_flag,
  `MERCHANT_NAME#1`,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    invoice_id,
    FLOOR(line_number) AS line_number,
    line_type_lookup_code,
    requester_id,
    description,
    line_source,
    org_id,
    line_group_number,
    inventory_item_id,
    item_description,
    serial_number,
    manufacturer,
    model_number,
    warranty_number,
    generate_dists,
    match_type,
    distribution_set_id,
    account_segment,
    balancing_segment,
    cost_center_segment,
    overlay_dist_code_concat,
    default_dist_ccid,
    prorate_across_all_items,
    accounting_date,
    period_name,
    deferred_acctg_flag,
    def_acctg_start_date,
    def_acctg_end_date,
    def_acctg_number_of_periods,
    def_acctg_period_type,
    set_of_books_id,
    amount,
    base_amount,
    rounding_amt,
    quantity_invoiced,
    unit_meas_lookup_code,
    unit_price,
    wfapproval_status,
    ussgl_transaction_code,
    discarded_flag,
    original_amount,
    original_base_amount,
    original_rounding_amt,
    cancelled_flag,
    income_tax_region,
    type_1099,
    stat_amount,
    prepay_invoice_id,
    prepay_line_number,
    invoice_includes_prepay_flag,
    corrected_inv_id,
    corrected_line_number,
    po_header_id,
    po_line_id,
    po_release_id,
    po_line_location_id,
    po_distribution_id,
    rcv_transaction_id,
    final_match_flag,
    assets_tracking_flag,
    asset_book_type_code,
    asset_category_id,
    project_id,
    task_id,
    expenditure_type,
    expenditure_item_date,
    expenditure_organization_id,
    pa_quantity,
    pa_cc_ar_invoice_id,
    pa_cc_ar_invoice_line_num,
    pa_cc_processed_code,
    award_id,
    awt_group_id,
    reference_1,
    reference_2,
    receipt_verified_flag,
    receipt_required_flag,
    receipt_missing_flag,
    justification,
    expense_group,
    start_expense_date,
    end_expense_date,
    receipt_currency_code,
    receipt_conversion_rate,
    receipt_currency_amount,
    daily_amount,
    web_parameter_id,
    adjustment_reason,
    merchant_document_number,
    merchant_name,
    line_owner_role,
    disputable_flag,
    rcv_shipment_line_id,
    pay_awt_group_id,
    ail_invoice_id,
    ail_distribution_line_number,
    ail_invoice_id2,
    ail_distribution_line_number2,
    ail_invoice_id3,
    ail_distribution_line_number3,
    ail_invoice_id4,
    merchant_reference,
    merchant_tax_reg_number,
    merchant_taxpayer_id,
    country_of_supply,
    credit_card_trx_id,
    company_prepaid_invoice_id,
    cc_reversal_flag,
    creation_date,
    created_by,
    last_updated_by,
    last_update_date,
    last_update_login,
    program_application_id,
    program_id,
    program_update_date,
    request_id,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    global_attribute_category,
    global_attribute1,
    global_attribute2,
    global_attribute3,
    global_attribute4,
    global_attribute5,
    global_attribute6,
    global_attribute7,
    global_attribute8,
    global_attribute9,
    global_attribute10,
    global_attribute11,
    global_attribute12,
    global_attribute13,
    global_attribute14,
    global_attribute15,
    global_attribute16,
    global_attribute17,
    global_attribute18,
    global_attribute19,
    global_attribute20,
    line_selected_for_appl_flag,
    prepay_appl_request_id,
    application_id,
    product_table,
    reference_key1,
    reference_key2,
    reference_key3,
    reference_key4,
    reference_key5,
    purchasing_category_id,
    cost_factor_id,
    control_amount,
    assessable_value,
    total_rec_tax_amount,
    total_nrec_tax_amount,
    total_rec_tax_amt_funcl_curr,
    total_nrec_tax_amt_funcl_curr,
    included_tax_amount,
    tax_already_calculated_flag,
    ship_to_location_id,
    product_type,
    product_category,
    product_fisc_classification,
    user_defined_fisc_class,
    trx_business_category,
    summary_tax_line_id,
    tax_regime_code,
    tax,
    tax_jurisdiction_code,
    tax_status_code,
    tax_rate_id,
    tax_rate_code,
    tax_rate,
    tax_code_id,
    historical_flag,
    tax_classification_code,
    source_application_id,
    source_event_class_code,
    source_entity_code,
    source_trx_id,
    source_line_id,
    source_trx_level_type,
    retained_amount,
    retained_amount_remaining,
    retained_invoice_id,
    retained_line_number,
    line_selected_for_release_flag,
    `MERCHANT_NAME#1`,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.ap_invoice_lines_all
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_invoice_lines_all';