DROP TABLE IF EXISTS silver_bec_ods.MTL_CATEGORIES_VL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_CATEGORIES_VL (
  category_id DECIMAL(15, 0),
  structure_id DECIMAL(15, 0),
  disable_date TIMESTAMP,
  web_status STRING,
  supplier_enabled_flag STRING,
  segment1 STRING,
  segment2 STRING,
  segment3 STRING,
  segment4 STRING,
  segment5 STRING,
  segment6 STRING,
  segment7 STRING,
  segment8 STRING,
  segment9 STRING,
  segment10 STRING,
  segment11 STRING,
  segment12 STRING,
  segment13 STRING,
  segment14 STRING,
  segment15 STRING,
  segment16 STRING,
  segment17 STRING,
  segment18 STRING,
  segment19 STRING,
  segment20 STRING,
  summary_flag STRING,
  enabled_flag STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  description STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_CATEGORIES_VL (
  category_id,
  structure_id,
  disable_date,
  web_status,
  supplier_enabled_flag,
  segment1,
  segment2,
  segment3,
  segment4,
  segment5,
  segment6,
  segment7,
  segment8,
  segment9,
  segment10,
  segment11,
  segment12,
  segment13,
  segment14,
  segment15,
  segment16,
  segment17,
  segment18,
  segment19,
  segment20,
  summary_flag,
  enabled_flag,
  start_date_active,
  end_date_active,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  description,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  category_id,
  structure_id,
  disable_date,
  web_status,
  supplier_enabled_flag,
  segment1,
  segment2,
  segment3,
  segment4,
  segment5,
  segment6,
  segment7,
  segment8,
  segment9,
  segment10,
  segment11,
  segment12,
  segment13,
  segment14,
  segment15,
  segment16,
  segment17,
  segment18,
  segment19,
  segment20,
  summary_flag,
  enabled_flag,
  start_date_active,
  end_date_active,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  description,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_CATEGORIES_VL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_categories_vl';