DROP TABLE IF EXISTS silver_bec_ods.GL_PERIOD_STATUSES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.GL_PERIOD_STATUSES (
  application_id DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  period_name STRING,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  closing_status STRING,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  year_start_date TIMESTAMP,
  quarter_num DECIMAL(15, 0),
  quarter_start_date TIMESTAMP,
  period_type STRING,
  period_year DECIMAL(15, 0),
  effective_period_num DECIMAL(15, 0),
  period_num DECIMAL(15, 0),
  adjustment_period_flag STRING,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  elimination_confirmed_flag STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  context STRING,
  chronological_seq_status_code STRING,
  ledger_id DECIMAL(15, 0),
  migration_status_code STRING,
  track_bc_ytd_flag STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.gl_period_statuses (
  application_id,
  set_of_books_id,
  period_name,
  last_update_date,
  last_updated_by,
  closing_status,
  start_date,
  end_date,
  year_start_date,
  quarter_num,
  quarter_start_date,
  period_type,
  period_year,
  effective_period_num,
  period_num,
  adjustment_period_flag,
  creation_date,
  created_by,
  last_update_login,
  elimination_confirmed_flag,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  context,
  chronological_seq_status_code,
  ledger_id,
  migration_status_code,
  track_bc_ytd_flag,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  application_id,
  set_of_books_id,
  period_name,
  last_update_date,
  last_updated_by,
  closing_status,
  start_date,
  end_date,
  year_start_date,
  quarter_num,
  quarter_start_date,
  period_type,
  period_year,
  effective_period_num,
  period_num,
  adjustment_period_flag,
  creation_date,
  created_by,
  last_update_login,
  elimination_confirmed_flag,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  context,
  chronological_seq_status_code,
  ledger_id,
  migration_status_code,
  track_bc_ytd_flag,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.gl_period_statuses;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_period_statuses';