DROP TABLE IF EXISTS silver_bec_ods.WSH_NEW_DELIVERIES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.WSH_NEW_DELIVERIES (
  delivery_id DECIMAL(15, 0),
  name STRING,
  planned_flag STRING,
  status_code STRING,
  initial_pickup_date TIMESTAMP,
  initial_pickup_location_id DECIMAL(15, 0),
  ultimate_dropoff_location_id DECIMAL(15, 0),
  ultimate_dropoff_date TIMESTAMP,
  customer_id DECIMAL(15, 0),
  intmed_ship_to_location_id DECIMAL(15, 0),
  pooled_ship_to_location_id DECIMAL(15, 0),
  freight_terms_code STRING,
  fob_code STRING,
  fob_location_id DECIMAL(15, 0),
  waybill STRING,
  acceptance_flag STRING,
  accepted_by STRING,
  accepted_date TIMESTAMP,
  acknowledged_by STRING,
  confirmed_by STRING,
  asn_date_sent TIMESTAMP,
  asn_status_code STRING,
  asn_seq_number DECIMAL(28, 10),
  reason_of_transport STRING,
  description STRING,
  gross_weight DECIMAL(28, 10),
  net_weight DECIMAL(28, 10),
  weight_uom_code STRING,
  volume DECIMAL(28, 10),
  volume_uom_code STRING,
  additional_shipment_info STRING,
  port_of_discharge STRING,
  booking_number STRING,
  cod_amount DECIMAL(28, 10),
  cod_currency_code STRING,
  service_contract STRING,
  cod_remit_to STRING,
  cod_charge_paid_by STRING,
  problem_contact_reference STRING,
  bill_freight_to STRING,
  carried_by STRING,
  port_of_loading STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  tp_attribute_category STRING,
  tp_attribute1 STRING,
  tp_attribute2 STRING,
  tp_attribute3 STRING,
  tp_attribute4 STRING,
  tp_attribute5 STRING,
  tp_attribute6 STRING,
  tp_attribute7 STRING,
  tp_attribute8 STRING,
  tp_attribute9 STRING,
  tp_attribute10 STRING,
  tp_attribute11 STRING,
  tp_attribute12 STRING,
  tp_attribute13 STRING,
  tp_attribute14 STRING,
  tp_attribute15 STRING,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  confirm_date TIMESTAMP,
  ship_method_code STRING,
  dock_code STRING,
  delivery_type STRING,
  carrier_id DECIMAL(15, 0),
  currency_code STRING,
  organization_id DECIMAL(15, 0),
  loading_sequence DECIMAL(28, 10),
  loading_order_flag STRING,
  number_of_lpn DECIMAL(28, 10),
  batch_id DECIMAL(15, 0),
  source_header_id DECIMAL(15, 0),
  hash_value DECIMAL(28, 10),
  ftz_number STRING,
  routed_export_txn STRING,
  entry_number STRING,
  routing_instructions STRING,
  in_bond_code STRING,
  shipping_marks STRING,
  service_level STRING,
  mode_of_transport STRING,
  assigned_to_fte_trips STRING,
  auto_sc_exclude_flag STRING,
  auto_ap_exclude_flag STRING,
  ap_batch_id DECIMAL(15, 0),
  tp_delivery_number DECIMAL(15, 0),
  tp_plan_name STRING,
  vendor_id DECIMAL(15, 0),
  earliest_pickup_date TIMESTAMP,
  latest_pickup_date TIMESTAMP,
  earliest_dropoff_date TIMESTAMP,
  latest_dropoff_date TIMESTAMP,
  ignore_for_planning STRING,
  party_id DECIMAL(15, 0),
  routing_response_id DECIMAL(15, 0),
  rcv_shipment_header_id DECIMAL(15, 0),
  asn_shipment_header_id DECIMAL(15, 0),
  shipment_direction STRING,
  shipping_control STRING,
  wv_frozen_flag STRING,
  hash_string STRING,
  itinerary_complete STRING,
  delivered_date TIMESTAMP,
  delivery_wf_process STRING,
  del_wf_intransit_attr STRING,
  del_wf_interface_attr STRING,
  del_wf_close_attr STRING,
  delivery_scpod_wf_process STRING,
  tms_version_number DECIMAL(28, 10),
  tms_interface_flag STRING,
  pending_advice_flag STRING,
  client_id DECIMAL(15, 0),
  consignee_flag STRING,
  service_org_id DECIMAL(15, 0),
  tms_sub_batch_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.WSH_NEW_DELIVERIES (
  delivery_id,
  `name`,
  planned_flag,
  status_code,
  initial_pickup_date,
  initial_pickup_location_id,
  ultimate_dropoff_location_id,
  ultimate_dropoff_date,
  customer_id,
  intmed_ship_to_location_id,
  pooled_ship_to_location_id,
  freight_terms_code,
  fob_code,
  fob_location_id,
  waybill,
  acceptance_flag,
  accepted_by,
  accepted_date,
  acknowledged_by,
  confirmed_by,
  asn_date_sent,
  asn_status_code,
  asn_seq_number,
  reason_of_transport,
  description,
  gross_weight,
  net_weight,
  weight_uom_code,
  volume,
  volume_uom_code,
  additional_shipment_info,
  port_of_discharge,
  booking_number,
  cod_amount,
  cod_currency_code,
  service_contract,
  cod_remit_to,
  cod_charge_paid_by,
  problem_contact_reference,
  bill_freight_to,
  carried_by,
  port_of_loading,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  tp_attribute_category,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  confirm_date,
  ship_method_code,
  dock_code,
  delivery_type,
  carrier_id,
  currency_code,
  organization_id,
  loading_sequence,
  loading_order_flag,
  number_of_lpn,
  batch_id,
  source_header_id,
  hash_value,
  ftz_number,
  routed_export_txn,
  entry_number,
  routing_instructions,
  in_bond_code,
  shipping_marks,
  service_level,
  mode_of_transport,
  assigned_to_fte_trips,
  auto_sc_exclude_flag,
  auto_ap_exclude_flag,
  ap_batch_id,
  tp_delivery_number,
  tp_plan_name,
  vendor_id,
  earliest_pickup_date,
  latest_pickup_date,
  earliest_dropoff_date,
  latest_dropoff_date,
  ignore_for_planning,
  party_id,
  routing_response_id,
  rcv_shipment_header_id,
  asn_shipment_header_id,
  shipment_direction,
  shipping_control,
  wv_frozen_flag,
  hash_string,
  itinerary_complete,
  delivered_date,
  delivery_wf_process,
  del_wf_intransit_attr,
  del_wf_interface_attr,
  del_wf_close_attr,
  delivery_scpod_wf_process,
  tms_version_number,
  tms_interface_flag,
  pending_advice_flag,
  client_id,
  consignee_flag,
  service_org_id,
  tms_sub_batch_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  delivery_id,
  `name`,
  planned_flag,
  status_code,
  initial_pickup_date,
  initial_pickup_location_id,
  ultimate_dropoff_location_id,
  ultimate_dropoff_date,
  customer_id,
  intmed_ship_to_location_id,
  pooled_ship_to_location_id,
  freight_terms_code,
  fob_code,
  fob_location_id,
  waybill,
  acceptance_flag,
  accepted_by,
  accepted_date,
  acknowledged_by,
  confirmed_by,
  asn_date_sent,
  asn_status_code,
  asn_seq_number,
  reason_of_transport,
  description,
  gross_weight,
  net_weight,
  weight_uom_code,
  volume,
  volume_uom_code,
  additional_shipment_info,
  port_of_discharge,
  booking_number,
  cod_amount,
  cod_currency_code,
  service_contract,
  cod_remit_to,
  cod_charge_paid_by,
  problem_contact_reference,
  bill_freight_to,
  carried_by,
  port_of_loading,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  tp_attribute_category,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  confirm_date,
  ship_method_code,
  dock_code,
  delivery_type,
  carrier_id,
  currency_code,
  organization_id,
  loading_sequence,
  loading_order_flag,
  number_of_lpn,
  batch_id,
  source_header_id,
  hash_value,
  ftz_number,
  routed_export_txn,
  entry_number,
  routing_instructions,
  in_bond_code,
  shipping_marks,
  service_level,
  mode_of_transport,
  assigned_to_fte_trips,
  auto_sc_exclude_flag,
  auto_ap_exclude_flag,
  ap_batch_id,
  tp_delivery_number,
  tp_plan_name,
  vendor_id,
  earliest_pickup_date,
  latest_pickup_date,
  earliest_dropoff_date,
  latest_dropoff_date,
  ignore_for_planning,
  party_id,
  routing_response_id,
  rcv_shipment_header_id,
  asn_shipment_header_id,
  shipment_direction,
  shipping_control,
  wv_frozen_flag,
  hash_string,
  itinerary_complete,
  delivered_date,
  delivery_wf_process,
  del_wf_intransit_attr,
  del_wf_interface_attr,
  del_wf_close_attr,
  delivery_scpod_wf_process,
  tms_version_number,
  tms_interface_flag,
  pending_advice_flag,
  client_id,
  consignee_flag,
  service_org_id,
  tms_sub_batch_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.WSH_NEW_DELIVERIES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wsh_new_deliveries';