DROP TABLE IF EXISTS silver_bec_ods.CST_COST_GROUP_ACCOUNTS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.CST_COST_GROUP_ACCOUNTS (
  cost_group_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  material_account DECIMAL(15, 0),
  material_overhead_account DECIMAL(15, 0),
  resource_account DECIMAL(15, 0),
  overhead_account DECIMAL(15, 0),
  outside_processing_account DECIMAL(15, 0),
  average_cost_var_account DECIMAL(15, 0),
  encumbrance_account DECIMAL(15, 0),
  payback_mat_var_account DECIMAL(15, 0),
  payback_res_var_account DECIMAL(15, 0),
  payback_osp_var_account DECIMAL(15, 0),
  payback_moh_var_account DECIMAL(15, 0),
  payback_ovh_var_account DECIMAL(15, 0),
  expense_account DECIMAL(15, 0),
  purchase_price_var_account DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.CST_COST_GROUP_ACCOUNTS (
  cost_group_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  material_account,
  material_overhead_account,
  resource_account,
  overhead_account,
  outside_processing_account,
  average_cost_var_account,
  encumbrance_account,
  payback_mat_var_account,
  payback_res_var_account,
  payback_osp_var_account,
  payback_moh_var_account,
  payback_ovh_var_account,
  expense_account,
  purchase_price_var_account,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cost_group_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  material_account,
  material_overhead_account,
  resource_account,
  overhead_account,
  outside_processing_account,
  average_cost_var_account,
  encumbrance_account,
  payback_mat_var_account,
  payback_res_var_account,
  payback_osp_var_account,
  payback_moh_var_account,
  payback_ovh_var_account,
  expense_account,
  purchase_price_var_account,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.CST_COST_GROUP_ACCOUNTS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cst_cost_group_accounts';