DROP TABLE IF EXISTS silver_bec_ods.MTL_INTERORG_SHIP_METHODS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_INTERORG_SHIP_METHODS (
  FROM_ORGANIZATION_ID DECIMAL(15, 0),
  TO_ORGANIZATION_ID DECIMAL(15, 0),
  SHIP_METHOD STRING,
  LAST_UPDATE_DATE TIMESTAMP,
  LAST_UPDATED_BY DECIMAL(15, 0) NOT NULL,
  CREATION_DATE TIMESTAMP,
  CREATED_BY DECIMAL(15, 0) NOT NULL,
  LAST_UPDATE_LOGIN DECIMAL(15, 0),
  TIME_UOM_CODE STRING,
  INTRANSIT_TIME DECIMAL(15, 0) NOT NULL,
  DEFAULT_FLAG DECIMAL(15, 0),
  FROM_LOCATION_ID DECIMAL(15, 0),
  TO_LOCATION_ID DECIMAL(15, 0),
  LOAD_WEIGHT_UOM_CODE STRING,
  VOLUME_UOM_CODE STRING,
  CURRENCY_CODE STRING,
  DAILY_LOAD_WEIGHT_CAPACITY DECIMAL(28, 10),
  COST_PER_UNIT_LOAD_WEIGHT DECIMAL(28, 10),
  DAILY_VOLUME_CAPACITY DECIMAL(28, 10),
  COST_PER_UNIT_LOAD_VOLUME DECIMAL(28, 10),
  ATTRIBUTE_CATEGORY STRING,
  ATTRIBUTE1 STRING,
  ATTRIBUTE2 STRING,
  ATTRIBUTE3 STRING,
  ATTRIBUTE4 STRING,
  ATTRIBUTE5 STRING,
  ATTRIBUTE6 STRING,
  ATTRIBUTE7 STRING,
  ATTRIBUTE8 STRING,
  ATTRIBUTE9 STRING,
  ATTRIBUTE10 STRING,
  ATTRIBUTE11 STRING,
  ATTRIBUTE12 STRING,
  ATTRIBUTE13 STRING,
  ATTRIBUTE14 STRING,
  ATTRIBUTE15 STRING,
  TO_REGION_ID DECIMAL(15, 0),
  DESTINATION_TYPE STRING,
  ORIGIN_TYPE STRING,
  FROM_REGION_ID DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_INTERORG_SHIP_METHODS (
  from_organization_id,
  to_organization_id,
  ship_method,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  time_uom_code,
  intransit_time,
  default_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  from_location_id,
  to_location_id,
  load_weight_uom_code,
  volume_uom_code,
  currency_code,
  daily_load_weight_capacity,
  cost_per_unit_load_weight,
  daily_volume_capacity,
  cost_per_unit_load_volume,
  to_region_id,
  destination_type,
  origin_type,
  from_region_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  from_organization_id,
  to_organization_id,
  ship_method,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  time_uom_code,
  intransit_time,
  default_flag,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  from_location_id,
  to_location_id,
  load_weight_uom_code,
  volume_uom_code,
  currency_code,
  daily_load_weight_capacity,
  cost_per_unit_load_weight,
  daily_volume_capacity,
  cost_per_unit_load_volume,
  to_region_id,
  destination_type,
  origin_type,
  from_region_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_INTERORG_SHIP_METHODS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_interorg_ship_methods';