DROP TABLE IF EXISTS silver_bec_ods.JTF_RS_GROUPS_TL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.JTF_RS_GROUPS_TL (
  GROUP_ID DECIMAL(15, 0),
  CREATED_BY DECIMAL(15, 0),
  CREATION_DATE TIMESTAMP,
  LAST_UPDATED_BY DECIMAL(15, 0),
  LAST_UPDATE_DATE TIMESTAMP,
  LAST_UPDATE_LOGIN DECIMAL(15, 0),
  GROUP_NAME STRING,
  GROUP_DESC STRING,
  LANGUAGE STRING,
  SOURCE_LANG STRING,
  SECURITY_GROUP_ID DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.JTF_RS_GROUPS_TL (
  GROUP_ID,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  GROUP_NAME,
  GROUP_DESC,
  LANGUAGE,
  SOURCE_LANG,
  SECURITY_GROUP_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  GROUP_ID,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  GROUP_NAME,
  GROUP_DESC,
  LANGUAGE,
  SOURCE_LANG,
  SECURITY_GROUP_ID,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.JTF_RS_GROUPS_TL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'jtf_rs_groups_tl';