DROP TABLE IF EXISTS silver_bec_ods.OKS_BILL_TXN_LINES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.oks_bill_txn_lines (
  id STRING,
  btn_id STRING,
  bsl_id STRING,
  bcl_id STRING,
  object_version_number DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  bill_instance_number DECIMAL(15, 0),
  trx_line_amount STRING,
  trx_line_tax_amount DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  security_group_id DECIMAL(15, 0),
  trx_date TIMESTAMP,
  trx_number STRING,
  trx_class STRING,
  manual_credit DECIMAL(15, 0),
  trx_amount DECIMAL(28, 10),
  split_flag STRING,
  cycle_refrence STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.oks_bill_txn_lines (
  id,
  btn_id,
  bsl_id,
  bcl_id,
  object_version_number,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  bill_instance_number,
  trx_line_amount,
  trx_line_tax_amount,
  last_update_login,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  trx_date,
  trx_number,
  trx_class,
  manual_credit,
  trx_amount,
  split_flag,
  cycle_refrence,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  id,
  btn_id,
  bsl_id,
  bcl_id,
  object_version_number,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  bill_instance_number,
  trx_line_amount,
  trx_line_tax_amount,
  last_update_login,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  trx_date,
  trx_number,
  trx_class,
  manual_credit,
  trx_amount,
  split_flag,
  cycle_refrence,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.oks_bill_txn_lines;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'oks_bill_txn_lines';