DROP TABLE IF EXISTS silver_bec_ods.PO_ASL_ATTRIBUTES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.PO_ASL_ATTRIBUTES (
  asl_id DECIMAL(15, 0),
  using_organization_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  document_sourcing_method STRING,
  release_generation_method STRING,
  purchasing_unit_of_measure STRING,
  enable_plan_schedule_flag STRING,
  enable_ship_schedule_flag STRING,
  plan_schedule_type STRING,
  ship_schedule_type STRING,
  plan_bucket_pattern_id DECIMAL(15, 0),
  ship_bucket_pattern_id DECIMAL(15, 0),
  enable_autoschedule_flag STRING,
  scheduler_id DECIMAL(15, 0),
  enable_authorizations_flag STRING,
  vendor_id DECIMAL(15, 0),
  vendor_site_id DECIMAL(15, 0),
  item_id DECIMAL(15, 0),
  category_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  price_update_tolerance DECIMAL(28, 10),
  processing_lead_time DECIMAL(15, 0),
  min_order_qty DECIMAL(28, 10),
  fixed_lot_multiple DECIMAL(28, 10),
  delivery_calendar STRING,
  country_of_origin_code STRING,
  enable_vmi_flag STRING,
  vmi_min_qty DECIMAL(28, 10),
  vmi_max_qty DECIMAL(28, 10),
  enable_vmi_auto_replenish_flag STRING,
  vmi_replenishment_approval STRING,
  consigned_from_supplier_flag STRING,
  last_billing_date TIMESTAMP,
  consigned_billing_cycle DECIMAL(15, 0),
  consume_on_aging_flag STRING,
  aging_period DECIMAL(15, 0),
  replenishment_method DECIMAL(28, 10),
  vmi_min_days DECIMAL(15, 0),
  vmi_max_days DECIMAL(15, 0),
  fixed_order_quantity DECIMAL(28, 10),
  forecast_horizon DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.PO_ASL_ATTRIBUTES (
  asl_id,
  using_organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  document_sourcing_method,
  release_generation_method,
  purchasing_unit_of_measure,
  enable_plan_schedule_flag,
  enable_ship_schedule_flag,
  plan_schedule_type,
  ship_schedule_type,
  plan_bucket_pattern_id,
  ship_bucket_pattern_id,
  enable_autoschedule_flag,
  scheduler_id,
  enable_authorizations_flag,
  vendor_id,
  vendor_site_id,
  item_id,
  category_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  price_update_tolerance,
  processing_lead_time,
  min_order_qty,
  fixed_lot_multiple,
  delivery_calendar,
  country_of_origin_code,
  enable_vmi_flag,
  vmi_min_qty,
  vmi_max_qty,
  enable_vmi_auto_replenish_flag,
  vmi_replenishment_approval,
  consigned_from_supplier_flag,
  last_billing_date,
  consigned_billing_cycle,
  consume_on_aging_flag,
  aging_period,
  replenishment_method,
  vmi_min_days,
  vmi_max_days,
  fixed_order_quantity,
  forecast_horizon,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  asl_id,
  using_organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  document_sourcing_method,
  release_generation_method,
  purchasing_unit_of_measure,
  enable_plan_schedule_flag,
  enable_ship_schedule_flag,
  plan_schedule_type,
  ship_schedule_type,
  plan_bucket_pattern_id,
  ship_bucket_pattern_id,
  enable_autoschedule_flag,
  scheduler_id,
  enable_authorizations_flag,
  vendor_id,
  vendor_site_id,
  item_id,
  category_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  price_update_tolerance,
  processing_lead_time,
  min_order_qty,
  fixed_lot_multiple,
  delivery_calendar,
  country_of_origin_code,
  enable_vmi_flag,
  vmi_min_qty,
  vmi_max_qty,
  enable_vmi_auto_replenish_flag,
  vmi_replenishment_approval,
  consigned_from_supplier_flag,
  last_billing_date,
  consigned_billing_cycle,
  consume_on_aging_flag,
  aging_period,
  replenishment_method,
  vmi_min_days,
  vmi_max_days,
  fixed_order_quantity,
  forecast_horizon,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.PO_ASL_ATTRIBUTES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'po_asl_attributes';