DROP TABLE IF EXISTS silver_bec_ods.GL_IMPORT_REFERENCES;
CREATE TABLE silver_bec_ods.GL_IMPORT_REFERENCES (
  je_batch_id DECIMAL(15, 0),
  je_header_id DECIMAL(15, 0),
  je_line_num DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  reference_1 STRING,
  reference_2 STRING,
  reference_3 STRING,
  reference_4 STRING,
  reference_5 STRING,
  reference_6 STRING,
  reference_7 STRING,
  reference_8 STRING,
  reference_9 STRING,
  reference_10 STRING,
  subledger_doc_sequence_id DECIMAL(15, 0),
  subledger_doc_sequence_value DECIMAL(38, 10),
  gl_sl_link_id DECIMAL(15, 0),
  gl_sl_link_table STRING,
  KCA_OPERATION STRING,
  `IS_DELETED_FLG` STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.GL_IMPORT_REFERENCES (
  je_batch_id,
  je_header_id,
  je_line_num,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  reference_1,
  reference_2,
  reference_3,
  reference_4,
  reference_5,
  reference_6,
  reference_7,
  reference_8,
  reference_9,
  reference_10,
  subledger_doc_sequence_id,
  subledger_doc_sequence_value,
  gl_sl_link_id,
  gl_sl_link_table,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  je_batch_id,
  je_header_id,
  je_line_num,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  reference_1,
  reference_2,
  reference_3,
  reference_4,
  reference_5,
  reference_6,
  reference_7,
  reference_8,
  reference_9,
  reference_10,
  subledger_doc_sequence_id,
  subledger_doc_sequence_value,
  gl_sl_link_id,
  gl_sl_link_table,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(kca_seq_id, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.GL_IMPORT_REFERENCES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_import_references';