DROP TABLE IF EXISTS silver_bec_ods.fnd_responsibility_tl;
CREATE TABLE IF NOT EXISTS silver_bec_ods.fnd_responsibility_tl (
  APPLICATION_ID DECIMAL(15, 0),
  RESPONSIBILITY_ID DECIMAL(15, 0),
  LANGUAGE STRING,
  RESPONSIBILITY_NAME STRING,
  CREATED_BY DECIMAL(15, 0),
  CREATION_DATE TIMESTAMP,
  LAST_UPDATED_BY DECIMAL(15, 0),
  LAST_UPDATE_DATE TIMESTAMP,
  LAST_UPDATE_LOGIN DECIMAL(15, 0),
  DESCRIPTION STRING,
  SOURCE_LANG STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.fnd_responsibility_tl (
  APPLICATION_ID,
  RESPONSIBILITY_ID,
  LANGUAGE,
  RESPONSIBILITY_NAME,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  DESCRIPTION,
  SOURCE_LANG,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  APPLICATION_ID,
  RESPONSIBILITY_ID,
  LANGUAGE,
  RESPONSIBILITY_NAME,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  DESCRIPTION,
  SOURCE_LANG,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.fnd_responsibility_tl;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fnd_responsibility_tl';