DROP TABLE IF EXISTS silver_bec_ods.FA_DEPRN_PERIODS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.FA_DEPRN_PERIODS (
  book_type_code STRING,
  period_name STRING,
  period_counter DECIMAL(15, 0),
  fiscal_year SMALLINT,
  period_num SMALLINT,
  period_open_date TIMESTAMP,
  period_close_date TIMESTAMP,
  depreciation_batch_id DECIMAL(15, 0),
  retirement_batch_id DECIMAL(15, 0),
  reclass_batch_id DECIMAL(15, 0),
  transfer_batch_id DECIMAL(15, 0),
  addition_batch_id DECIMAL(15, 0),
  adjustment_batch_id DECIMAL(15, 0),
  deferred_deprn_batch_id DECIMAL(15, 0),
  calendar_period_open_date TIMESTAMP,
  calendar_period_close_date TIMESTAMP,
  cip_addition_batch_id DECIMAL(15, 0),
  cip_adjustment_batch_id DECIMAL(15, 0),
  cip_reclass_batch_id DECIMAL(15, 0),
  cip_retirement_batch_id DECIMAL(15, 0),
  cip_reval_batch_id DECIMAL(15, 0),
  cip_transfer_batch_id DECIMAL(15, 0),
  reval_batch_id DECIMAL(15, 0),
  deprn_adjustment_batch_id DECIMAL(15, 0),
  deprn_run STRING,
  xla_conversion_status STRING,
  gl_transfer_flag STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.FA_DEPRN_PERIODS (
  book_type_code,
  period_name,
  period_counter,
  fiscal_year,
  period_num,
  period_open_date,
  period_close_date,
  depreciation_batch_id,
  retirement_batch_id,
  reclass_batch_id,
  transfer_batch_id,
  addition_batch_id,
  adjustment_batch_id,
  deferred_deprn_batch_id,
  calendar_period_open_date,
  calendar_period_close_date,
  cip_addition_batch_id,
  cip_adjustment_batch_id,
  cip_reclass_batch_id,
  cip_retirement_batch_id,
  cip_reval_batch_id,
  cip_transfer_batch_id,
  reval_batch_id,
  deprn_adjustment_batch_id,
  deprn_run,
  xla_conversion_status,
  gl_transfer_flag,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  book_type_code,
  period_name,
  period_counter,
  fiscal_year,
  period_num,
  period_open_date,
  period_close_date,
  depreciation_batch_id,
  retirement_batch_id,
  reclass_batch_id,
  transfer_batch_id,
  addition_batch_id,
  adjustment_batch_id,
  deferred_deprn_batch_id,
  calendar_period_open_date,
  calendar_period_close_date,
  cip_addition_batch_id,
  cip_adjustment_batch_id,
  cip_reclass_batch_id,
  cip_retirement_batch_id,
  cip_reval_batch_id,
  cip_transfer_batch_id,
  reval_batch_id,
  deprn_adjustment_batch_id,
  deprn_run,
  xla_conversion_status,
  gl_transfer_flag,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.FA_DEPRN_PERIODS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fa_deprn_periods';