DROP TABLE IF EXISTS silver_bec_ods.QP_LIST_HEADERS_B;
CREATE TABLE IF NOT EXISTS silver_bec_ods.QP_LIST_HEADERS_B (
  list_header_id DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  list_type_code STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  automatic_flag STRING,
  currency_code STRING,
  rounding_factor DECIMAL(15, 0),
  ship_method_code STRING,
  freight_terms_code STRING,
  terms_id DECIMAL(15, 0),
  comments STRING,
  discount_lines_flag STRING,
  gsa_indicator STRING,
  prorate_flag STRING,
  source_system_code STRING,
  ask_for_flag STRING,
  active_flag STRING,
  parent_list_header_id DECIMAL(15, 0),
  start_date_active_first TIMESTAMP,
  end_date_active_first TIMESTAMP,
  active_date_first_type STRING,
  start_date_active_second TIMESTAMP,
  end_date_active_second TIMESTAMP,
  active_date_second_type STRING,
  context STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  limit_exists_flag STRING,
  mobile_download STRING,
  currency_header_id DECIMAL(15, 0),
  pte_code STRING,
  list_source_code STRING,
  orig_system_header_ref STRING,
  orig_org_id DECIMAL(15, 0),
  global_flag STRING,
  shareable_flag STRING,
  sold_to_org_id DECIMAL(15, 0),
  locked_from_list_header_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.QP_LIST_HEADERS_B (
  list_header_id,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  list_type_code,
  start_date_active,
  end_date_active,
  automatic_flag,
  currency_code,
  rounding_factor,
  ship_method_code,
  freight_terms_code,
  terms_id,
  comments,
  discount_lines_flag,
  gsa_indicator,
  prorate_flag,
  source_system_code,
  ask_for_flag,
  active_flag,
  parent_list_header_id,
  start_date_active_first,
  end_date_active_first,
  active_date_first_type,
  start_date_active_second,
  end_date_active_second,
  active_date_second_type,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  limit_exists_flag,
  mobile_download,
  currency_header_id,
  pte_code,
  list_source_code,
  orig_system_header_ref,
  orig_org_id,
  global_flag,
  shareable_flag,
  sold_to_org_id,
  locked_from_list_header_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  list_header_id,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  list_type_code,
  start_date_active,
  end_date_active,
  automatic_flag,
  currency_code,
  rounding_factor,
  ship_method_code,
  freight_terms_code,
  terms_id,
  comments,
  discount_lines_flag,
  gsa_indicator,
  prorate_flag,
  source_system_code,
  ask_for_flag,
  active_flag,
  parent_list_header_id,
  start_date_active_first,
  end_date_active_first,
  active_date_first_type,
  start_date_active_second,
  end_date_active_second,
  active_date_second_type,
  context,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  limit_exists_flag,
  mobile_download,
  currency_header_id,
  pte_code,
  list_source_code,
  orig_system_header_ref,
  orig_org_id,
  global_flag,
  shareable_flag,
  sold_to_org_id,
  locked_from_list_header_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.QP_LIST_HEADERS_B;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'qp_list_headers_b';