DROP TABLE IF EXISTS silver_bec_ods.OKS_K_LINES_B;
CREATE TABLE IF NOT EXISTS silver_bec_ods.OKS_K_LINES_B (
  id STRING,
  cle_id STRING,
  dnz_chr_id STRING,
  discount_list DECIMAL(15, 0),
  acct_rule_id DECIMAL(15, 0),
  payment_type STRING,
  cc_no STRING,
  cc_expiry_date TIMESTAMP,
  cc_bank_acct_id DECIMAL(15, 0),
  cc_auth_code STRING,
  commitment_id DECIMAL(15, 0),
  locked_price_list_id DECIMAL(15, 0),
  usage_est_yn STRING,
  usage_est_method STRING,
  usage_est_start_date TIMESTAMP,
  termn_method STRING,
  ubt_amount DECIMAL(28, 10),
  credit_amount DECIMAL(28, 10),
  suppressed_credit DECIMAL(28, 10),
  override_amount DECIMAL(28, 10),
  cust_po_number_req_yn STRING,
  cust_po_number STRING,
  grace_duration DECIMAL(15, 0),
  grace_period STRING,
  inv_print_flag STRING,
  price_uom STRING,
  tax_amount DECIMAL(28, 10),
  tax_inclusive_yn STRING,
  tax_status STRING,
  tax_code DECIMAL(28, 10),
  tax_exemption_id DECIMAL(15, 0),
  ib_trans_type STRING,
  ib_trans_date TIMESTAMP,
  prod_price DECIMAL(28, 10),
  service_price DECIMAL(28, 10),
  clvl_list_price DECIMAL(28, 10),
  clvl_quantity DECIMAL(28, 10),
  clvl_extended_amt DECIMAL(28, 10),
  clvl_uom_code STRING,
  toplvl_operand_code STRING,
  toplvl_operand_val DECIMAL(28, 10),
  toplvl_quantity DECIMAL(28, 10),
  toplvl_uom_code STRING,
  toplvl_adj_price DECIMAL(28, 10),
  toplvl_price_qty DECIMAL(28, 10),
  averaging_interval DECIMAL(28, 10),
  settlement_interval STRING,
  minimum_quantity DECIMAL(28, 10),
  default_quantity DECIMAL(28, 10),
  amcv_flag STRING,
  fixed_quantity DECIMAL(28, 10),
  usage_duration DECIMAL(28, 10),
  usage_period STRING,
  level_yn STRING,
  usage_type STRING,
  uom_quantified STRING,
  base_reading DECIMAL(15, 0),
  billing_schedule_type STRING,
  full_credit STRING,
  locked_price_list_line_id DECIMAL(15, 0),
  break_uom STRING,
  prorate STRING,
  coverage_type STRING,
  exception_cov_id DECIMAL(15, 0),
  limit_uom_quantified STRING,
  discount_amount DECIMAL(28, 10),
  discount_percent DECIMAL(28, 10),
  offset_duration DECIMAL(28, 10),
  offset_period STRING,
  incident_severity_id DECIMAL(15, 0),
  pdf_id DECIMAL(15, 0),
  work_thru_yn STRING,
  react_active_yn STRING,
  transfer_option STRING,
  prod_upgrade_yn STRING,
  inheritance_type STRING,
  pm_program_id DECIMAL(15, 0),
  pm_conf_req_yn STRING,
  pm_sch_exists_yn STRING,
  allow_bt_discount STRING,
  apply_default_timezone STRING,
  sync_date_install STRING,
  object_version_number DECIMAL(15, 0),
  security_group_id DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  trxn_extension_id DECIMAL(15, 0),
  tax_classification_code STRING,
  exempt_certificate_number STRING,
  exempt_reason_code STRING,
  coverage_id STRING,
  standard_cov_yn STRING,
  orig_system_id1 STRING,
  orig_system_reference1 STRING,
  orig_system_source_code STRING,
  revenue_impact_date TIMESTAMP,
  counter_value_id DECIMAL(15, 0),
  from_day DECIMAL(15, 0),
  to_day DECIMAL(15, 0),
  inv_organization_id DECIMAL(15, 0),
  consolidation_yn STRING,
  billing_option STRING,
  usage_limit_definition STRING,
  rollover_type STRING,
  usage_limit_value DECIMAL(28, 10),
  usage_grace_period STRING,
  usage_grace_duration DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.OKS_K_LINES_B (
  id,
  cle_id,
  dnz_chr_id,
  discount_list,
  acct_rule_id,
  payment_type,
  cc_no,
  cc_expiry_date,
  cc_bank_acct_id,
  cc_auth_code,
  commitment_id,
  locked_price_list_id,
  usage_est_yn,
  usage_est_method,
  usage_est_start_date,
  termn_method,
  ubt_amount,
  credit_amount,
  suppressed_credit,
  override_amount,
  cust_po_number_req_yn,
  cust_po_number,
  grace_duration,
  grace_period,
  inv_print_flag,
  price_uom,
  tax_amount,
  tax_inclusive_yn,
  tax_status,
  tax_code,
  tax_exemption_id,
  ib_trans_type,
  ib_trans_date,
  prod_price,
  service_price,
  clvl_list_price,
  clvl_quantity,
  clvl_extended_amt,
  clvl_uom_code,
  toplvl_operand_code,
  toplvl_operand_val,
  toplvl_quantity,
  toplvl_uom_code,
  toplvl_adj_price,
  toplvl_price_qty,
  averaging_interval,
  settlement_interval,
  minimum_quantity,
  default_quantity,
  amcv_flag,
  fixed_quantity,
  usage_duration,
  usage_period,
  level_yn,
  usage_type,
  uom_quantified,
  base_reading,
  billing_schedule_type,
  full_credit,
  locked_price_list_line_id,
  break_uom,
  prorate,
  coverage_type,
  exception_cov_id,
  limit_uom_quantified,
  discount_amount,
  discount_percent,
  offset_duration,
  offset_period,
  incident_severity_id,
  pdf_id,
  work_thru_yn,
  react_active_yn,
  transfer_option,
  prod_upgrade_yn,
  inheritance_type,
  pm_program_id,
  pm_conf_req_yn,
  pm_sch_exists_yn,
  allow_bt_discount,
  apply_default_timezone,
  sync_date_install,
  object_version_number,
  security_group_id,
  request_id,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  trxn_extension_id,
  tax_classification_code,
  exempt_certificate_number,
  exempt_reason_code,
  coverage_id,
  standard_cov_yn,
  orig_system_id1,
  orig_system_reference1,
  orig_system_source_code,
  revenue_impact_date,
  counter_value_id,
  from_day,
  to_day,
  inv_organization_id,
  consolidation_yn,
  billing_option,
  usage_limit_definition,
  rollover_type,
  usage_limit_value,
  usage_grace_period,
  usage_grace_duration,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  id,
  cle_id,
  dnz_chr_id,
  discount_list,
  acct_rule_id,
  payment_type,
  cc_no,
  cc_expiry_date,
  cc_bank_acct_id,
  cc_auth_code,
  commitment_id,
  locked_price_list_id,
  usage_est_yn,
  usage_est_method,
  usage_est_start_date,
  termn_method,
  ubt_amount,
  credit_amount,
  suppressed_credit,
  override_amount,
  cust_po_number_req_yn,
  cust_po_number,
  grace_duration,
  grace_period,
  inv_print_flag,
  price_uom,
  tax_amount,
  tax_inclusive_yn,
  tax_status,
  tax_code,
  tax_exemption_id,
  ib_trans_type,
  ib_trans_date,
  prod_price,
  service_price,
  clvl_list_price,
  clvl_quantity,
  clvl_extended_amt,
  clvl_uom_code,
  toplvl_operand_code,
  toplvl_operand_val,
  toplvl_quantity,
  toplvl_uom_code,
  toplvl_adj_price,
  toplvl_price_qty,
  averaging_interval,
  settlement_interval,
  minimum_quantity,
  default_quantity,
  amcv_flag,
  fixed_quantity,
  usage_duration,
  usage_period,
  level_yn,
  usage_type,
  uom_quantified,
  base_reading,
  billing_schedule_type,
  full_credit,
  locked_price_list_line_id,
  break_uom,
  prorate,
  coverage_type,
  exception_cov_id,
  limit_uom_quantified,
  discount_amount,
  discount_percent,
  offset_duration,
  offset_period,
  incident_severity_id,
  pdf_id,
  work_thru_yn,
  react_active_yn,
  transfer_option,
  prod_upgrade_yn,
  inheritance_type,
  pm_program_id,
  pm_conf_req_yn,
  pm_sch_exists_yn,
  allow_bt_discount,
  apply_default_timezone,
  sync_date_install,
  object_version_number,
  security_group_id,
  request_id,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  trxn_extension_id,
  tax_classification_code,
  exempt_certificate_number,
  exempt_reason_code,
  coverage_id,
  standard_cov_yn,
  orig_system_id1,
  orig_system_reference1,
  orig_system_source_code,
  revenue_impact_date,
  counter_value_id,
  from_day,
  to_day,
  inv_organization_id,
  consolidation_yn,
  billing_option,
  usage_limit_definition,
  rollover_type,
  usage_limit_value,
  usage_grace_period,
  usage_grace_duration,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.OKS_K_LINES_B;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'oks_k_lines_b';