DROP TABLE IF EXISTS silver_bec_ods.GL_BALANCES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.GL_BALANCES (
  ledger_id DECIMAL(15, 0),
  code_combination_id DECIMAL(15, 0),
  currency_code STRING,
  period_name STRING,
  actual_flag STRING,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  budget_version_id DECIMAL(15, 0),
  encumbrance_type_id DECIMAL(15, 0),
  translated_flag STRING,
  revaluation_status STRING,
  period_type STRING,
  period_year DECIMAL(15, 0),
  period_num DECIMAL(15, 0),
  period_net_dr DECIMAL(28, 10),
  period_net_cr DECIMAL(28, 10),
  period_to_date_adb DECIMAL(28, 10),
  quarter_to_date_dr DECIMAL(28, 10),
  quarter_to_date_cr DECIMAL(28, 10),
  quarter_to_date_adb DECIMAL(28, 10),
  year_to_date_adb DECIMAL(28, 10),
  project_to_date_dr DECIMAL(28, 10),
  project_to_date_cr DECIMAL(28, 10),
  project_to_date_adb DECIMAL(28, 10),
  begin_balance_dr DECIMAL(28, 10),
  begin_balance_cr DECIMAL(28, 10),
  period_net_dr_beq DECIMAL(28, 10),
  period_net_cr_beq DECIMAL(28, 10),
  begin_balance_dr_beq DECIMAL(28, 10),
  begin_balance_cr_beq DECIMAL(28, 10),
  template_id DECIMAL(15, 0),
  encumbrance_doc_id DECIMAL(15, 0),
  encumbrance_line_num DECIMAL(15, 0),
  quarter_to_date_dr_beq DECIMAL(28, 10),
  quarter_to_date_cr_beq DECIMAL(28, 10),
  project_to_date_dr_beq DECIMAL(28, 10),
  project_to_date_cr_beq DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.GL_BALANCES (
  ledger_id,
  code_combination_id,
  currency_code,
  period_name,
  actual_flag,
  last_update_date,
  last_updated_by,
  budget_version_id,
  encumbrance_type_id,
  translated_flag,
  revaluation_status,
  period_type,
  period_year,
  period_num,
  period_net_dr,
  period_net_cr,
  period_to_date_adb,
  quarter_to_date_dr,
  quarter_to_date_cr,
  quarter_to_date_adb,
  year_to_date_adb,
  project_to_date_dr,
  project_to_date_cr,
  project_to_date_adb,
  begin_balance_dr,
  begin_balance_cr,
  period_net_dr_beq,
  period_net_cr_beq,
  begin_balance_dr_beq,
  begin_balance_cr_beq,
  template_id,
  encumbrance_doc_id,
  encumbrance_line_num,
  quarter_to_date_dr_beq,
  quarter_to_date_cr_beq,
  project_to_date_dr_beq,
  project_to_date_cr_beq,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  ledger_id,
  code_combination_id,
  currency_code,
  period_name,
  actual_flag,
  last_update_date,
  last_updated_by,
  budget_version_id,
  encumbrance_type_id,
  translated_flag,
  revaluation_status,
  period_type,
  period_year,
  period_num,
  period_net_dr,
  period_net_cr,
  period_to_date_adb,
  quarter_to_date_dr,
  quarter_to_date_cr,
  quarter_to_date_adb,
  year_to_date_adb,
  project_to_date_dr,
  project_to_date_cr,
  project_to_date_adb,
  begin_balance_dr,
  begin_balance_cr,
  period_net_dr_beq,
  period_net_cr_beq,
  begin_balance_dr_beq,
  begin_balance_cr_beq,
  template_id,
  encumbrance_doc_id,
  encumbrance_line_num,
  quarter_to_date_dr_beq,
  quarter_to_date_cr_beq,
  project_to_date_dr_beq,
  project_to_date_cr_beq,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.GL_BALANCES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_balances';