DROP TABLE IF EXISTS silver_bec_ods.BEC_ACTUAL_PO_RECPT1;
CREATE TABLE IF NOT EXISTS silver_bec_ods.BEC_ACTUAL_PO_RECPT1 (
  wip_entity_name STRING,
  po_type STRING,
  po_number STRING,
  pr_approved_date TIMESTAMP,
  reaction_time DECIMAL(38, 0),
  po_placed_ontime DECIMAL(15, 0),
  buyer_name STRING,
  po_release_number DECIMAL(15, 0),
  po_shipment_num DECIMAL(15, 0),
  po_date TIMESTAMP,
  po_last_update_date TIMESTAMP,
  processing_leadtime DECIMAL(15, 0),
  po_line_num DECIMAL(28, 10),
  item_name STRING,
  item_description STRING,
  line_quantity DECIMAL(28, 10),
  quantity_shipped DECIMAL(28, 10),
  po_unit_of_measure STRING,
  primary_uom_code STRING,
  primary_unit_of_measure STRING,
  need_by_date TIMESTAMP,
  promised_date TIMESTAMP,
  rcv_quantity_received DECIMAL(28, 10),
  primary_quantity DECIMAL(28, 10),
  po_unit_price DECIMAL(28, 10),
  extended_po_rcv_price DECIMAL(28, 10),
  receipt_number STRING,
  packing_slip STRING,
  shipment_num STRING,
  waybill_airbill_num STRING,
  bill_of_lading STRING,
  shipment_date TIMESTAMP,
  vendor_number STRING,
  vendor_name STRING,
  closed_code STRING,
  po_currency_code STRING,
  shipment_header_id DECIMAL(15, 0),
  shipment_line_id DECIMAL(15, 0),
  po_line_type STRING,
  line_location_id DECIMAL(15, 0),
  unit_of_measure STRING,
  po_conversion DECIMAL(28, 10),
  rcv_conversion DECIMAL(28, 10),
  asn_type STRING,
  asn_status STRING,
  receipt_date TIMESTAMP,
  std_item_cost DECIMAL(28, 10),
  material_cost DECIMAL(28, 10),
  ext_material_cost DECIMAL(28, 10),
  purchase_price_variance DECIMAL(28, 10),
  outside_processing_cost DECIMAL(28, 10),
  overhead_cost DECIMAL(28, 10),
  material_overhead_cost DECIMAL(28, 10),
  resource_cost DECIMAL(28, 10),
  fob_code STRING,
  ship_to_location STRING,
  ship_to_organization STRING,
  organization_code STRING,
  organization_id DECIMAL(15, 0),
  category STRING,
  item_revision STRING,
  attribute10 TIMESTAMP,
  actual_commit_need_date TIMESTAMP,
  freight_terms STRING,
  cvmi_flag STRING,
  vendor_country STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.BEC_ACTUAL_PO_RECPT1 (
  wip_entity_name,
  po_type,
  po_number,
  pr_approved_date,
  reaction_time,
  po_placed_ontime,
  buyer_name,
  po_release_number,
  po_shipment_num,
  po_date,
  po_last_update_date,
  processing_leadtime,
  po_line_num,
  item_name,
  item_description,
  line_quantity,
  quantity_shipped,
  po_unit_of_measure,
  primary_uom_code,
  primary_unit_of_measure,
  need_by_date,
  promised_date,
  rcv_quantity_received,
  primary_quantity,
  po_unit_price,
  extended_po_rcv_price,
  receipt_number,
  packing_slip,
  shipment_num,
  waybill_airbill_num,
  bill_of_lading,
  shipment_date,
  vendor_number,
  vendor_name,
  closed_code,
  po_currency_code,
  shipment_header_id,
  shipment_line_id,
  po_line_type,
  line_location_id,
  unit_of_measure,
  po_conversion,
  rcv_conversion,
  asn_type,
  asn_status,
  receipt_date,
  std_item_cost,
  material_cost,
  ext_material_cost,
  purchase_price_variance,
  outside_processing_cost,
  overhead_cost,
  material_overhead_cost,
  resource_cost,
  fob_code,
  ship_to_location,
  ship_to_organization,
  organization_code,
  organization_id,
  category,
  item_revision,
  attribute10,
  actual_commit_need_date,
  freight_terms,
  cvmi_flag,
  vendor_country,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  wip_entity_name,
  po_type,
  po_number,
  pr_approved_date,
  reaction_time,
  po_placed_ontime,
  buyer_name,
  po_release_number,
  po_shipment_num,
  po_date,
  po_last_update_date,
  processing_leadtime,
  po_line_num,
  item_name,
  item_description,
  line_quantity,
  quantity_shipped,
  po_unit_of_measure,
  primary_uom_code,
  primary_unit_of_measure,
  need_by_date,
  promised_date,
  rcv_quantity_received,
  primary_quantity,
  po_unit_price,
  extended_po_rcv_price,
  receipt_number,
  packing_slip,
  shipment_num,
  waybill_airbill_num,
  bill_of_lading,
  shipment_date,
  vendor_number,
  vendor_name,
  closed_code,
  po_currency_code,
  shipment_header_id,
  shipment_line_id,
  po_line_type,
  line_location_id,
  unit_of_measure,
  po_conversion,
  rcv_conversion,
  asn_type,
  asn_status,
  receipt_date,
  std_item_cost,
  material_cost,
  ext_material_cost,
  purchase_price_variance,
  outside_processing_cost,
  overhead_cost,
  material_overhead_cost,
  resource_cost,
  fob_code,
  ship_to_location,
  ship_to_organization,
  organization_code,
  organization_id,
  category,
  item_revision,
  attribute10,
  actual_commit_need_date,
  freight_terms,
  cvmi_flag,
  vendor_country,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.BEC_ACTUAL_PO_RECPT1;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'bec_actual_po_recpt1';