DROP TABLE IF EXISTS silver_bec_ods.HZ_CUST_ACCOUNTS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.hz_cust_accounts (
  cust_account_id DECIMAL(15, 0),
  party_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  account_number STRING,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  wh_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute16 STRING,
  attribute17 STRING,
  attribute18 STRING,
  attribute19 STRING,
  attribute20 STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  orig_system_reference STRING,
  status STRING,
  customer_type STRING,
  customer_class_code STRING,
  primary_salesrep_id DECIMAL(15, 0),
  sales_channel_code STRING,
  order_type_id DECIMAL(15, 0),
  price_list_id DECIMAL(15, 0),
  subcategory_code STRING,
  tax_code STRING,
  fob_point STRING,
  freight_term STRING,
  ship_partial STRING,
  ship_via STRING,
  warehouse_id DECIMAL(15, 0),
  payment_term_id DECIMAL(15, 0),
  tax_header_level_flag STRING,
  tax_rounding_rule STRING,
  coterminate_day_month STRING,
  primary_specialist_id DECIMAL(15, 0),
  secondary_specialist_id DECIMAL(15, 0),
  account_liable_flag STRING,
  restriction_limit_amount DECIMAL(28, 10),
  current_balance DECIMAL(28, 10),
  password_text STRING,
  high_priority_indicator STRING,
  account_established_date TIMESTAMP,
  account_termination_date TIMESTAMP,
  account_activation_date TIMESTAMP,
  credit_classification_code STRING,
  department STRING,
  major_account_number STRING,
  hotwatch_service_flag STRING,
  hotwatch_svc_bal_ind STRING,
  held_bill_expiration_date TIMESTAMP,
  hold_bill_flag STRING,
  high_priority_remarks STRING,
  po_effective_date TIMESTAMP,
  po_expiration_date TIMESTAMP,
  realtime_rate_flag STRING,
  single_user_flag STRING,
  watch_account_flag STRING,
  watch_balance_indicator STRING,
  geo_code STRING,
  acct_life_cycle_status STRING,
  account_name STRING,
  deposit_refund_method STRING,
  dormant_account_flag STRING,
  npa_number STRING,
  pin_number DECIMAL(16, 0),
  suspension_date TIMESTAMP,
  write_off_adjustment_amount DECIMAL(28, 10),
  write_off_payment_amount DECIMAL(28, 10),
  write_off_amount DECIMAL(28, 10),
  source_code STRING,
  competitor_type STRING,
  comments STRING,
  dates_negative_tolerance DECIMAL(28, 10),
  dates_positive_tolerance DECIMAL(28, 10),
  date_type_preference STRING,
  over_shipment_tolerance DECIMAL(28, 10),
  under_shipment_tolerance DECIMAL(28, 10),
  over_return_tolerance DECIMAL(28, 10),
  under_return_tolerance DECIMAL(28, 10),
  item_cross_ref_pref STRING,
  ship_sets_include_lines_flag STRING,
  arrivalsets_include_lines_flag STRING,
  sched_date_push_flag STRING,
  invoice_quantity_rule STRING,
  pricing_event STRING,
  account_replication_key DECIMAL(15, 0),
  status_update_date TIMESTAMP,
  autopay_flag STRING,
  notify_flag STRING,
  last_batch_id DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  object_version_number DECIMAL(15, 0),
  created_by_module STRING,
  application_id DECIMAL(15, 0),
  selling_party_id DECIMAL(15, 0),
  ADVANCE_PAYMENT_INDICATOR STRING,
  DUNS_EXTENSION STRING,
  FEDERAL_ENTITY_TYPE STRING,
  TRADING_PARTNER_AGENCY_ID DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.HZ_CUST_ACCOUNTS (
  cust_account_id,
  party_id,
  last_update_date,
  account_number,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wh_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  orig_system_reference,
  status,
  customer_type,
  customer_class_code,
  primary_salesrep_id,
  sales_channel_code,
  order_type_id,
  price_list_id,
  subcategory_code,
  tax_code,
  fob_point,
  freight_term,
  ship_partial,
  ship_via,
  warehouse_id,
  payment_term_id,
  tax_header_level_flag,
  tax_rounding_rule,
  coterminate_day_month,
  primary_specialist_id,
  secondary_specialist_id,
  account_liable_flag,
  restriction_limit_amount,
  current_balance,
  password_text,
  high_priority_indicator,
  account_established_date,
  account_termination_date,
  account_activation_date,
  credit_classification_code,
  department,
  major_account_number,
  hotwatch_service_flag,
  hotwatch_svc_bal_ind,
  held_bill_expiration_date,
  hold_bill_flag,
  high_priority_remarks,
  po_effective_date,
  po_expiration_date,
  realtime_rate_flag,
  single_user_flag,
  watch_account_flag,
  watch_balance_indicator,
  geo_code,
  acct_life_cycle_status,
  account_name,
  deposit_refund_method,
  dormant_account_flag,
  npa_number,
  pin_number,
  suspension_date,
  write_off_adjustment_amount,
  write_off_payment_amount,
  write_off_amount,
  source_code,
  competitor_type,
  comments,
  dates_negative_tolerance,
  dates_positive_tolerance,
  date_type_preference,
  over_shipment_tolerance,
  under_shipment_tolerance,
  over_return_tolerance,
  under_return_tolerance,
  item_cross_ref_pref,
  ship_sets_include_lines_flag,
  arrivalsets_include_lines_flag,
  sched_date_push_flag,
  invoice_quantity_rule,
  pricing_event,
  account_replication_key,
  status_update_date,
  autopay_flag,
  notify_flag,
  last_batch_id,
  org_id,
  object_version_number,
  created_by_module,
  application_id,
  selling_party_id,
  ADVANCE_PAYMENT_INDICATOR,
  DUNS_EXTENSION,
  FEDERAL_ENTITY_TYPE,
  TRADING_PARTNER_AGENCY_ID,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cust_account_id,
  party_id,
  last_update_date,
  account_number,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wh_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  orig_system_reference,
  status,
  customer_type,
  customer_class_code,
  primary_salesrep_id,
  sales_channel_code,
  order_type_id,
  price_list_id,
  subcategory_code,
  tax_code,
  fob_point,
  freight_term,
  ship_partial,
  ship_via,
  warehouse_id,
  payment_term_id,
  tax_header_level_flag,
  tax_rounding_rule,
  coterminate_day_month,
  primary_specialist_id,
  secondary_specialist_id,
  account_liable_flag,
  restriction_limit_amount,
  current_balance,
  password_text,
  high_priority_indicator,
  account_established_date,
  account_termination_date,
  account_activation_date,
  credit_classification_code,
  department,
  major_account_number,
  hotwatch_service_flag,
  hotwatch_svc_bal_ind,
  held_bill_expiration_date,
  hold_bill_flag,
  high_priority_remarks,
  po_effective_date,
  po_expiration_date,
  realtime_rate_flag,
  single_user_flag,
  watch_account_flag,
  watch_balance_indicator,
  geo_code,
  acct_life_cycle_status,
  account_name,
  deposit_refund_method,
  dormant_account_flag,
  npa_number,
  pin_number,
  suspension_date,
  write_off_adjustment_amount,
  write_off_payment_amount,
  write_off_amount,
  source_code,
  competitor_type,
  comments,
  dates_negative_tolerance,
  dates_positive_tolerance,
  date_type_preference,
  over_shipment_tolerance,
  under_shipment_tolerance,
  over_return_tolerance,
  under_return_tolerance,
  item_cross_ref_pref,
  ship_sets_include_lines_flag,
  arrivalsets_include_lines_flag,
  sched_date_push_flag,
  invoice_quantity_rule,
  pricing_event,
  account_replication_key,
  status_update_date,
  autopay_flag,
  notify_flag,
  last_batch_id,
  org_id,
  object_version_number,
  created_by_module,
  application_id,
  selling_party_id,
  ADVANCE_PAYMENT_INDICATOR,
  DUNS_EXTENSION,
  FEDERAL_ENTITY_TYPE,
  TRADING_PARTNER_AGENCY_ID,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.HZ_CUST_ACCOUNTS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'hz_cust_accounts';