DROP TABLE IF EXISTS silver_bec_ods.MSC_BOMS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MSC_BOMS (
  plan_id DECIMAL(15, 0),
  bill_sequence_id DECIMAL(15, 0),
  sr_instance_id DECIMAL(15, 0),
  assembly_type DECIMAL(15, 0),
  alternate_bom_designator STRING,
  specific_assembly_comment STRING,
  pending_from_ecn STRING,
  scaling_type DECIMAL(15, 0),
  assembly_quantity DECIMAL(28, 10),
  uom STRING,
  organization_id DECIMAL(15, 0),
  assembly_item_id DECIMAL(15, 0),
  refresh_number DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  yielding_op_seq_num DECIMAL(15, 0),
  new_plan_id DECIMAL(15, 0),
  new_plan_list STRING,
  applied DECIMAL(15, 0),
  simulation_set_id DECIMAL(15, 0),
  repairable DECIMAL(15, 0),
  activity_item_id DECIMAL(15, 0),
  `alternate_bom_designator#1` STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MSC_BOMS (
  PLAN_ID,
  BILL_SEQUENCE_ID,
  SR_INSTANCE_ID,
  ASSEMBLY_TYPE,
  ALTERNATE_BOM_DESIGNATOR,
  SPECIFIC_ASSEMBLY_COMMENT,
  PENDING_FROM_ECN,
  SCALING_TYPE,
  ASSEMBLY_QUANTITY,
  UOM,
  ORGANIZATION_ID,
  ASSEMBLY_ITEM_ID,
  REFRESH_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  YIELDING_OP_SEQ_NUM,
  NEW_PLAN_ID,
  NEW_PLAN_LIST,
  APPLIED,
  SIMULATION_SET_ID,
  REPAIRABLE,
  ACTIVITY_ITEM_ID,
  `alternate_bom_designator#1`,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  PLAN_ID,
  BILL_SEQUENCE_ID,
  SR_INSTANCE_ID,
  ASSEMBLY_TYPE,
  ALTERNATE_BOM_DESIGNATOR,
  SPECIFIC_ASSEMBLY_COMMENT,
  PENDING_FROM_ECN,
  SCALING_TYPE,
  ASSEMBLY_QUANTITY,
  UOM,
  ORGANIZATION_ID,
  ASSEMBLY_ITEM_ID,
  REFRESH_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  YIELDING_OP_SEQ_NUM,
  NEW_PLAN_ID,
  NEW_PLAN_LIST,
  APPLIED,
  SIMULATION_SET_ID,
  REPAIRABLE,
  ACTIVITY_ITEM_ID,
  `alternate_bom_designator#1`,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MSC_BOMS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_boms';