DROP TABLE IF EXISTS silver_bec_ods.AR_CASH_RECEIPT_HISTORY_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ar_cash_receipt_history_all (
  cash_receipt_history_id DECIMAL(15, 0),
  cash_receipt_id DECIMAL(15, 0),
  status STRING,
  trx_date TIMESTAMP,
  amount DECIMAL(28, 10),
  first_posted_record_flag STRING,
  postable_flag STRING,
  factor_flag STRING,
  gl_date TIMESTAMP,
  current_record_flag STRING,
  batch_id DECIMAL(15, 0),
  account_code_combination_id DECIMAL(15, 0),
  reversal_gl_date TIMESTAMP,
  reversal_cash_receipt_hist_id DECIMAL(15, 0),
  factor_discount_amount DECIMAL(28, 10),
  bank_charge_account_ccid DECIMAL(15, 0),
  posting_control_id DECIMAL(15, 0),
  reversal_posting_control_id DECIMAL(15, 0),
  gl_posted_date TIMESTAMP,
  reversal_gl_posted_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  acctd_amount DECIMAL(28, 10),
  acctd_factor_discount_amount DECIMAL(28, 10),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  exchange_date TIMESTAMP,
  exchange_rate DECIMAL(28, 10),
  exchange_rate_type STRING,
  last_update_date TIMESTAMP,
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  prv_stat_cash_receipt_hist_id DECIMAL(15, 0),
  created_from STRING,
  reversal_created_from STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute_category STRING,
  org_id DECIMAL(15, 0),
  MRC_POSTING_CONTROL_ID STRING,
  note_status STRING,
  mrc_gl_posted_date STRING,
  mrc_reversal_gl_posted_date STRING,
  mrc_acctd_amount STRING,
  mrc_acctd_factor_disc_amount STRING,
  mrc_exchange_date STRING,
  mrc_exchange_rate STRING,
  mrc_exchange_rate_type STRING,
  event_id DECIMAL(15, 0),
  kca_operation STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.AR_CASH_RECEIPT_HISTORY_ALL (
  cash_receipt_history_id,
  cash_receipt_id,
  status,
  trx_date,
  amount,
  first_posted_record_flag,
  postable_flag,
  factor_flag,
  gl_date,
  current_record_flag,
  batch_id,
  account_code_combination_id,
  reversal_gl_date,
  reversal_cash_receipt_hist_id,
  factor_discount_amount,
  bank_charge_account_ccid,
  posting_control_id,
  reversal_posting_control_id,
  gl_posted_date,
  reversal_gl_posted_date,
  last_update_login,
  acctd_amount,
  acctd_factor_discount_amount,
  created_by,
  creation_date,
  exchange_date,
  exchange_rate,
  exchange_rate_type,
  last_update_date,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  last_updated_by,
  prv_stat_cash_receipt_hist_id,
  created_from,
  reversal_created_from,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  org_id,
  MRC_POSTING_CONTROL_ID,
  note_status,
  mrc_gl_posted_date,
  mrc_reversal_gl_posted_date,
  mrc_acctd_amount,
  mrc_acctd_factor_disc_amount,
  mrc_exchange_date,
  mrc_exchange_rate,
  mrc_exchange_rate_type,
  event_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cash_receipt_history_id,
  cash_receipt_id,
  status,
  trx_date,
  amount,
  first_posted_record_flag,
  postable_flag,
  factor_flag,
  gl_date,
  current_record_flag,
  batch_id,
  account_code_combination_id,
  reversal_gl_date,
  reversal_cash_receipt_hist_id,
  factor_discount_amount,
  bank_charge_account_ccid,
  posting_control_id,
  reversal_posting_control_id,
  gl_posted_date,
  reversal_gl_posted_date,
  last_update_login,
  acctd_amount,
  acctd_factor_discount_amount,
  created_by,
  creation_date,
  exchange_date,
  exchange_rate,
  exchange_rate_type,
  last_update_date,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  last_updated_by,
  prv_stat_cash_receipt_hist_id,
  created_from,
  reversal_created_from,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  org_id,
  MRC_POSTING_CONTROL_ID,
  note_status,
  mrc_gl_posted_date,
  mrc_reversal_gl_posted_date,
  mrc_acctd_amount,
  mrc_acctd_factor_disc_amount,
  mrc_exchange_date,
  mrc_exchange_rate,
  mrc_exchange_rate_type,
  event_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.AR_CASH_RECEIPT_HISTORY_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ar_cash_receipt_history_all';