DROP TABLE IF EXISTS silver_bec_ods.wsh_deliverables_v;
CREATE TABLE IF NOT EXISTS silver_bec_ods.wsh_deliverables_v (
  trip_id DECIMAL(15, 0),
  stop_id DECIMAL(15, 0),
  `type` STRING,
  delivery_detail_id DECIMAL(15, 0),
  delivery_line_id DECIMAL(15, 0),
  container_instance_id DECIMAL(15, 0),
  container_name STRING,
  delivery_id DECIMAL(15, 0),
  source_code STRING,
  source_name STRING,
  source_header_id DECIMAL(15, 0),
  source_line_id DECIMAL(15, 0),
  source_header_number STRING,
  source_header_type_id DECIMAL(15, 0),
  source_header_type_name STRING,
  source_line_number STRING,
  src_requested_quantity DECIMAL(28, 10),
  src_requested_quantity_uom STRING,
  customer_id DECIMAL(15, 0),
  sold_to_contact_id DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  item_description STRING,
  country_of_origin STRING,
  classification STRING,
  ship_from_location_id DECIMAL(15, 0),
  ship_to_location_id DECIMAL(15, 0),
  ship_to_contact_id DECIMAL(15, 0),
  deliver_to_location_id DECIMAL(15, 0),
  deliver_to_contact_id DECIMAL(15, 0),
  intmed_ship_to_location_id DECIMAL(15, 0),
  intmed_ship_to_contact_id DECIMAL(15, 0),
  ship_tolerance_above DECIMAL(28, 10),
  ship_tolerance_below DECIMAL(28, 10),
  requested_quantity DECIMAL(28, 10),
  shipped_quantity DECIMAL(28, 10),
  delivered_quantity DECIMAL(28, 10),
  cancelled_quantity DECIMAL(28, 10),
  requested_quantity_uom STRING,
  subinventory STRING,
  revision STRING,
  lot_number STRING,
  customer_requested_lot_flag STRING,
  serial_number STRING,
  locator_id DECIMAL(15, 0),
  date_requested TIMESTAMP,
  date_scheduled TIMESTAMP,
  master_container_item_id DECIMAL(15, 0),
  detail_container_item_id DECIMAL(15, 0),
  load_seq_number DECIMAL(15, 0),
  ship_method_code STRING,
  carrier_id DECIMAL(15, 0),
  freight_terms_code STRING,
  shipment_priority_code STRING,
  fob_code STRING,
  customer_item_id DECIMAL(15, 0),
  dep_plan_required_flag STRING,
  customer_prod_seq STRING,
  customer_dock_code STRING,
  unit_weight DECIMAL(28, 10),
  unit_volume DECIMAL(28, 10),
  wv_frozen_flag STRING,
  gross_weight DECIMAL(28, 10),
  tare_weight DECIMAL(28, 10),
  net_weight DECIMAL(28, 10),
  weight_uom_code STRING,
  filled_volume DECIMAL(28, 10),
  volume DECIMAL(28, 10),
  volume_uom_code STRING,
  fill_percent DECIMAL(28, 10),
  maximum_load_weight DECIMAL(28, 10),
  maximum_volume DECIMAL(28, 10),
  minimum_fill_percent DECIMAL(28, 10),
  mvt_stat_status STRING,
  released_status STRING,
  released_status_name STRING,
  organization_id DECIMAL(15, 0),
  transaction_temp_id DECIMAL(15, 0),
  ship_set_id DECIMAL(15, 0),
  arrival_set_id DECIMAL(15, 0),
  ship_model_complete_flag STRING,
  top_model_line_id DECIMAL(15, 0),
  hold_code STRING,
  cust_po_number STRING,
  ato_line_id DECIMAL(15, 0),
  move_order_line_id DECIMAL(15, 0),
  hazard_class_id DECIMAL(15, 0),
  quality_control_quantity DECIMAL(28, 10),
  cycle_count_quantity DECIMAL(28, 10),
  tracking_number STRING,
  movement_id DECIMAL(15, 0),
  shipping_instructions STRING,
  packing_instructions STRING,
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  oe_interfaced_flag STRING,
  split_from_delivery_detail_id DECIMAL(15, 0),
  inv_interfaced_flag STRING,
  parent_container_instance_id DECIMAL(15, 0),
  master_serial_number STRING,
  container_flag STRING,
  container_type_code STRING,
  seal_code STRING,
  activity_code STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  tp_attribute_category STRING,
  tp_attribute1 STRING,
  tp_attribute2 STRING,
  tp_attribute3 STRING,
  tp_attribute4 STRING,
  tp_attribute5 STRING,
  tp_attribute6 STRING,
  tp_attribute7 STRING,
  tp_attribute8 STRING,
  tp_attribute9 STRING,
  tp_attribute10 STRING,
  tp_attribute11 STRING,
  tp_attribute12 STRING,
  tp_attribute13 STRING,
  tp_attribute14 STRING,
  tp_attribute15 STRING,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  preferred_grade STRING,
  shipped_quantity2 DECIMAL(28, 10),
  delivered_quantity2 DECIMAL(28, 10),
  cancelled_quantity2 DECIMAL(28, 10),
  requested_quantity2 DECIMAL(28, 10),
  requested_quantity_uom2 STRING,
  src_requested_quantity2 DECIMAL(28, 10),
  src_requested_quantity_uom2 STRING,
  quality_control_quantity2 DECIMAL(28, 10),
  cycle_count_quantity2 DECIMAL(28, 10),
  unit_number STRING,
  unit_price DECIMAL(28, 10),
  currency_code STRING,
  freight_class_cat_id DECIMAL(15, 0),
  commodity_code_cat_id DECIMAL(15, 0),
  inspection_flag STRING,
  pickable_flag STRING,
  ship_to_site_use_id DECIMAL(15, 0),
  deliver_to_site_use_id DECIMAL(15, 0),
  to_serial_number STRING,
  picked_quantity DECIMAL(28, 10),
  picked_quantity2 DECIMAL(28, 10),
  customer_production_line STRING,
  customer_job STRING,
  cust_model_serial_number STRING,
  received_quantity DECIMAL(28, 10),
  received_quantity2 DECIMAL(28, 10),
  source_line_set_id DECIMAL(15, 0),
  batch_id DECIMAL(15, 0),
  shipment_batch_id DECIMAL(15, 0),
  lpn_id DECIMAL(15, 0),
  original_subinventory STRING,
  service_level STRING,
  mode_of_transport STRING,
  ignore_for_planning STRING,
  LINE_DIRECTION STRING,
  party_id DECIMAL(15, 0),
  routing_req_id DECIMAL(15, 0),
  shipping_control STRING,
  source_blanket_reference_id DECIMAL(15, 0),
  source_blanket_reference_num DECIMAL(28, 10),
  po_shipment_line_id DECIMAL(15, 0),
  po_shipment_line_number DECIMAL(28, 10),
  returned_quantity DECIMAL(28, 10),
  returned_quantity2 DECIMAL(28, 10),
  source_line_type_code STRING,
  rcv_shipment_line_id DECIMAL(15, 0),
  supplier_item_number STRING,
  vendor_id DECIMAL(15, 0),
  ship_from_site_id DECIMAL(15, 0),
  earliest_pickup_date TIMESTAMP,
  latest_pickup_date TIMESTAMP,
  earliest_dropoff_date TIMESTAMP,
  latest_dropoff_date TIMESTAMP,
  request_date_type_code STRING,
  tp_delivery_detail_id DECIMAL(15, 0),
  source_document_type_id DECIMAL(15, 0),
  po_revision_number DECIMAL(28, 10),
  release_revision_number DECIMAL(28, 10),
  replenishment_status STRING,
  reference_number STRING,
  reference_line_number STRING,
  reference_line_quantity DECIMAL(28, 10),
  reference_line_quantity_uom STRING,
  original_locator_id DECIMAL(15, 0),
  original_revision STRING,
  original_lot_number STRING,
  client_id DECIMAL(15, 0),
  consignee_flag STRING,
  equipment_id DECIMAL(15, 0),
  mcc_code STRING,
  tms_sub_batch_id DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.wsh_deliverables_v (
  trip_id,
  stop_id,
  `type`,
  delivery_detail_id,
  delivery_line_id,
  container_instance_id,
  container_name,
  delivery_id,
  source_code,
  source_name,
  source_header_id,
  source_line_id,
  source_header_number,
  source_header_type_id,
  source_header_type_name,
  source_line_number,
  src_requested_quantity,
  src_requested_quantity_uom,
  customer_id,
  sold_to_contact_id,
  inventory_item_id,
  item_description,
  country_of_origin,
  classification,
  ship_from_location_id,
  ship_to_location_id,
  ship_to_contact_id,
  deliver_to_location_id,
  deliver_to_contact_id,
  intmed_ship_to_location_id,
  intmed_ship_to_contact_id,
  ship_tolerance_above,
  ship_tolerance_below,
  requested_quantity,
  shipped_quantity,
  delivered_quantity,
  cancelled_quantity,
  requested_quantity_uom,
  subinventory,
  revision,
  lot_number,
  customer_requested_lot_flag,
  serial_number,
  locator_id,
  date_requested,
  date_scheduled,
  master_container_item_id,
  detail_container_item_id,
  load_seq_number,
  ship_method_code,
  carrier_id,
  freight_terms_code,
  shipment_priority_code,
  fob_code,
  customer_item_id,
  dep_plan_required_flag,
  customer_prod_seq,
  customer_dock_code,
  unit_weight,
  unit_volume,
  wv_frozen_flag,
  gross_weight,
  tare_weight,
  net_weight,
  weight_uom_code,
  filled_volume,
  volume,
  volume_uom_code,
  fill_percent,
  maximum_load_weight,
  maximum_volume,
  minimum_fill_percent,
  mvt_stat_status,
  released_status,
  released_status_name,
  organization_id,
  transaction_temp_id,
  ship_set_id,
  arrival_set_id,
  ship_model_complete_flag,
  top_model_line_id,
  hold_code,
  cust_po_number,
  ato_line_id,
  move_order_line_id,
  hazard_class_id,
  quality_control_quantity,
  cycle_count_quantity,
  tracking_number,
  movement_id,
  shipping_instructions,
  packing_instructions,
  project_id,
  task_id,
  org_id,
  oe_interfaced_flag,
  split_from_delivery_detail_id,
  inv_interfaced_flag,
  parent_container_instance_id,
  master_serial_number,
  container_flag,
  container_type_code,
  seal_code,
  activity_code,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  tp_attribute_category,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  preferred_grade,
  shipped_quantity2,
  delivered_quantity2,
  cancelled_quantity2,
  requested_quantity2,
  requested_quantity_uom2,
  src_requested_quantity2,
  src_requested_quantity_uom2,
  quality_control_quantity2,
  cycle_count_quantity2,
  unit_number,
  unit_price,
  currency_code,
  freight_class_cat_id,
  commodity_code_cat_id,
  inspection_flag,
  pickable_flag,
  ship_to_site_use_id,
  deliver_to_site_use_id,
  to_serial_number,
  picked_quantity,
  picked_quantity2,
  customer_production_line,
  customer_job,
  cust_model_serial_number,
  received_quantity,
  received_quantity2,
  source_line_set_id,
  batch_id,
  shipment_batch_id,
  lpn_id,
  original_subinventory,
  service_level,
  mode_of_transport,
  ignore_for_planning,
  LINE_DIRECTION,
  party_id,
  routing_req_id,
  shipping_control,
  source_blanket_reference_id,
  source_blanket_reference_num,
  po_shipment_line_id,
  po_shipment_line_number,
  returned_quantity,
  returned_quantity2,
  source_line_type_code,
  rcv_shipment_line_id,
  supplier_item_number,
  vendor_id,
  ship_from_site_id,
  earliest_pickup_date,
  latest_pickup_date,
  earliest_dropoff_date,
  latest_dropoff_date,
  request_date_type_code,
  tp_delivery_detail_id,
  source_document_type_id,
  po_revision_number,
  release_revision_number,
  replenishment_status,
  reference_number,
  reference_line_number,
  reference_line_quantity,
  reference_line_quantity_uom,
  original_locator_id,
  original_revision,
  original_lot_number,
  client_id,
  consignee_flag,
  equipment_id,
  mcc_code,
  tms_sub_batch_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  trip_id,
  stop_id,
  `type`,
  delivery_detail_id,
  delivery_line_id,
  container_instance_id,
  container_name,
  delivery_id,
  source_code,
  source_name,
  source_header_id,
  source_line_id,
  source_header_number,
  source_header_type_id,
  source_header_type_name,
  source_line_number,
  src_requested_quantity,
  src_requested_quantity_uom,
  customer_id,
  sold_to_contact_id,
  inventory_item_id,
  item_description,
  country_of_origin,
  classification,
  ship_from_location_id,
  ship_to_location_id,
  ship_to_contact_id,
  deliver_to_location_id,
  deliver_to_contact_id,
  intmed_ship_to_location_id,
  intmed_ship_to_contact_id,
  ship_tolerance_above,
  ship_tolerance_below,
  requested_quantity,
  shipped_quantity,
  delivered_quantity,
  cancelled_quantity,
  requested_quantity_uom,
  subinventory,
  revision,
  lot_number,
  customer_requested_lot_flag,
  serial_number,
  locator_id,
  date_requested,
  date_scheduled,
  master_container_item_id,
  detail_container_item_id,
  load_seq_number,
  ship_method_code,
  carrier_id,
  freight_terms_code,
  shipment_priority_code,
  fob_code,
  customer_item_id,
  dep_plan_required_flag,
  customer_prod_seq,
  customer_dock_code,
  unit_weight,
  unit_volume,
  wv_frozen_flag,
  gross_weight,
  tare_weight,
  net_weight,
  weight_uom_code,
  filled_volume,
  volume,
  volume_uom_code,
  fill_percent,
  maximum_load_weight,
  maximum_volume,
  minimum_fill_percent,
  mvt_stat_status,
  released_status,
  released_status_name,
  organization_id,
  transaction_temp_id,
  ship_set_id,
  arrival_set_id,
  ship_model_complete_flag,
  top_model_line_id,
  hold_code,
  cust_po_number,
  ato_line_id,
  move_order_line_id,
  hazard_class_id,
  quality_control_quantity,
  cycle_count_quantity,
  tracking_number,
  movement_id,
  shipping_instructions,
  packing_instructions,
  project_id,
  task_id,
  org_id,
  oe_interfaced_flag,
  split_from_delivery_detail_id,
  inv_interfaced_flag,
  parent_container_instance_id,
  master_serial_number,
  container_flag,
  container_type_code,
  seal_code,
  activity_code,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  tp_attribute_category,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  preferred_grade,
  shipped_quantity2,
  delivered_quantity2,
  cancelled_quantity2,
  requested_quantity2,
  requested_quantity_uom2,
  src_requested_quantity2,
  src_requested_quantity_uom2,
  quality_control_quantity2,
  cycle_count_quantity2,
  unit_number,
  unit_price,
  currency_code,
  freight_class_cat_id,
  commodity_code_cat_id,
  inspection_flag,
  pickable_flag,
  ship_to_site_use_id,
  deliver_to_site_use_id,
  to_serial_number,
  picked_quantity,
  picked_quantity2,
  customer_production_line,
  customer_job,
  cust_model_serial_number,
  received_quantity,
  received_quantity2,
  source_line_set_id,
  batch_id,
  shipment_batch_id,
  lpn_id,
  original_subinventory,
  service_level,
  mode_of_transport,
  ignore_for_planning,
  LINE_DIRECTION,
  party_id,
  routing_req_id,
  shipping_control,
  source_blanket_reference_id,
  source_blanket_reference_num,
  po_shipment_line_id,
  po_shipment_line_number,
  returned_quantity,
  returned_quantity2,
  source_line_type_code,
  rcv_shipment_line_id,
  supplier_item_number,
  vendor_id,
  ship_from_site_id,
  earliest_pickup_date,
  latest_pickup_date,
  earliest_dropoff_date,
  latest_dropoff_date,
  request_date_type_code,
  tp_delivery_detail_id,
  source_document_type_id,
  po_revision_number,
  release_revision_number,
  replenishment_status,
  reference_number,
  reference_line_number,
  reference_line_quantity,
  reference_line_quantity_uom,
  original_locator_id,
  original_revision,
  original_lot_number,
  client_id,
  consignee_flag,
  equipment_id,
  mcc_code,
  tms_sub_batch_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.wsh_deliverables_v;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wsh_deliverables_v';