DROP TABLE IF EXISTS silver_bec_ods.MTL_TXN_REQUEST_HEADERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_TXN_REQUEST_HEADERS (
  header_id DECIMAL(15, 0),
  request_number STRING,
  transaction_type_id DECIMAL(15, 0),
  move_order_type DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  description STRING,
  date_required TIMESTAMP,
  from_subinventory_code STRING,
  to_subinventory_code STRING,
  to_account_id DECIMAL(15, 0),
  header_status DECIMAL(15, 0),
  status_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  grouping_rule_id DECIMAL(15, 0),
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute_category STRING,
  ship_to_location_id DECIMAL(15, 0),
  freight_code STRING,
  shipment_method STRING,
  auto_receipt_flag STRING,
  reference_id DECIMAL(15, 0),
  reference_detail_id DECIMAL(15, 0),
  assignment_id STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_TXN_REQUEST_HEADERS (
  header_id,
  request_number,
  transaction_type_id,
  move_order_type,
  organization_id,
  description,
  date_required,
  from_subinventory_code,
  to_subinventory_code,
  to_account_id,
  header_status,
  status_date,
  last_updated_by,
  last_update_login,
  last_update_date,
  created_by,
  creation_date,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  grouping_rule_id,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  ship_to_location_id,
  freight_code,
  shipment_method,
  auto_receipt_flag,
  reference_id,
  reference_detail_id,
  assignment_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  header_id,
  request_number,
  transaction_type_id,
  move_order_type,
  organization_id,
  description,
  date_required,
  from_subinventory_code,
  to_subinventory_code,
  to_account_id,
  header_status,
  status_date,
  last_updated_by,
  last_update_login,
  last_update_date,
  created_by,
  creation_date,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  grouping_rule_id,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  ship_to_location_id,
  freight_code,
  shipment_method,
  auto_receipt_flag,
  reference_id,
  reference_detail_id,
  assignment_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_TXN_REQUEST_HEADERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_txn_request_headers';