DROP TABLE IF EXISTS silver_bec_ods.WSH_DELIVERY_DETAILS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.WSH_DELIVERY_DETAILS (
  delivery_detail_id DECIMAL(15, 0),
  source_code STRING,
  source_header_id DECIMAL(15, 0),
  source_line_id DECIMAL(15, 0),
  source_header_type_id DECIMAL(15, 0),
  source_header_type_name STRING,
  cust_po_number STRING,
  customer_id DECIMAL(15, 0),
  sold_to_contact_id DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  item_description STRING,
  ship_set_id DECIMAL(15, 0),
  arrival_set_id DECIMAL(15, 0),
  top_model_line_id DECIMAL(15, 0),
  ato_line_id DECIMAL(15, 0),
  hold_code STRING,
  ship_model_complete_flag STRING,
  hazard_class_id DECIMAL(15, 0),
  country_of_origin STRING,
  classification STRING,
  ship_from_location_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  ship_to_location_id DECIMAL(15, 0),
  ship_to_contact_id DECIMAL(15, 0),
  deliver_to_location_id DECIMAL(15, 0),
  deliver_to_contact_id DECIMAL(15, 0),
  intmed_ship_to_location_id DECIMAL(15, 0),
  intmed_ship_to_contact_id DECIMAL(15, 0),
  ship_tolerance_above DECIMAL(28, 10),
  ship_tolerance_below DECIMAL(28, 10),
  src_requested_quantity DECIMAL(28, 10),
  src_requested_quantity_uom STRING,
  cancelled_quantity DECIMAL(28, 10),
  requested_quantity DECIMAL(28, 10),
  requested_quantity_uom STRING,
  shipped_quantity DECIMAL(28, 10),
  delivered_quantity DECIMAL(28, 10),
  quality_control_quantity DECIMAL(28, 10),
  cycle_count_quantity DECIMAL(28, 10),
  move_order_line_id DECIMAL(15, 0),
  subinventory STRING,
  revision STRING,
  lot_number STRING,
  released_status STRING,
  customer_requested_lot_flag STRING,
  serial_number STRING,
  locator_id DECIMAL(15, 0),
  date_requested TIMESTAMP,
  date_scheduled TIMESTAMP,
  master_container_item_id DECIMAL(15, 0),
  detail_container_item_id DECIMAL(15, 0),
  load_seq_number DECIMAL(15, 0),
  ship_method_code STRING,
  carrier_id DECIMAL(15, 0),
  freight_terms_code STRING,
  shipment_priority_code STRING,
  fob_code STRING,
  customer_item_id DECIMAL(15, 0),
  dep_plan_required_flag STRING,
  customer_prod_seq STRING,
  customer_dock_code STRING,
  net_weight DECIMAL(28, 10),
  weight_uom_code STRING,
  volume DECIMAL(28, 10),
  volume_uom_code STRING,
  shipping_instructions STRING,
  packing_instructions STRING,
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  org_id DECIMAL(15, 0),
  oe_interfaced_flag STRING,
  mvt_stat_status STRING,
  tracking_number STRING,
  transaction_temp_id DECIMAL(15, 0),
  tp_attribute_category STRING,
  tp_attribute1 STRING,
  tp_attribute2 STRING,
  tp_attribute3 STRING,
  tp_attribute4 STRING,
  tp_attribute5 STRING,
  tp_attribute6 STRING,
  tp_attribute7 STRING,
  tp_attribute8 STRING,
  tp_attribute9 STRING,
  tp_attribute10 STRING,
  tp_attribute11 STRING,
  tp_attribute12 STRING,
  tp_attribute13 STRING,
  tp_attribute14 STRING,
  tp_attribute15 STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  movement_id DECIMAL(15, 0),
  split_from_delivery_detail_id DECIMAL(15, 0),
  inv_interfaced_flag STRING,
  seal_code STRING,
  minimum_fill_percent DECIMAL(28, 10),
  maximum_volume DECIMAL(28, 10),
  maximum_load_weight DECIMAL(28, 10),
  master_serial_number STRING,
  gross_weight DECIMAL(28, 10),
  fill_percent DECIMAL(28, 10),
  container_name STRING,
  container_type_code STRING,
  container_flag STRING,
  preferred_grade STRING,
  src_requested_quantity2 DECIMAL(28, 10),
  src_requested_quantity_uom2 STRING,
  requested_quantity2 DECIMAL(28, 10),
  shipped_quantity2 DECIMAL(28, 10),
  delivered_quantity2 DECIMAL(28, 10),
  cancelled_quantity2 DECIMAL(28, 10),
  quality_control_quantity2 DECIMAL(28, 10),
  cycle_count_quantity2 DECIMAL(28, 10),
  requested_quantity_uom2 STRING,
  sublot_number STRING,
  unit_price DECIMAL(28, 10),
  currency_code STRING,
  unit_number STRING,
  freight_class_cat_id DECIMAL(15, 0),
  commodity_code_cat_id DECIMAL(15, 0),
  lpn_content_id DECIMAL(15, 0),
  ship_to_site_use_id DECIMAL(15, 0),
  deliver_to_site_use_id DECIMAL(15, 0),
  lpn_id DECIMAL(15, 0),
  inspection_flag STRING,
  original_subinventory STRING,
  source_header_number STRING,
  source_line_number STRING,
  pickable_flag STRING,
  customer_production_line STRING,
  customer_job STRING,
  cust_model_serial_number STRING,
  to_serial_number STRING,
  picked_quantity DECIMAL(28, 10),
  picked_quantity2 DECIMAL(28, 10),
  received_quantity DECIMAL(28, 10),
  received_quantity2 DECIMAL(28, 10),
  source_line_set_id DECIMAL(15, 0),
  batch_id DECIMAL(15, 0),
  transaction_id DECIMAL(15, 0),
  service_level STRING,
  mode_of_transport STRING,
  earliest_pickup_date TIMESTAMP,
  latest_pickup_date TIMESTAMP,
  earliest_dropoff_date TIMESTAMP,
  latest_dropoff_date TIMESTAMP,
  request_date_type_code STRING,
  tp_delivery_detail_id DECIMAL(15, 0),
  source_document_type_id DECIMAL(15, 0),
  vendor_id DECIMAL(15, 0),
  ship_from_site_id DECIMAL(15, 0),
  ignore_for_planning STRING,
  line_direction STRING,
  party_id DECIMAL(15, 0),
  routing_req_id DECIMAL(15, 0),
  shipping_control STRING,
  source_blanket_reference_id DECIMAL(15, 0),
  source_blanket_reference_num DECIMAL(28, 10),
  po_shipment_line_id DECIMAL(15, 0),
  po_shipment_line_number DECIMAL(28, 10),
  scheduled_quantity DECIMAL(28, 10),
  returned_quantity DECIMAL(28, 10),
  scheduled_quantity2 DECIMAL(28, 10),
  returned_quantity2 DECIMAL(28, 10),
  source_line_type_code STRING,
  rcv_shipment_line_id DECIMAL(15, 0),
  supplier_item_number STRING,
  filled_volume DECIMAL(28, 10),
  unit_weight DECIMAL(28, 10),
  unit_volume DECIMAL(28, 10),
  wv_frozen_flag STRING,
  po_revision_number DECIMAL(28, 10),
  release_revision_number DECIMAL(28, 10),
  replenishment_status STRING,
  original_lot_number STRING,
  original_revision STRING,
  original_locator_id DECIMAL(15, 0),
  reference_number STRING,
  reference_line_number STRING,
  reference_line_quantity DECIMAL(28, 10),
  reference_line_quantity_uom STRING,
  client_id DECIMAL(15, 0),
  shipment_batch_id DECIMAL(15, 0),
  shipment_line_number DECIMAL(15, 0),
  reference_line_id DECIMAL(15, 0),
  consignee_flag STRING,
  equipment_id DECIMAL(15, 0),
  mcc_code STRING,
  tms_sub_batch_id DECIMAL(15, 0),
  tms_sub_batch_line_num DECIMAL(15, 0),
  tms_interface_flag STRING,
  tms_sshipunit_id STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.WSH_DELIVERY_DETAILS (
  delivery_detail_id,
  source_code,
  source_header_id,
  source_line_id,
  source_header_type_id,
  source_header_type_name,
  cust_po_number,
  customer_id,
  sold_to_contact_id,
  inventory_item_id,
  item_description,
  ship_set_id,
  arrival_set_id,
  top_model_line_id,
  ato_line_id,
  hold_code,
  ship_model_complete_flag,
  hazard_class_id,
  country_of_origin,
  classification,
  ship_from_location_id,
  organization_id,
  ship_to_location_id,
  ship_to_contact_id,
  deliver_to_location_id,
  deliver_to_contact_id,
  intmed_ship_to_location_id,
  intmed_ship_to_contact_id,
  ship_tolerance_above,
  ship_tolerance_below,
  src_requested_quantity,
  src_requested_quantity_uom,
  cancelled_quantity,
  requested_quantity,
  requested_quantity_uom,
  shipped_quantity,
  delivered_quantity,
  quality_control_quantity,
  cycle_count_quantity,
  move_order_line_id,
  subinventory,
  revision,
  lot_number,
  released_status,
  customer_requested_lot_flag,
  serial_number,
  locator_id,
  date_requested,
  date_scheduled,
  master_container_item_id,
  detail_container_item_id,
  load_seq_number,
  ship_method_code,
  carrier_id,
  freight_terms_code,
  shipment_priority_code,
  fob_code,
  customer_item_id,
  dep_plan_required_flag,
  customer_prod_seq,
  customer_dock_code,
  net_weight,
  weight_uom_code,
  volume,
  volume_uom_code,
  shipping_instructions,
  packing_instructions,
  project_id,
  task_id,
  org_id,
  oe_interfaced_flag,
  mvt_stat_status,
  tracking_number,
  transaction_temp_id,
  tp_attribute_category,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  movement_id,
  split_from_delivery_detail_id,
  inv_interfaced_flag,
  seal_code,
  minimum_fill_percent,
  maximum_volume,
  maximum_load_weight,
  master_serial_number,
  gross_weight,
  fill_percent,
  container_name,
  container_type_code,
  container_flag,
  preferred_grade,
  src_requested_quantity2,
  src_requested_quantity_uom2,
  requested_quantity2,
  shipped_quantity2,
  delivered_quantity2,
  cancelled_quantity2,
  quality_control_quantity2,
  cycle_count_quantity2,
  requested_quantity_uom2,
  sublot_number,
  unit_price,
  currency_code,
  unit_number,
  freight_class_cat_id,
  commodity_code_cat_id,
  lpn_content_id,
  ship_to_site_use_id,
  deliver_to_site_use_id,
  lpn_id,
  inspection_flag,
  original_subinventory,
  source_header_number,
  source_line_number,
  pickable_flag,
  customer_production_line,
  customer_job,
  cust_model_serial_number,
  to_serial_number,
  picked_quantity,
  picked_quantity2,
  received_quantity,
  received_quantity2,
  source_line_set_id,
  batch_id,
  transaction_id,
  service_level,
  mode_of_transport,
  earliest_pickup_date,
  latest_pickup_date,
  earliest_dropoff_date,
  latest_dropoff_date,
  request_date_type_code,
  tp_delivery_detail_id,
  source_document_type_id,
  vendor_id,
  ship_from_site_id,
  ignore_for_planning,
  line_direction,
  party_id,
  routing_req_id,
  shipping_control,
  source_blanket_reference_id,
  source_blanket_reference_num,
  po_shipment_line_id,
  po_shipment_line_number,
  scheduled_quantity,
  returned_quantity,
  scheduled_quantity2,
  returned_quantity2,
  source_line_type_code,
  rcv_shipment_line_id,
  supplier_item_number,
  filled_volume,
  unit_weight,
  unit_volume,
  wv_frozen_flag,
  po_revision_number,
  release_revision_number,
  replenishment_status,
  original_lot_number,
  original_revision,
  original_locator_id,
  reference_number,
  reference_line_number,
  reference_line_quantity,
  reference_line_quantity_uom,
  client_id,
  shipment_batch_id,
  shipment_line_number,
  reference_line_id,
  consignee_flag,
  equipment_id,
  mcc_code,
  tms_sub_batch_id,
  tms_sub_batch_line_num,
  tms_interface_flag,
  tms_sshipunit_id,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  delivery_detail_id,
  source_code,
  source_header_id,
  source_line_id,
  source_header_type_id,
  source_header_type_name,
  cust_po_number,
  customer_id,
  sold_to_contact_id,
  inventory_item_id,
  item_description,
  ship_set_id,
  arrival_set_id,
  top_model_line_id,
  ato_line_id,
  hold_code,
  ship_model_complete_flag,
  hazard_class_id,
  country_of_origin,
  classification,
  ship_from_location_id,
  organization_id,
  ship_to_location_id,
  ship_to_contact_id,
  deliver_to_location_id,
  deliver_to_contact_id,
  intmed_ship_to_location_id,
  intmed_ship_to_contact_id,
  ship_tolerance_above,
  ship_tolerance_below,
  src_requested_quantity,
  src_requested_quantity_uom,
  cancelled_quantity,
  requested_quantity,
  requested_quantity_uom,
  shipped_quantity,
  delivered_quantity,
  quality_control_quantity,
  cycle_count_quantity,
  move_order_line_id,
  subinventory,
  revision,
  lot_number,
  released_status,
  customer_requested_lot_flag,
  serial_number,
  locator_id,
  date_requested,
  date_scheduled,
  master_container_item_id,
  detail_container_item_id,
  load_seq_number,
  ship_method_code,
  carrier_id,
  freight_terms_code,
  shipment_priority_code,
  fob_code,
  customer_item_id,
  dep_plan_required_flag,
  customer_prod_seq,
  customer_dock_code,
  net_weight,
  weight_uom_code,
  volume,
  volume_uom_code,
  shipping_instructions,
  packing_instructions,
  project_id,
  task_id,
  org_id,
  oe_interfaced_flag,
  mvt_stat_status,
  tracking_number,
  transaction_temp_id,
  tp_attribute_category,
  tp_attribute1,
  tp_attribute2,
  tp_attribute3,
  tp_attribute4,
  tp_attribute5,
  tp_attribute6,
  tp_attribute7,
  tp_attribute8,
  tp_attribute9,
  tp_attribute10,
  tp_attribute11,
  tp_attribute12,
  tp_attribute13,
  tp_attribute14,
  tp_attribute15,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  creation_date,
  created_by,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  movement_id,
  split_from_delivery_detail_id,
  inv_interfaced_flag,
  seal_code,
  minimum_fill_percent,
  maximum_volume,
  maximum_load_weight,
  master_serial_number,
  gross_weight,
  fill_percent,
  container_name,
  container_type_code,
  container_flag,
  preferred_grade,
  src_requested_quantity2,
  src_requested_quantity_uom2,
  requested_quantity2,
  shipped_quantity2,
  delivered_quantity2,
  cancelled_quantity2,
  quality_control_quantity2,
  cycle_count_quantity2,
  requested_quantity_uom2,
  sublot_number,
  unit_price,
  currency_code,
  unit_number,
  freight_class_cat_id,
  commodity_code_cat_id,
  lpn_content_id,
  ship_to_site_use_id,
  deliver_to_site_use_id,
  lpn_id,
  inspection_flag,
  original_subinventory,
  source_header_number,
  source_line_number,
  pickable_flag,
  customer_production_line,
  customer_job,
  cust_model_serial_number,
  to_serial_number,
  picked_quantity,
  picked_quantity2,
  received_quantity,
  received_quantity2,
  source_line_set_id,
  batch_id,
  transaction_id,
  service_level,
  mode_of_transport,
  earliest_pickup_date,
  latest_pickup_date,
  earliest_dropoff_date,
  latest_dropoff_date,
  request_date_type_code,
  tp_delivery_detail_id,
  source_document_type_id,
  vendor_id,
  ship_from_site_id,
  ignore_for_planning,
  line_direction,
  party_id,
  routing_req_id,
  shipping_control,
  source_blanket_reference_id,
  source_blanket_reference_num,
  po_shipment_line_id,
  po_shipment_line_number,
  scheduled_quantity,
  returned_quantity,
  scheduled_quantity2,
  returned_quantity2,
  source_line_type_code,
  rcv_shipment_line_id,
  supplier_item_number,
  filled_volume,
  unit_weight,
  unit_volume,
  wv_frozen_flag,
  po_revision_number,
  release_revision_number,
  replenishment_status,
  original_lot_number,
  original_revision,
  original_locator_id,
  reference_number,
  reference_line_number,
  reference_line_quantity,
  reference_line_quantity_uom,
  client_id,
  shipment_batch_id,
  shipment_line_number,
  reference_line_id,
  consignee_flag,
  equipment_id,
  mcc_code,
  tms_sub_batch_id,
  tms_sub_batch_line_num,
  tms_interface_flag,
  tms_sshipunit_id,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.WSH_DELIVERY_DETAILS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wsh_delivery_details';