DROP TABLE IF EXISTS silver_bec_ods.BOM_COMPONENTS_B;
CREATE TABLE IF NOT EXISTS silver_bec_ods.BOM_COMPONENTS_B (
  operation_seq_num DECIMAL(15, 0),
  component_item_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  item_num DECIMAL(15, 0),
  component_quantity DECIMAL(28, 10),
  component_yield_factor DECIMAL(28, 10),
  component_remarks STRING,
  effectivity_date TIMESTAMP,
  change_notice STRING,
  implementation_date TIMESTAMP,
  disable_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  planning_factor DECIMAL(15, 0),
  quantity_related DECIMAL(15, 0),
  so_basis DECIMAL(15, 0),
  optional DECIMAL(15, 0),
  mutually_exclusive_options DECIMAL(15, 0),
  include_in_cost_rollup DECIMAL(15, 0),
  check_atp DECIMAL(15, 0),
  shipping_allowed DECIMAL(15, 0),
  required_to_ship DECIMAL(15, 0),
  required_for_revenue DECIMAL(15, 0),
  include_on_ship_docs DECIMAL(15, 0),
  include_on_bill_docs DECIMAL(15, 0),
  low_quantity DECIMAL(15, 0),
  high_quantity DECIMAL(15, 0),
  acd_type DECIMAL(15, 0),
  old_component_sequence_id DECIMAL(15, 0),
  component_sequence_id DECIMAL(15, 0),
  bill_sequence_id DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  wip_supply_type DECIMAL(15, 0),
  pick_components DECIMAL(15, 0),
  supply_subinventory STRING,
  supply_locator_id DECIMAL(15, 0),
  operation_lead_time_percent DECIMAL(28, 10),
  revised_item_sequence_id DECIMAL(15, 0),
  cost_factor DECIMAL(28, 10),
  bom_item_type DECIMAL(15, 0),
  from_end_item_unit_number STRING,
  to_end_item_unit_number STRING,
  original_system_reference STRING,
  eco_for_production DECIMAL(15, 0),
  enforce_int_requirements DECIMAL(15, 0),
  component_item_revision_id DECIMAL(15, 0),
  delete_group_name STRING,
  dg_description STRING,
  optional_on_model DECIMAL(15, 0),
  parent_bill_seq_id DECIMAL(15, 0),
  model_comp_seq_id DECIMAL(15, 0),
  plan_level DECIMAL(15, 0),
  from_bill_revision_id DECIMAL(15, 0),
  to_bill_revision_id DECIMAL(15, 0),
  auto_request_material STRING,
  suggested_vendor_name STRING,
  vendor_id DECIMAL(15, 0),
  unit_price DECIMAL(28, 10),
  obj_name STRING,
  pk1_value STRING,
  pk2_value STRING,
  pk3_value STRING,
  pk4_value STRING,
  pk5_value STRING,
  from_end_item_rev_id DECIMAL(15, 0),
  to_end_item_rev_id DECIMAL(15, 0),
  overlapping_changes DECIMAL(15, 0),
  from_object_revision_id DECIMAL(15, 0),
  from_minor_revision_id DECIMAL(15, 0),
  to_object_revision_id DECIMAL(15, 0),
  to_minor_revision_id DECIMAL(15, 0),
  from_end_item_minor_rev_id DECIMAL(15, 0),
  to_end_item_minor_rev_id DECIMAL(15, 0),
  component_minor_revision_id DECIMAL(15, 0),
  from_structure_revision_code STRING,
  to_structure_revision_code STRING,
  from_end_item_strc_rev_id DECIMAL(15, 0),
  to_end_item_strc_rev_id DECIMAL(15, 0),
  basis_type DECIMAL(15, 0),
  common_component_sequence_id DECIMAL(15, 0),
  inherit_flag DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.BOM_COMPONENTS_B (
  operation_seq_num,
  component_item_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  item_num,
  component_quantity,
  component_yield_factor,
  component_remarks,
  effectivity_date,
  change_notice,
  implementation_date,
  disable_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  planning_factor,
  quantity_related,
  so_basis,
  optional,
  mutually_exclusive_options,
  include_in_cost_rollup,
  check_atp,
  shipping_allowed,
  required_to_ship,
  required_for_revenue,
  include_on_ship_docs,
  include_on_bill_docs,
  low_quantity,
  high_quantity,
  acd_type,
  old_component_sequence_id,
  component_sequence_id,
  bill_sequence_id,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wip_supply_type,
  pick_components,
  supply_subinventory,
  supply_locator_id,
  operation_lead_time_percent,
  revised_item_sequence_id,
  cost_factor,
  bom_item_type,
  from_end_item_unit_number,
  to_end_item_unit_number,
  original_system_reference,
  eco_for_production,
  enforce_int_requirements,
  component_item_revision_id,
  delete_group_name,
  dg_description,
  optional_on_model,
  parent_bill_seq_id,
  model_comp_seq_id,
  plan_level,
  from_bill_revision_id,
  to_bill_revision_id,
  auto_request_material,
  suggested_vendor_name,
  vendor_id,
  unit_price,
  obj_name,
  pk1_value,
  pk2_value,
  pk3_value,
  pk4_value,
  pk5_value,
  from_end_item_rev_id,
  to_end_item_rev_id,
  overlapping_changes,
  from_object_revision_id,
  from_minor_revision_id,
  to_object_revision_id,
  to_minor_revision_id,
  from_end_item_minor_rev_id,
  to_end_item_minor_rev_id,
  component_minor_revision_id,
  from_structure_revision_code,
  to_structure_revision_code,
  from_end_item_strc_rev_id,
  to_end_item_strc_rev_id,
  basis_type,
  common_component_sequence_id,
  inherit_flag,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  operation_seq_num,
  component_item_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  item_num,
  component_quantity,
  component_yield_factor,
  component_remarks,
  effectivity_date,
  change_notice,
  implementation_date,
  disable_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  planning_factor,
  quantity_related,
  so_basis,
  optional,
  mutually_exclusive_options,
  include_in_cost_rollup,
  check_atp,
  shipping_allowed,
  required_to_ship,
  required_for_revenue,
  include_on_ship_docs,
  include_on_bill_docs,
  low_quantity,
  high_quantity,
  acd_type,
  old_component_sequence_id,
  component_sequence_id,
  bill_sequence_id,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wip_supply_type,
  pick_components,
  supply_subinventory,
  supply_locator_id,
  operation_lead_time_percent,
  revised_item_sequence_id,
  cost_factor,
  bom_item_type,
  from_end_item_unit_number,
  to_end_item_unit_number,
  original_system_reference,
  eco_for_production,
  enforce_int_requirements,
  component_item_revision_id,
  delete_group_name,
  dg_description,
  optional_on_model,
  parent_bill_seq_id,
  model_comp_seq_id,
  plan_level,
  from_bill_revision_id,
  to_bill_revision_id,
  auto_request_material,
  suggested_vendor_name,
  vendor_id,
  unit_price,
  obj_name,
  pk1_value,
  pk2_value,
  pk3_value,
  pk4_value,
  pk5_value,
  from_end_item_rev_id,
  to_end_item_rev_id,
  overlapping_changes,
  from_object_revision_id,
  from_minor_revision_id,
  to_object_revision_id,
  to_minor_revision_id,
  from_end_item_minor_rev_id,
  to_end_item_minor_rev_id,
  component_minor_revision_id,
  from_structure_revision_code,
  to_structure_revision_code,
  from_end_item_strc_rev_id,
  to_end_item_strc_rev_id,
  basis_type,
  common_component_sequence_id,
  inherit_flag,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.BOM_COMPONENTS_B;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'bom_components_b';