DROP TABLE IF EXISTS silver_bec_ods.MTL_PHYSICAL_INVENTORIES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_PHYSICAL_INVENTORIES (
  physical_inventory_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  physical_inventory_date TIMESTAMP,
  last_adjustment_date TIMESTAMP,
  total_adjustment_value DECIMAL(28, 10),
  description STRING,
  freeze_date TIMESTAMP,
  physical_inventory_name STRING,
  approval_required DECIMAL(15, 0),
  all_subinventories_flag DECIMAL(15, 0),
  next_tag_number STRING,
  tag_number_increments STRING,
  default_gl_adjust_account DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  approval_tolerance_pos DECIMAL(15, 0),
  approval_tolerance_neg DECIMAL(15, 0),
  cost_variance_pos DECIMAL(15, 0),
  cost_variance_neg DECIMAL(15, 0),
  number_of_skus DECIMAL(15, 0),
  dynamic_tag_entry_flag DECIMAL(15, 0),
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute_category STRING,
  exclude_zero_balance STRING,
  exclude_negative_balance STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_PHYSICAL_INVENTORIES (
  physical_inventory_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  physical_inventory_date,
  last_adjustment_date,
  total_adjustment_value,
  description,
  freeze_date,
  physical_inventory_name,
  approval_required,
  all_subinventories_flag,
  next_tag_number,
  tag_number_increments,
  default_gl_adjust_account,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  approval_tolerance_pos,
  approval_tolerance_neg,
  cost_variance_pos,
  cost_variance_neg,
  number_of_skus,
  dynamic_tag_entry_flag,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  exclude_zero_balance,
  exclude_negative_balance,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  physical_inventory_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  physical_inventory_date,
  last_adjustment_date,
  total_adjustment_value,
  description,
  freeze_date,
  physical_inventory_name,
  approval_required,
  all_subinventories_flag,
  next_tag_number,
  tag_number_increments,
  default_gl_adjust_account,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  approval_tolerance_pos,
  approval_tolerance_neg,
  cost_variance_pos,
  cost_variance_neg,
  number_of_skus,
  dynamic_tag_entry_flag,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  exclude_zero_balance,
  exclude_negative_balance,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_PHYSICAL_INVENTORIES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_physical_inventories';