DROP TABLE IF EXISTS silver_bec_ods.XXBEC_RCV_MSL_V;
CREATE TABLE IF NOT EXISTS silver_bec_ods.XXBEC_RCV_MSL_V (
  source_type STRING,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  charge_account_id DECIMAL(15, 0),
  comments STRING,
  deliver_to_location_id DECIMAL(15, 0),
  deliver_to_person_id DECIMAL(15, 0),
  destination_context STRING,
  destination_type_code STRING,
  destination_type STRING,
  employee_id DECIMAL(15, 0),
  from_organization_id DECIMAL(15, 0),
  item_description STRING,
  item_id DECIMAL(15, 0),
  item_revision STRING,
  hazard_class STRING,
  un_number STRING,
  line_num DECIMAL(15, 0),
  item_category_id DECIMAL(15, 0),
  locator_id DECIMAL(15, 0),
  need_by_date TIMESTAMP,
  packing_slip STRING,
  quantity_received DECIMAL(15, 0),
  quantity_shipped DECIMAL(15, 0),
  requisition_line_id DECIMAL(15, 0),
  requisition_header_id DECIMAL(15, 0),
  order_num STRING,
  order_line_num DECIMAL(15, 0),
  req_distribution_id DECIMAL(15, 0),
  shipment_header_id DECIMAL(15, 0),
  shipment_line_id DECIMAL(15, 0),
  shipment_line_status_code STRING,
  source_document_code STRING,
  source_document_type STRING,
  to_organization_id DECIMAL(15, 0),
  to_subinventory STRING,
  transfer_cost DECIMAL(15, 0),
  transportation_account_id DECIMAL(15, 0),
  transportation_cost DECIMAL(28, 10),
  unit_of_measure STRING,
  uom_conversion_rate DECIMAL(28, 10),
  routing_header_id DECIMAL(15, 0),
  routing_name STRING,
  reason_id DECIMAL(15, 0),
  reason_name STRING,
  location_code STRING,
  deliver_to_person STRING,
  po_header_id DECIMAL(15, 0),
  po_line_id DECIMAL(15, 0),
  po_line_location_id DECIMAL(15, 0),
  po_release_id DECIMAL(15, 0),
  release_num DECIMAL(15, 0),
  vendor_name STRING,
  vendor_site_code STRING,
  ship_to_location_id DECIMAL(15, 0),
  primary_unit_of_measure STRING,
  vendor_id DECIMAL(15, 0),
  bar_code_label STRING,
  truck_num STRING,
  container_num STRING,
  vendor_lot_num STRING,
  secondary_quantity_received DECIMAL(15, 0),
  secondary_quantity_shipped DECIMAL(15, 0),
  secondary_unit_of_measure STRING,
  qc_grade STRING,
  org_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.XXBEC_RCV_MSL_V (
  source_type,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  charge_account_id,
  comments,
  deliver_to_location_id,
  deliver_to_person_id,
  destination_context,
  destination_type_code,
  destination_type,
  employee_id,
  from_organization_id,
  item_description,
  item_id,
  item_revision,
  hazard_class,
  un_number,
  line_num,
  item_category_id,
  locator_id,
  need_by_date,
  packing_slip,
  quantity_received,
  quantity_shipped,
  requisition_line_id,
  requisition_header_id,
  order_num,
  order_line_num,
  req_distribution_id,
  shipment_header_id,
  shipment_line_id,
  shipment_line_status_code,
  source_document_code,
  source_document_type,
  to_organization_id,
  to_subinventory,
  transfer_cost,
  transportation_account_id,
  transportation_cost,
  unit_of_measure,
  uom_conversion_rate,
  routing_header_id,
  routing_name,
  reason_id,
  reason_name,
  location_code,
  deliver_to_person,
  po_header_id,
  po_line_id,
  po_line_location_id,
  po_release_id,
  release_num,
  vendor_name,
  vendor_site_code,
  ship_to_location_id,
  primary_unit_of_measure,
  vendor_id,
  bar_code_label,
  truck_num,
  container_num,
  vendor_lot_num,
  secondary_quantity_received,
  secondary_quantity_shipped,
  secondary_unit_of_measure,
  qc_grade,
  org_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  source_type,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  charge_account_id,
  comments,
  deliver_to_location_id,
  deliver_to_person_id,
  destination_context,
  destination_type_code,
  destination_type,
  employee_id,
  from_organization_id,
  item_description,
  item_id,
  item_revision,
  hazard_class,
  un_number,
  line_num,
  item_category_id,
  locator_id,
  need_by_date,
  packing_slip,
  quantity_received,
  quantity_shipped,
  requisition_line_id,
  requisition_header_id,
  order_num,
  order_line_num,
  req_distribution_id,
  shipment_header_id,
  shipment_line_id,
  shipment_line_status_code,
  source_document_code,
  source_document_type,
  to_organization_id,
  to_subinventory,
  transfer_cost,
  transportation_account_id,
  transportation_cost,
  unit_of_measure,
  uom_conversion_rate,
  routing_header_id,
  routing_name,
  reason_id,
  reason_name,
  location_code,
  deliver_to_person,
  po_header_id,
  po_line_id,
  po_line_location_id,
  po_release_id,
  release_num,
  vendor_name,
  vendor_site_code,
  ship_to_location_id,
  primary_unit_of_measure,
  vendor_id,
  bar_code_label,
  truck_num,
  container_num,
  vendor_lot_num,
  secondary_quantity_received,
  secondary_quantity_shipped,
  secondary_unit_of_measure,
  qc_grade,
  org_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.XXBEC_RCV_MSL_V;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'xxbec_rcv_msl_v';