DROP TABLE IF EXISTS silver_bec_ods.OKC_K_HEADERS_ALL_B;
CREATE TABLE IF NOT EXISTS silver_bec_ods.OKC_K_HEADERS_ALL_B (
  id DECIMAL(15, 0),
  contract_number STRING,
  authoring_org_id DECIMAL(15, 0),
  contract_number_modifier STRING,
  chr_id_response DECIMAL(15, 0),
  chr_id_award DECIMAL(15, 0),
  chr_id_renewed DECIMAL(15, 0),
  inv_organization_id DECIMAL(15, 0),
  sts_code STRING,
  qcl_id DECIMAL(15, 0),
  scs_code STRING,
  trn_code STRING,
  currency_code STRING,
  archived_yn STRING,
  deleted_yn STRING,
  template_yn STRING,
  chr_type STRING,
  object_version_number DECIMAL(9, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  cust_po_number_req_yn STRING,
  pre_pay_req_yn STRING,
  cust_po_number STRING,
  dpas_rating STRING,
  template_used STRING,
  date_approved TIMESTAMP,
  datetime_cancelled TIMESTAMP,
  auto_renew_days DECIMAL(4, 0),
  date_issued TIMESTAMP,
  datetime_responded TIMESTAMP,
  rfp_type STRING,
  keep_on_mail_list STRING,
  set_aside_percent DECIMAL(5, 2),
  response_copies_req DECIMAL(2, 0),
  date_close_projected TIMESTAMP,
  datetime_proposed TIMESTAMP,
  date_signed TIMESTAMP,
  date_terminated TIMESTAMP,
  date_renewed TIMESTAMP,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  buy_or_sell STRING,
  issue_or_receive STRING,
  last_update_login DECIMAL(15, 0),
  estimated_amount DECIMAL(28, 10),
  attribute_category STRING,
  last_update_date TIMESTAMP,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  security_group_id DECIMAL(15, 0),
  chr_id_renewed_to DECIMAL(15, 0),
  estimated_amount_renewed DECIMAL(28, 10),
  currency_code_renewed STRING,
  upg_orig_system_ref STRING,
  upg_orig_system_ref_id DECIMAL(15, 0),
  application_id DECIMAL(15, 0),
  resolved_until TIMESTAMP,
  orig_system_source_code STRING,
  orig_system_id1 DECIMAL(15, 0),
  orig_system_reference1 STRING,
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  price_list_id DECIMAL(15, 0),
  pricing_date TIMESTAMP,
  total_line_list_price DECIMAL(28, 10),
  sign_by_date TIMESTAMP,
  user_estimated_amount DECIMAL(28, 10),
  governing_contract_yn STRING,
  conversion_type STRING,
  conversion_rate DECIMAL(28, 10),
  conversion_rate_date TIMESTAMP,
  conversion_euro_rate DECIMAL(28, 10),
  cust_acct_id DECIMAL(15, 0),
  bill_to_site_use_id DECIMAL(15, 0),
  inv_rule_id DECIMAL(15, 0),
  renewal_type_code STRING,
  renewal_notify_to DECIMAL(28, 10),
  renewal_end_date TIMESTAMP,
  ship_to_site_use_id DECIMAL(15, 0),
  payment_term_id DECIMAL(15, 0),
  document_id DECIMAL(15, 0),
  approval_type STRING,
  term_cancel_source STRING,
  payment_instruction_type STRING,
  org_id DECIMAL(15, 0),
  cancelled_amount DECIMAL(28, 10),
  billed_at_source STRING,
  attribute16 STRING,
  attribute17 STRING,
  attribute18 STRING,
  attribute19 STRING,
  attribute20 STRING,
  attribute21 STRING,
  attribute22 STRING,
  attribute23 STRING,
  attribute24 STRING,
  attribute25 STRING,
  attribute26 STRING,
  attribute27 STRING,
  attribute28 STRING,
  attribute29 STRING,
  attribute30 STRING,
  attribute31 STRING,
  attribute32 STRING,
  attribute33 STRING,
  attribute34 STRING,
  attribute35 STRING,
  attribute36 STRING,
  attribute37 STRING,
  attribute38 STRING,
  attribute39 STRING,
  attribute40 STRING,
  attribute41 STRING,
  attribute42 STRING,
  attribute43 STRING,
  attribute44 STRING,
  attribute45 STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.OKC_K_HEADERS_ALL_B (
  id,
  contract_number,
  authoring_org_id,
  contract_number_modifier,
  chr_id_response,
  chr_id_award,
  chr_id_renewed,
  inv_organization_id,
  sts_code,
  qcl_id,
  scs_code,
  trn_code,
  currency_code,
  archived_yn,
  deleted_yn,
  template_yn,
  chr_type,
  object_version_number,
  created_by,
  creation_date,
  last_updated_by,
  cust_po_number_req_yn,
  pre_pay_req_yn,
  cust_po_number,
  dpas_rating,
  template_used,
  date_approved,
  datetime_cancelled,
  auto_renew_days,
  date_issued,
  datetime_responded,
  rfp_type,
  keep_on_mail_list,
  set_aside_percent,
  response_copies_req,
  date_close_projected,
  datetime_proposed,
  date_signed,
  date_terminated,
  date_renewed,
  start_date,
  end_date,
  buy_or_sell,
  issue_or_receive,
  last_update_login,
  estimated_amount,
  attribute_category,
  last_update_date,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  chr_id_renewed_to,
  estimated_amount_renewed,
  currency_code_renewed,
  upg_orig_system_ref,
  upg_orig_system_ref_id,
  application_id,
  resolved_until,
  orig_system_source_code,
  orig_system_id1,
  orig_system_reference1,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  price_list_id,
  pricing_date,
  total_line_list_price,
  sign_by_date,
  user_estimated_amount,
  governing_contract_yn,
  conversion_type,
  conversion_rate,
  conversion_rate_date,
  conversion_euro_rate,
  cust_acct_id,
  bill_to_site_use_id,
  inv_rule_id,
  renewal_type_code,
  renewal_notify_to,
  renewal_end_date,
  ship_to_site_use_id,
  payment_term_id,
  document_id,
  approval_type,
  term_cancel_source,
  payment_instruction_type,
  org_id,
  cancelled_amount,
  billed_at_source,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  attribute21,
  attribute22,
  attribute23,
  attribute24,
  attribute25,
  attribute26,
  attribute27,
  attribute28,
  attribute29,
  attribute30,
  attribute31,
  attribute32,
  attribute33,
  attribute34,
  attribute35,
  attribute36,
  attribute37,
  attribute38,
  attribute39,
  attribute40,
  attribute41,
  attribute42,
  attribute43,
  attribute44,
  attribute45,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  id,
  contract_number,
  authoring_org_id,
  contract_number_modifier,
  chr_id_response,
  chr_id_award,
  chr_id_renewed,
  inv_organization_id,
  sts_code,
  qcl_id,
  scs_code,
  trn_code,
  currency_code,
  archived_yn,
  deleted_yn,
  template_yn,
  chr_type,
  object_version_number,
  created_by,
  creation_date,
  last_updated_by,
  cust_po_number_req_yn,
  pre_pay_req_yn,
  cust_po_number,
  dpas_rating,
  template_used,
  date_approved,
  datetime_cancelled,
  auto_renew_days,
  date_issued,
  datetime_responded,
  rfp_type,
  keep_on_mail_list,
  set_aside_percent,
  response_copies_req,
  date_close_projected,
  datetime_proposed,
  date_signed,
  date_terminated,
  date_renewed,
  start_date,
  end_date,
  buy_or_sell,
  issue_or_receive,
  last_update_login,
  estimated_amount,
  attribute_category,
  last_update_date,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  security_group_id,
  chr_id_renewed_to,
  estimated_amount_renewed,
  currency_code_renewed,
  upg_orig_system_ref,
  upg_orig_system_ref_id,
  application_id,
  resolved_until,
  orig_system_source_code,
  orig_system_id1,
  orig_system_reference1,
  program_application_id,
  program_id,
  program_update_date,
  request_id,
  price_list_id,
  pricing_date,
  total_line_list_price,
  sign_by_date,
  user_estimated_amount,
  governing_contract_yn,
  conversion_type,
  conversion_rate,
  conversion_rate_date,
  conversion_euro_rate,
  cust_acct_id,
  bill_to_site_use_id,
  inv_rule_id,
  renewal_type_code,
  renewal_notify_to,
  renewal_end_date,
  ship_to_site_use_id,
  payment_term_id,
  document_id,
  approval_type,
  term_cancel_source,
  payment_instruction_type,
  org_id,
  cancelled_amount,
  billed_at_source,
  attribute16,
  attribute17,
  attribute18,
  attribute19,
  attribute20,
  attribute21,
  attribute22,
  attribute23,
  attribute24,
  attribute25,
  attribute26,
  attribute27,
  attribute28,
  attribute29,
  attribute30,
  attribute31,
  attribute32,
  attribute33,
  attribute34,
  attribute35,
  attribute36,
  attribute37,
  attribute38,
  attribute39,
  attribute40,
  attribute41,
  attribute42,
  attribute43,
  attribute44,
  attribute45,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.OKC_K_HEADERS_ALL_B;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'okc_k_headers_all_b';