DROP TABLE IF EXISTS silver_bec_ods.hz_cust_profile_classes;
CREATE TABLE IF NOT EXISTS silver_bec_ods.hz_cust_profile_classes (
  profile_class_id DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  program_application_id DECIMAL(15, 0),
  name STRING,
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  status STRING,
  wh_update_date TIMESTAMP,
  collector_id DECIMAL(15, 0),
  credit_analyst_id DECIMAL(15, 0),
  credit_checking STRING,
  tolerance DECIMAL(15, 0),
  discount_terms STRING,
  dunning_letters STRING,
  interest_charges STRING,
  pref_functional_currency STRING,
  statements STRING,
  credit_balance_statements STRING,
  description STRING,
  review_cycle_days DECIMAL(15, 0),
  outside_reporting STRING,
  standard_terms DECIMAL(15, 0),
  override_terms STRING,
  dunning_letter_set_id DECIMAL(15, 0),
  combine_dunning_letters STRING,
  interest_period_days DECIMAL(15, 0),
  autocash_hierarchy_id DECIMAL(15, 0),
  payment_grace_days DECIMAL(15, 0),
  discount_grace_days DECIMAL(15, 0),
  statement_cycle_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  request_id DECIMAL(15, 0),
  copy_method STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  auto_rec_incl_disputed_flag STRING,
  tax_printing_option STRING,
  charge_on_finance_charge_flag STRING,
  grouping_rule_id DECIMAL(15, 0),
  jgzz_attribute_category STRING,
  jgzz_attribute1 STRING,
  jgzz_attribute2 STRING,
  jgzz_attribute3 STRING,
  jgzz_attribute4 STRING,
  jgzz_attribute5 STRING,
  jgzz_attribute6 STRING,
  jgzz_attribute7 STRING,
  jgzz_attribute8 STRING,
  jgzz_attribute9 STRING,
  jgzz_attribute10 STRING,
  jgzz_attribute11 STRING,
  jgzz_attribute12 STRING,
  jgzz_attribute13 STRING,
  jgzz_attribute14 STRING,
  jgzz_attribute15 STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute_category STRING,
  cons_inv_flag STRING,
  cons_inv_type STRING,
  autocash_hierarchy_id_for_adr DECIMAL(15, 0),
  lockbox_matching_option STRING,
  review_cycle STRING,
  credit_classification STRING,
  cons_bill_level STRING,
  late_charge_calculation_trx STRING,
  credit_items_flag STRING,
  disputed_transactions_flag STRING,
  late_charge_type STRING,
  late_charge_term_id DECIMAL(15, 0),
  interest_calculation_period STRING,
  hold_charged_invoices_flag STRING,
  message_text_id DECIMAL(15, 0),
  multiple_interest_rates_flag STRING,
  charge_begin_date TIMESTAMP,
  object_version_number DECIMAL(15, 0),
  AUTOMATCH_SET_ID DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.hz_cust_profile_classes (
  profile_class_id,
  last_updated_by,
  last_update_date,
  last_update_login,
  created_by,
  creation_date,
  program_application_id,
  `name`,
  program_id,
  program_update_date,
  status,
  wh_update_date,
  collector_id,
  credit_analyst_id,
  credit_checking,
  tolerance,
  discount_terms,
  dunning_letters,
  interest_charges,
  pref_functional_currency,
  statements,
  credit_balance_statements,
  description,
  review_cycle_days,
  outside_reporting,
  standard_terms,
  override_terms,
  dunning_letter_set_id,
  combine_dunning_letters,
  interest_period_days,
  autocash_hierarchy_id,
  payment_grace_days,
  discount_grace_days,
  statement_cycle_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  request_id,
  copy_method,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  auto_rec_incl_disputed_flag,
  tax_printing_option,
  charge_on_finance_charge_flag,
  grouping_rule_id,
  jgzz_attribute_category,
  jgzz_attribute1,
  jgzz_attribute2,
  jgzz_attribute3,
  jgzz_attribute4,
  jgzz_attribute5,
  jgzz_attribute6,
  jgzz_attribute7,
  jgzz_attribute8,
  jgzz_attribute9,
  jgzz_attribute10,
  jgzz_attribute11,
  jgzz_attribute12,
  jgzz_attribute13,
  jgzz_attribute14,
  jgzz_attribute15,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  cons_inv_flag,
  cons_inv_type,
  autocash_hierarchy_id_for_adr,
  lockbox_matching_option,
  review_cycle,
  credit_classification,
  cons_bill_level,
  late_charge_calculation_trx,
  credit_items_flag,
  disputed_transactions_flag,
  late_charge_type,
  late_charge_term_id,
  interest_calculation_period,
  hold_charged_invoices_flag,
  message_text_id,
  multiple_interest_rates_flag,
  charge_begin_date,
  object_version_number,
  AUTOMATCH_SET_ID,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  profile_class_id,
  last_updated_by,
  last_update_date,
  last_update_login,
  created_by,
  creation_date,
  program_application_id,
  `name`,
  program_id,
  program_update_date,
  status,
  wh_update_date,
  collector_id,
  credit_analyst_id,
  credit_checking,
  tolerance,
  discount_terms,
  dunning_letters,
  interest_charges,
  pref_functional_currency,
  statements,
  credit_balance_statements,
  description,
  review_cycle_days,
  outside_reporting,
  standard_terms,
  override_terms,
  dunning_letter_set_id,
  combine_dunning_letters,
  interest_period_days,
  autocash_hierarchy_id,
  payment_grace_days,
  discount_grace_days,
  statement_cycle_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  request_id,
  copy_method,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  auto_rec_incl_disputed_flag,
  tax_printing_option,
  charge_on_finance_charge_flag,
  grouping_rule_id,
  jgzz_attribute_category,
  jgzz_attribute1,
  jgzz_attribute2,
  jgzz_attribute3,
  jgzz_attribute4,
  jgzz_attribute5,
  jgzz_attribute6,
  jgzz_attribute7,
  jgzz_attribute8,
  jgzz_attribute9,
  jgzz_attribute10,
  jgzz_attribute11,
  jgzz_attribute12,
  jgzz_attribute13,
  jgzz_attribute14,
  jgzz_attribute15,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  cons_inv_flag,
  cons_inv_type,
  autocash_hierarchy_id_for_adr,
  lockbox_matching_option,
  review_cycle,
  credit_classification,
  cons_bill_level,
  late_charge_calculation_trx,
  credit_items_flag,
  disputed_transactions_flag,
  late_charge_type,
  late_charge_term_id,
  interest_calculation_period,
  hold_charged_invoices_flag,
  message_text_id,
  multiple_interest_rates_flag,
  charge_begin_date,
  object_version_number,
  AUTOMATCH_SET_ID,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.HZ_CUST_PROFILE_CLASSES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'hz_cust_profile_classes';