DROP TABLE IF EXISTS silver_bec_ods.MSC_CALENDAR_DATES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MSC_CALENDAR_DATES (
  calendar_date TIMESTAMP,
  calendar_code STRING,
  seq_num DECIMAL(15, 0),
  next_seq_num DECIMAL(15, 0),
  prior_seq_num DECIMAL(15, 0),
  next_date TIMESTAMP,
  prior_date TIMESTAMP,
  calendar_start_date TIMESTAMP,
  calendar_end_date TIMESTAMP,
  description STRING,
  exception_set_id DECIMAL(15, 0),
  sr_instance_id DECIMAL(15, 0),
  refresh_number DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  deleted_flag DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MSC_CALENDAR_DATES (
  CALENDAR_DATE,
  CALENDAR_CODE,
  SEQ_NUM,
  NEXT_SEQ_NUM,
  PRIOR_SEQ_NUM,
  NEXT_DATE,
  PRIOR_DATE,
  CALENDAR_START_DATE,
  CALENDAR_END_DATE,
  DESCRIPTION,
  EXCEPTION_SET_ID,
  SR_INSTANCE_ID,
  REFRESH_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  DELETED_FLAG,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  CALENDAR_DATE,
  CALENDAR_CODE,
  SEQ_NUM,
  NEXT_SEQ_NUM,
  PRIOR_SEQ_NUM,
  NEXT_DATE,
  PRIOR_DATE,
  CALENDAR_START_DATE,
  CALENDAR_END_DATE,
  DESCRIPTION,
  EXCEPTION_SET_ID,
  SR_INSTANCE_ID,
  REFRESH_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  DELETED_FLAG,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MSC_CALENDAR_DATES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_calendar_dates';