DROP TABLE IF EXISTS silver_bec_ods.hz_cust_profile_amts;
CREATE TABLE IF NOT EXISTS silver_bec_ods.hz_cust_profile_amts (
  cust_acct_profile_amt_id DECIMAL(15, 0),
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  cust_account_profile_id DECIMAL(15, 0),
  currency_code STRING,
  last_update_login DECIMAL(15, 0),
  trx_credit_limit DECIMAL(28, 10),
  overall_credit_limit DECIMAL(28, 10),
  min_dunning_amount DECIMAL(28, 10),
  min_dunning_invoice_amount DECIMAL(28, 10),
  max_interest_charge DECIMAL(28, 10),
  min_statement_amount DECIMAL(28, 10),
  auto_rec_min_receipt_amount DECIMAL(28, 10),
  interest_rate DECIMAL(28, 10),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  min_fc_balance_amount DECIMAL(28, 10),
  min_fc_invoice_amount DECIMAL(28, 10),
  cust_account_id DECIMAL(15, 0),
  site_use_id DECIMAL(15, 0),
  expiration_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  wh_update_date TIMESTAMP,
  jgzz_attribute_category STRING,
  jgzz_attribute1 STRING,
  jgzz_attribute2 STRING,
  jgzz_attribute3 STRING,
  jgzz_attribute4 STRING,
  jgzz_attribute5 STRING,
  jgzz_attribute6 STRING,
  jgzz_attribute7 STRING,
  jgzz_attribute8 STRING,
  jgzz_attribute9 STRING,
  jgzz_attribute10 STRING,
  jgzz_attribute11 STRING,
  jgzz_attribute12 STRING,
  jgzz_attribute13 STRING,
  jgzz_attribute14 STRING,
  jgzz_attribute15 STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute_category STRING,
  object_version_number DECIMAL(15, 0),
  created_by_module STRING,
  application_id DECIMAL(15, 0),
  exchange_rate_type STRING,
  min_fc_invoice_overdue_type STRING,
  min_fc_invoice_percent DECIMAL(28, 10),
  min_fc_balance_overdue_type STRING,
  min_fc_balance_percent DECIMAL(28, 10),
  interest_type STRING,
  interest_fixed_amount DECIMAL(28, 10),
  interest_schedule_id DECIMAL(15, 0),
  penalty_type STRING,
  penalty_rate DECIMAL(28, 10),
  min_interest_charge DECIMAL(28, 10),
  penalty_fixed_amount DECIMAL(28, 10),
  penalty_schedule_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.hz_cust_profile_amts (
  cust_acct_profile_amt_id,
  last_updated_by,
  last_update_date,
  created_by,
  creation_date,
  cust_account_profile_id,
  currency_code,
  last_update_login,
  trx_credit_limit,
  overall_credit_limit,
  min_dunning_amount,
  min_dunning_invoice_amount,
  max_interest_charge,
  min_statement_amount,
  auto_rec_min_receipt_amount,
  interest_rate,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  min_fc_balance_amount,
  min_fc_invoice_amount,
  cust_account_id,
  site_use_id,
  expiration_date,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wh_update_date,
  jgzz_attribute_category,
  jgzz_attribute1,
  jgzz_attribute2,
  jgzz_attribute3,
  jgzz_attribute4,
  jgzz_attribute5,
  jgzz_attribute6,
  jgzz_attribute7,
  jgzz_attribute8,
  jgzz_attribute9,
  jgzz_attribute10,
  jgzz_attribute11,
  jgzz_attribute12,
  jgzz_attribute13,
  jgzz_attribute14,
  jgzz_attribute15,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  object_version_number,
  created_by_module,
  application_id,
  exchange_rate_type,
  min_fc_invoice_overdue_type,
  min_fc_invoice_percent,
  min_fc_balance_overdue_type,
  min_fc_balance_percent,
  interest_type,
  interest_fixed_amount,
  interest_schedule_id,
  penalty_type,
  penalty_rate,
  min_interest_charge,
  penalty_fixed_amount,
  penalty_schedule_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cust_acct_profile_amt_id,
  last_updated_by,
  last_update_date,
  created_by,
  creation_date,
  cust_account_profile_id,
  currency_code,
  last_update_login,
  trx_credit_limit,
  overall_credit_limit,
  min_dunning_amount,
  min_dunning_invoice_amount,
  max_interest_charge,
  min_statement_amount,
  auto_rec_min_receipt_amount,
  interest_rate,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  min_fc_balance_amount,
  min_fc_invoice_amount,
  cust_account_id,
  site_use_id,
  expiration_date,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  wh_update_date,
  jgzz_attribute_category,
  jgzz_attribute1,
  jgzz_attribute2,
  jgzz_attribute3,
  jgzz_attribute4,
  jgzz_attribute5,
  jgzz_attribute6,
  jgzz_attribute7,
  jgzz_attribute8,
  jgzz_attribute9,
  jgzz_attribute10,
  jgzz_attribute11,
  jgzz_attribute12,
  jgzz_attribute13,
  jgzz_attribute14,
  jgzz_attribute15,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  object_version_number,
  created_by_module,
  application_id,
  exchange_rate_type,
  min_fc_invoice_overdue_type,
  min_fc_invoice_percent,
  min_fc_balance_overdue_type,
  min_fc_balance_percent,
  interest_type,
  interest_fixed_amount,
  interest_schedule_id,
  penalty_type,
  penalty_rate,
  min_interest_charge,
  penalty_fixed_amount,
  penalty_schedule_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.HZ_CUST_PROFILE_AMTS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'hz_cust_profile_amts';