DROP table IF EXISTS silver_bec_ods.ap_terms_lines;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_terms_lines (
  term_id DECIMAL(15, 0),
  sequence_num DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  due_percent DECIMAL(28, 10),
  due_amount DECIMAL(28, 10),
  due_days DECIMAL(15, 0),
  due_day_of_month DECIMAL(15, 0),
  due_months_forward DECIMAL(15, 0),
  discount_percent DECIMAL(28, 10),
  discount_days DECIMAL(15, 0),
  discount_day_of_month DECIMAL(15, 0),
  discount_months_forward DECIMAL(15, 0),
  discount_percent_2 DECIMAL(28, 10),
  discount_days_2 DECIMAL(15, 0),
  discount_day_of_month_2 DECIMAL(15, 0),
  discount_months_forward_2 DECIMAL(15, 0),
  discount_percent_3 DECIMAL(28, 10),
  discount_days_3 DECIMAL(15, 0),
  discount_day_of_month_3 DECIMAL(15, 0),
  discount_months_forward_3 DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  fixed_date TIMESTAMP,
  calendar STRING,
  discount_amount DECIMAL(28, 10),
  discount_criteria STRING,
  discount_amount_2 DECIMAL(28, 10),
  discount_criteria_2 STRING,
  discount_amount_3 DECIMAL(28, 10),
  discount_criteria_3 STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_terms_lines (
  term_id,
  sequence_num,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  due_percent,
  due_amount,
  due_days,
  due_day_of_month,
  due_months_forward,
  discount_percent,
  discount_days,
  discount_day_of_month,
  discount_months_forward,
  discount_percent_2,
  discount_days_2,
  discount_day_of_month_2,
  discount_months_forward_2,
  discount_percent_3,
  discount_days_3,
  discount_day_of_month_3,
  discount_months_forward_3,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  fixed_date,
  calendar,
  discount_amount,
  discount_criteria,
  discount_amount_2,
  discount_criteria_2,
  discount_amount_3,
  discount_criteria_3,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  term_id,
  sequence_num,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  due_percent,
  due_amount,
  due_days,
  due_day_of_month,
  due_months_forward,
  discount_percent,
  discount_days,
  discount_day_of_month,
  discount_months_forward,
  discount_percent_2,
  discount_days_2,
  discount_day_of_month_2,
  discount_months_forward_2,
  discount_percent_3,
  discount_days_3,
  discount_day_of_month_3,
  discount_months_forward_3,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  fixed_date,
  calendar,
  discount_amount,
  discount_criteria,
  discount_amount_2,
  discount_criteria_2,
  discount_amount_3,
  discount_criteria_3,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ap_terms_lines;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_terms_lines';