DROP TABLE IF EXISTS silver_bec_ods.MSC_ITEM_CATEGORIES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MSC_ITEM_CATEGORIES (
  organization_id DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  category_set_id DECIMAL(15, 0),
  category_name STRING,
  description STRING,
  disable_date TIMESTAMP,
  summary_flag STRING,
  enabled_flag STRING,
  start_date_active TIMESTAMP,
  end_date_active TIMESTAMP,
  sr_instance_id DECIMAL(15, 0),
  sr_category_id DECIMAL(15, 0),
  refresh_number DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MSC_ITEM_CATEGORIES (
  organization_id,
  inventory_item_id,
  category_set_id,
  category_name,
  description,
  disable_date,
  summary_flag,
  enabled_flag,
  start_date_active,
  end_date_active,
  sr_instance_id,
  sr_category_id,
  refresh_number,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  organization_id,
  inventory_item_id,
  category_set_id,
  category_name,
  description,
  disable_date,
  summary_flag,
  enabled_flag,
  start_date_active,
  end_date_active,
  sr_instance_id,
  sr_category_id,
  refresh_number,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MSC_ITEM_CATEGORIES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_item_categories';