DROP TABLE IF EXISTS silver_bec_ods.FA_ASSET_INVOICES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.FA_ASSET_INVOICES (
  asset_id DECIMAL(15, 0),
  po_vendor_id DECIMAL(15, 0),
  asset_invoice_id DECIMAL(15, 0),
  fixed_assets_cost DECIMAL(28, 10),
  date_effective TIMESTAMP,
  date_ineffective TIMESTAMP,
  invoice_transaction_id_in DECIMAL(15, 0),
  invoice_transaction_id_out DECIMAL(15, 0),
  deleted_flag STRING,
  po_number STRING,
  invoice_number STRING,
  payables_batch_name STRING,
  payables_code_combination_id DECIMAL(15, 0),
  feeder_system_name STRING,
  create_batch_date TIMESTAMP,
  create_batch_id DECIMAL(15, 0),
  invoice_date TIMESTAMP,
  payables_cost DECIMAL(28, 10),
  post_batch_id DECIMAL(15, 0),
  invoice_id DECIMAL(15, 0),
  ap_distribution_line_number DECIMAL(15, 0),
  payables_units DECIMAL(15, 0),
  split_merged_code STRING,
  description STRING,
  parent_mass_addition_id STRING,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute_category_code STRING,
  unrevalued_cost DECIMAL(28, 10),
  merged_code STRING,
  split_code STRING,
  merge_parent_mass_additions_id DECIMAL(15, 0),
  split_parent_mass_additions_id DECIMAL(15, 0),
  project_asset_line_id DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  source_line_id DECIMAL(15, 0),
  depreciate_in_group_flag STRING,
  material_indicator_flag STRING,
  prior_source_line_id DECIMAL(15, 0),
  invoice_distribution_id DECIMAL(15, 0),
  invoice_line_number DECIMAL(15, 0),
  po_distribution_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.FA_ASSET_INVOICES (
  asset_id,
  po_vendor_id,
  asset_invoice_id,
  fixed_assets_cost,
  date_effective,
  date_ineffective,
  invoice_transaction_id_in,
  invoice_transaction_id_out,
  deleted_flag,
  po_number,
  invoice_number,
  payables_batch_name,
  payables_code_combination_id,
  feeder_system_name,
  create_batch_date,
  create_batch_id,
  invoice_date,
  payables_cost,
  post_batch_id,
  invoice_id,
  ap_distribution_line_number,
  payables_units,
  split_merged_code,
  description,
  parent_mass_addition_id,
  last_update_date,
  last_updated_by,
  created_by,
  creation_date,
  last_update_login,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category_code,
  unrevalued_cost,
  merged_code,
  split_code,
  merge_parent_mass_additions_id,
  split_parent_mass_additions_id,
  project_asset_line_id,
  project_id,
  task_id,
  source_line_id,
  depreciate_in_group_flag,
  material_indicator_flag,
  prior_source_line_id,
  invoice_distribution_id,
  invoice_line_number,
  po_distribution_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  asset_id,
  po_vendor_id,
  asset_invoice_id,
  fixed_assets_cost,
  date_effective,
  date_ineffective,
  invoice_transaction_id_in,
  invoice_transaction_id_out,
  deleted_flag,
  po_number,
  invoice_number,
  payables_batch_name,
  payables_code_combination_id,
  feeder_system_name,
  create_batch_date,
  create_batch_id,
  invoice_date,
  payables_cost,
  post_batch_id,
  invoice_id,
  ap_distribution_line_number,
  payables_units,
  split_merged_code,
  description,
  parent_mass_addition_id,
  last_update_date,
  last_updated_by,
  created_by,
  creation_date,
  last_update_login,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category_code,
  unrevalued_cost,
  merged_code,
  split_code,
  merge_parent_mass_additions_id,
  split_parent_mass_additions_id,
  project_asset_line_id,
  project_id,
  task_id,
  source_line_id,
  depreciate_in_group_flag,
  material_indicator_flag,
  prior_source_line_id,
  invoice_distribution_id,
  invoice_line_number,
  po_distribution_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.FA_ASSET_INVOICES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fa_asset_invoices';