DROP TABLE IF EXISTS silver_bec_ods.AR_RECEIPT_METHODS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ar_receipt_methods (
  receipt_method_id DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  name STRING,
  receipt_class_id DECIMAL(15, 0),
  start_date TIMESTAMP,
  auto_print_program_id DECIMAL(15, 0),
  auto_trans_program_id DECIMAL(15, 0),
  end_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  lead_days DECIMAL(5, 0),
  maturity_date_rule_code STRING,
  receipt_creation_rule_code STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  printed_name STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute_category STRING,
  payment_type_code STRING,
  merchant_id DECIMAL(15, 0),
  receipt_inherit_inv_num_flag STRING,
  dm_inherit_receipt_num_flag STRING,
  br_cust_trx_type_id DECIMAL(15, 0),
  br_min_acctd_amount DECIMAL(28, 10),
  br_max_acctd_amount DECIMAL(28, 10),
  br_inherit_inv_num_flag STRING,
  merchant_ref STRING,
  payment_channel_code STRING,
  ZD_EDITION_NAME STRING,
  ZD_SYNC STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.AR_RECEIPT_METHODS (
  receipt_method_id,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  `name`,
  receipt_class_id,
  start_date,
  auto_print_program_id,
  auto_trans_program_id,
  end_date,
  last_update_login,
  lead_days,
  maturity_date_rule_code,
  receipt_creation_rule_code,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  printed_name,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  payment_type_code,
  merchant_id,
  receipt_inherit_inv_num_flag,
  dm_inherit_receipt_num_flag,
  br_cust_trx_type_id,
  br_min_acctd_amount,
  br_max_acctd_amount,
  br_inherit_inv_num_flag,
  merchant_ref,
  payment_channel_code,
  zd_edition_name,
  zd_sync,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  receipt_method_id,
  created_by,
  creation_date,
  last_updated_by,
  last_update_date,
  `name`,
  receipt_class_id,
  start_date,
  auto_print_program_id,
  auto_trans_program_id,
  end_date,
  last_update_login,
  lead_days,
  maturity_date_rule_code,
  receipt_creation_rule_code,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  printed_name,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  payment_type_code,
  merchant_id,
  receipt_inherit_inv_num_flag,
  dm_inherit_receipt_num_flag,
  br_cust_trx_type_id,
  br_min_acctd_amount,
  br_max_acctd_amount,
  br_inherit_inv_num_flag,
  merchant_ref,
  payment_channel_code,
  zd_edition_name,
  zd_sync,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.AR_RECEIPT_METHODS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ar_receipt_methods';