DROP TABLE IF EXISTS silver_bec_ods.ra_cust_trx_types_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ra_cust_trx_types_all (
  cust_trx_type_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  post_to_gl STRING,
  accounting_affect_flag STRING,
  credit_memo_type_id DECIMAL(15, 0),
  status STRING,
  name STRING,
  description STRING,
  `type` STRING,
  default_term DECIMAL(15, 0),
  default_printing_option STRING,
  default_status STRING,
  gl_id_rev DECIMAL(15, 0),
  gl_id_freight DECIMAL(15, 0),
  gl_id_rec DECIMAL(15, 0),
  subsequent_trx_type_id DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  allow_freight_flag STRING,
  allow_overapplication_flag STRING,
  creation_sign STRING,
  end_date TIMESTAMP,
  gl_id_clearing DECIMAL(15, 0),
  gl_id_tax DECIMAL(15, 0),
  gl_id_unbilled DECIMAL(15, 0),
  gl_id_unearned DECIMAL(15, 0),
  start_date TIMESTAMP,
  tax_calculation_flag STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  natural_application_only_flag STRING,
  org_id DECIMAL(15, 0),
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute_category STRING,
  rule_set_id DECIMAL(15, 0),
  signed_flag STRING,
  drawee_issued_flag STRING,
  magnetic_format_code STRING,
  format_program_id DECIMAL(15, 0),
  gl_id_unpaid_rec DECIMAL(15, 0),
  gl_id_remittance DECIMAL(15, 0),
  gl_id_factor DECIMAL(15, 0),
  allocate_tax_freight STRING,
  legal_entity_id DECIMAL(15, 0),
  exclude_from_late_charges STRING,
  adj_post_to_gl STRING,
  ZD_EDITION_NAME STRING,
  ZD_SYNC STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ra_cust_trx_types_all (
  cust_trx_type_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  post_to_gl,
  accounting_affect_flag,
  credit_memo_type_id,
  status,
  `name`,
  description,
  `type`,
  default_term,
  default_printing_option,
  default_status,
  gl_id_rev,
  gl_id_freight,
  gl_id_rec,
  subsequent_trx_type_id,
  set_of_books_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  allow_freight_flag,
  allow_overapplication_flag,
  creation_sign,
  end_date,
  gl_id_clearing,
  gl_id_tax,
  gl_id_unbilled,
  gl_id_unearned,
  start_date,
  tax_calculation_flag,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  natural_application_only_flag,
  org_id,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  rule_set_id,
  signed_flag,
  drawee_issued_flag,
  magnetic_format_code,
  format_program_id,
  gl_id_unpaid_rec,
  gl_id_remittance,
  gl_id_factor,
  allocate_tax_freight,
  legal_entity_id,
  exclude_from_late_charges,
  adj_post_to_gl,
  ZD_EDITION_NAME,
  ZD_SYNC,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cust_trx_type_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  post_to_gl,
  accounting_affect_flag,
  credit_memo_type_id,
  status,
  `name`,
  description,
  `type`,
  default_term,
  default_printing_option,
  default_status,
  gl_id_rev,
  gl_id_freight,
  gl_id_rec,
  subsequent_trx_type_id,
  set_of_books_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  allow_freight_flag,
  allow_overapplication_flag,
  creation_sign,
  end_date,
  gl_id_clearing,
  gl_id_tax,
  gl_id_unbilled,
  gl_id_unearned,
  start_date,
  tax_calculation_flag,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  natural_application_only_flag,
  org_id,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  rule_set_id,
  signed_flag,
  drawee_issued_flag,
  magnetic_format_code,
  format_program_id,
  gl_id_unpaid_rec,
  gl_id_remittance,
  gl_id_factor,
  allocate_tax_freight,
  legal_entity_id,
  exclude_from_late_charges,
  adj_post_to_gl,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ra_cust_trx_types_all;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ra_cust_trx_types_all';