DROP TABLE IF EXISTS silver_bec_ods.MTL_CYCLE_COUNT_HEADERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_CYCLE_COUNT_HEADERS (
  cycle_count_header_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  cycle_count_header_name STRING,
  inventory_adjustment_account DECIMAL(15, 0),
  orientation_code DECIMAL(15, 0),
  abc_assignment_group_id DECIMAL(15, 0),
  onhand_visible_flag DECIMAL(15, 0),
  days_until_late DECIMAL(15, 0),
  autoschedule_enabled_flag DECIMAL(15, 0),
  schedule_interval_time DECIMAL(15, 0),
  zero_count_flag DECIMAL(15, 0),
  header_last_schedule_date TIMESTAMP,
  header_next_schedule_date TIMESTAMP,
  disable_date TIMESTAMP,
  approval_option_code DECIMAL(15, 0),
  automatic_recount_flag DECIMAL(15, 0),
  next_user_count_sequence DECIMAL(15, 0),
  unscheduled_count_entry DECIMAL(15, 0),
  cycle_count_calendar STRING,
  calendar_exception_set DECIMAL(15, 0),
  approval_tolerance_positive DECIMAL(15, 0),
  approval_tolerance_negative DECIMAL(15, 0),
  cost_tolerance_positive DECIMAL(15, 0),
  cost_tolerance_negative DECIMAL(15, 0),
  hit_miss_tolerance_positive DECIMAL(15, 0),
  hit_miss_tolerance_negative DECIMAL(15, 0),
  abc_initialization_status DECIMAL(15, 0),
  description STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  maximum_auto_recounts DECIMAL(15, 0),
  serial_count_option DECIMAL(15, 0),
  serial_detail_option DECIMAL(15, 0),
  serial_adjustment_option DECIMAL(15, 0),
  serial_discrepancy_option DECIMAL(15, 0),
  container_adjustment_option DECIMAL(15, 0),
  container_discrepancy_option DECIMAL(15, 0),
  container_enabled_flag DECIMAL(15, 0),
  cycle_count_type DECIMAL(15, 0),
  schedule_empty_locations DECIMAL(15, 0),
  default_num_counts_per_year DECIMAL(15, 0),
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_CYCLE_COUNT_HEADERS (
  cycle_count_header_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  cycle_count_header_name,
  inventory_adjustment_account,
  orientation_code,
  abc_assignment_group_id,
  onhand_visible_flag,
  days_until_late,
  autoschedule_enabled_flag,
  schedule_interval_time,
  zero_count_flag,
  header_last_schedule_date,
  header_next_schedule_date,
  disable_date,
  approval_option_code,
  automatic_recount_flag,
  next_user_count_sequence,
  unscheduled_count_entry,
  cycle_count_calendar,
  calendar_exception_set,
  approval_tolerance_positive,
  approval_tolerance_negative,
  cost_tolerance_positive,
  cost_tolerance_negative,
  hit_miss_tolerance_positive,
  hit_miss_tolerance_negative,
  abc_initialization_status,
  description,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  maximum_auto_recounts,
  serial_count_option,
  serial_detail_option,
  serial_adjustment_option,
  serial_discrepancy_option,
  container_adjustment_option,
  container_discrepancy_option,
  container_enabled_flag,
  cycle_count_type,
  schedule_empty_locations,
  default_num_counts_per_year,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  cycle_count_header_id,
  organization_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  cycle_count_header_name,
  inventory_adjustment_account,
  orientation_code,
  abc_assignment_group_id,
  onhand_visible_flag,
  days_until_late,
  autoschedule_enabled_flag,
  schedule_interval_time,
  zero_count_flag,
  header_last_schedule_date,
  header_next_schedule_date,
  disable_date,
  approval_option_code,
  automatic_recount_flag,
  next_user_count_sequence,
  unscheduled_count_entry,
  cycle_count_calendar,
  calendar_exception_set,
  approval_tolerance_positive,
  approval_tolerance_negative,
  cost_tolerance_positive,
  cost_tolerance_negative,
  hit_miss_tolerance_positive,
  hit_miss_tolerance_negative,
  abc_initialization_status,
  description,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  maximum_auto_recounts,
  serial_count_option,
  serial_detail_option,
  serial_adjustment_option,
  serial_discrepancy_option,
  container_adjustment_option,
  container_discrepancy_option,
  container_enabled_flag,
  cycle_count_type,
  schedule_empty_locations,
  default_num_counts_per_year,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_CYCLE_COUNT_HEADERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_cycle_count_headers';