DROP TABLE IF EXISTS silver_bec_ods.MRP_FORECAST_DATES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MRP_FORECAST_DATES (
  transaction_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  forecast_designator STRING,
  forecast_date TIMESTAMP,
  original_forecast_quantity DECIMAL(28, 10),
  current_forecast_quantity DECIMAL(28, 10),
  confidence_percentage DECIMAL(28, 10),
  bucket_type DECIMAL(15, 0),
  rate_end_date TIMESTAMP,
  origination_type DECIMAL(15, 0),
  customer_id DECIMAL(15, 0),
  ship_id DECIMAL(15, 0),
  bill_id DECIMAL(15, 0),
  comments STRING,
  source_organization_id DECIMAL(15, 0),
  source_forecast_designator STRING,
  source_code STRING,
  source_line_id DECIMAL(15, 0),
  end_item_id DECIMAL(15, 0),
  end_planning_bom_percent DECIMAL(28, 10),
  forecast_rule_id DECIMAL(15, 0),
  demand_usage_start_date TIMESTAMP,
  forecast_trend DECIMAL(28, 10),
  focus_type DECIMAL(15, 0),
  forecast_mad DECIMAL(28, 10),
  demand_class STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(38, 10),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  old_transaction_id DECIMAL(15, 0),
  to_update DECIMAL(15, 0),
  ddf_context STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  project_id DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  line_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MRP_FORECAST_DATES (
  transaction_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  inventory_item_id,
  organization_id,
  forecast_designator,
  forecast_date,
  original_forecast_quantity,
  current_forecast_quantity,
  confidence_percentage,
  bucket_type,
  rate_end_date,
  origination_type,
  customer_id,
  ship_id,
  bill_id,
  comments,
  source_organization_id,
  source_forecast_designator,
  source_code,
  source_line_id,
  end_item_id,
  end_planning_bom_percent,
  forecast_rule_id,
  demand_usage_start_date,
  forecast_trend,
  focus_type,
  forecast_mad,
  demand_class,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  old_transaction_id,
  to_update,
  ddf_context,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  project_id,
  task_id,
  line_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  transaction_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  inventory_item_id,
  organization_id,
  forecast_designator,
  forecast_date,
  original_forecast_quantity,
  current_forecast_quantity,
  confidence_percentage,
  bucket_type,
  rate_end_date,
  origination_type,
  customer_id,
  ship_id,
  bill_id,
  comments,
  source_organization_id,
  source_forecast_designator,
  source_code,
  source_line_id,
  end_item_id,
  end_planning_bom_percent,
  forecast_rule_id,
  demand_usage_start_date,
  forecast_trend,
  focus_type,
  forecast_mad,
  demand_class,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  old_transaction_id,
  to_update,
  ddf_context,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  project_id,
  task_id,
  line_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MRP_FORECAST_DATES;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mrp_forecast_dates';