DROP TABLE IF EXISTS silver_bec_ods.ap_batches_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_batches_all (
  batch_id DECIMAL(15, 0),
  batch_name STRING,
  batch_date TIMESTAMP,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  control_invoice_count DECIMAL(15, 0),
  control_invoice_total DECIMAL(28, 10),
  actual_invoice_count DECIMAL(15, 0),
  actual_invoice_total DECIMAL(28, 10),
  invoice_currency_code STRING,
  payment_currency_code STRING,
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  pay_group_lookup_code STRING,
  batch_code_combination_id DECIMAL(15, 0),
  terms_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  invoice_type_lookup_code STRING,
  hold_lookup_code STRING,
  hold_reason STRING,
  doc_category_code STRING,
  org_id DECIMAL(15, 0),
  gl_date TIMESTAMP,
  payment_priority DECIMAL(2, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_batches_all (
  batch_id,
  batch_name,
  batch_date,
  last_update_date,
  last_updated_by,
  control_invoice_count,
  control_invoice_total,
  actual_invoice_count,
  actual_invoice_total,
  invoice_currency_code,
  payment_currency_code,
  last_update_login,
  creation_date,
  created_by,
  pay_group_lookup_code,
  batch_code_combination_id,
  terms_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  invoice_type_lookup_code,
  hold_lookup_code,
  hold_reason,
  doc_category_code,
  org_id,
  gl_date,
  payment_priority,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  batch_id,
  batch_name,
  batch_date,
  last_update_date,
  last_updated_by,
  control_invoice_count,
  control_invoice_total,
  actual_invoice_count,
  actual_invoice_total,
  invoice_currency_code,
  payment_currency_code,
  last_update_login,
  creation_date,
  created_by,
  pay_group_lookup_code,
  batch_code_combination_id,
  terms_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  invoice_type_lookup_code,
  hold_lookup_code,
  hold_reason,
  doc_category_code,
  org_id,
  gl_date,
  payment_priority,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ap_batches_all;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_batches_all';