DROP TABLE IF EXISTS silver_bec_ods.ap_bank_branches;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_bank_branches (
  bank_branch_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  bank_name STRING,
  bank_branch_name STRING,
  description STRING,
  address_line1 STRING,
  address_line2 STRING,
  address_line3 STRING,
  city STRING,
  state STRING,
  zip STRING,
  province STRING,
  country STRING,
  area_code STRING,
  phone STRING,
  contact_first_name STRING,
  contact_middle_name STRING,
  contact_last_name STRING,
  contact_prefix STRING,
  contact_title STRING,
  bank_num STRING,
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  institution_type STRING,
  clearing_house_id DECIMAL(15, 0),
  transmission_program_id DECIMAL(15, 0),
  printing_program_id DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  address_style STRING,
  bank_number STRING,
  address_line4 STRING,
  county STRING,
  eft_user_number STRING,
  eft_swift_code STRING,
  end_date TIMESTAMP,
  edi_id_number STRING,
  bank_branch_type STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  bank_name_alt STRING,
  bank_branch_name_alt STRING,
  address_lines_alt STRING,
  active_date TIMESTAMP,
  tp_header_id DECIMAL(15, 0),
  ece_tp_location_code STRING,
  payroll_bank_account_id DECIMAL(15, 0),
  rfc_identifier STRING,
  bank_admin_email STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_bank_branches (
  bank_branch_id,
  last_update_date,
  last_updated_by,
  bank_name,
  bank_branch_name,
  description,
  address_line1,
  address_line2,
  address_line3,
  city,
  state,
  zip,
  province,
  country,
  area_code,
  phone,
  contact_first_name,
  contact_middle_name,
  contact_last_name,
  contact_prefix,
  contact_title,
  bank_num,
  last_update_login,
  creation_date,
  created_by,
  institution_type,
  clearing_house_id,
  transmission_program_id,
  printing_program_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  address_style,
  bank_number,
  address_line4,
  county,
  eft_user_number,
  eft_swift_code,
  end_date,
  edi_id_number,
  bank_branch_type,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  bank_name_alt,
  bank_branch_name_alt,
  address_lines_alt,
  active_date,
  tp_header_id,
  ece_tp_location_code,
  payroll_bank_account_id,
  rfc_identifier,
  bank_admin_email,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  bank_branch_id,
  last_update_date,
  last_updated_by,
  bank_name,
  bank_branch_name,
  description,
  address_line1,
  address_line2,
  address_line3,
  city,
  state,
  zip,
  province,
  country,
  area_code,
  phone,
  contact_first_name,
  contact_middle_name,
  contact_last_name,
  contact_prefix,
  contact_title,
  bank_num,
  last_update_login,
  creation_date,
  created_by,
  institution_type,
  clearing_house_id,
  transmission_program_id,
  printing_program_id,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  address_style,
  bank_number,
  address_line4,
  county,
  eft_user_number,
  eft_swift_code,
  end_date,
  edi_id_number,
  bank_branch_type,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  bank_name_alt,
  bank_branch_name_alt,
  address_lines_alt,
  active_date,
  tp_header_id,
  ece_tp_location_code,
  payroll_bank_account_id,
  rfc_identifier,
  bank_admin_email,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ap_bank_branches;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_bank_branches';