DROP TABLE IF EXISTS silver_bec_ods.MTL_MATERIAL_TRANSACTIONS_TEMP;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_MATERIAL_TRANSACTIONS_TEMP (
  transaction_header_id DECIMAL(15, 0),
  transaction_temp_id DECIMAL(15, 0),
  source_code STRING,
  source_line_id DECIMAL(15, 0),
  transaction_mode DECIMAL(15, 0),
  lock_flag STRING,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  inventory_item_id DECIMAL(15, 0),
  revision STRING,
  organization_id DECIMAL(15, 0),
  subinventory_code STRING,
  locator_id DECIMAL(15, 0),
  transaction_quantity DECIMAL(28, 10),
  primary_quantity DECIMAL(28, 10),
  transaction_uom STRING,
  transaction_cost DECIMAL(28, 10),
  transaction_type_id DECIMAL(15, 0),
  transaction_action_id DECIMAL(15, 0),
  transaction_source_type_id DECIMAL(15, 0),
  transaction_source_id DECIMAL(15, 0),
  transaction_source_name STRING,
  transaction_date TIMESTAMP,
  acct_period_id DECIMAL(15, 0),
  distribution_account_id DECIMAL(15, 0),
  transaction_reference STRING,
  requisition_line_id DECIMAL(15, 0),
  requisition_distribution_id DECIMAL(15, 0),
  reason_id DECIMAL(15, 0),
  lot_number STRING,
  lot_expiration_date TIMESTAMP,
  serial_number STRING,
  receiving_document STRING,
  demand_id DECIMAL(15, 0),
  rcv_transaction_id DECIMAL(15, 0),
  move_transaction_id DECIMAL(15, 0),
  completion_transaction_id DECIMAL(15, 0),
  wip_entity_type DECIMAL(15, 0),
  schedule_id DECIMAL(15, 0),
  repetitive_line_id DECIMAL(15, 0),
  employee_code STRING,
  primary_switch DECIMAL(15, 0),
  schedule_update_code DECIMAL(15, 0),
  setup_teardown_code DECIMAL(15, 0),
  item_ordering DECIMAL(28, 10),
  negative_req_flag DECIMAL(28, 10),
  operation_seq_num DECIMAL(15, 0),
  picking_line_id DECIMAL(15, 0),
  trx_source_line_id DECIMAL(15, 0),
  trx_source_delivery_id DECIMAL(15, 0),
  physical_adjustment_id DECIMAL(15, 0),
  cycle_count_id DECIMAL(15, 0),
  rma_line_id DECIMAL(15, 0),
  customer_ship_id DECIMAL(15, 0),
  currency_code STRING,
  currency_conversion_rate DECIMAL(28, 10),
  currency_conversion_type STRING,
  currency_conversion_date TIMESTAMP,
  ussgl_transaction_code STRING,
  vendor_lot_number STRING,
  encumbrance_account DECIMAL(28, 10),
  encumbrance_amount DECIMAL(28, 10),
  ship_to_location DECIMAL(15, 0),
  shipment_number STRING,
  transfer_cost DECIMAL(28, 10),
  transportation_cost DECIMAL(28, 10),
  transportation_account DECIMAL(15, 0),
  freight_code STRING,
  containers DECIMAL(15, 0),
  waybill_airbill STRING,
  expected_arrival_date TIMESTAMP,
  transfer_subinventory STRING,
  transfer_organization DECIMAL(15, 0),
  transfer_to_location DECIMAL(15, 0),
  new_average_cost DECIMAL(28, 10),
  value_change DECIMAL(28, 10),
  percentage_change DECIMAL(28, 10),
  material_allocation_temp_id DECIMAL(15, 0),
  demand_source_header_id DECIMAL(15, 0),
  demand_source_line STRING,
  demand_source_delivery STRING,
  item_segments STRING,
  item_description STRING,
  item_trx_enabled_flag STRING,
  item_location_control_code DECIMAL(15, 0),
  item_restrict_subinv_code DECIMAL(15, 0),
  item_restrict_locators_code DECIMAL(15, 0),
  item_revision_qty_control_code DECIMAL(15, 0),
  item_primary_uom_code STRING,
  item_uom_class STRING,
  item_shelf_life_code DECIMAL(15, 0),
  item_shelf_life_days DECIMAL(15, 0),
  item_lot_control_code DECIMAL(15, 0),
  item_serial_control_code DECIMAL(15, 0),
  item_inventory_asset_flag STRING,
  allowed_units_lookup_code DECIMAL(15, 0),
  department_id DECIMAL(15, 0),
  department_code STRING,
  wip_supply_type DECIMAL(15, 0),
  supply_subinventory STRING,
  supply_locator_id DECIMAL(15, 0),
  valid_subinventory_flag STRING,
  valid_locator_flag STRING,
  locator_segments STRING,
  current_locator_control_code DECIMAL(15, 0),
  number_of_lots_entered DECIMAL(15, 0),
  wip_commit_flag STRING,
  next_lot_number STRING,
  lot_alpha_prefix STRING,
  next_serial_number STRING,
  serial_alpha_prefix STRING,
  shippable_flag STRING,
  posting_flag STRING,
  required_flag STRING,
  process_flag STRING,
  error_code STRING,
  error_explanation STRING,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  movement_id DECIMAL(15, 0),
  reservation_quantity DECIMAL(28, 10),
  shipped_quantity DECIMAL(28, 10),
  transaction_line_number DECIMAL(15, 0),
  task_id DECIMAL(15, 0),
  to_task_id DECIMAL(15, 0),
  source_task_id DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  source_project_id DECIMAL(15, 0),
  pa_expenditure_org_id DECIMAL(15, 0),
  to_project_id DECIMAL(15, 0),
  expenditure_type STRING,
  final_completion_flag STRING,
  transfer_percentage DECIMAL(28, 10),
  transaction_sequence_id DECIMAL(15, 0),
  material_account DECIMAL(28, 10),
  material_overhead_account DECIMAL(28, 10),
  resource_account DECIMAL(28, 10),
  outside_processing_account DECIMAL(28, 10),
  overhead_account DECIMAL(28, 10),
  flow_schedule STRING,
  cost_group_id DECIMAL(15, 0),
  demand_class STRING,
  qa_collection_id DECIMAL(15, 0),
  kanban_card_id DECIMAL(15, 0),
  overcompletion_transaction_qty DECIMAL(28, 10),
  overcompletion_primary_qty DECIMAL(28, 10),
  overcompletion_transaction_id DECIMAL(15, 0),
  end_item_unit_number STRING,
  scheduled_payback_date TIMESTAMP,
  line_type_code DECIMAL(15, 0),
  parent_transaction_temp_id DECIMAL(15, 0),
  put_away_strategy_id DECIMAL(15, 0),
  put_away_rule_id DECIMAL(15, 0),
  pick_strategy_id DECIMAL(15, 0),
  pick_rule_id DECIMAL(15, 0),
  move_order_line_id DECIMAL(15, 0),
  task_group_id DECIMAL(15, 0),
  pick_slip_number DECIMAL(15, 0),
  reservation_id DECIMAL(15, 0),
  common_bom_seq_id DECIMAL(15, 0),
  common_routing_seq_id DECIMAL(15, 0),
  org_cost_group_id DECIMAL(15, 0),
  cost_type_id DECIMAL(15, 0),
  transaction_status DECIMAL(15, 0),
  standard_operation_id DECIMAL(15, 0),
  task_priority DECIMAL(15, 0),
  wms_task_type DECIMAL(15, 0),
  parent_line_id DECIMAL(15, 0),
  source_lot_number STRING,
  transfer_cost_group_id DECIMAL(15, 0),
  lpn_id DECIMAL(15, 0),
  transfer_lpn_id DECIMAL(15, 0),
  wms_task_status DECIMAL(15, 0),
  content_lpn_id DECIMAL(15, 0),
  container_item_id DECIMAL(15, 0),
  cartonization_id DECIMAL(15, 0),
  pick_slip_date TIMESTAMP,
  rebuild_item_id DECIMAL(15, 0),
  rebuild_serial_number STRING,
  rebuild_activity_id DECIMAL(15, 0),
  rebuild_job_name STRING,
  organization_type DECIMAL(15, 0),
  transfer_organization_type DECIMAL(15, 0),
  owning_organization_id DECIMAL(15, 0),
  owning_tp_type DECIMAL(15, 0),
  xfr_owning_organization_id DECIMAL(15, 0),
  transfer_owning_tp_type DECIMAL(15, 0),
  planning_organization_id DECIMAL(15, 0),
  planning_tp_type DECIMAL(15, 0),
  xfr_planning_organization_id DECIMAL(15, 0),
  transfer_planning_tp_type DECIMAL(15, 0),
  secondary_uom_code STRING,
  secondary_transaction_quantity DECIMAL(28, 10),
  allocated_lpn_id DECIMAL(15, 0),
  schedule_number STRING,
  scheduled_flag DECIMAL(15, 0),
  class_code STRING,
  schedule_group DECIMAL(15, 0),
  build_sequence DECIMAL(15, 0),
  bom_revision STRING,
  routing_revision STRING,
  bom_revision_date TIMESTAMP,
  routing_revision_date TIMESTAMP,
  alternate_bom_designator STRING,
  alternate_routing_designator STRING,
  transaction_batch_id DECIMAL(15, 0),
  transaction_batch_seq DECIMAL(15, 0),
  operation_plan_id DECIMAL(15, 0),
  intransit_account DECIMAL(15, 0),
  fob_point DECIMAL(28, 10),
  move_order_header_id DECIMAL(15, 0),
  serial_allocated_flag STRING,
  trx_flow_header_id DECIMAL(15, 0),
  logical_trx_type_code DECIMAL(15, 0),
  original_transaction_temp_id DECIMAL(15, 0),
  transfer_secondary_quantity DECIMAL(28, 10),
  transfer_secondary_uom STRING,
  relieve_reservations_flag STRING,
  relieve_high_level_rsv_flag STRING,
  transfer_price DECIMAL(28, 10),
  material_expense_account DECIMAL(28, 10),
  fulfillment_base STRING,
  nested_parent_line_id DECIMAL(15, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_MATERIAL_TRANSACTIONS_TEMP (
  transaction_header_id,
  transaction_temp_id,
  source_code,
  source_line_id,
  transaction_mode,
  lock_flag,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  inventory_item_id,
  revision,
  organization_id,
  subinventory_code,
  locator_id,
  transaction_quantity,
  primary_quantity,
  transaction_uom,
  transaction_cost,
  transaction_type_id,
  transaction_action_id,
  transaction_source_type_id,
  transaction_source_id,
  transaction_source_name,
  transaction_date,
  acct_period_id,
  distribution_account_id,
  transaction_reference,
  requisition_line_id,
  requisition_distribution_id,
  reason_id,
  lot_number,
  lot_expiration_date,
  serial_number,
  receiving_document,
  demand_id,
  rcv_transaction_id,
  move_transaction_id,
  completion_transaction_id,
  wip_entity_type,
  schedule_id,
  repetitive_line_id,
  employee_code,
  primary_switch,
  schedule_update_code,
  setup_teardown_code,
  item_ordering,
  negative_req_flag,
  operation_seq_num,
  picking_line_id,
  trx_source_line_id,
  trx_source_delivery_id,
  physical_adjustment_id,
  cycle_count_id,
  rma_line_id,
  customer_ship_id,
  currency_code,
  currency_conversion_rate,
  currency_conversion_type,
  currency_conversion_date,
  ussgl_transaction_code,
  vendor_lot_number,
  encumbrance_account,
  encumbrance_amount,
  ship_to_location,
  shipment_number,
  transfer_cost,
  transportation_cost,
  transportation_account,
  freight_code,
  containers,
  waybill_airbill,
  expected_arrival_date,
  transfer_subinventory,
  transfer_organization,
  transfer_to_location,
  new_average_cost,
  value_change,
  percentage_change,
  material_allocation_temp_id,
  demand_source_header_id,
  demand_source_line,
  demand_source_delivery,
  item_segments,
  item_description,
  item_trx_enabled_flag,
  item_location_control_code,
  item_restrict_subinv_code,
  item_restrict_locators_code,
  item_revision_qty_control_code,
  item_primary_uom_code,
  item_uom_class,
  item_shelf_life_code,
  item_shelf_life_days,
  item_lot_control_code,
  item_serial_control_code,
  item_inventory_asset_flag,
  allowed_units_lookup_code,
  department_id,
  department_code,
  wip_supply_type,
  supply_subinventory,
  supply_locator_id,
  valid_subinventory_flag,
  valid_locator_flag,
  locator_segments,
  current_locator_control_code,
  number_of_lots_entered,
  wip_commit_flag,
  next_lot_number,
  lot_alpha_prefix,
  next_serial_number,
  serial_alpha_prefix,
  shippable_flag,
  posting_flag,
  required_flag,
  process_flag,
  error_code,
  error_explanation,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  movement_id,
  reservation_quantity,
  shipped_quantity,
  transaction_line_number,
  task_id,
  to_task_id,
  source_task_id,
  project_id,
  source_project_id,
  pa_expenditure_org_id,
  to_project_id,
  expenditure_type,
  final_completion_flag,
  transfer_percentage,
  transaction_sequence_id,
  material_account,
  material_overhead_account,
  resource_account,
  outside_processing_account,
  overhead_account,
  flow_schedule,
  cost_group_id,
  demand_class,
  qa_collection_id,
  kanban_card_id,
  overcompletion_transaction_qty,
  overcompletion_primary_qty,
  overcompletion_transaction_id,
  end_item_unit_number,
  scheduled_payback_date,
  line_type_code,
  parent_transaction_temp_id,
  put_away_strategy_id,
  put_away_rule_id,
  pick_strategy_id,
  pick_rule_id,
  move_order_line_id,
  task_group_id,
  pick_slip_number,
  reservation_id,
  common_bom_seq_id,
  common_routing_seq_id,
  org_cost_group_id,
  cost_type_id,
  transaction_status,
  standard_operation_id,
  task_priority,
  wms_task_type,
  parent_line_id,
  source_lot_number,
  transfer_cost_group_id,
  lpn_id,
  transfer_lpn_id,
  wms_task_status,
  content_lpn_id,
  container_item_id,
  cartonization_id,
  pick_slip_date,
  rebuild_item_id,
  rebuild_serial_number,
  rebuild_activity_id,
  rebuild_job_name,
  organization_type,
  transfer_organization_type,
  owning_organization_id,
  owning_tp_type,
  xfr_owning_organization_id,
  transfer_owning_tp_type,
  planning_organization_id,
  planning_tp_type,
  xfr_planning_organization_id,
  transfer_planning_tp_type,
  secondary_uom_code,
  secondary_transaction_quantity,
  allocated_lpn_id,
  schedule_number,
  scheduled_flag,
  class_code,
  schedule_group,
  build_sequence,
  bom_revision,
  routing_revision,
  bom_revision_date,
  routing_revision_date,
  alternate_bom_designator,
  alternate_routing_designator,
  transaction_batch_id,
  transaction_batch_seq,
  operation_plan_id,
  intransit_account,
  fob_point,
  move_order_header_id,
  serial_allocated_flag,
  trx_flow_header_id,
  logical_trx_type_code,
  original_transaction_temp_id,
  transfer_secondary_quantity,
  transfer_secondary_uom,
  relieve_reservations_flag,
  relieve_high_level_rsv_flag,
  transfer_price,
  material_expense_account,
  fulfillment_base,
  nested_parent_line_id,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  transaction_header_id,
  transaction_temp_id,
  source_code,
  source_line_id,
  transaction_mode,
  lock_flag,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  inventory_item_id,
  revision,
  organization_id,
  subinventory_code,
  locator_id,
  transaction_quantity,
  primary_quantity,
  transaction_uom,
  transaction_cost,
  transaction_type_id,
  transaction_action_id,
  transaction_source_type_id,
  transaction_source_id,
  transaction_source_name,
  transaction_date,
  acct_period_id,
  distribution_account_id,
  transaction_reference,
  requisition_line_id,
  requisition_distribution_id,
  reason_id,
  lot_number,
  lot_expiration_date,
  serial_number,
  receiving_document,
  demand_id,
  rcv_transaction_id,
  move_transaction_id,
  completion_transaction_id,
  wip_entity_type,
  schedule_id,
  repetitive_line_id,
  employee_code,
  primary_switch,
  schedule_update_code,
  setup_teardown_code,
  item_ordering,
  negative_req_flag,
  operation_seq_num,
  picking_line_id,
  trx_source_line_id,
  trx_source_delivery_id,
  physical_adjustment_id,
  cycle_count_id,
  rma_line_id,
  customer_ship_id,
  currency_code,
  currency_conversion_rate,
  currency_conversion_type,
  currency_conversion_date,
  ussgl_transaction_code,
  vendor_lot_number,
  encumbrance_account,
  encumbrance_amount,
  ship_to_location,
  shipment_number,
  transfer_cost,
  transportation_cost,
  transportation_account,
  freight_code,
  containers,
  waybill_airbill,
  expected_arrival_date,
  transfer_subinventory,
  transfer_organization,
  transfer_to_location,
  new_average_cost,
  value_change,
  percentage_change,
  material_allocation_temp_id,
  demand_source_header_id,
  demand_source_line,
  demand_source_delivery,
  item_segments,
  item_description,
  item_trx_enabled_flag,
  item_location_control_code,
  item_restrict_subinv_code,
  item_restrict_locators_code,
  item_revision_qty_control_code,
  item_primary_uom_code,
  item_uom_class,
  item_shelf_life_code,
  item_shelf_life_days,
  item_lot_control_code,
  item_serial_control_code,
  item_inventory_asset_flag,
  allowed_units_lookup_code,
  department_id,
  department_code,
  wip_supply_type,
  supply_subinventory,
  supply_locator_id,
  valid_subinventory_flag,
  valid_locator_flag,
  locator_segments,
  current_locator_control_code,
  number_of_lots_entered,
  wip_commit_flag,
  next_lot_number,
  lot_alpha_prefix,
  next_serial_number,
  serial_alpha_prefix,
  shippable_flag,
  posting_flag,
  required_flag,
  process_flag,
  error_code,
  error_explanation,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  movement_id,
  reservation_quantity,
  shipped_quantity,
  transaction_line_number,
  task_id,
  to_task_id,
  source_task_id,
  project_id,
  source_project_id,
  pa_expenditure_org_id,
  to_project_id,
  expenditure_type,
  final_completion_flag,
  transfer_percentage,
  transaction_sequence_id,
  material_account,
  material_overhead_account,
  resource_account,
  outside_processing_account,
  overhead_account,
  flow_schedule,
  cost_group_id,
  demand_class,
  qa_collection_id,
  kanban_card_id,
  overcompletion_transaction_qty,
  overcompletion_primary_qty,
  overcompletion_transaction_id,
  end_item_unit_number,
  scheduled_payback_date,
  line_type_code,
  parent_transaction_temp_id,
  put_away_strategy_id,
  put_away_rule_id,
  pick_strategy_id,
  pick_rule_id,
  move_order_line_id,
  task_group_id,
  pick_slip_number,
  reservation_id,
  common_bom_seq_id,
  common_routing_seq_id,
  org_cost_group_id,
  cost_type_id,
  transaction_status,
  standard_operation_id,
  task_priority,
  wms_task_type,
  parent_line_id,
  source_lot_number,
  transfer_cost_group_id,
  lpn_id,
  transfer_lpn_id,
  wms_task_status,
  content_lpn_id,
  container_item_id,
  cartonization_id,
  pick_slip_date,
  rebuild_item_id,
  rebuild_serial_number,
  rebuild_activity_id,
  rebuild_job_name,
  organization_type,
  transfer_organization_type,
  owning_organization_id,
  owning_tp_type,
  xfr_owning_organization_id,
  transfer_owning_tp_type,
  planning_organization_id,
  planning_tp_type,
  xfr_planning_organization_id,
  transfer_planning_tp_type,
  secondary_uom_code,
  secondary_transaction_quantity,
  allocated_lpn_id,
  schedule_number,
  scheduled_flag,
  class_code,
  schedule_group,
  build_sequence,
  bom_revision,
  routing_revision,
  bom_revision_date,
  routing_revision_date,
  alternate_bom_designator,
  alternate_routing_designator,
  transaction_batch_id,
  transaction_batch_seq,
  operation_plan_id,
  intransit_account,
  fob_point,
  move_order_header_id,
  serial_allocated_flag,
  trx_flow_header_id,
  logical_trx_type_code,
  original_transaction_temp_id,
  transfer_secondary_quantity,
  transfer_secondary_uom,
  relieve_reservations_flag,
  relieve_high_level_rsv_flag,
  transfer_price,
  material_expense_account,
  fulfillment_base,
  nested_parent_line_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_MATERIAL_TRANSACTIONS_TEMP;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_material_transactions_temp';