DROP table IF EXISTS silver_bec_ods.MTL_TRANSACTION_TYPES;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_TRANSACTION_TYPES (
  transaction_type_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  transaction_type_name STRING,
  description STRING,
  transaction_action_id DECIMAL(15, 0),
  transaction_source_type_id DECIMAL(15, 0),
  disable_date TIMESTAMP,
  user_defined_flag STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  attribute_category STRING,
  type_class DECIMAL(15, 0),
  shortage_msg_background_flag STRING,
  shortage_msg_online_flag STRING,
  status_control_flag DECIMAL(15, 0),
  location_required_flag STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_TRANSACTION_TYPES (
  transaction_type_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  transaction_type_name,
  description,
  transaction_action_id,
  transaction_source_type_id,
  disable_date,
  user_defined_flag,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  attribute_category,
  type_class,
  shortage_msg_background_flag,
  shortage_msg_online_flag,
  status_control_flag,
  location_required_flag,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    transaction_type_id,
    last_update_date,
    last_updated_by,
    creation_date,
    created_by,
    transaction_type_name,
    description,
    transaction_action_id,
    transaction_source_type_id,
    disable_date,
    user_defined_flag,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    attribute_category,
    type_class,
    shortage_msg_background_flag,
    shortage_msg_online_flag,
    status_control_flag,
    location_required_flag,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MTL_TRANSACTION_TYPES
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_transaction_types';