DROP TABLE IF EXISTS silver_bec_ods.XXBEC_SRVCREV_CDW_VARIABLE_STG;
CREATE TABLE IF NOT EXISTS silver_bec_ods.XXBEC_SRVCREV_CDW_VARIABLE_STG (
  source STRING,
  contract_group STRING,
  contract_id DECIMAL(15, 0),
  customer_trx_line_id DECIMAL(15, 0),
  gl_dist_id DECIMAL(15, 0),
  event_id DECIMAL(15, 0),
  actual_forecast STRING,
  ledger_id DECIMAL(15, 0),
  ledger_name STRING,
  org_id DECIMAL(15, 0),
  org_name STRING,
  site_id STRING,
  revenue_type STRING,
  transaction_currency STRING,
  accounted_currency STRING,
  period_name STRING,
  revenue_amount_trans_curr DECIMAL(28, 10),
  revenue_amount_acctd_curr DECIMAL(28, 10),
  conversion_rate DECIMAL(15, 0),
  tolling_rates_trans_curr DECIMAL(28, 10),
  tolling_rates_acctd_curr DECIMAL(28, 10),
  tmo_prcntge DECIMAL(28, 10),
  last_update_date TIMESTAMP,
  extract_date TIMESTAMP,
  from_date TIMESTAMP,
  to_date TIMESTAMP,
  period_end_date TIMESTAMP,
  no_days DECIMAL(15, 0),
  query_name STRING,
  kwh STRING,
  kwh_type STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.XXBEC_SRVCREV_CDW_VARIABLE_STG (
  `source`,
  contract_group,
  contract_id,
  customer_trx_line_id,
  gl_dist_id,
  event_id,
  actual_forecast,
  ledger_id,
  ledger_name,
  org_id,
  org_name,
  site_id,
  revenue_type,
  transaction_currency,
  accounted_currency,
  period_name,
  revenue_amount_trans_curr,
  revenue_amount_acctd_curr,
  conversion_rate,
  tolling_rates_trans_curr,
  tolling_rates_acctd_curr,
  tmo_prcntge,
  last_update_date,
  extract_date,
  from_date,
  to_date,
  period_end_date,
  no_days,
  query_name,
  kwh,
  kwh_type,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  `source`,
  contract_group,
  contract_id,
  customer_trx_line_id,
  gl_dist_id,
  event_id,
  actual_forecast,
  ledger_id,
  ledger_name,
  org_id,
  org_name,
  site_id,
  revenue_type,
  transaction_currency,
  accounted_currency,
  period_name,
  revenue_amount_trans_curr,
  revenue_amount_acctd_curr,
  conversion_rate,
  tolling_rates_trans_curr,
  tolling_rates_acctd_curr,
  tmo_prcntge,
  last_update_date,
  extract_date,
  from_date,
  to_date,
  period_end_date,
  no_days,
  query_name,
  kwh,
  kwh_type,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.XXBEC_SRVCREV_CDW_VARIABLE_STG;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'xxbec_srvcrev_cdw_variable_stg';