DROP TABLE IF EXISTS silver_bec_ods.AR_PAYMENT_SCHEDULES_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ar_payment_schedules_all (
  payment_schedule_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  due_date TIMESTAMP,
  amount_due_original DECIMAL(28, 10),
  amount_due_remaining DECIMAL(28, 10),
  number_of_due_dates DECIMAL(15, 0),
  status STRING,
  invoice_currency_code STRING,
  `class` STRING,
  cust_trx_type_id DECIMAL(15, 0),
  customer_id DECIMAL(15, 0),
  customer_site_use_id DECIMAL(15, 0),
  customer_trx_id DECIMAL(15, 0),
  cash_receipt_id DECIMAL(15, 0),
  associated_cash_receipt_id DECIMAL(15, 0),
  term_id DECIMAL(15, 0),
  terms_sequence_number DECIMAL(15, 0),
  gl_date_closed TIMESTAMP,
  actual_date_closed TIMESTAMP,
  discount_date TIMESTAMP,
  amount_line_items_original DECIMAL(28, 10),
  amount_line_items_remaining DECIMAL(28, 10),
  amount_applied DECIMAL(28, 10),
  amount_adjusted DECIMAL(28, 10),
  amount_in_dispute DECIMAL(28, 10),
  amount_credited DECIMAL(28, 10),
  receivables_charges_charged DECIMAL(28, 10),
  receivables_charges_remaining DECIMAL(28, 10),
  freight_original DECIMAL(28, 10),
  freight_remaining DECIMAL(28, 10),
  tax_original DECIMAL(28, 10),
  tax_remaining DECIMAL(28, 10),
  discount_original DECIMAL(28, 10),
  discount_remaining DECIMAL(28, 10),
  discount_taken_earned DECIMAL(28, 10),
  discount_taken_unearned DECIMAL(28, 10),
  in_collection STRING,
  cash_applied_id_last DECIMAL(15, 0),
  cash_applied_date_last TIMESTAMP,
  cash_applied_amount_last DECIMAL(28, 10),
  cash_applied_status_last STRING,
  cash_gl_date_last TIMESTAMP,
  cash_receipt_id_last DECIMAL(15, 0),
  cash_receipt_date_last TIMESTAMP,
  cash_receipt_amount_last DECIMAL(28, 10),
  cash_receipt_status_last STRING,
  exchange_rate_type STRING,
  exchange_date TIMESTAMP,
  exchange_rate DECIMAL(28, 10),
  adjustment_id_last DECIMAL(15, 0),
  adjustment_date_last TIMESTAMP,
  adjustment_gl_date_last TIMESTAMP,
  adjustment_amount_last DECIMAL(28, 10),
  follow_up_date_last TIMESTAMP,
  follow_up_code_last STRING,
  promise_date_last TIMESTAMP,
  promise_amount_last DECIMAL(28, 10),
  collector_last DECIMAL(15, 0),
  call_date_last TIMESTAMP,
  trx_number STRING,
  trx_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  reversed_cash_receipt_id DECIMAL(15, 0),
  amount_adjusted_pending DECIMAL(28, 10),
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  gl_date TIMESTAMP,
  acctd_amount_due_remaining DECIMAL(28, 10),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  receipt_confirmed_flag STRING,
  request_id DECIMAL(15, 0),
  selected_for_receipt_batch_id DECIMAL(15, 0),
  last_charge_date TIMESTAMP,
  second_last_charge_date TIMESTAMP,
  dispute_date TIMESTAMP,
  org_id DECIMAL(15, 0),
  staged_dunning_level DECIMAL(2, 0),
  dunning_level_override_date TIMESTAMP,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  global_attribute_category STRING,
  cons_inv_id DECIMAL(15, 0),
  cons_inv_id_rev DECIMAL(15, 0),
  exclude_from_dunning_flag STRING,
  mrc_customer_trx_id STRING,
  mrc_exchange_rate_type STRING,
  mrc_exchange_date STRING,
  mrc_exchange_rate STRING,
  mrc_acctd_amount_due_remaining STRING,
  br_amount_assigned DECIMAL(28, 10),
  reserved_type STRING,
  reserved_value DECIMAL(15, 0),
  active_claim_flag STRING,
  exclude_from_cons_bill_flag STRING,
  payment_approval STRING,
  kca_operation STRING,
  is_deleted_flg STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.AR_PAYMENT_SCHEDULES_ALL (
  payment_schedule_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  due_date,
  amount_due_original,
  amount_due_remaining,
  number_of_due_dates,
  status,
  invoice_currency_code,
  `class`,
  cust_trx_type_id,
  customer_id,
  customer_site_use_id,
  customer_trx_id,
  cash_receipt_id,
  associated_cash_receipt_id,
  term_id,
  terms_sequence_number,
  gl_date_closed,
  actual_date_closed,
  discount_date,
  amount_line_items_original,
  amount_line_items_remaining,
  amount_applied,
  amount_adjusted,
  amount_in_dispute,
  amount_credited,
  receivables_charges_charged,
  receivables_charges_remaining,
  freight_original,
  freight_remaining,
  tax_original,
  tax_remaining,
  discount_original,
  discount_remaining,
  discount_taken_earned,
  discount_taken_unearned,
  in_collection,
  cash_applied_id_last,
  cash_applied_date_last,
  cash_applied_amount_last,
  cash_applied_status_last,
  cash_gl_date_last,
  cash_receipt_id_last,
  cash_receipt_date_last,
  cash_receipt_amount_last,
  cash_receipt_status_last,
  exchange_rate_type,
  exchange_date,
  exchange_rate,
  adjustment_id_last,
  adjustment_date_last,
  adjustment_gl_date_last,
  adjustment_amount_last,
  follow_up_date_last,
  follow_up_code_last,
  promise_date_last,
  promise_amount_last,
  collector_last,
  call_date_last,
  trx_number,
  trx_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  reversed_cash_receipt_id,
  amount_adjusted_pending,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  gl_date,
  acctd_amount_due_remaining,
  program_application_id,
  program_id,
  program_update_date,
  receipt_confirmed_flag,
  request_id,
  selected_for_receipt_batch_id,
  last_charge_date,
  second_last_charge_date,
  dispute_date,
  org_id,
  staged_dunning_level,
  dunning_level_override_date,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  cons_inv_id,
  cons_inv_id_rev,
  exclude_from_dunning_flag,
  mrc_customer_trx_id,
  mrc_exchange_rate_type,
  mrc_exchange_date,
  mrc_exchange_rate,
  mrc_acctd_amount_due_remaining,
  br_amount_assigned,
  reserved_type,
  reserved_value,
  active_claim_flag,
  exclude_from_cons_bill_flag,
  payment_approval,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  payment_schedule_id,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  due_date,
  amount_due_original,
  amount_due_remaining,
  number_of_due_dates,
  status,
  invoice_currency_code,
  `class`,
  cust_trx_type_id,
  customer_id,
  customer_site_use_id,
  customer_trx_id,
  cash_receipt_id,
  associated_cash_receipt_id,
  term_id,
  terms_sequence_number,
  gl_date_closed,
  actual_date_closed,
  discount_date,
  amount_line_items_original,
  amount_line_items_remaining,
  amount_applied,
  amount_adjusted,
  amount_in_dispute,
  amount_credited,
  receivables_charges_charged,
  receivables_charges_remaining,
  freight_original,
  freight_remaining,
  tax_original,
  tax_remaining,
  discount_original,
  discount_remaining,
  discount_taken_earned,
  discount_taken_unearned,
  in_collection,
  cash_applied_id_last,
  cash_applied_date_last,
  cash_applied_amount_last,
  cash_applied_status_last,
  cash_gl_date_last,
  cash_receipt_id_last,
  cash_receipt_date_last,
  cash_receipt_amount_last,
  cash_receipt_status_last,
  exchange_rate_type,
  exchange_date,
  exchange_rate,
  adjustment_id_last,
  adjustment_date_last,
  adjustment_gl_date_last,
  adjustment_amount_last,
  follow_up_date_last,
  follow_up_code_last,
  promise_date_last,
  promise_amount_last,
  collector_last,
  call_date_last,
  trx_number,
  trx_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  reversed_cash_receipt_id,
  amount_adjusted_pending,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  gl_date,
  acctd_amount_due_remaining,
  program_application_id,
  program_id,
  program_update_date,
  receipt_confirmed_flag,
  request_id,
  selected_for_receipt_batch_id,
  last_charge_date,
  second_last_charge_date,
  dispute_date,
  org_id,
  staged_dunning_level,
  dunning_level_override_date,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  global_attribute_category,
  cons_inv_id,
  cons_inv_id_rev,
  exclude_from_dunning_flag,
  mrc_customer_trx_id,
  mrc_exchange_rate_type,
  mrc_exchange_date,
  mrc_exchange_rate,
  mrc_acctd_amount_due_remaining,
  br_amount_assigned,
  reserved_type,
  reserved_value,
  active_claim_flag,
  exclude_from_cons_bill_flag,
  payment_approval,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.AR_PAYMENT_SCHEDULES_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ar_payment_schedules_all';