DROP TABLE IF EXISTS silver_bec_ods.ap_payment_hist_dists;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_payment_hist_dists (
  payment_hist_dist_id DECIMAL(15, 0),
  accounting_event_id DECIMAL(15, 0),
  pay_dist_lookup_code STRING,
  invoice_distribution_id DECIMAL(15, 0),
  amount DECIMAL(28, 10),
  payment_history_id DECIMAL(15, 0),
  invoice_payment_id DECIMAL(15, 0),
  bank_curr_amount DECIMAL(28, 10),
  cleared_base_amount DECIMAL(28, 10),
  historical_flag STRING,
  invoice_dist_amount DECIMAL(28, 10),
  invoice_dist_base_amount DECIMAL(28, 10),
  invoice_adjustment_event_id DECIMAL(15, 0),
  matured_base_amount DECIMAL(28, 10),
  paid_base_amount DECIMAL(28, 10),
  rounding_amt DECIMAL(28, 10),
  reversal_flag STRING,
  reversed_pay_hist_dist_id DECIMAL(15, 0),
  created_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_login_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  request_id DECIMAL(15, 0),
  awt_related_id DECIMAL(15, 0),
  release_inv_dist_derived_from DECIMAL(15, 0),
  pa_addition_flag STRING,
  amount_variance DECIMAL(28, 10),
  invoice_base_amt_variance DECIMAL(28, 10),
  quantity_variance DECIMAL(28, 10),
  invoice_base_qty_variance DECIMAL(28, 10),
  GAIN_LOSS_INDICATOR STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_payment_hist_dists (
  payment_hist_dist_id,
  accounting_event_id,
  pay_dist_lookup_code,
  invoice_distribution_id,
  amount,
  payment_history_id,
  invoice_payment_id,
  bank_curr_amount,
  cleared_base_amount,
  historical_flag,
  invoice_dist_amount,
  invoice_dist_base_amount,
  invoice_adjustment_event_id,
  matured_base_amount,
  paid_base_amount,
  rounding_amt,
  reversal_flag,
  reversed_pay_hist_dist_id,
  created_by,
  creation_date,
  last_update_date,
  last_updated_by,
  last_update_login,
  program_application_id,
  program_id,
  program_login_id,
  program_update_date,
  request_id,
  awt_related_id,
  release_inv_dist_derived_from,
  pa_addition_flag,
  amount_variance,
  invoice_base_amt_variance,
  quantity_variance,
  invoice_base_qty_variance,
  GAIN_LOSS_INDICATOR,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    payment_hist_dist_id,
    accounting_event_id,
    pay_dist_lookup_code,
    invoice_distribution_id,
    amount,
    payment_history_id,
    invoice_payment_id,
    bank_curr_amount,
    cleared_base_amount,
    historical_flag,
    invoice_dist_amount,
    invoice_dist_base_amount,
    invoice_adjustment_event_id,
    matured_base_amount,
    paid_base_amount,
    rounding_amt,
    reversal_flag,
    reversed_pay_hist_dist_id,
    created_by,
    creation_date,
    last_update_date,
    last_updated_by,
    last_update_login,
    program_application_id,
    program_id,
    program_login_id,
    program_update_date,
    request_id,
    awt_related_id,
    release_inv_dist_derived_from,
    pa_addition_flag,
    amount_variance,
    invoice_base_amt_variance,
    quantity_variance,
    invoice_base_qty_variance,
    GAIN_LOSS_INDICATOR,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.ap_payment_hist_dists
);
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_payment_hist_dists';