DROP TABLE IF EXISTS silver_bec_ods.FA_MC_DEPRN_SUMMARY;
CREATE TABLE IF NOT EXISTS silver_bec_ods.FA_MC_DEPRN_SUMMARY (
  set_of_books_id DECIMAL(15, 0),
  book_type_code STRING,
  asset_id DECIMAL(15, 0),
  deprn_run_date TIMESTAMP,
  deprn_amount DECIMAL(28, 10),
  ytd_deprn DECIMAL(28, 10),
  deprn_reserve DECIMAL(28, 10),
  deprn_source_code STRING,
  adjusted_cost DECIMAL(28, 10),
  bonus_rate DECIMAL(28, 10),
  ltd_production DECIMAL(28, 10),
  period_counter DECIMAL(15, 0),
  production DECIMAL(28, 10),
  reval_amortization DECIMAL(28, 10),
  reval_amortization_basis DECIMAL(28, 10),
  reval_deprn_expense DECIMAL(28, 10),
  reval_reserve DECIMAL(28, 10),
  ytd_production DECIMAL(28, 10),
  ytd_reval_deprn_expense DECIMAL(28, 10),
  prior_fy_expense DECIMAL(28, 10),
  converted_flag STRING,
  bonus_deprn_amount DECIMAL(28, 10),
  bonus_ytd_deprn DECIMAL(28, 10),
  bonus_deprn_reserve DECIMAL(28, 10),
  prior_fy_bonus_expense DECIMAL(28, 10),
  deprn_override_flag STRING,
  system_deprn_amount DECIMAL(28, 10),
  system_bonus_deprn_amount DECIMAL(28, 10),
  event_id DECIMAL(15, 0),
  deprn_run_id DECIMAL(15, 0),
  deprn_adjustment_amount DECIMAL(28, 10),
  bonus_deprn_adjustment_amount DECIMAL(28, 10),
  impairment_amount DECIMAL(28, 10),
  ytd_impairment DECIMAL(28, 10),
  impairment_reserve DECIMAL(28, 10),
  capital_adjustment DECIMAL(28, 10),
  general_fund DECIMAL(28, 10),
  reval_loss_balance DECIMAL(28, 10),
  UNREVALUED_COST DECIMAL(28, 10),
  HISTORICAL_NBV DECIMAL(28, 10),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.FA_MC_DEPRN_SUMMARY (
  set_of_books_id,
  book_type_code,
  asset_id,
  deprn_run_date,
  deprn_amount,
  ytd_deprn,
  deprn_reserve,
  deprn_source_code,
  adjusted_cost,
  bonus_rate,
  ltd_production,
  period_counter,
  production,
  reval_amortization,
  reval_amortization_basis,
  reval_deprn_expense,
  reval_reserve,
  ytd_production,
  ytd_reval_deprn_expense,
  prior_fy_expense,
  converted_flag,
  bonus_deprn_amount,
  bonus_ytd_deprn,
  bonus_deprn_reserve,
  prior_fy_bonus_expense,
  deprn_override_flag,
  system_deprn_amount,
  system_bonus_deprn_amount,
  event_id,
  deprn_run_id,
  deprn_adjustment_amount,
  bonus_deprn_adjustment_amount,
  impairment_amount,
  ytd_impairment,
  impairment_reserve,
  capital_adjustment,
  general_fund,
  reval_loss_balance,
  UNREVALUED_COST,
  HISTORICAL_NBV,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  set_of_books_id,
  book_type_code,
  asset_id,
  deprn_run_date,
  deprn_amount,
  ytd_deprn,
  deprn_reserve,
  deprn_source_code,
  adjusted_cost,
  bonus_rate,
  ltd_production,
  period_counter,
  production,
  reval_amortization,
  reval_amortization_basis,
  reval_deprn_expense,
  reval_reserve,
  ytd_production,
  ytd_reval_deprn_expense,
  prior_fy_expense,
  converted_flag,
  bonus_deprn_amount,
  bonus_ytd_deprn,
  bonus_deprn_reserve,
  prior_fy_bonus_expense,
  deprn_override_flag,
  system_deprn_amount,
  system_bonus_deprn_amount,
  event_id,
  deprn_run_id,
  deprn_adjustment_amount,
  bonus_deprn_adjustment_amount,
  impairment_amount,
  ytd_impairment,
  impairment_reserve,
  capital_adjustment,
  general_fund,
  reval_loss_balance,
  UNREVALUED_COST,
  HISTORICAL_NBV,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.FA_MC_DEPRN_SUMMARY;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fa_mc_deprn_summary';