DROP TABLE IF EXISTS silver_bec_ods.MTL_ITEM_REVISIONS_B;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MTL_ITEM_REVISIONS_B (
  inventory_item_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  revision STRING,
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  change_notice STRING,
  ecn_initiation_date TIMESTAMP,
  implementation_date TIMESTAMP,
  implemented_serial_number STRING,
  effectivity_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  revised_item_sequence_id DECIMAL(15, 0),
  description STRING,
  object_version_number DECIMAL(9, 0),
  revision_id DECIMAL(15, 0),
  revision_label STRING,
  revision_reason STRING,
  lifecycle_id DECIMAL(15, 0),
  current_phase_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MTL_ITEM_REVISIONS_B (
  inventory_item_id,
  organization_id,
  revision,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  change_notice,
  ecn_initiation_date,
  implementation_date,
  implemented_serial_number,
  effectivity_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  revised_item_sequence_id,
  description,
  object_version_number,
  revision_id,
  revision_label,
  revision_reason,
  lifecycle_id,
  current_phase_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  inventory_item_id,
  organization_id,
  revision,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  change_notice,
  ecn_initiation_date,
  implementation_date,
  implemented_serial_number,
  effectivity_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  revised_item_sequence_id,
  description,
  object_version_number,
  revision_id,
  revision_label,
  revision_reason,
  lifecycle_id,
  current_phase_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MTL_ITEM_REVISIONS_B;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_item_revisions_b';