DROP TABLE IF EXISTS silver_bec_ods.PO_RELEASES_ALL;
CREATE TABLE IF NOT EXISTS silver_bec_ods.po_releases_all (
  po_release_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  po_header_id DECIMAL(15, 0),
  release_num DECIMAL(15, 0),
  agent_id DECIMAL(9, 0),
  release_date TIMESTAMP,
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  revision_num DECIMAL(15, 0),
  revised_date TIMESTAMP,
  approved_flag STRING,
  approved_date TIMESTAMP,
  print_count DECIMAL(15, 0),
  printed_date TIMESTAMP,
  acceptance_required_flag STRING,
  acceptance_due_date TIMESTAMP,
  hold_by DECIMAL(9, 0),
  hold_date TIMESTAMP,
  hold_reason STRING,
  hold_flag STRING,
  cancel_flag STRING,
  cancelled_by DECIMAL(9, 0),
  cancel_date TIMESTAMP,
  cancel_reason STRING,
  firm_status_lookup_code STRING,
  firm_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  authorization_status STRING,
  ussgl_transaction_code STRING,
  government_context STRING,
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  closed_code STRING,
  frozen_flag STRING,
  release_type STRING,
  note_to_vendor STRING,
  org_id DECIMAL(15, 0),
  edi_processed_flag STRING,
  global_attribute_category STRING,
  global_attribute1 STRING,
  global_attribute2 STRING,
  global_attribute3 STRING,
  global_attribute4 STRING,
  global_attribute5 STRING,
  global_attribute6 STRING,
  global_attribute7 STRING,
  global_attribute8 STRING,
  global_attribute9 STRING,
  global_attribute10 STRING,
  global_attribute11 STRING,
  global_attribute12 STRING,
  global_attribute13 STRING,
  global_attribute14 STRING,
  global_attribute15 STRING,
  global_attribute16 STRING,
  global_attribute17 STRING,
  global_attribute18 STRING,
  global_attribute19 STRING,
  global_attribute20 STRING,
  wf_item_type STRING,
  wf_item_key STRING,
  pcard_id DECIMAL(15, 0),
  pay_on_code STRING,
  xml_flag STRING,
  xml_send_date TIMESTAMP,
  xml_change_send_date TIMESTAMP,
  consigned_consumption_flag STRING,
  cbc_accounting_date TIMESTAMP,
  change_requested_by STRING,
  shipping_control STRING,
  change_summary STRING,
  vendor_order_num STRING,
  document_creation_method STRING,
  submit_date TIMESTAMP,
  tax_attribute_update_code STRING,
  comm_rev_num DECIMAL(15, 0),
  otm_status_code STRING,
  otm_recovery_flag STRING,
  `cancel_reason#1` STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.po_releases_all (
  po_release_id,
  last_update_date,
  last_updated_by,
  po_header_id,
  release_num,
  agent_id,
  release_date,
  last_update_login,
  creation_date,
  created_by,
  revision_num,
  revised_date,
  approved_flag,
  approved_date,
  print_count,
  printed_date,
  acceptance_required_flag,
  acceptance_due_date,
  hold_by,
  hold_date,
  hold_reason,
  hold_flag,
  cancel_flag,
  cancelled_by,
  cancel_date,
  cancel_reason,
  firm_status_lookup_code,
  firm_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  authorization_status,
  ussgl_transaction_code,
  government_context,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  closed_code,
  frozen_flag,
  release_type,
  note_to_vendor,
  org_id,
  edi_processed_flag,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  wf_item_type,
  wf_item_key,
  pcard_id,
  pay_on_code,
  xml_flag,
  xml_send_date,
  xml_change_send_date,
  consigned_consumption_flag,
  cbc_accounting_date,
  change_requested_by,
  shipping_control,
  change_summary,
  vendor_order_num,
  document_creation_method,
  submit_date,
  tax_attribute_update_code,
  comm_rev_num,
  otm_status_code,
  otm_recovery_flag,
  `cancel_reason#1`,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  po_release_id,
  last_update_date,
  last_updated_by,
  po_header_id,
  release_num,
  agent_id,
  release_date,
  last_update_login,
  creation_date,
  created_by,
  revision_num,
  revised_date,
  approved_flag,
  approved_date,
  print_count,
  printed_date,
  acceptance_required_flag,
  acceptance_due_date,
  hold_by,
  hold_date,
  hold_reason,
  hold_flag,
  cancel_flag,
  cancelled_by,
  cancel_date,
  cancel_reason,
  firm_status_lookup_code,
  firm_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  authorization_status,
  ussgl_transaction_code,
  government_context,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  closed_code,
  frozen_flag,
  release_type,
  note_to_vendor,
  org_id,
  edi_processed_flag,
  global_attribute_category,
  global_attribute1,
  global_attribute2,
  global_attribute3,
  global_attribute4,
  global_attribute5,
  global_attribute6,
  global_attribute7,
  global_attribute8,
  global_attribute9,
  global_attribute10,
  global_attribute11,
  global_attribute12,
  global_attribute13,
  global_attribute14,
  global_attribute15,
  global_attribute16,
  global_attribute17,
  global_attribute18,
  global_attribute19,
  global_attribute20,
  wf_item_type,
  wf_item_key,
  pcard_id,
  pay_on_code,
  xml_flag,
  xml_send_date,
  xml_change_send_date,
  consigned_consumption_flag,
  cbc_accounting_date,
  change_requested_by,
  shipping_control,
  change_summary,
  vendor_order_num,
  document_creation_method,
  submit_date,
  tax_attribute_update_code,
  comm_rev_num,
  otm_status_code,
  otm_recovery_flag,
  `cancel_reason#1`,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.po_releases_all;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'po_releases_all';