DROP TABLE IF EXISTS silver_bec_ods.ap_distribution_set_lines_all;
CREATE TABLE IF NOT EXISTS silver_bec_ods.ap_distribution_set_lines_all (
  distribution_set_id DECIMAL(15, 0),
  dist_code_combination_id DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  set_of_books_id DECIMAL(15, 0),
  percent_distribution DECIMAL(28, 10),
  type_1099 STRING,
  vat_code STRING,
  description STRING,
  last_update_login DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  distribution_set_line_number DECIMAL(15, 0),
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  project_accounting_context STRING,
  task_id DECIMAL(15, 0),
  project_id DECIMAL(15, 0),
  expenditure_organization_id DECIMAL(15, 0),
  expenditure_type STRING,
  org_id DECIMAL(15, 0),
  award_id DECIMAL(15, 0),
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.ap_distribution_set_lines_all (
  distribution_set_id,
  dist_code_combination_id,
  last_update_date,
  last_updated_by,
  set_of_books_id,
  percent_distribution,
  type_1099,
  vat_code,
  description,
  last_update_login,
  creation_date,
  created_by,
  distribution_set_line_number,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  project_accounting_context,
  task_id,
  project_id,
  expenditure_organization_id,
  expenditure_type,
  org_id,
  award_id,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  kca_seq_date
)
SELECT
  distribution_set_id,
  dist_code_combination_id,
  last_update_date,
  last_updated_by,
  set_of_books_id,
  percent_distribution,
  type_1099,
  vat_code,
  description,
  last_update_login,
  creation_date,
  created_by,
  distribution_set_line_number,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  project_accounting_context,
  task_id,
  project_id,
  expenditure_organization_id,
  expenditure_type,
  org_id,
  award_id,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.ap_distribution_set_lines_all;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ap_distribution_set_lines_all';