DROP TABLE IF EXISTS silver_bec_ods.XXBEC_MSC_ORDERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.XXBEC_MSC_ORDERS (
  plan_id DECIMAL(15, 0),
  compile_designator STRING,
  organization_code STRING,
  organization_id DECIMAL(15, 0),
  item_segments STRING,
  requested_start_date TIMESTAMP,
  requested_completion_date TIMESTAMP,
  order_type_text STRING,
  new_due_date TIMESTAMP,
  ship_set_name STRING,
  arrival_set_name STRING,
  schedule_arrival_date TIMESTAMP,
  schedule_ship_date TIMESTAMP,
  actual_start_date TIMESTAMP,
  planned_arrival_date TIMESTAMP,
  latest_acceptable_date TIMESTAMP,
  quantity_rate DECIMAL(28, 10),
  qty_by_due_date DECIMAL(15, 0),
  po_line_id DECIMAL(15, 0),
  shipment_id DECIMAL(15, 0),
  reschedule_days DECIMAL(15, 0),
  old_due_date TIMESTAMP,
  sr_instance_id DECIMAL(15, 0),
  disposition_id DECIMAL(15, 0),
  description STRING,
  original_item_name STRING,
  prev_subst_item STRING,
  prev_subst_org STRING,
  original_item_qty DECIMAL(28, 10),
  last_unit_completion_date TIMESTAMP,
  line_code STRING,
  expiration_date TIMESTAMP,
  order_number STRING,
  `action` STRING,
  mrp_planning_code_text STRING,
  old_order_quantity DECIMAL(28, 10),
  orig_org_code STRING,
  dest_org_code STRING,
  dest_org_id DECIMAL(15, 0),
  dest_inst_id DECIMAL(15, 0),
  ship_method STRING,
  orig_ship_method STRING,
  source_vendor_name STRING,
  source_vendor_site_code STRING,
  planning_group STRING,
  schedule_group_name STRING,
  quantity DECIMAL(28, 10),
  ship_date TIMESTAMP,
  assembly_demand_comp_date TIMESTAMP,
  planner_code STRING,
  order_type DECIMAL(15, 0),
  vendor_id DECIMAL(15, 0),
  vendor_site_id DECIMAL(15, 0),
  category_id DECIMAL(15, 0),
  source_vendor_site_id DECIMAL(15, 0),
  source_vendor_id DECIMAL(15, 0),
  supplier_name STRING,
  supplier_site_code STRING,
  subinventory_code STRING,
  mrp_planning_code DECIMAL(15, 0),
  source_organization_id DECIMAL(15, 0),
  status_code DECIMAL(15, 0),
  customer_id DECIMAL(15, 0),
  customer_name STRING,
  ship_to_site_id DECIMAL(15, 0),
  ship_to_site_name STRING,
  customer_site_id DECIMAL(15, 0),
  customer_site_name STRING,
  promise_date TIMESTAMP,
  promise_ship_date TIMESTAMP,
  original_need_by_date TIMESTAMP,
  request_date TIMESTAMP,
  request_ship_date TIMESTAMP,
  category_set_id DECIMAL(15, 0),
  sales_order_line_id DECIMAL(15, 0),
  ship_set_id DECIMAL(15, 0),
  customer_po_number STRING,
  customer_po_line_number STRING,
  buyer_name STRING,
  source_table STRING,
  transaction_id DECIMAL(15, 0),
  inventory_item_id DECIMAL(15, 0),
  new_order_date TIMESTAMP,
  new_dock_date TIMESTAMP,
  new_start_date TIMESTAMP,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.XXBEC_MSC_ORDERS (
  plan_id,
  compile_designator,
  organization_code,
  organization_id,
  item_segments,
  requested_start_date,
  requested_completion_date,
  order_type_text,
  new_due_date,
  ship_set_name,
  arrival_set_name,
  schedule_arrival_date,
  schedule_ship_date,
  actual_start_date,
  planned_arrival_date,
  latest_acceptable_date,
  quantity_rate,
  qty_by_due_date,
  po_line_id,
  shipment_id,
  reschedule_days,
  old_due_date,
  sr_instance_id,
  disposition_id,
  description,
  original_item_name,
  prev_subst_item,
  prev_subst_org,
  original_item_qty,
  last_unit_completion_date,
  line_code,
  expiration_date,
  order_number,
  `action`,
  mrp_planning_code_text,
  old_order_quantity,
  orig_org_code,
  dest_org_code,
  dest_org_id,
  dest_inst_id,
  ship_method,
  orig_ship_method,
  source_vendor_name,
  source_vendor_site_code,
  planning_group,
  schedule_group_name,
  quantity,
  ship_date,
  assembly_demand_comp_date,
  planner_code,
  order_type,
  vendor_id,
  vendor_site_id,
  category_id,
  source_vendor_site_id,
  source_vendor_id,
  supplier_name,
  supplier_site_code,
  subinventory_code,
  mrp_planning_code,
  source_organization_id,
  status_code,
  customer_id,
  customer_name,
  ship_to_site_id,
  ship_to_site_name,
  customer_site_id,
  customer_site_name,
  promise_date,
  promise_ship_date,
  original_need_by_date,
  request_date,
  request_ship_date,
  category_set_id,
  sales_order_line_id,
  ship_set_id,
  customer_po_number,
  customer_po_line_number,
  buyer_name,
  source_table,
  transaction_id,
  inventory_item_id,
  new_order_date,
  new_dock_date,
  new_start_date,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  plan_id,
  compile_designator,
  organization_code,
  organization_id,
  item_segments,
  requested_start_date,
  requested_completion_date,
  order_type_text,
  new_due_date,
  ship_set_name,
  arrival_set_name,
  schedule_arrival_date,
  schedule_ship_date,
  actual_start_date,
  planned_arrival_date,
  latest_acceptable_date,
  quantity_rate,
  qty_by_due_date,
  po_line_id,
  shipment_id,
  reschedule_days,
  old_due_date,
  sr_instance_id,
  disposition_id,
  description,
  original_item_name,
  prev_subst_item,
  prev_subst_org,
  original_item_qty,
  last_unit_completion_date,
  line_code,
  expiration_date,
  order_number,
  `action`,
  mrp_planning_code_text,
  old_order_quantity,
  orig_org_code,
  dest_org_code,
  dest_org_id,
  dest_inst_id,
  ship_method,
  orig_ship_method,
  source_vendor_name,
  source_vendor_site_code,
  planning_group,
  schedule_group_name,
  quantity,
  ship_date,
  assembly_demand_comp_date,
  planner_code,
  order_type,
  vendor_id,
  vendor_site_id,
  category_id,
  source_vendor_site_id,
  source_vendor_id,
  supplier_name,
  supplier_site_code,
  subinventory_code,
  mrp_planning_code,
  source_organization_id,
  status_code,
  customer_id,
  customer_name,
  ship_to_site_id,
  ship_to_site_name,
  customer_site_id,
  customer_site_name,
  promise_date,
  promise_ship_date,
  original_need_by_date,
  request_date,
  request_ship_date,
  category_set_id,
  sales_order_line_id,
  ship_set_id,
  customer_po_number,
  customer_po_line_number,
  buyer_name,
  source_table,
  transaction_id,
  inventory_item_id,
  new_order_date,
  new_dock_date,
  new_start_date,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.XXBEC_MSC_ORDERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'xxbec_msc_orders';