/* DDL generated by DBeaver */ /* WARNING: It may differ from actual native database DDL */
DROP TABLE gold_bec_dwh.fact_ascp_horizontal_plan_snp;
CREATE TABLE IF NOT EXISTS gold_bec_dwh.fact_ascp_horizontal_plan_snp (
  inventory_item_id DECIMAL(15, 0),
  organization_id DECIMAL(15, 0),
  plan_id DECIMAL(15, 0),
  category_set_id DECIMAL(15, 0),
  sr_instance_id DECIMAL(15, 0),
  fill_kill_flag DECIMAL(15, 0),
  so_line_split DECIMAL(28, 10),
  quantity_rate DECIMAL(38, 10),
  new_due_date DATE,
  order_type_entity STRING,
  plan_id_key STRING,
  organization_id_key STRING,
  inventory_item_id_key STRING,
  is_deleted_flg STRING,
  source_app_id INT,
  dw_load_id STRING,
  snp_date DATE,
  plan_name_archive_date STRING
);