/*
# COPYRIGHT(C) 2022 KPI PARTNERS, INC. ALL RIGHTS RESERVED.
#
# UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, SOFTWARE
# DISTRIBUTED UNDER THE LICENSE IS DISTRIBUTED ON AN "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
# AUTHOR: KPI PARTNERS, INC.
# VERSION: 2022.06
# DESCRIPTION: THIS SCRIPT REPRESENTS FULL LOAD APPROACH FOR STAGE.
# FILE VERSION: KPI V1.0
*/
BEGIN;

DROP TABLE IF EXISTS BEC_ODS_STG.MTL_TRANSACTION_TYPES;

CREATE TABLE BEC_ODS_STG.MTL_TRANSACTION_TYPES 
DISTKEY (TRANSACTION_TYPE_ID)
SORTKEY (TRANSACTION_TYPE_ID, TRANSACTION_TYPE_NAME, LAST_UPDATE_DATE)
AS 
SELECT
	*
	FROM
	BEC_RAW_DL_EXT.MTL_TRANSACTION_TYPES
WHERE
	KCA_OPERATION != 'DELETE'
	AND (NVL(TRANSACTION_TYPE_ID,0) ,NVL(TRANSACTION_TYPE_NAME,'NA') ,LAST_UPDATE_DATE) IN 
	(
	SELECT
		 NVL(TRANSACTION_TYPE_ID,0) AS TRANSACTION_TYPE_ID,NVL(TRANSACTION_TYPE_NAME,'NA') AS TRANSACTION_TYPE_NAME,MAX(LAST_UPDATE_DATE)
	FROM
		BEC_RAW_DL_EXT.MTL_TRANSACTION_TYPES
	WHERE
		KCA_OPERATION != 'DELETE'
		AND NVL(KCA_SEQ_ID, '') = ''
	GROUP BY
		NVL(TRANSACTION_TYPE_ID,0) ,NVL(TRANSACTION_TYPE_NAME,'NA')
	);
END;