/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for Dimensions.
# File Version: KPI v1.0
*/
begin;

drop table if exists bec_dwh.DIM_INV_EXP_PO_CAT;

create table bec_dwh.DIM_INV_EXP_PO_CAT 
	diststyle all
	sortkey (PO_HEADER_ID,PO_LINE_ID,CATEGORY_ID,CATEGORY_SET_ID)
as
select 
PO_HEADER_ID
,PO_LINE_ID
,INVENTORY_ITEM_ID
,ORGANIZATION_ID
,CATEGORY_SET_ID
,STRUCTURE_ID
,CATEGORY_ID
,ITEM_NAME
,ITEM_DESCRIPTION
,CATEGORY_SET_NAME
,CATEGORY_SET_DESC
,ITEM_CATEGORY_SEGMENT1
,ITEM_CATEGORY_SEGMENT2
,ITEM_CATEGORY_SEGMENT3
,ITEM_CATEGORY_SEGMENT4
,ITEM_CATEGORY_DESC
--Audit Columns
,'N' as is_deleted_flg,
(
select
	system_id
from
	bec_etl_ctrl.etlsourceappid
where
	source_system = 'EBS') as source_app_id,
(
select
	system_id
from
	bec_etl_ctrl.etlsourceappid
where
	source_system = 'EBS')
	|| '-' || nvl(INVENTORY_ITEM_ID, 0)
	|| '-' || nvl(ORGANIZATION_ID, 0)
	|| '-' || nvl(PO_HEADER_ID, 0)
	|| '-' || nvl(PO_LINE_ID, 0)
	|| '-' || nvl(CATEGORY_ID, 0) 
	|| '-' || nvl(CATEGORY_SET_ID, 0)  as dw_load_id,
getdate() as dw_insert_date,
getdate() as dw_update_date
from 
(
SELECT
PHA.PO_HEADER_ID,
PLA.PO_LINE_ID,
NULL INVENTORY_ITEM_ID,
NULL ORGANIZATION_ID,
NULL CATEGORY_SET_ID,
NVL(MC.STRUCTURE_ID, 0) AS STRUCTURE_ID,
NVL(PLA.CATEGORY_ID, 0) AS CATEGORY_ID,
NULL "ITEM_NAME",
NULL ITEM_DESCRIPTION,
NULL CATEGORY_SET_NAME,
NULL CATEGORY_SET_DESC,
MC.SEGMENT1 "ITEM_CATEGORY_SEGMENT1",
NVL (MC.SEGMENT2,'LEVEL2') "ITEM_CATEGORY_SEGMENT2",
NVL (MC.SEGMENT3,'LEVEL3') "ITEM_CATEGORY_SEGMENT3",
NVL (MC.SEGMENT4,'LEVEL4') "ITEM_CATEGORY_SEGMENT4",
MC.DESCRIPTION "ITEM_CATEGORY_DESC"
FROM
(SELECT STRUCTURE_ID,SEGMENT1,SEGMENT2,SEGMENT3,SEGMENT4,DESCRIPTION,CATEGORY_ID FROM BEC_ODS.MTL_CATEGORIES_B WHERE IS_DELETED_FLG <> 'Y')MC,
(SELECT PO_HEADER_ID FROM BEC_ODS.PO_HEADERS_ALL WHERE IS_DELETED_FLG <> 'Y')PHA,
(SELECT PO_HEADER_ID,PO_LINE_ID,CATEGORY_ID FROM BEC_ODS.PO_LINES_ALL WHERE IS_DELETED_FLG <> 'Y' AND ITEM_ID IS NULL)PLA
WHERE 1=1
AND PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
AND PLA.CATEGORY_ID = MC.CATEGORY_ID
UNION
SELECT    
PHA.PO_HEADER_ID,
PLA.PO_LINE_ID,
NVL(MIC.INVENTORY_ITEM_ID, 0) AS INVENTORY_ITEM_ID,
NVL(MIC.ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
NVL(MIC.CATEGORY_SET_ID, 0) AS CATEGORY_SET_ID,
NVL(MC.STRUCTURE_ID, 0) AS STRUCTURE_ID,
NVL(PLA.CATEGORY_ID, 0) AS CATEGORY_ID,
MSI.SEGMENT1 "ITEM_NAME",
PLA.ITEM_DESCRIPTION ITEM_DESCRIPTION,
CSET.CATEGORY_SET_NAME CATEGORY_SET_NAME,
CSET.DESCRIPTION CATEGORY_SET_DESC,
MC.SEGMENT1 "ITEM_CATEGORY_SEGMENT1",
NVL (MC.SEGMENT2,'LEVEL2') "ITEM_CATEGORY_SEGMENT2",
NVL (MC.SEGMENT3,'LEVEL3') "ITEM_CATEGORY_SEGMENT3",
NVL (MC.SEGMENT4,'LEVEL4') "ITEM_CATEGORY_SEGMENT4",
MC.DESCRIPTION "ITEM_CATEGORY_DESC"
FROM
(SELECT  INVENTORY_ITEM_ID,ORGANIZATION_ID,CATEGORY_SET_ID,CATEGORY_ID  FROM BEC_ODS.MTL_ITEM_CATEGORIES  WHERE IS_DELETED_FLG <> 'Y') MIC,
(SELECT  CATEGORY_SET_NAME,CATEGORY_SET_ID ,DESCRIPTION FROM BEC_ODS.MTL_CATEGORY_SETS_TL  WHERE IS_DELETED_FLG <> 'Y' 	AND LANGUAGE = 'US')CSET,
(SELECT  INVENTORY_ITEM_ID,ORGANIZATION_ID,SEGMENT1 FROM BEC_ODS.MTL_SYSTEM_ITEMS_B  WHERE IS_DELETED_FLG <> 'Y')MSI,
(SELECT STRUCTURE_ID,SEGMENT1,SEGMENT2,SEGMENT3,SEGMENT4,DESCRIPTION,CATEGORY_ID FROM BEC_ODS.MTL_CATEGORIES_B WHERE IS_DELETED_FLG <> 'Y')MC,
(SELECT PO_HEADER_ID FROM BEC_ODS.PO_HEADERS_ALL WHERE IS_DELETED_FLG <> 'Y')PHA,
(SELECT PO_LINE_ID,CATEGORY_ID,PO_HEADER_ID,ITEM_ID,ITEM_DESCRIPTION FROM BEC_ODS.PO_LINES_ALL WHERE IS_DELETED_FLG <> 'Y')PLA,
(SELECT SHIP_TO_ORGANIZATION_ID,PO_LINE_ID,PO_HEADER_ID   FROM BEC_ODS.PO_LINE_LOCATIONS_ALL  WHERE IS_DELETED_FLG <> 'Y')PLLA
WHERE 1=1
AND MIC.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
AND MIC.ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND MIC.CATEGORY_SET_ID = CSET.CATEGORY_SET_ID
AND MIC.CATEGORY_ID = MC.CATEGORY_ID
AND PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
AND PLA.ITEM_ID = MIC.INVENTORY_ITEM_ID
AND PLLA.SHIP_TO_ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND PLLA.PO_LINE_ID = PLA.PO_LINE_ID
AND PLLA.PO_HEADER_ID = PLA.PO_HEADER_ID
AND MIC.CATEGORY_SET_ID = 1100000043
);
        
end;

update
	bec_etl_ctrl.batch_dw_info
set
	load_type = 'I',
	last_refresh_date = getdate()
where
	dw_table_name = 'dim_inv_exp_po_cat'
	and batch_name = 'inv';

commit; 