/*
# COPYRIGHT(C) 2022 KPI PARTNERS, INC. ALL RIGHTS RESERVED.
#
# UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, SOFTWARE
# DISTRIBUTED UNDER THE LICENSE IS DISTRIBUTED ON AN "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
# AUTHOR: KPI PARTNERS, INC.
# VERSION: 2022.06
# DESCRIPTION: THIS SCRIPT REPRESENTS FULL LOAD APPROACH FOR DIMENSIONS.
# FILE VERSION: KPI V1.0
*/

BEGIN;
DROP TABLE IF EXISTS BEC_DWH.DIM_GLOBAL_CONVERSION;
CREATE TABLE BEC_DWH.DIM_GLOBAL_CONVERSION 
	DISTSTYLE ALL 
	SORTKEY (CONVERSION_DATE)
AS
(
SELECT 
	GLR.FROM_CURRENCY AS FROM_CURRENCY,
	GLR.TO_CURRENCY AS TO_CURRENCY,
	GLR.CONVERSION_DATE::DATE AS CONVERSION_DATE,
	GLR.CONVERSION_TYPE AS CONVERSION_TYPE,
	GLR.RATE_SOURCE_CODE AS RATE_SOURCE_CODE,
	GLR.CONVERSION_RATE AS CONVERSION_RATE,
	GLR.CONVERSION_RATE AS INVERSE_CONVERSION_RATE,
	-- AUDIT COLUMNS
	'N' AS IS_DELETED_FLG,
	(SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM='EBS') AS SOURCE_APP_ID,
	(SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM='EBS')
	||'-'||NVL(FROM_CURRENCY,'NA')||'-'||NVL(TO_CURRENCY,'NA')||'-'||NVL(CONVERSION_DATE::DATE,'1900-01-01')||'-'||
	NVL(CONVERSION_TYPE,'NA')||'-'||NVL(CONVERSION_RATE,0) AS DW_LOAD_ID,
	GETDATE() AS DW_INSERT_DATE,
	GETDATE() AS DW_UPDATE_DATE       
FROM BEC_ODS.GL_DAILY_RATES GLR
);

END;

update
	bec_etl_ctrl.batch_dw_info
set
	load_type = 'I',
	last_refresh_date = getdate()
where
	dw_table_name = 'dim_global_conversion'
	and batch_name = 'gl';

commit;