/*
# COPYRIGHT(C) 2022 KPI PARTNERS, INC. ALL RIGHTS RESERVED.
#
# UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, SOFTWARE
# DISTRIBUTED UNDER THE LICENSE IS DISTRIBUTED ON AN "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
# AUTHOR: KPI PARTNERS, INC.
# VERSION: 2022.06
# DESCRIPTION: THIS SCRIPT REPRESENTS FULL LOAD APPROACH FOR DIMENSIONS.
# FILE VERSION: KPI V1.0
*/

BEGIN;
DROP TABLE IF EXISTS BEC_DWH.DIM_SEGMENT3;
CREATE TABLE BEC_DWH.DIM_SEGMENT3 	DISTSTYLE ALL SORTKEY (LEDGER_ID,CHART_OF_ACCOUNTS_ID,FLEX_VALUE_SET_ID,LEVEL0_VALUE,SEGMENT_NAME)
AS
(
SELECT DISTINCT 
	S1.CHART_OF_ACCOUNTS_ID AS CHART_OF_ACCOUNTS_ID,
	S1.FLEX_VALUE_SET_ID AS FLEX_VALUE_SET_ID,
	S1.LEDGER_ID AS LEDGER_ID,
	S1.LEDGER_NAME AS LEDGER_NAME,
	CONCAT(S1.CHART_OF_ACCOUNTS_ID, CONCAT('-', F1.FLEX_VALUE)) AS COA_SEGVAL,
	F1.FLEX_VALUE AS LEVEL0_VALUE,
	F1.DESCRIPTION AS LEVEL0_DESC,
	CONCAT(F1.FLEX_VALUE, CONCAT('-',F1.DESCRIPTION)) AS SEG3_VALUE_DESC,
	S1.SEGMENT_NAME AS SEGMENT_NAME,
	F1.CREATION_DATE AS CREATION_DATE,
	F1.LAST_UPDATE_DATE AS LAST_UPDATE,
	-- AUDIT COLUMN
	'N' AS IS_DELETED_FLG,
	(SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM='EBS') AS SOURCE_APP_ID,
	(SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM='EBS')||'-'||
		NVL(S1.LEDGER_ID,0)||'-'||NVL(S1.CHART_OF_ACCOUNTS_ID,0)||'-'||NVL(S1.FLEX_VALUE_SET_ID,0)
		||'-'||NVL(F1.FLEX_VALUE,'0')||'-'||NVL(S1.SEGMENT_NAME,'0') AS DW_LOAD_ID,
	GETDATE() AS DW_INSERT_DATE,
	GETDATE() AS DW_UPDATE_DATE
FROM 
(
	SELECT 
		F1.FLEX_VALUE_SET_ID,
		F1.FLEX_VALUE_ID,
		F1.FLEX_VALUE,
		F1.CREATION_DATE,
		F1.LAST_UPDATE_DATE,
		F2.DESCRIPTION
	FROM BEC_ODS.FND_FLEX_VALUES F1 
	INNER JOIN BEC_ODS.FND_FLEX_VALUES_TL F2 
	ON
		F1.FLEX_VALUE_ID = F2.FLEX_VALUE_ID
		AND F2."LANGUAGE" = 'US'
	WHERE F1.IS_DELETED_FLG <> 'Y'
) F1 
INNER JOIN 
(
	SELECT 
		F1.APPLICATION_ID,
		G1.LEDGER_ID,
		F1.ID_FLEX_NUM,
		F1.ID_FLEX_STRUCTURE_CODE,
		F1.ID_FLEX_STRUCTURE_NAME,
		F1.DESCRIPTION,
		F2.APPLICATION_COLUMN_NAME,
		F2.SEGMENT_NAME,
		F2.SEGMENT_NUM,
		F2.FLEX_VALUE_SET_ID,
		G1.CHART_OF_ACCOUNTS_ID,
		G1.NAME AS LEDGER_NAME
	FROM BEC_ODS.FND_ID_FLEX_STRUCTURES_VL F1 
	INNER JOIN BEC_ODS.FND_ID_FLEX_SEGMENTS F2 
	ON
		F1.ID_FLEX_NUM = F2.ID_FLEX_NUM 
		AND F1.ID_FLEX_CODE = F2.ID_FLEX_CODE
		AND F2.ID_FLEX_CODE = 'GL#'
	INNER JOIN BEC_ODS.GL_LEDGERS G1 
	ON
		F1.ID_FLEX_NUM = G1.CHART_OF_ACCOUNTS_ID
	WHERE F1.IS_DELETED_FLG <> 'Y'
)  S1
ON 
	F1.FLEX_VALUE_SET_ID = S1.FLEX_VALUE_SET_ID
	AND S1.APPLICATION_COLUMN_NAME = 'SEGMENT3');
 end;

update
	bec_etl_ctrl.batch_dw_info
set
	load_type = 'I',
	last_refresh_date = getdate()
where
	dw_table_name = 'dim_segment3'
	and batch_name = 'gl';

commit;