/*
	# COPYRIGHT(C) 2022 KPI PARTNERS, INC. ALL RIGHTS RESERVED.
	#
	# UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, SOFTWARE
	# DISTRIBUTED UNDER THE LICENSE IS DISTRIBUTED ON AN "AS IS" BASIS, WITHOUT
	# WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
	#
	# AUTHOR: KPI PARTNERS, INC.
	# VERSION: 2022.06
	# DESCRIPTION: THIS SCRIPT REPRESENTS FULL LOAD APPROACH FOR FACTS.
	# FILE VERSION: KPI V1.0
*/

BEGIN;
	
	DROP TABLE IF EXISTS BEC_DWH.FACT_INV_RELATED_ITEMS;
	
	CREATE TABLE BEC_DWH.FACT_INV_RELATED_ITEMS DISTSTYLE ALL SORTKEY (RELATED_ITEM_ID) 
	AS
	(SELECT 
       	
		INVENTORY_ITEM_ID 
        ,ORGANIZATION_ID 
        ,RELATED_ITEM_ID 
        ,relationship_type_id
        ,reciprocal_flag
        ,PLANNING_ENABLED_FLAG 
        ,START_DATE 
        ,END_DATE 
        ,CREATION_DATE 
        ,CREATED_BY 
        ,LAST_UPDATE_DATE 
        ,LAST_UPDATED_BY
		,(SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM = 'EBS')|| '-' || INVENTORY_ITEM_ID  INVENTORY_ITEM_ID_KEY,
        (SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM = 'EBS')|| '-' || ORGANIZATION_ID    ORGANIZATION_ID_KEY,
        (SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM = 'EBS')|| '-' || RELATED_ITEM_ID        RELATED_ITEM_ID_KEY,
        (SELECT SYSTEM_ID FROM BEC_ETL_CTRL.ETLSOURCEAPPID WHERE SOURCE_SYSTEM = 'EBS')|| '-' ||RELATIONSHIP_TYPE_ID   RELATIONSHIP_TYPE_ID_KEY, 		
        (
			SELECT
			SYSTEM_ID
			FROM
			BEC_ETL_CTRL.ETLSOURCEAPPID
			WHERE
			SOURCE_SYSTEM = 'EBS'
		) AS SOURCE_APP_ID,
		(
			SELECT
			SYSTEM_ID
			FROM
			BEC_ETL_CTRL.ETLSOURCEAPPID
			WHERE
			SOURCE_SYSTEM = 'EBS'
		)
 		|| '-' || NVL(RELATED_ITEM_ID, 0)  AS DW_LOAD_ID, 
		GETDATE() AS DW_INSERT_DATE,
		GETDATE() AS DW_UPDATE_DATE			
		from
		( select * from bec_ods.mtl_related_items where is_deleted_flg <> 'Y' )
		
	);
	
END;

UPDATE
BEC_ETL_CTRL.BATCH_DW_INFO
SET
LOAD_TYPE = 'I',
LAST_REFRESH_DATE = GETDATE()
WHERE
DW_TABLE_NAME = 'fact_inv_related_items'
AND BATCH_NAME = 'inv';