/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.AP_CHECK_FORMATS;
CREATE TABLE IF NOT EXISTS bec_ods.AP_CHECK_FORMATS
(
CHECK_FORMAT_ID	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE	TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(10,0)   ENCODE az64
,NAME	VARCHAR(30)   ENCODE lzo
,TYPE	VARCHAR(15)   ENCODE lzo
,STUB_FIRST_FLAG	VARCHAR(1)   ENCODE lzo
,CHECK_LENGTH	NUMERIC(15,0)   ENCODE az64
,STUB_LENGTH	NUMERIC(15,0)   ENCODE az64
,INVOICES_PER_STUB	NUMERIC(15,0)   ENCODE az64
,OVERFLOW_RULE	VARCHAR(10)   ENCODE lzo
,PRE_NUMBERED_FLAG	VARCHAR(1)   ENCODE lzo
,CHECK_NUM_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,DATE_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,AMOUNT_ROW_LINE	NUMERIC(28,10)   ENCODE az64
,AMOUNT_WORDS_ROW_LINE	NUMERIC(28,10)   ENCODE az64
,VENDOR_NUM_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,VENDOR_NAME_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,VENDOR_ADDRESS_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,STUB_CHECK_NUM_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,STUB_VENDOR_NAME_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,STUB_VENDOR_NUM_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,STUB_FIRST_INVOICE_ROW_LINE	NUMERIC(15,0)   ENCODE az64
,PAYMENT_METHOD_LOOKUP_CODE	VARCHAR(25)   ENCODE lzo
,CURRENCY_CODE	VARCHAR(15)   ENCODE lzo
,CREATE_PAYMENTS_PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,CONFIRM_PAYMENTS_PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,SEPARATE_REMITTANCE_ADVICE	VARCHAR(1)   ENCODE lzo
,REMITTANCE_ADVICE_PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE	TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,EFT_TYPE	VARCHAR(1)   ENCODE lzo
,MULTI_CURRENCY_FLAG	VARCHAR(1)   ENCODE lzo
,ATTRIBUTE_CATEGORY	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,ZERO_AMOUNTS_ONLY	VARCHAR(1)   ENCODE lzo
,BUILD_PAYMENTS_PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,FORMAT_PAYMENTS_PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,PRINT_CHECK_STUB	VARCHAR(1)   ENCODE lzo
,GROUP_BY_DUE_DATE	VARCHAR(1)   ENCODE lzo
,GLOBAL_ATTRIBUTE_CATEGORY	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE16	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE17	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE18	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE19	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE20	VARCHAR(150)   ENCODE lzo
,BANK_FILE_CHARACTER_SET	VARCHAR(25)   ENCODE lzo
,TRANSMISSIONS_FLAG	VARCHAR(1)   ENCODE lzo
,ZD_EDITION_NAME VARCHAR(30)   ENCODE lzo
,ZD_SYNC VARCHAR(30)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE AUTO
;

INSERT INTO bec_ods.AP_CHECK_FORMATS
(CHECK_FORMAT_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,NAME
,TYPE
,STUB_FIRST_FLAG
,CHECK_LENGTH
,STUB_LENGTH
,INVOICES_PER_STUB
,OVERFLOW_RULE
,PRE_NUMBERED_FLAG
,CHECK_NUM_ROW_LINE
,DATE_ROW_LINE
,AMOUNT_ROW_LINE
,AMOUNT_WORDS_ROW_LINE
,VENDOR_NUM_ROW_LINE
,VENDOR_NAME_ROW_LINE
,VENDOR_ADDRESS_ROW_LINE
,STUB_CHECK_NUM_ROW_LINE
,STUB_VENDOR_NAME_ROW_LINE
,STUB_VENDOR_NUM_ROW_LINE
,STUB_FIRST_INVOICE_ROW_LINE
,PAYMENT_METHOD_LOOKUP_CODE
,CURRENCY_CODE
,CREATE_PAYMENTS_PROGRAM_ID
,CONFIRM_PAYMENTS_PROGRAM_ID
,SEPARATE_REMITTANCE_ADVICE
,REMITTANCE_ADVICE_PROGRAM_ID
,LAST_UPDATE_LOGIN
,CREATION_DATE
,CREATED_BY
,EFT_TYPE
,MULTI_CURRENCY_FLAG
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ZERO_AMOUNTS_ONLY
,BUILD_PAYMENTS_PROGRAM_ID
,FORMAT_PAYMENTS_PROGRAM_ID
,PRINT_CHECK_STUB
,GROUP_BY_DUE_DATE
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE20
,BANK_FILE_CHARACTER_SET
,TRANSMISSIONS_FLAG
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id
,kca_seq_date
)
SELECT
CHECK_FORMAT_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,NAME
,TYPE
,STUB_FIRST_FLAG
,CHECK_LENGTH
,STUB_LENGTH
,INVOICES_PER_STUB
,OVERFLOW_RULE
,PRE_NUMBERED_FLAG
,CHECK_NUM_ROW_LINE
,DATE_ROW_LINE
,AMOUNT_ROW_LINE
,AMOUNT_WORDS_ROW_LINE
,VENDOR_NUM_ROW_LINE
,VENDOR_NAME_ROW_LINE
,VENDOR_ADDRESS_ROW_LINE
,STUB_CHECK_NUM_ROW_LINE
,STUB_VENDOR_NAME_ROW_LINE
,STUB_VENDOR_NUM_ROW_LINE
,STUB_FIRST_INVOICE_ROW_LINE
,PAYMENT_METHOD_LOOKUP_CODE
,CURRENCY_CODE
,CREATE_PAYMENTS_PROGRAM_ID
,CONFIRM_PAYMENTS_PROGRAM_ID
,SEPARATE_REMITTANCE_ADVICE
,REMITTANCE_ADVICE_PROGRAM_ID
,LAST_UPDATE_LOGIN
,CREATION_DATE
,CREATED_BY
,EFT_TYPE
,MULTI_CURRENCY_FLAG
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ZERO_AMOUNTS_ONLY
,BUILD_PAYMENTS_PROGRAM_ID
,FORMAT_PAYMENTS_PROGRAM_ID
,PRINT_CHECK_STUB
,GROUP_BY_DUE_DATE
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE20
,BANK_FILE_CHARACTER_SET
,TRANSMISSIONS_FLAG
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
,kca_seq_date
FROM bec_ods_stg.AP_CHECK_FORMATS;

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', last_refresh_date = getdate() where ods_table_name='ap_check_formats';

commit;