/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;

DROP TABLE if exists bec_ods.AP_EXPENSE_REPORT_HEADERS_ALL;

CREATE TABLE IF NOT EXISTS bec_ods.AP_EXPENSE_REPORT_HEADERS_ALL
(
	report_header_id NUMERIC(15,0)   ENCODE az64
	,employee_id NUMERIC(10,0)   ENCODE az64
	,week_end_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,creation_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,created_by NUMERIC(15,0)   ENCODE az64
	,last_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_updated_by NUMERIC(15,0)   ENCODE az64
	,vouchno NUMERIC(15,0)   ENCODE az64
	,total NUMERIC(28,10)   ENCODE az64
	,vendor_id NUMERIC(15,0)   ENCODE az64
	,vendor_site_id NUMERIC(15,0)   ENCODE az64
	,expense_check_address_flag VARCHAR(30)   ENCODE lzo
	,reference_1 VARCHAR(30)   ENCODE lzo
	,reference_2 VARCHAR(30)   ENCODE lzo
	,invoice_num VARCHAR(50)   ENCODE lzo
	,expense_report_id NUMERIC(15,0)   ENCODE az64
	,accts_pay_code_combination_id NUMERIC(15,0)   ENCODE az64
	,set_of_books_id NUMERIC(15,0)   ENCODE az64
	,source VARCHAR(25)   ENCODE lzo
	,purgeable_flag VARCHAR(1)   ENCODE lzo
	,accounting_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,maximum_amount_to_apply NUMERIC(28,10)   ENCODE az64
	,advance_invoice_to_apply NUMERIC(15,0)   ENCODE az64
	,apply_advances_default VARCHAR(4)   ENCODE lzo
	,employee_ccid NUMERIC(15,0)   ENCODE az64
	,description VARCHAR(240)   ENCODE lzo
	,reject_code VARCHAR(30)   ENCODE lzo
	,hold_lookup_code VARCHAR(25)   ENCODE lzo
	,attribute_category VARCHAR(150)   ENCODE lzo
	,attribute1 VARCHAR(150)   ENCODE lzo
	,attribute2 VARCHAR(150)   ENCODE lzo
	,attribute3 VARCHAR(150)   ENCODE lzo
	,attribute4 VARCHAR(150)   ENCODE lzo
	,attribute5 VARCHAR(150)   ENCODE lzo
	,attribute6 VARCHAR(150)   ENCODE lzo
	,attribute7 VARCHAR(150)   ENCODE lzo
	,attribute8 VARCHAR(150)   ENCODE lzo
	,attribute9 VARCHAR(150)   ENCODE lzo
	,attribute10 VARCHAR(150)   ENCODE lzo
	,attribute11 VARCHAR(150)   ENCODE lzo
	,attribute12 VARCHAR(150)   ENCODE lzo
	,attribute13 VARCHAR(150)   ENCODE lzo
	,attribute14 VARCHAR(150)   ENCODE lzo
	,attribute15 VARCHAR(150)   ENCODE lzo
	,default_currency_code VARCHAR(15)   ENCODE lzo
	,default_exchange_rate_type VARCHAR(30)   ENCODE lzo
	,default_exchange_rate NUMERIC(28,10)   ENCODE az64
	,default_exchange_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_update_login NUMERIC(15,0)   ENCODE az64
	,voucher_num VARCHAR(50)   ENCODE lzo
	,ussgl_transaction_code VARCHAR(30)   ENCODE lzo
	,ussgl_trx_code_context VARCHAR(30)   ENCODE lzo
	,doc_category_code VARCHAR(30)   ENCODE lzo
	,awt_group_id NUMERIC(15,0)   ENCODE az64
	,org_id NUMERIC(15,0)   ENCODE az64
	,workflow_approved_flag VARCHAR(1)   ENCODE lzo
	,flex_concatenated VARCHAR(240)   ENCODE lzo
	,global_attribute_category VARCHAR(150)   ENCODE lzo
	,global_attribute1 VARCHAR(150)   ENCODE lzo
	,global_attribute2 VARCHAR(150)   ENCODE lzo
	,global_attribute3 VARCHAR(150)   ENCODE lzo
	,global_attribute4 VARCHAR(150)   ENCODE lzo
	,global_attribute5 VARCHAR(150)   ENCODE lzo
	,global_attribute6 VARCHAR(150)   ENCODE lzo
	,global_attribute7 VARCHAR(150)   ENCODE lzo
	,global_attribute8 VARCHAR(150)   ENCODE lzo
	,global_attribute9 VARCHAR(150)   ENCODE lzo
	,global_attribute10 VARCHAR(150)   ENCODE lzo
	,global_attribute11 VARCHAR(150)   ENCODE lzo
	,global_attribute12 VARCHAR(150)   ENCODE lzo
	,global_attribute13 VARCHAR(150)   ENCODE lzo
	,global_attribute14 VARCHAR(150)   ENCODE lzo
	,global_attribute15 VARCHAR(150)   ENCODE lzo
	,global_attribute16 VARCHAR(150)   ENCODE lzo
	,global_attribute17 VARCHAR(150)   ENCODE lzo
	,global_attribute18 VARCHAR(150)   ENCODE lzo
	,global_attribute19 VARCHAR(150)   ENCODE lzo
	,global_attribute20 VARCHAR(150)   ENCODE lzo
	,override_approver_id NUMERIC(9,0)   ENCODE az64
	,payment_cross_rate_type VARCHAR(30)   ENCODE lzo
	,payment_cross_rate_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,payment_cross_rate NUMERIC(28,10)   ENCODE az64
	,payment_currency_code VARCHAR(15)   ENCODE lzo
	,core_wf_status_flag VARCHAR(1)   ENCODE lzo
	,prepay_apply_flag VARCHAR(4)   ENCODE lzo
	,prepay_num VARCHAR(50)   ENCODE lzo
	,prepay_dist_num NUMERIC(15,0)   ENCODE az64
	,prepay_apply_amount NUMERIC(28,10)   ENCODE az64
	,prepay_gl_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,bothpay_parent_id NUMERIC(15,0)   ENCODE az64
	,shortpay_parent_id NUMERIC(15,0)   ENCODE az64
	,paid_on_behalf_employee_id NUMERIC(15,0)   ENCODE az64
	,override_approver_name VARCHAR(240)   ENCODE lzo
	,amt_due_ccard_company NUMERIC(28,10)   ENCODE az64
	,amt_due_employee NUMERIC(28,10)   ENCODE az64
	,default_receipt_currency_code VARCHAR(15)   ENCODE lzo
	,multiple_currencies_flag VARCHAR(1)   ENCODE lzo
	,expense_status_code VARCHAR(30)   ENCODE lzo
	,expense_last_status_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,expense_current_approver_id NUMERIC(15,0)   ENCODE az64
	,report_filing_number VARCHAR(240)   ENCODE lzo
	,receipts_received_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,audit_code VARCHAR(30)   ENCODE lzo
	,report_submitted_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_audited_by NUMERIC(15,0)   ENCODE az64
	,return_reason_code VARCHAR(30)   ENCODE lzo
	,return_instruction VARCHAR(4000)   ENCODE lzo
	,receipts_status VARCHAR(30)   ENCODE lzo
	,holding_report_header_id NUMERIC(15,0)   ENCODE az64
	,request_id NUMERIC(15,0)   ENCODE az64
	,advances_justification VARCHAR(240)   ENCODE lzo 
	,IMAGE_RECEIPTS_STATUS VARCHAR(30)   ENCODE lzo
	,IMAGE_RECEIPTS_RECEIVED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,MISSING_IMG_JUST VARCHAR(240)   ENCODE lzo
	,APPROVAL_TYPE VARCHAR(10)   ENCODE lzo
	,OVERDUE_REQUEST_ID NUMERIC(15,0)   ENCODE az64
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
	,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE AUTO;
INSERT
	INTO
	bec_ods.AP_EXPENSE_REPORT_HEADERS_ALL
(REPORT_HEADER_ID,
	EMPLOYEE_ID,
	WEEK_END_DATE,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	VOUCHNO,
	TOTAL,
	VENDOR_ID,
	VENDOR_SITE_ID,
	EXPENSE_CHECK_ADDRESS_FLAG,
	REFERENCE_1,
	REFERENCE_2,
	INVOICE_NUM,
	EXPENSE_REPORT_ID,
	ACCTS_PAY_CODE_COMBINATION_ID,
	SET_OF_BOOKS_ID,
	"SOURCE",
	PURGEABLE_FLAG,
	ACCOUNTING_DATE,
	MAXIMUM_AMOUNT_TO_APPLY,
	ADVANCE_INVOICE_TO_APPLY,
	APPLY_ADVANCES_DEFAULT,
	EMPLOYEE_CCID,
	DESCRIPTION,
	REJECT_CODE,
	HOLD_LOOKUP_CODE,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	DEFAULT_CURRENCY_CODE,
	DEFAULT_EXCHANGE_RATE_TYPE,
	DEFAULT_EXCHANGE_RATE,
	DEFAULT_EXCHANGE_DATE,
	LAST_UPDATE_LOGIN,
	VOUCHER_NUM,
	USSGL_TRANSACTION_CODE,
	USSGL_TRX_CODE_CONTEXT,
	DOC_CATEGORY_CODE,
	AWT_GROUP_ID,
	ORG_ID,
	WORKFLOW_APPROVED_FLAG,
	FLEX_CONCATENATED,
	GLOBAL_ATTRIBUTE_CATEGORY,
	GLOBAL_ATTRIBUTE1,
	GLOBAL_ATTRIBUTE2,
	GLOBAL_ATTRIBUTE3,
	GLOBAL_ATTRIBUTE4,
	GLOBAL_ATTRIBUTE5,
	GLOBAL_ATTRIBUTE6,
	GLOBAL_ATTRIBUTE7,
	GLOBAL_ATTRIBUTE8,
	GLOBAL_ATTRIBUTE9,
	GLOBAL_ATTRIBUTE10,
	GLOBAL_ATTRIBUTE11,
	GLOBAL_ATTRIBUTE12,
	GLOBAL_ATTRIBUTE13,
	GLOBAL_ATTRIBUTE14,
	GLOBAL_ATTRIBUTE15,
	GLOBAL_ATTRIBUTE16,
	GLOBAL_ATTRIBUTE17,
	GLOBAL_ATTRIBUTE18,
	GLOBAL_ATTRIBUTE19,
	GLOBAL_ATTRIBUTE20,
	OVERRIDE_APPROVER_ID,
	PAYMENT_CROSS_RATE_TYPE,
	PAYMENT_CROSS_RATE_DATE,
	PAYMENT_CROSS_RATE,
	PAYMENT_CURRENCY_CODE,
	CORE_WF_STATUS_FLAG,
	PREPAY_APPLY_FLAG,
	PREPAY_NUM,
	PREPAY_DIST_NUM,
	PREPAY_APPLY_AMOUNT,
	PREPAY_GL_DATE,
	BOTHPAY_PARENT_ID,
	SHORTPAY_PARENT_ID,
	PAID_ON_BEHALF_EMPLOYEE_ID,
	OVERRIDE_APPROVER_NAME,
	AMT_DUE_CCARD_COMPANY,
	AMT_DUE_EMPLOYEE,
	DEFAULT_RECEIPT_CURRENCY_CODE,
	MULTIPLE_CURRENCIES_FLAG,
	EXPENSE_STATUS_CODE,
	EXPENSE_LAST_STATUS_DATE,
	EXPENSE_CURRENT_APPROVER_ID,
	REPORT_FILING_NUMBER,
	RECEIPTS_RECEIVED_DATE,
	AUDIT_CODE,
	REPORT_SUBMITTED_DATE,
	LAST_AUDITED_BY,
	RETURN_REASON_CODE,
	RETURN_INSTRUCTION,
	RECEIPTS_STATUS,
	HOLDING_REPORT_HEADER_ID,
	REQUEST_ID,
	ADVANCES_JUSTIFICATION,
	IMAGE_RECEIPTS_STATUS,
	IMAGE_RECEIPTS_RECEIVED_DATE,
	MISSING_IMG_JUST,
	APPROVAL_TYPE,
	OVERDUE_REQUEST_ID,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
	)
	SELECT
	REPORT_HEADER_ID,
	EMPLOYEE_ID,
	WEEK_END_DATE,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	VOUCHNO,
	TOTAL,
	VENDOR_ID,
	VENDOR_SITE_ID,
	EXPENSE_CHECK_ADDRESS_FLAG,
	REFERENCE_1,
	REFERENCE_2,
	INVOICE_NUM,
	EXPENSE_REPORT_ID,
	ACCTS_PAY_CODE_COMBINATION_ID,
	SET_OF_BOOKS_ID,
	"SOURCE",
	PURGEABLE_FLAG,
	ACCOUNTING_DATE,
	MAXIMUM_AMOUNT_TO_APPLY,
	ADVANCE_INVOICE_TO_APPLY,
	APPLY_ADVANCES_DEFAULT,
	EMPLOYEE_CCID,
	DESCRIPTION,
	REJECT_CODE,
	HOLD_LOOKUP_CODE,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	DEFAULT_CURRENCY_CODE,
	DEFAULT_EXCHANGE_RATE_TYPE,
	DEFAULT_EXCHANGE_RATE,
	DEFAULT_EXCHANGE_DATE,
	LAST_UPDATE_LOGIN,
	VOUCHER_NUM,
	USSGL_TRANSACTION_CODE,
	USSGL_TRX_CODE_CONTEXT,
	DOC_CATEGORY_CODE,
	AWT_GROUP_ID,
	ORG_ID,
	WORKFLOW_APPROVED_FLAG,
	FLEX_CONCATENATED,
	GLOBAL_ATTRIBUTE_CATEGORY,
	GLOBAL_ATTRIBUTE1,
	GLOBAL_ATTRIBUTE2,
	GLOBAL_ATTRIBUTE3,
	GLOBAL_ATTRIBUTE4,
	GLOBAL_ATTRIBUTE5,
	GLOBAL_ATTRIBUTE6,
	GLOBAL_ATTRIBUTE7,
	GLOBAL_ATTRIBUTE8,
	GLOBAL_ATTRIBUTE9,
	GLOBAL_ATTRIBUTE10,
	GLOBAL_ATTRIBUTE11,
	GLOBAL_ATTRIBUTE12,
	GLOBAL_ATTRIBUTE13,
	GLOBAL_ATTRIBUTE14,
	GLOBAL_ATTRIBUTE15,
	GLOBAL_ATTRIBUTE16,
	GLOBAL_ATTRIBUTE17,
	GLOBAL_ATTRIBUTE18,
	GLOBAL_ATTRIBUTE19,
	GLOBAL_ATTRIBUTE20,
	OVERRIDE_APPROVER_ID,
	PAYMENT_CROSS_RATE_TYPE,
	PAYMENT_CROSS_RATE_DATE,
	PAYMENT_CROSS_RATE,
	PAYMENT_CURRENCY_CODE,
	CORE_WF_STATUS_FLAG,
	PREPAY_APPLY_FLAG,
	PREPAY_NUM,
	PREPAY_DIST_NUM,
	PREPAY_APPLY_AMOUNT,
	PREPAY_GL_DATE,
	BOTHPAY_PARENT_ID,
	SHORTPAY_PARENT_ID,
	PAID_ON_BEHALF_EMPLOYEE_ID,
	OVERRIDE_APPROVER_NAME,
	AMT_DUE_CCARD_COMPANY,
	AMT_DUE_EMPLOYEE,
	DEFAULT_RECEIPT_CURRENCY_CODE,
	MULTIPLE_CURRENCIES_FLAG,
	EXPENSE_STATUS_CODE,
	EXPENSE_LAST_STATUS_DATE,
	EXPENSE_CURRENT_APPROVER_ID,
	REPORT_FILING_NUMBER,
	RECEIPTS_RECEIVED_DATE,
	AUDIT_CODE,
	REPORT_SUBMITTED_DATE,
	LAST_AUDITED_BY,
	RETURN_REASON_CODE,
	RETURN_INSTRUCTION,
	RECEIPTS_STATUS,
	HOLDING_REPORT_HEADER_ID,
	REQUEST_ID,
	ADVANCES_JUSTIFICATION,
	IMAGE_RECEIPTS_STATUS,
	IMAGE_RECEIPTS_RECEIVED_DATE,
	MISSING_IMG_JUST,
	APPROVAL_TYPE,
	OVERDUE_REQUEST_ID,
	KCA_OPERATION,
	'N' as IS_DELETED_FLG,
	cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
FROM
	bec_ods_stg.AP_EXPENSE_REPORT_HEADERS_ALL;

end;		 
UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'ap_expense_report_headers_all'; 
	
commit;