/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach FOR ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.AP_INV_APRVL_HIST_ALL;

CREATE TABLE IF NOT EXISTS bec_ods.AP_INV_APRVL_HIST_ALL
(
   APPROVAL_HISTORY_ID NUMERIC(15,0) ENCODE az64,
INVOICE_ID NUMERIC(15,0) ENCODE az64,
ITERATION NUMERIC(9,0) ENCODE az64,
RESPONSE VARCHAR(50) ENCODE lzo,
APPROVER_ID NUMERIC(15,0) ENCODE az64,
APPROVER_NAME VARCHAR(150) ENCODE lzo,
AMOUNT_APPROVED NUMERIC(28,10) ENCODE az64,
APPROVER_COMMENTS VARCHAR(240) ENCODE lzo,
CREATED_BY NUMERIC(15,0) ENCODE az64,
CREATION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 NOT NULL,
LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 NOT NULL,
LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64,
LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64,
ORG_ID NUMERIC(15,0) ENCODE az64,
NOTIFICATION_ORDER NUMERIC(9,0) ENCODE az64,
ORIG_SYSTEM VARCHAR(30) ENCODE lzo,
ITEM_CLASS VARCHAR(50) ENCODE lzo,
ITEM_ID VARCHAR(50) ENCODE lzo,
LINE_NUMBER NUMERIC(15,0) ENCODE az64,
HOLD_ID NUMERIC(15,0) ENCODE az64,
HISTORY_TYPE VARCHAR(30) ENCODE lzo,
"APPROVER_COMMENTS#1" VARCHAR(4000) ENCODE lzo,
"LINE_NUMBER#1" NUMERIC(28,10) ENCODE az64
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.AP_INV_APRVL_HIST_ALL (
   APPROVAL_HISTORY_ID,
	INVOICE_ID,
	ITERATION,
	RESPONSE,
	APPROVER_ID,
	APPROVER_NAME,
	AMOUNT_APPROVED,
	APPROVER_COMMENTS,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_LOGIN,
	ORG_ID,
	NOTIFICATION_ORDER,
	ORIG_SYSTEM,
	ITEM_CLASS,
	ITEM_ID,
	LINE_NUMBER,
	HOLD_ID,
	HISTORY_TYPE,
	"APPROVER_COMMENTS#1",
	"LINE_NUMBER#1",
	kca_operation,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
	APPROVAL_HISTORY_ID,
	INVOICE_ID,
	ITERATION,
	RESPONSE,
	APPROVER_ID,
	APPROVER_NAME,
	AMOUNT_APPROVED,
	APPROVER_COMMENTS,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_LOGIN,
	ORG_ID,
	NOTIFICATION_ORDER,
	ORIG_SYSTEM,
	ITEM_CLASS,
	ITEM_ID,
	LINE_NUMBER,
	HOLD_ID,
	HISTORY_TYPE,
	"APPROVER_COMMENTS#1",
	"LINE_NUMBER#1",
    KCA_OPERATION,
    'N' as IS_DELETED_FLG,
    cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
    FROM
        bec_ods_stg.AP_INV_APRVL_HIST_ALL;

end;

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'ap_inv_aprvl_hist_all';

COMMIT;