/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;
drop table if exists bec_ods.CE_PAYMENT_DOCUMENTS;

CREATE TABLE IF NOT EXISTS bec_ods.CE_PAYMENT_DOCUMENTS
(
PAYMENT_DOCUMENT_ID NUMERIC(15,0)   ENCODE az64 , 
PAYMENT_DOC_CATEGORY VARCHAR(30)   ENCODE lzo, 
PAYMENT_DOCUMENT_NAME VARCHAR(100)   ENCODE lzo , 
PAYMENT_INSTRUCTION_ID NUMERIC(15,0)   ENCODE az64, 
INTERNAL_BANK_ACCOUNT_ID NUMERIC(15,0)   ENCODE az64 , 
PAPER_STOCK_TYPE VARCHAR(30)   ENCODE lzo , 
ATTACHED_REMITTANCE_STUB_FLAG VARCHAR(1)   ENCODE lzo , 
NUMBER_OF_LINES_PER_REMIT_STUB NUMERIC(15,0)   ENCODE az64, 
NUMBER_OF_SETUP_DOCUMENTS NUMERIC(15,0)   ENCODE az64, 
FORMAT_CODE VARCHAR(30)   ENCODE lzo, 
FIRST_AVAILABLE_DOCUMENT_NUM NUMERIC(15,0)   ENCODE az64, 
LAST_AVAILABLE_DOCUMENT_NUMBER NUMERIC(15,0)   ENCODE az64, 
LAST_ISSUED_DOCUMENT_NUMBER NUMERIC(15,0)   ENCODE az64 , 
MANUAL_PAYMENTS_ONLY_FLAG VARCHAR(1)   ENCODE lzo , 
ATTRIBUTE_CATEGORY VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE1 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE2 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE3 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE4 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE5 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE6 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE7 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE8 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE9 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE10 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE11 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE12 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE13 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE14 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE15 VARCHAR(150)   ENCODE lzo, 
INACTIVE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
CREATED_BY NUMERIC(15,0)   ENCODE az64 , 
CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 , 
LAST_UPDATED_BY NUMERIC(15,0)   ENCODE az64 , 
LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 , 
LAST_UPDATE_LOGIN NUMERIC(15,0)   ENCODE az64, 
OBJECT_VERSION_NUMBER NUMERIC(15,0)   ENCODE az64 
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE AUTO
;

INSERT
	INTO
	bec_ods.CE_PAYMENT_DOCUMENTS
(PAYMENT_DOCUMENT_ID,
	PAYMENT_DOC_CATEGORY,
	PAYMENT_DOCUMENT_NAME,
	PAYMENT_INSTRUCTION_ID,
	INTERNAL_BANK_ACCOUNT_ID,
	PAPER_STOCK_TYPE,
	ATTACHED_REMITTANCE_STUB_FLAG,
	NUMBER_OF_LINES_PER_REMIT_STUB,
	NUMBER_OF_SETUP_DOCUMENTS,
	FORMAT_CODE,
	FIRST_AVAILABLE_DOCUMENT_NUM,
	LAST_AVAILABLE_DOCUMENT_NUMBER,
	LAST_ISSUED_DOCUMENT_NUMBER,
	MANUAL_PAYMENTS_ONLY_FLAG,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	INACTIVE_DATE,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATE_LOGIN,
	OBJECT_VERSION_NUMBER
	,KCA_OPERATION
	,IS_DELETED_FLG
	,kca_seq_id
	,kca_seq_date)
SELECT
	PAYMENT_DOCUMENT_ID,
	PAYMENT_DOC_CATEGORY,
	PAYMENT_DOCUMENT_NAME,
	PAYMENT_INSTRUCTION_ID,
	INTERNAL_BANK_ACCOUNT_ID,
	PAPER_STOCK_TYPE,
	ATTACHED_REMITTANCE_STUB_FLAG,
	NUMBER_OF_LINES_PER_REMIT_STUB,
	NUMBER_OF_SETUP_DOCUMENTS,
	FORMAT_CODE,
	FIRST_AVAILABLE_DOCUMENT_NUM,
	LAST_AVAILABLE_DOCUMENT_NUMBER,
	LAST_ISSUED_DOCUMENT_NUMBER,
	MANUAL_PAYMENTS_ONLY_FLAG,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	INACTIVE_DATE,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATE_LOGIN,
	OBJECT_VERSION_NUMBER
	,KCA_OPERATION
	,'N' as IS_DELETED_FLG
	,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
FROM
	bec_ods_stg.CE_PAYMENT_DOCUMENTS;
end; 

update bec_etl_ctrl.batch_ods_info set load_type = 'I', last_refresh_date = getdate() where ods_table_name='ce_payment_documents';

commit;
 
	
