/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.CSI_COUNTER_ASSOCIATIONS;

CREATE TABLE IF NOT EXISTS bec_ods.CSI_COUNTER_ASSOCIATIONS
(
	INSTANCE_ASSOCIATION_ID NUMERIC(15,0) ENCODE az64 
	,SOURCE_OBJECT_CODE VARCHAR(30) ENCODE lzo 
	,SOURCE_OBJECT_ID NUMERIC(15,0) ENCODE az64 
	,COUNTER_ID NUMERIC(15,0) ENCODE az64 
	,START_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,END_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,SECURITY_GROUP_ID NUMERIC(15,0) ENCODE az64 
	,OBJECT_VERSION_NUMBER NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64 
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,CREATED_BY NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64 
	,ATTRIBUTE_CATEGORY VARCHAR(30) ENCODE lzo 
	,ATTRIBUTE1 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE2 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE3 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE4 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE5 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE6 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE7 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE8 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE9 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE10 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE11 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE12 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE13 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE14 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE15 VARCHAR(150) ENCODE lzo 
	,MIGRATED_FLAG VARCHAR(1) ENCODE lzo 
	,MAINT_ORGANIZATION_ID NUMERIC(15,0) ENCODE az64 
	,PRIMARY_FAILURE_FLAG VARCHAR(1) ENCODE lzo
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE
auto;

COMMIT;

INSERT INTO bec_ods.CSI_COUNTER_ASSOCIATIONS (
	INSTANCE_ASSOCIATION_ID,
	SOURCE_OBJECT_CODE,
	SOURCE_OBJECT_ID,
	COUNTER_ID,
	START_DATE_ACTIVE,
	END_DATE_ACTIVE,
	SECURITY_GROUP_ID,
	OBJECT_VERSION_NUMBER,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	MIGRATED_FLAG,
	MAINT_ORGANIZATION_ID,
	PRIMARY_FAILURE_FLAG,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
		INSTANCE_ASSOCIATION_ID,
		SOURCE_OBJECT_CODE,
		SOURCE_OBJECT_ID,
		COUNTER_ID,
		START_DATE_ACTIVE,
		END_DATE_ACTIVE,
		SECURITY_GROUP_ID,
		OBJECT_VERSION_NUMBER,
		LAST_UPDATE_DATE,
		LAST_UPDATED_BY,
		CREATION_DATE,
		CREATED_BY,
		LAST_UPDATE_LOGIN,
		ATTRIBUTE_CATEGORY,
		ATTRIBUTE1,
		ATTRIBUTE2,
		ATTRIBUTE3,
		ATTRIBUTE4,
		ATTRIBUTE5,
		ATTRIBUTE6,
		ATTRIBUTE7,
		ATTRIBUTE8,
		ATTRIBUTE9,
		ATTRIBUTE10,
		ATTRIBUTE11,
		ATTRIBUTE12,
		ATTRIBUTE13,
		ATTRIBUTE14,
		ATTRIBUTE15,
		MIGRATED_FLAG,
		MAINT_ORGANIZATION_ID,
		PRIMARY_FAILURE_FLAG,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
    FROM
        bec_ods_stg.CSI_COUNTER_ASSOCIATIONS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'csi_counter_associations';
	
commit;