/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.csi_item_instances;

CREATE TABLE IF NOT EXISTS bec_ods.csi_item_instances
(
	INSTANCE_ID NUMERIC(15,0) ENCODE az64 
	,INSTANCE_NUMBER VARCHAR(30) ENCODE lzo 
	,EXTERNAL_REFERENCE VARCHAR(30) ENCODE lzo 
	,INVENTORY_ITEM_ID NUMERIC(15,0) ENCODE az64 
	,INVENTORY_REVISION VARCHAR(3) ENCODE lzo
	,INV_MASTER_ORGANIZATION_ID NUMERIC(15,0) ENCODE az64 
	,SERIAL_NUMBER VARCHAR(30) ENCODE lzo
	,MFG_SERIAL_NUMBER_FLAG VARCHAR(1) ENCODE lzo
	,LOT_NUMBER VARCHAR(80) ENCODE lzo
	,QUANTITY NUMERIC(28,10) ENCODE az64 
	,UNIT_OF_MEASURE VARCHAR(3) ENCODE lzo
	,ACCOUNTING_CLASS_CODE VARCHAR(10) ENCODE lzo
	,INSTANCE_CONDITION_ID NUMERIC(15,0) ENCODE az64 
	,INSTANCE_STATUS_ID NUMERIC(15,0) ENCODE az64 
	,CUSTOMER_VIEW_FLAG VARCHAR(1) ENCODE lzo
	,MERCHANT_VIEW_FLAG VARCHAR(1) ENCODE lzo
	,SELLABLE_FLAG VARCHAR(1) ENCODE lzo
	,SYSTEM_ID NUMERIC(15,0) ENCODE az64 
	,INSTANCE_TYPE_CODE VARCHAR(30) ENCODE lzo
	,ACTIVE_START_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64  
	,ACTIVE_END_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,LOCATION_TYPE_CODE VARCHAR(30) ENCODE lzo 	
	,LOCATION_ID NUMERIC(15,0) ENCODE az64 
	,INV_ORGANIZATION_ID NUMERIC(15,0) ENCODE az64 
	,INV_SUBINVENTORY_NAME VARCHAR(10) ENCODE lzo 	
	,INV_LOCATOR_ID NUMERIC(15,0) ENCODE az64 
	,PA_PROJECT_ID NUMERIC(15,0) ENCODE az64  	
	,PA_PROJECT_TASK_ID NUMERIC(15,0) ENCODE az64 
	,IN_TRANSIT_ORDER_LINE_ID NUMERIC(15,0) ENCODE az64  	
	,WIP_JOB_ID NUMERIC(15,0) ENCODE az64 
	,PO_ORDER_LINE_ID NUMERIC(15,0) ENCODE az64  	
	,LAST_OE_ORDER_LINE_ID NUMERIC(15,0) ENCODE az64 
	,LAST_OE_RMA_LINE_ID NUMERIC(15,0) ENCODE az64  	
	,LAST_PO_PO_LINE_ID NUMERIC(15,0) ENCODE az64 
	,LAST_OE_PO_NUMBER VARCHAR(50) ENCODE lzo 
	,LAST_WIP_JOB_ID NUMERIC(15,0) ENCODE az64  	
	,LAST_PA_PROJECT_ID NUMERIC(15,0) ENCODE az64 
	,LAST_PA_TASK_ID NUMERIC(15,0) ENCODE az64  	
	,LAST_OE_AGREEMENT_ID NUMERIC(15,0) ENCODE az64 
	,INSTALL_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,MANUALLY_CREATED_FLAG VARCHAR(1) ENCODE lzo 
	,RETURN_BY_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64
	,ACTUAL_RETURN_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,CREATION_COMPLETE_FLAG VARCHAR(1) ENCODE lzo 
	,COMPLETENESS_FLAG VARCHAR(1) ENCODE lzo 
	,CONTEXT VARCHAR(30) ENCODE lzo 
	,ATTRIBUTE1 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE2 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE3 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE4 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE5 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE6 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE7 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE8 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE9 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE10 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE11 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE12 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE13 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE14 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE15 VARCHAR(240) ENCODE lzo 	
	,CREATED_BY NUMERIC(15,0) ENCODE az64 	
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64 	
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64	
	,LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64 	
	,OBJECT_VERSION_NUMBER NUMERIC(28,10) ENCODE az64 	
	,SECURITY_GROUP_ID NUMERIC(15,0) ENCODE az64 	
	,LAST_TXN_LINE_DETAIL_ID NUMERIC(15,0) ENCODE az64 
	,INSTALL_LOCATION_TYPE_CODE VARCHAR(30) ENCODE lzo 
	,INSTALL_LOCATION_ID NUMERIC(15,0) ENCODE az64 
	,INSTANCE_USAGE_CODE VARCHAR(30) ENCODE lzo 
	,OWNER_PARTY_SOURCE_TABLE VARCHAR(30) ENCODE lzo 
	,OWNER_PARTY_ID NUMERIC(15,0) ENCODE az64 
	,OWNER_PARTY_ACCOUNT_ID NUMERIC(15,0) ENCODE az64 
	,LAST_VLD_ORGANIZATION_ID NUMERIC(15,0) ENCODE az64 
	,MIGRATED_FLAG VARCHAR(1) ENCODE lzo 
	,REQUEST_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_APPLICATION_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 	
	,CONFIG_INST_HDR_ID NUMERIC(15,0) ENCODE az64 
	,CONFIG_INST_REV_NUM NUMERIC(28,10) ENCODE az64 
	,CONFIG_INST_ITEM_ID NUMERIC(15,0) ENCODE az64 
	,CONFIG_VALID_STATUS VARCHAR(30) ENCODE lzo 	
	,INSTANCE_DESCRIPTION VARCHAR(240) ENCODE lzo 
	,LAST_PURGE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64
	,ATTRIBUTE16 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE17 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE18 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE19 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE20 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE21 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE22 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE23 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE24 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE25 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE26 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE27 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE28 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE29 VARCHAR(240) ENCODE lzo 
	,ATTRIBUTE30 VARCHAR(240) ENCODE lzo 
	,NETWORK_ASSET_FLAG VARCHAR(1) ENCODE lzo
	,MAINTAINABLE_FLAG VARCHAR(1) ENCODE lzo
	,PN_LOCATION_ID NUMERIC(15,0) ENCODE az64 
	,ASSET_CRITICALITY_CODE VARCHAR(30) ENCODE lzo 	
	,CATEGORY_ID NUMERIC(15,0) ENCODE az64 
	,EQUIPMENT_GEN_OBJECT_ID NUMERIC(15,0) ENCODE az64 
	,INSTANTIATION_FLAG VARCHAR(1) ENCODE lzo
	,LINEAR_LOCATION_ID NUMERIC(15,0) ENCODE az64 
	,OPERATIONAL_LOG_FLAG VARCHAR(1) ENCODE lzo
	,CHECKIN_STATUS NUMERIC(28,10) ENCODE az64 	
	,SUPPLIER_WARRANTY_EXP_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 	
	,PURCHASE_UNIT_PRICE NUMERIC(28,10) ENCODE az64  
	,PURCHASE_CURRENCY_CODE VARCHAR(15) ENCODE lzo 		
	,PAYABLES_UNIT_PRICE NUMERIC(28,10) ENCODE az64  
	,PAYABLES_CURRENCY_CODE VARCHAR(15) ENCODE lzo 		
	,SALES_UNIT_PRICE NUMERIC(28,10) ENCODE az64  
	,SALES_CURRENCY_CODE VARCHAR(15) ENCODE lzo 
	,OPERATIONAL_STATUS_CODE VARCHAR(30) ENCODE lzo 
	,SOURCE_CODE VARCHAR(10) ENCODE lzo 
	,ROUTE_UPDATE_WO_FLAG VARCHAR(1) ENCODE lzo
	,COST_UPDATE_WO_FLAG VARCHAR(1) ENCODE lzo
	,ROUTE_COST_EQUAL_FLAG VARCHAR(1) ENCODE lzo
	,LINEAR_ASSET VARCHAR(1) ENCODE lzo
	,SEGMENTED VARCHAR(1) ENCODE lzo
	,ROUTE_QUALITY_RESULT_FLAG VARCHAR(1) ENCODE lzo
	,ESRI_FEATURE VARCHAR(240) ENCODE lzo
	,NO_MEASURES_LA VARCHAR(1) ENCODE lzo
	,ROUTE_LAYER_ID NUMERIC(15,0) ENCODE az64 	
	,IN_SERVICE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64		
	,IOT_SYNC_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64		
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.csi_item_instances (
	INSTANCE_ID,
	INSTANCE_NUMBER,
	EXTERNAL_REFERENCE,
	INVENTORY_ITEM_ID,
	INVENTORY_REVISION,
	INV_MASTER_ORGANIZATION_ID,
	SERIAL_NUMBER,
	MFG_SERIAL_NUMBER_FLAG,
	LOT_NUMBER,
	QUANTITY,
	UNIT_OF_MEASURE,
	ACCOUNTING_CLASS_CODE,
	INSTANCE_CONDITION_ID,
	INSTANCE_STATUS_ID,
	CUSTOMER_VIEW_FLAG,
	MERCHANT_VIEW_FLAG,
	SELLABLE_FLAG,
	SYSTEM_ID,
	INSTANCE_TYPE_CODE,
	ACTIVE_START_DATE,
	ACTIVE_END_DATE,
	LOCATION_TYPE_CODE,
	LOCATION_ID,
	INV_ORGANIZATION_ID,
	INV_SUBINVENTORY_NAME,
	INV_LOCATOR_ID,
	PA_PROJECT_ID,
	PA_PROJECT_TASK_ID,
	IN_TRANSIT_ORDER_LINE_ID,
	WIP_JOB_ID,
	PO_ORDER_LINE_ID,
	LAST_OE_ORDER_LINE_ID,
	LAST_OE_RMA_LINE_ID,
	LAST_PO_PO_LINE_ID,
	LAST_OE_PO_NUMBER,
	LAST_WIP_JOB_ID,
	LAST_PA_PROJECT_ID,
	LAST_PA_TASK_ID,
	LAST_OE_AGREEMENT_ID,
	INSTALL_DATE,
	MANUALLY_CREATED_FLAG,
	RETURN_BY_DATE,
	ACTUAL_RETURN_DATE,
	CREATION_COMPLETE_FLAG,
	COMPLETENESS_FLAG,
	CONTEXT,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATE_LOGIN,
	OBJECT_VERSION_NUMBER,
	SECURITY_GROUP_ID,
	LAST_TXN_LINE_DETAIL_ID,
	INSTALL_LOCATION_TYPE_CODE,
	INSTALL_LOCATION_ID,
	INSTANCE_USAGE_CODE,
	OWNER_PARTY_SOURCE_TABLE,
	OWNER_PARTY_ID,
	OWNER_PARTY_ACCOUNT_ID,
	LAST_VLD_ORGANIZATION_ID,
	MIGRATED_FLAG,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	CONFIG_INST_HDR_ID,
	CONFIG_INST_REV_NUM,
	CONFIG_INST_ITEM_ID,
	CONFIG_VALID_STATUS,
	INSTANCE_DESCRIPTION,
	LAST_PURGE_DATE,
	ATTRIBUTE16,
	ATTRIBUTE17,
	ATTRIBUTE18,
	ATTRIBUTE19,
	ATTRIBUTE20,
	ATTRIBUTE21,
	ATTRIBUTE22,
	ATTRIBUTE23,
	ATTRIBUTE24,
	ATTRIBUTE25,
	ATTRIBUTE26,
	ATTRIBUTE27,
	ATTRIBUTE28,
	ATTRIBUTE29,
	ATTRIBUTE30,
	NETWORK_ASSET_FLAG,
	MAINTAINABLE_FLAG,
	PN_LOCATION_ID,
	ASSET_CRITICALITY_CODE,
	CATEGORY_ID,
	EQUIPMENT_GEN_OBJECT_ID,
	INSTANTIATION_FLAG,
	LINEAR_LOCATION_ID,
	OPERATIONAL_LOG_FLAG,
	CHECKIN_STATUS,
	SUPPLIER_WARRANTY_EXP_DATE,
	PURCHASE_UNIT_PRICE,
	PURCHASE_CURRENCY_CODE,
	PAYABLES_UNIT_PRICE,
	PAYABLES_CURRENCY_CODE,
	SALES_UNIT_PRICE,
	SALES_CURRENCY_CODE,
	OPERATIONAL_STATUS_CODE,
	SOURCE_CODE,
	ROUTE_UPDATE_WO_FLAG,
	COST_UPDATE_WO_FLAG,
	ROUTE_COST_EQUAL_FLAG,
	LINEAR_ASSET,
	SEGMENTED,
	ROUTE_QUALITY_RESULT_FLAG,
	ESRI_FEATURE,
	NO_MEASURES_LA,
	ROUTE_LAYER_ID,
	IN_SERVICE_DATE,
	IOT_SYNC_DATE,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
		INSTANCE_ID,
		INSTANCE_NUMBER,
		EXTERNAL_REFERENCE,
		INVENTORY_ITEM_ID,
		INVENTORY_REVISION,
		INV_MASTER_ORGANIZATION_ID,
		SERIAL_NUMBER,
		MFG_SERIAL_NUMBER_FLAG,
		LOT_NUMBER,
		QUANTITY,
		UNIT_OF_MEASURE,
		ACCOUNTING_CLASS_CODE,
		INSTANCE_CONDITION_ID,
		INSTANCE_STATUS_ID,
		CUSTOMER_VIEW_FLAG,
		MERCHANT_VIEW_FLAG,
		SELLABLE_FLAG,
		SYSTEM_ID,
		INSTANCE_TYPE_CODE,
		ACTIVE_START_DATE,
		ACTIVE_END_DATE,
		LOCATION_TYPE_CODE,
		LOCATION_ID,
		INV_ORGANIZATION_ID,
		INV_SUBINVENTORY_NAME,
		INV_LOCATOR_ID,
		PA_PROJECT_ID,
		PA_PROJECT_TASK_ID,
		IN_TRANSIT_ORDER_LINE_ID,
		WIP_JOB_ID,
		PO_ORDER_LINE_ID,
		LAST_OE_ORDER_LINE_ID,
		LAST_OE_RMA_LINE_ID,
		LAST_PO_PO_LINE_ID,
		LAST_OE_PO_NUMBER,
		LAST_WIP_JOB_ID,
		LAST_PA_PROJECT_ID,
		LAST_PA_TASK_ID,
		LAST_OE_AGREEMENT_ID,
		INSTALL_DATE,
		MANUALLY_CREATED_FLAG,
		RETURN_BY_DATE,
		ACTUAL_RETURN_DATE,
		CREATION_COMPLETE_FLAG,
		COMPLETENESS_FLAG,
		CONTEXT,
		ATTRIBUTE1,
		ATTRIBUTE2,
		ATTRIBUTE3,
		ATTRIBUTE4,
		ATTRIBUTE5,
		ATTRIBUTE6,
		ATTRIBUTE7,
		ATTRIBUTE8,
		ATTRIBUTE9,
		ATTRIBUTE10,
		ATTRIBUTE11,
		ATTRIBUTE12,
		ATTRIBUTE13,
		ATTRIBUTE14,
		ATTRIBUTE15,
		CREATED_BY,
		CREATION_DATE,
		LAST_UPDATED_BY,
		LAST_UPDATE_DATE,
		LAST_UPDATE_LOGIN,
		OBJECT_VERSION_NUMBER,
		SECURITY_GROUP_ID,
		LAST_TXN_LINE_DETAIL_ID,
		INSTALL_LOCATION_TYPE_CODE,
		INSTALL_LOCATION_ID,
		INSTANCE_USAGE_CODE,
		OWNER_PARTY_SOURCE_TABLE,
		OWNER_PARTY_ID,
		OWNER_PARTY_ACCOUNT_ID,
		LAST_VLD_ORGANIZATION_ID,
		MIGRATED_FLAG,
		REQUEST_ID,
		PROGRAM_APPLICATION_ID,
		PROGRAM_ID,
		PROGRAM_UPDATE_DATE,
		CONFIG_INST_HDR_ID,
		CONFIG_INST_REV_NUM,
		CONFIG_INST_ITEM_ID,
		CONFIG_VALID_STATUS,
		INSTANCE_DESCRIPTION,
		LAST_PURGE_DATE,
		ATTRIBUTE16,
		ATTRIBUTE17,
		ATTRIBUTE18,
		ATTRIBUTE19,
		ATTRIBUTE20,
		ATTRIBUTE21,
		ATTRIBUTE22,
		ATTRIBUTE23,
		ATTRIBUTE24,
		ATTRIBUTE25,
		ATTRIBUTE26,
		ATTRIBUTE27,
		ATTRIBUTE28,
		ATTRIBUTE29,
		ATTRIBUTE30,
		NETWORK_ASSET_FLAG,
		MAINTAINABLE_FLAG,
		PN_LOCATION_ID,
		ASSET_CRITICALITY_CODE,
		CATEGORY_ID,
		EQUIPMENT_GEN_OBJECT_ID,
		INSTANTIATION_FLAG,
		LINEAR_LOCATION_ID,
		OPERATIONAL_LOG_FLAG,
		CHECKIN_STATUS,
		SUPPLIER_WARRANTY_EXP_DATE,
		PURCHASE_UNIT_PRICE,
		PURCHASE_CURRENCY_CODE,
		PAYABLES_UNIT_PRICE,
		PAYABLES_CURRENCY_CODE,
		SALES_UNIT_PRICE,
		SALES_CURRENCY_CODE,
		OPERATIONAL_STATUS_CODE,
		SOURCE_CODE,
		ROUTE_UPDATE_WO_FLAG,
		COST_UPDATE_WO_FLAG,
		ROUTE_COST_EQUAL_FLAG,
		LINEAR_ASSET,
		SEGMENTED,
		ROUTE_QUALITY_RESULT_FLAG,
		ESRI_FEATURE,
		NO_MEASURES_LA,
		ROUTE_LAYER_ID,
		IN_SERVICE_DATE,
		IOT_SYNC_DATE,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
    FROM
        bec_ods_stg.csi_item_instances;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'csi_item_instances';
	
commit;