/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.FA_BOOKS;

CREATE TABLE IF NOT EXISTS bec_ods.FA_BOOKS
(
	BOOK_TYPE_CODE VARCHAR(15) ENCODE lzo 
	,ASSET_ID NUMERIC(15,0) ENCODE az64 
	,DATE_PLACED_IN_SERVICE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DATE_EFFECTIVE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DEPRN_START_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DEPRN_METHOD_CODE VARCHAR(12) ENCODE lzo 
	,LIFE_IN_MONTHS NUMERIC(4,0) ENCODE az64 
	,RATE_ADJUSTMENT_FACTOR NUMERIC(28,10) ENCODE az64 
	,ADJUSTED_COST NUMERIC(28,10) ENCODE az64 
	,COST NUMERIC(28,10) ENCODE az64 
	,ORIGINAL_COST NUMERIC(28,10) ENCODE az64 
	,SALVAGE_VALUE NUMERIC(28,10) ENCODE az64 
	,PRORATE_CONVENTION_CODE VARCHAR(10) ENCODE lzo 
	,PRORATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,COST_CHANGE_FLAG VARCHAR(3) ENCODE lzo 
	,ADJUSTMENT_REQUIRED_STATUS VARCHAR(4) ENCODE lzo 
	,CAPITALIZE_FLAG VARCHAR(3) ENCODE lzo 
	,RETIREMENT_PENDING_FLAG VARCHAR(3) ENCODE lzo 
	,DEPRECIATE_FLAG VARCHAR(3) ENCODE lzo 
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64 
	,DATE_INEFFECTIVE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,TRANSACTION_HEADER_ID_IN NUMERIC(15,0) ENCODE az64 
	,TRANSACTION_HEADER_ID_OUT NUMERIC(15,0) ENCODE az64 
	,ITC_AMOUNT_ID NUMERIC(15,0) ENCODE az64 
	,ITC_AMOUNT NUMERIC(28,10) ENCODE az64
	,RETIREMENT_ID NUMERIC(15,0) ENCODE az64 
	,TAX_REQUEST_ID NUMERIC(15,0) ENCODE az64 
	,ITC_BASIS NUMERIC(28,10) ENCODE az64 
	,BASIC_RATE NUMERIC(28,10) ENCODE az64 
	,ADJUSTED_RATE NUMERIC(28,10) ENCODE az64 
	,BONUS_RULE VARCHAR(30) ENCODE lzo 
	,CEILING_NAME VARCHAR(30) ENCODE lzo 
	,RECOVERABLE_COST NUMERIC(28,10) ENCODE az64 
	,LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64 
	,ADJUSTED_CAPACITY NUMERIC(28,10) ENCODE az64 
	,FULLY_RSVD_REVALS_COUNTER NUMERIC(5,0) ENCODE az64 
	,IDLED_FLAG VARCHAR(3) ENCODE lzo 
	,PERIOD_COUNTER_CAPITALIZED NUMERIC(15,0) ENCODE az64 
	,PERIOD_COUNTER_FULLY_RESERVED NUMERIC(15,0) ENCODE az64 
	,PERIOD_COUNTER_FULLY_RETIRED NUMERIC(15,0) ENCODE az64 
	,PRODUCTION_CAPACITY NUMERIC(28,10) ENCODE az64 
	,REVAL_AMORTIZATION_BASIS NUMERIC(15,0) ENCODE az64  
	,REVAL_CEILING NUMERIC(28,10) ENCODE az64 
	,UNIT_OF_MEASURE VARCHAR(25) ENCODE lzo 
	,UNREVALUED_COST NUMERIC(28,10) ENCODE az64 
	,ANNUAL_DEPRN_ROUNDING_FLAG VARCHAR(5) ENCODE lzo 
	,PERCENT_SALVAGE_VALUE NUMERIC(28,10) ENCODE az64 
	,ALLOWED_DEPRN_LIMIT NUMERIC(28,10) ENCODE az64 
	,ALLOWED_DEPRN_LIMIT_AMOUNT NUMERIC(28,10) ENCODE az64 
	,PERIOD_COUNTER_LIFE_COMPLETE NUMERIC(15,0) ENCODE az64 
	,ADJUSTED_RECOVERABLE_COST NUMERIC(28,10) ENCODE az64
	,ANNUAL_ROUNDING_FLAG VARCHAR(5) ENCODE lzo 
	,GLOBAL_ATTRIBUTE1 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE2 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE3 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE4 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE5 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE6 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE7 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE8 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE9 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE10 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE11 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE12 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE13 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE14 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE15 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE16 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE17 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE18 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE19 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE20 VARCHAR(150) ENCODE lzo 
	,GLOBAL_ATTRIBUTE_CATEGORY VARCHAR(30) ENCODE lzo 
	,EOFY_ADJ_COST NUMERIC(28,10) ENCODE az64 
	,EOFY_FORMULA_FACTOR NUMERIC(28,10) ENCODE az64 
	,SHORT_FISCAL_YEAR_FLAG VARCHAR(3) ENCODE lzo 
	,CONVERSION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,ORIGINAL_DEPRN_START_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,REMAINING_LIFE1 NUMERIC(4,0) ENCODE az64 
	,REMAINING_LIFE2 NUMERIC(4,0) ENCODE az64 
	,OLD_ADJUSTED_COST NUMERIC(28,10) ENCODE az64 
	,FORMULA_FACTOR NUMERIC(28,10) ENCODE az64 
	,GROUP_ASSET_ID NUMERIC(15,0) ENCODE az64 
	,SALVAGE_TYPE VARCHAR(30) ENCODE lzo 
	,DEPRN_LIMIT_TYPE VARCHAR(30) ENCODE lzo 
	,REDUCTION_RATE NUMERIC(28,10) ENCODE az64
	,REDUCE_ADDITION_FLAG VARCHAR(1) ENCODE lzo 
	,REDUCE_ADJUSTMENT_FLAG VARCHAR(1) ENCODE lzo 
	,REDUCE_RETIREMENT_FLAG VARCHAR(1) ENCODE lzo 
	,RECOGNIZE_GAIN_LOSS VARCHAR(30) ENCODE lzo 
	,RECAPTURE_RESERVE_FLAG VARCHAR(1) ENCODE lzo 
	,LIMIT_PROCEEDS_FLAG VARCHAR(1) ENCODE lzo 
	,TERMINAL_GAIN_LOSS VARCHAR(30) ENCODE lzo 
	,TRACKING_METHOD VARCHAR(30) ENCODE lzo 
	,EXCLUDE_FULLY_RSV_FLAG VARCHAR(1) ENCODE lzo 
	,EXCESS_ALLOCATION_OPTION VARCHAR(30) ENCODE lzo 
	,DEPRECIATION_OPTION VARCHAR(30) ENCODE lzo 
	,MEMBER_ROLLUP_FLAG VARCHAR(1) ENCODE lzo 
	,ALLOCATE_TO_FULLY_RSV_FLAG VARCHAR(1) ENCODE lzo 
	,ALLOCATE_TO_FULLY_RET_FLAG VARCHAR(1) ENCODE lzo 
	,TERMINAL_GAIN_LOSS_AMOUNT NUMERIC(28,10) ENCODE az64 
	,CIP_COST NUMERIC(28,10) ENCODE az64 
	,YTD_PROCEEDS NUMERIC(28,10) ENCODE az64 
	,LTD_PROCEEDS NUMERIC(28,10) ENCODE az64 
	,LTD_COST_OF_REMOVAL NUMERIC(28,10) ENCODE az64 
	,EOFY_RESERVE NUMERIC(28,10) ENCODE az64 
	,PRIOR_EOFY_RESERVE NUMERIC(28,10) ENCODE az64
	,EOP_ADJ_COST NUMERIC(28,10) ENCODE az64 
	,EOP_FORMULA_FACTOR NUMERIC(28,10) ENCODE az64 
	,EXCLUDE_PROCEEDS_FROM_BASIS VARCHAR(1) ENCODE lzo 
	,RETIREMENT_DEPRN_OPTION VARCHAR(30) ENCODE lzo 
	,TERMINAL_GAIN_LOSS_FLAG VARCHAR(1) ENCODE lzo 
	,SUPER_GROUP_ID NUMERIC(15,0) ENCODE az64 
	,OVER_DEPRECIATE_OPTION VARCHAR(30) ENCODE lzo 
	,DISABLED_FLAG VARCHAR(1) ENCODE lzo 
	,OLD_ADJUSTED_CAPACITY NUMERIC(28,10) ENCODE az64 
	,DRY_HOLE_FLAG VARCHAR(1) ENCODE lzo 
	,CASH_GENERATING_UNIT_ID NUMERIC(15,0) ENCODE az64 
	,CONTRACT_ID NUMERIC(15,0) ENCODE az64  
	,RATE_IN_USE NUMERIC(28,10) ENCODE az64 
	,EXTENDED_DEPRN_FLAG VARCHAR(1) ENCODE lzo 
	,EXTENDED_DEPRECIATION_PERIOD NUMERIC(15,0) ENCODE az64 
	,PERIOD_COUNTER_FULLY_EXTENDED NUMERIC(15,0) ENCODE az64 
	,NBV_AT_SWITCH NUMERIC(28,10) ENCODE az64
	,PRIOR_DEPRN_LIMIT_TYPE VARCHAR(30) ENCODE lzo 
	,PRIOR_DEPRN_LIMIT_AMOUNT NUMERIC(28,10) ENCODE az64 
	,PRIOR_DEPRN_LIMIT NUMERIC(28,10) ENCODE az64 
	,PRIOR_DEPRN_METHOD VARCHAR(12) ENCODE lzo 
	,PRIOR_LIFE_IN_MONTHS NUMERIC(6,0) ENCODE az64 
	,PRIOR_BASIC_RATE NUMERIC(28,10) ENCODE az64 
	,PRIOR_ADJUSTED_RATE NUMERIC(28,10) ENCODE az64 
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.FA_BOOKS (
    BOOK_TYPE_CODE, 
	ASSET_ID, 
	DATE_PLACED_IN_SERVICE, 
	DATE_EFFECTIVE, 
	DEPRN_START_DATE, 
	DEPRN_METHOD_CODE, 
	LIFE_IN_MONTHS, 
	RATE_ADJUSTMENT_FACTOR, 
	ADJUSTED_COST, 
	COST, 
	ORIGINAL_COST, 
	SALVAGE_VALUE, 
	PRORATE_CONVENTION_CODE, 
	PRORATE_DATE, 
	COST_CHANGE_FLAG, 
	ADJUSTMENT_REQUIRED_STATUS, 
	CAPITALIZE_FLAG, 
	RETIREMENT_PENDING_FLAG, 
	DEPRECIATE_FLAG, 
	LAST_UPDATE_DATE, 
	LAST_UPDATED_BY, 
	DATE_INEFFECTIVE, 
	TRANSACTION_HEADER_ID_IN, 
	TRANSACTION_HEADER_ID_OUT, 
	ITC_AMOUNT_ID, 
	ITC_AMOUNT,
	RETIREMENT_ID, 
	TAX_REQUEST_ID, 
	ITC_BASIS, 
	BASIC_RATE, 
	ADJUSTED_RATE, 
	BONUS_RULE, 
	CEILING_NAME, 
	RECOVERABLE_COST, 
	LAST_UPDATE_LOGIN, 
	ADJUSTED_CAPACITY, 
	FULLY_RSVD_REVALS_COUNTER, 
	IDLED_FLAG, 
	PERIOD_COUNTER_CAPITALIZED, 
	PERIOD_COUNTER_FULLY_RESERVED, 
	PERIOD_COUNTER_FULLY_RETIRED, 
	PRODUCTION_CAPACITY, 
	REVAL_AMORTIZATION_BASIS,  
	REVAL_CEILING, 
	UNIT_OF_MEASURE, 
	UNREVALUED_COST, 
	ANNUAL_DEPRN_ROUNDING_FLAG, 
	PERCENT_SALVAGE_VALUE, 
	ALLOWED_DEPRN_LIMIT, 
	ALLOWED_DEPRN_LIMIT_AMOUNT, 
	PERIOD_COUNTER_LIFE_COMPLETE, 
	ADJUSTED_RECOVERABLE_COST,
	ANNUAL_ROUNDING_FLAG, 
	GLOBAL_ATTRIBUTE1, 
	GLOBAL_ATTRIBUTE2, 
	GLOBAL_ATTRIBUTE3, 
	GLOBAL_ATTRIBUTE4, 
	GLOBAL_ATTRIBUTE5, 
	GLOBAL_ATTRIBUTE6, 
	GLOBAL_ATTRIBUTE7, 
	GLOBAL_ATTRIBUTE8, 
	GLOBAL_ATTRIBUTE9, 
	GLOBAL_ATTRIBUTE10, 
	GLOBAL_ATTRIBUTE11, 
	GLOBAL_ATTRIBUTE12, 
	GLOBAL_ATTRIBUTE13, 
	GLOBAL_ATTRIBUTE14, 
	GLOBAL_ATTRIBUTE15, 
	GLOBAL_ATTRIBUTE16, 
	GLOBAL_ATTRIBUTE17, 
	GLOBAL_ATTRIBUTE18, 
	GLOBAL_ATTRIBUTE19, 
	GLOBAL_ATTRIBUTE20, 
	GLOBAL_ATTRIBUTE_CATEGORY, 
	EOFY_ADJ_COST, 
	EOFY_FORMULA_FACTOR, 
	SHORT_FISCAL_YEAR_FLAG, 
	CONVERSION_DATE, 
	ORIGINAL_DEPRN_START_DATE, 
	REMAINING_LIFE1, 
	REMAINING_LIFE2, 
	OLD_ADJUSTED_COST, 
	FORMULA_FACTOR, 
	GROUP_ASSET_ID, 
	SALVAGE_TYPE, 
	DEPRN_LIMIT_TYPE, 
	REDUCTION_RATE,
	REDUCE_ADDITION_FLAG, 
	REDUCE_ADJUSTMENT_FLAG, 
	REDUCE_RETIREMENT_FLAG, 
	RECOGNIZE_GAIN_LOSS, 
	RECAPTURE_RESERVE_FLAG, 
	LIMIT_PROCEEDS_FLAG, 
	TERMINAL_GAIN_LOSS, 
	TRACKING_METHOD, 
	EXCLUDE_FULLY_RSV_FLAG, 
	EXCESS_ALLOCATION_OPTION, 
	DEPRECIATION_OPTION, 
	MEMBER_ROLLUP_FLAG, 
	ALLOCATE_TO_FULLY_RSV_FLAG, 
	ALLOCATE_TO_FULLY_RET_FLAG, 
	TERMINAL_GAIN_LOSS_AMOUNT, 
	CIP_COST, 
	YTD_PROCEEDS, 
	LTD_PROCEEDS, 
	LTD_COST_OF_REMOVAL, 
	EOFY_RESERVE, 
	PRIOR_EOFY_RESERVE,
	EOP_ADJ_COST, 
	EOP_FORMULA_FACTOR, 
	EXCLUDE_PROCEEDS_FROM_BASIS, 
	RETIREMENT_DEPRN_OPTION, 
	TERMINAL_GAIN_LOSS_FLAG, 
	SUPER_GROUP_ID, 
	OVER_DEPRECIATE_OPTION, 
	DISABLED_FLAG, 
	OLD_ADJUSTED_CAPACITY, 
	DRY_HOLE_FLAG, 
	CASH_GENERATING_UNIT_ID, 
	CONTRACT_ID,  
	RATE_IN_USE, 
	EXTENDED_DEPRN_FLAG, 
	EXTENDED_DEPRECIATION_PERIOD, 
	PERIOD_COUNTER_FULLY_EXTENDED, 
	NBV_AT_SWITCH,
	PRIOR_DEPRN_LIMIT_TYPE, 
	PRIOR_DEPRN_LIMIT_AMOUNT, 
	PRIOR_DEPRN_LIMIT, 
	PRIOR_DEPRN_METHOD, 
	PRIOR_LIFE_IN_MONTHS, 
	PRIOR_BASIC_RATE, 
	PRIOR_ADJUSTED_RATE,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
        BOOK_TYPE_CODE, 
		ASSET_ID, 
		DATE_PLACED_IN_SERVICE, 
		DATE_EFFECTIVE, 
		DEPRN_START_DATE, 
		DEPRN_METHOD_CODE, 
		LIFE_IN_MONTHS, 
		RATE_ADJUSTMENT_FACTOR, 
		ADJUSTED_COST, 
		COST, 
		ORIGINAL_COST, 
		SALVAGE_VALUE, 
		PRORATE_CONVENTION_CODE, 
		PRORATE_DATE, 
		COST_CHANGE_FLAG, 
		ADJUSTMENT_REQUIRED_STATUS, 
		CAPITALIZE_FLAG, 
		RETIREMENT_PENDING_FLAG, 
		DEPRECIATE_FLAG, 
		LAST_UPDATE_DATE, 
		LAST_UPDATED_BY, 
		DATE_INEFFECTIVE, 
		TRANSACTION_HEADER_ID_IN, 
		TRANSACTION_HEADER_ID_OUT, 
		ITC_AMOUNT_ID, 
		ITC_AMOUNT,
		RETIREMENT_ID, 
		TAX_REQUEST_ID, 
		ITC_BASIS, 
		BASIC_RATE, 
		ADJUSTED_RATE, 
		BONUS_RULE, 
		CEILING_NAME, 
		RECOVERABLE_COST, 
		LAST_UPDATE_LOGIN, 
		ADJUSTED_CAPACITY, 
		FULLY_RSVD_REVALS_COUNTER, 
		IDLED_FLAG, 
		PERIOD_COUNTER_CAPITALIZED, 
		PERIOD_COUNTER_FULLY_RESERVED, 
		PERIOD_COUNTER_FULLY_RETIRED, 
		PRODUCTION_CAPACITY, 
		REVAL_AMORTIZATION_BASIS,  
		REVAL_CEILING, 
		UNIT_OF_MEASURE, 
		UNREVALUED_COST, 
		ANNUAL_DEPRN_ROUNDING_FLAG, 
		PERCENT_SALVAGE_VALUE, 
		ALLOWED_DEPRN_LIMIT, 
		ALLOWED_DEPRN_LIMIT_AMOUNT, 
		PERIOD_COUNTER_LIFE_COMPLETE, 
		ADJUSTED_RECOVERABLE_COST,
		ANNUAL_ROUNDING_FLAG, 
		GLOBAL_ATTRIBUTE1, 
		GLOBAL_ATTRIBUTE2, 
		GLOBAL_ATTRIBUTE3, 
		GLOBAL_ATTRIBUTE4, 
		GLOBAL_ATTRIBUTE5, 
		GLOBAL_ATTRIBUTE6, 
		GLOBAL_ATTRIBUTE7, 
		GLOBAL_ATTRIBUTE8, 
		GLOBAL_ATTRIBUTE9, 
		GLOBAL_ATTRIBUTE10, 
		GLOBAL_ATTRIBUTE11, 
		GLOBAL_ATTRIBUTE12, 
		GLOBAL_ATTRIBUTE13, 
		GLOBAL_ATTRIBUTE14, 
		GLOBAL_ATTRIBUTE15, 
		GLOBAL_ATTRIBUTE16, 
		GLOBAL_ATTRIBUTE17, 
		GLOBAL_ATTRIBUTE18, 
		GLOBAL_ATTRIBUTE19, 
		GLOBAL_ATTRIBUTE20, 
		GLOBAL_ATTRIBUTE_CATEGORY, 
		EOFY_ADJ_COST, 
		EOFY_FORMULA_FACTOR, 
		SHORT_FISCAL_YEAR_FLAG, 
		CONVERSION_DATE, 
		ORIGINAL_DEPRN_START_DATE, 
		REMAINING_LIFE1, 
		REMAINING_LIFE2, 
		OLD_ADJUSTED_COST, 
		FORMULA_FACTOR, 
		GROUP_ASSET_ID, 
		SALVAGE_TYPE, 
		DEPRN_LIMIT_TYPE, 
		REDUCTION_RATE,
		REDUCE_ADDITION_FLAG, 
		REDUCE_ADJUSTMENT_FLAG, 
		REDUCE_RETIREMENT_FLAG, 
		RECOGNIZE_GAIN_LOSS, 
		RECAPTURE_RESERVE_FLAG, 
		LIMIT_PROCEEDS_FLAG, 
		TERMINAL_GAIN_LOSS, 
		TRACKING_METHOD, 
		EXCLUDE_FULLY_RSV_FLAG, 
		EXCESS_ALLOCATION_OPTION, 
		DEPRECIATION_OPTION, 
		MEMBER_ROLLUP_FLAG, 
		ALLOCATE_TO_FULLY_RSV_FLAG, 
		ALLOCATE_TO_FULLY_RET_FLAG, 
		TERMINAL_GAIN_LOSS_AMOUNT, 
		CIP_COST, 
		YTD_PROCEEDS, 
		LTD_PROCEEDS, 
		LTD_COST_OF_REMOVAL, 
		EOFY_RESERVE, 
		PRIOR_EOFY_RESERVE,
		EOP_ADJ_COST, 
		EOP_FORMULA_FACTOR, 
		EXCLUDE_PROCEEDS_FROM_BASIS, 
		RETIREMENT_DEPRN_OPTION, 
		TERMINAL_GAIN_LOSS_FLAG, 
		SUPER_GROUP_ID, 
		OVER_DEPRECIATE_OPTION, 
		DISABLED_FLAG, 
		OLD_ADJUSTED_CAPACITY, 
		DRY_HOLE_FLAG, 
		CASH_GENERATING_UNIT_ID, 
		CONTRACT_ID,  
		RATE_IN_USE, 
		EXTENDED_DEPRN_FLAG, 
		EXTENDED_DEPRECIATION_PERIOD, 
		PERIOD_COUNTER_FULLY_EXTENDED, 
		NBV_AT_SWITCH,
		PRIOR_DEPRN_LIMIT_TYPE, 
		PRIOR_DEPRN_LIMIT_AMOUNT, 
		PRIOR_DEPRN_LIMIT, 
		PRIOR_DEPRN_METHOD, 
		PRIOR_LIFE_IN_MONTHS, 
		PRIOR_BASIC_RATE, 
		PRIOR_ADJUSTED_RATE, 
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
    FROM
        bec_ods_stg.FA_BOOKS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'fa_books';
	
commit;