/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.FA_MC_DEPRN_PERIODS;

CREATE TABLE IF NOT EXISTS bec_ods.FA_MC_DEPRN_PERIODS
(
	SET_OF_BOOKS_ID NUMERIC(15,0) ENCODE az64 
	,BOOK_TYPE_CODE VARCHAR(15) ENCODE lzo 
	,PERIOD_NAME VARCHAR(15) ENCODE lzo
	,PERIOD_COUNTER NUMERIC(15,0) ENCODE az64 
	,FISCAL_YEAR NUMERIC(4,0) ENCODE az64 
	,PERIOD_NUM NUMERIC(3,0) ENCODE az64 
	,PERIOD_OPEN_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 
	,PERIOD_CLOSE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 
	,DEPRECIATION_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,RETIREMENT_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,RECLASS_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,TRANSFER_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,ADDITION_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,ADJUSTMENT_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,DEFERRED_DEPRN_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,CALENDAR_PERIOD_OPEN_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 
	,CALENDAR_PERIOD_CLOSE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 
	,CIP_ADDITION_BATCH_ID NUMERIC(15,0) ENCODE az64
	,CIP_ADJUSTMENT_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,CIP_RECLASS_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,CIP_RETIREMENT_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,CIP_REVAL_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,CIP_TRANSFER_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,REVAL_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,DEPRN_ADJUSTMENT_BATCH_ID NUMERIC(15,0) ENCODE az64 
	,DEPRN_RUN VARCHAR(1) ENCODE lzo
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.FA_MC_DEPRN_PERIODS (
    SET_OF_BOOKS_ID,
	BOOK_TYPE_CODE, 
	PERIOD_NAME,
	PERIOD_COUNTER,
	FISCAL_YEAR,
	PERIOD_NUM,
	PERIOD_OPEN_DATE,
	PERIOD_CLOSE_DATE,
	DEPRECIATION_BATCH_ID,
	RETIREMENT_BATCH_ID,
	RECLASS_BATCH_ID,
	TRANSFER_BATCH_ID,
	ADDITION_BATCH_ID,
	ADJUSTMENT_BATCH_ID,
	DEFERRED_DEPRN_BATCH_ID,
	CALENDAR_PERIOD_OPEN_DATE,
	CALENDAR_PERIOD_CLOSE_DATE,
	CIP_ADDITION_BATCH_ID,
	CIP_ADJUSTMENT_BATCH_ID,
	CIP_RECLASS_BATCH_ID,
	CIP_RETIREMENT_BATCH_ID,
	CIP_REVAL_BATCH_ID,
	CIP_TRANSFER_BATCH_ID,
	REVAL_BATCH_ID,
	DEPRN_ADJUSTMENT_BATCH_ID,
	DEPRN_RUN,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
        SET_OF_BOOKS_ID,
		BOOK_TYPE_CODE, 
		PERIOD_NAME,
		PERIOD_COUNTER,
		FISCAL_YEAR,
		PERIOD_NUM,
		PERIOD_OPEN_DATE,
		PERIOD_CLOSE_DATE,
		DEPRECIATION_BATCH_ID,
		RETIREMENT_BATCH_ID,
		RECLASS_BATCH_ID,
		TRANSFER_BATCH_ID,
		ADDITION_BATCH_ID,
		ADJUSTMENT_BATCH_ID,
		DEFERRED_DEPRN_BATCH_ID,
		CALENDAR_PERIOD_OPEN_DATE,
		CALENDAR_PERIOD_CLOSE_DATE,
		CIP_ADDITION_BATCH_ID,
		CIP_ADJUSTMENT_BATCH_ID,
		CIP_RECLASS_BATCH_ID,
		CIP_RETIREMENT_BATCH_ID,
		CIP_REVAL_BATCH_ID,
		CIP_TRANSFER_BATCH_ID,
		REVAL_BATCH_ID,
		DEPRN_ADJUSTMENT_BATCH_ID,
		DEPRN_RUN,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
    FROM
        bec_ods_stg.FA_MC_DEPRN_PERIODS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'fa_mc_deprn_periods';
	
commit;