/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.fnd_document_sequences;

CREATE TABLE IF NOT EXISTS bec_ods.fnd_document_sequences
(
	DOC_SEQUENCE_ID NUMERIC(15,0)   ENCODE az64
	,NAME VARCHAR(30)   ENCODE lzo
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64	
	,LAST_UPDATED_BY NUMERIC(15,0)   ENCODE az64
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,CREATED_BY NUMERIC(15,0)   ENCODE az64
	,LAST_UPDATE_LOGIN NUMERIC(15,0)   ENCODE az64
	,APPLICATION_ID	 NUMERIC(15,0)   ENCODE az64
	,AUDIT_TABLE_NAME VARCHAR(30)   ENCODE lzo
	,MESSAGE_FLAG VARCHAR(1)   ENCODE lzo
	,START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64	
	,TYPE VARCHAR(1)   ENCODE lzo
	,DB_SEQUENCE_NAME VARCHAR(30)   ENCODE lzo
	,END_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64	
	,INITIAL_VALUE NUMERIC(28,10)   ENCODE az64
	,TABLE_NAME VARCHAR(30)   ENCODE lzo
	,ATTRIBUTE_CATEGORY VARCHAR(30)   ENCODE LZO
	,ATTRIBUTE1 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE2 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE3 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE4 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE5 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE6 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE7 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE8 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE9 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE10 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE11 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE12 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE13 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE14 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE15 VARCHAR(150)   ENCODE LZO
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.fnd_document_sequences (
	DOC_SEQUENCE_ID,
	NAME,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	APPLICATION_ID,
	AUDIT_TABLE_NAME,
	MESSAGE_FLAG,
	START_DATE,
	TYPE,
	DB_SEQUENCE_NAME,
	END_DATE,
	INITIAL_VALUE,
	TABLE_NAME,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
		DOC_SEQUENCE_ID,
		NAME,
		LAST_UPDATE_DATE,
		LAST_UPDATED_BY,
		CREATION_DATE,
		CREATED_BY,
		LAST_UPDATE_LOGIN,
		APPLICATION_ID,
		AUDIT_TABLE_NAME,
		MESSAGE_FLAG,
		START_DATE,
		TYPE,
		DB_SEQUENCE_NAME,
		END_DATE,
		INITIAL_VALUE,
		TABLE_NAME,
		ATTRIBUTE_CATEGORY,
		ATTRIBUTE1,
		ATTRIBUTE2,
		ATTRIBUTE3,
		ATTRIBUTE4,
		ATTRIBUTE5,
		ATTRIBUTE6,
		ATTRIBUTE7,
		ATTRIBUTE8,
		ATTRIBUTE9,
		ATTRIBUTE10,
		ATTRIBUTE11,
		ATTRIBUTE12,
		ATTRIBUTE13,
		ATTRIBUTE14,
		ATTRIBUTE15,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
    FROM
        bec_ods_stg.fnd_document_sequences;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'fnd_document_sequences';