/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

drop table if exists bec_ods.FND_ID_FLEX_SEGMENTS;

CREATE TABLE IF NOT EXISTS bec_ods.FND_ID_FLEX_SEGMENTS
(
APPLICATION_ID	NUMERIC(10,0)   ENCODE az64
,ID_FLEX_CODE	VARCHAR(4)   ENCODE lzo
,ID_FLEX_NUM	NUMERIC(15,0)   ENCODE az64
,APPLICATION_COLUMN_NAME	VARCHAR(30)   ENCODE lzo
,SEGMENT_NAME	VARCHAR(30)   ENCODE lzo
,LAST_UPDATE_DATE	TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE	TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,SEGMENT_NUM	NUMERIC(3,0)   ENCODE az64
,APPLICATION_COLUMN_INDEX_FLAG	VARCHAR(1)   ENCODE lzo
,ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,REQUIRED_FLAG	VARCHAR(1)   ENCODE lzo
,DISPLAY_FLAG	VARCHAR(1)   ENCODE lzo
,DISPLAY_SIZE	NUMERIC(3,0)   ENCODE az64
,SECURITY_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,MAXIMUM_DESCRIPTION_LEN	NUMERIC(3,0)    ENCODE az64
,CONCATENATION_DESCRIPTION_LEN	NUMERIC(3,0)    ENCODE az64
,FLEX_VALUE_SET_ID	NUMERIC(10,0)   ENCODE az64
,RANGE_CODE	VARCHAR(1)   ENCODE lzo
,DEFAULT_TYPE	VARCHAR(1)   ENCODE lzo
,DEFAULT_VALUE	VARCHAR(2000)   ENCODE lzo
,RUNTIME_PROPERTY_FUNCTION	VARCHAR(2000)   ENCODE lzo
,SECURITY_GROUP_ID	NUMERIC(15,0)    ENCODE az64
,ADDITIONAL_WHERE_CLAUSE	VARCHAR(4000)   ENCODE lzo
,SEGMENT_INSERT_FLAG VARCHAR(1)   ENCODE lzo
,SEGMENT_UPDATE_FLAG VARCHAR(1)   ENCODE lzo
,ZD_EDITION_NAME VARCHAR(30)   ENCODE lzo
,ZD_SYNC VARCHAR(30)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.FND_ID_FLEX_SEGMENTS
(
APPLICATION_ID
,ID_FLEX_CODE
,ID_FLEX_NUM
,APPLICATION_COLUMN_NAME
,SEGMENT_NAME
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,SEGMENT_NUM
,APPLICATION_COLUMN_INDEX_FLAG
,ENABLED_FLAG
,REQUIRED_FLAG
,DISPLAY_FLAG
,DISPLAY_SIZE
,SECURITY_ENABLED_FLAG
,MAXIMUM_DESCRIPTION_LEN
,CONCATENATION_DESCRIPTION_LEN
,FLEX_VALUE_SET_ID
,RANGE_CODE
,DEFAULT_TYPE
,DEFAULT_VALUE
,RUNTIME_PROPERTY_FUNCTION 
,ADDITIONAL_WHERE_CLAUSE
,SEGMENT_INSERT_FLAG
,SEGMENT_UPDATE_FLAG
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date
)
(
select
APPLICATION_ID
,ID_FLEX_CODE
,ID_FLEX_NUM
,APPLICATION_COLUMN_NAME
,SEGMENT_NAME
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,SEGMENT_NUM
,APPLICATION_COLUMN_INDEX_FLAG
,ENABLED_FLAG
,REQUIRED_FLAG
,DISPLAY_FLAG
,DISPLAY_SIZE
,SECURITY_ENABLED_FLAG
,MAXIMUM_DESCRIPTION_LEN
,CONCATENATION_DESCRIPTION_LEN
,FLEX_VALUE_SET_ID
,RANGE_CODE
,DEFAULT_TYPE
,DEFAULT_VALUE
,RUNTIME_PROPERTY_FUNCTION 
,ADDITIONAL_WHERE_CLAUSE
,SEGMENT_INSERT_FLAG
,SEGMENT_UPDATE_FLAG
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
from
bec_ods_stg.FND_ID_FLEX_SEGMENTS);

end;


update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='fnd_id_flex_segments';

commit;
 