/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.FND_RESPONSIBILITY;

CREATE TABLE IF NOT EXISTS bec_ods.FND_RESPONSIBILITY
(
	APPLICATION_ID NUMERIC(15,0) ENCODE az64 
	,RESPONSIBILITY_ID NUMERIC(15,0) ENCODE az64
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 
	,CREATED_BY NUMERIC(15,0) ENCODE az64
	,LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64 
	,DATA_GROUP_APPLICATION_ID NUMERIC(15,0) ENCODE az64
	,DATA_GROUP_ID NUMERIC(15,0) ENCODE az64
	,MENU_ID NUMERIC(15,0) ENCODE az64
	,TERM_SECURITY_ENABLED_FLAG VARCHAR(1) ENCODE lzo
	,START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64 
	,END_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,GROUP_APPLICATION_ID NUMERIC(15,0) ENCODE az64 
	,REQUEST_GROUP_ID NUMERIC(15,0) ENCODE az64 
	,VERSION VARCHAR(1) ENCODE lzo
	,WEB_HOST_NAME VARCHAR(80) ENCODE lzo
	,WEB_AGENT_NAME VARCHAR(80) ENCODE lzo
	,RESPONSIBILITY_KEY VARCHAR(30) ENCODE lzo
	,ZD_EDITION_NAME VARCHAR(30) ENCODE lzo
	,ZD_SYNC VARCHAR(30) ENCODE lzo
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64  ) 
DISTSTYLE
auto;

INSERT INTO bec_ods.FND_RESPONSIBILITY (
    APPLICATION_ID, 
	RESPONSIBILITY_ID, 
	LAST_UPDATE_DATE, 
	LAST_UPDATED_BY, 
	CREATION_DATE, 
	CREATED_BY, 
	LAST_UPDATE_LOGIN, 
	DATA_GROUP_APPLICATION_ID, 
	DATA_GROUP_ID, 
	MENU_ID, 
	TERM_SECURITY_ENABLED_FLAG, 
	START_DATE, 
	END_DATE, 
	GROUP_APPLICATION_ID, 
	REQUEST_GROUP_ID, 
	VERSION, 
	WEB_HOST_NAME, 
	WEB_AGENT_NAME, 
	RESPONSIBILITY_KEY, 
	ZD_EDITION_NAME, 
	ZD_SYNC,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id
	,kca_seq_date
)
    SELECT
        APPLICATION_ID, 
		RESPONSIBILITY_ID, 
		LAST_UPDATE_DATE, 
		LAST_UPDATED_BY, 
		CREATION_DATE, 
		CREATED_BY, 
		LAST_UPDATE_LOGIN, 
		DATA_GROUP_APPLICATION_ID, 
		DATA_GROUP_ID, 
		MENU_ID, 
		TERM_SECURITY_ENABLED_FLAG, 
		START_DATE, 
		END_DATE, 
		GROUP_APPLICATION_ID, 
		REQUEST_GROUP_ID, 
		VERSION, 
		WEB_HOST_NAME, 
		WEB_AGENT_NAME, 
		RESPONSIBILITY_KEY, 
		ZD_EDITION_NAME, 
		ZD_SYNC,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
     FROM
        bec_ods_stg.FND_RESPONSIBILITY;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'fnd_responsibility';
	
commit;