/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach.
# File Version: KPI v1.0
*/

begin;

drop table if exists bec_ods.FND_USER;

CREATE TABLE IF NOT EXISTS bec_ods.FND_USER
(
USER_ID	NUMERIC(15,0)   ENCODE az64
,USER_NAME	 VARCHAR(100)   ENCODE lzo
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
--,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,ENCRYPTED_FOUNDATION_PASSWORD	 VARCHAR(100)   ENCODE lzo
,ENCRYPTED_USER_PASSWORD	 VARCHAR(100)   ENCODE lzo
--,SESSION_NUMBER	 NUMERIC(28,10)   ENCODE az64
,START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,END_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,DESCRIPTION	VARCHAR(240)   ENCODE lzo
--,LAST_LOGON_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PASSWORD_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PASSWORD_ACCESSES_LEFT	NUMERIC(15,0)   ENCODE az64
,PASSWORD_LIFESPAN_ACCESSES	NUMERIC(15,0)   ENCODE az64
,PASSWORD_LIFESPAN_DAYS	NUMERIC(15,0)   ENCODE az64
,EMPLOYEE_ID	NUMERIC(15,0)   ENCODE az64
,EMAIL_ADDRESS	VARCHAR(240)   ENCODE lzo
,FAX	VARCHAR(80)   ENCODE lzo
,CUSTOMER_ID	NUMERIC(15,0)   ENCODE az64
,SUPPLIER_ID	NUMERIC(15,0)   ENCODE az64
,WEB_PASSWORD	VARCHAR(240)   ENCODE lzo
--,SECURITY_GROUP_ID	NUMERIC(28,10)   ENCODE az64
,GCN_CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,PERSON_PARTY_ID	NUMERIC(28,10)   ENCODE az64
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64  ) 
DISTSTYLE AUTO
;

insert into bec_ods.FND_USER
(
USER_ID
,USER_NAME
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
--,LAST_UPDATE_LOGIN
,ENCRYPTED_FOUNDATION_PASSWORD
,ENCRYPTED_USER_PASSWORD
--,SESSION_NUMBER
,START_DATE
,END_DATE
,DESCRIPTION
--,LAST_LOGON_DATE
,PASSWORD_DATE
,PASSWORD_ACCESSES_LEFT
,PASSWORD_LIFESPAN_ACCESSES
,PASSWORD_LIFESPAN_DAYS
,EMPLOYEE_ID
,EMAIL_ADDRESS
,FAX
,CUSTOMER_ID
,SUPPLIER_ID
,WEB_PASSWORD
--,SECURITY_GROUP_ID
,GCN_CODE_COMBINATION_ID
,PERSON_PARTY_ID
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date
)
(
select
USER_ID
,USER_NAME
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
--,LAST_UPDATE_LOGIN
,ENCRYPTED_FOUNDATION_PASSWORD
,ENCRYPTED_USER_PASSWORD
--,SESSION_NUMBER
,START_DATE
,END_DATE
,DESCRIPTION
--,LAST_LOGON_DATE
,PASSWORD_DATE
,PASSWORD_ACCESSES_LEFT
,PASSWORD_LIFESPAN_ACCESSES
,PASSWORD_LIFESPAN_DAYS
,EMPLOYEE_ID
,EMAIL_ADDRESS
,FAX
,CUSTOMER_ID
,SUPPLIER_ID
,WEB_PASSWORD
--,SECURITY_GROUP_ID
,GCN_CODE_COMBINATION_ID
,PERSON_PARTY_ID
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
from bec_ods_stg.FND_USER);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='fnd_user';

commit;