/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

drop table if exists bec_ods.GL_CODE_COMBINATIONS;

CREATE TABLE IF NOT EXISTS bec_ods.GL_CODE_COMBINATIONS
(
CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CHART_OF_ACCOUNTS_ID	NUMERIC(15,0)   ENCODE az64
,DETAIL_POSTING_ALLOWED_FLAG	VARCHAR(1)   ENCODE lzo
,DETAIL_BUDGETING_ALLOWED_FLAG	VARCHAR(1)   ENCODE lzo
,ACCOUNT_TYPE	VARCHAR(1)   ENCODE lzo
,ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,SUMMARY_FLAG	VARCHAR(1)   ENCODE lzo
,SEGMENT1	VARCHAR(25)   ENCODE lzo
,SEGMENT2	VARCHAR(25)   ENCODE lzo
,SEGMENT3	VARCHAR(25)   ENCODE lzo
,SEGMENT4	VARCHAR(25)   ENCODE lzo
,SEGMENT5	VARCHAR(25)   ENCODE lzo
,SEGMENT6	VARCHAR(25)   ENCODE lzo
,SEGMENT7	VARCHAR(25)   ENCODE lzo
,SEGMENT8	VARCHAR(25)   ENCODE lzo
,SEGMENT9	VARCHAR(25)   ENCODE lzo
,SEGMENT10	VARCHAR(25)   ENCODE lzo
,SEGMENT11	VARCHAR(25)   ENCODE lzo
,SEGMENT12	VARCHAR(25)   ENCODE lzo
,SEGMENT13	VARCHAR(25)   ENCODE lzo
,SEGMENT14	VARCHAR(25)   ENCODE lzo
,SEGMENT15	VARCHAR(25)   ENCODE lzo
,SEGMENT16	VARCHAR(25)   ENCODE lzo
,SEGMENT17	VARCHAR(25)   ENCODE lzo
,SEGMENT18	VARCHAR(25)   ENCODE lzo
,SEGMENT19	VARCHAR(25)   ENCODE lzo
,SEGMENT20	VARCHAR(25)   ENCODE lzo
,SEGMENT21	VARCHAR(25)   ENCODE lzo
,SEGMENT22	VARCHAR(25)   ENCODE lzo
,SEGMENT23	VARCHAR(25)   ENCODE lzo
,SEGMENT24	VARCHAR(25)   ENCODE lzo
,SEGMENT25	VARCHAR(25)   ENCODE lzo
,SEGMENT26	VARCHAR(25)   ENCODE lzo
,SEGMENT27	VARCHAR(25)   ENCODE lzo
,SEGMENT28	VARCHAR(25)   ENCODE lzo
,SEGMENT29	VARCHAR(25)   ENCODE lzo
,SEGMENT30	VARCHAR(25)   ENCODE lzo
,DESCRIPTION	VARCHAR(240)   ENCODE lzo
,TEMPLATE_ID	NUMERIC(15,0)   ENCODE az64
,ALLOCATION_CREATE_FLAG	VARCHAR(1)   ENCODE lzo
,START_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,END_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,CONTEXT	VARCHAR(150)   ENCODE lzo
,SEGMENT_ATTRIBUTE1	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE2	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE3	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE4	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE5	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE6	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE7	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE8	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE9	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE10	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE11	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE12	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE13	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE14	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE15	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE16	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE17	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE18	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE19	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE20	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE21	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE22	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE23	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE24	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE25	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE26	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE27	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE28	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE29	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE30	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE31	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE32	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE33	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE34	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE35	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE36	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE37	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE38	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE39	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE40	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE41	VARCHAR(60)   ENCODE lzo
,SEGMENT_ATTRIBUTE42	VARCHAR(60)   ENCODE lzo
,JGZZ_RECON_FLAG	VARCHAR(1)   ENCODE lzo
,JGZZ_RECON_CONTEXT	VARCHAR(30)   ENCODE lzo
,REFERENCE1	VARCHAR(1)   ENCODE lzo
,REFERENCE2	VARCHAR(1)   ENCODE lzo
,REFERENCE3	VARCHAR(25)   ENCODE lzo
,REFERENCE4	VARCHAR(1)   ENCODE lzo
,REFERENCE5	VARCHAR(1)   ENCODE lzo
,PRESERVE_FLAG	VARCHAR(1)   ENCODE lzo
,REFRESH_FLAG	VARCHAR(1)   ENCODE lzo
,IGI_BALANCED_BUDGET_FLAG	VARCHAR(1)   ENCODE lzo
,COMPANY_COST_CENTER_ORG_ID	NUMERIC(15,0)   ENCODE az64
,REVALUATION_ID	NUMERIC(15,0)   ENCODE az64
,LEDGER_SEGMENT	VARCHAR(20)   ENCODE lzo
,LEDGER_TYPE_CODE	VARCHAR(1)   ENCODE lzo
,ALTERNATE_CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)

DISTSTYLE AUTO
;

insert into bec_ods.GL_CODE_COMBINATIONS
(
CODE_COMBINATION_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CHART_OF_ACCOUNTS_ID
,DETAIL_POSTING_ALLOWED_FLAG
,DETAIL_BUDGETING_ALLOWED_FLAG
,ACCOUNT_TYPE
,ENABLED_FLAG
,SUMMARY_FLAG
,SEGMENT1
,SEGMENT2
,SEGMENT3
,SEGMENT4
,SEGMENT5
,SEGMENT6
,SEGMENT7
,SEGMENT8
,SEGMENT9
,SEGMENT10
,SEGMENT11
,SEGMENT12
,SEGMENT13
,SEGMENT14
,SEGMENT15
,SEGMENT16
,SEGMENT17
,SEGMENT18
,SEGMENT19
,SEGMENT20
,SEGMENT21
,SEGMENT22
,SEGMENT23
,SEGMENT24
,SEGMENT25
,SEGMENT26
,SEGMENT27
,SEGMENT28
,SEGMENT29
,SEGMENT30
,DESCRIPTION
,TEMPLATE_ID
,ALLOCATION_CREATE_FLAG
,START_DATE_ACTIVE
,END_DATE_ACTIVE
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,CONTEXT
,SEGMENT_ATTRIBUTE1
,SEGMENT_ATTRIBUTE2
,SEGMENT_ATTRIBUTE3
,SEGMENT_ATTRIBUTE4
,SEGMENT_ATTRIBUTE5
,SEGMENT_ATTRIBUTE6
,SEGMENT_ATTRIBUTE7
,SEGMENT_ATTRIBUTE8
,SEGMENT_ATTRIBUTE9
,SEGMENT_ATTRIBUTE10
,SEGMENT_ATTRIBUTE11
,SEGMENT_ATTRIBUTE12
,SEGMENT_ATTRIBUTE13
,SEGMENT_ATTRIBUTE14
,SEGMENT_ATTRIBUTE15
,SEGMENT_ATTRIBUTE16
,SEGMENT_ATTRIBUTE17
,SEGMENT_ATTRIBUTE18
,SEGMENT_ATTRIBUTE19
,SEGMENT_ATTRIBUTE20
,SEGMENT_ATTRIBUTE21
,SEGMENT_ATTRIBUTE22
,SEGMENT_ATTRIBUTE23
,SEGMENT_ATTRIBUTE24
,SEGMENT_ATTRIBUTE25
,SEGMENT_ATTRIBUTE26
,SEGMENT_ATTRIBUTE27
,SEGMENT_ATTRIBUTE28
,SEGMENT_ATTRIBUTE29
,SEGMENT_ATTRIBUTE30
,SEGMENT_ATTRIBUTE31
,SEGMENT_ATTRIBUTE32
,SEGMENT_ATTRIBUTE33
,SEGMENT_ATTRIBUTE34
,SEGMENT_ATTRIBUTE35
,SEGMENT_ATTRIBUTE36
,SEGMENT_ATTRIBUTE37
,SEGMENT_ATTRIBUTE38
,SEGMENT_ATTRIBUTE39
,SEGMENT_ATTRIBUTE40
,SEGMENT_ATTRIBUTE41
,SEGMENT_ATTRIBUTE42
,JGZZ_RECON_FLAG
,JGZZ_RECON_CONTEXT
,REFERENCE1
,REFERENCE2
,REFERENCE3
,REFERENCE4
,REFERENCE5
,PRESERVE_FLAG
,REFRESH_FLAG
,IGI_BALANCED_BUDGET_FLAG
,COMPANY_COST_CENTER_ORG_ID
,REVALUATION_ID
,LEDGER_SEGMENT
,LEDGER_TYPE_CODE
,ALTERNATE_CODE_COMBINATION_ID
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
kca_seq_date
)
(
select
CODE_COMBINATION_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CHART_OF_ACCOUNTS_ID
,DETAIL_POSTING_ALLOWED_FLAG
,DETAIL_BUDGETING_ALLOWED_FLAG
,ACCOUNT_TYPE
,ENABLED_FLAG
,SUMMARY_FLAG
,SEGMENT1
,SEGMENT2
,SEGMENT3
,SEGMENT4
,SEGMENT5
,SEGMENT6
,SEGMENT7
,SEGMENT8
,SEGMENT9
,SEGMENT10
,SEGMENT11
,SEGMENT12
,SEGMENT13
,SEGMENT14
,SEGMENT15
,SEGMENT16
,SEGMENT17
,SEGMENT18
,SEGMENT19
,SEGMENT20
,SEGMENT21
,SEGMENT22
,SEGMENT23
,SEGMENT24
,SEGMENT25
,SEGMENT26
,SEGMENT27
,SEGMENT28
,SEGMENT29
,SEGMENT30
,DESCRIPTION
,TEMPLATE_ID
,ALLOCATION_CREATE_FLAG
,START_DATE_ACTIVE
,END_DATE_ACTIVE
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,CONTEXT
,SEGMENT_ATTRIBUTE1
,SEGMENT_ATTRIBUTE2
,SEGMENT_ATTRIBUTE3
,SEGMENT_ATTRIBUTE4
,SEGMENT_ATTRIBUTE5
,SEGMENT_ATTRIBUTE6
,SEGMENT_ATTRIBUTE7
,SEGMENT_ATTRIBUTE8
,SEGMENT_ATTRIBUTE9
,SEGMENT_ATTRIBUTE10
,SEGMENT_ATTRIBUTE11
,SEGMENT_ATTRIBUTE12
,SEGMENT_ATTRIBUTE13
,SEGMENT_ATTRIBUTE14
,SEGMENT_ATTRIBUTE15
,SEGMENT_ATTRIBUTE16
,SEGMENT_ATTRIBUTE17
,SEGMENT_ATTRIBUTE18
,SEGMENT_ATTRIBUTE19
,SEGMENT_ATTRIBUTE20
,SEGMENT_ATTRIBUTE21
,SEGMENT_ATTRIBUTE22
,SEGMENT_ATTRIBUTE23
,SEGMENT_ATTRIBUTE24
,SEGMENT_ATTRIBUTE25
,SEGMENT_ATTRIBUTE26
,SEGMENT_ATTRIBUTE27
,SEGMENT_ATTRIBUTE28
,SEGMENT_ATTRIBUTE29
,SEGMENT_ATTRIBUTE30
,SEGMENT_ATTRIBUTE31
,SEGMENT_ATTRIBUTE32
,SEGMENT_ATTRIBUTE33
,SEGMENT_ATTRIBUTE34
,SEGMENT_ATTRIBUTE35
,SEGMENT_ATTRIBUTE36
,SEGMENT_ATTRIBUTE37
,SEGMENT_ATTRIBUTE38
,SEGMENT_ATTRIBUTE39
,SEGMENT_ATTRIBUTE40
,SEGMENT_ATTRIBUTE41
,SEGMENT_ATTRIBUTE42
,JGZZ_RECON_FLAG
,JGZZ_RECON_CONTEXT
,REFERENCE1
,REFERENCE2
,REFERENCE3
,REFERENCE4
,REFERENCE5
,PRESERVE_FLAG
,REFRESH_FLAG
,IGI_BALANCED_BUDGET_FLAG
,COMPANY_COST_CENTER_ORG_ID
,REVALUATION_ID
,LEDGER_SEGMENT
,LEDGER_TYPE_CODE
,ALTERNATE_CODE_COMBINATION_ID
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
from 
 bec_ods_stg.GL_CODE_COMBINATIONS);
 
end;
 
update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='gl_code_combinations'; 

commit;