/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.gl_je_categories_tl;

CREATE TABLE IF NOT EXISTS bec_ods.gl_je_categories_tl
(
	JE_CATEGORY_NAME VARCHAR(25)   ENCODE lzo
	,LANGUAGE VARCHAR(4)   ENCODE lzo
	,SOURCE_LANG VARCHAR(4)   ENCODE lzo
	,USER_JE_CATEGORY_NAME VARCHAR(25)   ENCODE lzo
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64	
	,LAST_UPDATED_BY NUMERIC(15,0)   ENCODE az64
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,CREATED_BY NUMERIC(15,0)   ENCODE az64
	,LAST_UPDATE_LOGIN NUMERIC(15,0)   ENCODE az64
	,DESCRIPTION VARCHAR(240)   ENCODE lzo
	,ATTRIBUTE1 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE2 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE3 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE4 VARCHAR(150)   ENCODE LZO
	,ATTRIBUTE5 VARCHAR(150)   ENCODE LZO
	,CONTEXT VARCHAR(150)   ENCODE LZO
	,CONSOLIDATION_FLAG VARCHAR(1)   ENCODE lzo
	,JE_CATEGORY_KEY VARCHAR(25)   ENCODE lzo
	,ZD_EDITION_NAME VARCHAR(30)   ENCODE lzo
	,ZD_SYNC VARCHAR(30)   ENCODE lzo
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64  ) 
DISTSTYLE
auto;

INSERT INTO bec_ods.gl_je_categories_tl (
	JE_CATEGORY_NAME,
	LANGUAGE,
	SOURCE_LANG,
	USER_JE_CATEGORY_NAME,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	DESCRIPTION,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	CONTEXT,
	CONSOLIDATION_FLAG,
	JE_CATEGORY_KEY,
	ZD_EDITION_NAME,
	ZD_SYNC,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
		JE_CATEGORY_NAME,
		LANGUAGE,
		SOURCE_LANG,
		USER_JE_CATEGORY_NAME,
		LAST_UPDATE_DATE,
		LAST_UPDATED_BY,
		CREATION_DATE,
		CREATED_BY,
		LAST_UPDATE_LOGIN,
		DESCRIPTION,
		ATTRIBUTE1,
		ATTRIBUTE2,
		ATTRIBUTE3,
		ATTRIBUTE4,
		ATTRIBUTE5,
		CONTEXT,
		CONSOLIDATION_FLAG,
		JE_CATEGORY_KEY,
		ZD_EDITION_NAME,
		ZD_SYNC,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
    FROM
        bec_ods_stg.gl_je_categories_tl;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'gl_je_categories_tl';