/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;
drop table if exists bec_ods.GL_JE_HEADERS;

CREATE TABLE IF NOT EXISTS bec_ods.GL_JE_HEADERS
(
JE_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,LEDGER_ID	NUMERIC(15,0)   ENCODE az64
,JE_CATEGORY	VARCHAR(25)   ENCODE lzo
,JE_SOURCE	VARCHAR(25)   ENCODE lzo
,PERIOD_NAME	VARCHAR(15)   ENCODE lzo
,NAME	VARCHAR(100)   ENCODE lzo
,CURRENCY_CODE	VARCHAR(15)   ENCODE lzo
,STATUS	VARCHAR(1)   ENCODE lzo
,DATE_CREATED TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ACCRUAL_REV_FLAG	VARCHAR(1)   ENCODE lzo
,MULTI_BAL_SEG_FLAG	VARCHAR(1)   ENCODE lzo
,ACTUAL_FLAG	VARCHAR(1)   ENCODE lzo
,DEFAULT_EFFECTIVE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CONVERSION_FLAG	VARCHAR(1)   ENCODE lzo
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,ENCUMBRANCE_TYPE_ID	NUMERIC(15,0)   ENCODE az64
,BUDGET_VERSION_ID	NUMERIC(15,0)   ENCODE az64
,BALANCED_JE_FLAG	VARCHAR(1)   ENCODE lzo
,BALANCING_SEGMENT_VALUE	VARCHAR(25)   ENCODE lzo
,JE_BATCH_ID	NUMERIC(15,0)   ENCODE az64
,FROM_RECURRING_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,UNIQUE_DATE	VARCHAR(30)   ENCODE lzo
,EARLIEST_POSTABLE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,POSTED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ACCRUAL_REV_EFFECTIVE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ACCRUAL_REV_PERIOD_NAME	VARCHAR(15)   ENCODE lzo
,ACCRUAL_REV_STATUS	VARCHAR(1)   ENCODE lzo
,ACCRUAL_REV_JE_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,ACCRUAL_REV_CHANGE_SIGN_FLAG	VARCHAR(1)   ENCODE lzo
,DESCRIPTION	VARCHAR(240)   ENCODE lzo
,CONTROL_TOTAL	NUMERIC(28,10)   ENCODE az64
,RUNNING_TOTAL_DR	NUMERIC(28,10)   ENCODE az64
,RUNNING_TOTAL_CR	NUMERIC(28,10)   ENCODE az64
,RUNNING_TOTAL_ACCOUNTED_DR	NUMERIC(28,10)   ENCODE az64
,RUNNING_TOTAL_ACCOUNTED_CR	NUMERIC(28,10)   ENCODE az64
,CURRENCY_CONVERSION_RATE	NUMERIC(28,10)   ENCODE az64
,CURRENCY_CONVERSION_TYPE	VARCHAR(30)   ENCODE lzo
,CURRENCY_CONVERSION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,EXTERNAL_REFERENCE	VARCHAR(80)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,CONTEXT	VARCHAR(150)   ENCODE lzo
,USSGL_TRANSACTION_CODE	VARCHAR(30)   ENCODE lzo
,CONTEXT2	VARCHAR(150)   ENCODE lzo
,DOC_SEQUENCE_ID	NUMERIC(15,0)   ENCODE az64
,DOC_SEQUENCE_VALUE	NUMERIC(28,10)   ENCODE az64
,JGZZ_RECON_CONTEXT	VARCHAR(30)   ENCODE lzo
,JGZZ_RECON_REF	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,GLOBAL_ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,TAX_STATUS_CODE	VARCHAR(1)   ENCODE lzo
,PARENT_JE_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,REVERSED_JE_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,ORIGINATING_BAL_SEG_VALUE	VARCHAR(25)   ENCODE lzo
,INTERCOMPANY_MODE	NUMERIC(15,0)   ENCODE az64
,DR_BAL_SEG_VALUE	VARCHAR(25)   ENCODE lzo
,CR_BAL_SEG_VALUE	VARCHAR(25)   ENCODE lzo
,REFERENCE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LOCAL_DOC_SEQUENCE_ID	NUMERIC(15,0)   ENCODE az64
,LOCAL_DOC_SEQUENCE_VALUE	NUMERIC(28,10)   ENCODE az64
,DISPLAY_ALC_JOURNAL_FLAG	VARCHAR(1)   ENCODE lzo
,JE_FROM_SLA_FLAG	VARCHAR(1)   ENCODE lzo
,POSTING_ACCT_SEQ_VERSION_ID	NUMERIC(15,0)   ENCODE az64
,POSTING_ACCT_SEQ_ASSIGN_ID	NUMERIC(15,0)   ENCODE az64
,POSTING_ACCT_SEQ_VALUE	NUMERIC(28,10)   ENCODE az64
,CLOSE_ACCT_SEQ_VERSION_ID	NUMERIC(15,0)   ENCODE az64
,CLOSE_ACCT_SEQ_ASSIGN_ID	NUMERIC(15,0)   ENCODE az64
,CLOSE_ACCT_SEQ_VALUE	NUMERIC(28,10)   ENCODE az64
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64  ) 
DISTSTYLE AUTO
;

insert into bec_ods.GL_JE_HEADERS
(
JE_HEADER_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LEDGER_ID
,JE_CATEGORY
,JE_SOURCE
,PERIOD_NAME
,NAME
,CURRENCY_CODE
,STATUS
,DATE_CREATED
,ACCRUAL_REV_FLAG
,MULTI_BAL_SEG_FLAG
,ACTUAL_FLAG
,DEFAULT_EFFECTIVE_DATE
,CONVERSION_FLAG
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,ENCUMBRANCE_TYPE_ID
,BUDGET_VERSION_ID
,BALANCED_JE_FLAG
,BALANCING_SEGMENT_VALUE
,JE_BATCH_ID
,FROM_RECURRING_HEADER_ID
,UNIQUE_DATE
,EARLIEST_POSTABLE_DATE
,POSTED_DATE
,ACCRUAL_REV_EFFECTIVE_DATE
,ACCRUAL_REV_PERIOD_NAME
,ACCRUAL_REV_STATUS
,ACCRUAL_REV_JE_HEADER_ID
,ACCRUAL_REV_CHANGE_SIGN_FLAG
,DESCRIPTION
,CONTROL_TOTAL
,RUNNING_TOTAL_DR
,RUNNING_TOTAL_CR
,RUNNING_TOTAL_ACCOUNTED_DR
,RUNNING_TOTAL_ACCOUNTED_CR
,CURRENCY_CONVERSION_RATE
,CURRENCY_CONVERSION_TYPE
,CURRENCY_CONVERSION_DATE
,EXTERNAL_REFERENCE
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,CONTEXT
,USSGL_TRANSACTION_CODE
,CONTEXT2
,DOC_SEQUENCE_ID
,DOC_SEQUENCE_VALUE
,JGZZ_RECON_CONTEXT
,JGZZ_RECON_REF
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,TAX_STATUS_CODE
,PARENT_JE_HEADER_ID
,REVERSED_JE_HEADER_ID
,ORIGINATING_BAL_SEG_VALUE
,INTERCOMPANY_MODE
,DR_BAL_SEG_VALUE
,CR_BAL_SEG_VALUE
,REFERENCE_DATE
,LOCAL_DOC_SEQUENCE_ID
,LOCAL_DOC_SEQUENCE_VALUE
,DISPLAY_ALC_JOURNAL_FLAG
,JE_FROM_SLA_FLAG
,POSTING_ACCT_SEQ_VERSION_ID
,POSTING_ACCT_SEQ_ASSIGN_ID
,POSTING_ACCT_SEQ_VALUE
,CLOSE_ACCT_SEQ_VERSION_ID
,CLOSE_ACCT_SEQ_ASSIGN_ID
,CLOSE_ACCT_SEQ_VALUE
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date
)
(
select
JE_HEADER_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LEDGER_ID
,JE_CATEGORY
,JE_SOURCE
,PERIOD_NAME
,NAME
,CURRENCY_CODE
,STATUS
,DATE_CREATED
,ACCRUAL_REV_FLAG
,MULTI_BAL_SEG_FLAG
,ACTUAL_FLAG
,DEFAULT_EFFECTIVE_DATE
,CONVERSION_FLAG
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,ENCUMBRANCE_TYPE_ID
,BUDGET_VERSION_ID
,BALANCED_JE_FLAG
,BALANCING_SEGMENT_VALUE
,JE_BATCH_ID
,FROM_RECURRING_HEADER_ID
,UNIQUE_DATE
,EARLIEST_POSTABLE_DATE
,POSTED_DATE
,ACCRUAL_REV_EFFECTIVE_DATE
,ACCRUAL_REV_PERIOD_NAME
,ACCRUAL_REV_STATUS
,ACCRUAL_REV_JE_HEADER_ID
,ACCRUAL_REV_CHANGE_SIGN_FLAG
,DESCRIPTION
,CONTROL_TOTAL
,RUNNING_TOTAL_DR
,RUNNING_TOTAL_CR
,RUNNING_TOTAL_ACCOUNTED_DR
,RUNNING_TOTAL_ACCOUNTED_CR
,CURRENCY_CONVERSION_RATE
,CURRENCY_CONVERSION_TYPE
,CURRENCY_CONVERSION_DATE
,EXTERNAL_REFERENCE
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,CONTEXT
,USSGL_TRANSACTION_CODE
,CONTEXT2
,DOC_SEQUENCE_ID
,DOC_SEQUENCE_VALUE
,JGZZ_RECON_CONTEXT
,JGZZ_RECON_REF
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,TAX_STATUS_CODE
,PARENT_JE_HEADER_ID
,REVERSED_JE_HEADER_ID
,ORIGINATING_BAL_SEG_VALUE
,INTERCOMPANY_MODE
,DR_BAL_SEG_VALUE
,CR_BAL_SEG_VALUE
,REFERENCE_DATE
,LOCAL_DOC_SEQUENCE_ID
,LOCAL_DOC_SEQUENCE_VALUE
,DISPLAY_ALC_JOURNAL_FLAG
,JE_FROM_SLA_FLAG
,POSTING_ACCT_SEQ_VERSION_ID
,POSTING_ACCT_SEQ_ASSIGN_ID
,POSTING_ACCT_SEQ_VALUE
,CLOSE_ACCT_SEQ_VERSION_ID
,CLOSE_ACCT_SEQ_ASSIGN_ID
,CLOSE_ACCT_SEQ_VALUE
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
from 
bec_ods_stg.GL_JE_HEADERS
);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='gl_je_headers';

commit;
 
