/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/


begin;
drop table if exists bec_ods.GL_JE_LINES;

CREATE TABLE IF NOT EXISTS bec_ods.GL_JE_LINES
(
JE_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,JE_LINE_NUM	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,LEDGER_ID	NUMERIC(15,0)   ENCODE az64
,CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,PERIOD_NAME	VARCHAR(15)   ENCODE lzo
,EFFECTIVE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,STATUS	VARCHAR(1)   ENCODE lzo
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,ENTERED_DR	NUMERIC(28,10)   ENCODE az64
,ENTERED_CR	NUMERIC(28,10)   ENCODE az64
,ACCOUNTED_DR	NUMERIC(28,10)   ENCODE az64
,ACCOUNTED_CR	NUMERIC(28,10)   ENCODE az64
,DESCRIPTION	VARCHAR(240)   ENCODE lzo
,REFERENCE_1	VARCHAR(240)   ENCODE lzo
,REFERENCE_2	VARCHAR(240)   ENCODE lzo
,REFERENCE_3	VARCHAR(240)   ENCODE lzo
,REFERENCE_4	VARCHAR(240)   ENCODE lzo
,REFERENCE_5	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE16	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE17	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE18	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE19	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE20	VARCHAR(150)   ENCODE lzo
,CONTEXT	VARCHAR(150)   ENCODE lzo
,CONTEXT2	VARCHAR(150)   ENCODE lzo
,INVOICE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,TAX_CODE	VARCHAR(15)   ENCODE lzo
,INVOICE_IDENTIFIER	VARCHAR(20)   ENCODE lzo
,INVOICE_AMOUNT	NUMERIC(28,10)   ENCODE az64
,NO1	VARCHAR(150)   ENCODE lzo
,STAT_AMOUNT	NUMERIC(28,10)   ENCODE az64
,IGNORE_RATE_FLAG	VARCHAR(1)   ENCODE lzo
,CONTEXT3	VARCHAR(150)   ENCODE lzo
,USSGL_TRANSACTION_CODE	VARCHAR(30)   ENCODE lzo
,SUBLEDGER_DOC_SEQUENCE_ID	NUMERIC(15,0)   ENCODE az64
,CONTEXT4	VARCHAR(150)   ENCODE lzo
,SUBLEDGER_DOC_SEQUENCE_VALUE	NUMERIC(28,10)   ENCODE az64
,REFERENCE_6	VARCHAR(240)   ENCODE lzo
,REFERENCE_7	VARCHAR(240)   ENCODE lzo
,REFERENCE_8	VARCHAR(240)   ENCODE lzo
,REFERENCE_9	VARCHAR(240)   ENCODE lzo
,REFERENCE_10	VARCHAR(240)   ENCODE lzo
,JGZZ_RECON_STATUS_11I	VARCHAR(1)   ENCODE lzo
,JGZZ_RECON_DATE_11I TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,JGZZ_RECON_ID_11I	NUMERIC(28,10)   ENCODE az64
,JGZZ_RECON_REF_11I	VARCHAR(240)   ENCODE lzo
,JGZZ_RECON_CONTEXT_11I	VARCHAR(30)   ENCODE lzo
,GLOBAL_ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,GLOBAL_ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,TAXABLE_LINE_FLAG	VARCHAR(1)   ENCODE lzo
,TAX_TYPE_CODE	VARCHAR(1)   ENCODE lzo
,TAX_CODE_ID	NUMERIC(15,0)   ENCODE az64
,TAX_ROUNDING_RULE_CODE	VARCHAR(1)   ENCODE lzo
,AMOUNT_INCLUDES_TAX_FLAG	VARCHAR(1)   ENCODE lzo
,TAX_DOCUMENT_IDENTIFIER	VARCHAR(50)   ENCODE lzo
,TAX_DOCUMENT_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,TAX_CUSTOMER_NAME	VARCHAR(240)   ENCODE lzo
,TAX_CUSTOMER_REFERENCE	VARCHAR(240)   ENCODE lzo
,TAX_REGISTRATION_NUMBER	VARCHAR(50)   ENCODE lzo
,TAX_LINE_FLAG	VARCHAR(1)   ENCODE lzo
,TAX_GROUP_ID	NUMERIC(15,0)   ENCODE az64
,LINE_TYPE_CODE	VARCHAR(20)   ENCODE lzo
,GL_SL_LINK_ID	NUMERIC(15,0)   ENCODE az64
,GL_SL_LINK_TABLE	VARCHAR(30)   ENCODE lzo
,CO_THIRD_PARTY	VARCHAR(14)   ENCODE lzo
,CO_PROCESSED_FLAG	VARCHAR(1)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64  ) 
DISTSTYLE AUTO
;

insert into bec_ods.GL_JE_LINES
(
JE_HEADER_ID
,JE_LINE_NUM
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LEDGER_ID
,CODE_COMBINATION_ID
,PERIOD_NAME
,EFFECTIVE_DATE
,STATUS
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,ENTERED_DR
,ENTERED_CR
,ACCOUNTED_DR
,ACCOUNTED_CR
,DESCRIPTION
,REFERENCE_1
,REFERENCE_2
,REFERENCE_3
,REFERENCE_4
,REFERENCE_5
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,CONTEXT
,CONTEXT2
,INVOICE_DATE
,TAX_CODE
,INVOICE_IDENTIFIER
,INVOICE_AMOUNT
,NO1
,STAT_AMOUNT
,IGNORE_RATE_FLAG
,CONTEXT3
,USSGL_TRANSACTION_CODE
,SUBLEDGER_DOC_SEQUENCE_ID
,CONTEXT4
,SUBLEDGER_DOC_SEQUENCE_VALUE
,REFERENCE_6
,REFERENCE_7
,REFERENCE_8
,REFERENCE_9
,REFERENCE_10
,JGZZ_RECON_STATUS_11I
,JGZZ_RECON_DATE_11I
,JGZZ_RECON_ID_11I
,JGZZ_RECON_REF_11I
,JGZZ_RECON_CONTEXT_11I
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,TAXABLE_LINE_FLAG
,TAX_TYPE_CODE
,TAX_CODE_ID
,TAX_ROUNDING_RULE_CODE
,AMOUNT_INCLUDES_TAX_FLAG
,TAX_DOCUMENT_IDENTIFIER
,TAX_DOCUMENT_DATE
,TAX_CUSTOMER_NAME
,TAX_CUSTOMER_REFERENCE
,TAX_REGISTRATION_NUMBER
,TAX_LINE_FLAG
,TAX_GROUP_ID
,LINE_TYPE_CODE
,GL_SL_LINK_ID
,GL_SL_LINK_TABLE
,CO_THIRD_PARTY
,CO_PROCESSED_FLAG
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date
)
(
select
JE_HEADER_ID
,JE_LINE_NUM
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LEDGER_ID
,CODE_COMBINATION_ID
,PERIOD_NAME
,EFFECTIVE_DATE
,STATUS
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,ENTERED_DR
,ENTERED_CR
,ACCOUNTED_DR
,ACCOUNTED_CR
,DESCRIPTION
,REFERENCE_1
,REFERENCE_2
,REFERENCE_3
,REFERENCE_4
,REFERENCE_5
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,CONTEXT
,CONTEXT2
,INVOICE_DATE
,TAX_CODE
,INVOICE_IDENTIFIER
,INVOICE_AMOUNT
,NO1
,STAT_AMOUNT
,IGNORE_RATE_FLAG
,CONTEXT3
,USSGL_TRANSACTION_CODE
,SUBLEDGER_DOC_SEQUENCE_ID
,CONTEXT4
,SUBLEDGER_DOC_SEQUENCE_VALUE
,REFERENCE_6
,REFERENCE_7
,REFERENCE_8
,REFERENCE_9
,REFERENCE_10
,JGZZ_RECON_STATUS_11I
,JGZZ_RECON_DATE_11I
,JGZZ_RECON_ID_11I
,JGZZ_RECON_REF_11I
,JGZZ_RECON_CONTEXT_11I
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,TAXABLE_LINE_FLAG
,TAX_TYPE_CODE
,TAX_CODE_ID
,TAX_ROUNDING_RULE_CODE
,AMOUNT_INCLUDES_TAX_FLAG
,TAX_DOCUMENT_IDENTIFIER
,TAX_DOCUMENT_DATE
,TAX_CUSTOMER_NAME
,TAX_CUSTOMER_REFERENCE
,TAX_REGISTRATION_NUMBER
,TAX_LINE_FLAG
,TAX_GROUP_ID
,LINE_TYPE_CODE
,GL_SL_LINK_ID
,GL_SL_LINK_TABLE
,CO_THIRD_PARTY
,CO_PROCESSED_FLAG
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
from 
bec_ods_stg.GL_JE_LINES
);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='gl_je_lines';

commit;
 

