/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;
drop table if exists bec_ods.GL_JE_SOURCES_TL;

CREATE TABLE IF NOT EXISTS bec_ods.GL_JE_SOURCES_TL
(
JE_SOURCE_NAME	VARCHAR(25)   ENCODE lzo
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,OVERRIDE_EDITS_FLAG	VARCHAR(1)   ENCODE lzo
,USER_JE_SOURCE_NAME	VARCHAR(25)   ENCODE lzo
,JOURNAL_REFERENCE_FLAG	VARCHAR(1)   ENCODE lzo
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,DESCRIPTION	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,CONTEXT	VARCHAR(150)   ENCODE lzo
,EFFECTIVE_DATE_RULE_CODE	VARCHAR(1)   ENCODE lzo
,JOURNAL_APPROVAL_FLAG	VARCHAR(1)   ENCODE lzo
,LANGUAGE	VARCHAR(4)   ENCODE lzo
,SOURCE_LANG	VARCHAR(4)   ENCODE lzo
,IMPORT_USING_KEY_FLAG	VARCHAR(1)   ENCODE lzo
,JE_SOURCE_KEY	VARCHAR(25)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.GL_JE_SOURCES_TL
(
JE_SOURCE_NAME
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,OVERRIDE_EDITS_FLAG
,USER_JE_SOURCE_NAME
,JOURNAL_REFERENCE_FLAG
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,DESCRIPTION
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,CONTEXT
,EFFECTIVE_DATE_RULE_CODE
,JOURNAL_APPROVAL_FLAG
,LANGUAGE
,SOURCE_LANG
,IMPORT_USING_KEY_FLAG
,JE_SOURCE_KEY
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date)
(
select

JE_SOURCE_NAME
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,OVERRIDE_EDITS_FLAG
,USER_JE_SOURCE_NAME
,JOURNAL_REFERENCE_FLAG
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,DESCRIPTION
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,CONTEXT
,EFFECTIVE_DATE_RULE_CODE
,JOURNAL_APPROVAL_FLAG
,LANGUAGE
,SOURCE_LANG
,IMPORT_USING_KEY_FLAG
,JE_SOURCE_KEY
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
from bec_ods_stg.GL_JE_SOURCES_TL
);

end; 
update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='gl_je_sources_tl';

commit;
 