/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

drop table if exists bec_ods.GL_LEDGERS;

CREATE TABLE IF NOT EXISTS bec_ods.GL_LEDGERS
(
LEDGER_ID	NUMERIC(15,0)   ENCODE az64
,NAME	VARCHAR(30)   ENCODE lzo
,SHORT_NAME	VARCHAR(20)   ENCODE lzo
,DESCRIPTION	VARCHAR(240)   ENCODE lzo
,LEDGER_CATEGORY_CODE	VARCHAR(30)   ENCODE lzo
,ALC_LEDGER_TYPE_CODE	VARCHAR(30)   ENCODE lzo
,OBJECT_TYPE_CODE	VARCHAR(1)   ENCODE lzo
,LE_LEDGER_TYPE_CODE	VARCHAR(1)   ENCODE lzo
,COMPLETION_STATUS_CODE	VARCHAR(30)   ENCODE lzo
,CONFIGURATION_ID	NUMERIC(15,0)   ENCODE az64
,CHART_OF_ACCOUNTS_ID	NUMERIC(15,0)   ENCODE az64
,CURRENCY_CODE	VARCHAR(15)   ENCODE lzo
,PERIOD_SET_NAME	VARCHAR(15)   ENCODE lzo
,ACCOUNTED_PERIOD_TYPE	VARCHAR(15)   ENCODE lzo
,FIRST_LEDGER_PERIOD_NAME	VARCHAR(15)   ENCODE lzo
,RET_EARN_CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,SUSPENSE_ALLOWED_FLAG	VARCHAR(1)   ENCODE lzo
,ALLOW_INTERCOMPANY_POST_FLAG	VARCHAR(1)   ENCODE lzo
,TRACK_ROUNDING_IMBALANCE_FLAG	VARCHAR(1)   ENCODE lzo
,ENABLE_AVERAGE_BALANCES_FLAG	VARCHAR(1)   ENCODE lzo
,CUM_TRANS_CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,RES_ENCUMB_CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,NET_INCOME_CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,ROUNDING_CODE_COMBINATION_ID	NUMERIC(15,0)   ENCODE az64
,ENABLE_BUDGETARY_CONTROL_FLAG	VARCHAR(1)   ENCODE lzo
,REQUIRE_BUDGET_JOURNALS_FLAG	VARCHAR(1)   ENCODE lzo
,ENABLE_JE_APPROVAL_FLAG	VARCHAR(1)   ENCODE lzo
,ENABLE_AUTOMATIC_TAX_FLAG	VARCHAR(1)   ENCODE lzo
,CONSOLIDATION_LEDGER_FLAG	VARCHAR(1)   ENCODE lzo
,TRANSLATE_EOD_FLAG	VARCHAR(1)   ENCODE lzo
,TRANSLATE_QATD_FLAG	VARCHAR(1)   ENCODE lzo
,TRANSLATE_YATD_FLAG	VARCHAR(1)   ENCODE lzo
,TRANSACTION_CALENDAR_ID	NUMERIC(15,0)   ENCODE az64
,DAILY_TRANSLATION_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,AUTOMATICALLY_CREATED_FLAG	VARCHAR(1)   ENCODE lzo
,BAL_SEG_VALUE_OPTION_CODE	VARCHAR(1)   ENCODE lzo
,BAL_SEG_COLUMN_NAME	VARCHAR(25)   ENCODE lzo
,MGT_SEG_VALUE_OPTION_CODE	VARCHAR(1)   ENCODE lzo
,MGT_SEG_COLUMN_NAME	VARCHAR(25)   ENCODE lzo
,BAL_SEG_VALUE_SET_ID	NUMERIC(10,0)   ENCODE az64
,MGT_SEG_VALUE_SET_ID	NUMERIC(10,0)   ENCODE az64
,IMPLICIT_ACCESS_SET_ID	NUMERIC(15,0)   ENCODE az64
,CRITERIA_SET_ID	NUMERIC(15,0)   ENCODE az64
,FUTURE_ENTERABLE_PERIODS_LIMIT	NUMERIC(15,0)   ENCODE az64
,LEDGER_ATTRIBUTES	VARCHAR(2000)   ENCODE lzo
,IMPLICIT_LEDGER_SET_ID	NUMERIC(15,0)   ENCODE az64
,LATEST_OPENED_PERIOD_NAME	VARCHAR(15)   ENCODE lzo
,LATEST_ENCUMBRANCE_YEAR	NUMERIC(15,0)   ENCODE az64
,PERIOD_AVERAGE_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,PERIOD_END_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,BUDGET_PERIOD_AVG_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,BUDGET_PERIOD_END_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,SLA_ACCOUNTING_METHOD_CODE	VARCHAR(30)   ENCODE lzo
,SLA_ACCOUNTING_METHOD_TYPE	VARCHAR(1)   ENCODE lzo
,SLA_DESCRIPTION_LANGUAGE	VARCHAR(15)   ENCODE lzo
,SLA_ENTERED_CUR_BAL_SUS_CCID	NUMERIC(15,0)   ENCODE az64
,SLA_SEQUENCING_FLAG	VARCHAR(1)   ENCODE lzo
,SLA_BAL_BY_LEDGER_CURR_FLAG	VARCHAR(1)   ENCODE lzo
,SLA_LEDGER_CUR_BAL_SUS_CCID	NUMERIC(15,0)   ENCODE az64
,ENABLE_SECONDARY_TRACK_FLAG	VARCHAR(1)   ENCODE lzo
,ENABLE_REVAL_SS_TRACK_FLAG	VARCHAR(1)   ENCODE lzo
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,CONTEXT	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,ENABLE_RECONCILIATION_FLAG	VARCHAR(1)   ENCODE lzo
,CREATE_JE_FLAG	VARCHAR(1)   ENCODE lzo
,SLA_LEDGER_CASH_BASIS_FLAG	VARCHAR(1)   ENCODE lzo
,COMPLETE_FLAG	VARCHAR(1)   ENCODE lzo
,COMMITMENT_BUDGET_FLAG	VARCHAR(1)   ENCODE lzo
,AUTOMATE_SEC_JRNL_REV_FLAG VARCHAR(1) ENCODE lzo
,NET_CLOSING_BAL_FLAG VARCHAR(1) ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.GL_LEDGERS
(
LEDGER_ID
,NAME
,SHORT_NAME
,DESCRIPTION
,LEDGER_CATEGORY_CODE
,ALC_LEDGER_TYPE_CODE
,OBJECT_TYPE_CODE
,LE_LEDGER_TYPE_CODE
,COMPLETION_STATUS_CODE
,CONFIGURATION_ID
,CHART_OF_ACCOUNTS_ID
,CURRENCY_CODE
,PERIOD_SET_NAME
,ACCOUNTED_PERIOD_TYPE
,FIRST_LEDGER_PERIOD_NAME
,RET_EARN_CODE_COMBINATION_ID
,SUSPENSE_ALLOWED_FLAG
,ALLOW_INTERCOMPANY_POST_FLAG
,TRACK_ROUNDING_IMBALANCE_FLAG
,ENABLE_AVERAGE_BALANCES_FLAG
,CUM_TRANS_CODE_COMBINATION_ID
,RES_ENCUMB_CODE_COMBINATION_ID
,NET_INCOME_CODE_COMBINATION_ID
,ROUNDING_CODE_COMBINATION_ID
,ENABLE_BUDGETARY_CONTROL_FLAG
,REQUIRE_BUDGET_JOURNALS_FLAG
,ENABLE_JE_APPROVAL_FLAG
,ENABLE_AUTOMATIC_TAX_FLAG
,CONSOLIDATION_LEDGER_FLAG
,TRANSLATE_EOD_FLAG
,TRANSLATE_QATD_FLAG
,TRANSLATE_YATD_FLAG
,TRANSACTION_CALENDAR_ID
,DAILY_TRANSLATION_RATE_TYPE
,AUTOMATICALLY_CREATED_FLAG
,BAL_SEG_VALUE_OPTION_CODE
,BAL_SEG_COLUMN_NAME
,MGT_SEG_VALUE_OPTION_CODE
,MGT_SEG_COLUMN_NAME
,BAL_SEG_VALUE_SET_ID
,MGT_SEG_VALUE_SET_ID
,IMPLICIT_ACCESS_SET_ID
,CRITERIA_SET_ID
,FUTURE_ENTERABLE_PERIODS_LIMIT
,LEDGER_ATTRIBUTES
,IMPLICIT_LEDGER_SET_ID
,LATEST_OPENED_PERIOD_NAME
,LATEST_ENCUMBRANCE_YEAR
,PERIOD_AVERAGE_RATE_TYPE
,PERIOD_END_RATE_TYPE
,BUDGET_PERIOD_AVG_RATE_TYPE
,BUDGET_PERIOD_END_RATE_TYPE
,SLA_ACCOUNTING_METHOD_CODE
,SLA_ACCOUNTING_METHOD_TYPE
,SLA_DESCRIPTION_LANGUAGE
,SLA_ENTERED_CUR_BAL_SUS_CCID
,SLA_SEQUENCING_FLAG
,SLA_BAL_BY_LEDGER_CURR_FLAG
,SLA_LEDGER_CUR_BAL_SUS_CCID
,ENABLE_SECONDARY_TRACK_FLAG
,ENABLE_REVAL_SS_TRACK_FLAG
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,CONTEXT
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ENABLE_RECONCILIATION_FLAG
,CREATE_JE_FLAG
,SLA_LEDGER_CASH_BASIS_FLAG
,COMPLETE_FLAG
,COMMITMENT_BUDGET_FLAG
,AUTOMATE_SEC_JRNL_REV_FLAG
,NET_CLOSING_BAL_FLAG
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date)
(
select
LEDGER_ID
,NAME
,SHORT_NAME
,DESCRIPTION
,LEDGER_CATEGORY_CODE
,ALC_LEDGER_TYPE_CODE
,OBJECT_TYPE_CODE
,LE_LEDGER_TYPE_CODE
,COMPLETION_STATUS_CODE
,CONFIGURATION_ID
,CHART_OF_ACCOUNTS_ID
,CURRENCY_CODE
,PERIOD_SET_NAME
,ACCOUNTED_PERIOD_TYPE
,FIRST_LEDGER_PERIOD_NAME
,RET_EARN_CODE_COMBINATION_ID
,SUSPENSE_ALLOWED_FLAG
,ALLOW_INTERCOMPANY_POST_FLAG
,TRACK_ROUNDING_IMBALANCE_FLAG
,ENABLE_AVERAGE_BALANCES_FLAG
,CUM_TRANS_CODE_COMBINATION_ID
,RES_ENCUMB_CODE_COMBINATION_ID
,NET_INCOME_CODE_COMBINATION_ID
,ROUNDING_CODE_COMBINATION_ID
,ENABLE_BUDGETARY_CONTROL_FLAG
,REQUIRE_BUDGET_JOURNALS_FLAG
,ENABLE_JE_APPROVAL_FLAG
,ENABLE_AUTOMATIC_TAX_FLAG
,CONSOLIDATION_LEDGER_FLAG
,TRANSLATE_EOD_FLAG
,TRANSLATE_QATD_FLAG
,TRANSLATE_YATD_FLAG
,TRANSACTION_CALENDAR_ID
,DAILY_TRANSLATION_RATE_TYPE
,AUTOMATICALLY_CREATED_FLAG
,BAL_SEG_VALUE_OPTION_CODE
,BAL_SEG_COLUMN_NAME
,MGT_SEG_VALUE_OPTION_CODE
,MGT_SEG_COLUMN_NAME
,BAL_SEG_VALUE_SET_ID
,MGT_SEG_VALUE_SET_ID
,IMPLICIT_ACCESS_SET_ID
,CRITERIA_SET_ID
,FUTURE_ENTERABLE_PERIODS_LIMIT
,LEDGER_ATTRIBUTES
,IMPLICIT_LEDGER_SET_ID
,LATEST_OPENED_PERIOD_NAME
,LATEST_ENCUMBRANCE_YEAR
,PERIOD_AVERAGE_RATE_TYPE
,PERIOD_END_RATE_TYPE
,BUDGET_PERIOD_AVG_RATE_TYPE
,BUDGET_PERIOD_END_RATE_TYPE
,SLA_ACCOUNTING_METHOD_CODE
,SLA_ACCOUNTING_METHOD_TYPE
,SLA_DESCRIPTION_LANGUAGE
,SLA_ENTERED_CUR_BAL_SUS_CCID
,SLA_SEQUENCING_FLAG
,SLA_BAL_BY_LEDGER_CURR_FLAG
,SLA_LEDGER_CUR_BAL_SUS_CCID
,ENABLE_SECONDARY_TRACK_FLAG
,ENABLE_REVAL_SS_TRACK_FLAG
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,CONTEXT
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ENABLE_RECONCILIATION_FLAG
,CREATE_JE_FLAG
,SLA_LEDGER_CASH_BASIS_FLAG
,COMPLETE_FLAG
,COMMITMENT_BUDGET_FLAG
,AUTOMATE_SEC_JRNL_REV_FLAG
,NET_CLOSING_BAL_FLAG
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
from 
bec_ods_stg.GL_LEDGERS
);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='gl_ledgers';

commit;
 