/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;
drop table if exists bec_ods.HR_ALL_ORGANIZATION_UNITS;

CREATE TABLE IF NOT EXISTS bec_ods.HR_ALL_ORGANIZATION_UNITS
(
ORGANIZATION_ID	NUMERIC(15,0)   ENCODE az64
,BUSINESS_GROUP_ID	NUMERIC(15,0)   ENCODE az64
,COST_ALLOCATION_KEYFLEX_ID	NUMERIC(9,0)   ENCODE az64
,LOCATION_ID	NUMERIC(15,0)   ENCODE az64
,SOFT_CODING_KEYFLEX_ID	NUMERIC(15,0)   ENCODE az64
,DATE_FROM TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,NAME	VARCHAR(240)   ENCODE lzo
,DATE_TO TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,INTERNAL_EXTERNAL_FLAG	VARCHAR(30)   ENCODE lzo
,INTERNAL_ADDRESS_LINE	VARCHAR(80)   ENCODE lzo
,TYPE	VARCHAR(30)   ENCODE lzo
,REQUEST_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE16	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE17	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE18	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE19	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE20	VARCHAR(150)   ENCODE lzo
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,OBJECT_VERSION_NUMBER	NUMERIC(9,0)   ENCODE az64
,PARTY_ID	NUMERIC(15,0)   ENCODE az64
,ATTRIBUTE21	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE22	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE23	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE24	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE25	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE26	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE27	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE28	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE29	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE30	VARCHAR(150)   ENCODE lzo
,COMMENTS	VARCHAR(2000)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.HR_ALL_ORGANIZATION_UNITS
(
ORGANIZATION_ID
,BUSINESS_GROUP_ID
,COST_ALLOCATION_KEYFLEX_ID
,LOCATION_ID
,SOFT_CODING_KEYFLEX_ID
,DATE_FROM
,NAME
,DATE_TO
,INTERNAL_EXTERNAL_FLAG
,INTERNAL_ADDRESS_LINE
,TYPE
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,CREATED_BY
,CREATION_DATE
,OBJECT_VERSION_NUMBER
,PARTY_ID
,ATTRIBUTE21
,ATTRIBUTE22
,ATTRIBUTE23
,ATTRIBUTE24
,ATTRIBUTE25
,ATTRIBUTE26
,ATTRIBUTE27
,ATTRIBUTE28
,ATTRIBUTE29
,ATTRIBUTE30
,COMMENTS
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date)
(
select
ORGANIZATION_ID
,BUSINESS_GROUP_ID
,COST_ALLOCATION_KEYFLEX_ID
,LOCATION_ID
,SOFT_CODING_KEYFLEX_ID
,DATE_FROM
,NAME
,DATE_TO
,INTERNAL_EXTERNAL_FLAG
,INTERNAL_ADDRESS_LINE
,TYPE
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,CREATED_BY
,CREATION_DATE
,OBJECT_VERSION_NUMBER
,PARTY_ID
,ATTRIBUTE21
,ATTRIBUTE22
,ATTRIBUTE23
,ATTRIBUTE24
,ATTRIBUTE25
,ATTRIBUTE26
,ATTRIBUTE27
,ATTRIBUTE28
,ATTRIBUTE29
,ATTRIBUTE30
,COMMENTS
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
from bec_ods_stg.HR_ALL_ORGANIZATION_UNITS);
end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='hr_all_organization_units';

commit;
 

