/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;
drop table if exists bec_ods.HR_ORGANIZATION_INFORMATION;

CREATE TABLE IF NOT EXISTS bec_ods.HR_ORGANIZATION_INFORMATION
(
ORG_INFORMATION_ID	NUMERIC(15,0)   ENCODE az64
,ORG_INFORMATION_CONTEXT	VARCHAR(40)   ENCODE lzo
,ORGANIZATION_ID	NUMERIC(15,0)   ENCODE az64
,ORG_INFORMATION1	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION10	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION11	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION12	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION13	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION14	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION15	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION16	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION17	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION18	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION19	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION2	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION20	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION3	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION4	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION5	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION6	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION7	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION8	VARCHAR(150)   ENCODE lzo
,ORG_INFORMATION9	VARCHAR(150)   ENCODE lzo
,REQUEST_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE16	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE17	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE18	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE19	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE20	VARCHAR(150)   ENCODE lzo
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,OBJECT_VERSION_NUMBER	NUMERIC(9,0)   ENCODE az64
,PARTY_ID	NUMERIC(15,0)   ENCODE az64
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.hr_organization_information
(
select
ORG_INFORMATION_ID
,ORG_INFORMATION_CONTEXT
,ORGANIZATION_ID
,ORG_INFORMATION1
,ORG_INFORMATION10
,ORG_INFORMATION11
,ORG_INFORMATION12
,ORG_INFORMATION13
,ORG_INFORMATION14
,ORG_INFORMATION15
,ORG_INFORMATION16
,ORG_INFORMATION17
,ORG_INFORMATION18
,ORG_INFORMATION19
,ORG_INFORMATION2
,ORG_INFORMATION20
,ORG_INFORMATION3
,ORG_INFORMATION4
,ORG_INFORMATION5
,ORG_INFORMATION6
,ORG_INFORMATION7
,ORG_INFORMATION8
,ORG_INFORMATION9
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,CREATED_BY
,CREATION_DATE
,OBJECT_VERSION_NUMBER
,PARTY_ID
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
from 
bec_ods_stg.hr_organization_information
);

end; 

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='hr_organization_information';

commit;
 
