/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS. 
# File Version: KPI v1.0
*/
begin;
drop table if exists bec_ods.HZ_PARTIES;

CREATE TABLE IF NOT EXISTS bec_ods.HZ_PARTIES
(

PARTY_ID	NUMERIC(15,0)   ENCODE az64
,PARTY_NUMBER	VARCHAR(30)   ENCODE lzo
,PARTY_NAME	VARCHAR(360)   ENCODE lzo
,PARTY_TYPE	VARCHAR(30)   ENCODE lzo
,VALIDATED_FLAG	VARCHAR(1)   ENCODE lzo
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,REQUEST_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,WH_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE16	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE17	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE18	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE19	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE20	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE21	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE22	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE23	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE24	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,GLOBAL_ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE16	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE17	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE18	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE19	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE20	VARCHAR(150)   ENCODE lzo
,ORIG_SYSTEM_REFERENCE	VARCHAR(240)   ENCODE lzo
,SIC_CODE	VARCHAR(30)   ENCODE lzo
,HQ_BRANCH_IND	VARCHAR(30)   ENCODE lzo
,CUSTOMER_KEY	VARCHAR(500)   ENCODE lzo
,TAX_REFERENCE	VARCHAR(50)   ENCODE lzo
,JGZZ_FISCAL_CODE	VARCHAR(20)   ENCODE lzo
,DUNS_NUMBER	NUMERIC(15,0)   ENCODE az64
,TAX_NAME	VARCHAR(60)   ENCODE lzo
,PERSON_PRE_NAME_ADJUNCT	VARCHAR(30)   ENCODE lzo
,PERSON_FIRST_NAME	VARCHAR(150)   ENCODE lzo
,PERSON_MIDDLE_NAME	VARCHAR(60)   ENCODE lzo
,PERSON_LAST_NAME	VARCHAR(150)   ENCODE lzo
,PERSON_NAME_SUFFIX	VARCHAR(30)   ENCODE lzo
,PERSON_TITLE VARCHAR(60)   ENCODE lzo
,PERSON_ACADEMIC_TITLE	VARCHAR(30)   ENCODE lzo
,PERSON_PREVIOUS_LAST_NAME	VARCHAR(150)   ENCODE lzo
,KNOWN_AS	VARCHAR(240)   ENCODE lzo
,PERSON_IDEN_TYPE	VARCHAR(30)   ENCODE lzo
,PERSON_IDENTIFIER	VARCHAR(60)   ENCODE lzo
,GROUP_TYPE	VARCHAR(30)   ENCODE lzo
,COUNTRY	VARCHAR(60)   ENCODE lzo
,ADDRESS1	VARCHAR(240)   ENCODE lzo
,ADDRESS2	VARCHAR(240)   ENCODE lzo
,ADDRESS3	VARCHAR(240)   ENCODE lzo
,ADDRESS4	VARCHAR(240)   ENCODE lzo
,CITY	VARCHAR(60)   ENCODE lzo
,POSTAL_CODE	VARCHAR(60)   ENCODE lzo
,STATE	VARCHAR(60)   ENCODE lzo
,PROVINCE	VARCHAR(60)   ENCODE lzo
,STATUS	VARCHAR(1)   ENCODE lzo
,COUNTY	VARCHAR(60)   ENCODE lzo
,SIC_CODE_TYPE	VARCHAR(30)   ENCODE lzo
,TOTAL_NUM_OF_ORDERS	NUMERIC(28,10)   ENCODE az64
,TOTAL_ORDERED_AMOUNT	NUMERIC(28,10)   ENCODE az64
,LAST_ORDERED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,URL	VARCHAR(2000)   ENCODE lzo
,EMAIL_ADDRESS	VARCHAR(2000)   ENCODE lzo
,DO_NOT_MAIL_FLAG	VARCHAR(1)   ENCODE lzo
,ANALYSIS_FY	VARCHAR(5)   ENCODE lzo
,FISCAL_YEAREND_MONTH	VARCHAR(30)   ENCODE lzo
,EMPLOYEES_TOTAL	NUMERIC(28,10)   ENCODE az64
,CURR_FY_POTENTIAL_REVENUE	NUMERIC(28,10)   ENCODE az64
,NEXT_FY_POTENTIAL_REVENUE	NUMERIC(28,10)   ENCODE az64
,YEAR_ESTABLISHED	NUMERIC(4,0)   ENCODE az64
,GSA_INDICATOR_FLAG	VARCHAR(1)   ENCODE lzo
,MISSION_STATEMENT	VARCHAR(2000)   ENCODE lzo
,ORGANIZATION_NAME_PHONETIC	VARCHAR(320)   ENCODE lzo
,PERSON_FIRST_NAME_PHONETIC	VARCHAR(60)   ENCODE lzo
,PERSON_LAST_NAME_PHONETIC	VARCHAR(60)   ENCODE lzo
,LANGUAGE_NAME	VARCHAR(4)   ENCODE lzo
,CATEGORY_CODE	VARCHAR(30)   ENCODE lzo
,REFERENCE_USE_FLAG	VARCHAR(1)   ENCODE lzo
,THIRD_PARTY_FLAG	VARCHAR(1)   ENCODE lzo
,COMPETITOR_FLAG	VARCHAR(1)   ENCODE lzo
,SALUTATION	VARCHAR(60)   ENCODE lzo
,KNOWN_AS2	VARCHAR(240)   ENCODE lzo
,KNOWN_AS3	VARCHAR(240)   ENCODE lzo
,KNOWN_AS4	VARCHAR(240)   ENCODE lzo
,KNOWN_AS5	VARCHAR(240)   ENCODE lzo
,DUNS_NUMBER_C	VARCHAR(30)   ENCODE lzo
,OBJECT_VERSION_NUMBER	NUMERIC(15,0)   ENCODE az64
,CREATED_BY_MODULE	VARCHAR(150)   ENCODE lzo
,APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,CERTIFICATION_LEVEL	VARCHAR(30)   ENCODE lzo
,CERT_REASON_CODE	VARCHAR(30)   ENCODE lzo
,PRIMARY_PHONE_CONTACT_PT_ID	NUMERIC(15,0)   ENCODE az64
,PRIMARY_PHONE_PURPOSE	VARCHAR(30)   ENCODE lzo
,PRIMARY_PHONE_LINE_TYPE	VARCHAR(30)   ENCODE lzo
,PRIMARY_PHONE_COUNTRY_CODE	VARCHAR(10)   ENCODE lzo
,PRIMARY_PHONE_AREA_CODE	VARCHAR(10)   ENCODE lzo
,PRIMARY_PHONE_NUMBER	VARCHAR(40)   ENCODE lzo
,PRIMARY_PHONE_EXTENSION	VARCHAR(20)   ENCODE lzo
,PREFERRED_CONTACT_METHOD	VARCHAR(30)   ENCODE lzo
,HOME_COUNTRY	VARCHAR(2)   ENCODE lzo
,PERSON_BO_VERSION	NUMERIC(15,0)   ENCODE az64
,ORG_BO_VERSION	NUMERIC(15,0)   ENCODE az64
,PERSON_CUST_BO_VERSION	NUMERIC(15,0)   ENCODE az64
,ORG_CUST_BO_VERSION	NUMERIC(15,0)   ENCODE az64
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.HZ_PARTIES
(
select
PARTY_ID
,PARTY_NUMBER
,PARTY_NAME
,PARTY_TYPE
,VALIDATED_FLAG
,LAST_UPDATED_BY
,CREATION_DATE
,LAST_UPDATE_LOGIN
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,CREATED_BY
,LAST_UPDATE_DATE
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,WH_UPDATE_DATE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,ATTRIBUTE21
,ATTRIBUTE22
,ATTRIBUTE23
,ATTRIBUTE24
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE20
,ORIG_SYSTEM_REFERENCE
,SIC_CODE
,HQ_BRANCH_IND
,CUSTOMER_KEY
,TAX_REFERENCE
,JGZZ_FISCAL_CODE
,DUNS_NUMBER
,TAX_NAME
,PERSON_PRE_NAME_ADJUNCT
,PERSON_FIRST_NAME
,PERSON_MIDDLE_NAME
,PERSON_LAST_NAME
,PERSON_NAME_SUFFIX
,PERSON_TITLE
,PERSON_ACADEMIC_TITLE
,PERSON_PREVIOUS_LAST_NAME
,KNOWN_AS
,PERSON_IDEN_TYPE
,PERSON_IDENTIFIER
,GROUP_TYPE
,COUNTRY
,ADDRESS1
,ADDRESS2
,ADDRESS3
,ADDRESS4
,CITY
,POSTAL_CODE
,STATE
,PROVINCE
,STATUS
,COUNTY
,SIC_CODE_TYPE
,TOTAL_NUM_OF_ORDERS
,TOTAL_ORDERED_AMOUNT
,LAST_ORDERED_DATE
,URL
,EMAIL_ADDRESS
,DO_NOT_MAIL_FLAG
,ANALYSIS_FY
,FISCAL_YEAREND_MONTH
,EMPLOYEES_TOTAL
,CURR_FY_POTENTIAL_REVENUE
,NEXT_FY_POTENTIAL_REVENUE
,YEAR_ESTABLISHED
,GSA_INDICATOR_FLAG
,MISSION_STATEMENT
,ORGANIZATION_NAME_PHONETIC
,PERSON_FIRST_NAME_PHONETIC
,PERSON_LAST_NAME_PHONETIC
,LANGUAGE_NAME
,CATEGORY_CODE
,REFERENCE_USE_FLAG
,THIRD_PARTY_FLAG
,COMPETITOR_FLAG
,SALUTATION
,KNOWN_AS2
,KNOWN_AS3
,KNOWN_AS4
,KNOWN_AS5
,DUNS_NUMBER_C
,OBJECT_VERSION_NUMBER
,CREATED_BY_MODULE
,APPLICATION_ID
,CERTIFICATION_LEVEL
,CERT_REASON_CODE
,PRIMARY_PHONE_CONTACT_PT_ID
,PRIMARY_PHONE_PURPOSE
,PRIMARY_PHONE_LINE_TYPE
,PRIMARY_PHONE_COUNTRY_CODE
,PRIMARY_PHONE_AREA_CODE
,PRIMARY_PHONE_NUMBER
,PRIMARY_PHONE_EXTENSION
,PREFERRED_CONTACT_METHOD
,HOME_COUNTRY
,PERSON_BO_VERSION
,ORG_BO_VERSION
,PERSON_CUST_BO_VERSION
,ORG_CUST_BO_VERSION
,KCA_OPERATION
,'N' as IS_DELETED_FLG,
cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date 
from bec_ods_stg.HZ_PARTIES);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='hz_parties';

commit;
 