/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.MSC_SUB_INVENTORIES;

CREATE TABLE IF NOT EXISTS bec_ods.MSC_SUB_INVENTORIES
(
	PLAN_ID NUMERIC(15,0) ENCODE az64 
	,ORGANIZATION_ID NUMERIC(15,0) ENCODE az64 
	,SUB_INVENTORY_CODE VARCHAR(10) ENCODE lzo 
	,NETTING_TYPE NUMERIC(15,0) ENCODE az64 
	,SR_INSTANCE_ID NUMERIC(15,0) ENCODE az64 
	,DESCRIPTION VARCHAR(50) ENCODE lzo 
	,REFRESH_NUMBER NUMERIC(15,0) ENCODE az64 
	,INVENTORY_ATP_CODE NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64 
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,CREATED_BY NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64 
	,REQUEST_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_APPLICATION_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,ATTRIBUTE_CATEGORY VARCHAR(30) ENCODE lzo 
	,ATTRIBUTE1 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE2 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE3 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE4 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE5 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE6 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE7 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE8 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE9 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE10 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE11 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE12 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE13 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE14 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE15 VARCHAR(150) ENCODE lzo 
	,INCLUDE_NON_NETTABLE NUMERIC(15,0) ENCODE az64 
	,SR_RESOURCE_NAME VARCHAR(240) ENCODE lzo 
	,SR_CUSTOMER_ACCT_ID NUMERIC(15,0) ENCODE az64 
	,CONDITION_TYPE VARCHAR(240) ENCODE lzo 
	,kca_operation VARCHAR(10)   ENCODE lzo
    ,is_deleted_flg VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64	
)
DISTSTYLE
auto;

INSERT INTO bec_ods.MSC_SUB_INVENTORIES (
	PLAN_ID
	,ORGANIZATION_ID
	,SUB_INVENTORY_CODE
	,NETTING_TYPE
	,SR_INSTANCE_ID
	,DESCRIPTION
	,REFRESH_NUMBER
	,INVENTORY_ATP_CODE
	,LAST_UPDATE_DATE
	,LAST_UPDATED_BY
	,CREATION_DATE
	,CREATED_BY
	,LAST_UPDATE_LOGIN
	,REQUEST_ID
	,PROGRAM_APPLICATION_ID
	,PROGRAM_ID
	,PROGRAM_UPDATE_DATE
	,ATTRIBUTE_CATEGORY
	,ATTRIBUTE1
	,ATTRIBUTE2
	,ATTRIBUTE3
	,ATTRIBUTE4
	,ATTRIBUTE5
	,ATTRIBUTE6
	,ATTRIBUTE7
	,ATTRIBUTE8
	,ATTRIBUTE9
	,ATTRIBUTE10
	,ATTRIBUTE11
	,ATTRIBUTE12
	,ATTRIBUTE13
	,ATTRIBUTE14
	,ATTRIBUTE15
	,INCLUDE_NON_NETTABLE
	,SR_RESOURCE_NAME
	,SR_CUSTOMER_ACCT_ID
	,CONDITION_TYPE
	,kca_operation
	,is_deleted_flg
	,kca_seq_id
	,kca_seq_date
)
 SELECT
	PLAN_ID
	,ORGANIZATION_ID
	,SUB_INVENTORY_CODE
	,NETTING_TYPE
	,SR_INSTANCE_ID
	,DESCRIPTION
	,REFRESH_NUMBER
	,INVENTORY_ATP_CODE
	,LAST_UPDATE_DATE
	,LAST_UPDATED_BY
	,CREATION_DATE
	,CREATED_BY
	,LAST_UPDATE_LOGIN
	,REQUEST_ID
	,PROGRAM_APPLICATION_ID
	,PROGRAM_ID
	,PROGRAM_UPDATE_DATE
	,ATTRIBUTE_CATEGORY
	,ATTRIBUTE1
	,ATTRIBUTE2
	,ATTRIBUTE3
	,ATTRIBUTE4
	,ATTRIBUTE5
	,ATTRIBUTE6
	,ATTRIBUTE7
	,ATTRIBUTE8
	,ATTRIBUTE9
	,ATTRIBUTE10
	,ATTRIBUTE11
	,ATTRIBUTE12
	,ATTRIBUTE13
	,ATTRIBUTE14
	,ATTRIBUTE15
	,INCLUDE_NON_NETTABLE
	,SR_RESOURCE_NAME
	,SR_CUSTOMER_ACCT_ID
	,CONDITION_TYPE
	,kca_operation
	,'N' as IS_DELETED_FLG
	,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
	,kca_seq_date
    FROM
        bec_ods_stg.MSC_SUB_INVENTORIES;
end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'msc_sub_inventories';

COMMIT;