/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;
drop table if exists bec_ods.MTL_CATEGORY_SETS_B;
CREATE TABLE bec_ods.MTL_CATEGORY_SETS_B
(
CATEGORY_SET_ID    NUMERIC(15,0)   ENCODE az64 
,STRUCTURE_ID    NUMERIC(15,0)   ENCODE az64
,VALIDATE_FLAG    VARCHAR(1)   ENCODE lzo
,CONTROL_LEVEL    NUMERIC(15,0)   ENCODE az64 
,LAST_UPDATE_DATE   TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY    NUMERIC(15,0)   ENCODE az64
,CREATION_DATE    TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY    NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN    NUMERIC(15,0)   ENCODE az64
,REQUEST_ID    NUMERIC(15,0)   ENCODE az64
,PROGRAM_APPLICATION_ID    NUMERIC(15,0)   ENCODE az64
,PROGRAM_ID    NUMERIC(15,0)   ENCODE az64
,PROGRAM_UPDATE_DATE    TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,DEFAULT_CATEGORY_ID    NUMERIC(15,0)   ENCODE az64
,MULT_ITEM_CAT_ASSIGN_FLAG    VARCHAR(1)   ENCODE lzo
,CONTROL_LEVEL_UPDATEABLE_FLAG    VARCHAR(1)   ENCODE lzo
,MULT_ITEM_CAT_UPDATEABLE_FLAG   VARCHAR(1)   ENCODE lzo
,HIERARCHY_ENABLED    VARCHAR(1)   ENCODE lzo
,VALIDATE_FLAG_UPDATEABLE_FLAG   VARCHAR(1)   ENCODE lzo
,USER_CREATION_ALLOWED_FLAG    VARCHAR(1)   ENCODE lzo
,RAISE_ITEM_CAT_ASSIGN_EVENT    VARCHAR(1)   ENCODE lzo
,RAISE_ALT_CAT_HIER_CHG_EVENT    VARCHAR(1)   ENCODE lzo
,RAISE_CATALOG_CAT_CHG_EVENT    VARCHAR(1)   ENCODE lzo
,ZD_EDITION_NAME VARCHAR(30) ENCODE lzo 
,ZD_SYNC VARCHAR(30)  ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;
insert into bec_ods.MTL_CATEGORY_SETS_B
(
CATEGORY_SET_ID     
,STRUCTURE_ID    
,VALIDATE_FLAG    
,CONTROL_LEVEL    
,LAST_UPDATE_DATE   
,LAST_UPDATED_BY    
,CREATION_DATE    
,CREATED_BY    
,LAST_UPDATE_LOGIN    
,REQUEST_ID    
,PROGRAM_APPLICATION_ID   
,PROGRAM_ID    
,PROGRAM_UPDATE_DATE    
,DEFAULT_CATEGORY_ID    
,MULT_ITEM_CAT_ASSIGN_FLAG    
,CONTROL_LEVEL_UPDATEABLE_FLAG    
,MULT_ITEM_CAT_UPDATEABLE_FLAG   
,HIERARCHY_ENABLED    
,VALIDATE_FLAG_UPDATEABLE_FLAG   
,USER_CREATION_ALLOWED_FLAG    
,RAISE_ITEM_CAT_ASSIGN_EVENT    
,RAISE_ALT_CAT_HIER_CHG_EVENT    
,RAISE_CATALOG_CAT_CHG_EVENT
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id,
	kca_seq_date) 
SELECT CATEGORY_SET_ID 
,STRUCTURE_ID    
,VALIDATE_FLAG    
,CONTROL_LEVEL  
,LAST_UPDATE_DATE   
,LAST_UPDATED_BY    
,CREATION_DATE    
,CREATED_BY    
,LAST_UPDATE_LOGIN    
,REQUEST_ID    
,PROGRAM_APPLICATION_ID   
,PROGRAM_ID    
,PROGRAM_UPDATE_DATE    
,DEFAULT_CATEGORY_ID    
,MULT_ITEM_CAT_ASSIGN_FLAG    
,CONTROL_LEVEL_UPDATEABLE_FLAG    
,MULT_ITEM_CAT_UPDATEABLE_FLAG   
,HIERARCHY_ENABLED    
,VALIDATE_FLAG_UPDATEABLE_FLAG   
,USER_CREATION_ALLOWED_FLAG    
,RAISE_ITEM_CAT_ASSIGN_EVENT    
,RAISE_ALT_CAT_HIER_CHG_EVENT    
,RAISE_CATALOG_CAT_CHG_EVENT   
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,'N' AS IS_DELETED_FLG 
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date 
FROM bec_ods_stg.mtl_category_sets_b;

end;

update bec_etl_ctrl.batch_ods_info
set load_type = 'I', last_refresh_date = getdate()
where ods_table_name='mtl_category_sets_b';

commit;
 