/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;
drop table if exists bec_ods.MTL_SYSTEM_ITEMS_B;

CREATE TABLE IF NOT EXISTS bec_ods.MTL_SYSTEM_ITEMS_B
(

INVENTORY_ITEM_ID	NUMERIC(15,0)   ENCODE az64
,ORGANIZATION_ID	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,SUMMARY_FLAG	VARCHAR(1)   ENCODE lzo
,ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,START_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,END_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,DESCRIPTION	VARCHAR(240)   ENCODE lzo
,BUYER_ID	NUMERIC(9,0)   ENCODE az64
,ACCOUNTING_RULE_ID	NUMERIC(15,0)   ENCODE az64
,INVOICING_RULE_ID	NUMERIC(15,0)   ENCODE az64
,SEGMENT1	VARCHAR(40)   ENCODE lzo
,SEGMENT2	VARCHAR(40)   ENCODE lzo
,SEGMENT3	VARCHAR(40)   ENCODE lzo
,SEGMENT4	VARCHAR(40)   ENCODE lzo
,SEGMENT5	VARCHAR(40)   ENCODE lzo
,SEGMENT6	VARCHAR(40)   ENCODE lzo
,SEGMENT7	VARCHAR(40)   ENCODE lzo
,SEGMENT8	VARCHAR(40)   ENCODE lzo
,SEGMENT9	VARCHAR(40)   ENCODE lzo
,SEGMENT10	VARCHAR(40)   ENCODE lzo
,SEGMENT11	VARCHAR(40)   ENCODE lzo
,SEGMENT12	VARCHAR(40)   ENCODE lzo
,SEGMENT13	VARCHAR(40)   ENCODE lzo
,SEGMENT14	VARCHAR(40)   ENCODE lzo
,SEGMENT15	VARCHAR(40)   ENCODE lzo
,SEGMENT16	VARCHAR(40)   ENCODE lzo
,SEGMENT17	VARCHAR(40)   ENCODE lzo
,SEGMENT18	VARCHAR(40)   ENCODE lzo
,SEGMENT19	VARCHAR(40)   ENCODE lzo
,SEGMENT20	VARCHAR(40)   ENCODE lzo
,ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(240)   ENCODE lzo
,PURCHASING_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,SHIPPABLE_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,CUSTOMER_ORDER_FLAG	VARCHAR(1)   ENCODE lzo
,INTERNAL_ORDER_FLAG	VARCHAR(1)   ENCODE lzo
,SERVICE_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,INVENTORY_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,ENG_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,INVENTORY_ASSET_FLAG	VARCHAR(1)   ENCODE lzo
,PURCHASING_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,CUSTOMER_ORDER_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,INTERNAL_ORDER_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,SO_TRANSACTIONS_FLAG	VARCHAR(1)   ENCODE lzo
,MTL_TRANSACTIONS_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,STOCK_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,BOM_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,BUILD_IN_WIP_FLAG	VARCHAR(1)   ENCODE lzo
,REVISION_QTY_CONTROL_CODE	NUMERIC(15,0)   ENCODE az64
,ITEM_CATALOG_GROUP_ID	NUMERIC(15,0)   ENCODE az64
,CATALOG_STATUS_FLAG	VARCHAR(1)   ENCODE lzo
,RETURNABLE_FLAG	VARCHAR(1)   ENCODE lzo
,DEFAULT_SHIPPING_ORG	NUMERIC(15,0)   ENCODE az64
,COLLATERAL_FLAG	VARCHAR(1)   ENCODE lzo
,TAXABLE_FLAG	VARCHAR(1)   ENCODE lzo
,QTY_RCV_EXCEPTION_CODE	VARCHAR(25)   ENCODE lzo
,ALLOW_ITEM_DESC_UPDATE_FLAG	VARCHAR(1)   ENCODE lzo
,INSPECTION_REQUIRED_FLAG	VARCHAR(1)   ENCODE lzo
,RECEIPT_REQUIRED_FLAG	VARCHAR(1)   ENCODE lzo
,MARKET_PRICE	NUMERIC(28,10)   ENCODE az64
,HAZARD_CLASS_ID	NUMERIC(15,0)   ENCODE az64
,RFQ_REQUIRED_FLAG	VARCHAR(1)   ENCODE lzo
,QTY_RCV_TOLERANCE	NUMERIC(28,10)   ENCODE az64
,LIST_PRICE_PER_UNIT	NUMERIC(28,10)   ENCODE az64
,UN_NUMBER_ID	NUMERIC(15,0)   ENCODE az64
,PRICE_TOLERANCE_PERCENT	NUMERIC(28,10)   ENCODE az64
,ASSET_CATEGORY_ID	NUMERIC(15,0)   ENCODE az64
,ROUNDING_FACTOR	NUMERIC(28,10)   ENCODE az64
,UNIT_OF_ISSUE	VARCHAR(25)   ENCODE lzo
,ENFORCE_SHIP_TO_LOCATION_CODE	VARCHAR(25)   ENCODE lzo
,ALLOW_SUBSTITUTE_RECEIPTS_FLAG	VARCHAR(1)   ENCODE lzo
,ALLOW_UNORDERED_RECEIPTS_FLAG	VARCHAR(1)   ENCODE lzo
,ALLOW_EXPRESS_DELIVERY_FLAG	VARCHAR(1)   ENCODE lzo
,DAYS_EARLY_RECEIPT_ALLOWED	NUMERIC(15,0)   ENCODE az64
,DAYS_LATE_RECEIPT_ALLOWED	NUMERIC(15,0)   ENCODE az64
,RECEIPT_DAYS_EXCEPTION_CODE	VARCHAR(25)   ENCODE lzo
,RECEIVING_ROUTING_ID	NUMERIC(15,0)   ENCODE az64
,INVOICE_CLOSE_TOLERANCE	NUMERIC(28,10)   ENCODE az64
,RECEIVE_CLOSE_TOLERANCE	NUMERIC(28,10)   ENCODE az64
,AUTO_LOT_ALPHA_PREFIX	VARCHAR(30)   ENCODE lzo
,START_AUTO_LOT_NUMBER	VARCHAR(30)   ENCODE lzo
,LOT_CONTROL_CODE	NUMERIC(15,0)   ENCODE az64
,SHELF_LIFE_CODE	NUMERIC(15,0)   ENCODE az64
,SHELF_LIFE_DAYS	NUMERIC(15,0)   ENCODE az64
,SERIAL_NUMBER_CONTROL_CODE	NUMERIC(15,0)   ENCODE az64
,START_AUTO_SERIAL_NUMBER	VARCHAR(30)   ENCODE lzo
,AUTO_SERIAL_ALPHA_PREFIX	VARCHAR(30)   ENCODE lzo
,SOURCE_TYPE	NUMERIC(15,0)   ENCODE az64
,SOURCE_ORGANIZATION_ID	NUMERIC(15,0)   ENCODE az64
,SOURCE_SUBINVENTORY	VARCHAR(10)   ENCODE lzo
,EXPENSE_ACCOUNT	NUMERIC(15,0)    ENCODE az64
,ENCUMBRANCE_ACCOUNT	NUMERIC(15,0)    ENCODE az64
,RESTRICT_SUBINVENTORIES_CODE	NUMERIC(15,0)    ENCODE az64
,UNIT_WEIGHT	NUMERIC(28,10)    ENCODE az64
,WEIGHT_UOM_CODE	VARCHAR(3)   ENCODE lzo
,VOLUME_UOM_CODE	VARCHAR(3)   ENCODE lzo
,UNIT_VOLUME	NUMERIC(28,10)    ENCODE az64
,RESTRICT_LOCATORS_CODE	NUMERIC(15,0)    ENCODE az64
,LOCATION_CONTROL_CODE	NUMERIC(15,0)    ENCODE az64
,SHRINKAGE_RATE	NUMERIC(28,10)    ENCODE az64
,ACCEPTABLE_EARLY_DAYS	NUMERIC(28,10)    ENCODE az64
,PLANNING_TIME_FENCE_CODE	NUMERIC(15,0)    ENCODE az64
,DEMAND_TIME_FENCE_CODE	NUMERIC(15,0)    ENCODE az64
,LEAD_TIME_LOT_SIZE	NUMERIC(28,10)    ENCODE az64
,STD_LOT_SIZE	NUMERIC(28,10)    ENCODE az64
,CUM_MANUFACTURING_LEAD_TIME	NUMERIC(28,10)    ENCODE az64
,OVERRUN_PERCENTAGE	NUMERIC(28,10)    ENCODE az64
,MRP_CALCULATE_ATP_FLAG	VARCHAR(1)   ENCODE lzo
,ACCEPTABLE_RATE_INCREASE	NUMERIC(28,10)    ENCODE az64
,ACCEPTABLE_RATE_DECREASE	NUMERIC(28,10)    ENCODE az64
,CUMULATIVE_TOTAL_LEAD_TIME	NUMERIC(28,10)    ENCODE az64
,PLANNING_TIME_FENCE_DAYS	NUMERIC(15,0)    ENCODE az64
,DEMAND_TIME_FENCE_DAYS	NUMERIC(15,0)    ENCODE az64
,END_ASSEMBLY_PEGGING_FLAG	VARCHAR(1)   ENCODE lzo
,REPETITIVE_PLANNING_FLAG	VARCHAR(1)   ENCODE lzo
,PLANNING_EXCEPTION_SET	VARCHAR(10)   ENCODE lzo
,BOM_ITEM_TYPE	NUMERIC(15,0)    ENCODE az64
,PICK_COMPONENTS_FLAG	VARCHAR(1)   ENCODE lzo
,REPLENISH_TO_ORDER_FLAG	VARCHAR(1)   ENCODE lzo
,BASE_ITEM_ID	NUMERIC(15,0)    ENCODE az64
,ATP_COMPONENTS_FLAG	VARCHAR(1)   ENCODE lzo
,ATP_FLAG	VARCHAR(1)   ENCODE lzo
,FIXED_LEAD_TIME	NUMERIC(28,10)    ENCODE az64
,VARIABLE_LEAD_TIME	NUMERIC(28,10)    ENCODE az64
,WIP_SUPPLY_LOCATOR_ID	NUMERIC(15,0)    ENCODE az64
,WIP_SUPPLY_TYPE	NUMERIC(15,0)    ENCODE az64
,WIP_SUPPLY_SUBINVENTORY	VARCHAR(10)   ENCODE lzo
,PRIMARY_UOM_CODE	VARCHAR(3)   ENCODE lzo
,PRIMARY_UNIT_OF_MEASURE	VARCHAR(25)   ENCODE lzo
,ALLOWED_UNITS_LOOKUP_CODE	NUMERIC(15,0)    ENCODE az64
,COST_OF_SALES_ACCOUNT	NUMERIC(28,10)    ENCODE az64
,SALES_ACCOUNT	NUMERIC(15,0)    ENCODE az64
,DEFAULT_INCLUDE_IN_ROLLUP_FLAG	VARCHAR(1)   ENCODE lzo
,INVENTORY_ITEM_STATUS_CODE	VARCHAR(10)   ENCODE lzo
,INVENTORY_PLANNING_CODE	NUMERIC(15,0)    ENCODE az64
,PLANNER_CODE	VARCHAR(10)   ENCODE lzo
,PLANNING_MAKE_BUY_CODE	NUMERIC(15,0)    ENCODE az64
,FIXED_LOT_MULTIPLIER	NUMERIC(28,10)    ENCODE az64
,ROUNDING_CONTROL_TYPE	NUMERIC(28,10)    ENCODE az64
,CARRYING_COST	NUMERIC(28,10)    ENCODE az64
,POSTPROCESSING_LEAD_TIME	NUMERIC(28,10)    ENCODE az64
,PREPROCESSING_LEAD_TIME	NUMERIC(28,10)    ENCODE az64
,FULL_LEAD_TIME	NUMERIC(28,10)    ENCODE az64
,ORDER_COST	NUMERIC(28,10)    ENCODE az64
,MRP_SAFETY_STOCK_PERCENT	NUMERIC(28,10)    ENCODE az64
,MRP_SAFETY_STOCK_CODE	NUMERIC(28,10)    ENCODE az64
,MIN_MINMAX_QUANTITY	NUMERIC(28,10)    ENCODE az64
,MAX_MINMAX_QUANTITY	NUMERIC(28,10)    ENCODE az64
,MINIMUM_ORDER_QUANTITY	NUMERIC(28,10)    ENCODE az64
,FIXED_ORDER_QUANTITY	NUMERIC(28,10)    ENCODE az64
,FIXED_DAYS_SUPPLY	NUMERIC(28,10)    ENCODE az64
,MAXIMUM_ORDER_QUANTITY	NUMERIC(28,10)    ENCODE az64
,ATP_RULE_ID	NUMERIC(15,0)    ENCODE az64
,PICKING_RULE_ID	NUMERIC(15,0)    ENCODE az64
,RESERVABLE_TYPE	NUMERIC(15,0)    ENCODE az64
,POSITIVE_MEASUREMENT_ERROR	NUMERIC(28,10)    ENCODE az64
,NEGATIVE_MEASUREMENT_ERROR	NUMERIC(28,10)    ENCODE az64
,ENGINEERING_ECN_CODE	VARCHAR(50)   ENCODE lzo
,ENGINEERING_ITEM_ID	NUMERIC(15,0)    ENCODE az64
,ENGINEERING_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SERVICE_STARTING_DELAY	NUMERIC(28,10)    ENCODE az64
,VENDOR_WARRANTY_FLAG	VARCHAR(1)   ENCODE lzo
,SERVICEABLE_COMPONENT_FLAG	VARCHAR(1)   ENCODE lzo
,SERVICEABLE_PRODUCT_FLAG	VARCHAR(1)   ENCODE lzo
,BASE_WARRANTY_SERVICE_ID	NUMERIC(15,0)    ENCODE az64
,PAYMENT_TERMS_ID	NUMERIC(15,0)    ENCODE az64
,PREVENTIVE_MAINTENANCE_FLAG	VARCHAR(1)   ENCODE lzo
,PRIMARY_SPECIALIST_ID	NUMERIC(15,0)    ENCODE az64
,SECONDARY_SPECIALIST_ID	NUMERIC(15,0)    ENCODE az64
,SERVICEABLE_ITEM_CLASS_ID	NUMERIC(15,0)    ENCODE az64
,TIME_BILLABLE_FLAG	VARCHAR(1)   ENCODE lzo
,MATERIAL_BILLABLE_FLAG	VARCHAR(30)   ENCODE lzo
,EXPENSE_BILLABLE_FLAG	VARCHAR(1)   ENCODE lzo
,PRORATE_SERVICE_FLAG	VARCHAR(1)   ENCODE lzo
,COVERAGE_SCHEDULE_ID	NUMERIC(15,0)    ENCODE az64
,SERVICE_DURATION_PERIOD_CODE	VARCHAR(10)   ENCODE lzo
,SERVICE_DURATION	NUMERIC(28,10)    ENCODE az64
,WARRANTY_VENDOR_ID	NUMERIC(15,0)    ENCODE az64
,MAX_WARRANTY_AMOUNT	NUMERIC(28,10)    ENCODE az64
,RESPONSE_TIME_PERIOD_CODE	VARCHAR(30)   ENCODE lzo
,RESPONSE_TIME_VALUE	NUMERIC(28,10)    ENCODE az64
,NEW_REVISION_CODE	VARCHAR(30)   ENCODE lzo
,INVOICEABLE_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,TAX_CODE	VARCHAR(50)   ENCODE lzo
,INVOICE_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,MUST_USE_APPROVED_VENDOR_FLAG	VARCHAR(1)   ENCODE lzo
,REQUEST_ID	NUMERIC(15,0)    ENCODE az64
,PROGRAM_APPLICATION_ID	NUMERIC(15,0)    ENCODE az64
,PROGRAM_ID	NUMERIC(15,0)    ENCODE az64
,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,OUTSIDE_OPERATION_FLAG	VARCHAR(1)   ENCODE lzo
,OUTSIDE_OPERATION_UOM_TYPE	VARCHAR(25)   ENCODE lzo
,SAFETY_STOCK_BUCKET_DAYS	NUMERIC(15,0)    ENCODE az64
,AUTO_REDUCE_MPS	NUMERIC(22,0)    ENCODE az64
,COSTING_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,AUTO_CREATED_CONFIG_FLAG	VARCHAR(1)   ENCODE lzo
,CYCLE_COUNT_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,ITEM_TYPE	VARCHAR(30)   ENCODE lzo
,MODEL_CONFIG_CLAUSE_NAME	VARCHAR(10)   ENCODE lzo
,SHIP_MODEL_COMPLETE_FLAG	VARCHAR(1)   ENCODE lzo
,MRP_PLANNING_CODE	NUMERIC(15,0)    ENCODE az64
,RETURN_INSPECTION_REQUIREMENT	NUMERIC(15,0)    ENCODE az64
,ATO_FORECAST_CONTROL	NUMERIC(15,0)    ENCODE az64
,RELEASE_TIME_FENCE_CODE	NUMERIC(15,0)    ENCODE az64
,RELEASE_TIME_FENCE_DAYS	NUMERIC(15,0)    ENCODE az64
,CONTAINER_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,VEHICLE_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,MAXIMUM_LOAD_WEIGHT	NUMERIC(28,10)    ENCODE az64
,MINIMUM_FILL_PERCENT	NUMERIC(28,10)    ENCODE az64
,CONTAINER_TYPE_CODE	VARCHAR(30)   ENCODE lzo
,INTERNAL_VOLUME	NUMERIC(28,10)    ENCODE az64
,WH_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PRODUCT_FAMILY_ITEM_ID	NUMERIC(15,0)    ENCODE az64
,GLOBAL_ATTRIBUTE_CATEGORY	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,GLOBAL_ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,PURCHASING_TAX_CODE	VARCHAR(50)   ENCODE lzo
,OVERCOMPLETION_TOLERANCE_TYPE	NUMERIC(15,0)    ENCODE az64
,OVERCOMPLETION_TOLERANCE_VALUE	NUMERIC(28,10)    ENCODE az64
,EFFECTIVITY_CONTROL	NUMERIC(15,0)    ENCODE az64
,CHECK_SHORTAGES_FLAG	VARCHAR(1)   ENCODE lzo
,OVER_SHIPMENT_TOLERANCE	NUMERIC(28,10)    ENCODE az64
,UNDER_SHIPMENT_TOLERANCE	NUMERIC(28,10)    ENCODE az64
,OVER_RETURN_TOLERANCE	NUMERIC(28,10)    ENCODE az64
,UNDER_RETURN_TOLERANCE	NUMERIC(28,10)    ENCODE az64
,EQUIPMENT_TYPE	NUMERIC(15,0)    ENCODE az64
,RECOVERED_PART_DISP_CODE	VARCHAR(30)   ENCODE lzo
,DEFECT_TRACKING_ON_FLAG	VARCHAR(1)   ENCODE lzo
,USAGE_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,EVENT_FLAG	VARCHAR(1)   ENCODE lzo
,ELECTRONIC_FLAG	VARCHAR(1)   ENCODE lzo
,DOWNLOADABLE_FLAG	VARCHAR(1)   ENCODE lzo
,VOL_DISCOUNT_EXEMPT_FLAG	VARCHAR(1)   ENCODE lzo
,COUPON_EXEMPT_FLAG	VARCHAR(1)   ENCODE lzo
,COMMS_NL_TRACKABLE_FLAG	VARCHAR(1)   ENCODE lzo
,ASSET_CREATION_CODE	VARCHAR(30)   ENCODE lzo
,COMMS_ACTIVATION_REQD_FLAG	VARCHAR(1)   ENCODE lzo
,ORDERABLE_ON_WEB_FLAG	VARCHAR(1)   ENCODE lzo
,BACK_ORDERABLE_FLAG	VARCHAR(1)   ENCODE lzo
,WEB_STATUS	VARCHAR(30)   ENCODE lzo
,INDIVISIBLE_FLAG	VARCHAR(1)   ENCODE lzo
,DIMENSION_UOM_CODE	VARCHAR(3)   ENCODE lzo
,UNIT_LENGTH	NUMERIC(28,10)    ENCODE az64
,UNIT_WIDTH	NUMERIC(28,10)    ENCODE az64
,UNIT_HEIGHT	NUMERIC(28,10)    ENCODE az64
,BULK_PICKED_FLAG	VARCHAR(1)   ENCODE lzo
,LOT_STATUS_ENABLED	VARCHAR(1)   ENCODE lzo
,DEFAULT_LOT_STATUS_ID	NUMERIC(15,0)    ENCODE az64
,SERIAL_STATUS_ENABLED	VARCHAR(1)   ENCODE lzo
,DEFAULT_SERIAL_STATUS_ID	NUMERIC(15,0)    ENCODE az64
,LOT_SPLIT_ENABLED	VARCHAR(1)   ENCODE lzo
,LOT_MERGE_ENABLED	VARCHAR(1)   ENCODE lzo
,INVENTORY_CARRY_PENALTY	NUMERIC(15,0)    ENCODE az64
,OPERATION_SLACK_PENALTY	NUMERIC(15,0)    ENCODE az64
,FINANCING_ALLOWED_FLAG	VARCHAR(1)   ENCODE lzo
,EAM_ITEM_TYPE	NUMERIC(15,0)    ENCODE az64
,EAM_ACTIVITY_TYPE_CODE	VARCHAR(30)   ENCODE lzo
,EAM_ACTIVITY_CAUSE_CODE	VARCHAR(30)   ENCODE lzo
,EAM_ACT_NOTIFICATION_FLAG	VARCHAR(1)   ENCODE lzo
,EAM_ACT_SHUTDOWN_STATUS	VARCHAR(30)   ENCODE lzo
,DUAL_UOM_CONTROL	NUMERIC(15,0)    ENCODE az64
,SECONDARY_UOM_CODE	VARCHAR(3)   ENCODE lzo
,DUAL_UOM_DEVIATION_HIGH	NUMERIC(28,10)    ENCODE az64
,DUAL_UOM_DEVIATION_LOW	NUMERIC(28,10)    ENCODE az64
,CONTRACT_ITEM_TYPE_CODE	VARCHAR(30)   ENCODE lzo
,SUBSCRIPTION_DEPEND_FLAG	VARCHAR(1)   ENCODE lzo
,SERV_REQ_ENABLED_CODE	VARCHAR(30)   ENCODE lzo
,SERV_BILLING_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,SERV_IMPORTANCE_LEVEL	NUMERIC(15,0)    ENCODE az64
,PLANNED_INV_POINT_FLAG	VARCHAR(1)   ENCODE lzo
,LOT_TRANSLATE_ENABLED	VARCHAR(1)   ENCODE lzo
,DEFAULT_SO_SOURCE_TYPE	VARCHAR(30)   ENCODE lzo
,CREATE_SUPPLY_FLAG	VARCHAR(1)   ENCODE lzo
,SUBSTITUTION_WINDOW_CODE	NUMERIC(15,0)    ENCODE az64
,SUBSTITUTION_WINDOW_DAYS	NUMERIC(15,0)    ENCODE az64
,IB_ITEM_INSTANCE_CLASS	VARCHAR(30)   ENCODE lzo
,CONFIG_MODEL_TYPE	VARCHAR(30)   ENCODE lzo
,LOT_SUBSTITUTION_ENABLED	VARCHAR(1)   ENCODE lzo
,MINIMUM_LICENSE_QUANTITY	NUMERIC(15,0)    ENCODE az64
,EAM_ACTIVITY_SOURCE_CODE	VARCHAR(30)   ENCODE lzo
,LIFECYCLE_ID	NUMERIC(15,0)    ENCODE az64
,CURRENT_PHASE_ID	NUMERIC(15,0)    ENCODE az64
,OBJECT_VERSION_NUMBER	NUMERIC(9,0)    ENCODE az64
,TRACKING_QUANTITY_IND	VARCHAR(30)   ENCODE lzo
,ONT_PRICING_QTY_SOURCE	VARCHAR(30)   ENCODE lzo
,SECONDARY_DEFAULT_IND	VARCHAR(30)   ENCODE lzo
,OPTION_SPECIFIC_SOURCED	NUMERIC(28,10)    ENCODE az64
,APPROVAL_STATUS	VARCHAR(30)   ENCODE lzo
,VMI_MINIMUM_UNITS	NUMERIC(15,0)    ENCODE az64
,VMI_MINIMUM_DAYS	NUMERIC(15,0)    ENCODE az64
,VMI_MAXIMUM_UNITS	NUMERIC(15,0)    ENCODE az64
,VMI_MAXIMUM_DAYS	NUMERIC(15,0)    ENCODE az64
,VMI_FIXED_ORDER_QUANTITY	NUMERIC(15,0)    ENCODE az64
,SO_AUTHORIZATION_FLAG	NUMERIC(15,0)    ENCODE az64
,CONSIGNED_FLAG	NUMERIC(15,0)    ENCODE az64
,ASN_AUTOEXPIRE_FLAG	NUMERIC(15,0)    ENCODE az64
,VMI_FORECAST_TYPE	NUMERIC(15,0)    ENCODE az64
,FORECAST_HORIZON	NUMERIC(15,0)    ENCODE az64
,EXCLUDE_FROM_BUDGET_FLAG	NUMERIC(15,0)    ENCODE az64
,DAYS_TGT_INV_SUPPLY	NUMERIC(15,0)    ENCODE az64
,DAYS_TGT_INV_WINDOW	NUMERIC(15,0)    ENCODE az64
,DAYS_MAX_INV_SUPPLY	NUMERIC(15,0)    ENCODE az64
,DAYS_MAX_INV_WINDOW	NUMERIC(15,0)    ENCODE az64
,DRP_PLANNED_FLAG	NUMERIC(15,0)    ENCODE az64
,CRITICAL_COMPONENT_FLAG	NUMERIC(15,0)    ENCODE az64
,CONTINOUS_TRANSFER	NUMERIC(15,0)    ENCODE az64
,CONVERGENCE	NUMERIC(15,0)    ENCODE az64
,DIVERGENCE	NUMERIC(15,0)    ENCODE az64
,CONFIG_ORGS	VARCHAR(30)   ENCODE lzo
,CONFIG_MATCH	VARCHAR(30)   ENCODE lzo
,ATTRIBUTE16	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE17	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE18	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE19	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE20	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE21	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE22	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE23	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE24	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE25	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE26	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE27	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE28	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE29	VARCHAR(240)   ENCODE lzo
,ATTRIBUTE30	VARCHAR(240)   ENCODE lzo
,CAS_NUMBER	VARCHAR(30)   ENCODE lzo
,CHILD_LOT_FLAG	VARCHAR(1)   ENCODE lzo
,CHILD_LOT_PREFIX	VARCHAR(30)   ENCODE lzo
,CHILD_LOT_STARTING_NUMBER	NUMERIC(15,0)    ENCODE az64
,CHILD_LOT_VALIDATION_FLAG	VARCHAR(1)   ENCODE lzo
,COPY_LOT_ATTRIBUTE_FLAG	VARCHAR(1)   ENCODE lzo
,DEFAULT_GRADE	VARCHAR(150)   ENCODE lzo
,EXPIRATION_ACTION_CODE	VARCHAR(32)   ENCODE lzo
,EXPIRATION_ACTION_INTERVAL	NUMERIC(15,0)    ENCODE az64
,GRADE_CONTROL_FLAG	VARCHAR(1)   ENCODE lzo
,HAZARDOUS_MATERIAL_FLAG	VARCHAR(1)   ENCODE lzo
,HOLD_DAYS	NUMERIC(15,0)    ENCODE az64
,LOT_DIVISIBLE_FLAG	VARCHAR(1)   ENCODE lzo
,MATURITY_DAYS	NUMERIC(15,0)    ENCODE az64
,PARENT_CHILD_GENERATION_FLAG	VARCHAR(1)   ENCODE lzo
,PROCESS_COSTING_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,PROCESS_EXECUTION_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,PROCESS_QUALITY_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,PROCESS_SUPPLY_LOCATOR_ID	NUMERIC(15,0)    ENCODE az64
,PROCESS_SUPPLY_SUBINVENTORY	VARCHAR(10)   ENCODE lzo
,PROCESS_YIELD_LOCATOR_ID	NUMERIC(15,0)    ENCODE az64
,PROCESS_YIELD_SUBINVENTORY	VARCHAR(10)   ENCODE lzo
,RECIPE_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,RETEST_INTERVAL	NUMERIC(15,0)    ENCODE az64
,CHARGE_PERIODICITY_CODE	VARCHAR(3)   ENCODE lzo
,REPAIR_LEADTIME	NUMERIC(15,0)    ENCODE az64
,REPAIR_YIELD	NUMERIC(15,0)    ENCODE az64
,PREPOSITION_POINT	VARCHAR(1)   ENCODE lzo
,REPAIR_PROGRAM	NUMERIC(15,0)    ENCODE az64
,SUBCONTRACTING_COMPONENT	NUMERIC(15,0)    ENCODE az64
,OUTSOURCED_ASSEMBLY	NUMERIC(15,0)    ENCODE az64
,EGO_MASTER_ITEMS_DFF_CTX	VARCHAR(1)   ENCODE lzo
,GDSN_OUTBOUND_ENABLED_FLAG	VARCHAR(1)   ENCODE lzo
,TRADE_ITEM_DESCRIPTOR	VARCHAR(35)   ENCODE lzo
,STYLE_ITEM_ID	NUMERIC(15,0)    ENCODE az64
,STYLE_ITEM_FLAG	VARCHAR(1)   ENCODE lzo
,LAST_SUBMITTED_NIR_ID	NUMERIC(15,0)    ENCODE az64
,DEFAULT_MATERIAL_STATUS_ID	NUMERIC(15,0)    ENCODE az64
,GLOBAL_ATTRIBUTE11	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE12	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE13	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE14	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE15	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE16	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE17	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE18	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE19	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE20	VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE21 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE22 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE23 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE24 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE25 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE26 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE27 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE28 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE29 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE30 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE31 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE32 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE33 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE34 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE35 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE36 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE37 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE38 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE39 VARCHAR(240)   ENCODE lzo
,GLOBAL_ATTRIBUTE40 VARCHAR(240)   ENCODE lzo
,IB_ITEM_TRACKING_LEVEL VARCHAR(30)   ENCODE lzo
,MCC_CLASSIFICATION_TYPE VARCHAR(30)   ENCODE lzo
,MCC_CONTROL_CODE NUMERIC(15,0)   ENCODE az64
,MCC_TRACKING_CODE VARCHAR(30)   ENCODE lzo
,SERIAL_TAGGING_FLAG VARCHAR(1)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.mtl_system_items_b
(
INVENTORY_ITEM_ID
,ORGANIZATION_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,SUMMARY_FLAG
,ENABLED_FLAG
,START_DATE_ACTIVE
,END_DATE_ACTIVE
,DESCRIPTION
,BUYER_ID
,ACCOUNTING_RULE_ID
,INVOICING_RULE_ID
,SEGMENT1
,SEGMENT2
,SEGMENT3
,SEGMENT4
,SEGMENT5
,SEGMENT6
,SEGMENT7
,SEGMENT8
,SEGMENT9
,SEGMENT10
,SEGMENT11
,SEGMENT12
,SEGMENT13
,SEGMENT14
,SEGMENT15
,SEGMENT16
,SEGMENT17
,SEGMENT18
,SEGMENT19
,SEGMENT20
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,PURCHASING_ITEM_FLAG
,SHIPPABLE_ITEM_FLAG
,CUSTOMER_ORDER_FLAG
,INTERNAL_ORDER_FLAG
,SERVICE_ITEM_FLAG
,INVENTORY_ITEM_FLAG
,ENG_ITEM_FLAG
,INVENTORY_ASSET_FLAG
,PURCHASING_ENABLED_FLAG
,CUSTOMER_ORDER_ENABLED_FLAG
,INTERNAL_ORDER_ENABLED_FLAG
,SO_TRANSACTIONS_FLAG
,MTL_TRANSACTIONS_ENABLED_FLAG
,STOCK_ENABLED_FLAG
,BOM_ENABLED_FLAG
,BUILD_IN_WIP_FLAG
,REVISION_QTY_CONTROL_CODE
,ITEM_CATALOG_GROUP_ID
,CATALOG_STATUS_FLAG
,RETURNABLE_FLAG
,DEFAULT_SHIPPING_ORG
,COLLATERAL_FLAG
,TAXABLE_FLAG
,QTY_RCV_EXCEPTION_CODE
,ALLOW_ITEM_DESC_UPDATE_FLAG
,INSPECTION_REQUIRED_FLAG
,RECEIPT_REQUIRED_FLAG
,MARKET_PRICE
,HAZARD_CLASS_ID
,RFQ_REQUIRED_FLAG
,QTY_RCV_TOLERANCE
,LIST_PRICE_PER_UNIT
,UN_NUMBER_ID
,PRICE_TOLERANCE_PERCENT
,ASSET_CATEGORY_ID
,ROUNDING_FACTOR
,UNIT_OF_ISSUE
,ENFORCE_SHIP_TO_LOCATION_CODE
,ALLOW_SUBSTITUTE_RECEIPTS_FLAG
,ALLOW_UNORDERED_RECEIPTS_FLAG
,ALLOW_EXPRESS_DELIVERY_FLAG
,DAYS_EARLY_RECEIPT_ALLOWED
,DAYS_LATE_RECEIPT_ALLOWED
,RECEIPT_DAYS_EXCEPTION_CODE
,RECEIVING_ROUTING_ID
,INVOICE_CLOSE_TOLERANCE
,RECEIVE_CLOSE_TOLERANCE
,AUTO_LOT_ALPHA_PREFIX
,START_AUTO_LOT_NUMBER
,LOT_CONTROL_CODE
,SHELF_LIFE_CODE
,SHELF_LIFE_DAYS
,SERIAL_NUMBER_CONTROL_CODE
,START_AUTO_SERIAL_NUMBER
,AUTO_SERIAL_ALPHA_PREFIX
,SOURCE_TYPE
,SOURCE_ORGANIZATION_ID
,SOURCE_SUBINVENTORY
,EXPENSE_ACCOUNT
,ENCUMBRANCE_ACCOUNT
,RESTRICT_SUBINVENTORIES_CODE
,UNIT_WEIGHT
,WEIGHT_UOM_CODE
,VOLUME_UOM_CODE
,UNIT_VOLUME
,RESTRICT_LOCATORS_CODE
,LOCATION_CONTROL_CODE
,SHRINKAGE_RATE
,ACCEPTABLE_EARLY_DAYS
,PLANNING_TIME_FENCE_CODE
,DEMAND_TIME_FENCE_CODE
,LEAD_TIME_LOT_SIZE
,STD_LOT_SIZE
,CUM_MANUFACTURING_LEAD_TIME
,OVERRUN_PERCENTAGE
,MRP_CALCULATE_ATP_FLAG
,ACCEPTABLE_RATE_INCREASE
,ACCEPTABLE_RATE_DECREASE
,CUMULATIVE_TOTAL_LEAD_TIME
,PLANNING_TIME_FENCE_DAYS
,DEMAND_TIME_FENCE_DAYS
,END_ASSEMBLY_PEGGING_FLAG
,REPETITIVE_PLANNING_FLAG
,PLANNING_EXCEPTION_SET
,BOM_ITEM_TYPE
,PICK_COMPONENTS_FLAG
,REPLENISH_TO_ORDER_FLAG
,BASE_ITEM_ID
,ATP_COMPONENTS_FLAG
,ATP_FLAG
,FIXED_LEAD_TIME
,VARIABLE_LEAD_TIME
,WIP_SUPPLY_LOCATOR_ID
,WIP_SUPPLY_TYPE
,WIP_SUPPLY_SUBINVENTORY
,PRIMARY_UOM_CODE
,PRIMARY_UNIT_OF_MEASURE
,ALLOWED_UNITS_LOOKUP_CODE
,COST_OF_SALES_ACCOUNT
,SALES_ACCOUNT
,DEFAULT_INCLUDE_IN_ROLLUP_FLAG
,INVENTORY_ITEM_STATUS_CODE
,INVENTORY_PLANNING_CODE
,PLANNER_CODE
,PLANNING_MAKE_BUY_CODE
,FIXED_LOT_MULTIPLIER
,ROUNDING_CONTROL_TYPE
,CARRYING_COST
,POSTPROCESSING_LEAD_TIME
,PREPROCESSING_LEAD_TIME
,FULL_LEAD_TIME
,ORDER_COST
,MRP_SAFETY_STOCK_PERCENT
,MRP_SAFETY_STOCK_CODE
,MIN_MINMAX_QUANTITY
,MAX_MINMAX_QUANTITY
,MINIMUM_ORDER_QUANTITY
,FIXED_ORDER_QUANTITY
,FIXED_DAYS_SUPPLY
,MAXIMUM_ORDER_QUANTITY
,ATP_RULE_ID
,PICKING_RULE_ID
,RESERVABLE_TYPE
,POSITIVE_MEASUREMENT_ERROR
,NEGATIVE_MEASUREMENT_ERROR
,ENGINEERING_ECN_CODE
,ENGINEERING_ITEM_ID
,ENGINEERING_DATE
,SERVICE_STARTING_DELAY
,VENDOR_WARRANTY_FLAG
,SERVICEABLE_COMPONENT_FLAG
,SERVICEABLE_PRODUCT_FLAG
,BASE_WARRANTY_SERVICE_ID
,PAYMENT_TERMS_ID
,PREVENTIVE_MAINTENANCE_FLAG
,PRIMARY_SPECIALIST_ID
,SECONDARY_SPECIALIST_ID
,SERVICEABLE_ITEM_CLASS_ID
,TIME_BILLABLE_FLAG
,MATERIAL_BILLABLE_FLAG
,EXPENSE_BILLABLE_FLAG
,PRORATE_SERVICE_FLAG
,COVERAGE_SCHEDULE_ID
,SERVICE_DURATION_PERIOD_CODE
,SERVICE_DURATION
,WARRANTY_VENDOR_ID
,MAX_WARRANTY_AMOUNT
,RESPONSE_TIME_PERIOD_CODE
,RESPONSE_TIME_VALUE
,NEW_REVISION_CODE
,INVOICEABLE_ITEM_FLAG
,TAX_CODE
,INVOICE_ENABLED_FLAG
,MUST_USE_APPROVED_VENDOR_FLAG
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,OUTSIDE_OPERATION_FLAG
,OUTSIDE_OPERATION_UOM_TYPE
,SAFETY_STOCK_BUCKET_DAYS
,AUTO_REDUCE_MPS
,COSTING_ENABLED_FLAG
,AUTO_CREATED_CONFIG_FLAG
,CYCLE_COUNT_ENABLED_FLAG
,ITEM_TYPE
,MODEL_CONFIG_CLAUSE_NAME
,SHIP_MODEL_COMPLETE_FLAG
,MRP_PLANNING_CODE
,RETURN_INSPECTION_REQUIREMENT
,ATO_FORECAST_CONTROL
,RELEASE_TIME_FENCE_CODE
,RELEASE_TIME_FENCE_DAYS
,CONTAINER_ITEM_FLAG
,VEHICLE_ITEM_FLAG
,MAXIMUM_LOAD_WEIGHT
,MINIMUM_FILL_PERCENT
,CONTAINER_TYPE_CODE
,INTERNAL_VOLUME
,WH_UPDATE_DATE
,PRODUCT_FAMILY_ITEM_ID
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,PURCHASING_TAX_CODE
,OVERCOMPLETION_TOLERANCE_TYPE
,OVERCOMPLETION_TOLERANCE_VALUE
,EFFECTIVITY_CONTROL
,CHECK_SHORTAGES_FLAG
,OVER_SHIPMENT_TOLERANCE
,UNDER_SHIPMENT_TOLERANCE
,OVER_RETURN_TOLERANCE
,UNDER_RETURN_TOLERANCE
,EQUIPMENT_TYPE
,RECOVERED_PART_DISP_CODE
,DEFECT_TRACKING_ON_FLAG
,USAGE_ITEM_FLAG
,EVENT_FLAG
,ELECTRONIC_FLAG
,DOWNLOADABLE_FLAG
,VOL_DISCOUNT_EXEMPT_FLAG
,COUPON_EXEMPT_FLAG
,COMMS_NL_TRACKABLE_FLAG
,ASSET_CREATION_CODE
,COMMS_ACTIVATION_REQD_FLAG
,ORDERABLE_ON_WEB_FLAG
,BACK_ORDERABLE_FLAG
,WEB_STATUS
,INDIVISIBLE_FLAG
,DIMENSION_UOM_CODE
,UNIT_LENGTH
,UNIT_WIDTH
,UNIT_HEIGHT
,BULK_PICKED_FLAG
,LOT_STATUS_ENABLED
,DEFAULT_LOT_STATUS_ID
,SERIAL_STATUS_ENABLED
,DEFAULT_SERIAL_STATUS_ID
,LOT_SPLIT_ENABLED
,LOT_MERGE_ENABLED
,INVENTORY_CARRY_PENALTY
,OPERATION_SLACK_PENALTY
,FINANCING_ALLOWED_FLAG
,EAM_ITEM_TYPE
,EAM_ACTIVITY_TYPE_CODE
,EAM_ACTIVITY_CAUSE_CODE
,EAM_ACT_NOTIFICATION_FLAG
,EAM_ACT_SHUTDOWN_STATUS
,DUAL_UOM_CONTROL
,SECONDARY_UOM_CODE
,DUAL_UOM_DEVIATION_HIGH
,DUAL_UOM_DEVIATION_LOW
,CONTRACT_ITEM_TYPE_CODE
,SUBSCRIPTION_DEPEND_FLAG
,SERV_REQ_ENABLED_CODE
,SERV_BILLING_ENABLED_FLAG
,SERV_IMPORTANCE_LEVEL
,PLANNED_INV_POINT_FLAG
,LOT_TRANSLATE_ENABLED
,DEFAULT_SO_SOURCE_TYPE
,CREATE_SUPPLY_FLAG
,SUBSTITUTION_WINDOW_CODE
,SUBSTITUTION_WINDOW_DAYS
,IB_ITEM_INSTANCE_CLASS
,CONFIG_MODEL_TYPE
,LOT_SUBSTITUTION_ENABLED
,MINIMUM_LICENSE_QUANTITY
,EAM_ACTIVITY_SOURCE_CODE
,LIFECYCLE_ID
,CURRENT_PHASE_ID
,OBJECT_VERSION_NUMBER
,TRACKING_QUANTITY_IND
,ONT_PRICING_QTY_SOURCE
,SECONDARY_DEFAULT_IND
,OPTION_SPECIFIC_SOURCED
,APPROVAL_STATUS
,VMI_MINIMUM_UNITS
,VMI_MINIMUM_DAYS
,VMI_MAXIMUM_UNITS
,VMI_MAXIMUM_DAYS
,VMI_FIXED_ORDER_QUANTITY
,SO_AUTHORIZATION_FLAG
,CONSIGNED_FLAG
,ASN_AUTOEXPIRE_FLAG
,VMI_FORECAST_TYPE
,FORECAST_HORIZON
,EXCLUDE_FROM_BUDGET_FLAG
,DAYS_TGT_INV_SUPPLY
,DAYS_TGT_INV_WINDOW
,DAYS_MAX_INV_SUPPLY
,DAYS_MAX_INV_WINDOW
,DRP_PLANNED_FLAG
,CRITICAL_COMPONENT_FLAG
,CONTINOUS_TRANSFER
,CONVERGENCE
,DIVERGENCE
,CONFIG_ORGS
,CONFIG_MATCH
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,ATTRIBUTE21
,ATTRIBUTE22
,ATTRIBUTE23
,ATTRIBUTE24
,ATTRIBUTE25
,ATTRIBUTE26
,ATTRIBUTE27
,ATTRIBUTE28
,ATTRIBUTE29
,ATTRIBUTE30
,CAS_NUMBER
,CHILD_LOT_FLAG
,CHILD_LOT_PREFIX
,CHILD_LOT_STARTING_NUMBER
,CHILD_LOT_VALIDATION_FLAG
,COPY_LOT_ATTRIBUTE_FLAG
,DEFAULT_GRADE
,EXPIRATION_ACTION_CODE
,EXPIRATION_ACTION_INTERVAL
,GRADE_CONTROL_FLAG
,HAZARDOUS_MATERIAL_FLAG
,HOLD_DAYS
,LOT_DIVISIBLE_FLAG
,MATURITY_DAYS
,PARENT_CHILD_GENERATION_FLAG
,PROCESS_COSTING_ENABLED_FLAG
,PROCESS_EXECUTION_ENABLED_FLAG
,PROCESS_QUALITY_ENABLED_FLAG
,PROCESS_SUPPLY_LOCATOR_ID
,PROCESS_SUPPLY_SUBINVENTORY
,PROCESS_YIELD_LOCATOR_ID
,PROCESS_YIELD_SUBINVENTORY
,RECIPE_ENABLED_FLAG
,RETEST_INTERVAL
,CHARGE_PERIODICITY_CODE
,REPAIR_LEADTIME
,REPAIR_YIELD
,PREPOSITION_POINT
,REPAIR_PROGRAM
,SUBCONTRACTING_COMPONENT
,OUTSOURCED_ASSEMBLY
,EGO_MASTER_ITEMS_DFF_CTX
,GDSN_OUTBOUND_ENABLED_FLAG
,TRADE_ITEM_DESCRIPTOR
,STYLE_ITEM_ID
,STYLE_ITEM_FLAG
,LAST_SUBMITTED_NIR_ID
,DEFAULT_MATERIAL_STATUS_ID
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE20
,GLOBAL_ATTRIBUTE21
,GLOBAL_ATTRIBUTE22
,GLOBAL_ATTRIBUTE23
,GLOBAL_ATTRIBUTE24
,GLOBAL_ATTRIBUTE25
,GLOBAL_ATTRIBUTE26
,GLOBAL_ATTRIBUTE27
,GLOBAL_ATTRIBUTE28
,GLOBAL_ATTRIBUTE29
,GLOBAL_ATTRIBUTE30
,GLOBAL_ATTRIBUTE31
,GLOBAL_ATTRIBUTE32
,GLOBAL_ATTRIBUTE33
,GLOBAL_ATTRIBUTE34
,GLOBAL_ATTRIBUTE35
,GLOBAL_ATTRIBUTE36
,GLOBAL_ATTRIBUTE37
,GLOBAL_ATTRIBUTE38
,GLOBAL_ATTRIBUTE39
,GLOBAL_ATTRIBUTE40
,IB_ITEM_TRACKING_LEVEL
,MCC_CLASSIFICATION_TYPE
,MCC_CONTROL_CODE
,MCC_TRACKING_CODE
,SERIAL_TAGGING_FLAG
,KCA_OPERATION
,IS_DELETED_FLG
,kca_seq_id 
,kca_seq_date
)
(
select
INVENTORY_ITEM_ID
,ORGANIZATION_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,SUMMARY_FLAG
,ENABLED_FLAG
,START_DATE_ACTIVE
,END_DATE_ACTIVE
,DESCRIPTION
,BUYER_ID
,ACCOUNTING_RULE_ID
,INVOICING_RULE_ID
,SEGMENT1
,SEGMENT2
,SEGMENT3
,SEGMENT4
,SEGMENT5
,SEGMENT6
,SEGMENT7
,SEGMENT8
,SEGMENT9
,SEGMENT10
,SEGMENT11
,SEGMENT12
,SEGMENT13
,SEGMENT14
,SEGMENT15
,SEGMENT16
,SEGMENT17
,SEGMENT18
,SEGMENT19
,SEGMENT20
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,PURCHASING_ITEM_FLAG
,SHIPPABLE_ITEM_FLAG
,CUSTOMER_ORDER_FLAG
,INTERNAL_ORDER_FLAG
,SERVICE_ITEM_FLAG
,INVENTORY_ITEM_FLAG
,ENG_ITEM_FLAG
,INVENTORY_ASSET_FLAG
,PURCHASING_ENABLED_FLAG
,CUSTOMER_ORDER_ENABLED_FLAG
,INTERNAL_ORDER_ENABLED_FLAG
,SO_TRANSACTIONS_FLAG
,MTL_TRANSACTIONS_ENABLED_FLAG
,STOCK_ENABLED_FLAG
,BOM_ENABLED_FLAG
,BUILD_IN_WIP_FLAG
,REVISION_QTY_CONTROL_CODE
,ITEM_CATALOG_GROUP_ID
,CATALOG_STATUS_FLAG
,RETURNABLE_FLAG
,DEFAULT_SHIPPING_ORG
,COLLATERAL_FLAG
,TAXABLE_FLAG
,QTY_RCV_EXCEPTION_CODE
,ALLOW_ITEM_DESC_UPDATE_FLAG
,INSPECTION_REQUIRED_FLAG
,RECEIPT_REQUIRED_FLAG
,MARKET_PRICE
,HAZARD_CLASS_ID
,RFQ_REQUIRED_FLAG
,QTY_RCV_TOLERANCE
,LIST_PRICE_PER_UNIT
,UN_NUMBER_ID
,PRICE_TOLERANCE_PERCENT
,ASSET_CATEGORY_ID
,ROUNDING_FACTOR
,UNIT_OF_ISSUE
,ENFORCE_SHIP_TO_LOCATION_CODE
,ALLOW_SUBSTITUTE_RECEIPTS_FLAG
,ALLOW_UNORDERED_RECEIPTS_FLAG
,ALLOW_EXPRESS_DELIVERY_FLAG
,DAYS_EARLY_RECEIPT_ALLOWED
,DAYS_LATE_RECEIPT_ALLOWED
,RECEIPT_DAYS_EXCEPTION_CODE
,RECEIVING_ROUTING_ID
,INVOICE_CLOSE_TOLERANCE
,RECEIVE_CLOSE_TOLERANCE
,AUTO_LOT_ALPHA_PREFIX
,START_AUTO_LOT_NUMBER
,LOT_CONTROL_CODE
,SHELF_LIFE_CODE
,SHELF_LIFE_DAYS
,SERIAL_NUMBER_CONTROL_CODE
,START_AUTO_SERIAL_NUMBER
,AUTO_SERIAL_ALPHA_PREFIX
,SOURCE_TYPE
,SOURCE_ORGANIZATION_ID
,SOURCE_SUBINVENTORY
,EXPENSE_ACCOUNT
,ENCUMBRANCE_ACCOUNT
,RESTRICT_SUBINVENTORIES_CODE
,UNIT_WEIGHT
,WEIGHT_UOM_CODE
,VOLUME_UOM_CODE
,UNIT_VOLUME
,RESTRICT_LOCATORS_CODE
,LOCATION_CONTROL_CODE
,SHRINKAGE_RATE
,ACCEPTABLE_EARLY_DAYS
,PLANNING_TIME_FENCE_CODE
,DEMAND_TIME_FENCE_CODE
,LEAD_TIME_LOT_SIZE
,STD_LOT_SIZE
,CUM_MANUFACTURING_LEAD_TIME
,OVERRUN_PERCENTAGE
,MRP_CALCULATE_ATP_FLAG
,ACCEPTABLE_RATE_INCREASE
,ACCEPTABLE_RATE_DECREASE
,CUMULATIVE_TOTAL_LEAD_TIME
,PLANNING_TIME_FENCE_DAYS
,DEMAND_TIME_FENCE_DAYS
,END_ASSEMBLY_PEGGING_FLAG
,REPETITIVE_PLANNING_FLAG
,PLANNING_EXCEPTION_SET
,BOM_ITEM_TYPE
,PICK_COMPONENTS_FLAG
,REPLENISH_TO_ORDER_FLAG
,BASE_ITEM_ID
,ATP_COMPONENTS_FLAG
,ATP_FLAG
,FIXED_LEAD_TIME
,VARIABLE_LEAD_TIME
,WIP_SUPPLY_LOCATOR_ID
,WIP_SUPPLY_TYPE
,WIP_SUPPLY_SUBINVENTORY
,PRIMARY_UOM_CODE
,PRIMARY_UNIT_OF_MEASURE
,ALLOWED_UNITS_LOOKUP_CODE
,COST_OF_SALES_ACCOUNT
,SALES_ACCOUNT
,DEFAULT_INCLUDE_IN_ROLLUP_FLAG
,INVENTORY_ITEM_STATUS_CODE
,INVENTORY_PLANNING_CODE
,PLANNER_CODE
,PLANNING_MAKE_BUY_CODE
,FIXED_LOT_MULTIPLIER
,ROUNDING_CONTROL_TYPE
,CARRYING_COST
,POSTPROCESSING_LEAD_TIME
,PREPROCESSING_LEAD_TIME
,FULL_LEAD_TIME
,ORDER_COST
,MRP_SAFETY_STOCK_PERCENT
,MRP_SAFETY_STOCK_CODE
,MIN_MINMAX_QUANTITY
,MAX_MINMAX_QUANTITY
,MINIMUM_ORDER_QUANTITY
,FIXED_ORDER_QUANTITY
,FIXED_DAYS_SUPPLY
,MAXIMUM_ORDER_QUANTITY
,ATP_RULE_ID
,PICKING_RULE_ID
,RESERVABLE_TYPE
,POSITIVE_MEASUREMENT_ERROR
,NEGATIVE_MEASUREMENT_ERROR
,ENGINEERING_ECN_CODE
,ENGINEERING_ITEM_ID
,ENGINEERING_DATE
,SERVICE_STARTING_DELAY
,VENDOR_WARRANTY_FLAG
,SERVICEABLE_COMPONENT_FLAG
,SERVICEABLE_PRODUCT_FLAG
,BASE_WARRANTY_SERVICE_ID
,PAYMENT_TERMS_ID
,PREVENTIVE_MAINTENANCE_FLAG
,PRIMARY_SPECIALIST_ID
,SECONDARY_SPECIALIST_ID
,SERVICEABLE_ITEM_CLASS_ID
,TIME_BILLABLE_FLAG
,MATERIAL_BILLABLE_FLAG
,EXPENSE_BILLABLE_FLAG
,PRORATE_SERVICE_FLAG
,COVERAGE_SCHEDULE_ID
,SERVICE_DURATION_PERIOD_CODE
,SERVICE_DURATION
,WARRANTY_VENDOR_ID
,MAX_WARRANTY_AMOUNT
,RESPONSE_TIME_PERIOD_CODE
,RESPONSE_TIME_VALUE
,NEW_REVISION_CODE
,INVOICEABLE_ITEM_FLAG
,TAX_CODE
,INVOICE_ENABLED_FLAG
,MUST_USE_APPROVED_VENDOR_FLAG
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,OUTSIDE_OPERATION_FLAG
,OUTSIDE_OPERATION_UOM_TYPE
,SAFETY_STOCK_BUCKET_DAYS
,AUTO_REDUCE_MPS
,COSTING_ENABLED_FLAG
,AUTO_CREATED_CONFIG_FLAG
,CYCLE_COUNT_ENABLED_FLAG
,ITEM_TYPE
,MODEL_CONFIG_CLAUSE_NAME
,SHIP_MODEL_COMPLETE_FLAG
,MRP_PLANNING_CODE
,RETURN_INSPECTION_REQUIREMENT
,ATO_FORECAST_CONTROL
,RELEASE_TIME_FENCE_CODE
,RELEASE_TIME_FENCE_DAYS
,CONTAINER_ITEM_FLAG
,VEHICLE_ITEM_FLAG
,MAXIMUM_LOAD_WEIGHT
,MINIMUM_FILL_PERCENT
,CONTAINER_TYPE_CODE
,INTERNAL_VOLUME
,WH_UPDATE_DATE
,PRODUCT_FAMILY_ITEM_ID
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,PURCHASING_TAX_CODE
,OVERCOMPLETION_TOLERANCE_TYPE
,OVERCOMPLETION_TOLERANCE_VALUE
,EFFECTIVITY_CONTROL
,CHECK_SHORTAGES_FLAG
,OVER_SHIPMENT_TOLERANCE
,UNDER_SHIPMENT_TOLERANCE
,OVER_RETURN_TOLERANCE
,UNDER_RETURN_TOLERANCE
,EQUIPMENT_TYPE
,RECOVERED_PART_DISP_CODE
,DEFECT_TRACKING_ON_FLAG
,USAGE_ITEM_FLAG
,EVENT_FLAG
,ELECTRONIC_FLAG
,DOWNLOADABLE_FLAG
,VOL_DISCOUNT_EXEMPT_FLAG
,COUPON_EXEMPT_FLAG
,COMMS_NL_TRACKABLE_FLAG
,ASSET_CREATION_CODE
,COMMS_ACTIVATION_REQD_FLAG
,ORDERABLE_ON_WEB_FLAG
,BACK_ORDERABLE_FLAG
,WEB_STATUS
,INDIVISIBLE_FLAG
,DIMENSION_UOM_CODE
,UNIT_LENGTH
,UNIT_WIDTH
,UNIT_HEIGHT
,BULK_PICKED_FLAG
,LOT_STATUS_ENABLED
,DEFAULT_LOT_STATUS_ID
,SERIAL_STATUS_ENABLED
,DEFAULT_SERIAL_STATUS_ID
,LOT_SPLIT_ENABLED
,LOT_MERGE_ENABLED
,INVENTORY_CARRY_PENALTY
,OPERATION_SLACK_PENALTY
,FINANCING_ALLOWED_FLAG
,EAM_ITEM_TYPE
,EAM_ACTIVITY_TYPE_CODE
,EAM_ACTIVITY_CAUSE_CODE
,EAM_ACT_NOTIFICATION_FLAG
,EAM_ACT_SHUTDOWN_STATUS
,DUAL_UOM_CONTROL
,SECONDARY_UOM_CODE
,DUAL_UOM_DEVIATION_HIGH
,DUAL_UOM_DEVIATION_LOW
,CONTRACT_ITEM_TYPE_CODE
,SUBSCRIPTION_DEPEND_FLAG
,SERV_REQ_ENABLED_CODE
,SERV_BILLING_ENABLED_FLAG
,SERV_IMPORTANCE_LEVEL
,PLANNED_INV_POINT_FLAG
,LOT_TRANSLATE_ENABLED
,DEFAULT_SO_SOURCE_TYPE
,CREATE_SUPPLY_FLAG
,SUBSTITUTION_WINDOW_CODE
,SUBSTITUTION_WINDOW_DAYS
,IB_ITEM_INSTANCE_CLASS
,CONFIG_MODEL_TYPE
,LOT_SUBSTITUTION_ENABLED
,MINIMUM_LICENSE_QUANTITY
,EAM_ACTIVITY_SOURCE_CODE
,LIFECYCLE_ID
,CURRENT_PHASE_ID
,OBJECT_VERSION_NUMBER
,TRACKING_QUANTITY_IND
,ONT_PRICING_QTY_SOURCE
,SECONDARY_DEFAULT_IND
,OPTION_SPECIFIC_SOURCED
,APPROVAL_STATUS
,VMI_MINIMUM_UNITS
,VMI_MINIMUM_DAYS
,VMI_MAXIMUM_UNITS
,VMI_MAXIMUM_DAYS
,VMI_FIXED_ORDER_QUANTITY
,SO_AUTHORIZATION_FLAG
,CONSIGNED_FLAG
,ASN_AUTOEXPIRE_FLAG
,VMI_FORECAST_TYPE
,FORECAST_HORIZON
,EXCLUDE_FROM_BUDGET_FLAG
,DAYS_TGT_INV_SUPPLY
,DAYS_TGT_INV_WINDOW
,DAYS_MAX_INV_SUPPLY
,DAYS_MAX_INV_WINDOW
,DRP_PLANNED_FLAG
,CRITICAL_COMPONENT_FLAG
,CONTINOUS_TRANSFER
,CONVERGENCE
,DIVERGENCE
,CONFIG_ORGS
,CONFIG_MATCH
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,ATTRIBUTE21
,ATTRIBUTE22
,ATTRIBUTE23
,ATTRIBUTE24
,ATTRIBUTE25
,ATTRIBUTE26
,ATTRIBUTE27
,ATTRIBUTE28
,ATTRIBUTE29
,ATTRIBUTE30
,CAS_NUMBER
,CHILD_LOT_FLAG
,CHILD_LOT_PREFIX
,CHILD_LOT_STARTING_NUMBER
,CHILD_LOT_VALIDATION_FLAG
,COPY_LOT_ATTRIBUTE_FLAG
,DEFAULT_GRADE
,EXPIRATION_ACTION_CODE
,EXPIRATION_ACTION_INTERVAL
,GRADE_CONTROL_FLAG
,HAZARDOUS_MATERIAL_FLAG
,HOLD_DAYS
,LOT_DIVISIBLE_FLAG
,MATURITY_DAYS
,PARENT_CHILD_GENERATION_FLAG
,PROCESS_COSTING_ENABLED_FLAG
,PROCESS_EXECUTION_ENABLED_FLAG
,PROCESS_QUALITY_ENABLED_FLAG
,PROCESS_SUPPLY_LOCATOR_ID
,PROCESS_SUPPLY_SUBINVENTORY
,PROCESS_YIELD_LOCATOR_ID
,PROCESS_YIELD_SUBINVENTORY
,RECIPE_ENABLED_FLAG
,RETEST_INTERVAL
,CHARGE_PERIODICITY_CODE
,REPAIR_LEADTIME
,REPAIR_YIELD
,PREPOSITION_POINT
,REPAIR_PROGRAM
,SUBCONTRACTING_COMPONENT
,OUTSOURCED_ASSEMBLY
,EGO_MASTER_ITEMS_DFF_CTX
,GDSN_OUTBOUND_ENABLED_FLAG
,TRADE_ITEM_DESCRIPTOR
,STYLE_ITEM_ID
,STYLE_ITEM_FLAG
,LAST_SUBMITTED_NIR_ID
,DEFAULT_MATERIAL_STATUS_ID
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE20
,GLOBAL_ATTRIBUTE21
,GLOBAL_ATTRIBUTE22
,GLOBAL_ATTRIBUTE23
,GLOBAL_ATTRIBUTE24
,GLOBAL_ATTRIBUTE25
,GLOBAL_ATTRIBUTE26
,GLOBAL_ATTRIBUTE27
,GLOBAL_ATTRIBUTE28
,GLOBAL_ATTRIBUTE29
,GLOBAL_ATTRIBUTE30
,GLOBAL_ATTRIBUTE31
,GLOBAL_ATTRIBUTE32
,GLOBAL_ATTRIBUTE33
,GLOBAL_ATTRIBUTE34
,GLOBAL_ATTRIBUTE35
,GLOBAL_ATTRIBUTE36
,GLOBAL_ATTRIBUTE37
,GLOBAL_ATTRIBUTE38
,GLOBAL_ATTRIBUTE39
,GLOBAL_ATTRIBUTE40
,IB_ITEM_TRACKING_LEVEL
,MCC_CLASSIFICATION_TYPE
,MCC_CONTROL_CODE
,MCC_TRACKING_CODE
,SERIAL_TAGGING_FLAG
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date  
from bec_ods_stg.mtl_system_items_b);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='mtl_system_items_b'; 

commit;


