/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.mtl_consumption_transactions;

CREATE TABLE IF NOT EXISTS bec_ods.mtl_consumption_transactions
(
	TRANSACTION_ID NUMERIC(15,0)   ENCODE az64
	,CONSUMPTION_RELEASE_ID NUMERIC(15,0)  ENCODE az64
	,CONSUMPTION_PO_HEADER_ID NUMERIC(15,0)  ENCODE az64
	,CONSUMPTION_PROCESSED_FLAG VARCHAR(1)   ENCODE lzo
	,REQUEST_ID NUMERIC(15,0)   ENCODE az64
	,CREATED_BY NUMERIC(15,0)   ENCODE az64
	,PROGRAM_APPLICATION_ID NUMERIC(15,0)   ENCODE az64
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,PROGRAM_ID NUMERIC(15,0)   ENCODE az64
	,LAST_UPDATED_BY NUMERIC(15,0)   ENCODE az64
	,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,LAST_UPDATE_LOGIN NUMERIC(15,0)   ENCODE az64
	,NET_QTY NUMERIC(28,10)   ENCODE az64
	,BATCH_ID NUMERIC(15,0)   ENCODE az64
	,RATE NUMERIC(28,10)   ENCODE az64
	,RATE_TYPE VARCHAR(24) ENCODE lzo
	,TAX_CODE_ID NUMERIC(15,0)   ENCODE az64
	,TAX_RATE NUMERIC(28,10)   ENCODE az64
	,ERROR_CODE VARCHAR(30) ENCODE lzo
	,RECOVERABLE_TAX NUMERIC(28,10)   ENCODE az64
	,NON_RECOVERABLE_TAX NUMERIC(28,10)   ENCODE az64
	,TAX_RECOVERY_RATE NUMERIC(28,10)   ENCODE az64
	,PARENT_TRANSACTION_ID NUMERIC(15,0)   ENCODE az64
	,CHARGE_ACCOUNT_ID NUMERIC(15,0)   ENCODE az64
	,VARIANCE_ACCOUNT_ID NUMERIC(15,0)   ENCODE az64
	,GLOBAL_AGREEMENT_FLAG VARCHAR(1) ENCODE lzo
	,NEED_BY_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,ERROR_EXPLANATION VARCHAR(240) ENCODE lzo
	,SECONDARY_NET_QTY NUMERIC(28,10)   ENCODE az64
	,BLANKET_PRICE NUMERIC(28,10)   ENCODE az64
	,PO_DISTRIBUTION_ID NUMERIC(15,0)   ENCODE az64
	,INTERFACE_DISTRIBUTION_REF VARCHAR(240)   ENCODE lzo
	,TRANSACTION_SOURCE_ID NUMERIC(15,0)   ENCODE az64
	,INVENTORY_ITEM_ID NUMERIC(15,0)   ENCODE az64
	,ACCRUAL_ACCOUNT_ID NUMERIC(15,0)   ENCODE az64
	,ORGANIZATION_ID NUMERIC(15,0)   ENCODE az64
	,OWNING_ORGANIZATION_ID NUMERIC(15,0)   ENCODE az64
	,TRANSACTION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,PO_LINE_ID NUMERIC(15,0)   ENCODE az64
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.mtl_consumption_transactions (
	TRANSACTION_ID,
	CONSUMPTION_RELEASE_ID,
	CONSUMPTION_PO_HEADER_ID,
	CONSUMPTION_PROCESSED_FLAG,
	REQUEST_ID,
	CREATED_BY,
	PROGRAM_APPLICATION_ID,
	CREATION_DATE,
	PROGRAM_ID,
	LAST_UPDATED_BY,
	PROGRAM_UPDATE_DATE,
	LAST_UPDATE_DATE,
	LAST_UPDATE_LOGIN,
	NET_QTY,
	BATCH_ID,
	RATE,
	RATE_TYPE,
	TAX_CODE_ID,
	TAX_RATE,
	ERROR_CODE,
	RECOVERABLE_TAX,
	NON_RECOVERABLE_TAX,
	TAX_RECOVERY_RATE,
	PARENT_TRANSACTION_ID,
	CHARGE_ACCOUNT_ID,
	VARIANCE_ACCOUNT_ID,
	GLOBAL_AGREEMENT_FLAG,
	NEED_BY_DATE,
	ERROR_EXPLANATION,
	SECONDARY_NET_QTY,
	BLANKET_PRICE,
	PO_DISTRIBUTION_ID,
	INTERFACE_DISTRIBUTION_REF,
	TRANSACTION_SOURCE_ID,
	INVENTORY_ITEM_ID,
	ACCRUAL_ACCOUNT_ID,
	ORGANIZATION_ID,
	OWNING_ORGANIZATION_ID,
	TRANSACTION_DATE,
	PO_LINE_ID,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date)
    SELECT
		TRANSACTION_ID,
		CONSUMPTION_RELEASE_ID,
		CONSUMPTION_PO_HEADER_ID,
		CONSUMPTION_PROCESSED_FLAG,
		REQUEST_ID,
		CREATED_BY,
		PROGRAM_APPLICATION_ID,
		CREATION_DATE,
		PROGRAM_ID,
		LAST_UPDATED_BY,
		PROGRAM_UPDATE_DATE,
		LAST_UPDATE_DATE,
		LAST_UPDATE_LOGIN,
		NET_QTY,
		BATCH_ID,
		RATE,
		RATE_TYPE,
		TAX_CODE_ID,
		TAX_RATE,
		ERROR_CODE,
		RECOVERABLE_TAX,
		NON_RECOVERABLE_TAX,
		TAX_RECOVERY_RATE,
		PARENT_TRANSACTION_ID,
		CHARGE_ACCOUNT_ID,
		VARIANCE_ACCOUNT_ID,
		GLOBAL_AGREEMENT_FLAG,
		NEED_BY_DATE,
		ERROR_EXPLANATION,
		SECONDARY_NET_QTY,
		BLANKET_PRICE,
		PO_DISTRIBUTION_ID,
		INTERFACE_DISTRIBUTION_REF,
		TRANSACTION_SOURCE_ID,
		INVENTORY_ITEM_ID,
		ACCRUAL_ACCOUNT_ID,
		ORGANIZATION_ID,
		OWNING_ORGANIZATION_ID,
		TRANSACTION_DATE,
		PO_LINE_ID,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
    FROM
        bec_ods_stg.mtl_consumption_transactions;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'mtl_consumption_transactions';
	
commit;