/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.mtl_txn_request_lines;

CREATE TABLE IF NOT EXISTS bec_ods.mtl_txn_request_lines
(
	LINE_ID NUMERIC(15,0) ENCODE az64 
	,HEADER_ID NUMERIC(15,0) ENCODE az64 
	,LINE_NUMBER NUMERIC(15,0) ENCODE az64 
	,ORGANIZATION_ID NUMERIC(15,0) ENCODE az64 
	,INVENTORY_ITEM_ID NUMERIC(15,0) ENCODE az64 
	,REVISION VARCHAR(3) ENCODE lzo 	
	,FROM_SUBINVENTORY_CODE VARCHAR(10) ENCODE lzo 
	,FROM_LOCATOR_ID NUMERIC(15,0) ENCODE az64 	
	,TO_SUBINVENTORY_CODE VARCHAR(10) ENCODE lzo 
	,TO_LOCATOR_ID NUMERIC(15,0) ENCODE az64 
	,TO_ACCOUNT_ID NUMERIC(15,0) ENCODE az64 
	,LOT_NUMBER VARCHAR(80) ENCODE lzo
	,SERIAL_NUMBER_START VARCHAR(30) ENCODE lzo
	,SERIAL_NUMBER_END VARCHAR(30) ENCODE lzo
	,UOM_CODE VARCHAR(3) ENCODE lzo
	,QUANTITY NUMERIC(28,10) ENCODE az64 
	,QUANTITY_DELIVERED NUMERIC(28,10) ENCODE az64
	,QUANTITY_DETAILED NUMERIC(28,10) ENCODE az64	
	,DATE_REQUIRED TIMESTAMP WITHOUT TIME ZONE ENCODE az64 	
	,REASON_ID NUMERIC(15,0) ENCODE az64	
	,REFERENCE VARCHAR(240) ENCODE lzo  
	,REFERENCE_TYPE_CODE NUMERIC(15,0) ENCODE az64 
	,REFERENCE_ID NUMERIC(15,0) ENCODE az64 
	,PROJECT_ID NUMERIC(15,0) ENCODE az64  
	,TASK_ID NUMERIC(15,0) ENCODE az64 
	,TRANSACTION_HEADER_ID NUMERIC(15,0) ENCODE az64 
	,LINE_STATUS NUMERIC(15,0) ENCODE az64 	
	,STATUS_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64  
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64  
	,CREATED_BY NUMERIC(15,0) ENCODE az64 
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 	
	,REQUEST_ID NUMERIC(15,0) ENCODE az64 	
	,PROGRAM_APPLICATION_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64  
	,ATTRIBUTE1 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE2 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE3 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE4 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE5 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE6 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE7 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE8 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE9 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE10 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE11 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE12 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE13 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE14 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE15 VARCHAR(150) ENCODE lzo
	,ATTRIBUTE_CATEGORY VARCHAR(30) ENCODE lzo 
	,TXN_SOURCE_ID NUMERIC(15,0) ENCODE az64 
	,TXN_SOURCE_LINE_ID  NUMERIC(15,0) ENCODE az64 	 
	,TXN_SOURCE_LINE_DETAIL_ID NUMERIC(15,0) ENCODE az64 
	,TRANSACTION_TYPE_ID  NUMERIC(15,0) ENCODE az64 	 
	,TRANSACTION_SOURCE_TYPE_ID NUMERIC(15,0) ENCODE az64 
	,PRIMARY_QUANTITY  NUMERIC(28,10) ENCODE az64 	 
	,TO_ORGANIZATION_ID NUMERIC(15,0) ENCODE az64 
	,PUT_AWAY_STRATEGY_ID  NUMERIC(15,0) ENCODE az64 	 
	,PICK_STRATEGY_ID NUMERIC(15,0) ENCODE az64 
	,SHIP_TO_LOCATION_ID  NUMERIC(15,0) ENCODE az64 
	,UNIT_NUMBER VARCHAR(30) ENCODE lzo
	,REFERENCE_DETAIL_ID  NUMERIC(15,0) ENCODE az64 	 
	,ASSIGNMENT_ID NUMERIC(15,0) ENCODE az64 
	,FROM_COST_GROUP_ID  NUMERIC(15,0) ENCODE az64 	 
	,TO_COST_GROUP_ID NUMERIC(15,0) ENCODE az64 
	,LPN_ID  NUMERIC(15,0) ENCODE az64 	 
	,TO_LPN_ID NUMERIC(15,0) ENCODE az64 
	,PICK_SLIP_NUMBER  NUMERIC(15,0) ENCODE az64 
	,PICK_SLIP_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,FROM_SUBINVENTORY_ID NUMERIC(15,0) ENCODE az64 
	,TO_SUBINVENTORY_ID  NUMERIC(15,0) ENCODE az64 	 
	,INSPECTION_STATUS NUMERIC(15,0) ENCODE az64 
	,PICK_METHODOLOGY_ID  NUMERIC(15,0) ENCODE az64 	 
	,CONTAINER_ITEM_ID NUMERIC(15,0) ENCODE az64 
	,CARTON_GROUPING_ID  NUMERIC(15,0) ENCODE az64 
	,BACKORDER_DELIVERY_DETAIL_ID  NUMERIC(15,0) ENCODE az64 	 
	,WMS_PROCESS_FLAG NUMERIC(15,0) ENCODE az64 
	,SHIP_SET_ID  NUMERIC(15,0) ENCODE az64 	 
	,SHIP_MODEL_ID NUMERIC(15,0) ENCODE az64 
	,MODEL_QUANTITY  NUMERIC(28,10) ENCODE az64 	 
	,CROSSDOCK_TYPE NUMERIC(28,10) ENCODE az64 
	,REQUIRED_QUANTITY  NUMERIC(28,10) ENCODE az64	
	,GRADE_CODE VARCHAR(150) ENCODE lzo		 
	,SECONDARY_QUANTITY NUMERIC(28,10) ENCODE az64 
	,SECONDARY_QUANTITY_DELIVERED  NUMERIC(28,10) ENCODE az64	 
	,SECONDARY_QUANTITY_DETAILED NUMERIC(28,10) ENCODE az64 
	,SECONDARY_REQUIRED_QUANTITY  NUMERIC(28,10) ENCODE az64
	,SECONDARY_UOM_CODE VARCHAR(3) ENCODE lzo	
	,WIP_ENTITY_ID NUMERIC(15,0) ENCODE az64 
	,REPETITIVE_SCHEDULE_ID NUMERIC(15,0) ENCODE az64 
	,OPERATION_SEQ_NUM NUMERIC(15,0) ENCODE az64 
	,WIP_SUPPLY_TYPE NUMERIC(15,0) ENCODE az64  	
	,MCC_CODE VARCHAR(30) ENCODE lzo 
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.mtl_txn_request_lines (
	LINE_ID,
	HEADER_ID,
	LINE_NUMBER,
	ORGANIZATION_ID,
	INVENTORY_ITEM_ID,
	REVISION,
	FROM_SUBINVENTORY_CODE,
	FROM_LOCATOR_ID,
	TO_SUBINVENTORY_CODE,
	TO_LOCATOR_ID,
	TO_ACCOUNT_ID,
	LOT_NUMBER,
	SERIAL_NUMBER_START,
	SERIAL_NUMBER_END,
	UOM_CODE,
	QUANTITY,
	QUANTITY_DELIVERED,
	QUANTITY_DETAILED,
	DATE_REQUIRED,
	REASON_ID,
	REFERENCE,
	REFERENCE_TYPE_CODE,
	REFERENCE_ID,
	PROJECT_ID,
	TASK_ID,
	TRANSACTION_HEADER_ID,
	LINE_STATUS,
	STATUS_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_LOGIN,
	LAST_UPDATE_DATE,
	CREATED_BY,
	CREATION_DATE,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	ATTRIBUTE_CATEGORY,
	TXN_SOURCE_ID,
	TXN_SOURCE_LINE_ID,
	TXN_SOURCE_LINE_DETAIL_ID,
	TRANSACTION_TYPE_ID,
	TRANSACTION_SOURCE_TYPE_ID,
	PRIMARY_QUANTITY,
	TO_ORGANIZATION_ID,
	PUT_AWAY_STRATEGY_ID,
	PICK_STRATEGY_ID,
	SHIP_TO_LOCATION_ID,
	UNIT_NUMBER,
	REFERENCE_DETAIL_ID,
	ASSIGNMENT_ID,
	FROM_COST_GROUP_ID,
	TO_COST_GROUP_ID,
	LPN_ID,
	TO_LPN_ID,
	PICK_SLIP_NUMBER,
	PICK_SLIP_DATE,
	FROM_SUBINVENTORY_ID,
	TO_SUBINVENTORY_ID,
	INSPECTION_STATUS,
	PICK_METHODOLOGY_ID,
	CONTAINER_ITEM_ID,
	CARTON_GROUPING_ID,
	BACKORDER_DELIVERY_DETAIL_ID,
	WMS_PROCESS_FLAG,
	SHIP_SET_ID,
	SHIP_MODEL_ID,
	MODEL_QUANTITY,
	CROSSDOCK_TYPE,
	REQUIRED_QUANTITY,
	GRADE_CODE,
	SECONDARY_QUANTITY,
	SECONDARY_QUANTITY_DELIVERED,
	SECONDARY_QUANTITY_DETAILED,
	SECONDARY_REQUIRED_QUANTITY,
	SECONDARY_UOM_CODE,
	WIP_ENTITY_ID,
	REPETITIVE_SCHEDULE_ID,
	OPERATION_SEQ_NUM,
	WIP_SUPPLY_TYPE,
	MCC_CODE,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id
	,kca_seq_date
)
    SELECT
		LINE_ID,
		HEADER_ID,
		LINE_NUMBER,
		ORGANIZATION_ID,
		INVENTORY_ITEM_ID,
		REVISION,
		FROM_SUBINVENTORY_CODE,
		FROM_LOCATOR_ID,
		TO_SUBINVENTORY_CODE,
		TO_LOCATOR_ID,
		TO_ACCOUNT_ID,
		LOT_NUMBER,
		SERIAL_NUMBER_START,
		SERIAL_NUMBER_END,
		UOM_CODE,
		QUANTITY,
		QUANTITY_DELIVERED,
		QUANTITY_DETAILED,
		DATE_REQUIRED,
		REASON_ID,
		REFERENCE,
		REFERENCE_TYPE_CODE,
		REFERENCE_ID,
		PROJECT_ID,
		TASK_ID,
		TRANSACTION_HEADER_ID,
		LINE_STATUS,
		STATUS_DATE,
		LAST_UPDATED_BY,
		LAST_UPDATE_LOGIN,
		LAST_UPDATE_DATE,
		CREATED_BY,
		CREATION_DATE,
		REQUEST_ID,
		PROGRAM_APPLICATION_ID,
		PROGRAM_ID,
		PROGRAM_UPDATE_DATE,
		ATTRIBUTE1,
		ATTRIBUTE2,
		ATTRIBUTE3,
		ATTRIBUTE4,
		ATTRIBUTE5,
		ATTRIBUTE6,
		ATTRIBUTE7,
		ATTRIBUTE8,
		ATTRIBUTE9,
		ATTRIBUTE10,
		ATTRIBUTE11,
		ATTRIBUTE12,
		ATTRIBUTE13,
		ATTRIBUTE14,
		ATTRIBUTE15,
		ATTRIBUTE_CATEGORY,
		TXN_SOURCE_ID,
		TXN_SOURCE_LINE_ID,
		TXN_SOURCE_LINE_DETAIL_ID,
		TRANSACTION_TYPE_ID,
		TRANSACTION_SOURCE_TYPE_ID,
		PRIMARY_QUANTITY,
		TO_ORGANIZATION_ID,
		PUT_AWAY_STRATEGY_ID,
		PICK_STRATEGY_ID,
		SHIP_TO_LOCATION_ID,
		UNIT_NUMBER,
		REFERENCE_DETAIL_ID,
		ASSIGNMENT_ID,
		FROM_COST_GROUP_ID,
		TO_COST_GROUP_ID,
		LPN_ID,
		TO_LPN_ID,
		PICK_SLIP_NUMBER,
		PICK_SLIP_DATE,
		FROM_SUBINVENTORY_ID,
		TO_SUBINVENTORY_ID,
		INSPECTION_STATUS,
		PICK_METHODOLOGY_ID,
		CONTAINER_ITEM_ID,
		CARTON_GROUPING_ID,
		BACKORDER_DELIVERY_DETAIL_ID,
		WMS_PROCESS_FLAG,
		SHIP_SET_ID,
		SHIP_MODEL_ID,
		MODEL_QUANTITY,
		CROSSDOCK_TYPE,
		REQUIRED_QUANTITY,
		GRADE_CODE,
		SECONDARY_QUANTITY,
		SECONDARY_QUANTITY_DELIVERED,
		SECONDARY_QUANTITY_DETAILED,
		SECONDARY_REQUIRED_QUANTITY,
		SECONDARY_UOM_CODE,
		WIP_ENTITY_ID,
		REPETITIVE_SCHEDULE_ID,
		OPERATION_SEQ_NUM,
		WIP_SUPPLY_TYPE,
		MCC_CODE,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
    FROM
        bec_ods_stg.mtl_txn_request_lines;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'mtl_txn_request_lines';
	
commit;