/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.MTL_SERIAL_NUMBERS;

CREATE TABLE  IF NOT EXISTS bec_ods.MTL_SERIAL_NUMBERS
(
	INVENTORY_ITEM_ID NUMERIC(15,0)   ENCODE az64, 
SERIAL_NUMBER VARCHAR(30)   ENCODE lzo, 
LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
LAST_UPDATED_BY NUMERIC(15,0)   ENCODE az64, 
CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
CREATED_BY NUMERIC(15,0)   ENCODE az64, 
LAST_UPDATE_LOGIN NUMERIC(15,0)   ENCODE az64, 
REQUEST_ID NUMERIC(15,0)   ENCODE az64, 
PROGRAM_APPLICATION_ID NUMERIC(15,0)   ENCODE az64, 
PROGRAM_ID NUMERIC(15,0)   ENCODE az64, 
PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
INITIALIZATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
COMPLETION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
SHIP_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
CURRENT_STATUS NUMERIC(15,0)   ENCODE az64, 
REVISION VARCHAR(3)   ENCODE lzo, 
LOT_NUMBER VARCHAR(80)   ENCODE lzo, 
FIXED_ASSET_TAG VARCHAR(10)    ENCODE lzo, 
RESERVED_ORDER_ID NUMERIC(15,0)   ENCODE az64, 
PARENT_ITEM_ID NUMERIC(15,0)   ENCODE az64, 
PARENT_SERIAL_NUMBER VARCHAR(30)   ENCODE lzo, 
END_ITEM_UNIT_NUMBER VARCHAR(30)   ENCODE lzo, 
ORIGINAL_WIP_ENTITY_ID NUMERIC(15,0)   ENCODE az64, 
ORIGINAL_UNIT_VENDOR_ID NUMERIC(15,0)   ENCODE az64, 
VENDOR_SERIAL_NUMBER VARCHAR(30)   ENCODE lzo, 
VENDOR_LOT_NUMBER VARCHAR(30)   ENCODE lzo, 
LAST_TXN_SOURCE_TYPE_ID NUMERIC(15,0)   ENCODE az64, 
LAST_TRANSACTION_ID NUMERIC(15,0)   ENCODE az64, 
LAST_RECEIPT_ISSUE_TYPE NUMERIC(15,0)   ENCODE az64, 
LAST_TXN_SOURCE_NAME VARCHAR(80)    ENCODE lzo, 
LAST_TXN_SOURCE_ID NUMERIC(15,0)   ENCODE az64, 
DESCRIPTIVE_TEXT VARCHAR(240)   ENCODE lzo, 
CURRENT_SUBINVENTORY_CODE VARCHAR(10)    ENCODE lzo, 
CURRENT_LOCATOR_ID NUMERIC(15,0)   ENCODE az64, 
CURRENT_ORGANIZATION_ID NUMERIC(15,0)   ENCODE az64, 
ATTRIBUTE_CATEGORY VARCHAR(30)   ENCODE lzo, 
ATTRIBUTE1 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE2 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE3 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE4 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE5 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE6 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE7 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE8 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE9 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE10 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE11 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE12 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE13 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE14 VARCHAR(150)   ENCODE lzo, 
ATTRIBUTE15 VARCHAR(150)   ENCODE lzo, 
GROUP_MARK_ID NUMERIC(15,0)   ENCODE az64, 
LINE_MARK_ID NUMERIC(15,0)   ENCODE az64, 
LOT_LINE_MARK_ID NUMERIC(15,0)   ENCODE az64, 
GEN_OBJECT_ID NUMERIC(15,0)   ENCODE az64, 
SERIAL_ATTRIBUTE_CATEGORY VARCHAR(30)   ENCODE lzo,  
ORIGINATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
C_ATTRIBUTE1 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE2 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE3 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE4 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE5 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE6 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE7 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE8 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE9 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE10 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE11 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE12 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE13 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE14 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE15 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE16 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE17 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE18 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE19 VARCHAR(150)   ENCODE lzo, 
C_ATTRIBUTE20 VARCHAR(150)   ENCODE lzo, 
D_ATTRIBUTE1 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE2 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE3 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE4 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE5 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE6 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE7 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE8 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE9 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE10 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE11 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE12 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE13 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE14 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE15 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE16 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE17 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE18 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE19 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
D_ATTRIBUTE20 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64, 
N_ATTRIBUTE1 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE2 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE3 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE4 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE5 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE6 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE7 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE8 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE9 NUMERIC(15,0)   ENCODE az64, 
N_ATTRIBUTE10 NUMERIC(15,0)   ENCODE az64, 
STATUS_ID NUMERIC(15,0)   ENCODE az64, 
TERRITORY_CODE VARCHAR(30)   ENCODE lzo, 
COST_GROUP_ID NUMERIC(15,0)   ENCODE az64, 
TIME_SINCE_NEW NUMERIC(15,0)   ENCODE az64, 
CYCLES_SINCE_NEW NUMERIC(15,0)   ENCODE az64, 
TIME_SINCE_OVERHAUL NUMERIC(15,0)   ENCODE az64, 
CYCLES_SINCE_OVERHAUL NUMERIC(15,0)   ENCODE az64, 
TIME_SINCE_REPAIR NUMERIC(15,0)   ENCODE az64, 
CYCLES_SINCE_REPAIR NUMERIC(15,0)   ENCODE az64, 
TIME_SINCE_VISIT NUMERIC(15,0)   ENCODE az64, 
CYCLES_SINCE_VISIT NUMERIC(15,0)   ENCODE az64, 
TIME_SINCE_MARK NUMERIC(15,0)   ENCODE az64, 
CYCLES_SINCE_MARK NUMERIC(15,0)   ENCODE az64, 
NUMBER_OF_REPAIRS NUMERIC(15,0)   ENCODE az64, 
LPN_ID NUMERIC(15,0)   ENCODE az64, 
INSPECTION_STATUS NUMERIC(15,0)   ENCODE az64, 
PREVIOUS_STATUS NUMERIC(15,0)   ENCODE az64, 
LPN_TXN_ERROR_FLAG VARCHAR(1)   ENCODE lzo, 
WIP_ACCOUNTING_CLASS_CODE VARCHAR(10)    ENCODE lzo, 
MAINTAINABLE_FLAG VARCHAR(1)   ENCODE lzo, 
OWNING_DEPARTMENT_ID NUMERIC(15,0)   ENCODE az64, 
NETWORK_ASSET_FLAG VARCHAR(1)   ENCODE lzo, 
FA_ASSET_ID NUMERIC(15,0)   ENCODE az64, 
PN_LOCATION_ID NUMERIC(15,0)   ENCODE az64, 
EAM_LOCATION_ID NUMERIC(15,0)   ENCODE az64, 
ASSET_CRITICALITY_CODE VARCHAR(30)   ENCODE lzo, 
CATEGORY_ID NUMERIC(15,0)   ENCODE az64, 
PROD_ORGANIZATION_ID NUMERIC(15,0)   ENCODE az64, 
EQUIPMENT_ITEM_ID NUMERIC(15,0)   ENCODE az64, 
EQP_SERIAL_NUMBER VARCHAR(30)   ENCODE lzo, 
ORGANIZATION_TYPE NUMERIC(15,0)   ENCODE az64, 
OWNING_ORGANIZATION_ID NUMERIC(15,0)   ENCODE az64, 
OWNING_TP_TYPE NUMERIC(15,0)   ENCODE az64, 
PLANNING_ORGANIZATION_ID NUMERIC(15,0)   ENCODE az64, 
PLANNING_TP_TYPE NUMERIC(15,0)   ENCODE az64, 
ONHAND_QUANTITIES_ID NUMERIC(15,0)   ENCODE az64, 
WIP_ENTITY_ID NUMERIC(15,0)   ENCODE az64, 
OPERATION_SEQ_NUM NUMERIC(15,0)   ENCODE az64, 
INTRAOPERATION_STEP_TYPE NUMERIC(15,0)   ENCODE az64, 
EAM_INSTANTIATION_FLAG VARCHAR(1)   ENCODE lzo, 
DEPENDENT_ASSET_FLAG VARCHAR(1)   ENCODE lzo, 
EAM_LINEAR_LOCATION_ID NUMERIC(15,0)   ENCODE az64, 
RESERVATION_ID NUMERIC(15,0)   ENCODE az64, 
AVAILABILITY_TYPE NUMERIC(15,0)   ENCODE az64, 
INVENTORY_ATP_CODE NUMERIC(15,0)   ENCODE az64, 
RESERVABLE_TYPE NUMERIC(15,0)   ENCODE az64, 
PARENT_LOT_NUMBER VARCHAR(30)   ENCODE lzo, 
OPERATIONAL_LOG_FLAG VARCHAR(1)   ENCODE lzo, 
OPERATIONAL_STATUS_FLAG NUMERIC(15,0)   ENCODE az64,
C_ATTRIBUTE21 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE22 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE23 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE24 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE25 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE26 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE27 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE28 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE29 VARCHAR(150)   ENCODE lzo,
C_ATTRIBUTE30 VARCHAR(150)   ENCODE lzo,
N_ATTRIBUTE11 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE12 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE13 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE14 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE15 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE16 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE17 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE18 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE19 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE20 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE21 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE22 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE23 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE24 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE25 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE26 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE27 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE28 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE29 NUMERIC(15,0)   ENCODE az64,
N_ATTRIBUTE30 NUMERIC(15,0)   ENCODE az64,
COUNTRY_OF_ORIGIN VARCHAR(30)   ENCODE lzo,
MCC_CODE VARCHAR(30)   ENCODE lzo,
KCA_OPERATION VARCHAR(10)   ENCODE lzo,
IS_DELETED_FLG VARCHAR(2) ENCODE lzo,
kca_seq_id NUMERIC(36,0)   ENCODE az64
 ,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64

)
DISTSTYLE AUTO
;
	
insert
	into
	bec_ods.MTL_SERIAL_NUMBERS
(inventory_item_id,
	serial_number,
	last_update_date,
	last_updated_by,
	creation_date,
	created_by,
	last_update_login,
	request_id,
	program_application_id,
	program_id,
	program_update_date,
	initialization_date,
	completion_date,
	ship_date,
	current_status,
	revision,
	lot_number,
	fixed_asset_tag,
	reserved_order_id,
	parent_item_id,
	parent_serial_number,
	original_wip_entity_id,
	original_unit_vendor_id,
	vendor_serial_number,
	vendor_lot_number,
	last_txn_source_type_id,
	last_transaction_id,
	last_receipt_issue_type,
	last_txn_source_name,
	last_txn_source_id,
	descriptive_text,
	current_subinventory_code,
	current_locator_id,
	current_organization_id,
	attribute_category,
	attribute1,
	attribute2,
	attribute3,
	attribute4,
	attribute5,
	attribute6,
	attribute7,
	attribute8,
	attribute9,
	attribute10,
	attribute11,
	attribute12,
	attribute13,
	attribute14,
	attribute15,
	group_mark_id,
	line_mark_id,
	lot_line_mark_id,
	end_item_unit_number,
	gen_object_id,
	serial_attribute_category,
	origination_date,
	c_attribute1,
	c_attribute2,
	c_attribute3,
	c_attribute4,
	c_attribute5,
	c_attribute6,
	c_attribute7,
	c_attribute8,
	c_attribute9,
	c_attribute10,
	c_attribute11,
	c_attribute12,
	c_attribute13,
	c_attribute14,
	c_attribute15,
	c_attribute16,
	c_attribute17,
	c_attribute18,
	c_attribute19,
	c_attribute20,
	d_attribute1,
	d_attribute2,
	d_attribute3,
	d_attribute4,
	d_attribute5,
	d_attribute6,
	d_attribute7,
	d_attribute8,
	d_attribute9,
	d_attribute10,
	n_attribute1,
	n_attribute2,
	n_attribute3,
	n_attribute4,
	n_attribute5,
	n_attribute6,
	n_attribute7,
	n_attribute8,
	n_attribute9,
	n_attribute10,
	status_id,
	territory_code,
	cost_group_id,
	time_since_new,
	cycles_since_new,
	time_since_overhaul,
	cycles_since_overhaul,
	time_since_repair,
	cycles_since_repair,
	time_since_visit,
	cycles_since_visit,
	time_since_mark,
	cycles_since_mark,
	number_of_repairs,
	lpn_id,
	inspection_status,
	previous_status,
	lpn_txn_error_flag,
	wip_accounting_class_code,
	maintainable_flag,
	owning_department_id,
	dependent_asset_flag,
	network_asset_flag,
	fa_asset_id,
	pn_location_id,
	eam_location_id,
	asset_criticality_code,
	category_id,
	prod_organization_id,
	equipment_item_id,
	eqp_serial_number,
	organization_type,
	owning_organization_id,
	owning_tp_type,
	planning_organization_id,
	planning_tp_type,
	onhand_quantities_id,
	wip_entity_id,
	operation_seq_num,
	intraoperation_step_type,
	eam_instantiation_flag,
	eam_linear_location_id,
	reservation_id,
	availability_type,
	inventory_atp_code,
	reservable_type,
	parent_lot_number,
	operational_log_flag,
	operational_status_flag,
	c_attribute21,
	c_attribute22,
	c_attribute23,
	c_attribute24,
	c_attribute25,
	c_attribute26,
	c_attribute27,
	c_attribute28,
	c_attribute29,
	c_attribute30,
	n_attribute11,
	n_attribute12,
	n_attribute13,
	n_attribute14,
	n_attribute15,
	n_attribute16,
	n_attribute17,
	n_attribute18,
	n_attribute19,
	n_attribute20,
	n_attribute21,
	n_attribute22,
	n_attribute23,
	n_attribute24,
	n_attribute25,
	n_attribute26,
	n_attribute27,
	n_attribute28,
	n_attribute29,
	n_attribute30,
	country_of_origin,
	mcc_code,
	kca_operation,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date)
	SELECT
inventory_item_id,
	serial_number,
	last_update_date,
	last_updated_by,
	creation_date,
	created_by,
	last_update_login,
	request_id,
	program_application_id,
	program_id,
	program_update_date,
	initialization_date,
	completion_date,
	ship_date,
	current_status,
	revision,
	lot_number,
	fixed_asset_tag,
	reserved_order_id,
	parent_item_id,
	parent_serial_number,
	original_wip_entity_id,
	original_unit_vendor_id,
	vendor_serial_number,
	vendor_lot_number,
	last_txn_source_type_id,
	last_transaction_id,
	last_receipt_issue_type,
	last_txn_source_name,
	last_txn_source_id,
	descriptive_text,
	current_subinventory_code,
	current_locator_id,
	current_organization_id,
	attribute_category,
	attribute1,
	attribute2,
	attribute3,
	attribute4,
	attribute5,
	attribute6,
	attribute7,
	attribute8,
	attribute9,
	attribute10,
	attribute11,
	attribute12,
	attribute13,
	attribute14,
	attribute15,
	group_mark_id,
	line_mark_id,
	lot_line_mark_id,
	end_item_unit_number,
	gen_object_id,
	serial_attribute_category,
	origination_date,
	c_attribute1,
	c_attribute2,
	c_attribute3,
	c_attribute4,
	c_attribute5,
	c_attribute6,
	c_attribute7,
	c_attribute8,
	c_attribute9,
	c_attribute10,
	c_attribute11,
	c_attribute12,
	c_attribute13,
	c_attribute14,
	c_attribute15,
	c_attribute16,
	c_attribute17,
	c_attribute18,
	c_attribute19,
	c_attribute20,
	d_attribute1,
	d_attribute2,
	d_attribute3,
	d_attribute4,
	d_attribute5,
	d_attribute6,
	d_attribute7,
	d_attribute8,
	d_attribute9,
	d_attribute10,
	n_attribute1,
	n_attribute2,
	n_attribute3,
	n_attribute4,
	n_attribute5,
	n_attribute6,
	n_attribute7,
	n_attribute8,
	n_attribute9,
	n_attribute10,
	status_id,
	territory_code,
	cost_group_id,
	time_since_new,
	cycles_since_new,
	time_since_overhaul,
	cycles_since_overhaul,
	time_since_repair,
	cycles_since_repair,
	time_since_visit,
	cycles_since_visit,
	time_since_mark,
	cycles_since_mark,
	number_of_repairs,
	lpn_id,
	inspection_status,
	previous_status,
	lpn_txn_error_flag,
	wip_accounting_class_code,
	maintainable_flag,
	owning_department_id,
	dependent_asset_flag,
	network_asset_flag,
	fa_asset_id,
	pn_location_id,
	eam_location_id,
	asset_criticality_code,
	category_id,
	prod_organization_id,
	equipment_item_id,
	eqp_serial_number,
	organization_type,
	owning_organization_id,
	owning_tp_type,
	planning_organization_id,
	planning_tp_type,
	onhand_quantities_id,
	wip_entity_id,
	operation_seq_num,
	intraoperation_step_type,
	eam_instantiation_flag,
	eam_linear_location_id,
	reservation_id,
	availability_type,
	inventory_atp_code,
	reservable_type,
	parent_lot_number,
	operational_log_flag,
	operational_status_flag,
	c_attribute21,
	c_attribute22,
	c_attribute23,
	c_attribute24,
	c_attribute25,
	c_attribute26,
	c_attribute27,
	c_attribute28,
	c_attribute29,
	c_attribute30,
	n_attribute11,
	n_attribute12,
	n_attribute13,
	n_attribute14,
	n_attribute15,
	n_attribute16,
	n_attribute17,
	n_attribute18,
	n_attribute19,
	n_attribute20,
	n_attribute21,
	n_attribute22,
	n_attribute23,
	n_attribute24,
	n_attribute25,
	n_attribute26,
	n_attribute27,
	n_attribute28,
	n_attribute29,
	n_attribute30,
	country_of_origin,
	mcc_code,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
    FROM
        bec_ods_stg.MTL_SERIAL_NUMBERS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'mtl_serial_numbers';
	
commit;
	
