/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.mtl_reservations;

CREATE TABLE IF NOT EXISTS bec_ods.mtl_reservations
(
	RESERVATION_ID NUMERIC(15,0) ENCODE az64 
	,REQUIREMENT_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,ORGANIZATION_ID NUMERIC(15,0) ENCODE az64  
	,INVENTORY_ITEM_ID NUMERIC(15,0) ENCODE az64 
	,DEMAND_SOURCE_TYPE_ID NUMERIC(15,0) ENCODE az64 
	,DEMAND_SOURCE_NAME VARCHAR(30) ENCODE lzo 
	,DEMAND_SOURCE_HEADER_ID NUMERIC(15,0) ENCODE az64 
	,DEMAND_SOURCE_LINE_ID NUMERIC(15,0) ENCODE az64 
	,DEMAND_SOURCE_DELIVERY NUMERIC(28,10) ENCODE az64 
	,PRIMARY_UOM_CODE VARCHAR(3) ENCODE lzo 
	,PRIMARY_UOM_ID NUMERIC(15,0) ENCODE az64 
	,RESERVATION_UOM_CODE VARCHAR(3) ENCODE lzo
	,RESERVATION_UOM_ID NUMERIC(15,0) ENCODE az64 
	,RESERVATION_QUANTITY NUMERIC(28,10) ENCODE az64 
	,PRIMARY_RESERVATION_QUANTITY NUMERIC(28,10) ENCODE az64 
	,AUTODETAIL_GROUP_ID NUMERIC(15,0) ENCODE az64  	
	,EXTERNAL_SOURCE_CODE VARCHAR(30) ENCODE lzo 
	,EXTERNAL_SOURCE_LINE_ID NUMERIC(15,0) ENCODE az64 
	,SUPPLY_SOURCE_TYPE_ID NUMERIC(15,0) ENCODE az64 
	,SUPPLY_SOURCE_HEADER_ID NUMERIC(15,0) ENCODE az64 
	,SUPPLY_SOURCE_LINE_ID NUMERIC(15,0) ENCODE az64 
	,SUPPLY_SOURCE_LINE_DETAIL NUMERIC(28,10) ENCODE az64 	
	,SUPPLY_SOURCE_NAME VARCHAR(30) ENCODE lzo 
	,REVISION VARCHAR(3) ENCODE lzo 
	,SUBINVENTORY_CODE VARCHAR(10) ENCODE lzo 
	,SUBINVENTORY_ID NUMERIC(15,0) ENCODE az64 
	,LOCATOR_ID NUMERIC(15,0) ENCODE az64 	
	,LOT_NUMBER VARCHAR(80) ENCODE lzo 
	,LOT_NUMBER_ID NUMERIC(15,0) ENCODE az64 	
	,SERIAL_NUMBER VARCHAR(3) ENCODE lzo  
	,SERIAL_NUMBER_ID NUMERIC(15,0) ENCODE az64 
	,PARTIAL_QUANTITIES_ALLOWED NUMERIC(28,10) ENCODE az64 
	,AUTO_DETAILED NUMERIC(28,10) ENCODE az64 
	,PICK_SLIP_NUMBER NUMERIC(28,10) ENCODE az64 
	,LPN_ID NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64 
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,CREATED_BY NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_LOGIN NUMERIC(15,0) ENCODE az64 
	,REQUEST_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_APPLICATION_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_ID NUMERIC(15,0) ENCODE az64 
	,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64	
	,ATTRIBUTE_CATEGORY VARCHAR(30) ENCODE lzo 
	,ATTRIBUTE1 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE2 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE3 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE4 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE5 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE6 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE7 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE8 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE9 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE10 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE11 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE12 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE13 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE14 VARCHAR(150) ENCODE lzo 
	,ATTRIBUTE15 VARCHAR(150) ENCODE lzo 
	,SHIP_READY_FLAG NUMERIC(15,0) ENCODE az64 
	,N_COLUMN1 NUMERIC(28,10) ENCODE az64 
	,DETAILED_QUANTITY NUMERIC(28,10) ENCODE az64 
	,COST_GROUP_ID NUMERIC(15,0) ENCODE az64 
	,CONTAINER_LPN_ID NUMERIC(15,0) ENCODE az64 	
	,STAGED_FLAG VARCHAR(1) ENCODE lzo 
	,SECONDARY_DETAILED_QUANTITY NUMERIC(28,10) ENCODE az64 
	,SECONDARY_RESERVATION_QUANTITY NUMERIC(28,10) ENCODE az64 	
	,SECONDARY_UOM_CODE VARCHAR(3) ENCODE lzo 
	,SECONDARY_UOM_ID NUMERIC(15,0) ENCODE az64 	
	,CROSSDOCK_FLAG VARCHAR(1) ENCODE lzo 
	,CROSSDOCK_CRITERIA_ID NUMERIC(15,0) ENCODE az64 
	,DEMAND_SOURCE_LINE_DETAIL NUMERIC(28,10) ENCODE az64 
	,SERIAL_RESERVATION_QUANTITY NUMERIC(28,10) ENCODE az64  
	,SUPPLY_RECEIPT_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DEMAND_SHIP_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64	
	,EXCEPTION_CODE VARCHAR(150) ENCODE lzo 
	,ORIG_SUPPLY_SOURCE_TYPE_ID NUMERIC(15,0) ENCODE az64 
	,ORIG_SUPPLY_SOURCE_HEADER_ID NUMERIC(15,0) ENCODE az64 
	,ORIG_SUPPLY_SOURCE_LINE_ID NUMERIC(15,0) ENCODE az64 
	,ORIG_SUPPLY_SOURCE_LINE_DETAIL NUMERIC(28,10) ENCODE az64 
	,ORIG_DEMAND_SOURCE_TYPE_ID NUMERIC(15,0) ENCODE az64 
	,ORIG_DEMAND_SOURCE_HEADER_ID NUMERIC(15,0) ENCODE az64 
	,ORIG_DEMAND_SOURCE_LINE_ID NUMERIC(15,0) ENCODE az64 
	,ORIG_DEMAND_SOURCE_LINE_DETAIL NUMERIC(28,10) ENCODE az64 
	,PROJECT_ID NUMERIC(15,0) ENCODE az64 
	,TASK_ID NUMERIC(15,0) ENCODE az64 
	,MCC_CODE VARCHAR(30) ENCODE lzo  
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.mtl_reservations (
	RESERVATION_ID,
	REQUIREMENT_DATE,
	ORGANIZATION_ID,
	INVENTORY_ITEM_ID,
	DEMAND_SOURCE_TYPE_ID,
	DEMAND_SOURCE_NAME,
	DEMAND_SOURCE_HEADER_ID,
	DEMAND_SOURCE_LINE_ID,
	DEMAND_SOURCE_DELIVERY,
	PRIMARY_UOM_CODE,
	PRIMARY_UOM_ID,
	RESERVATION_UOM_CODE,
	RESERVATION_UOM_ID,
	RESERVATION_QUANTITY,
	PRIMARY_RESERVATION_QUANTITY,
	AUTODETAIL_GROUP_ID,
	EXTERNAL_SOURCE_CODE,
	EXTERNAL_SOURCE_LINE_ID,
	SUPPLY_SOURCE_TYPE_ID,
	SUPPLY_SOURCE_HEADER_ID,
	SUPPLY_SOURCE_LINE_ID,
	SUPPLY_SOURCE_LINE_DETAIL,
	SUPPLY_SOURCE_NAME,
	REVISION,
	SUBINVENTORY_CODE,
	SUBINVENTORY_ID,
	LOCATOR_ID,
	LOT_NUMBER,
	LOT_NUMBER_ID,
	SERIAL_NUMBER,
	SERIAL_NUMBER_ID,
	PARTIAL_QUANTITIES_ALLOWED,
	AUTO_DETAILED,
	PICK_SLIP_NUMBER,
	LPN_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	SHIP_READY_FLAG,
	N_COLUMN1,
	DETAILED_QUANTITY,
	COST_GROUP_ID,
	CONTAINER_LPN_ID,
	STAGED_FLAG,
	SECONDARY_DETAILED_QUANTITY,
	SECONDARY_RESERVATION_QUANTITY,
	SECONDARY_UOM_CODE,
	SECONDARY_UOM_ID,
	CROSSDOCK_FLAG,
	CROSSDOCK_CRITERIA_ID,
	DEMAND_SOURCE_LINE_DETAIL,
	SERIAL_RESERVATION_QUANTITY,
	SUPPLY_RECEIPT_DATE,
	DEMAND_SHIP_DATE,
	EXCEPTION_CODE,
	ORIG_SUPPLY_SOURCE_TYPE_ID,
	ORIG_SUPPLY_SOURCE_HEADER_ID,
	ORIG_SUPPLY_SOURCE_LINE_ID,
	ORIG_SUPPLY_SOURCE_LINE_DETAIL,
	ORIG_DEMAND_SOURCE_TYPE_ID,
	ORIG_DEMAND_SOURCE_HEADER_ID,
	ORIG_DEMAND_SOURCE_LINE_ID,
	ORIG_DEMAND_SOURCE_LINE_DETAIL,
	PROJECT_ID,
	TASK_ID,
	MCC_CODE, 
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date)
    SELECT
		RESERVATION_ID,
		REQUIREMENT_DATE,
		ORGANIZATION_ID,
		INVENTORY_ITEM_ID,
		DEMAND_SOURCE_TYPE_ID,
		DEMAND_SOURCE_NAME,
		DEMAND_SOURCE_HEADER_ID,
		DEMAND_SOURCE_LINE_ID,
		DEMAND_SOURCE_DELIVERY,
		PRIMARY_UOM_CODE,
		PRIMARY_UOM_ID,
		RESERVATION_UOM_CODE,
		RESERVATION_UOM_ID,
		RESERVATION_QUANTITY,
		PRIMARY_RESERVATION_QUANTITY,
		AUTODETAIL_GROUP_ID,
		EXTERNAL_SOURCE_CODE,
		EXTERNAL_SOURCE_LINE_ID,
		SUPPLY_SOURCE_TYPE_ID,
		SUPPLY_SOURCE_HEADER_ID,
		SUPPLY_SOURCE_LINE_ID,
		SUPPLY_SOURCE_LINE_DETAIL,
		SUPPLY_SOURCE_NAME,
		REVISION,
		SUBINVENTORY_CODE,
		SUBINVENTORY_ID,
		LOCATOR_ID,
		LOT_NUMBER,
		LOT_NUMBER_ID,
		SERIAL_NUMBER,
		SERIAL_NUMBER_ID,
		PARTIAL_QUANTITIES_ALLOWED,
		AUTO_DETAILED,
		PICK_SLIP_NUMBER,
		LPN_ID,
		LAST_UPDATE_DATE,
		LAST_UPDATED_BY,
		CREATION_DATE,
		CREATED_BY,
		LAST_UPDATE_LOGIN,
		REQUEST_ID,
		PROGRAM_APPLICATION_ID,
		PROGRAM_ID,
		PROGRAM_UPDATE_DATE,
		ATTRIBUTE_CATEGORY,
		ATTRIBUTE1,
		ATTRIBUTE2,
		ATTRIBUTE3,
		ATTRIBUTE4,
		ATTRIBUTE5,
		ATTRIBUTE6,
		ATTRIBUTE7,
		ATTRIBUTE8,
		ATTRIBUTE9,
		ATTRIBUTE10,
		ATTRIBUTE11,
		ATTRIBUTE12,
		ATTRIBUTE13,
		ATTRIBUTE14,
		ATTRIBUTE15,
		SHIP_READY_FLAG,
		N_COLUMN1,
		DETAILED_QUANTITY,
		COST_GROUP_ID,
		CONTAINER_LPN_ID,
		STAGED_FLAG,
		SECONDARY_DETAILED_QUANTITY,
		SECONDARY_RESERVATION_QUANTITY,
		SECONDARY_UOM_CODE,
		SECONDARY_UOM_ID,
		CROSSDOCK_FLAG,
		CROSSDOCK_CRITERIA_ID,
		DEMAND_SOURCE_LINE_DETAIL,
		SERIAL_RESERVATION_QUANTITY,
		SUPPLY_RECEIPT_DATE,
		DEMAND_SHIP_DATE,
		EXCEPTION_CODE,
		ORIG_SUPPLY_SOURCE_TYPE_ID,
		ORIG_SUPPLY_SOURCE_HEADER_ID,
		ORIG_SUPPLY_SOURCE_LINE_ID,
		ORIG_SUPPLY_SOURCE_LINE_DETAIL,
		ORIG_DEMAND_SOURCE_TYPE_ID,
		ORIG_DEMAND_SOURCE_HEADER_ID,
		ORIG_DEMAND_SOURCE_LINE_ID,
		ORIG_DEMAND_SOURCE_LINE_DETAIL,
		PROJECT_ID,
		TASK_ID,
		MCC_CODE,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
    FROM
        bec_ods_stg.mtl_reservations;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'mtl_reservations';
	
commit;