/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.OKS_LEVEL_ELEMENTS;

CREATE TABLE IF NOT EXISTS bec_ods.OKS_LEVEL_ELEMENTS
(
	ID VARCHAR(50) ENCODE lzo
	,SEQUENCE_NUMBER VARCHAR(240) ENCODE lzo
	,DATE_START TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,AMOUNT NUMERIC(28,10) ENCODE az64  
	,DATE_RECEIVABLE_GL TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DATE_REVENUE_RULE_START TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DATE_TRANSACTION TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DATE_DUE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DATE_PRINT TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DATE_TO_INTERFACE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,DATE_COMPLETED TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,OBJECT_VERSION_NUMBER NUMERIC(9,0) ENCODE az64
	,RUL_ID VARCHAR(50) ENCODE lzo 
	,CREATED_BY NUMERIC(15,0) ENCODE az64 
	,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,LAST_UPDATED_BY NUMERIC(15,0) ENCODE az64 
	,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,SECURITY_GROUP_ID NUMERIC(15,0) ENCODE az64 
	,CLE_ID VARCHAR(50) ENCODE lzo 
	,DNZ_CHR_ID NUMERIC(15,0) ENCODE az64 
	,PARENT_CLE_ID VARCHAR(50) ENCODE lzo
	,DATE_END TIMESTAMP WITHOUT TIME ZONE ENCODE az64 
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
)
DISTSTYLE
auto;

COMMIT;

INSERT INTO bec_ods.OKS_LEVEL_ELEMENTS (
	ID,
	SEQUENCE_NUMBER,
	DATE_START,
	AMOUNT,
	DATE_RECEIVABLE_GL,
	DATE_REVENUE_RULE_START,
	DATE_TRANSACTION,
	DATE_DUE,
	DATE_PRINT,
	DATE_TO_INTERFACE,
	DATE_COMPLETED,
	OBJECT_VERSION_NUMBER,
	RUL_ID,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_DATE,
	SECURITY_GROUP_ID,
	CLE_ID,
	DNZ_CHR_ID,
	PARENT_CLE_ID,
	DATE_END,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date
)
    SELECT
		ID,
		SEQUENCE_NUMBER,
		DATE_START,
		AMOUNT,
		DATE_RECEIVABLE_GL,
		DATE_REVENUE_RULE_START,
		DATE_TRANSACTION,
		DATE_DUE,
		DATE_PRINT,
		DATE_TO_INTERFACE,
		DATE_COMPLETED,
		OBJECT_VERSION_NUMBER,
		RUL_ID,
		CREATED_BY,
		CREATION_DATE,
		LAST_UPDATED_BY,
		LAST_UPDATE_DATE,
		SECURITY_GROUP_ID,
		CLE_ID,
		DNZ_CHR_ID,
		PARENT_CLE_ID,
		DATE_END,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
    FROM
        bec_ods_stg.OKS_LEVEL_ELEMENTS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'oks_level_elements';
	
commit;