/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

drop table if exists bec_ods.PA_PROJECTS_ALL;

CREATE TABLE IF NOT EXISTS bec_ods.PA_PROJECTS_ALL
(
PROJECT_ID	NUMERIC(15,0)   ENCODE az64
,NAME	VARCHAR(30)   ENCODE lzo
,SEGMENT1	VARCHAR(25)   ENCODE lzo
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,PROJECT_TYPE	 VARCHAR(20)   ENCODE lzo
,CARRYING_OUT_ORGANIZATION_ID	NUMERIC(15,0)   ENCODE az64
,PUBLIC_SECTOR_FLAG	 VARCHAR(1)   ENCODE lzo
,PROJECT_STATUS_CODE	VARCHAR(30)   ENCODE lzo
,DESCRIPTION	 VARCHAR(250)   ENCODE lzo
,START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,COMPLETION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CLOSED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,DISTRIBUTION_RULE	VARCHAR(30)   ENCODE lzo
,LABOR_INVOICE_FORMAT_ID	NUMERIC(15,0)   ENCODE az64
,NON_LABOR_INVOICE_FORMAT_ID	NUMERIC(15,0)   ENCODE az64
,RETENTION_INVOICE_FORMAT_ID	NUMERIC(15,0)   ENCODE az64
,RETENTION_PERCENTAGE	NUMERIC(28,10)   ENCODE az64
,BILLING_OFFSET	NUMERIC(15,0)   ENCODE az64
,BILLING_CYCLE	NUMERIC(15,0)   ENCODE az64
,LABOR_STD_BILL_RATE_SCHDL	 VARCHAR(20)   ENCODE lzo
,LABOR_BILL_RATE_ORG_ID	NUMERIC(15,0)   ENCODE az64
,LABOR_SCHEDULE_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LABOR_SCHEDULE_DISCOUNT	NUMERIC(28,10)   ENCODE az64
,NON_LABOR_STD_BILL_RATE_SCHDL	VARCHAR(30)   ENCODE lzo
,NON_LABOR_BILL_RATE_ORG_ID	NUMERIC(15,0)   ENCODE az64
,NON_LABOR_SCHEDULE_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,NON_LABOR_SCHEDULE_DISCOUNT	NUMERIC(28,10)   ENCODE az64
,LIMIT_TO_TXN_CONTROLS_FLAG	 VARCHAR(1)   ENCODE lzo
,PROJECT_LEVEL_FUNDING_FLAG	 VARCHAR(1)   ENCODE lzo
,INVOICE_COMMENT	 VARCHAR(240)   ENCODE lzo
,UNBILLED_RECEIVABLE_DR	NUMERIC(28,10)   ENCODE az64
,UNEARNED_REVENUE_CR	NUMERIC(28,10)   ENCODE az64
,REQUEST_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SUMMARY_FLAG	 VARCHAR(1)   ENCODE lzo
,ENABLED_FLAG	 VARCHAR(1)   ENCODE lzo
,SEGMENT2	VARCHAR(25)   ENCODE lzo
,SEGMENT3	VARCHAR(25)   ENCODE lzo
,SEGMENT4	VARCHAR(25)   ENCODE lzo
,SEGMENT5	VARCHAR(25)   ENCODE lzo
,SEGMENT6	VARCHAR(25)   ENCODE lzo
,SEGMENT7	VARCHAR(25)   ENCODE lzo
,SEGMENT8	VARCHAR(25)   ENCODE lzo
,SEGMENT9	VARCHAR(25)   ENCODE lzo
,SEGMENT10	VARCHAR(25)   ENCODE lzo
,ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,ATTRIBUTE1	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	 VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	 VARCHAR(150)   ENCODE lzo
,COST_IND_RATE_SCH_ID	NUMERIC(15,0)   ENCODE az64
,REV_IND_RATE_SCH_ID	NUMERIC(15,0)   ENCODE az64
,INV_IND_RATE_SCH_ID	NUMERIC(15,0)   ENCODE az64
,COST_IND_SCH_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,REV_IND_SCH_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,INV_IND_SCH_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LABOR_SCH_TYPE	 VARCHAR(1)   ENCODE lzo
,NON_LABOR_SCH_TYPE	 VARCHAR(1)   ENCODE lzo
,OVR_COST_IND_RATE_SCH_ID	NUMERIC(15,0)   ENCODE az64
,OVR_REV_IND_RATE_SCH_ID	NUMERIC(15,0)   ENCODE az64
,OVR_INV_IND_RATE_SCH_ID	NUMERIC(15,0)   ENCODE az64
,TEMPLATE_FLAG	 VARCHAR(1)   ENCODE lzo
,VERIFICATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_FROM_PROJECT_ID	NUMERIC(15,0)   ENCODE az64
,TEMPLATE_START_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,TEMPLATE_END_DATE_ACTIVE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ORG_ID	NUMERIC(15,0)   ENCODE az64
,PM_PRODUCT_CODE	VARCHAR(30)   ENCODE lzo
,PM_PROJECT_REFERENCE	VARCHAR(25)   ENCODE lzo
,ACTUAL_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ACTUAL_FINISH_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,EARLY_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,EARLY_FINISH_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LATE_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LATE_FINISH_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SCHEDULED_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SCHEDULED_FINISH_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,BILLING_CYCLE_ID	NUMERIC(15,0)   ENCODE az64
,ADW_NOTIFY_FLAG	 VARCHAR(1)   ENCODE lzo
,WF_STATUS_CODE	VARCHAR(30)   ENCODE lzo
,OUTPUT_TAX_CODE	 VARCHAR(50)   ENCODE lzo
,RETENTION_TAX_CODE	 VARCHAR(50)   ENCODE lzo
,PROJECT_CURRENCY_CODE	 VARCHAR(15)   ENCODE lzo
,ALLOW_CROSS_CHARGE_FLAG	 VARCHAR(1)   ENCODE lzo
,PROJECT_RATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PROJECT_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,CC_PROCESS_LABOR_FLAG	 VARCHAR(1)   ENCODE lzo
,LABOR_TP_SCHEDULE_ID	NUMERIC(15,0)   ENCODE az64
,LABOR_TP_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CC_PROCESS_NL_FLAG	 VARCHAR(1)   ENCODE lzo
,NL_TP_SCHEDULE_ID	NUMERIC(15,0)   ENCODE az64
,NL_TP_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CC_TAX_TASK_ID	NUMERIC(15,0)   ENCODE az64
,BILL_JOB_GROUP_ID	NUMERIC(15,0)   ENCODE az64
,COST_JOB_GROUP_ID	NUMERIC(15,0)   ENCODE az64
,ROLE_LIST_ID	NUMERIC(15,0)   ENCODE az64
,WORK_TYPE_ID	NUMERIC(15,0)   ENCODE az64
,CALENDAR_ID	NUMERIC(15,0)   ENCODE az64
,LOCATION_ID	NUMERIC(15,0)   ENCODE az64
,PROBABILITY_MEMBER_ID	NUMERIC(15,0)   ENCODE az64
,PROJECT_VALUE	NUMERIC(28,10)   ENCODE az64
,EXPECTED_APPROVAL_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,RECORD_VERSION_NUMBER	NUMERIC(15,0)   ENCODE az64
,INITIAL_TEAM_TEMPLATE_ID	NUMERIC(15,0)   ENCODE az64
,JOB_BILL_RATE_SCHEDULE_ID	NUMERIC(15,0)   ENCODE az64
,EMP_BILL_RATE_SCHEDULE_ID	NUMERIC(15,0)   ENCODE az64
,COMPETENCE_MATCH_WT	NUMERIC(28,10)   ENCODE az64
,AVAILABILITY_MATCH_WT	NUMERIC(28,10)   ENCODE az64
,JOB_LEVEL_MATCH_WT	NUMERIC(28,10)   ENCODE az64
,ENABLE_AUTOMATED_SEARCH	 VARCHAR(1)   ENCODE lzo
,SEARCH_MIN_AVAILABILITY	NUMERIC(28,10)   ENCODE az64
,SEARCH_ORG_HIER_ID	NUMERIC(15,0)   ENCODE az64
,SEARCH_STARTING_ORG_ID	NUMERIC(15,0)   ENCODE az64
,SEARCH_COUNTRY_CODE	VARCHAR(2)   ENCODE lzo
,MIN_CAND_SCORE_REQD_FOR_NOM	NUMERIC(28,10)   ENCODE az64
,NON_LAB_STD_BILL_RT_SCH_ID	NUMERIC(15,0)   ENCODE az64
,INVPROC_CURRENCY_TYPE	VARCHAR(30)   ENCODE lzo
,REVPROC_CURRENCY_CODE	 VARCHAR(15)   ENCODE lzo
,PROJECT_BIL_RATE_DATE_CODE	VARCHAR(30)   ENCODE lzo
,PROJECT_BIL_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,PROJECT_BIL_RATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PROJECT_BIL_EXCHANGE_RATE	NUMERIC(28,10)   ENCODE az64
,PROJFUNC_CURRENCY_CODE	 VARCHAR(15)   ENCODE lzo
,PROJFUNC_BIL_RATE_DATE_CODE	VARCHAR(30)   ENCODE lzo
,PROJFUNC_BIL_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,PROJFUNC_BIL_RATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PROJFUNC_BIL_EXCHANGE_RATE	NUMERIC(28,10)   ENCODE az64
,FUNDING_RATE_DATE_CODE	VARCHAR(30)   ENCODE lzo
,FUNDING_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,FUNDING_RATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,FUNDING_EXCHANGE_RATE	NUMERIC(28,10)   ENCODE az64
,BASELINE_FUNDING_FLAG	 VARCHAR(1)   ENCODE lzo
,PROJFUNC_COST_RATE_TYPE	VARCHAR(30)   ENCODE lzo
,PROJFUNC_COST_RATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,INV_BY_BILL_TRANS_CURR_FLAG	 VARCHAR(1)   ENCODE lzo
,MULTI_CURRENCY_BILLING_FLAG	 VARCHAR(1)   ENCODE lzo
,SPLIT_COST_FROM_WORKPLAN_FLAG	 VARCHAR(1)   ENCODE lzo
,SPLIT_COST_FROM_BILL_FLAG	 VARCHAR(1)   ENCODE lzo
,ASSIGN_PRECEDES_TASK	 VARCHAR(1)   ENCODE lzo
,PRIORITY_CODE	VARCHAR(30)   ENCODE lzo
,RETN_BILLING_INV_FORMAT_ID	NUMERIC(15,0)   ENCODE az64
,RETN_ACCOUNTING_FLAG	 VARCHAR(1)   ENCODE lzo
,ADV_ACTION_SET_ID	NUMERIC(15,0)   ENCODE az64
,START_ADV_ACTION_SET_FLAG	 VARCHAR(1)   ENCODE lzo
,REVALUATE_FUNDING_FLAG	 VARCHAR(1)   ENCODE lzo
,INCLUDE_GAINS_LOSSES_FLAG	 VARCHAR(1)   ENCODE lzo
,TARGET_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,TARGET_FINISH_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,BASELINE_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,BASELINE_FINISH_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SCHEDULED_AS_OF_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,BASELINE_AS_OF_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LABOR_DISC_REASON_CODE	VARCHAR(30)   ENCODE lzo
,NON_LABOR_DISC_REASON_CODE	VARCHAR(30)   ENCODE lzo
,SECURITY_LEVEL	NUMERIC(28,10)   ENCODE az64
,ACTUAL_AS_OF_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SCHEDULED_DURATION	NUMERIC(28,10)   ENCODE az64
,BASELINE_DURATION	NUMERIC(28,10)   ENCODE az64
,ACTUAL_DURATION	NUMERIC(28,10)   ENCODE az64
,LONG_NAME	 VARCHAR(240)   ENCODE lzo
,BTC_COST_BASE_REV_CODE	VARCHAR(90)   ENCODE lzo
,ASSET_ALLOCATION_METHOD	VARCHAR(30)   ENCODE lzo
,CAPITAL_EVENT_PROCESSING	VARCHAR(30)   ENCODE lzo
,CINT_RATE_SCH_ID	NUMERIC(15,0)   ENCODE az64
,CINT_ELIGIBLE_FLAG	 VARCHAR(1)   ENCODE lzo
,CINT_STOP_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SYS_PROGRAM_FLAG	 VARCHAR(1)   ENCODE lzo
,STRUCTURE_SHARING_CODE	VARCHAR(30)   ENCODE lzo
,ENABLE_TOP_TASK_CUSTOMER_FLAG	 VARCHAR(1)   ENCODE lzo
,ENABLE_TOP_TASK_INV_MTH_FLAG	 VARCHAR(1)   ENCODE lzo
,REVENUE_ACCRUAL_METHOD	VARCHAR(30)   ENCODE lzo
,INVOICE_METHOD	VARCHAR(30)   ENCODE lzo
,PROJFUNC_ATTR_FOR_AR_FLAG	 VARCHAR(1)   ENCODE lzo
,PJI_SOURCE_FLAG	 VARCHAR(1)   ENCODE lzo
,ALLOW_MULTI_PROGRAM_ROLLUP	 VARCHAR(1)   ENCODE lzo
,PROJ_REQ_RES_FORMAT_ID	NUMERIC(15,0)   ENCODE az64
,PROJ_ASGMT_RES_FORMAT_ID	NUMERIC(15,0)   ENCODE az64
,FUNDING_APPROVAL_STATUS_CODE	VARCHAR(30)   ENCODE lzo
,REVTRANS_CURRENCY_TYPE	VARCHAR(30)   ENCODE lzo
,DATE_EFF_FUNDS_CONSUMPTION	 VARCHAR(1)   ENCODE lzo
,AR_REC_NOTIFY_FLAG	 VARCHAR(1)   ENCODE lzo
,AUTO_RELEASE_PWP_INV	 VARCHAR(1)   ENCODE lzo
,ADJ_ON_STD_INV VARCHAR(2)   ENCODE lzo
,ALT_LIQUIDATION_RATE_PER NUMERIC(17,2)   ENCODE az64
,BILL_GROUP_ID NUMERIC(15,0)   ENCODE az64
,BILL_LABOR_ACCRUAL VARCHAR(1)   ENCODE lzo
,BILLING_FUNDS_CHECK_FC_FLAG VARCHAR(1)   ENCODE lzo
,CBS_ENABLE_FLAG VARCHAR(1)   ENCODE lzo
,CBS_VERSION_ID NUMERIC(15,0)   ENCODE az64
,CONTRACT_ID NUMERIC(15,0)   ENCODE az64
,COST_PLUS_FIXED_FEE_FLAG VARCHAR(1)   ENCODE lzo
,DEFERRED_ROLLUP_ENABLED_FLAG VARCHAR(1)   ENCODE lzo
,DERIVE_BILLING_FROM_OKE_FLAG VARCHAR(1)   ENCODE lzo
,IC_LABOR_TP_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,IC_LABOR_TP_SCHEDULE_ID NUMERIC(22,0)   ENCODE az64
,IC_NL_TP_FIXED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,IC_NL_TP_SCHEDULE_ID NUMERIC(22,0)   ENCODE az64
,FEE_PERCENTAGE NUMERIC(17,2)   ENCODE az64
,FEE_RATE NUMERIC(22,5)   ENCODE az64
,FEE_RATE_SCHEDULE_ID NUMERIC(15,0)   ENCODE az64
,FEE_REVENUE_SCHEDULE_ID NUMERIC(15,0)   ENCODE az64
,INV_LINE_GROUP VARCHAR(30)   ENCODE lzo
,LABOR_FEE_RATE_CURRENCY_CODE VARCHAR(15)   ENCODE lzo
,LAST_SUMMARIZATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LIQUIDATION_RATE_PERCENTAGE NUMERIC(17,2)   ENCODE az64
,OLAP_GROUP NUMERIC(15,0)   ENCODE az64
,OLAP_TASK_ID NUMERIC(15,0)   ENCODE az64
,OVR_FEE_RATE_SCHEDULE_ID NUMERIC(15,0)   ENCODE az64
,PJT_ROLLUP_ENABLED_FLAG VARCHAR(1)   ENCODE lzo
,POBG_FLAG VARCHAR(1)   ENCODE lzo
,PROGRESS_PAYMENT_FLAG VARCHAR(1)   ENCODE lzo
,PROJ_SOV_FRM_CNTRT_FLAG VARCHAR(1)   ENCODE lzo
,PROJ_SOV_LEVEL VARCHAR(1)   ENCODE lzo
,RATE_PERCENTAGE NUMERIC(17,2)   ENCODE az64
,RMCS_INTEGRATION_FLAG VARCHAR(1)   ENCODE lzo
,SLA_ACC_END_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,WITHHOLD_AMOUNT NUMERIC(22,5)   ENCODE az64
,WP_BASELINE_VER_FLAG VARCHAR(1)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.PA_PROJECTS_ALL
(PROJECT_ID
,NAME
,SEGMENT1
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,PROJECT_TYPE
,CARRYING_OUT_ORGANIZATION_ID
,PUBLIC_SECTOR_FLAG
,PROJECT_STATUS_CODE
,DESCRIPTION
,START_DATE
,COMPLETION_DATE
,CLOSED_DATE
,DISTRIBUTION_RULE
,LABOR_INVOICE_FORMAT_ID
,NON_LABOR_INVOICE_FORMAT_ID
,RETENTION_INVOICE_FORMAT_ID
,RETENTION_PERCENTAGE
,BILLING_OFFSET
,BILLING_CYCLE
,LABOR_STD_BILL_RATE_SCHDL
,LABOR_BILL_RATE_ORG_ID
,LABOR_SCHEDULE_FIXED_DATE
,LABOR_SCHEDULE_DISCOUNT
,NON_LABOR_STD_BILL_RATE_SCHDL
,NON_LABOR_BILL_RATE_ORG_ID
,NON_LABOR_SCHEDULE_FIXED_DATE
,NON_LABOR_SCHEDULE_DISCOUNT
,LIMIT_TO_TXN_CONTROLS_FLAG
,PROJECT_LEVEL_FUNDING_FLAG
,INVOICE_COMMENT
,UNBILLED_RECEIVABLE_DR
,UNEARNED_REVENUE_CR
,REQUEST_ID
,PROGRAM_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_UPDATE_DATE
,SUMMARY_FLAG
,ENABLED_FLAG
,SEGMENT2
,SEGMENT3
,SEGMENT4
,SEGMENT5
,SEGMENT6
,SEGMENT7
,SEGMENT8
,SEGMENT9
,SEGMENT10
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,COST_IND_RATE_SCH_ID
,REV_IND_RATE_SCH_ID
,INV_IND_RATE_SCH_ID
,COST_IND_SCH_FIXED_DATE
,REV_IND_SCH_FIXED_DATE
,INV_IND_SCH_FIXED_DATE
,LABOR_SCH_TYPE
,NON_LABOR_SCH_TYPE
,OVR_COST_IND_RATE_SCH_ID
,OVR_REV_IND_RATE_SCH_ID
,OVR_INV_IND_RATE_SCH_ID
,TEMPLATE_FLAG
,VERIFICATION_DATE
,CREATED_FROM_PROJECT_ID
,TEMPLATE_START_DATE_ACTIVE
,TEMPLATE_END_DATE_ACTIVE
,ORG_ID
,PM_PRODUCT_CODE
,PM_PROJECT_REFERENCE
,ACTUAL_START_DATE
,ACTUAL_FINISH_DATE
,EARLY_START_DATE
,EARLY_FINISH_DATE
,LATE_START_DATE
,LATE_FINISH_DATE
,SCHEDULED_START_DATE
,SCHEDULED_FINISH_DATE
,BILLING_CYCLE_ID
,ADW_NOTIFY_FLAG
,WF_STATUS_CODE
,OUTPUT_TAX_CODE
,RETENTION_TAX_CODE
,PROJECT_CURRENCY_CODE
,ALLOW_CROSS_CHARGE_FLAG
,PROJECT_RATE_DATE
,PROJECT_RATE_TYPE
,CC_PROCESS_LABOR_FLAG
,LABOR_TP_SCHEDULE_ID
,LABOR_TP_FIXED_DATE
,CC_PROCESS_NL_FLAG
,NL_TP_SCHEDULE_ID
,NL_TP_FIXED_DATE
,CC_TAX_TASK_ID
,BILL_JOB_GROUP_ID
,COST_JOB_GROUP_ID
,ROLE_LIST_ID
,WORK_TYPE_ID
,CALENDAR_ID
,LOCATION_ID
,PROBABILITY_MEMBER_ID
,PROJECT_VALUE
,EXPECTED_APPROVAL_DATE
,RECORD_VERSION_NUMBER
,INITIAL_TEAM_TEMPLATE_ID
,JOB_BILL_RATE_SCHEDULE_ID
,EMP_BILL_RATE_SCHEDULE_ID
,COMPETENCE_MATCH_WT
,AVAILABILITY_MATCH_WT
,JOB_LEVEL_MATCH_WT
,ENABLE_AUTOMATED_SEARCH
,SEARCH_MIN_AVAILABILITY
,SEARCH_ORG_HIER_ID
,SEARCH_STARTING_ORG_ID
,SEARCH_COUNTRY_CODE
,MIN_CAND_SCORE_REQD_FOR_NOM
,NON_LAB_STD_BILL_RT_SCH_ID
,INVPROC_CURRENCY_TYPE
,REVPROC_CURRENCY_CODE
,PROJECT_BIL_RATE_DATE_CODE
,PROJECT_BIL_RATE_TYPE
,PROJECT_BIL_RATE_DATE
,PROJECT_BIL_EXCHANGE_RATE
,PROJFUNC_CURRENCY_CODE
,PROJFUNC_BIL_RATE_DATE_CODE
,PROJFUNC_BIL_RATE_TYPE
,PROJFUNC_BIL_RATE_DATE
,PROJFUNC_BIL_EXCHANGE_RATE
,FUNDING_RATE_DATE_CODE
,FUNDING_RATE_TYPE
,FUNDING_RATE_DATE
,FUNDING_EXCHANGE_RATE
,BASELINE_FUNDING_FLAG
,PROJFUNC_COST_RATE_TYPE
,PROJFUNC_COST_RATE_DATE
,INV_BY_BILL_TRANS_CURR_FLAG
,MULTI_CURRENCY_BILLING_FLAG
,SPLIT_COST_FROM_WORKPLAN_FLAG
,SPLIT_COST_FROM_BILL_FLAG
,ASSIGN_PRECEDES_TASK
,PRIORITY_CODE
,RETN_BILLING_INV_FORMAT_ID
,RETN_ACCOUNTING_FLAG
,ADV_ACTION_SET_ID
,START_ADV_ACTION_SET_FLAG
,REVALUATE_FUNDING_FLAG
,INCLUDE_GAINS_LOSSES_FLAG
,TARGET_START_DATE
,TARGET_FINISH_DATE
,BASELINE_START_DATE
,BASELINE_FINISH_DATE
,SCHEDULED_AS_OF_DATE
,BASELINE_AS_OF_DATE
,LABOR_DISC_REASON_CODE
,NON_LABOR_DISC_REASON_CODE
,SECURITY_LEVEL
,ACTUAL_AS_OF_DATE
,SCHEDULED_DURATION
,BASELINE_DURATION
,ACTUAL_DURATION
,LONG_NAME
,BTC_COST_BASE_REV_CODE
,ASSET_ALLOCATION_METHOD
,CAPITAL_EVENT_PROCESSING
,CINT_RATE_SCH_ID
,CINT_ELIGIBLE_FLAG
,CINT_STOP_DATE
,SYS_PROGRAM_FLAG
,STRUCTURE_SHARING_CODE
,ENABLE_TOP_TASK_CUSTOMER_FLAG
,ENABLE_TOP_TASK_INV_MTH_FLAG
,REVENUE_ACCRUAL_METHOD
,INVOICE_METHOD
,PROJFUNC_ATTR_FOR_AR_FLAG
,PJI_SOURCE_FLAG
,ALLOW_MULTI_PROGRAM_ROLLUP
,PROJ_REQ_RES_FORMAT_ID
,PROJ_ASGMT_RES_FORMAT_ID
,FUNDING_APPROVAL_STATUS_CODE
,REVTRANS_CURRENCY_TYPE
,DATE_EFF_FUNDS_CONSUMPTION
,AR_REC_NOTIFY_FLAG
,AUTO_RELEASE_PWP_INV
,ADJ_ON_STD_INV
,ALT_LIQUIDATION_RATE_PER
,BILL_GROUP_ID
,BILL_LABOR_ACCRUAL
,BILLING_FUNDS_CHECK_FC_FLAG
,CBS_ENABLE_FLAG
,CBS_VERSION_ID
,CONTRACT_ID
,COST_PLUS_FIXED_FEE_FLAG
,DEFERRED_ROLLUP_ENABLED_FLAG
,DERIVE_BILLING_FROM_OKE_FLAG
,IC_LABOR_TP_FIXED_DATE
,IC_LABOR_TP_SCHEDULE_ID
,IC_NL_TP_FIXED_DATE
,IC_NL_TP_SCHEDULE_ID
,FEE_PERCENTAGE
,FEE_RATE
,FEE_RATE_SCHEDULE_ID
,FEE_REVENUE_SCHEDULE_ID
,INV_LINE_GROUP
,LABOR_FEE_RATE_CURRENCY_CODE
,LAST_SUMMARIZATION_DATE
,LIQUIDATION_RATE_PERCENTAGE
,OLAP_GROUP
,OLAP_TASK_ID
,OVR_FEE_RATE_SCHEDULE_ID
,PJT_ROLLUP_ENABLED_FLAG
,POBG_FLAG
,PROGRESS_PAYMENT_FLAG
,PROJ_SOV_FRM_CNTRT_FLAG
,PROJ_SOV_LEVEL
,RATE_PERCENTAGE
,RMCS_INTEGRATION_FLAG
,SLA_ACC_END_DATE
,WITHHOLD_AMOUNT
,WP_BASELINE_VER_FLAG
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date)
(
select
PROJECT_ID
,NAME
,SEGMENT1
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,PROJECT_TYPE
,CARRYING_OUT_ORGANIZATION_ID
,PUBLIC_SECTOR_FLAG
,PROJECT_STATUS_CODE
,DESCRIPTION
,START_DATE
,COMPLETION_DATE
,CLOSED_DATE
,DISTRIBUTION_RULE
,LABOR_INVOICE_FORMAT_ID
,NON_LABOR_INVOICE_FORMAT_ID
,RETENTION_INVOICE_FORMAT_ID
,RETENTION_PERCENTAGE
,BILLING_OFFSET
,BILLING_CYCLE
,LABOR_STD_BILL_RATE_SCHDL
,LABOR_BILL_RATE_ORG_ID
,LABOR_SCHEDULE_FIXED_DATE
,LABOR_SCHEDULE_DISCOUNT
,NON_LABOR_STD_BILL_RATE_SCHDL
,NON_LABOR_BILL_RATE_ORG_ID
,NON_LABOR_SCHEDULE_FIXED_DATE
,NON_LABOR_SCHEDULE_DISCOUNT
,LIMIT_TO_TXN_CONTROLS_FLAG
,PROJECT_LEVEL_FUNDING_FLAG
,INVOICE_COMMENT
,UNBILLED_RECEIVABLE_DR
,UNEARNED_REVENUE_CR
,REQUEST_ID
,PROGRAM_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_UPDATE_DATE
,SUMMARY_FLAG
,ENABLED_FLAG
,SEGMENT2
,SEGMENT3
,SEGMENT4
,SEGMENT5
,SEGMENT6
,SEGMENT7
,SEGMENT8
,SEGMENT9
,SEGMENT10
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,COST_IND_RATE_SCH_ID
,REV_IND_RATE_SCH_ID
,INV_IND_RATE_SCH_ID
,COST_IND_SCH_FIXED_DATE
,REV_IND_SCH_FIXED_DATE
,INV_IND_SCH_FIXED_DATE
,LABOR_SCH_TYPE
,NON_LABOR_SCH_TYPE
,OVR_COST_IND_RATE_SCH_ID
,OVR_REV_IND_RATE_SCH_ID
,OVR_INV_IND_RATE_SCH_ID
,TEMPLATE_FLAG
,VERIFICATION_DATE
,CREATED_FROM_PROJECT_ID
,TEMPLATE_START_DATE_ACTIVE
,TEMPLATE_END_DATE_ACTIVE
,ORG_ID
,PM_PRODUCT_CODE
,PM_PROJECT_REFERENCE
,ACTUAL_START_DATE
,ACTUAL_FINISH_DATE
,EARLY_START_DATE
,EARLY_FINISH_DATE
,LATE_START_DATE
,LATE_FINISH_DATE
,SCHEDULED_START_DATE
,SCHEDULED_FINISH_DATE
,BILLING_CYCLE_ID
,ADW_NOTIFY_FLAG
,WF_STATUS_CODE
,OUTPUT_TAX_CODE
,RETENTION_TAX_CODE
,PROJECT_CURRENCY_CODE
,ALLOW_CROSS_CHARGE_FLAG
,PROJECT_RATE_DATE
,PROJECT_RATE_TYPE
,CC_PROCESS_LABOR_FLAG
,LABOR_TP_SCHEDULE_ID
,LABOR_TP_FIXED_DATE
,CC_PROCESS_NL_FLAG
,NL_TP_SCHEDULE_ID
,NL_TP_FIXED_DATE
,CC_TAX_TASK_ID
,BILL_JOB_GROUP_ID
,COST_JOB_GROUP_ID
,ROLE_LIST_ID
,WORK_TYPE_ID
,CALENDAR_ID
,LOCATION_ID
,PROBABILITY_MEMBER_ID
,PROJECT_VALUE
,EXPECTED_APPROVAL_DATE
,RECORD_VERSION_NUMBER
,INITIAL_TEAM_TEMPLATE_ID
,JOB_BILL_RATE_SCHEDULE_ID
,EMP_BILL_RATE_SCHEDULE_ID
,COMPETENCE_MATCH_WT
,AVAILABILITY_MATCH_WT
,JOB_LEVEL_MATCH_WT
,ENABLE_AUTOMATED_SEARCH
,SEARCH_MIN_AVAILABILITY
,SEARCH_ORG_HIER_ID
,SEARCH_STARTING_ORG_ID
,SEARCH_COUNTRY_CODE
,MIN_CAND_SCORE_REQD_FOR_NOM
,NON_LAB_STD_BILL_RT_SCH_ID
,INVPROC_CURRENCY_TYPE
,REVPROC_CURRENCY_CODE
,PROJECT_BIL_RATE_DATE_CODE
,PROJECT_BIL_RATE_TYPE
,PROJECT_BIL_RATE_DATE
,PROJECT_BIL_EXCHANGE_RATE
,PROJFUNC_CURRENCY_CODE
,PROJFUNC_BIL_RATE_DATE_CODE
,PROJFUNC_BIL_RATE_TYPE
,PROJFUNC_BIL_RATE_DATE
,PROJFUNC_BIL_EXCHANGE_RATE
,FUNDING_RATE_DATE_CODE
,FUNDING_RATE_TYPE
,FUNDING_RATE_DATE
,FUNDING_EXCHANGE_RATE
,BASELINE_FUNDING_FLAG
,PROJFUNC_COST_RATE_TYPE
,PROJFUNC_COST_RATE_DATE
,INV_BY_BILL_TRANS_CURR_FLAG
,MULTI_CURRENCY_BILLING_FLAG
,SPLIT_COST_FROM_WORKPLAN_FLAG
,SPLIT_COST_FROM_BILL_FLAG
,ASSIGN_PRECEDES_TASK
,PRIORITY_CODE
,RETN_BILLING_INV_FORMAT_ID
,RETN_ACCOUNTING_FLAG
,ADV_ACTION_SET_ID
,START_ADV_ACTION_SET_FLAG
,REVALUATE_FUNDING_FLAG
,INCLUDE_GAINS_LOSSES_FLAG
,TARGET_START_DATE
,TARGET_FINISH_DATE
,BASELINE_START_DATE
,BASELINE_FINISH_DATE
,SCHEDULED_AS_OF_DATE
,BASELINE_AS_OF_DATE
,LABOR_DISC_REASON_CODE
,NON_LABOR_DISC_REASON_CODE
,SECURITY_LEVEL
,ACTUAL_AS_OF_DATE
,SCHEDULED_DURATION
,BASELINE_DURATION
,ACTUAL_DURATION
,LONG_NAME
,BTC_COST_BASE_REV_CODE
,ASSET_ALLOCATION_METHOD
,CAPITAL_EVENT_PROCESSING
,CINT_RATE_SCH_ID
,CINT_ELIGIBLE_FLAG
,CINT_STOP_DATE
,SYS_PROGRAM_FLAG
,STRUCTURE_SHARING_CODE
,ENABLE_TOP_TASK_CUSTOMER_FLAG
,ENABLE_TOP_TASK_INV_MTH_FLAG
,REVENUE_ACCRUAL_METHOD
,INVOICE_METHOD
,PROJFUNC_ATTR_FOR_AR_FLAG
,PJI_SOURCE_FLAG
,ALLOW_MULTI_PROGRAM_ROLLUP
,PROJ_REQ_RES_FORMAT_ID
,PROJ_ASGMT_RES_FORMAT_ID
,FUNDING_APPROVAL_STATUS_CODE
,REVTRANS_CURRENCY_TYPE
,DATE_EFF_FUNDS_CONSUMPTION
,AR_REC_NOTIFY_FLAG
,AUTO_RELEASE_PWP_INV
,ADJ_ON_STD_INV
,ALT_LIQUIDATION_RATE_PER
,BILL_GROUP_ID
,BILL_LABOR_ACCRUAL
,BILLING_FUNDS_CHECK_FC_FLAG
,CBS_ENABLE_FLAG
,CBS_VERSION_ID
,CONTRACT_ID
,COST_PLUS_FIXED_FEE_FLAG
,DEFERRED_ROLLUP_ENABLED_FLAG
,DERIVE_BILLING_FROM_OKE_FLAG
,IC_LABOR_TP_FIXED_DATE
,IC_LABOR_TP_SCHEDULE_ID
,IC_NL_TP_FIXED_DATE
,IC_NL_TP_SCHEDULE_ID
,FEE_PERCENTAGE
,FEE_RATE
,FEE_RATE_SCHEDULE_ID
,FEE_REVENUE_SCHEDULE_ID
,INV_LINE_GROUP
,LABOR_FEE_RATE_CURRENCY_CODE
,LAST_SUMMARIZATION_DATE
,LIQUIDATION_RATE_PERCENTAGE
,OLAP_GROUP
,OLAP_TASK_ID
,OVR_FEE_RATE_SCHEDULE_ID
,PJT_ROLLUP_ENABLED_FLAG
,POBG_FLAG
,PROGRESS_PAYMENT_FLAG
,PROJ_SOV_FRM_CNTRT_FLAG
,PROJ_SOV_LEVEL
,RATE_PERCENTAGE
,RMCS_INTEGRATION_FLAG
,SLA_ACC_END_DATE
,WITHHOLD_AMOUNT
,WP_BASELINE_VER_FLAG
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID 
,kca_seq_date
from
bec_ods_stg.PA_PROJECTS_ALL);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='pa_projects_all'; 

commit;