/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

drop table if exists bec_ods.PER_ALL_PEOPLE_F;

CREATE TABLE IF NOT EXISTS bec_ods.PER_ALL_PEOPLE_F
(
PERSON_ID	NUMERIC(10,0)   ENCODE az64
,EFFECTIVE_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,EFFECTIVE_END_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,BUSINESS_GROUP_ID	NUMERIC(15,0)   ENCODE az64
,PERSON_TYPE_ID	NUMERIC(15,0)   ENCODE az64
,LAST_NAME	VARCHAR(150)   ENCODE lzo
,START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,APPLICANT_NUMBER	VARCHAR(30)   ENCODE lzo
,COMMENT_ID	NUMERIC(15,0)   ENCODE az64
,CURRENT_APPLICANT_FLAG	VARCHAR(30)   ENCODE lzo
,CURRENT_EMP_OR_APL_FLAG	VARCHAR(30)   ENCODE lzo
,CURRENT_EMPLOYEE_FLAG	VARCHAR(30)   ENCODE lzo
,DATE_EMPLOYEE_DATA_VERIFIED TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,DATE_OF_BIRTH TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,EMAIL_ADDRESS	VARCHAR(240)   ENCODE lzo
,EMPLOYEE_NUMBER	VARCHAR(30)   ENCODE lzo
,EXPENSE_CHECK_SEND_TO_ADDRESS	VARCHAR(30)   ENCODE lzo
,FIRST_NAME	VARCHAR(150)   ENCODE lzo
,FULL_NAME	VARCHAR(240)   ENCODE lzo
,KNOWN_AS	VARCHAR(80)   ENCODE lzo
,MARITAL_STATUS	VARCHAR(30)   ENCODE lzo
,MIDDLE_NAMES	VARCHAR(60)   ENCODE lzo
,NATIONALITY	VARCHAR(30)   ENCODE lzo
,NATIONAL_IDENTIFIER	VARCHAR(30)   ENCODE lzo
,PREVIOUS_LAST_NAME	VARCHAR(150)   ENCODE lzo
,REGISTERED_DISABLED_FLAG	VARCHAR(30)   ENCODE lzo
,SEX	VARCHAR(30)   ENCODE lzo
,TITLE	VARCHAR(30)   ENCODE lzo
,VENDOR_ID	NUMERIC(15,0)   ENCODE az64
,WORK_TELEPHONE	VARCHAR(60)   ENCODE lzo
,REQUEST_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_ID	NUMERIC(15,0)   ENCODE az64
,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,ATTRIBUTE_CATEGORY	VARCHAR(30)   ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE16	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE17	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE18	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE19	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE20	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE21	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE22	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE23	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE24	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE25	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE26	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE27	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE28	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE29	VARCHAR(150)   ENCODE lzo
,ATTRIBUTE30	VARCHAR(150)   ENCODE lzo
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PER_INFORMATION_CATEGORY	VARCHAR(30)   ENCODE lzo
,PER_INFORMATION1	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION2	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION3	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION4	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION5	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION6	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION7	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION8	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION9	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION10	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION11	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION12	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION13	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION14	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION15	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION16	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION17	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION18	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION19	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION20	VARCHAR(150)   ENCODE lzo
,BACKGROUND_CHECK_STATUS	VARCHAR(30)   ENCODE lzo
,BACKGROUND_DATE_CHECK TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,BLOOD_TYPE	VARCHAR(30)   ENCODE lzo
,CORRESPONDENCE_LANGUAGE	VARCHAR(30)   ENCODE lzo
,FAST_PATH_EMPLOYEE	VARCHAR(30)   ENCODE lzo
,FTE_CAPACITY	 NUMERIC(28,10)   ENCODE az64
,HOLD_APPLICANT_DATE_UNTIL TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,HONORS	VARCHAR(45)   ENCODE lzo
,INTERNAL_LOCATION	VARCHAR(45)   ENCODE lzo
,LAST_MEDICAL_TEST_BY	VARCHAR(60)   ENCODE lzo
,LAST_MEDICAL_TEST_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,MAILSTOP	VARCHAR(45)   ENCODE lzo
,OFFICE_NUMBER	VARCHAR(45)   ENCODE lzo
,ON_MILITARY_SERVICE	VARCHAR(30)   ENCODE lzo
,ORDER_NAME	VARCHAR(240)   ENCODE lzo
,PRE_NAME_ADJUNCT	VARCHAR(30)   ENCODE lzo
,PROJECTED_START_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,REHIRE_AUTHORIZOR	VARCHAR(60)   ENCODE lzo
,REHIRE_RECOMMENDATION	VARCHAR(30)   ENCODE lzo
,RESUME_EXISTS	VARCHAR(30)   ENCODE lzo
,RESUME_LAST_UPDATED TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,SECOND_PASSPORT_EXISTS	VARCHAR(30)   ENCODE lzo
,STUDENT_STATUS	VARCHAR(30)   ENCODE lzo
,SUFFIX	VARCHAR(30)   ENCODE lzo
,WORK_SCHEDULE	VARCHAR(30)   ENCODE lzo
,PER_INFORMATION21	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION22	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION23	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION24	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION25	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION26	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION27	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION28	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION29	VARCHAR(150)   ENCODE lzo
,PER_INFORMATION30	VARCHAR(150)   ENCODE lzo
,OBJECT_VERSION_NUMBER	NUMERIC(9,0)   ENCODE az64
,DATE_OF_DEATH TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,REHIRE_REASON	VARCHAR(60)   ENCODE lzo
,COORD_BEN_MED_PLN_NO	VARCHAR(30)   ENCODE lzo
,COORD_BEN_NO_CVG_FLAG	VARCHAR(30)   ENCODE lzo
,DPDNT_ADOPTION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,DPDNT_VLNTRY_SVCE_FLAG	VARCHAR(30)   ENCODE lzo
,RECEIPT_OF_DEATH_CERT_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,USES_TOBACCO_FLAG	VARCHAR(30)   ENCODE lzo
,BENEFIT_GROUP_ID	NUMERIC(15,0)   ENCODE az64
,ORIGINAL_DATE_OF_HIRE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,TOWN_OF_BIRTH	VARCHAR(90)   ENCODE lzo
,REGION_OF_BIRTH	VARCHAR(90)   ENCODE lzo
,COUNTRY_OF_BIRTH	VARCHAR(90)   ENCODE lzo
,GLOBAL_PERSON_ID	VARCHAR(30)   ENCODE lzo
,COORD_BEN_MED_PL_NAME	VARCHAR(80)   ENCODE lzo
,COORD_BEN_MED_INSR_CRR_NAME	VARCHAR(80)   ENCODE lzo
,COORD_BEN_MED_INSR_CRR_IDENT	VARCHAR(80)   ENCODE lzo
,COORD_BEN_MED_EXT_ER	VARCHAR(80)   ENCODE lzo
,COORD_BEN_MED_CVG_STRT_DT TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,COORD_BEN_MED_CVG_END_DT TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PARTY_ID	NUMERIC(15,0)   ENCODE az64
,NPW_NUMBER	VARCHAR(30)   ENCODE lzo
,CURRENT_NPW_FLAG	VARCHAR(30)   ENCODE lzo
,GLOBAL_NAME	VARCHAR(240)   ENCODE lzo
,LOCAL_NAME	VARCHAR(240)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.PER_ALL_PEOPLE_F
(PERSON_ID
,EFFECTIVE_START_DATE
,EFFECTIVE_END_DATE
,BUSINESS_GROUP_ID
,PERSON_TYPE_ID
,LAST_NAME
,START_DATE
,APPLICANT_NUMBER
,COMMENT_ID
,CURRENT_APPLICANT_FLAG
,CURRENT_EMP_OR_APL_FLAG
,CURRENT_EMPLOYEE_FLAG
,DATE_EMPLOYEE_DATA_VERIFIED
,DATE_OF_BIRTH
,EMAIL_ADDRESS
,EMPLOYEE_NUMBER
,EXPENSE_CHECK_SEND_TO_ADDRESS
,FIRST_NAME
,FULL_NAME
,KNOWN_AS
,MARITAL_STATUS
,MIDDLE_NAMES
,NATIONALITY
,NATIONAL_IDENTIFIER
,PREVIOUS_LAST_NAME
,REGISTERED_DISABLED_FLAG
,SEX
,TITLE
,VENDOR_ID
,WORK_TELEPHONE
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,ATTRIBUTE21
,ATTRIBUTE22
,ATTRIBUTE23
,ATTRIBUTE24
,ATTRIBUTE25
,ATTRIBUTE26
,ATTRIBUTE27
,ATTRIBUTE28
,ATTRIBUTE29
,ATTRIBUTE30
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,CREATED_BY
,CREATION_DATE
,PER_INFORMATION_CATEGORY
,PER_INFORMATION1
,PER_INFORMATION2
,PER_INFORMATION3
,PER_INFORMATION4
,PER_INFORMATION5
,PER_INFORMATION6
,PER_INFORMATION7
,PER_INFORMATION8
,PER_INFORMATION9
,PER_INFORMATION10
,PER_INFORMATION11
,PER_INFORMATION12
,PER_INFORMATION13
,PER_INFORMATION14
,PER_INFORMATION15
,PER_INFORMATION16
,PER_INFORMATION17
,PER_INFORMATION18
,PER_INFORMATION19
,PER_INFORMATION20
,BACKGROUND_CHECK_STATUS
,BACKGROUND_DATE_CHECK
,BLOOD_TYPE
,CORRESPONDENCE_LANGUAGE
,FAST_PATH_EMPLOYEE
,FTE_CAPACITY
,HOLD_APPLICANT_DATE_UNTIL
,HONORS
,INTERNAL_LOCATION
,LAST_MEDICAL_TEST_BY
,LAST_MEDICAL_TEST_DATE
,MAILSTOP
,OFFICE_NUMBER
,ON_MILITARY_SERVICE
,ORDER_NAME
,PRE_NAME_ADJUNCT
,PROJECTED_START_DATE
,REHIRE_AUTHORIZOR
,REHIRE_RECOMMENDATION
,RESUME_EXISTS
,RESUME_LAST_UPDATED
,SECOND_PASSPORT_EXISTS
,STUDENT_STATUS
,SUFFIX
,WORK_SCHEDULE
,PER_INFORMATION21
,PER_INFORMATION22
,PER_INFORMATION23
,PER_INFORMATION24
,PER_INFORMATION25
,PER_INFORMATION26
,PER_INFORMATION27
,PER_INFORMATION28
,PER_INFORMATION29
,PER_INFORMATION30
,OBJECT_VERSION_NUMBER
,DATE_OF_DEATH
,REHIRE_REASON
,COORD_BEN_MED_PLN_NO
,COORD_BEN_NO_CVG_FLAG
,DPDNT_ADOPTION_DATE
,DPDNT_VLNTRY_SVCE_FLAG
,RECEIPT_OF_DEATH_CERT_DATE
,USES_TOBACCO_FLAG
,BENEFIT_GROUP_ID
,ORIGINAL_DATE_OF_HIRE
,TOWN_OF_BIRTH
,REGION_OF_BIRTH
,COUNTRY_OF_BIRTH
,GLOBAL_PERSON_ID
,COORD_BEN_MED_PL_NAME
,COORD_BEN_MED_INSR_CRR_NAME
,COORD_BEN_MED_INSR_CRR_IDENT
,COORD_BEN_MED_EXT_ER
,COORD_BEN_MED_CVG_STRT_DT
,COORD_BEN_MED_CVG_END_DT
,PARTY_ID
,NPW_NUMBER
,CURRENT_NPW_FLAG
,GLOBAL_NAME
,LOCAL_NAME
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date
)
(
select
PERSON_ID
,EFFECTIVE_START_DATE
,EFFECTIVE_END_DATE
,BUSINESS_GROUP_ID
,PERSON_TYPE_ID
,LAST_NAME
,START_DATE
,APPLICANT_NUMBER
,COMMENT_ID
,CURRENT_APPLICANT_FLAG
,CURRENT_EMP_OR_APL_FLAG
,CURRENT_EMPLOYEE_FLAG
,DATE_EMPLOYEE_DATA_VERIFIED
,DATE_OF_BIRTH
,EMAIL_ADDRESS
,EMPLOYEE_NUMBER
,EXPENSE_CHECK_SEND_TO_ADDRESS
,FIRST_NAME
,FULL_NAME
,KNOWN_AS
,MARITAL_STATUS
,MIDDLE_NAMES
,NATIONALITY
,NATIONAL_IDENTIFIER
,PREVIOUS_LAST_NAME
,REGISTERED_DISABLED_FLAG
,SEX
,TITLE
,VENDOR_ID
,WORK_TELEPHONE
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE16
,ATTRIBUTE17
,ATTRIBUTE18
,ATTRIBUTE19
,ATTRIBUTE20
,ATTRIBUTE21
,ATTRIBUTE22
,ATTRIBUTE23
,ATTRIBUTE24
,ATTRIBUTE25
,ATTRIBUTE26
,ATTRIBUTE27
,ATTRIBUTE28
,ATTRIBUTE29
,ATTRIBUTE30
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,CREATED_BY
,CREATION_DATE
,PER_INFORMATION_CATEGORY
,PER_INFORMATION1
,PER_INFORMATION2
,PER_INFORMATION3
,PER_INFORMATION4
,PER_INFORMATION5
,PER_INFORMATION6
,PER_INFORMATION7
,PER_INFORMATION8
,PER_INFORMATION9
,PER_INFORMATION10
,PER_INFORMATION11
,PER_INFORMATION12
,PER_INFORMATION13
,PER_INFORMATION14
,PER_INFORMATION15
,PER_INFORMATION16
,PER_INFORMATION17
,PER_INFORMATION18
,PER_INFORMATION19
,PER_INFORMATION20
,BACKGROUND_CHECK_STATUS
,BACKGROUND_DATE_CHECK
,BLOOD_TYPE
,CORRESPONDENCE_LANGUAGE
,FAST_PATH_EMPLOYEE
,FTE_CAPACITY
,HOLD_APPLICANT_DATE_UNTIL
,HONORS
,INTERNAL_LOCATION
,LAST_MEDICAL_TEST_BY
,LAST_MEDICAL_TEST_DATE
,MAILSTOP
,OFFICE_NUMBER
,ON_MILITARY_SERVICE
,ORDER_NAME
,PRE_NAME_ADJUNCT
,PROJECTED_START_DATE
,REHIRE_AUTHORIZOR
,REHIRE_RECOMMENDATION
,RESUME_EXISTS
,RESUME_LAST_UPDATED
,SECOND_PASSPORT_EXISTS
,STUDENT_STATUS
,SUFFIX
,WORK_SCHEDULE
,PER_INFORMATION21
,PER_INFORMATION22
,PER_INFORMATION23
,PER_INFORMATION24
,PER_INFORMATION25
,PER_INFORMATION26
,PER_INFORMATION27
,PER_INFORMATION28
,PER_INFORMATION29
,PER_INFORMATION30
,OBJECT_VERSION_NUMBER
,DATE_OF_DEATH
,REHIRE_REASON
,COORD_BEN_MED_PLN_NO
,COORD_BEN_NO_CVG_FLAG
,DPDNT_ADOPTION_DATE
,DPDNT_VLNTRY_SVCE_FLAG
,RECEIPT_OF_DEATH_CERT_DATE
,USES_TOBACCO_FLAG
,BENEFIT_GROUP_ID
,ORIGINAL_DATE_OF_HIRE
,TOWN_OF_BIRTH
,REGION_OF_BIRTH
,COUNTRY_OF_BIRTH
,GLOBAL_PERSON_ID
,COORD_BEN_MED_PL_NAME
,COORD_BEN_MED_INSR_CRR_NAME
,COORD_BEN_MED_INSR_CRR_IDENT
,COORD_BEN_MED_EXT_ER
,COORD_BEN_MED_CVG_STRT_DT
,COORD_BEN_MED_CVG_END_DT
,PARTY_ID
,NPW_NUMBER
,CURRENT_NPW_FLAG
,GLOBAL_NAME
,LOCAL_NAME
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID 
,kca_seq_date
from 
bec_ods_stg.PER_ALL_PEOPLE_F);

end;

update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='per_all_people_f'; 

commit;