/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;

DROP TABLE if exists bec_ods.PO_LINE_LOCATIONS_ALL;
CREATE TABLE IF NOT EXISTS bec_ods.PO_LINE_LOCATIONS_ALL
(
	line_location_id NUMERIC(15,0)   ENCODE az64
	,last_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_updated_by NUMERIC(15,0)   ENCODE az64
	,po_header_id NUMERIC(15,0)   ENCODE az64
	,po_line_id NUMERIC(15,0)   ENCODE az64
	,last_update_login NUMERIC(15,0)   ENCODE az64
	,creation_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,created_by NUMERIC(15,0)   ENCODE az64
	,quantity NUMERIC(28,10)   ENCODE az64
	,quantity_received NUMERIC(28,10)   ENCODE az64
	,quantity_accepted NUMERIC(28,10)   ENCODE az64
	,quantity_rejected NUMERIC(28,10)   ENCODE az64
	,quantity_billed NUMERIC(28,10)   ENCODE az64
	,quantity_cancelled NUMERIC(28,10)   ENCODE az64
	,unit_meas_lookup_code VARCHAR(25)   ENCODE lzo
	,po_release_id NUMERIC(15,0)   ENCODE az64
	,ship_to_location_id NUMERIC(15,0)   ENCODE az64
	,ship_via_lookup_code VARCHAR(25)   ENCODE lzo
	,need_by_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,promised_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_accept_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,price_override NUMERIC(28,10)   ENCODE az64
	,encumbered_flag VARCHAR(1)   ENCODE lzo
	,encumbered_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,unencumbered_quantity NUMERIC(28,10)   ENCODE az64
	,fob_lookup_code VARCHAR(25)   ENCODE lzo
	,freight_terms_lookup_code VARCHAR(25)   ENCODE lzo
	,taxable_flag VARCHAR(1)   ENCODE lzo
	,tax_name VARCHAR(30)   ENCODE lzo
	,estimated_tax_amount NUMERIC(28,10)   ENCODE az64
	,from_header_id NUMERIC(15,0)   ENCODE az64
	,from_line_id NUMERIC(15,0)   ENCODE az64
	,from_line_location_id NUMERIC(15,0)   ENCODE az64
	,start_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,end_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,lead_time NUMERIC(15,0)   ENCODE az64
	,lead_time_unit VARCHAR(25)   ENCODE lzo
	,price_discount NUMERIC(28,10)   ENCODE az64
	,terms_id NUMERIC(15,0)   ENCODE az64
	,approved_flag VARCHAR(1)   ENCODE lzo
	,approved_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,closed_flag VARCHAR(1)   ENCODE lzo
	,cancel_flag VARCHAR(1)   ENCODE lzo
	,cancelled_by NUMERIC(9,0)   ENCODE az64
	,cancel_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,cancel_reason VARCHAR(240)   ENCODE lzo
	,firm_status_lookup_code VARCHAR(25)   ENCODE lzo
	,firm_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,attribute_category VARCHAR(30)   ENCODE lzo
	,attribute1 VARCHAR(150)   ENCODE lzo
	,attribute2 VARCHAR(150)   ENCODE lzo
	,attribute3 VARCHAR(150)   ENCODE lzo
	,attribute4 VARCHAR(150)   ENCODE lzo
	,attribute5 VARCHAR(150)   ENCODE lzo
	,attribute6 VARCHAR(150)   ENCODE lzo
	,attribute7 VARCHAR(150)   ENCODE lzo
	,attribute8 VARCHAR(150)   ENCODE lzo
	,attribute9 VARCHAR(150)   ENCODE lzo
	,attribute10 VARCHAR(150)   ENCODE lzo
	,unit_of_measure_class VARCHAR(25)   ENCODE lzo
	,encumber_now VARCHAR(1)   ENCODE lzo
	,attribute11 VARCHAR(150)   ENCODE lzo
	,attribute12 VARCHAR(150)   ENCODE lzo
	,attribute13 VARCHAR(150)   ENCODE lzo
	,attribute14 VARCHAR(150)   ENCODE lzo
	,attribute15 VARCHAR(150)   ENCODE lzo
	,inspection_required_flag VARCHAR(1)   ENCODE lzo
	,receipt_required_flag VARCHAR(1)   ENCODE lzo
	,qty_rcv_tolerance NUMERIC(28,10)   ENCODE az64
	,qty_rcv_exception_code VARCHAR(25)   ENCODE lzo
	,enforce_ship_to_location_code VARCHAR(25)   ENCODE lzo
	,allow_substitute_receipts_flag VARCHAR(1)   ENCODE lzo
	,days_early_receipt_allowed NUMERIC(15,0)   ENCODE az64
	,days_late_receipt_allowed NUMERIC(15,0)   ENCODE az64
	,receipt_days_exception_code VARCHAR(25)   ENCODE lzo
	,invoice_close_tolerance NUMERIC(15,0)   ENCODE az64
	,receive_close_tolerance NUMERIC(15,0)   ENCODE az64
	,ship_to_organization_id NUMERIC(15,0)   ENCODE az64
	,shipment_num NUMERIC(15,0)   ENCODE az64
	,source_shipment_id NUMERIC(15,0)   ENCODE az64
	,shipment_type VARCHAR(25)   ENCODE lzo
	,closed_code VARCHAR(30)   ENCODE lzo
	,request_id NUMERIC(15,0)   ENCODE az64
	,program_application_id NUMERIC(15,0)   ENCODE az64
	,program_id NUMERIC(15,0)   ENCODE az64
	,program_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,ussgl_transaction_code VARCHAR(30)   ENCODE lzo
	,government_context VARCHAR(30)   ENCODE lzo
	,receiving_routing_id NUMERIC(15,0)   ENCODE az64
	,accrue_on_receipt_flag VARCHAR(1)   ENCODE lzo
	,closed_reason VARCHAR(240)   ENCODE lzo
	,closed_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,closed_by NUMERIC(9,0)   ENCODE az64
	,org_id NUMERIC(15,0)   ENCODE az64
	,quantity_shipped NUMERIC(28,10)   ENCODE az64
	,global_attribute_category VARCHAR(150)   ENCODE lzo
	,global_attribute1 VARCHAR(150)   ENCODE lzo
	,global_attribute2 VARCHAR(150)   ENCODE lzo
	,global_attribute3 VARCHAR(150)   ENCODE lzo
	,global_attribute4 VARCHAR(150)   ENCODE lzo
	,global_attribute5 VARCHAR(150)   ENCODE lzo
	,global_attribute6 VARCHAR(150)   ENCODE lzo
	,global_attribute7 VARCHAR(150)   ENCODE lzo
	,global_attribute8 VARCHAR(150)   ENCODE lzo
	,global_attribute9 VARCHAR(150)   ENCODE lzo
	,global_attribute10 VARCHAR(150)   ENCODE lzo
	,global_attribute11 VARCHAR(150)   ENCODE lzo
	,global_attribute12 VARCHAR(150)   ENCODE lzo
	,global_attribute13 VARCHAR(150)   ENCODE lzo
	,global_attribute14 VARCHAR(150)   ENCODE lzo
	,global_attribute15 VARCHAR(150)   ENCODE lzo
	,global_attribute16 VARCHAR(150)   ENCODE lzo
	,global_attribute17 VARCHAR(150)   ENCODE lzo
	,global_attribute18 VARCHAR(150)   ENCODE lzo
	,global_attribute19 VARCHAR(150)   ENCODE lzo
	,global_attribute20 VARCHAR(150)   ENCODE lzo
	,country_of_origin_code VARCHAR(2)   ENCODE lzo
	,tax_user_override_flag VARCHAR(1)   ENCODE lzo
	,match_option VARCHAR(25)   ENCODE lzo
	,tax_code_id NUMERIC(15,0)   ENCODE az64
	,calculate_tax_flag VARCHAR(1)   ENCODE lzo
	,change_promised_date_reason VARCHAR(240)   ENCODE lzo
	,note_to_receiver VARCHAR(480)   ENCODE lzo
	,secondary_quantity NUMERIC(28,10)   ENCODE az64
	,secondary_unit_of_measure VARCHAR(25)   ENCODE lzo
	,preferred_grade VARCHAR(150)   ENCODE lzo
	,secondary_quantity_received NUMERIC(28,10)   ENCODE az64
	,secondary_quantity_accepted NUMERIC(28,10)   ENCODE az64
	,secondary_quantity_rejected NUMERIC(28,10)   ENCODE az64
	,secondary_quantity_cancelled NUMERIC(28,10)   ENCODE az64
	,vmi_flag VARCHAR(1)   ENCODE lzo
	,consigned_flag VARCHAR(1)   ENCODE lzo
	,retroactive_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,supplier_order_line_number VARCHAR(25)   ENCODE lzo
	,amount NUMERIC(28,10)   ENCODE az64
	,amount_received NUMERIC(28,10)   ENCODE az64
	,amount_billed NUMERIC(28,10)   ENCODE az64
	,amount_cancelled NUMERIC(28,10)   ENCODE az64
	,amount_rejected NUMERIC(28,10)   ENCODE az64
	,amount_accepted NUMERIC(28,10)   ENCODE az64
	,drop_ship_flag VARCHAR(1)   ENCODE lzo
	,sales_order_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,transaction_flow_header_id NUMERIC(15,0)   ENCODE az64
	,final_match_flag VARCHAR(1)   ENCODE lzo
	,manual_price_change_flag VARCHAR(1)   ENCODE lzo
	,shipment_closed_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,closed_for_receiving_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,closed_for_invoice_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,secondary_quantity_shipped NUMERIC(28,10)   ENCODE az64
	,value_basis VARCHAR(25)   ENCODE lzo
	,matching_basis VARCHAR(30)   ENCODE lzo
	,payment_type VARCHAR(30)   ENCODE lzo
	,description VARCHAR(240)   ENCODE lzo
	,work_approver_id NUMERIC(15,0)   ENCODE az64
	,bid_payment_id NUMERIC(15,0)   ENCODE az64
	,quantity_financed NUMERIC(28,10)   ENCODE az64
	,amount_financed NUMERIC(28,10)   ENCODE az64
	,quantity_recouped NUMERIC(28,10)   ENCODE az64
	,amount_recouped NUMERIC(28,10)   ENCODE az64
	,retainage_withheld_amount NUMERIC(28,10)   ENCODE az64
	,retainage_released_amount NUMERIC(28,10)   ENCODE az64
	,amount_shipped NUMERIC(28,10)   ENCODE az64
	,outsourced_assembly NUMERIC(28,10)   ENCODE az64
	,tax_attribute_update_code VARCHAR(15)   ENCODE lzo
	,original_shipment_id NUMERIC(15,0)   ENCODE az64
	,lcm_flag VARCHAR(1)   ENCODE lzo
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO;
insert
	into
	bec_ods.PO_LINE_LOCATIONS_ALL
(LINE_LOCATION_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	PO_HEADER_ID,
	PO_LINE_ID,
	LAST_UPDATE_LOGIN,
	CREATION_DATE,
	CREATED_BY,
	QUANTITY,
	QUANTITY_RECEIVED,
	QUANTITY_ACCEPTED,
	QUANTITY_REJECTED,
	QUANTITY_BILLED,
	QUANTITY_CANCELLED,
	UNIT_MEAS_LOOKUP_CODE,
	PO_RELEASE_ID,
	SHIP_TO_LOCATION_ID,
	SHIP_VIA_LOOKUP_CODE,
	NEED_BY_DATE,
	PROMISED_DATE,
	LAST_ACCEPT_DATE,
	PRICE_OVERRIDE,
	ENCUMBERED_FLAG,
	ENCUMBERED_DATE,
	UNENCUMBERED_QUANTITY,
	FOB_LOOKUP_CODE,
	FREIGHT_TERMS_LOOKUP_CODE,
	TAXABLE_FLAG,
	TAX_NAME,
	ESTIMATED_TAX_AMOUNT,
	FROM_HEADER_ID,
	FROM_LINE_ID,
	FROM_LINE_LOCATION_ID,
	START_DATE,
	END_DATE,
	LEAD_TIME,
	LEAD_TIME_UNIT,
	PRICE_DISCOUNT,
	TERMS_ID,
	APPROVED_FLAG,
	APPROVED_DATE,
	CLOSED_FLAG,
	CANCEL_FLAG,
	CANCELLED_BY,
	CANCEL_DATE,
	CANCEL_REASON,
	FIRM_STATUS_LOOKUP_CODE,
	FIRM_DATE,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	UNIT_OF_MEASURE_CLASS,
	ENCUMBER_NOW,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	INSPECTION_REQUIRED_FLAG,
	RECEIPT_REQUIRED_FLAG,
	QTY_RCV_TOLERANCE,
	QTY_RCV_EXCEPTION_CODE,
	ENFORCE_SHIP_TO_LOCATION_CODE,
	ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
	DAYS_EARLY_RECEIPT_ALLOWED,
	DAYS_LATE_RECEIPT_ALLOWED,
	RECEIPT_DAYS_EXCEPTION_CODE,
	INVOICE_CLOSE_TOLERANCE,
	RECEIVE_CLOSE_TOLERANCE,
	SHIP_TO_ORGANIZATION_ID,
	SHIPMENT_NUM,
	SOURCE_SHIPMENT_ID,
	SHIPMENT_TYPE,
	CLOSED_CODE,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	USSGL_TRANSACTION_CODE,
	GOVERNMENT_CONTEXT,
	RECEIVING_ROUTING_ID,
	ACCRUE_ON_RECEIPT_FLAG,
	CLOSED_REASON,
	CLOSED_DATE,
	CLOSED_BY,
	ORG_ID,
	QUANTITY_SHIPPED,
	GLOBAL_ATTRIBUTE_CATEGORY,
	GLOBAL_ATTRIBUTE1,
	GLOBAL_ATTRIBUTE2,
	GLOBAL_ATTRIBUTE3,
	GLOBAL_ATTRIBUTE4,
	GLOBAL_ATTRIBUTE5,
	GLOBAL_ATTRIBUTE6,
	GLOBAL_ATTRIBUTE7,
	GLOBAL_ATTRIBUTE8,
	GLOBAL_ATTRIBUTE9,
	GLOBAL_ATTRIBUTE10,
	GLOBAL_ATTRIBUTE11,
	GLOBAL_ATTRIBUTE12,
	GLOBAL_ATTRIBUTE13,
	GLOBAL_ATTRIBUTE14,
	GLOBAL_ATTRIBUTE15,
	GLOBAL_ATTRIBUTE16,
	GLOBAL_ATTRIBUTE17,
	GLOBAL_ATTRIBUTE18,
	GLOBAL_ATTRIBUTE19,
	GLOBAL_ATTRIBUTE20,
	COUNTRY_OF_ORIGIN_CODE,
	TAX_USER_OVERRIDE_FLAG,
	MATCH_OPTION,
	TAX_CODE_ID,
	CALCULATE_TAX_FLAG,
	CHANGE_PROMISED_DATE_REASON,
	NOTE_TO_RECEIVER,
	SECONDARY_QUANTITY,
	SECONDARY_UNIT_OF_MEASURE,
	PREFERRED_GRADE,
	SECONDARY_QUANTITY_RECEIVED,
	SECONDARY_QUANTITY_ACCEPTED,
	SECONDARY_QUANTITY_REJECTED,
	SECONDARY_QUANTITY_CANCELLED,
	VMI_FLAG,
	CONSIGNED_FLAG,
	RETROACTIVE_DATE,
	SUPPLIER_ORDER_LINE_NUMBER,
	AMOUNT,
	AMOUNT_RECEIVED,
	AMOUNT_BILLED,
	AMOUNT_CANCELLED,
	AMOUNT_REJECTED,
	AMOUNT_ACCEPTED,
	DROP_SHIP_FLAG,
	SALES_ORDER_UPDATE_DATE,
	TRANSACTION_FLOW_HEADER_ID,
	FINAL_MATCH_FLAG,
	MANUAL_PRICE_CHANGE_FLAG,
	SHIPMENT_CLOSED_DATE,
	CLOSED_FOR_RECEIVING_DATE,
	CLOSED_FOR_INVOICE_DATE,
	SECONDARY_QUANTITY_SHIPPED,
	VALUE_BASIS,
	MATCHING_BASIS,
	PAYMENT_TYPE,
	DESCRIPTION,
	WORK_APPROVER_ID,
	BID_PAYMENT_ID,
	QUANTITY_FINANCED,
	AMOUNT_FINANCED,
	QUANTITY_RECOUPED,
	AMOUNT_RECOUPED,
	RETAINAGE_WITHHELD_AMOUNT,
	RETAINAGE_RELEASED_AMOUNT,
	AMOUNT_SHIPPED,
	OUTSOURCED_ASSEMBLY,
	TAX_ATTRIBUTE_UPDATE_CODE,
	ORIGINAL_SHIPMENT_ID,
	LCM_FLAG,
	KCA_OPERATION,
	IS_DELETED_FLG
	,kca_seq_id
	,kca_seq_date
	)
select
	LINE_LOCATION_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	PO_HEADER_ID,
	PO_LINE_ID,
	LAST_UPDATE_LOGIN,
	CREATION_DATE,
	CREATED_BY,
	QUANTITY,
	QUANTITY_RECEIVED,
	QUANTITY_ACCEPTED,
	QUANTITY_REJECTED,
	QUANTITY_BILLED,
	QUANTITY_CANCELLED,
	UNIT_MEAS_LOOKUP_CODE,
	PO_RELEASE_ID,
	SHIP_TO_LOCATION_ID,
	SHIP_VIA_LOOKUP_CODE,
	NEED_BY_DATE,
	PROMISED_DATE,
	LAST_ACCEPT_DATE,
	PRICE_OVERRIDE,
	ENCUMBERED_FLAG,
	ENCUMBERED_DATE,
	UNENCUMBERED_QUANTITY,
	FOB_LOOKUP_CODE,
	FREIGHT_TERMS_LOOKUP_CODE,
	TAXABLE_FLAG,
	TAX_NAME,
	ESTIMATED_TAX_AMOUNT,
	FROM_HEADER_ID,
	FROM_LINE_ID,
	FROM_LINE_LOCATION_ID,
	START_DATE,
	END_DATE,
	LEAD_TIME,
	LEAD_TIME_UNIT,
	PRICE_DISCOUNT,
	TERMS_ID,
	APPROVED_FLAG,
	APPROVED_DATE,
	CLOSED_FLAG,
	CANCEL_FLAG,
	CANCELLED_BY,
	CANCEL_DATE,
	CANCEL_REASON,
	FIRM_STATUS_LOOKUP_CODE,
	FIRM_DATE,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	UNIT_OF_MEASURE_CLASS,
	ENCUMBER_NOW,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	INSPECTION_REQUIRED_FLAG,
	RECEIPT_REQUIRED_FLAG,
	QTY_RCV_TOLERANCE,
	QTY_RCV_EXCEPTION_CODE,
	ENFORCE_SHIP_TO_LOCATION_CODE,
	ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
	DAYS_EARLY_RECEIPT_ALLOWED,
	DAYS_LATE_RECEIPT_ALLOWED,
	RECEIPT_DAYS_EXCEPTION_CODE,
	INVOICE_CLOSE_TOLERANCE,
	RECEIVE_CLOSE_TOLERANCE,
	SHIP_TO_ORGANIZATION_ID,
	SHIPMENT_NUM,
	SOURCE_SHIPMENT_ID,
	SHIPMENT_TYPE,
	CLOSED_CODE,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	USSGL_TRANSACTION_CODE,
	GOVERNMENT_CONTEXT,
	RECEIVING_ROUTING_ID,
	ACCRUE_ON_RECEIPT_FLAG,
	CLOSED_REASON,
	CLOSED_DATE,
	CLOSED_BY,
	ORG_ID,
	QUANTITY_SHIPPED,
	GLOBAL_ATTRIBUTE_CATEGORY,
	GLOBAL_ATTRIBUTE1,
	GLOBAL_ATTRIBUTE2,
	GLOBAL_ATTRIBUTE3,
	GLOBAL_ATTRIBUTE4,
	GLOBAL_ATTRIBUTE5,
	GLOBAL_ATTRIBUTE6,
	GLOBAL_ATTRIBUTE7,
	GLOBAL_ATTRIBUTE8,
	GLOBAL_ATTRIBUTE9,
	GLOBAL_ATTRIBUTE10,
	GLOBAL_ATTRIBUTE11,
	GLOBAL_ATTRIBUTE12,
	GLOBAL_ATTRIBUTE13,
	GLOBAL_ATTRIBUTE14,
	GLOBAL_ATTRIBUTE15,
	GLOBAL_ATTRIBUTE16,
	GLOBAL_ATTRIBUTE17,
	GLOBAL_ATTRIBUTE18,
	GLOBAL_ATTRIBUTE19,
	GLOBAL_ATTRIBUTE20,
	COUNTRY_OF_ORIGIN_CODE,
	TAX_USER_OVERRIDE_FLAG,
	MATCH_OPTION,
	TAX_CODE_ID,
	CALCULATE_TAX_FLAG,
	CHANGE_PROMISED_DATE_REASON,
	NOTE_TO_RECEIVER,
	SECONDARY_QUANTITY,
	SECONDARY_UNIT_OF_MEASURE,
	PREFERRED_GRADE,
	SECONDARY_QUANTITY_RECEIVED,
	SECONDARY_QUANTITY_ACCEPTED,
	SECONDARY_QUANTITY_REJECTED,
	SECONDARY_QUANTITY_CANCELLED,
	VMI_FLAG,
	CONSIGNED_FLAG,
	RETROACTIVE_DATE,
	SUPPLIER_ORDER_LINE_NUMBER,
	AMOUNT,
	AMOUNT_RECEIVED,
	AMOUNT_BILLED,
	AMOUNT_CANCELLED,
	AMOUNT_REJECTED,
	AMOUNT_ACCEPTED,
	DROP_SHIP_FLAG,
	SALES_ORDER_UPDATE_DATE,
	TRANSACTION_FLOW_HEADER_ID,
	FINAL_MATCH_FLAG,
	MANUAL_PRICE_CHANGE_FLAG,
	SHIPMENT_CLOSED_DATE,
	CLOSED_FOR_RECEIVING_DATE,
	CLOSED_FOR_INVOICE_DATE,
	SECONDARY_QUANTITY_SHIPPED,
	VALUE_BASIS,
	MATCHING_BASIS,
	PAYMENT_TYPE,
	DESCRIPTION,
	WORK_APPROVER_ID,
	BID_PAYMENT_ID,
	QUANTITY_FINANCED,
	AMOUNT_FINANCED,
	QUANTITY_RECOUPED,
	AMOUNT_RECOUPED,
	RETAINAGE_WITHHELD_AMOUNT,
	RETAINAGE_RELEASED_AMOUNT,
	AMOUNT_SHIPPED,
	OUTSOURCED_ASSEMBLY,
	TAX_ATTRIBUTE_UPDATE_CODE,
	ORIGINAL_SHIPMENT_ID,
	LCM_FLAG,
	KCA_OPERATION,
    'N' as IS_DELETED_FLG
	,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID 
	,kca_seq_date
from
	bec_ods_stg.po_line_locations_all;

end;		


UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'po_line_locations_all';

commit;