/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.RA_RULES;

CREATE TABLE IF NOT EXISTS bec_ods.RA_RULES
(
RULE_ID	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(15,0)   ENCODE az64
,NAME	VARCHAR(30)   ENCODE lzo
,TYPE	VARCHAR(10)  ENCODE lzo
,STATUS	VARCHAR(1)  ENCODE lzo
,FREQUENCY	VARCHAR(15)  ENCODE lzo
,OCCURRENCES	NUMERIC(15,0)   ENCODE az64
,DESCRIPTION	VARCHAR(80)  ENCODE lzo
,ATTRIBUTE_CATEGORY	VARCHAR(30)  ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)  ENCODE lzo
,DEFERRED_REVENUE_FLAG	VARCHAR(1)  ENCODE lzo
,ZD_EDITION_NAME VARCHAR(30)  ENCODE lzo
,ZD_SYNC VARCHAR(30)  ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,KCA_SEQ_ID NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.RA_RULES
(
RULE_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,NAME
,TYPE
,STATUS
,FREQUENCY
,OCCURRENCES
,DESCRIPTION
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,DEFERRED_REVENUE_FLAG
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date
)
SELECT
RULE_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_LOGIN
,NAME
,TYPE
,STATUS
,FREQUENCY
,OCCURRENCES
,DESCRIPTION
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,DEFERRED_REVENUE_FLAG
,ZD_EDITION_NAME
,ZD_SYNC
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
,kca_seq_date
    FROM
        bec_ods_stg.RA_RULES;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'ra_rules';
	
COMMIT;