/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;

DROP TABLE if exists bec_ods.RCV_SHIPMENT_HEADERS;

CREATE TABLE IF NOT EXISTS bec_ods.RCV_SHIPMENT_HEADERS
(
	shipment_header_id NUMERIC(15,0)   ENCODE az64
	,last_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_updated_by NUMERIC(15,0)   ENCODE az64
	,creation_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,created_by NUMERIC(15,0)   ENCODE az64
	,last_update_login NUMERIC(15,0)   ENCODE az64
	,receipt_source_code VARCHAR(25)   ENCODE lzo
	,vendor_id NUMERIC(15,0)   ENCODE az64
	,vendor_site_id NUMERIC(15,0)   ENCODE az64
	,organization_id NUMERIC(15,0)   ENCODE az64
	,shipment_num VARCHAR(30)   ENCODE lzo
	,receipt_num VARCHAR(30)   ENCODE lzo
	,ship_to_location_id NUMERIC(15,0)   ENCODE az64
	,bill_of_lading VARCHAR(25)   ENCODE lzo
	,packing_slip VARCHAR(25)   ENCODE lzo
	,shipped_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,freight_carrier_code VARCHAR(25)   ENCODE lzo
	,expected_receipt_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,employee_id NUMERIC(9,0)   ENCODE az64
	,num_of_containers NUMERIC(28,10)   ENCODE az64
	,waybill_airbill_num VARCHAR(30)   ENCODE lzo
	,comments VARCHAR(4000)   ENCODE lzo
	,attribute_category VARCHAR(30)   ENCODE lzo
	,attribute1 VARCHAR(150)   ENCODE lzo
	,attribute2 VARCHAR(150)   ENCODE lzo
	,attribute3 VARCHAR(150)   ENCODE lzo
	,attribute4 VARCHAR(150)   ENCODE lzo
	,attribute5 VARCHAR(150)   ENCODE lzo
	,attribute6 VARCHAR(150)   ENCODE lzo
	,attribute7 VARCHAR(150)   ENCODE lzo
	,attribute8 VARCHAR(150)   ENCODE lzo
	,attribute9 VARCHAR(150)   ENCODE lzo
	,attribute10 VARCHAR(150)   ENCODE lzo
	,attribute11 VARCHAR(150)   ENCODE lzo
	,attribute12 VARCHAR(150)   ENCODE lzo
	,attribute13 VARCHAR(150)   ENCODE lzo
	,attribute14 VARCHAR(150)   ENCODE lzo
	,attribute15 VARCHAR(150)   ENCODE lzo
	,ussgl_transaction_code VARCHAR(30)   ENCODE lzo
	,government_context VARCHAR(30)   ENCODE lzo
	,request_id NUMERIC(15,0)   ENCODE az64
	,program_application_id NUMERIC(15,0)   ENCODE az64
	,program_id NUMERIC(15,0)   ENCODE az64
	,program_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,asn_type VARCHAR(25)   ENCODE lzo
	,edi_control_num VARCHAR(10)   ENCODE lzo
	,notice_creation_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,gross_weight NUMERIC(28,10)   ENCODE az64
	,gross_weight_uom_code VARCHAR(3)   ENCODE lzo
	,net_weight NUMERIC(28,10)    ENCODE az64
	,net_weight_uom_code VARCHAR(3)   ENCODE lzo
	,tar_weight NUMERIC(28,10)    ENCODE az64
	,tar_weight_uom_code VARCHAR(3)   ENCODE lzo
	,packaging_code VARCHAR(5)   ENCODE lzo
	,carrier_method VARCHAR(2)   ENCODE lzo
	,carrier_equipment VARCHAR(10)   ENCODE lzo
	,carrier_equipment_num VARCHAR(10)   ENCODE lzo
	,carrier_equipment_alpha VARCHAR(10)   ENCODE lzo
	,special_handling_code VARCHAR(3)   ENCODE lzo
	,hazard_code VARCHAR(1)   ENCODE lzo
	,hazard_class VARCHAR(4)   ENCODE lzo
	,hazard_description VARCHAR(80)   ENCODE lzo
	,freight_terms VARCHAR(25)   ENCODE lzo
	,freight_bill_number VARCHAR(35)   ENCODE lzo
	,invoice_num VARCHAR(50)   ENCODE lzo
	,invoice_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,invoice_amount NUMERIC(28,10)    ENCODE az64
	,tax_name VARCHAR(50)   ENCODE lzo
	,tax_amount NUMERIC(28,10)   ENCODE az64
	,freight_amount NUMERIC(28,10)   ENCODE az64
	,invoice_status_code VARCHAR(25)   ENCODE lzo
	,asn_status VARCHAR(10)   ENCODE lzo
	,currency_code VARCHAR(15)   ENCODE lzo
	,conversion_rate_type VARCHAR(30)   ENCODE lzo
	,conversion_rate NUMERIC(28,10)   ENCODE az64
	,conversion_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,payment_terms_id NUMERIC(15,0)   ENCODE az64
	,mrc_conversion_rate_type VARCHAR(2000)   ENCODE lzo
	,mrc_conversion_date VARCHAR(2000)   ENCODE lzo
	,mrc_conversion_rate VARCHAR(2000)   ENCODE lzo
	,ship_to_org_id NUMERIC(15,0)   ENCODE az64
	,customer_id NUMERIC(15,0)   ENCODE az64
	,customer_site_id NUMERIC(15,0)   ENCODE az64
	,remit_to_site_id NUMERIC(15,0)   ENCODE az64
	,ship_from_location_id NUMERIC(15,0)   ENCODE az64
	,wf_item_type VARCHAR(8)   ENCODE lzo
	,wf_item_key VARCHAR(280)   ENCODE lzo
	,approval_status VARCHAR(25)   ENCODE lzo
	,performance_period_from TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,performance_period_to TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,request_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO;
insert
	into
	bec_ods.RCV_SHIPMENT_HEADERS
(SHIPMENT_HEADER_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	RECEIPT_SOURCE_CODE,
	VENDOR_ID,
	VENDOR_SITE_ID,
	ORGANIZATION_ID,
	SHIPMENT_NUM,
	RECEIPT_NUM,
	SHIP_TO_LOCATION_ID,
	BILL_OF_LADING,
	PACKING_SLIP,
	SHIPPED_DATE,
	FREIGHT_CARRIER_CODE,
	EXPECTED_RECEIPT_DATE,
	EMPLOYEE_ID,
	NUM_OF_CONTAINERS,
	WAYBILL_AIRBILL_NUM,
	COMMENTS,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	USSGL_TRANSACTION_CODE,
	GOVERNMENT_CONTEXT,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	ASN_TYPE,
	EDI_CONTROL_NUM,
	NOTICE_CREATION_DATE,
	GROSS_WEIGHT,
	GROSS_WEIGHT_UOM_CODE,
	NET_WEIGHT,
	NET_WEIGHT_UOM_CODE,
	TAR_WEIGHT,
	TAR_WEIGHT_UOM_CODE,
	PACKAGING_CODE,
	CARRIER_METHOD,
	CARRIER_EQUIPMENT,
	CARRIER_EQUIPMENT_NUM,
	CARRIER_EQUIPMENT_ALPHA,
	SPECIAL_HANDLING_CODE,
	HAZARD_CODE,
	HAZARD_CLASS,
	HAZARD_DESCRIPTION,
	FREIGHT_TERMS,
	FREIGHT_BILL_NUMBER,
	INVOICE_NUM,
	INVOICE_DATE,
	INVOICE_AMOUNT,
	TAX_NAME,
	TAX_AMOUNT,
	FREIGHT_AMOUNT,
	INVOICE_STATUS_CODE,
	ASN_STATUS,
	CURRENCY_CODE,
	CONVERSION_RATE_TYPE,
	CONVERSION_RATE,
	CONVERSION_DATE,
	PAYMENT_TERMS_ID,
	MRC_CONVERSION_RATE_TYPE,
	MRC_CONVERSION_DATE,
	MRC_CONVERSION_RATE,
	SHIP_TO_ORG_ID,
	CUSTOMER_ID,
	CUSTOMER_SITE_ID,
	REMIT_TO_SITE_ID,
	SHIP_FROM_LOCATION_ID,
	WF_ITEM_TYPE,
	WF_ITEM_KEY,
	APPROVAL_STATUS,
	PERFORMANCE_PERIOD_FROM,
	PERFORMANCE_PERIOD_TO,
	REQUEST_DATE,
	KCA_OPERATION,
IS_DELETED_FLG
,kca_seq_id
,kca_seq_date
	)
select
	SHIPMENT_HEADER_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	RECEIPT_SOURCE_CODE,
	VENDOR_ID,
	VENDOR_SITE_ID,
	ORGANIZATION_ID,
	SHIPMENT_NUM,
	RECEIPT_NUM,
	SHIP_TO_LOCATION_ID,
	BILL_OF_LADING,
	PACKING_SLIP,
	SHIPPED_DATE,
	FREIGHT_CARRIER_CODE,
	EXPECTED_RECEIPT_DATE,
	EMPLOYEE_ID,
	NUM_OF_CONTAINERS,
	WAYBILL_AIRBILL_NUM,
	COMMENTS,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	USSGL_TRANSACTION_CODE,
	GOVERNMENT_CONTEXT,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	ASN_TYPE,
	EDI_CONTROL_NUM,
	NOTICE_CREATION_DATE,
	GROSS_WEIGHT,
	GROSS_WEIGHT_UOM_CODE,
	NET_WEIGHT,
	NET_WEIGHT_UOM_CODE,
	TAR_WEIGHT,
	TAR_WEIGHT_UOM_CODE,
	PACKAGING_CODE,
	CARRIER_METHOD,
	CARRIER_EQUIPMENT,
	CARRIER_EQUIPMENT_NUM,
	CARRIER_EQUIPMENT_ALPHA,
	SPECIAL_HANDLING_CODE,
	HAZARD_CODE,
	HAZARD_CLASS,
	HAZARD_DESCRIPTION,
	FREIGHT_TERMS,
	FREIGHT_BILL_NUMBER,
	INVOICE_NUM,
	INVOICE_DATE,
	INVOICE_AMOUNT,
	TAX_NAME,
	TAX_AMOUNT,
	FREIGHT_AMOUNT,
	INVOICE_STATUS_CODE,
	ASN_STATUS,
	CURRENCY_CODE,
	CONVERSION_RATE_TYPE,
	CONVERSION_RATE,
	CONVERSION_DATE,
	PAYMENT_TERMS_ID,
	MRC_CONVERSION_RATE_TYPE,
	MRC_CONVERSION_DATE,
	MRC_CONVERSION_RATE,
	SHIP_TO_ORG_ID,
	CUSTOMER_ID,
	CUSTOMER_SITE_ID,
	REMIT_TO_SITE_ID,
	SHIP_FROM_LOCATION_ID,
	WF_ITEM_TYPE,
	WF_ITEM_KEY,
	APPROVAL_STATUS,
	PERFORMANCE_PERIOD_FROM,
	PERFORMANCE_PERIOD_TO,
	REQUEST_DATE
	,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID 
,kca_seq_date
from
	bec_ods_stg.RCV_SHIPMENT_HEADERS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'rcv_shipment_headers'; 
	
COMMIT;