/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;

DROP TABLE if exists bec_ods.RCV_SHIPMENT_LINES;

CREATE TABLE IF NOT EXISTS bec_ods.RCV_SHIPMENT_LINES
(
	shipment_line_id NUMERIC(15,0)   ENCODE az64
	,last_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_updated_by NUMERIC(15,0)   ENCODE az64
	,creation_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,created_by NUMERIC(15,0)   ENCODE az64
	,last_update_login NUMERIC(15,0)   ENCODE az64
	,shipment_header_id NUMERIC(15,0)   ENCODE az64
	,line_num NUMERIC(15,0)   ENCODE az64
	,category_id NUMERIC(15,0)   ENCODE az64
	,quantity_shipped NUMERIC(28,10)   ENCODE az64
	,quantity_received NUMERIC(28,10)   ENCODE az64
	,unit_of_measure VARCHAR(25)   ENCODE lzo
	,item_description VARCHAR(240)   ENCODE lzo
	,item_id NUMERIC(15,0)   ENCODE az64
	,item_revision VARCHAR(3)   ENCODE lzo
	,vendor_item_num VARCHAR(25)   ENCODE lzo
	,vendor_lot_num VARCHAR(30)   ENCODE lzo
	,uom_conversion_rate NUMERIC(28,10)   ENCODE az64
	,shipment_line_status_code VARCHAR(25)   ENCODE lzo
	,source_document_code VARCHAR(25)   ENCODE lzo
	,po_header_id NUMERIC(15,0)   ENCODE az64
	,po_release_id NUMERIC(15,0)   ENCODE az64
	,po_line_id NUMERIC(15,0)   ENCODE az64
	,po_line_location_id NUMERIC(15,0)   ENCODE az64
	,po_distribution_id NUMERIC(15,0)   ENCODE az64
	,requisition_line_id NUMERIC(15,0)   ENCODE az64
	,req_distribution_id NUMERIC(15,0)   ENCODE az64
	,routing_header_id NUMERIC(15,0)   ENCODE az64
	,packing_slip VARCHAR(25)   ENCODE lzo
	,from_organization_id NUMERIC(15,0)   ENCODE az64
	,deliver_to_person_id NUMERIC(9,0)   ENCODE az64
	,employee_id NUMERIC(9,0)   ENCODE az64
	,destination_type_code VARCHAR(25)   ENCODE lzo
	,to_organization_id NUMERIC(15,0)   ENCODE az64
	,to_subinventory VARCHAR(10)   ENCODE lzo
	,locator_id NUMERIC(15,0)   ENCODE az64
	,deliver_to_location_id NUMERIC(15,0)   ENCODE az64
	,charge_account_id NUMERIC(15,0)   ENCODE az64
	,transportation_account_id NUMERIC(15,0)   ENCODE az64
	,shipment_unit_price NUMERIC(28,10)   ENCODE az64
	,transfer_cost NUMERIC(28,10)   ENCODE az64
	,transportation_cost NUMERIC(28,10)   ENCODE az64
	,comments VARCHAR(4000)   ENCODE lzo
	,attribute_category VARCHAR(30)   ENCODE lzo
	,attribute1 VARCHAR(150)   ENCODE lzo
	,attribute2 VARCHAR(150)   ENCODE lzo
	,attribute3 VARCHAR(150)   ENCODE lzo
	,attribute4 VARCHAR(150)   ENCODE lzo
	,attribute5 VARCHAR(150)   ENCODE lzo
	,attribute6 VARCHAR(150)   ENCODE lzo
	,attribute7 VARCHAR(150)   ENCODE lzo
	,attribute8 VARCHAR(150)   ENCODE lzo
	,attribute9 VARCHAR(150)   ENCODE lzo
	,attribute10 VARCHAR(150)   ENCODE lzo
	,attribute11 VARCHAR(150)   ENCODE lzo
	,attribute12 VARCHAR(150)   ENCODE lzo
	,attribute13 VARCHAR(150)   ENCODE lzo
	,attribute14 VARCHAR(150)   ENCODE lzo
	,attribute15 VARCHAR(150)   ENCODE lzo
	,reason_id NUMERIC(15,0)   ENCODE az64
	,ussgl_transaction_code VARCHAR(30)   ENCODE lzo
	,government_context VARCHAR(30)   ENCODE lzo
	,request_id NUMERIC(15,0)   ENCODE az64
	,program_application_id NUMERIC(15,0)   ENCODE az64
	,program_id NUMERIC(15,0)   ENCODE az64
	,program_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,destination_context VARCHAR(30)   ENCODE lzo
	,primary_unit_of_measure VARCHAR(25)   ENCODE lzo
	,excess_transport_reason VARCHAR(25)   ENCODE lzo
	,excess_transport_responsible VARCHAR(25)   ENCODE lzo
	,excess_transport_auth_num VARCHAR(30)   ENCODE lzo
	,asn_line_flag VARCHAR(1)   ENCODE lzo
	,original_asn_parent_line_id VARCHAR(1)   ENCODE lzo
	,original_asn_line_flag VARCHAR(1)   ENCODE lzo
	,vendor_cum_shipped_quantity NUMERIC(28,10)   ENCODE az64
	,notice_unit_price NUMERIC(28,10)   ENCODE az64
	,tax_name VARCHAR(50)   ENCODE lzo
	,tax_amount NUMERIC(28,10)   ENCODE az64
	,invoice_status_code VARCHAR(25)   ENCODE lzo
	,cum_comparison_flag VARCHAR(1)   ENCODE lzo
	,container_num VARCHAR(35)   ENCODE lzo
	,truck_num VARCHAR(35)   ENCODE lzo
	,bar_code_label VARCHAR(35)   ENCODE lzo
	,transfer_percentage NUMERIC(28,10)   ENCODE az64
	,mrc_shipment_unit_price VARCHAR(2000)   ENCODE lzo
	,mrc_transfer_cost VARCHAR(2000)   ENCODE lzo
	,mrc_transportation_cost VARCHAR(2000)   ENCODE lzo
	,mrc_notice_unit_price VARCHAR(2000)   ENCODE lzo
	,ship_to_location_id NUMERIC(15,0)   ENCODE az64
	,country_of_origin_code VARCHAR(2)   ENCODE lzo
	,oe_order_header_id NUMERIC(15,0)   ENCODE az64
	,oe_order_line_id NUMERIC(15,0)   ENCODE az64
	,customer_item_num VARCHAR(50)   ENCODE lzo
	,cost_group_id NUMERIC(15,0)   ENCODE az64
	,secondary_quantity_shipped NUMERIC(28,10)   ENCODE az64
	,secondary_quantity_received NUMERIC(28,10)   ENCODE az64
	,secondary_unit_of_measure VARCHAR(25)   ENCODE lzo
	,qc_grade VARCHAR(150)   ENCODE lzo
	,mmt_transaction_id NUMERIC(15,0)   ENCODE az64
	,asn_lpn_id NUMERIC(15,0)   ENCODE az64
	,amount NUMERIC(28,10)   ENCODE az64
	,amount_received NUMERIC(28,10)   ENCODE az64
	,job_id NUMERIC(15,0)   ENCODE az64
	,timecard_id NUMERIC(15,0)   ENCODE az64
	,timecard_ovn NUMERIC(15,0)   ENCODE az64
	,osa_flag VARCHAR(1)   ENCODE lzo
	,requested_amount NUMERIC(28,10)   ENCODE az64
	,material_stored_amount NUMERIC(28,10)   ENCODE az64
	,approval_status VARCHAR(25)   ENCODE lzo
	,amount_shipped NUMERIC(28,10)   ENCODE az64
	,lcm_shipment_line_id NUMERIC(15,0)   ENCODE az64
	,unit_landed_cost NUMERIC(28,10)   ENCODE az64
	,equipment_id NUMERIC(15,0)   ENCODE az64
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
	,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
		,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO;
INSERT
	INTO
	bec_ods.RCV_SHIPMENT_LINES
(SHIPMENT_LINE_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	SHIPMENT_HEADER_ID,
	LINE_NUM,
	CATEGORY_ID,
	QUANTITY_SHIPPED,
	QUANTITY_RECEIVED,
	UNIT_OF_MEASURE,
	ITEM_DESCRIPTION,
	ITEM_ID,
	ITEM_REVISION,
	VENDOR_ITEM_NUM,
	VENDOR_LOT_NUM,
	UOM_CONVERSION_RATE,
	SHIPMENT_LINE_STATUS_CODE,
	SOURCE_DOCUMENT_CODE,
	PO_HEADER_ID,
	PO_RELEASE_ID,
	PO_LINE_ID,
	PO_LINE_LOCATION_ID,
	PO_DISTRIBUTION_ID,
	REQUISITION_LINE_ID,
	REQ_DISTRIBUTION_ID,
	ROUTING_HEADER_ID,
	PACKING_SLIP,
	FROM_ORGANIZATION_ID,
	DELIVER_TO_PERSON_ID,
	EMPLOYEE_ID,
	DESTINATION_TYPE_CODE,
	TO_ORGANIZATION_ID,
	TO_SUBINVENTORY,
	LOCATOR_ID,
	DELIVER_TO_LOCATION_ID,
	CHARGE_ACCOUNT_ID,
	TRANSPORTATION_ACCOUNT_ID,
	SHIPMENT_UNIT_PRICE,
	TRANSFER_COST,
	TRANSPORTATION_COST,
	COMMENTS,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	REASON_ID,
	USSGL_TRANSACTION_CODE,
	GOVERNMENT_CONTEXT,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	DESTINATION_CONTEXT,
	PRIMARY_UNIT_OF_MEASURE,
	EXCESS_TRANSPORT_REASON,
	EXCESS_TRANSPORT_RESPONSIBLE,
	EXCESS_TRANSPORT_AUTH_NUM,
	ASN_LINE_FLAG,
	ORIGINAL_ASN_PARENT_LINE_ID,
	ORIGINAL_ASN_LINE_FLAG,
	VENDOR_CUM_SHIPPED_QUANTITY,
	NOTICE_UNIT_PRICE,
	TAX_NAME,
	TAX_AMOUNT,
	INVOICE_STATUS_CODE,
	CUM_COMPARISON_FLAG,
	CONTAINER_NUM,
	TRUCK_NUM,
	BAR_CODE_LABEL,
	TRANSFER_PERCENTAGE,
	MRC_SHIPMENT_UNIT_PRICE,
	MRC_TRANSFER_COST,
	MRC_TRANSPORTATION_COST,
	MRC_NOTICE_UNIT_PRICE,
	SHIP_TO_LOCATION_ID,
	COUNTRY_OF_ORIGIN_CODE,
	OE_ORDER_HEADER_ID,
	OE_ORDER_LINE_ID,
	CUSTOMER_ITEM_NUM,
	COST_GROUP_ID,
	SECONDARY_QUANTITY_SHIPPED,
	SECONDARY_QUANTITY_RECEIVED,
	SECONDARY_UNIT_OF_MEASURE,
	QC_GRADE,
	MMT_TRANSACTION_ID,
	ASN_LPN_ID,
	AMOUNT,
	AMOUNT_RECEIVED,
	JOB_ID,
	TIMECARD_ID,
	TIMECARD_OVN,
	OSA_FLAG,
	REQUESTED_AMOUNT,
	MATERIAL_STORED_AMOUNT,
	APPROVAL_STATUS,
	AMOUNT_SHIPPED,
	LCM_SHIPMENT_LINE_ID,
	UNIT_LANDED_COST,
	equipment_id,
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id
	,kca_seq_date
	)
SELECT
	SHIPMENT_LINE_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_LOGIN,
	SHIPMENT_HEADER_ID,
	LINE_NUM,
	CATEGORY_ID,
	QUANTITY_SHIPPED,
	QUANTITY_RECEIVED,
	UNIT_OF_MEASURE,
	ITEM_DESCRIPTION,
	ITEM_ID,
	ITEM_REVISION,
	VENDOR_ITEM_NUM,
	VENDOR_LOT_NUM,
	UOM_CONVERSION_RATE,
	SHIPMENT_LINE_STATUS_CODE,
	SOURCE_DOCUMENT_CODE,
	PO_HEADER_ID,
	PO_RELEASE_ID,
	PO_LINE_ID,
	PO_LINE_LOCATION_ID,
	PO_DISTRIBUTION_ID,
	REQUISITION_LINE_ID,
	REQ_DISTRIBUTION_ID,
	ROUTING_HEADER_ID,
	PACKING_SLIP,
	FROM_ORGANIZATION_ID,
	DELIVER_TO_PERSON_ID,
	EMPLOYEE_ID,
	DESTINATION_TYPE_CODE,
	TO_ORGANIZATION_ID,
	TO_SUBINVENTORY,
	LOCATOR_ID,
	DELIVER_TO_LOCATION_ID,
	CHARGE_ACCOUNT_ID,
	TRANSPORTATION_ACCOUNT_ID,
	SHIPMENT_UNIT_PRICE,
	TRANSFER_COST,
	TRANSPORTATION_COST,
	COMMENTS,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	REASON_ID,
	USSGL_TRANSACTION_CODE,
	GOVERNMENT_CONTEXT,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	DESTINATION_CONTEXT,
	PRIMARY_UNIT_OF_MEASURE,
	EXCESS_TRANSPORT_REASON,
	EXCESS_TRANSPORT_RESPONSIBLE,
	EXCESS_TRANSPORT_AUTH_NUM,
	ASN_LINE_FLAG,
	ORIGINAL_ASN_PARENT_LINE_ID,
	ORIGINAL_ASN_LINE_FLAG,
	VENDOR_CUM_SHIPPED_QUANTITY,
	NOTICE_UNIT_PRICE,
	TAX_NAME,
	TAX_AMOUNT,
	INVOICE_STATUS_CODE,
	CUM_COMPARISON_FLAG,
	CONTAINER_NUM,
	TRUCK_NUM,
	BAR_CODE_LABEL,
	TRANSFER_PERCENTAGE,
	MRC_SHIPMENT_UNIT_PRICE,
	MRC_TRANSFER_COST,
	MRC_TRANSPORTATION_COST,
	MRC_NOTICE_UNIT_PRICE,
	SHIP_TO_LOCATION_ID,
	COUNTRY_OF_ORIGIN_CODE,
	OE_ORDER_HEADER_ID,
	OE_ORDER_LINE_ID,
	CUSTOMER_ITEM_NUM,
	COST_GROUP_ID,
	SECONDARY_QUANTITY_SHIPPED,
	SECONDARY_QUANTITY_RECEIVED,
	SECONDARY_UNIT_OF_MEASURE,
	QC_GRADE,
	MMT_TRANSACTION_ID,
	ASN_LPN_ID,
	AMOUNT,
	AMOUNT_RECEIVED,
	JOB_ID,
	TIMECARD_ID,
	TIMECARD_OVN,
	OSA_FLAG,
	REQUESTED_AMOUNT,
	MATERIAL_STORED_AMOUNT,
	APPROVAL_STATUS,
	AMOUNT_SHIPPED,
	LCM_SHIPMENT_LINE_ID,
	UNIT_LANDED_COST,
	equipment_id,
	KCA_OPERATION,
	'N' as IS_DELETED_FLG,
	cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
,kca_seq_date	
FROM
	bec_ods_stg.RCV_SHIPMENT_LINES; 
end;		 
UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'rcv_shipment_lines'; 
	
COMMIT;