/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.WSH_DOCUMENT_INSTANCES;

CREATE TABLE IF NOT EXISTS bec_ods.WSH_DOCUMENT_INSTANCES
(
	document_instance_id NUMERIC(15,0)   ENCODE az64
	,entity_name VARCHAR(50)   ENCODE lzo
	,entity_id NUMERIC(15,0)   ENCODE az64
	,document_type VARCHAR(30)   ENCODE lzo
	,sequence_number VARCHAR(50)   ENCODE lzo
	,status VARCHAR(16383)   ENCODE lzo
	,final_print_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,doc_sequence_category_id NUMERIC(15,0)   ENCODE az64
	,attribute_category VARCHAR(150)   ENCODE lzo
	,attribute1 VARCHAR(150)   ENCODE lzo
	,attribute2 VARCHAR(150)   ENCODE lzo
	,attribute3 VARCHAR(150)   ENCODE lzo
	,attribute4 VARCHAR(150)   ENCODE lzo
	,attribute5 VARCHAR(150)   ENCODE lzo
	,attribute6 VARCHAR(150)   ENCODE lzo
	,attribute7 VARCHAR(150)   ENCODE lzo
	,attribute8 VARCHAR(150)   ENCODE lzo
	,attribute9 VARCHAR(150)   ENCODE lzo
	,attribute10 VARCHAR(150)   ENCODE lzo
	,attribute11 VARCHAR(150)   ENCODE lzo
	,attribute12 VARCHAR(150)   ENCODE lzo
	,attribute13 VARCHAR(150)   ENCODE lzo
	,attribute14 VARCHAR(150)   ENCODE lzo
	,attribute15 VARCHAR(150)   ENCODE lzo
	,creation_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,created_by NUMERIC(15,0)   ENCODE az64
	,last_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,last_updated_by NUMERIC(15,0)   ENCODE az64
	,last_update_login NUMERIC(15,0)   ENCODE az64
	,program_application_id NUMERIC(15,0)   ENCODE az64
	,program_id NUMERIC(15,0)   ENCODE az64
	,program_update_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,request_id NUMERIC(15,0)   ENCODE az64
	,pod_flag VARCHAR(1)   ENCODE lzo
	,pod_by VARCHAR(150)   ENCODE lzo
	,pod_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,reason_of_transport VARCHAR(30)   ENCODE lzo
	,description VARCHAR(150)   ENCODE lzo
	,cod_amount NUMERIC(28,10)   ENCODE az64
	,cod_currency_code VARCHAR(15)   ENCODE lzo
	,cod_remit_to VARCHAR(150)   ENCODE lzo
	,cod_charge_paid_by VARCHAR(150)   ENCODE lzo
	,problem_contact_reference VARCHAR(500)   ENCODE lzo
	,bill_freight_to VARCHAR(1000)   ENCODE lzo
	,carried_by VARCHAR(150)   ENCODE lzo
	,port_of_loading VARCHAR(150)   ENCODE lzo
	,port_of_discharge VARCHAR(150)   ENCODE lzo
	,booking_office VARCHAR(50)   ENCODE lzo
	,booking_number VARCHAR(30)   ENCODE lzo
	,service_contract VARCHAR(30)   ENCODE lzo
	,shipper_export_ref VARCHAR(30)   ENCODE lzo
	,carrier_export_ref VARCHAR(30)   ENCODE lzo
	,bol_notify_party VARCHAR(30)   ENCODE lzo
	,supplier_code VARCHAR(30)   ENCODE lzo
	,aetc_number VARCHAR(30)   ENCODE lzo
	,shipper_signed_by VARCHAR(150)   ENCODE lzo
	,shipper_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,carrier_signed_by VARCHAR(150)   ENCODE lzo
	,carrier_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,bol_issue_office VARCHAR(150)   ENCODE lzo
	,bol_issued_by VARCHAR(150)   ENCODE lzo
	,bol_date_issued TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,shipper_hm_by VARCHAR(150)   ENCODE lzo
	,shipper_hm_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,carrier_hm_by VARCHAR(150)   ENCODE lzo
	,carrier_hm_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,expected_pod_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,func_amount NUMERIC(28,10)   ENCODE az64
	,gross_amount NUMERIC(28,10)   ENCODE az64
	,currency_code VARCHAR(15)   ENCODE lzo
	,certificate_number VARCHAR(80)   ENCODE lzo
	,key_version NUMERIC(15,0)   ENCODE az64
	,system_entry_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,document_seq_id NUMERIC(38,10)   ENCODE az64
	,signature VARCHAR(240)   ENCODE lzo
	,KCA_OPERATION VARCHAR(10)   ENCODE lzo
    ,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
	,kca_seq_id NUMERIC(36,0)   ENCODE az64
		,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.WSH_DOCUMENT_INSTANCES (
	DOCUMENT_INSTANCE_ID,
	ENTITY_NAME,
	ENTITY_ID,
	DOCUMENT_TYPE,
	SEQUENCE_NUMBER,
	STATUS,
	FINAL_PRINT_DATE,
	DOC_SEQUENCE_CATEGORY_ID,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_LOGIN,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	REQUEST_ID,
	POD_FLAG,
	POD_BY,
	POD_DATE,
	REASON_OF_TRANSPORT,
	DESCRIPTION,
	COD_AMOUNT,
	COD_CURRENCY_CODE,
	COD_REMIT_TO,
	COD_CHARGE_PAID_BY,
	PROBLEM_CONTACT_REFERENCE,
	BILL_FREIGHT_TO,
	CARRIED_BY,
	PORT_OF_LOADING,
	PORT_OF_DISCHARGE,
	BOOKING_OFFICE,
	BOOKING_NUMBER,
	SERVICE_CONTRACT,
	SHIPPER_EXPORT_REF,
	CARRIER_EXPORT_REF,
	BOL_NOTIFY_PARTY,
	SUPPLIER_CODE,
	AETC_NUMBER,
	SHIPPER_SIGNED_BY,
	SHIPPER_DATE,
	CARRIER_SIGNED_BY,
	CARRIER_DATE,
	BOL_ISSUE_OFFICE,
	BOL_ISSUED_BY,
	BOL_DATE_ISSUED,
	SHIPPER_HM_BY,
	SHIPPER_HM_DATE,
	CARRIER_HM_BY,
	CARRIER_HM_DATE,
	EXPECTED_POD_DATE,
	FUNC_AMOUNT,
	GROSS_AMOUNT,
	CURRENCY_CODE,
	CERTIFICATE_NUMBER,
	KEY_VERSION,
	SYSTEM_ENTRY_DATE,
	DOCUMENT_SEQ_ID,
	SIGNATURE,
	KCA_OPERATION,
	IS_DELETED_FLG,
	KCA_SEQ_ID
	,kca_seq_date
)
    SELECT
	DOCUMENT_INSTANCE_ID,
	ENTITY_NAME,
	ENTITY_ID,
	DOCUMENT_TYPE,
	SEQUENCE_NUMBER,
	STATUS,
	FINAL_PRINT_DATE,
	DOC_SEQUENCE_CATEGORY_ID,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_LOGIN,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	REQUEST_ID,
	POD_FLAG,
	POD_BY,
	POD_DATE,
	REASON_OF_TRANSPORT,
	DESCRIPTION,
	COD_AMOUNT,
	COD_CURRENCY_CODE,
	COD_REMIT_TO,
	COD_CHARGE_PAID_BY,
	PROBLEM_CONTACT_REFERENCE,
	BILL_FREIGHT_TO,
	CARRIED_BY,
	PORT_OF_LOADING,
	PORT_OF_DISCHARGE,
	BOOKING_OFFICE,
	BOOKING_NUMBER,
	SERVICE_CONTRACT,
	SHIPPER_EXPORT_REF,
	CARRIER_EXPORT_REF,
	BOL_NOTIFY_PARTY,
	SUPPLIER_CODE,
	AETC_NUMBER,
	SHIPPER_SIGNED_BY,
	SHIPPER_DATE,
	CARRIER_SIGNED_BY,
	CARRIER_DATE,
	BOL_ISSUE_OFFICE,
	BOL_ISSUED_BY,
	BOL_DATE_ISSUED,
	SHIPPER_HM_BY,
	SHIPPER_HM_DATE,
	CARRIER_HM_BY,
	CARRIER_HM_DATE,
	EXPECTED_POD_DATE,
	FUNC_AMOUNT,
	GROSS_AMOUNT,
	CURRENCY_CODE,
	CERTIFICATE_NUMBER,
	KEY_VERSION,
	SYSTEM_ENTRY_DATE,
	DOCUMENT_SEQ_ID,
	SIGNATURE,
		KCA_OPERATION,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
		,kca_seq_date
    FROM
        bec_ods_stg.WSH_DOCUMENT_INSTANCES;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'wsh_document_instances';
	
commit;