/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.XLA_DISTRIBUTION_LINKS;

CREATE TABLE IF NOT EXISTS bec_ods.XLA_DISTRIBUTION_LINKS
(
APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,EVENT_ID	NUMERIC(15,0)   ENCODE az64
,AE_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,AE_LINE_NUM	NUMERIC(38,0)   ENCODE az64
,SOURCE_DISTRIBUTION_TYPE	VARCHAR(30)  ENCODE lzo
,SOURCE_DISTRIBUTION_ID_CHAR_1	VARCHAR(240)  ENCODE lzo
,SOURCE_DISTRIBUTION_ID_CHAR_2	VARCHAR(240)  ENCODE lzo
,SOURCE_DISTRIBUTION_ID_CHAR_3	VARCHAR(240)  ENCODE lzo
,SOURCE_DISTRIBUTION_ID_CHAR_4	VARCHAR(240)  ENCODE lzo
,SOURCE_DISTRIBUTION_ID_CHAR_5	VARCHAR(240)  ENCODE lzo
,SOURCE_DISTRIBUTION_ID_NUM_1	NUMERIC(38,0)   ENCODE az64
,SOURCE_DISTRIBUTION_ID_NUM_2	NUMERIC(38,0)   ENCODE az64
,SOURCE_DISTRIBUTION_ID_NUM_3	NUMERIC(38,0)   ENCODE az64
,SOURCE_DISTRIBUTION_ID_NUM_4	NUMERIC(38,0)   ENCODE az64
,SOURCE_DISTRIBUTION_ID_NUM_5	NUMERIC(38,0)   ENCODE az64
,TAX_LINE_REF_ID	NUMERIC(15,0)   ENCODE az64
,TAX_SUMMARY_LINE_REF_ID	NUMERIC(15,0)   ENCODE az64
,TAX_REC_NREC_DIST_REF_ID	NUMERIC(15,0)   ENCODE az64
,STATISTICAL_AMOUNT	NUMERIC(28,10)   ENCODE az64
,REF_AE_HEADER_ID	NUMERIC(15,0)   ENCODE az64
,REF_TEMP_LINE_NUM	NUMERIC(15,0)   ENCODE az64
,ACCOUNTING_LINE_CODE	VARCHAR(30)  ENCODE lzo
,ACCOUNTING_LINE_TYPE_CODE	VARCHAR(1) ENCODE lzo
,MERGE_DUPLICATE_CODE	VARCHAR(1) ENCODE lzo
,TEMP_LINE_NUM	NUMERIC(15,0)   ENCODE az64
,REF_EVENT_ID	NUMERIC(15,0)   ENCODE az64
,LINE_DEFINITION_OWNER_CODE	VARCHAR(30)  ENCODE lzo
,LINE_DEFINITION_CODE	VARCHAR(30)  ENCODE lzo
,EVENT_CLASS_CODE	VARCHAR(30)  ENCODE lzo
,EVENT_TYPE_CODE	VARCHAR(30)  ENCODE lzo
,UPG_BATCH_ID	NUMERIC(15,0)   ENCODE az64
,CALCULATE_ACCTD_AMTS_FLAG	VARCHAR(1) ENCODE lzo
,CALCULATE_G_L_AMTS_FLAG	VARCHAR(1) ENCODE lzo
,ROUNDING_CLASS_CODE	VARCHAR(30)  ENCODE lzo
,DOCUMENT_ROUNDING_LEVEL	VARCHAR(30)  ENCODE lzo
,UNROUNDED_ENTERED_DR	NUMERIC(28,10)   ENCODE az64
,UNROUNDED_ENTERED_CR	NUMERIC(28,10)   ENCODE az64
,DOC_ROUNDING_ENTERED_AMT	NUMERIC(28,10)   ENCODE az64
,DOC_ROUNDING_ACCTD_AMT	NUMERIC(28,10)   ENCODE az64
,UNROUNDED_ACCOUNTED_CR	NUMERIC(28,10)   ENCODE az64
,UNROUNDED_ACCOUNTED_DR	NUMERIC(28,10)   ENCODE az64
,APPLIED_TO_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_ENTITY_CODE	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_ENTITY_ID	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_SOURCE_ID_NUM_1	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_SOURCE_ID_NUM_2	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_SOURCE_ID_NUM_3	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_SOURCE_ID_NUM_4	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_SOURCE_ID_CHAR_1	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_SOURCE_ID_CHAR_2	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_SOURCE_ID_CHAR_3	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_SOURCE_ID_CHAR_4	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_DISTRIBUTION_TYPE	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_DIST_ID_NUM_1	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_DIST_ID_NUM_2	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_DIST_ID_NUM_3	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_DIST_ID_NUM_4	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_DIST_ID_NUM_5	NUMERIC(15,0)   ENCODE az64
,APPLIED_TO_DIST_ID_CHAR_1	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_DIST_ID_CHAR_2	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_DIST_ID_CHAR_3	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_DIST_ID_CHAR_4	VARCHAR(30)  ENCODE lzo
,APPLIED_TO_DIST_ID_CHAR_5	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_ENTITY_CODE	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_SOURCE_ID_NUM_1	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_SOURCE_ID_NUM_2	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_SOURCE_ID_NUM_3	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_SOURCE_ID_NUM_4	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_SOURCE_ID_CHAR_1	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_SOURCE_ID_CHAR_2	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_SOURCE_ID_CHAR_3	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_SOURCE_ID_CHAR_4	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_DISTRIBUTION_TYPE	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_DIST_ID_NUM_1	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_DIST_ID_NUM_2	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_DIST_ID_NUM_3	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_DIST_ID_NUM_4	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_DIST_ID_NUM_5	NUMERIC(15,0)   ENCODE az64
,ALLOC_TO_DIST_ID_CHAR_1	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_DIST_ID_CHAR_2	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_DIST_ID_CHAR_3	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_DIST_ID_CHAR_4	VARCHAR(30)  ENCODE lzo
,ALLOC_TO_DIST_ID_CHAR_5	VARCHAR(30)  ENCODE lzo
,GAIN_OR_LOSS_REF	VARCHAR(30)  ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,KCA_SEQ_ID NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.XLA_DISTRIBUTION_LINKS
(
APPLICATION_ID
,EVENT_ID
,AE_HEADER_ID
,AE_LINE_NUM
,SOURCE_DISTRIBUTION_TYPE
,SOURCE_DISTRIBUTION_ID_CHAR_1
,SOURCE_DISTRIBUTION_ID_CHAR_2
,SOURCE_DISTRIBUTION_ID_CHAR_3
,SOURCE_DISTRIBUTION_ID_CHAR_4
,SOURCE_DISTRIBUTION_ID_CHAR_5
,SOURCE_DISTRIBUTION_ID_NUM_1
,SOURCE_DISTRIBUTION_ID_NUM_2
,SOURCE_DISTRIBUTION_ID_NUM_3
,SOURCE_DISTRIBUTION_ID_NUM_4
,SOURCE_DISTRIBUTION_ID_NUM_5
,TAX_LINE_REF_ID
,TAX_SUMMARY_LINE_REF_ID
,TAX_REC_NREC_DIST_REF_ID
,STATISTICAL_AMOUNT
,REF_AE_HEADER_ID
,REF_TEMP_LINE_NUM
,ACCOUNTING_LINE_CODE
,ACCOUNTING_LINE_TYPE_CODE
,MERGE_DUPLICATE_CODE
,TEMP_LINE_NUM
,REF_EVENT_ID
,LINE_DEFINITION_OWNER_CODE
,LINE_DEFINITION_CODE
,EVENT_CLASS_CODE
,EVENT_TYPE_CODE
,UPG_BATCH_ID
,CALCULATE_ACCTD_AMTS_FLAG
,CALCULATE_G_L_AMTS_FLAG
,ROUNDING_CLASS_CODE
,DOCUMENT_ROUNDING_LEVEL
,UNROUNDED_ENTERED_DR
,UNROUNDED_ENTERED_CR
,DOC_ROUNDING_ENTERED_AMT
,DOC_ROUNDING_ACCTD_AMT
,UNROUNDED_ACCOUNTED_CR
,UNROUNDED_ACCOUNTED_DR
,APPLIED_TO_APPLICATION_ID
,APPLIED_TO_ENTITY_CODE
,APPLIED_TO_ENTITY_ID
,APPLIED_TO_SOURCE_ID_NUM_1
,APPLIED_TO_SOURCE_ID_NUM_2
,APPLIED_TO_SOURCE_ID_NUM_3
,APPLIED_TO_SOURCE_ID_NUM_4
,APPLIED_TO_SOURCE_ID_CHAR_1
,APPLIED_TO_SOURCE_ID_CHAR_2
,APPLIED_TO_SOURCE_ID_CHAR_3
,APPLIED_TO_SOURCE_ID_CHAR_4
,APPLIED_TO_DISTRIBUTION_TYPE
,APPLIED_TO_DIST_ID_NUM_1
,APPLIED_TO_DIST_ID_NUM_2
,APPLIED_TO_DIST_ID_NUM_3
,APPLIED_TO_DIST_ID_NUM_4
,APPLIED_TO_DIST_ID_NUM_5
,APPLIED_TO_DIST_ID_CHAR_1
,APPLIED_TO_DIST_ID_CHAR_2
,APPLIED_TO_DIST_ID_CHAR_3
,APPLIED_TO_DIST_ID_CHAR_4
,APPLIED_TO_DIST_ID_CHAR_5
,ALLOC_TO_APPLICATION_ID
,ALLOC_TO_ENTITY_CODE
,ALLOC_TO_SOURCE_ID_NUM_1
,ALLOC_TO_SOURCE_ID_NUM_2
,ALLOC_TO_SOURCE_ID_NUM_3
,ALLOC_TO_SOURCE_ID_NUM_4
,ALLOC_TO_SOURCE_ID_CHAR_1
,ALLOC_TO_SOURCE_ID_CHAR_2
,ALLOC_TO_SOURCE_ID_CHAR_3
,ALLOC_TO_SOURCE_ID_CHAR_4
,ALLOC_TO_DISTRIBUTION_TYPE
,ALLOC_TO_DIST_ID_NUM_1
,ALLOC_TO_DIST_ID_NUM_2
,ALLOC_TO_DIST_ID_NUM_3
,ALLOC_TO_DIST_ID_NUM_4
,ALLOC_TO_DIST_ID_NUM_5
,ALLOC_TO_DIST_ID_CHAR_1
,ALLOC_TO_DIST_ID_CHAR_2
,ALLOC_TO_DIST_ID_CHAR_3
,ALLOC_TO_DIST_ID_CHAR_4
,ALLOC_TO_DIST_ID_CHAR_5
,GAIN_OR_LOSS_REF
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date
)
SELECT
APPLICATION_ID
,EVENT_ID
,AE_HEADER_ID
,AE_LINE_NUM
,SOURCE_DISTRIBUTION_TYPE
,SOURCE_DISTRIBUTION_ID_CHAR_1
,SOURCE_DISTRIBUTION_ID_CHAR_2
,SOURCE_DISTRIBUTION_ID_CHAR_3
,SOURCE_DISTRIBUTION_ID_CHAR_4
,SOURCE_DISTRIBUTION_ID_CHAR_5
,SOURCE_DISTRIBUTION_ID_NUM_1
,SOURCE_DISTRIBUTION_ID_NUM_2
,SOURCE_DISTRIBUTION_ID_NUM_3
,SOURCE_DISTRIBUTION_ID_NUM_4
,SOURCE_DISTRIBUTION_ID_NUM_5
,TAX_LINE_REF_ID
,TAX_SUMMARY_LINE_REF_ID
,TAX_REC_NREC_DIST_REF_ID
,STATISTICAL_AMOUNT
,REF_AE_HEADER_ID
,REF_TEMP_LINE_NUM
,ACCOUNTING_LINE_CODE
,ACCOUNTING_LINE_TYPE_CODE
,MERGE_DUPLICATE_CODE
,TEMP_LINE_NUM
,REF_EVENT_ID
,LINE_DEFINITION_OWNER_CODE
,LINE_DEFINITION_CODE
,EVENT_CLASS_CODE
,EVENT_TYPE_CODE
,UPG_BATCH_ID
,CALCULATE_ACCTD_AMTS_FLAG
,CALCULATE_G_L_AMTS_FLAG
,ROUNDING_CLASS_CODE
,DOCUMENT_ROUNDING_LEVEL
,UNROUNDED_ENTERED_DR
,UNROUNDED_ENTERED_CR
,DOC_ROUNDING_ENTERED_AMT
,DOC_ROUNDING_ACCTD_AMT
,UNROUNDED_ACCOUNTED_CR
,UNROUNDED_ACCOUNTED_DR
,APPLIED_TO_APPLICATION_ID
,APPLIED_TO_ENTITY_CODE
,APPLIED_TO_ENTITY_ID
,APPLIED_TO_SOURCE_ID_NUM_1
,APPLIED_TO_SOURCE_ID_NUM_2
,APPLIED_TO_SOURCE_ID_NUM_3
,APPLIED_TO_SOURCE_ID_NUM_4
,APPLIED_TO_SOURCE_ID_CHAR_1
,APPLIED_TO_SOURCE_ID_CHAR_2
,APPLIED_TO_SOURCE_ID_CHAR_3
,APPLIED_TO_SOURCE_ID_CHAR_4
,APPLIED_TO_DISTRIBUTION_TYPE
,APPLIED_TO_DIST_ID_NUM_1
,APPLIED_TO_DIST_ID_NUM_2
,APPLIED_TO_DIST_ID_NUM_3
,APPLIED_TO_DIST_ID_NUM_4
,APPLIED_TO_DIST_ID_NUM_5
,APPLIED_TO_DIST_ID_CHAR_1
,APPLIED_TO_DIST_ID_CHAR_2
,APPLIED_TO_DIST_ID_CHAR_3
,APPLIED_TO_DIST_ID_CHAR_4
,APPLIED_TO_DIST_ID_CHAR_5
,ALLOC_TO_APPLICATION_ID
,ALLOC_TO_ENTITY_CODE
,ALLOC_TO_SOURCE_ID_NUM_1
,ALLOC_TO_SOURCE_ID_NUM_2
,ALLOC_TO_SOURCE_ID_NUM_3
,ALLOC_TO_SOURCE_ID_NUM_4
,ALLOC_TO_SOURCE_ID_CHAR_1
,ALLOC_TO_SOURCE_ID_CHAR_2
,ALLOC_TO_SOURCE_ID_CHAR_3
,ALLOC_TO_SOURCE_ID_CHAR_4
,ALLOC_TO_DISTRIBUTION_TYPE
,ALLOC_TO_DIST_ID_NUM_1
,ALLOC_TO_DIST_ID_NUM_2
,ALLOC_TO_DIST_ID_NUM_3
,ALLOC_TO_DIST_ID_NUM_4
,ALLOC_TO_DIST_ID_NUM_5
,ALLOC_TO_DIST_ID_CHAR_1
,ALLOC_TO_DIST_ID_CHAR_2
,ALLOC_TO_DIST_ID_CHAR_3
,ALLOC_TO_DIST_ID_CHAR_4
,ALLOC_TO_DIST_ID_CHAR_5
,GAIN_OR_LOSS_REF
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
,kca_seq_date
    FROM
        bec_ods_stg.XLA_DISTRIBUTION_LINKS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'xla_distribution_links'; 
	
COMMIT;