/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/
begin;
drop table if exists bec_ods.XLA_TRANSACTION_ENTITIES;

CREATE TABLE IF NOT EXISTS bec_ods.XLA_TRANSACTION_ENTITIES
(
ENTITY_ID	NUMERIC(15,0)   ENCODE az64
,APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,LEGAL_ENTITY_ID	NUMERIC(15,0)   ENCODE az64
,ENTITY_CODE	VARCHAR(30)   ENCODE lzo
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY	NUMERIC(38,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY	NUMERIC(38,0)   ENCODE az64
,LAST_UPDATE_LOGIN	NUMERIC(38,0)   ENCODE az64
,SOURCE_ID_INT_1	NUMERIC(38,0)   ENCODE az64
,SOURCE_ID_CHAR_1	VARCHAR(30)   ENCODE lzo
,SECURITY_ID_INT_1	NUMERIC(38,0)   ENCODE az64
,SECURITY_ID_INT_2	NUMERIC(38,0)   ENCODE az64
,SECURITY_ID_INT_3	NUMERIC(38,0)   ENCODE az64
,SECURITY_ID_CHAR_1	VARCHAR(30)   ENCODE lzo
,SECURITY_ID_CHAR_2	VARCHAR(30)   ENCODE lzo
,SECURITY_ID_CHAR_3	VARCHAR(30)   ENCODE lzo
,SOURCE_ID_INT_2	NUMERIC(38,0)   ENCODE az64
,SOURCE_ID_CHAR_2	VARCHAR(30)   ENCODE lzo
,SOURCE_ID_INT_3	NUMERIC(38,0)   ENCODE az64
,SOURCE_ID_CHAR_3	VARCHAR(30)   ENCODE lzo
,SOURCE_ID_INT_4	NUMERIC(38,0)   ENCODE az64
,SOURCE_ID_CHAR_4	VARCHAR(30)   ENCODE lzo
,TRANSACTION_NUMBER	VARCHAR(240)   ENCODE lzo
,LEDGER_ID	NUMERIC(15,0)   ENCODE az64
,VALUATION_METHOD	VARCHAR(30)   ENCODE lzo
,SOURCE_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,UPG_BATCH_ID	NUMERIC(15,0)   ENCODE az64
,UPG_SOURCE_APPLICATION_ID	NUMERIC(15,0)   ENCODE az64
,UPG_VALID_FLAG	VARCHAR(1)   ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,kca_seq_id NUMERIC(36,0)   ENCODE az64
	,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

insert into bec_ods.XLA_TRANSACTION_ENTITIES
(ENTITY_ID
,APPLICATION_ID
,LEGAL_ENTITY_ID
,ENTITY_CODE
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,SOURCE_ID_INT_1
,SOURCE_ID_CHAR_1
,SECURITY_ID_INT_1
,SECURITY_ID_INT_2
,SECURITY_ID_INT_3
,SECURITY_ID_CHAR_1
,SECURITY_ID_CHAR_2
,SECURITY_ID_CHAR_3
,SOURCE_ID_INT_2
,SOURCE_ID_CHAR_2
,SOURCE_ID_INT_3
,SOURCE_ID_CHAR_3
,SOURCE_ID_INT_4
,SOURCE_ID_CHAR_4
,TRANSACTION_NUMBER
,LEDGER_ID
,VALUATION_METHOD
,SOURCE_APPLICATION_ID
,UPG_BATCH_ID
,UPG_SOURCE_APPLICATION_ID
,UPG_VALID_FLAG
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date)
(
select
ENTITY_ID
,APPLICATION_ID
,LEGAL_ENTITY_ID
,ENTITY_CODE
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,SOURCE_ID_INT_1
,SOURCE_ID_CHAR_1
,SECURITY_ID_INT_1
,SECURITY_ID_INT_2
,SECURITY_ID_INT_3
,SECURITY_ID_CHAR_1
,SECURITY_ID_CHAR_2
,SECURITY_ID_CHAR_3
,SOURCE_ID_INT_2
,SOURCE_ID_CHAR_2
,SOURCE_ID_INT_3
,SOURCE_ID_CHAR_3
,SOURCE_ID_INT_4
,SOURCE_ID_CHAR_4
,TRANSACTION_NUMBER
,LEDGER_ID
,VALUATION_METHOD
,SOURCE_APPLICATION_ID
,UPG_BATCH_ID
,UPG_SOURCE_APPLICATION_ID
,UPG_VALID_FLAG
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID  
,kca_seq_date
from bec_ods_stg.XLA_TRANSACTION_ENTITIES
);

end;
update bec_etl_ctrl.batch_ods_info set load_type = 'I', 
last_refresh_date = getdate() where ods_table_name='xla_transaction_entities';

COMMIT;
