/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for ODS.
# File Version: KPI v1.0
*/

begin;

DROP TABLE if exists bec_ods.XLA_AE_HEADERS;

CREATE TABLE IF NOT EXISTS bec_ods.XLA_AE_HEADERS
(
AE_HEADER_ID		NUMERIC(15,0)   ENCODE az64
,APPLICATION_ID		NUMERIC(15,0)   ENCODE az64
,LEDGER_ID		NUMERIC(15,0)   ENCODE az64
,ENTITY_ID		NUMERIC(15,0)   ENCODE az64
,EVENT_ID		NUMERIC(15,0)   ENCODE az64
,EVENT_TYPE_CODE	VARCHAR(30)  ENCODE lzo
,ACCOUNTING_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,GL_TRANSFER_STATUS_CODE	VARCHAR(30)  ENCODE lzo
,GL_TRANSFER_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,JE_CATEGORY_NAME	VARCHAR(30)  ENCODE lzo
,ACCOUNTING_ENTRY_STATUS_CODE	VARCHAR(30)  ENCODE lzo
,ACCOUNTING_ENTRY_TYPE_CODE	VARCHAR(30)  ENCODE lzo
,AMB_CONTEXT_CODE	VARCHAR(30)  ENCODE lzo
,PRODUCT_RULE_TYPE_CODE	VARCHAR(1)  ENCODE lzo
,PRODUCT_RULE_CODE	VARCHAR(30)  ENCODE lzo
,PRODUCT_RULE_VERSION	VARCHAR(30)  ENCODE lzo
,DESCRIPTION	VARCHAR(1996)  ENCODE lzo
,DOC_SEQUENCE_ID		NUMERIC(15,0)   ENCODE az64
,DOC_SEQUENCE_VALUE		NUMERIC(28,10)  ENCODE az64
,ACCOUNTING_BATCH_ID		NUMERIC(15,0)   ENCODE az64
,COMPLETION_ACCT_SEQ_VERSION_ID		NUMERIC(15,0)   ENCODE az64
,CLOSE_ACCT_SEQ_VERSION_ID		NUMERIC(15,0)   ENCODE az64
,COMPLETION_ACCT_SEQ_VALUE	NUMERIC(28,10)   ENCODE az64
,CLOSE_ACCT_SEQ_VALUE	NUMERIC(28,10)   ENCODE az64
,BUDGET_VERSION_ID		NUMERIC(15,0)   ENCODE az64
,FUNDS_STATUS_CODE	VARCHAR(30)  ENCODE lzo
,ENCUMBRANCE_TYPE_ID		NUMERIC(15,0)   ENCODE az64
,BALANCE_TYPE_CODE	VARCHAR(1) ENCODE lzo
,REFERENCE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,COMPLETED_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PERIOD_NAME	VARCHAR(15) ENCODE lzo
,PACKET_ID		NUMERIC(15,0)   ENCODE az64
,COMPLETION_ACCT_SEQ_ASSIGN_ID		NUMERIC(15,0)   ENCODE az64
,CLOSE_ACCT_SEQ_ASSIGN_ID		NUMERIC(15,0)   ENCODE az64
,DOC_CATEGORY_CODE	VARCHAR(30)  ENCODE lzo
,ATTRIBUTE_CATEGORY	VARCHAR(30)  ENCODE lzo
,ATTRIBUTE1	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE2	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE3	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE4	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE5	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE6	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE7	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE8	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE9	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE10	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE11	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE12	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE13	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE14	VARCHAR(150)  ENCODE lzo
,ATTRIBUTE15	VARCHAR(150)  ENCODE lzo
,GROUP_ID		NUMERIC(15,0)   ENCODE az64
,DOC_SEQUENCE_VERSION_ID		NUMERIC(15,0)   ENCODE az64
,DOC_SEQUENCE_ASSIGN_ID		NUMERIC(15,0)   ENCODE az64
,CREATION_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,CREATED_BY		NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,LAST_UPDATED_BY		NUMERIC(15,0)   ENCODE az64
,LAST_UPDATE_LOGIN		NUMERIC(15,0)   ENCODE az64
,PROGRAM_UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
,PROGRAM_APPLICATION_ID		NUMERIC(15,0)   ENCODE az64
,PROGRAM_ID		NUMERIC(15,0)   ENCODE az64
,REQUEST_ID		NUMERIC(15,0)   ENCODE az64
,UPG_BATCH_ID		NUMERIC(15,0)   ENCODE az64
,UPG_SOURCE_APPLICATION_ID		NUMERIC(15,0)   ENCODE az64
,UPG_VALID_FLAG	VARCHAR(1)  ENCODE lzo
,ZERO_AMOUNT_FLAG	VARCHAR(1)  ENCODE lzo
,PARENT_AE_HEADER_ID		NUMERIC(15,0)   ENCODE az64
,PARENT_AE_LINE_NUM		NUMERIC(15,0)   ENCODE az64
,ACCRUAL_REVERSAL_FLAG	VARCHAR(1)  ENCODE lzo
,MERGE_EVENT_ID		NUMERIC(15,0)   ENCODE az64
,NEED_BAL_FLAG	VARCHAR(1)  ENCODE lzo
,KCA_OPERATION VARCHAR(10)   ENCODE lzo
,IS_DELETED_FLG VARCHAR(2) ENCODE lzo
,KCA_SEQ_ID NUMERIC(36,0)   ENCODE az64
,kca_seq_date TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
)
DISTSTYLE
auto;

INSERT INTO bec_ods.XLA_AE_HEADERS
(
AE_HEADER_ID
,APPLICATION_ID
,LEDGER_ID
,ENTITY_ID
,EVENT_ID
,EVENT_TYPE_CODE
,ACCOUNTING_DATE
,GL_TRANSFER_STATUS_CODE
,GL_TRANSFER_DATE
,JE_CATEGORY_NAME
,ACCOUNTING_ENTRY_STATUS_CODE
,ACCOUNTING_ENTRY_TYPE_CODE
,AMB_CONTEXT_CODE
,PRODUCT_RULE_TYPE_CODE
,PRODUCT_RULE_CODE
,PRODUCT_RULE_VERSION
,DESCRIPTION
,DOC_SEQUENCE_ID
,DOC_SEQUENCE_VALUE
,ACCOUNTING_BATCH_ID
,COMPLETION_ACCT_SEQ_VERSION_ID
,CLOSE_ACCT_SEQ_VERSION_ID
,COMPLETION_ACCT_SEQ_VALUE
,CLOSE_ACCT_SEQ_VALUE
,BUDGET_VERSION_ID
,FUNDS_STATUS_CODE
,ENCUMBRANCE_TYPE_ID
,BALANCE_TYPE_CODE
,REFERENCE_DATE
,COMPLETED_DATE
,PERIOD_NAME
,PACKET_ID
,COMPLETION_ACCT_SEQ_ASSIGN_ID
,CLOSE_ACCT_SEQ_ASSIGN_ID
,DOC_CATEGORY_CODE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,GROUP_ID
,DOC_SEQUENCE_VERSION_ID
,DOC_SEQUENCE_ASSIGN_ID
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,PROGRAM_UPDATE_DATE
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,REQUEST_ID
,UPG_BATCH_ID
,UPG_SOURCE_APPLICATION_ID
,UPG_VALID_FLAG
,ZERO_AMOUNT_FLAG
,PARENT_AE_HEADER_ID
,PARENT_AE_LINE_NUM
,ACCRUAL_REVERSAL_FLAG
,MERGE_EVENT_ID
,NEED_BAL_FLAG
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date
)
SELECT
AE_HEADER_ID
,APPLICATION_ID
,LEDGER_ID
,ENTITY_ID
,EVENT_ID
,EVENT_TYPE_CODE
,ACCOUNTING_DATE
,GL_TRANSFER_STATUS_CODE
,GL_TRANSFER_DATE
,JE_CATEGORY_NAME
,ACCOUNTING_ENTRY_STATUS_CODE
,ACCOUNTING_ENTRY_TYPE_CODE
,AMB_CONTEXT_CODE
,PRODUCT_RULE_TYPE_CODE
,PRODUCT_RULE_CODE
,PRODUCT_RULE_VERSION
,DESCRIPTION
,DOC_SEQUENCE_ID
,DOC_SEQUENCE_VALUE
,ACCOUNTING_BATCH_ID
,COMPLETION_ACCT_SEQ_VERSION_ID
,CLOSE_ACCT_SEQ_VERSION_ID
,COMPLETION_ACCT_SEQ_VALUE
,CLOSE_ACCT_SEQ_VALUE
,BUDGET_VERSION_ID
,FUNDS_STATUS_CODE
,ENCUMBRANCE_TYPE_ID
,BALANCE_TYPE_CODE
,REFERENCE_DATE
,COMPLETED_DATE
,PERIOD_NAME
,PACKET_ID
,COMPLETION_ACCT_SEQ_ASSIGN_ID
,CLOSE_ACCT_SEQ_ASSIGN_ID
,DOC_CATEGORY_CODE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,GROUP_ID
,DOC_SEQUENCE_VERSION_ID
,DOC_SEQUENCE_ASSIGN_ID
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,PROGRAM_UPDATE_DATE
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,REQUEST_ID
,UPG_BATCH_ID
,UPG_SOURCE_APPLICATION_ID
,UPG_VALID_FLAG
,ZERO_AMOUNT_FLAG
,PARENT_AE_HEADER_ID
,PARENT_AE_LINE_NUM
,ACCRUAL_REVERSAL_FLAG
,MERGE_EVENT_ID
,NEED_BAL_FLAG
,KCA_OPERATION
,'N' as IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID
,kca_seq_date
    FROM
        bec_ods_stg.XLA_AE_HEADERS;

end;		

UPDATE bec_etl_ctrl.batch_ods_info
SET
    load_type = 'I',
    last_refresh_date = getdate()
WHERE
    ods_table_name = 'xla_ae_headers';

COMMIT;	