/*
	# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
	#
	# Unless required by applicable law or agreed to in writing, software
	# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
	# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	#
	# author: KPI Partners, Inc.
	# version: 2022.06
	# description: This script represents full incremental approach for ODS.
	# File Version: KPI v1.0
*/
begin;
	drop table if exists bec_ods.XXBEC_INVENTORY_VALUE_RPT;
	
	CREATE TABLE IF NOT EXISTS bec_ods.XXBEC_INVENTORY_VALUE_RPT
	(
		AS_OF_DATE TIMESTAMP WITHOUT TIME ZONE ENCODE az64, 
		INV_CATEGORY VARCHAR(150) ENCODE lzo, 
		INV_SUBCATEGORY VARCHAR(150) ENCODE lzo, 
		SUBINVENTORY VARCHAR(10) ENCODE lzo, 
		LOCATOR VARCHAR(122) ENCODE lzo, 
		PART_NUMBER VARCHAR(40) ENCODE lzo, 
		DESCRIPTION VARCHAR(240) ENCODE lzo, 
		INVENTORY_ITEM_STATUS_CODE VARCHAR(10) ENCODE lzo, 
		CATEGORY_SEGMENT1 VARCHAR(40) ENCODE lzo, 
		CATEGORY_SEGMENT2 VARCHAR(40) ENCODE lzo, 
		CATEGORY VARCHAR(81) ENCODE lzo, 
		PRIMARY_UOM_CODE VARCHAR(3) ENCODE lzo, 
		QUANTITY NUMERIC(28,10) ENCODE az64, 
		ITEM_COST NUMERIC(28,10) ENCODE az64, 
		EXTENDED_COST NUMERIC(28,10) ENCODE az64, 
		ORGANIZATION_ID NUMERIC(15,0) ENCODE az64, 
		ORGANIZATION_NAME VARCHAR(240) ENCODE lzo, 
		ORGANIZATION_CODE VARCHAR(3) ENCODE lzo, 
		VMI_FLAG VARCHAR(1) ENCODE lzo, 
		OWNING_ORGANIZATION_ID NUMERIC(15,0) ENCODE az64, 
		SUBINVENTORY_TYPE VARCHAR(40) ENCODE lzo, 
		MATERIAL_COST NUMERIC(28,10) ENCODE az64, 
		MATERIAL_OVERHEAD_COST NUMERIC(28,10) ENCODE az64, 
		RESOURCE_COST NUMERIC(28,10) ENCODE az64, 
		OUTSIDE_PROCESSING_COST NUMERIC(28,10) ENCODE az64, 
		OVERHEAD_COST NUMERIC(28,10) ENCODE az64, 
		EXT_MATERIAL_COST NUMERIC(28,10) ENCODE az64, 
		EXT_MATERIAL_OVERHEAD_COST NUMERIC(28,10) ENCODE az64, 
		EXT_RESOURCE_COST NUMERIC(28,10) ENCODE az64, 
		EXT_OUTSIDE_PROCESSING_COST NUMERIC(28,10) ENCODE az64, 
		EXT_OVERHEAD_COST NUMERIC(28,10) ENCODE az64, 
		LOCATOR_ID NUMERIC(15,0) ENCODE az64, 
		kca_operation VARCHAR(10)   ENCODE lzo,
		is_deleted_flg VARCHAR(2) ENCODE lzo,
		kca_seq_id NUMERIC(36,0)   ENCODE az64,
		kca_seq_date TIMESTAMP WITHOUT TIME ZONE ENCODE az64
	)
	DISTSTYLE AUTO
	;
	
	insert into bec_ods.XXBEC_INVENTORY_VALUE_RPT
	(
		AS_OF_DATE, 
		INV_CATEGORY, 
		INV_SUBCATEGORY, 
		SUBINVENTORY, 
		LOCATOR, 
		PART_NUMBER, 
		DESCRIPTION, 
		INVENTORY_ITEM_STATUS_CODE, 
		CATEGORY_SEGMENT1, 
		CATEGORY_SEGMENT2, 
		CATEGORY, 
		PRIMARY_UOM_CODE, 
		QUANTITY, 
		ITEM_COST, 
		EXTENDED_COST, 
		ORGANIZATION_ID, 
		ORGANIZATION_NAME, 
		ORGANIZATION_CODE, 
		VMI_FLAG, 
		OWNING_ORGANIZATION_ID, 
		SUBINVENTORY_TYPE, 
		MATERIAL_COST, 
		MATERIAL_OVERHEAD_COST, 
		RESOURCE_COST, 
		OUTSIDE_PROCESSING_COST, 
		OVERHEAD_COST, 
		EXT_MATERIAL_COST, 
		EXT_MATERIAL_OVERHEAD_COST, 
		EXT_RESOURCE_COST, 
		EXT_OUTSIDE_PROCESSING_COST, 
		EXT_OVERHEAD_COST, 
		LOCATOR_ID, 
		kca_operation,
		is_deleted_flg,
		kca_seq_id,
		kca_seq_date
	)
	(
		select 
		AS_OF_DATE, 
		INV_CATEGORY, 
		INV_SUBCATEGORY, 
		SUBINVENTORY, 
		LOCATOR, 
		PART_NUMBER, 
		DESCRIPTION, 
		INVENTORY_ITEM_STATUS_CODE, 
		CATEGORY_SEGMENT1, 
		CATEGORY_SEGMENT2, 
		CATEGORY, 
		PRIMARY_UOM_CODE, 
		QUANTITY, 
		ITEM_COST, 
		EXTENDED_COST, 
		ORGANIZATION_ID, 
		ORGANIZATION_NAME, 
		ORGANIZATION_CODE, 
		VMI_FLAG, 
		OWNING_ORGANIZATION_ID, 
		SUBINVENTORY_TYPE, 
		MATERIAL_COST, 
		MATERIAL_OVERHEAD_COST, 
		RESOURCE_COST, 
		OUTSIDE_PROCESSING_COST, 
		OVERHEAD_COST, 
		EXT_MATERIAL_COST, 
		EXT_MATERIAL_OVERHEAD_COST, 
		EXT_RESOURCE_COST, 
		EXT_OUTSIDE_PROCESSING_COST, 
		EXT_OVERHEAD_COST, 
		LOCATOR_ID,  
		kca_operation,
		'N' as IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
		from bec_ods_stg.XXBEC_INVENTORY_VALUE_RPT
	);
	
end;

update bec_etl_ctrl.batch_ods_info 
set load_type = 'I', 
last_refresh_date = getdate() 
where ods_table_name='xxbec_inventory_value_rpt'; 

commit;