DROP table IF EXISTS gold_bec_dwh.DIM_AR_CUSTOMER_SITES;
CREATE TABLE gold_bec_dwh.DIM_AR_CUSTOMER_SITES AS
(
  SELECT
    RS.SALESREP_ID,
    RS.RESOURCE_ID,
    RS.NAME AS SALESREP_NAME,
    RS.STATUS AS SALESREP_STATUS,
    RS.START_DATE_ACTIVE,
    RS.END_DATE_ACTIVE,
    RS.SALESREP_NUMBER,
    RS.ORG_ID,
    RS.PERSON_ID,
    PARTIES.PARTY_ID,
    PARTIES.PARTY_NUMBER,
    PARTIES.PARTY_NAME,
    PARTIES.PARTY_TYPE,
    PARTIES.COUNTRY,
    PARTIES.ADDRESS1,
    PARTIES.ADDRESS2,
    PARTIES.ADDRESS3,
    PARTIES.ADDRESS4,
    PARTIES.CITY,
    PARTIES.POSTAL_CODE,
    PARTIES.STATE,
    PARTIES.PROVINCE,
    PARTIES.STATUS AS PARTIES_STATUS,
    PARTIES.COUNTY,
    PARTIES.CATEGORY_CODE,
    HZCA.CUST_ACCOUNT_ID,
    HZCA.ACCOUNT_NUMBER,
    HZCA.STATUS AS CUST_ACCOUNT_STATUS,
    HZCA.CUSTOMER_TYPE,
    HZCA.CUSTOMER_CLASS_CODE,
    HZCA.WAREHOUSE_ID,
    HZCA.ACCOUNT_NAME,
    HCAS.CUST_ACCT_SITE_ID,
    HCSS.SITE_USE_ID,
    HCSS.SITE_USE_CODE,
    HCSS.PRIMARY_FLAG,
    HCSS.STATUS AS CUST_SITE_ACCT_STATUS,
    HCSS.LOCATION AS SITE_LOCATION,
    HCSS.WAREHOUSE_ID AS CUST_SITE_USE_WAREHOUSE_ID,
    HCSS.ORG_ID AS CUST_SITE_USE_ORG_ID,
    HCSS.LAST_UPDATE_DATE,
    RC.CUSTOMER_NAME AS CUSTOMER_NAME,
    RC.CUSTOMER_NUMBER AS CUSTOMER_NUMBER,
    RC.CUSTOMER_CATEGORY_CODE AS CUSTOMER_CATEGORY,
    RC.CUSTOMER_CLASS_CODE AS CUSTOMER_CLASS,
    RC.SALES_CHANNEL_CODE AS CUSTOMER_CHANNEL,
    PRO.PROFILE_CLASS_ID,
    COLL.COLLECTOR_ID,
    COLL.NAME AS COLLECTOR_NAME,
    COLL.EMPLOYEE_ID,
    COLL.DESCRIPTION,
    COLL.STATUS AS COLLECTOR_STAUS,
    COLL.INACTIVE_DATE,
    COLL.ALIAS AS COLLECTOR_ALIAS,
    'N' AS is_deleted_flg,
    (
      SELECT
        system_id
      FROM bec_etl_ctrl.etlsourceappid
      WHERE
        source_system = 'EBS'
    ) AS source_app_id,
    (
      SELECT
        system_id
      FROM bec_etl_ctrl.etlsourceappid
      WHERE
        source_system = 'EBS'
    ) || '-' || COALESCE(HCSS.SITE_USE_ID, 0) AS dw_load_id,
    CURRENT_TIMESTAMP() AS dw_insert_date,
    CURRENT_TIMESTAMP() AS dw_update_date
  FROM silver_bec_ods.JTF_RS_SALESREPS AS RS, silver_bec_ods.HZ_PARTIES AS PARTIES, silver_bec_ods.HZ_CUST_ACCOUNTS AS HZCA, silver_bec_ods.HZ_CUST_ACCT_SITES_ALL AS HCAS, silver_bec_ods.HZ_CUST_SITE_USES_ALL AS HCSS, silver_bec_ods.AR_CUSTOMERS AS RC, silver_bec_ods.HZ_CUSTOMER_PROFILES AS PRO, silver_bec_ods.HZ_CUST_PROFILE_CLASSES AS PRC, silver_bec_ods.AR_COLLECTORS AS COLL
  WHERE
    HCSS.CUST_ACCT_SITE_ID = HCAS.CUST_ACCT_SITE_ID
    AND HCAS.CUST_ACCOUNT_ID = HZCA.CUST_ACCOUNT_ID
    AND HZCA.PARTY_ID = PARTIES.PARTY_ID
    AND HZCA.CUST_ACCOUNT_ID = RC.CUSTOMER_ID
    AND HCSS.PRIMARY_SALESREP_ID = RS.SALESREP_ID()
    AND HCSS.SITE_USE_ID = PRO.SITE_USE_ID()
    AND PRO.PROFILE_CLASS_ID = PRC.PROFILE_CLASS_ID()
    AND PRO.COLLECTOR_ID = COLL.COLLECTOR_ID()
    AND HCSS.ORG_ID = RS.ORG_ID()
);
UPDATE bec_etl_ctrl.batch_dw_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  dw_table_name = 'dim_ar_customer_sites' AND batch_name = 'ar';