DROP table IF EXISTS gold_bec_dwh.DIM_INV_ITEM_CATEGORY_SET;
CREATE TABLE gold_bec_dwh.DIM_INV_ITEM_CATEGORY_SET AS
(
  SELECT
    COALESCE(MIC.INVENTORY_ITEM_ID, 0) AS INVENTORY_ITEM_ID,
    COALESCE(MIC.ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
    COALESCE(MIC.CATEGORY_SET_ID, 0) AS CATEGORY_SET_ID,
    COALESCE(MC.STRUCTURE_ID, 0) AS STRUCTURE_ID,
    COALESCE(MIC.CATEGORY_ID, 0) AS CATEGORY_ID,
    MSI.SEGMENT1 AS `ITEM_NAME`,
    MSI.DESCRIPTION AS `ITEM_DESCRIPTION`,
    CSET.CATEGORY_SET_NAME,
    CSET.DESCRIPTION AS `CATEGORY_SET_DESC`,
    MC.SEGMENT1 AS `ITEM_CATEGORY_SEGMENT1`,
    COALESCE(MC.SEGMENT2, 'LEVEL2') AS `ITEM_CATEGORY_SEGMENT2`,
    COALESCE(MC.SEGMENT3, 'LEVEL3') AS `ITEM_CATEGORY_SEGMENT3`,
    COALESCE(MC.SEGMENT4, 'LEVEL4') AS `ITEM_CATEGORY_SEGMENT4`,
    MC.DESCRIPTION AS `ITEM_CATEGORY_DESC`,
    'N' AS is_deleted_flg,
    (
      SELECT
        system_id
      FROM bec_etl_ctrl.etlsourceappid
      WHERE
        source_system = 'EBS'
    ) AS source_app_id,
    (
      SELECT
        system_id
      FROM bec_etl_ctrl.etlsourceappid
      WHERE
        source_system = 'EBS'
    ) || '-' || COALESCE(MIC.INVENTORY_ITEM_ID, 0) || '-' || COALESCE(MIC.ORGANIZATION_ID, 0) || '-' || COALESCE(MC.CATEGORY_ID, 0) || '-' || COALESCE(MIC.CATEGORY_SET_ID, 0) AS dw_load_id,
    CURRENT_TIMESTAMP() AS dw_insert_date,
    CURRENT_TIMESTAMP() AS dw_update_date
  FROM silver_bec_ods.MTL_ITEM_CATEGORIES AS MIC, silver_bec_ods.MTL_CATEGORY_SETS_TL AS CSET, silver_bec_ods.MTL_SYSTEM_ITEMS_B AS MSI, silver_bec_ods.MTL_CATEGORIES_B AS MC
  WHERE
    1 = 1
    AND MIC.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
    AND MIC.ORGANIZATION_ID = MSI.ORGANIZATION_ID
    AND MIC.CATEGORY_SET_ID = CSET.CATEGORY_SET_ID
    AND MIC.CATEGORY_ID = MC.CATEGORY_ID
    AND CSET.LANGUAGE = 'US'
);
UPDATE bec_etl_ctrl.batch_dw_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  dw_table_name = 'dim_inv_item_category_set' AND batch_name = 'ap';