DROP table IF EXISTS gold_bec_dwh.DIM_PO_AP_BRIDGE;
CREATE TABLE gold_bec_dwh.DIM_PO_AP_BRIDGE AS
(
  SELECT DISTINCT
    INV.ORG_ID,
    INV.INVOICE_ID,
    INV.VENDOR_ID,
    INV.VENDOR_SITE_ID,
    PAY.CHECK_ID,
    INV.PO_HEADER_ID,
    INV.PO_LINE_ID,
    INV.PO_RELEASE_ID,
    INV.HOLD_ID,
    INV.PO_LINE_LOCATION_ID,
    INV.RCV_SHIPMENT_LINE_ID,
    INV.PO_DISTRIBUTION_ID,
    INV.LINE_NUMBER,
    INV.INVOICE_NUM,
    PAY.CHECK_NUMBER,
    INV.INVOICE_DATE,
    INV.GL_DATE AS INV_GL_DATE,
    INV.INVOICE_CREATION_DATE,
    INV.INVOICE_LINE_AMOUNT,
    INV.INVOICE_TOTAL_AMOUNT,
    INV.IS_INV_ON_HOLD,
    INV.HOLD_REASON,
    INV.RELEASE_REASON,
    INV.PAYMENT_TERMS,
    SCH_DD.INVOICE_DUE_DATE,
    PAY.INVOICE_PAYMENT_ID,
    PAY.PAYMENT_DATE,
    PAY.CHECK_DATE,
    PAY.CHECK_CREATION_DATE,
    PAY.PAYMENT_METHOD_CODE,
    PAY.AMOUNT_PAID,
    SCH_DD.PAYMENT_NUM,
    INV.INVOICE_TYPE_LOOKUP_CODE,
    RSH.PO_RELEASE_NUMBER,
    RSH.RECEIPT_DATE,
    RSH.RECEIPT_NUMBER,
    'N' AS is_deleted_flg,
    (
      SELECT
        system_id
      FROM bec_etl_ctrl.etlsourceappid
      WHERE
        source_system = 'EBS'
    ) AS source_app_id,
    (
      SELECT
        system_id
      FROM bec_etl_ctrl.etlsourceappid
      WHERE
        source_system = 'EBS'
    ) || '-' || COALESCE(INV.INVOICE_ID, 0) || '-' || COALESCE(INV.LINE_NUMBER, 0) || '-' || COALESCE(PAY.INVOICE_PAYMENT_ID, 0) || '-' || COALESCE(INV.HOLD_ID, 0) || '-' || COALESCE(SCH_DD.PAYMENT_NUM, 0) || '-' || COALESCE(INV.PO_HEADER_ID, 0) || '-' || COALESCE(INV.PO_LINE_ID, 0) || '-' || COALESCE(INV.PO_RELEASE_ID, 0) || '-' || COALESCE(INV.PO_LINE_LOCATION_ID, 0) || '-' || COALESCE(INV.PO_DISTRIBUTION_ID, 0) || '-' || COALESCE(PAY.CHECK_ID, 0) || '-' || COALESCE(INV.RCV_SHIPMENT_LINE_ID, 0) AS dw_load_id,
    CURRENT_TIMESTAMP() AS dw_insert_date,
    CURRENT_TIMESTAMP() AS dw_update_date
  FROM (
    SELECT
      API.INVOICE_ID,
      API.ORG_ID,
      API.VENDOR_ID,
      API.VENDOR_SITE_ID,
      API.INVOICE_NUM,
      API.INVOICE_DATE,
      API.GL_DATE,
      API.CREATION_DATE AS INVOICE_CREATION_DATE,
      APIL.LINE_NUMBER,
      APIL.AMOUNT AS INVOICE_LINE_AMOUNT,
      API.INVOICE_AMOUNT AS INVOICE_TOTAL_AMOUNT,
      CASE
        WHEN APH.HOLD_REASON IS NULL
        THEN 'N'
        ELSE CASE WHEN APH.RELEASE_LOOKUP_CODE IS NULL THEN 'Y' ELSE 'N' END
      END AS IS_INV_ON_HOLD,
      APH.HOLD_REASON,
      APH.HOLD_ID,
      APH.RELEASE_REASON,
      APIL.PO_HEADER_ID,
      APIL.PO_LINE_ID,
      APIL.PO_RELEASE_ID,
      APIL.PO_LINE_LOCATION_ID,
      APIL.RCV_SHIPMENT_LINE_ID,
      APIL.PO_DISTRIBUTION_ID,
      APT.NAME AS PAYMENT_TERMS,
      API.INVOICE_TYPE_LOOKUP_CODE
    FROM silver_bec_ods.ap_invoices_all AS API, silver_bec_ods.AP_INVOICE_LINES_ALL AS APIL, silver_bec_ods.AP_TERMS AS APT, silver_bec_ods.AP_HOLDS_ALL AS APH, silver_bec_ods.AP_LOOKUP_CODES AS ALC
    WHERE
      API.INVOICE_ID = APIL.INVOICE_ID()
      AND API.CANCELLED_DATE IS NULL
      AND API.TERMS_ID = APT.TERM_ID()
      AND APIL.INVOICE_ID = APH.INVOICE_ID()
      AND APIL.PO_LINE_LOCATION_ID = APH.LINE_LOCATION_ID()
      AND APH.HOLD_LOOKUP_CODE = ALC.LOOKUP_CODE()
      AND ALC.LOOKUP_TYPE() = 'HOLD CODE'
      AND API.IS_DELETED_FLG <> 'Y'
  ) AS INV, (
    SELECT
      INVOICE_ID AS SCH_INVO_ID,
      DUE_DATE AS INVOICE_DUE_DATE,
      PAYMENT_NUM
    FROM silver_bec_ods.AP_PAYMENT_SCHEDULES_ALL
    WHERE
      1 = 1 AND IS_DELETED_FLG <> 'Y'
  ) AS SCH_DD, (
    SELECT
      AIP.INVOICE_ID,
      APC.CHECK_ID,
      AIP.INVOICE_PAYMENT_ID,
      AIP.CREATION_DATE AS PAYMENT_DATE,
      APC.CHECK_DATE,
      APC.CREATION_DATE AS CHECK_CREATION_DATE,
      APC.PAYMENT_METHOD_CODE,
      APC.CHECK_NUMBER,
      APC.AMOUNT AS AMOUNT_PAID
    FROM silver_bec_ods.AP_INVOICE_PAYMENTS_ALL AS AIP, silver_bec_ods.AP_CHECKS_ALL AS APC
    WHERE
      (
        AIP.REVERSAL_FLAG IS NULL OR AIP.REVERSAL_FLAG = 'N'
      )
      AND AIP.CHECK_ID = APC.CHECK_ID()
      AND AIP.IS_DELETED_FLG <> 'Y'
  ) AS PAY, (
    SELECT
      RSL.PO_LINE_LOCATION_ID,
      POR.PO_RELEASE_ID,
      POR.RELEASE_NUM AS PO_RELEASE_NUMBER,
      MAX(RSH.CREATION_DATE) AS RECEIPT_DATE,
      MAX(RSH.RECEIPT_NUM) AS RECEIPT_NUMBER
    FROM silver_bec_ods.po_line_locations_all AS poll, silver_bec_ods.RCV_SHIPMENT_LINES AS RSL, silver_bec_ods.RCV_SHIPMENT_HEADERS AS RSH, silver_bec_ods.PO_RELEASES_ALL AS POR
    WHERE
      1 = 1
      AND POLL.PO_RELEASE_ID = POR.PO_RELEASE_ID()
      AND POLL.LINE_LOCATION_ID = RSL.PO_LINE_LOCATION_ID()
      AND RSL.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID()
      AND POLL.IS_DELETED_FLG <> 'Y'
    GROUP BY
      RSL.PO_LINE_LOCATION_ID,
      POR.PO_RELEASE_ID,
      POR.RELEASE_NUM
  ) AS RSH
  WHERE
    1 = 1
    AND INV.INVOICE_ID = PAY.INVOICE_ID()
    AND INV.INVOICE_ID = SCH_DD.SCH_INVO_ID()
    AND INV.PO_LINE_LOCATION_ID = RSH.PO_LINE_LOCATION_ID()
);
UPDATE bec_etl_ctrl.batch_dw_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  dw_table_name = 'dim_po_ap_bridge' AND batch_name = 'po';