DROP TABLE IF EXISTS BEC_DWH.FACT_AR_RECEIPTS;
CREATE TABLE BEC_DWH.FACT_AR_RECEIPTS AS
(
  SELECT
    RECEIPT_APP,
    OPERATING_UNIT,
    RECEIVABLE_APPLICATION_ID,
    RECEIVABLE_APPLICATION_ID_KEY,
    GL_DATE,
    SET_OF_BOOKS_ID,
    APPLY_DATE,
    APPLICATION_TYPE,
    RCV_STATUS,
    RCV_AMOUNT_APPLIED,
    DISPLAY,
    GL_POSTED_DATE,
    ORG_ID_KEY,
    ORG_ID,
    RECEIPT_INFO,
    CASH_RECEIPT_ID,
    APPLIED_CUSTOMER_TRX_ID,
    APPLIED_PAYMENT_SCHEDULE_ID,
    RECEIPT_CURRENCY,
    PAY_FROM_CUSTOMER,
    RECEIPT_NUMBER,
    RECEIPT_DATE,
    BANK_ACCOUNT_ID,
    BANK_ACCT_USE_ID,
    RECEIPT_CUST_SITE_USE_ID,
    CUST_SITE_USE_ID_KEY,
    RECEIPT_METHOD_ID,
    AMOUNT_DUE_ORIGINAL,
    AMOUNT_DUE_REMAINING,
    AMOUNT_APPLIED,
    SCHEDULE_ID,
    DUE_DATE,
    PAYMENT_STATUS,
    RECEIPT_LEGAL_ENTITY,
    RECEIPT_AMOUNT_F,
    EXCHANGE_RATE,
    EXCHANGE_RATE_TYPE,
    EXCHANGE_RATE_DATE,
    REMIT_BANK_ACCT_USE_ID,
    INVOICE_INFO,
    INVOICE_ID,
    INVOICE_ID_KEY,
    INVOICE_NUMBER,
    INV_TRX_TYPE_ID,
    INV_TRX_TYPE_ID_KEY,
    INVOICE_DATE,
    INV_BILL_TO_CONTACT_ID,
    INV_SOLD_TO_SITE_USE_ID,
    INV_BILL_TO_CUST_ID,
    INV_BILL_TO_CUST_ID_KEY,
    INV_BILL_SITE_USE_ID,
    INV_SHIP_SITE_USE_ID,
    INV_BILL_TO_SITE_USE_ID_KEY,
    INV_SHIP_TO_SITE_USE_ID_KEY,
    INV_TERM_ID,
    INV_TERM_ID_KEY,
    INV_SALES_REP_ID,
    INV_SALES_REP_ID_KEY,
    INV_PO,
    INV_AMOUNT,
    INV_REMAINING_AMOUNT,
    RECEIPT_AMT_APPLIED_ON_INVOICE,
    AMOUNT_LINE_ITEMS_ORIGINAL,
    AMOUNT_LINE_ITEMS_REMAINING,
    INV_AMT_ADJUSTED,
    INV_AMT_DISPUTE,
    INV_AMT_CREDITTED,
    INV_CHARGES_AMT,
    INV_CHARGES_REMAINING,
    INV_FREIGHT_AMT,
    INV_FREIGHT_AMT_REMAINING,
    INV_TAX_ORIGINAL,
    INV_TAX_REMAINING,
    INV_DISCOUNT_EARNED,
    INV_DISCOUNT_UNEARNED,
    INV_PAY_SCHEDULE_ID,
    INV_DUE_DATE,
    INVOICE_STATUS,
    PROJ_NUM,
    INV_TERRITORY,
    INTERFACE_HEADER_ATTRIBUTE1,
    INTERFACE_HEADER_CONTEXT,
    INV_PAY_SITE_USE_ID,
    RECEIPT_APPLIED_DISTR_INFO,
    DIST_LINE_ID,
    RECEIPT_APP_DIST_LINE_ID_KEY,
    RECEIPT_APP_CC_ID,
    RECEIPT_APP_AMT_DR,
    RECEIPT_APP_AMT_CR,
    RECEIPT_APP_AMT_ACCT_DR,
    RECEIPT_APP_AMT_ACCT_CR,
    SOURCE_ID,
    RECEIPT_APPLIED_HISTORY_INFO,
    RECEIPT_HISTORY_ID,
    RECEIPT_HISTORY_ID_KEY,
    AMOUNT,
    ACCT_AMOUNT,
    CURRENT_FLAG,
    REVERSE_GL_DATE,
    EXCHANGE_GAIN_LOSS,
    SOURCE_NAME,
    'N' AS IS_DELETED_FLG,
    SOURCE_APP_ID,
    DW_LOAD_ID,
    DW_INSERT_DATE,
    DW_UPDATE_DATE,
    CASE WHEN RCV_STATUS = 'APP' THEN SUM(RCV_AMOUNT_APPLIED) END AS APPLIED_AMOUNT,
    CASE WHEN RCV_STATUS = 'UNAPP' THEN SUM(RCV_AMOUNT_APPLIED) END AS UNAPPLIED_AMOUNT,
    CAST(COALESCE(AMOUNT_DUE_ORIGINAL, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_AMOUNT_DUE_ORIGINAL,
    CAST(COALESCE(AMOUNT_DUE_REMAINING, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_AMOUNT_DUE_REMAINING,
    CAST(COALESCE(AMOUNT_APPLIED, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_AMOUNT_APPLIED,
    CAST(COALESCE(INV_AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_INV_AMOUNT,
    CAST(COALESCE(INV_REMAINING_AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_INV_REMAINING_AMOUNT,
    CAST(COALESCE(INV_FREIGHT_AMT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_INV_FREIGHT_AMT,
    CAST(COALESCE(INV_FREIGHT_AMT_REMAINING, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_INV_FREIGHT_AMT_REMAINING,
    CAST(COALESCE(ACCT_AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_ACCT_AMOUNT,
    CAST(COALESCE(AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_AMOUNT,
    CAST(COALESCE(RCV_AMOUNT_APPLIED, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)) AS GBL_CV_AMOUNT_APPLIED,
    (
      CASE
        WHEN RCV_STATUS = 'UNAPP'
        THEN SUM(RCV_AMOUNT_APPLIED) * CAST(COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2))
      END
    ) AS GBL_UNAPPLIED_AMOUNT
  FROM (
    SELECT
      'RECEIPT_APP' AS RECEIPT_APP,
      AR_RECEIVABLE_APPLICATIONS_ALL.ORG_ID AS OPERATING_UNIT,
      AR_RECEIVABLE_APPLICATIONS_ALL.RECEIVABLE_APPLICATION_ID AS RECEIVABLE_APPLICATION_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || AR_RECEIVABLE_APPLICATIONS_ALL.RECEIVABLE_APPLICATION_ID AS RECEIVABLE_APPLICATION_ID_KEY,
      AR_RECEIVABLE_APPLICATIONS_ALL.GL_DATE,
      AR_RECEIVABLE_APPLICATIONS_ALL.SET_OF_BOOKS_ID,
      AR_RECEIVABLE_APPLICATIONS_ALL.APPLY_DATE,
      AR_RECEIVABLE_APPLICATIONS_ALL.APPLICATION_TYPE,
      AR_RECEIVABLE_APPLICATIONS_ALL.STATUS AS RCV_STATUS,
      AR_RECEIVABLE_APPLICATIONS_ALL.AMOUNT_APPLIED AS RCV_AMOUNT_APPLIED,
      AR_RECEIVABLE_APPLICATIONS_ALL.DISPLAY,
      AR_RECEIVABLE_APPLICATIONS_ALL.GL_POSTED_DATE,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || AR_RECEIVABLE_APPLICATIONS_ALL.ORG_ID AS ORG_ID_KEY,
      AR_RECEIVABLE_APPLICATIONS_ALL.ORG_ID AS ORG_ID,
      'RECEIPT_INFO' AS RECEIPT_INFO,
      AR_RECEIVABLE_APPLICATIONS_ALL.CASH_RECEIPT_ID AS CASH_RECEIPT_ID,
      AR_RECEIVABLE_APPLICATIONS_ALL.APPLIED_CUSTOMER_TRX_ID,
      AR_RECEIVABLE_APPLICATIONS_ALL.APPLIED_PAYMENT_SCHEDULE_ID AS APPLIED_PAYMENT_SCHEDULE_ID,
      AR_CASH_RECEIPTS_ALL.CURRENCY_CODE AS RECEIPT_CURRENCY,
      AR_CASH_RECEIPTS_ALL.PAY_FROM_CUSTOMER,
      AR_CASH_RECEIPTS_ALL.RECEIPT_NUMBER AS RECEIPT_NUMBER,
      AR_CASH_RECEIPTS_ALL.RECEIPT_DATE AS RECEIPT_DATE,
      CE_BANK_ACCT_USES_ALL.BANK_ACCOUNT_ID,
      CE_BANK_ACCT_USES_ALL.BANK_ACCT_USE_ID,
      AR_CASH_RECEIPTS_ALL.CUSTOMER_SITE_USE_ID AS RECEIPT_CUST_SITE_USE_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || AR_CASH_RECEIPTS_ALL.CUSTOMER_SITE_USE_ID AS CUST_SITE_USE_ID_KEY,
      AR_CASH_RECEIPTS_ALL.RECEIPT_METHOD_ID,
      AR_PAYMENT_SCHEDULES_ALL1.AMOUNT_DUE_ORIGINAL,
      AR_PAYMENT_SCHEDULES_ALL1.AMOUNT_DUE_REMAINING,
      AR_PAYMENT_SCHEDULES_ALL1.AMOUNT_APPLIED,
      AR_PAYMENT_SCHEDULES_ALL1.PAYMENT_SCHEDULE_ID AS SCHEDULE_ID,
      AR_PAYMENT_SCHEDULES_ALL1.DUE_DATE AS DUE_DATE,
      AR_PAYMENT_SCHEDULES_ALL1.STATUS AS PAYMENT_STATUS,
      AR_CASH_RECEIPTS_ALL.LEGAL_ENTITY_ID AS RECEIPT_LEGAL_ENTITY,
      (
        AR_PAYMENT_SCHEDULES_ALL1.AMOUNT_DUE_ORIGINAL * AR_CASH_RECEIPTS_ALL.EXCHANGE_RATE
      ) AS RECEIPT_AMOUNT_F,
      AR_CASH_RECEIPTS_ALL.EXCHANGE_RATE AS EXCHANGE_RATE,
      AR_CASH_RECEIPTS_ALL.EXCHANGE_RATE_TYPE,
      AR_CASH_RECEIPTS_ALL.EXCHANGE_DATE AS exchange_rate_date,
      AR_CASH_RECEIPTS_ALL.REMIT_BANK_ACCT_USE_ID,
      'INVOICE_INFO' AS INVOICE_INFO,
      RA_CUSTOMER_TRX_ALL.CUSTOMER_TRX_ID AS INVOICE_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || RA_CUSTOMER_TRX_ALL.CUSTOMER_TRX_ID AS INVOICE_ID_KEY,
      RA_CUSTOMER_TRX_ALL.TRX_NUMBER AS INVOICE_NUMBER,
      RA_CUSTOMER_TRX_ALL.CUST_TRX_TYPE_ID AS INV_TRX_TYPE_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || RA_CUSTOMER_TRX_ALL.CUST_TRX_TYPE_ID AS INV_TRX_TYPE_ID_KEY,
      RA_CUSTOMER_TRX_ALL.TRX_DATE AS INVOICE_DATE,
      RA_CUSTOMER_TRX_ALL.BILL_TO_CONTACT_ID AS INV_BILL_TO_CONTACT_ID,
      RA_CUSTOMER_TRX_ALL.SOLD_TO_SITE_USE_ID AS INV_SOLD_TO_SITE_USE_ID,
      RA_CUSTOMER_TRX_ALL.BILL_TO_CUSTOMER_ID AS INV_BILL_TO_CUST_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || RA_CUSTOMER_TRX_ALL.BILL_TO_CUSTOMER_ID AS INV_BILL_TO_CUST_ID_KEY,
      RA_CUSTOMER_TRX_ALL.BILL_TO_SITE_USE_ID AS INV_BILL_SITE_USE_ID,
      RA_CUSTOMER_TRX_ALL.SHIP_TO_SITE_USE_ID AS INV_SHIP_SITE_USE_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || RA_CUSTOMER_TRX_ALL.BILL_TO_SITE_USE_ID AS INV_BILL_TO_SITE_USE_ID_KEY,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || RA_CUSTOMER_TRX_ALL.SHIP_TO_SITE_USE_ID AS INV_SHIP_TO_SITE_USE_ID_KEY,
      RA_CUSTOMER_TRX_ALL.TERM_ID AS INV_TERM_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || RA_CUSTOMER_TRX_ALL.TERM_ID AS INV_TERM_ID_KEY,
      RA_CUSTOMER_TRX_ALL.PRIMARY_SALESREP_ID AS INV_SALES_REP_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || RA_CUSTOMER_TRX_ALL.PRIMARY_SALESREP_ID AS INV_SALES_REP_ID_KEY,
      RA_CUSTOMER_TRX_ALL.PURCHASE_ORDER AS INV_PO,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_DUE_ORIGINAL AS INV_AMOUNT,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_DUE_REMAINING AS INV_REMAINING_AMOUNT,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_APPLIED AS RECEIPT_AMT_APPLIED_ON_INVOICE,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_LINE_ITEMS_ORIGINAL,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_LINE_ITEMS_REMAINING,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_ADJUSTED AS INV_AMT_ADJUSTED,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_IN_DISPUTE AS INV_AMT_DISPUTE,
      AR_PAYMENT_SCHEDULES_ALL.AMOUNT_CREDITED AS INV_AMT_CREDITTED,
      AR_PAYMENT_SCHEDULES_ALL.RECEIVABLES_CHARGES_CHARGED AS INV_CHARGES_AMT,
      AR_PAYMENT_SCHEDULES_ALL.RECEIVABLES_CHARGES_REMAINING AS INV_CHARGES_REMAINING,
      AR_PAYMENT_SCHEDULES_ALL.FREIGHT_ORIGINAL AS INV_FREIGHT_AMT,
      AR_PAYMENT_SCHEDULES_ALL.FREIGHT_REMAINING AS INV_FREIGHT_AMT_REMAINING,
      AR_PAYMENT_SCHEDULES_ALL.TAX_ORIGINAL AS INV_TAX_ORIGINAL,
      AR_PAYMENT_SCHEDULES_ALL.TAX_REMAINING AS INV_TAX_REMAINING,
      AR_PAYMENT_SCHEDULES_ALL.DISCOUNT_TAKEN_EARNED AS INV_DISCOUNT_EARNED,
      AR_PAYMENT_SCHEDULES_ALL.DISCOUNT_TAKEN_UNEARNED AS INV_DISCOUNT_UNEARNED,
      AR_PAYMENT_SCHEDULES_ALL.PAYMENT_SCHEDULE_ID AS INV_PAY_SCHEDULE_ID,
      AR_PAYMENT_SCHEDULES_ALL.DUE_DATE AS INV_DUE_DATE,
      AR_PAYMENT_SCHEDULES_ALL.STATUS AS INVOICE_STATUS,
      RA_CUSTOMER_TRX_ALL.INTERFACE_HEADER_ATTRIBUTE1 AS PROJ_NUM,
      RA_CUSTOMER_TRX_ALL.TERRITORY_ID AS INV_TERRITORY,
      RA_CUSTOMER_TRX_ALL.INTERFACE_HEADER_ATTRIBUTE1,
      RA_CUSTOMER_TRX_ALL.INTERFACE_HEADER_CONTEXT,
      RA_CUSTOMER_TRX_ALL.PAYING_SITE_USE_ID AS INV_PAY_SITE_USE_ID,
      'RECEIPT_APPLIED_DISTR_INFO' AS RECEIPT_APPLIED_DISTR_INFO,
      AR_DISTRIBUTIONS_ALL.LINE_ID AS DIST_LINE_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || AR_DISTRIBUTIONS_ALL.LINE_ID AS RECEIPT_APP_DIST_LINE_ID_KEY,
      AR_DISTRIBUTIONS_ALL.CODE_COMBINATION_ID AS RECEIPT_APP_CC_ID,
      AR_DISTRIBUTIONS_ALL.AMOUNT_DR AS RECEIPT_APP_AMT_DR,
      AR_DISTRIBUTIONS_ALL.AMOUNT_CR AS RECEIPT_APP_AMT_CR,
      AR_DISTRIBUTIONS_ALL.ACCTD_AMOUNT_DR AS RECEIPT_APP_AMT_ACCT_DR,
      AR_DISTRIBUTIONS_ALL.ACCTD_AMOUNT_CR AS RECEIPT_APP_AMT_ACCT_CR,
      AR_DISTRIBUTIONS_ALL.SOURCE_ID AS SOURCE_ID,
      'RECEIPT_APPLIED_HISTORY_INFO' AS RECEIPT_APPLIED_HISTORY_INFO,
      AR_RECEIVABLE_APPLICATIONS_ALL.CASH_RECEIPT_HISTORY_ID AS RECEIPT_HISTORY_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || AR_RECEIVABLE_APPLICATIONS_ALL.CASH_RECEIPT_HISTORY_ID AS RECEIPT_HISTORY_ID_KEY,
      AR_CASH_RECEIPT_HISTORY_ALL.AMOUNT AS AMOUNT,
      AR_CASH_RECEIPT_HISTORY_ALL.ACCTD_AMOUNT AS ACCT_AMOUNT,
      AR_CASH_RECEIPT_HISTORY_ALL.CURRENT_RECORD_FLAG AS CURRENT_FLAG,
      AR_CASH_RECEIPT_HISTORY_ALL.REVERSAL_GL_DATE AS REVERSE_GL_DATE,
      CASE
        WHEN SIGN(AR_RECEIVABLE_APPLICATIONS_ALL.applied_payment_schedule_id) = -1
        OR (
          SIGN(AR_RECEIVABLE_APPLICATIONS_ALL.applied_payment_schedule_id) IS NULL
          AND -1 IS NULL
        )
        THEN NULL
        ELSE AR_RECEIVABLE_APPLICATIONS_ALL.acctd_amount_applied_from - COALESCE(
          AR_RECEIVABLE_APPLICATIONS_ALL.acctd_amount_applied_to,
          AR_RECEIVABLE_APPLICATIONS_ALL.acctd_amount_applied_from
        )
      END AS EXCHANGE_GAIN_LOSS,
      ra_batch_sources_all.name AS source_name,
      'N' AS IS_DELETED_FLG, /* decode( */ /* (AR_RECEIVABLE_APPLICATIONS_ALL.applied_payment_schedule_id), 1,null */ /* (AR_RECEIVABLE_APPLICATIONS_ALL.acctd_amount_applied_from) - */ /* nvl(AR_RECEIVABLE_APPLICATIONS_ALL.acctd_amount_applied_to, AR_RECEIVABLE_APPLICATIONS_ALL.acctd_amount_applied_from) */ /* )     as EXCHANGE_GAIN_LOSS,                                                                                                    , */
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) AS SOURCE_APP_ID,
      (
        SELECT
          SYSTEM_ID
        FROM BEC_ETL_CTRL.ETLSOURCEAPPID
        WHERE
          SOURCE_SYSTEM = 'EBS'
      ) || '-' || COALESCE(AR_RECEIVABLE_APPLICATIONS_ALL.CASH_RECEIPT_ID, 0) || '-' || COALESCE(AR_DISTRIBUTIONS_ALL.LINE_ID, 0) || '-' || COALESCE(ra_batch_sources_all.name, 'NA') AS DW_LOAD_ID,
      CURRENT_TIMESTAMP() AS DW_INSERT_DATE,
      CURRENT_TIMESTAMP() AS DW_UPDATE_DATE
    FROM (
      SELECT
        *
      FROM silver_bec_ods.AR_RECEIVABLE_APPLICATIONS_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS AR_RECEIVABLE_APPLICATIONS_ALL
    LEFT OUTER JOIN (
      SELECT
        *
      FROM silver_bec_ods.RA_CUSTOMER_TRX_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS RA_CUSTOMER_TRX_ALL
      ON RA_CUSTOMER_TRX_ALL.CUSTOMER_TRX_ID = AR_RECEIVABLE_APPLICATIONS_ALL.APPLIED_CUSTOMER_TRX_ID
    INNER JOIN (
      SELECT
        *
      FROM silver_bec_ods.AR_DISTRIBUTIONS_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS AR_DISTRIBUTIONS_ALL
      ON AR_RECEIVABLE_APPLICATIONS_ALL.RECEIVABLE_APPLICATION_ID = AR_DISTRIBUTIONS_ALL.SOURCE_ID
    LEFT OUTER JOIN (
      SELECT
        *
      FROM silver_bec_ods.AR_PAYMENT_SCHEDULES_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS AR_PAYMENT_SCHEDULES_ALL
      ON AR_PAYMENT_SCHEDULES_ALL.PAYMENT_SCHEDULE_ID = AR_RECEIVABLE_APPLICATIONS_ALL.APPLIED_PAYMENT_SCHEDULE_ID
    INNER JOIN (
      SELECT
        *
      FROM silver_bec_ods.AR_CASH_RECEIPTS_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS AR_CASH_RECEIPTS_ALL
      ON AR_CASH_RECEIPTS_ALL.CASH_RECEIPT_ID = AR_RECEIVABLE_APPLICATIONS_ALL.CASH_RECEIPT_ID
    INNER JOIN (
      SELECT
        *
      FROM silver_bec_ods.AR_PAYMENT_SCHEDULES_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS AR_PAYMENT_SCHEDULES_ALL1
      ON AR_PAYMENT_SCHEDULES_ALL1.PAYMENT_SCHEDULE_ID = AR_RECEIVABLE_APPLICATIONS_ALL.PAYMENT_SCHEDULE_ID
    LEFT OUTER JOIN (
      SELECT
        *
      FROM silver_bec_ods.CE_BANK_ACCT_USES_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS CE_BANK_ACCT_USES_ALL
      ON AR_CASH_RECEIPTS_ALL.REMIT_BANK_ACCT_USE_ID = CE_BANK_ACCT_USES_ALL.BANK_ACCT_USE_ID
    INNER JOIN (
      SELECT
        *
      FROM silver_bec_ods.AR_CASH_RECEIPT_HISTORY_ALL
      WHERE
        is_deleted_flg <> 'Y'
    ) AS AR_CASH_RECEIPT_HISTORY_ALL
      ON AR_CASH_RECEIPT_HISTORY_ALL.CASH_RECEIPT_HISTORY_ID = AR_RECEIVABLE_APPLICATIONS_ALL.CASH_RECEIPT_HISTORY_ID
    LEFT OUTER JOIN (
      SELECT
        *
      FROM silver_bec_ods.ra_batch_sources_all
      WHERE
        is_deleted_flg <> 'Y'
    ) AS ra_batch_sources_all
      ON ra_customer_trx_all.batch_source_id = ra_batch_sources_all.batch_source_id
    WHERE
      AR_DISTRIBUTIONS_ALL.SOURCE_TABLE = 'RA'
      AND AR_DISTRIBUTIONS_ALL.SOURCE_TYPE IN ('REC', 'UNAPP', 'ACC', 'UNID', 'OTHER ACC')
      AND AR_RECEIVABLE_APPLICATIONS_ALL.APPLICATION_TYPE = 'CASH'
      AND COALESCE(AR_RECEIVABLE_APPLICATIONS_ALL.CONFIRMED_FLAG, 'Y') = 'Y'
  ) AS a
  LEFT OUTER JOIN (
    SELECT
      *
    FROM silver_bec_ods.GL_DAILY_RATES
    WHERE
      is_deleted_flg <> 'Y' AND to_currency = 'USD' AND conversion_type = 'Corporate'
  ) AS DCR
    ON a.RECEIPT_CURRENCY = DCR.from_currency AND DCR.conversion_date = a.GL_DATE
  GROUP BY
    receipt_app,
    operating_unit,
    receivable_application_id,
    receivable_application_id_key,
    gl_date,
    set_of_books_id,
    apply_date,
    application_type,
    RCV_STATUS,
    RCV_AMOUNT_APPLIED,
    display,
    gl_posted_date,
    org_id_key,
    ORG_ID,
    receipt_info,
    CASH_RECEIPT_ID,
    applied_customer_trx_id,
    applied_payment_schedule_id,
    receipt_currency,
    pay_from_customer,
    receipt_number,
    receipt_date,
    bank_account_id,
    bank_acct_use_id,
    receipt_cust_site_use_id,
    cust_site_use_id_key,
    receipt_method_id,
    amount_due_original,
    amount_due_remaining,
    amount_applied,
    schedule_id,
    due_date,
    payment_status,
    receipt_legal_entity,
    receipt_amount_f,
    exchange_rate,
    exchange_rate_type,
    exchange_rate_date,
    remit_bank_acct_use_id,
    invoice_info,
    invoice_id,
    invoice_id_key,
    invoice_number,
    inv_trx_type_id,
    inv_trx_type_id_key,
    invoice_date,
    inv_bill_to_contact_id,
    inv_sold_to_site_use_id,
    inv_bill_to_cust_id,
    inv_bill_to_cust_id_key,
    inv_bill_site_use_id,
    inv_ship_site_use_id,
    inv_bill_to_site_use_id_key,
    inv_ship_to_site_use_id_key,
    inv_term_id,
    inv_term_id_key,
    inv_sales_rep_id,
    inv_sales_rep_id_key,
    inv_po,
    inv_amount,
    inv_remaining_amount,
    receipt_amt_applied_on_invoice,
    amount_line_items_original,
    amount_line_items_remaining,
    inv_amt_adjusted,
    inv_amt_dispute,
    inv_amt_creditted,
    inv_charges_amt,
    inv_charges_remaining,
    inv_freight_amt,
    inv_freight_amt_remaining,
    inv_tax_original,
    inv_tax_remaining,
    inv_discount_earned,
    inv_discount_unearned,
    inv_pay_schedule_id,
    inv_due_date,
    invoice_status,
    proj_num,
    inv_territory,
    interface_header_attribute1,
    interface_header_context,
    inv_pay_site_use_id,
    receipt_applied_distr_info,
    DIST_LINE_ID,
    RECEIPT_APP_DIST_LINE_ID_KEY,
    RECEIPT_APP_CC_ID,
    RECEIPT_APP_AMT_DR,
    RECEIPT_APP_AMT_CR,
    RECEIPT_APP_AMT_ACCT_DR,
    RECEIPT_APP_AMT_ACCT_CR,
    SOURCE_ID,
    RECEIPT_APPLIED_HISTORY_INFO,
    RECEIPT_HISTORY_ID,
    RECEIPT_HISTORY_ID_KEY,
    amount,
    acct_amount,
    current_flag,
    reverse_gl_date,
    exchange_gain_loss,
    source_name,
    a.IS_DELETED_FLG,
    source_app_id,
    dw_load_id,
    dw_insert_date,
    dw_update_date,
    CAST(COALESCE(AMOUNT_DUE_ORIGINAL, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(AMOUNT_DUE_REMAINING, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(AMOUNT_APPLIED, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(INV_AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(INV_REMAINING_AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(INV_FREIGHT_AMT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(INV_FREIGHT_AMT_REMAINING, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(ACCT_AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(AMOUNT, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    CAST(COALESCE(RCV_AMOUNT_APPLIED, 0) * COALESCE(DCR.conversion_rate, 1) AS DECIMAL(18, 2)),
    COALESCE(DCR.conversion_rate, 1)
);
UPDATE bec_etl_ctrl.batch_dw_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  dw_table_name = 'fact_ar_receipts' AND batch_name = 'ar';