DROP TABLE IF EXISTS BEC_DWH.FACT_INV_RELATED_ITEMS;
CREATE TABLE BEC_DWH.FACT_INV_RELATED_ITEMS AS
(
  SELECT
    INVENTORY_ITEM_ID,
    ORGANIZATION_ID,
    RELATED_ITEM_ID,
    relationship_type_id,
    reciprocal_flag,
    PLANNING_ENABLED_FLAG,
    START_DATE,
    END_DATE,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    (
      SELECT
        SYSTEM_ID
      FROM BEC_ETL_CTRL.ETLSOURCEAPPID
      WHERE
        SOURCE_SYSTEM = 'EBS'
    ) || '-' || INVENTORY_ITEM_ID AS INVENTORY_ITEM_ID_KEY,
    (
      SELECT
        SYSTEM_ID
      FROM BEC_ETL_CTRL.ETLSOURCEAPPID
      WHERE
        SOURCE_SYSTEM = 'EBS'
    ) || '-' || ORGANIZATION_ID AS ORGANIZATION_ID_KEY,
    (
      SELECT
        SYSTEM_ID
      FROM BEC_ETL_CTRL.ETLSOURCEAPPID
      WHERE
        SOURCE_SYSTEM = 'EBS'
    ) || '-' || RELATED_ITEM_ID AS RELATED_ITEM_ID_KEY,
    (
      SELECT
        SYSTEM_ID
      FROM BEC_ETL_CTRL.ETLSOURCEAPPID
      WHERE
        SOURCE_SYSTEM = 'EBS'
    ) || '-' || RELATIONSHIP_TYPE_ID AS RELATIONSHIP_TYPE_ID_KEY,
    (
      SELECT
        SYSTEM_ID
      FROM BEC_ETL_CTRL.ETLSOURCEAPPID
      WHERE
        SOURCE_SYSTEM = 'EBS'
    ) AS SOURCE_APP_ID,
    (
      SELECT
        SYSTEM_ID
      FROM BEC_ETL_CTRL.ETLSOURCEAPPID
      WHERE
        SOURCE_SYSTEM = 'EBS'
    ) || '-' || COALESCE(RELATED_ITEM_ID, 0) AS DW_LOAD_ID,
    CURRENT_TIMESTAMP() AS DW_INSERT_DATE,
    CURRENT_TIMESTAMP() AS DW_UPDATE_DATE
  FROM (
    SELECT
      *
    FROM silver_bec_ods.mtl_related_items
    WHERE
      is_deleted_flg <> 'Y'
  )
);
UPDATE BEC_ETL_CTRL.BATCH_DW_INFO SET LOAD_TYPE = 'I', LAST_REFRESH_DATE = CURRENT_TIMESTAMP()
WHERE
  DW_TABLE_NAME = 'fact_inv_related_items' AND BATCH_NAME = 'inv';