DROP table IF EXISTS bronze_bec_ods_stg.MSC_SUB_INVENTORIES;
CREATE TABLE bronze_bec_ods_stg.MSC_SUB_INVENTORIES AS
SELECT
  *
FROM bec_raw_dl_ext.MSC_SUB_INVENTORIES
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(PLAN_ID, 0), COALESCE(SR_INSTANCE_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(SUB_INVENTORY_CODE, 'NA'), last_update_date) IN (
    SELECT
      COALESCE(PLAN_ID, 0) AS PLAN_ID,
      COALESCE(SR_INSTANCE_ID, 0) AS SR_INSTANCE_ID,
      COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
      COALESCE(SUB_INVENTORY_CODE, 'NA') AS SUB_INVENTORY_CODE,
      MAX(last_update_date)
    FROM bec_raw_dl_ext.MSC_SUB_INVENTORIES
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(PLAN_ID, 0),
      COALESCE(SR_INSTANCE_ID, 0),
      COALESCE(ORGANIZATION_ID, 0),
      COALESCE(SUB_INVENTORY_CODE, 'NA')
  );