DROP TABLE IF EXISTS bronze_bec_ods_stg.ORG_ACCESS;
CREATE TABLE bronze_bec_ods_stg.ORG_ACCESS AS
SELECT
  *
FROM bec_raw_dl_ext.ORG_ACCESS
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(RESP_APPLICATION_ID, 0), COALESCE(RESPONSIBILITY_ID, 0), COALESCE(ORGANIZATION_ID, 0), last_update_date) IN (
    SELECT
      COALESCE(RESP_APPLICATION_ID, 0) AS RESP_APPLICATION_ID,
      COALESCE(RESPONSIBILITY_ID, 0) AS RESPONSIBILITY_ID,
      COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
      MAX(last_update_date)
    FROM bec_raw_dl_ext.ORG_ACCESS
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(RESP_APPLICATION_ID, 0),
      COALESCE(RESPONSIBILITY_ID, 0),
      COALESCE(ORGANIZATION_ID, 0)
  );