DROP TABLE IF EXISTS bronze_bec_ods_stg.WIP_TRANSACTION_ACCOUNTS;
CREATE TABLE bronze_bec_ods_stg.WIP_TRANSACTION_ACCOUNTS AS
SELECT
  *
FROM bec_raw_dl_ext.WIP_TRANSACTION_ACCOUNTS
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(TRANSACTION_ID, 0), COALESCE(REFERENCE_ACCOUNT, 0), COALESCE(WIP_SUB_LEDGER_ID, 0), last_update_date) IN (
    SELECT
      COALESCE(TRANSACTION_ID, 0),
      COALESCE(REFERENCE_ACCOUNT, 0),
      COALESCE(WIP_SUB_LEDGER_ID, 0),
      MAX(last_update_date)
    FROM bec_raw_dl_ext.WIP_TRANSACTION_ACCOUNTS
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(TRANSACTION_ID, 0),
      COALESCE(REFERENCE_ACCOUNT, 0),
      COALESCE(WIP_SUB_LEDGER_ID, 0)
  );