DROP TABLE IF EXISTS bronze_bec_ods_stg.MTL_ITEM_LOCATIONS;
CREATE TABLE bronze_bec_ods_stg.MTL_ITEM_LOCATIONS AS
(
  SELECT
    *
  FROM bec_raw_dl_ext.MTL_ITEM_LOCATIONS
  WHERE
    kca_operation <> 'DELETE'
    AND (COALESCE(INVENTORY_LOCATION_ID, 0), COALESCE(ORGANIZATION_ID, 0), last_update_date) IN (
      SELECT
        COALESCE(INVENTORY_LOCATION_ID, 0) AS INVENTORY_LOCATION_ID,
        COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
        MAX(last_update_date)
      FROM bec_raw_dl_ext.MTL_ITEM_LOCATIONS
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
      GROUP BY
        COALESCE(INVENTORY_LOCATION_ID, 0),
        COALESCE(ORGANIZATION_ID, 0)
    )
);
COMMIT;