DROP TABLE IF EXISTS bronze_bec_ods_stg.MTL_ABC_ASSIGNMENTS;
CREATE TABLE bronze_bec_ods_stg.MTL_ABC_ASSIGNMENTS AS
SELECT
  *
FROM bec_raw_dl_ext.MTL_ABC_ASSIGNMENTS
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(INVENTORY_ITEM_ID, 0), COALESCE(ASSIGNMENT_GROUP_ID, 0), COALESCE(ABC_CLASS_ID, 0), last_update_date) IN (
    SELECT
      COALESCE(INVENTORY_ITEM_ID, 0) AS INVENTORY_ITEM_ID,
      COALESCE(ASSIGNMENT_GROUP_ID, 0) AS ASSIGNMENT_GROUP_ID,
      COALESCE(ABC_CLASS_ID, 0) AS ABC_CLASS_ID,
      MAX(last_update_date)
    FROM bec_raw_dl_ext.MTL_ABC_ASSIGNMENTS
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(INVENTORY_ITEM_ID, 0),
      COALESCE(ASSIGNMENT_GROUP_ID, 0),
      COALESCE(ABC_CLASS_ID, 0)
  );