DROP TABLE IF EXISTS bronze_bec_ods_stg.RCV_TRANSACTIONS_INTERFACE;
CREATE TABLE bronze_bec_ods_stg.RCV_TRANSACTIONS_INTERFACE AS
SELECT
  *
FROM bec_raw_dl_ext.RCV_TRANSACTIONS_INTERFACE
WHERE
  kca_operation <> 'DELETE'
  AND (INTERFACE_TRANSACTION_ID, last_update_date) IN (
    SELECT
      COALESCE(INTERFACE_TRANSACTION_ID, 0) AS INTERFACE_TRANSACTION_ID,
      MAX(last_update_date)
    FROM bec_raw_dl_ext.RCV_TRANSACTIONS_INTERFACE
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(INTERFACE_TRANSACTION_ID, 0)
  );