DROP table IF EXISTS bronze_bec_ods_stg.XXBEC_CVMI_CONS_CAL_FINAL;
CREATE TABLE bronze_bec_ods_stg.XXBEC_CVMI_CONS_CAL_FINAL AS
(
  SELECT
    *
  FROM bec_raw_dl_ext.XXBEC_CVMI_CONS_CAL_FINAL
  WHERE
    kca_operation <> 'DELETE'
    AND (COALESCE(PART_NUMBER, 'NA'), COALESCE(ORGANIZATION_ID, 0), COALESCE(PLAN_NAME, 'NA'), COALESCE(BQOH, 0), COALESCE(CVMI_QOH, 0), COALESCE(AS_OF_DATE, '1900-01-01')) IN (
      SELECT
        COALESCE(PART_NUMBER, 'NA') AS PART_NUMBER,
        COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
        COALESCE(PLAN_NAME, 'NA') AS PLAN_NAME,
        COALESCE(BQOH, 0) AS BQOH,
        COALESCE(CVMI_QOH, 0) AS CVMI_QOH,
        COALESCE(AS_OF_DATE, '1900-01-01') AS AS_OF_DATE
      FROM bec_raw_dl_ext.XXBEC_CVMI_CONS_CAL_FINAL
      WHERE
        kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
      GROUP BY
        (COALESCE(PART_NUMBER, 'NA'), COALESCE(ORGANIZATION_ID, 0), COALESCE(PLAN_NAME, 'NA'), COALESCE(BQOH, 0), COALESCE(CVMI_QOH, 0), COALESCE(AS_OF_DATE, '1900-01-01'))
    )
);