DROP TABLE IF EXISTS bronze_bec_ods_stg.XLA_DISTRIBUTION_LINKS;
CREATE TABLE bronze_bec_ods_stg.XLA_DISTRIBUTION_LINKS AS
SELECT
  *
FROM bec_raw_dl_ext.XLA_DISTRIBUTION_LINKS
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(APPLICATION_ID, 0), COALESCE(REF_AE_HEADER_ID, 0), COALESCE(TEMP_LINE_NUM, 0), COALESCE(AE_HEADER_ID, 0)) IN (
    SELECT
      COALESCE(APPLICATION_ID, 0),
      COALESCE(REF_AE_HEADER_ID, 0),
      COALESCE(TEMP_LINE_NUM, 0),
      COALESCE(AE_HEADER_ID, 0)
    FROM bec_raw_dl_ext.XLA_DISTRIBUTION_LINKS
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(APPLICATION_ID, 0),
      COALESCE(REF_AE_HEADER_ID, 0),
      COALESCE(TEMP_LINE_NUM, 0),
      COALESCE(AE_HEADER_ID, 0)
  );