DROP TABLE IF EXISTS bronze_bec_ods_stg.FND_RESPONSIBILITY;
CREATE TABLE bronze_bec_ods_stg.FND_RESPONSIBILITY AS
SELECT
  *
FROM bec_raw_dl_ext.FND_RESPONSIBILITY
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(APPLICATION_ID, 0), COALESCE(RESPONSIBILITY_ID, 0), last_update_date) IN (
    SELECT
      COALESCE(APPLICATION_ID, 0),
      COALESCE(RESPONSIBILITY_ID, 0),
      MAX(last_update_date)
    FROM bec_raw_dl_ext.FND_RESPONSIBILITY
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(APPLICATION_ID, 0),
      COALESCE(RESPONSIBILITY_ID, 0)
  );