DROP TABLE IF EXISTS bronze_bec_ods_stg.XLA_EVENT_CLASSES_TL;
CREATE TABLE bronze_bec_ods_stg.XLA_EVENT_CLASSES_TL AS
SELECT
  *
FROM bec_raw_dl_ext.XLA_EVENT_CLASSES_TL
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(APPLICATION_ID, 0), COALESCE(ENTITY_CODE, 'NA'), COALESCE(EVENT_CLASS_CODE, 'NA'), COALESCE(LANGUAGE, 'NA'), last_update_date) IN (
    SELECT
      COALESCE(APPLICATION_ID, 0),
      COALESCE(ENTITY_CODE, 'NA'),
      COALESCE(EVENT_CLASS_CODE, 'NA'),
      COALESCE(LANGUAGE, 'NA'),
      MAX(last_update_date)
    FROM bec_raw_dl_ext.XLA_EVENT_CLASSES_TL
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(APPLICATION_ID, 0),
      COALESCE(ENTITY_CODE, 'NA'),
      COALESCE(EVENT_CLASS_CODE, 'NA'),
      COALESCE(LANGUAGE, 'NA')
  );