DROP TABLE IF EXISTS bronze_bec_ods_stg.MTL_INTERORG_SHIP_METHODS;
CREATE TABLE bronze_bec_ods_stg.MTL_INTERORG_SHIP_METHODS AS
SELECT
  *
FROM bec_raw_dl_ext.MTL_INTERORG_SHIP_METHODS
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(FROM_ORGANIZATION_ID, 0), COALESCE(TO_ORGANIZATION_ID, 0), COALESCE(FROM_LOCATION_ID, 0), COALESCE(TO_LOCATION_ID, 0), COALESCE(SHIP_METHOD, '0'), last_update_date) IN (
    SELECT
      COALESCE(FROM_ORGANIZATION_ID, 0),
      COALESCE(TO_ORGANIZATION_ID, 0),
      COALESCE(FROM_LOCATION_ID, 0),
      COALESCE(TO_LOCATION_ID, 0),
      COALESCE(SHIP_METHOD, '0'),
      MAX(last_update_date)
    FROM bec_raw_dl_ext.MTL_INTERORG_SHIP_METHODS
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(FROM_ORGANIZATION_ID, 0),
      COALESCE(TO_ORGANIZATION_ID, 0),
      COALESCE(FROM_LOCATION_ID, 0),
      COALESCE(TO_LOCATION_ID, 0),
      COALESCE(SHIP_METHOD, '0')
  );