DROP table IF EXISTS bronze_bec_ods_stg.MSC_BOM_COMPONENTS;
CREATE TABLE bronze_bec_ods_stg.MSC_BOM_COMPONENTS AS
SELECT
  *
FROM bec_raw_dl_ext.MSC_BOM_COMPONENTS
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(PLAN_ID, 0), COALESCE(COMPONENT_SEQUENCE_ID, 0), COALESCE(SR_INSTANCE_ID, 0), COALESCE(BILL_SEQUENCE_ID, 0), last_update_date) IN (
    SELECT
      COALESCE(PLAN_ID, 0) AS PLAN_ID,
      COALESCE(COMPONENT_SEQUENCE_ID, 0) AS COMPONENT_SEQUENCE_ID,
      COALESCE(SR_INSTANCE_ID, 0) AS SR_INSTANCE_ID,
      COALESCE(BILL_SEQUENCE_ID, 0) AS BILL_SEQUENCE_ID,
      MAX(last_update_date)
    FROM bec_raw_dl_ext.MSC_BOM_COMPONENTS
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(PLAN_ID, 0),
      COALESCE(COMPONENT_SEQUENCE_ID, 0),
      COALESCE(SR_INSTANCE_ID, 0),
      COALESCE(BILL_SEQUENCE_ID, 0)
  );