DROP TABLE IF EXISTS bronze_bec_ods_stg.GL_IMPORT_REFERENCES;
CREATE TABLE bronze_bec_ods_stg.GL_IMPORT_REFERENCES AS
SELECT
  *
FROM bec_raw_dl_ext.GL_IMPORT_REFERENCES
WHERE
  kca_operation <> 'DELETE'
  AND (COALESCE(JE_HEADER_ID, 0), COALESCE(JE_LINE_NUM, 0), COALESCE(SUBLEDGER_DOC_SEQUENCE_ID, 0), COALESCE(SUBLEDGER_DOC_SEQUENCE_VALUE, 0), COALESCE(GL_SL_LINK_ID, 0), last_update_date) IN (
    SELECT
      COALESCE(JE_HEADER_ID, 0) AS JE_HEADER_ID,
      COALESCE(JE_LINE_NUM, 0) AS JE_LINE_NUM,
      COALESCE(SUBLEDGER_DOC_SEQUENCE_ID, 0) AS SUBLEDGER_DOC_SEQUENCE_ID,
      COALESCE(SUBLEDGER_DOC_SEQUENCE_VALUE, 0) AS SUBLEDGER_DOC_SEQUENCE_VALUE,
      COALESCE(GL_SL_LINK_ID, 0) AS GL_SL_LINK_ID,
      MAX(last_update_date)
    FROM bec_raw_dl_ext.GL_IMPORT_REFERENCES
    WHERE
      kca_operation <> 'DELETE' AND COALESCE(kca_seq_id, '') = ''
    GROUP BY
      COALESCE(JE_HEADER_ID, 0),
      COALESCE(JE_LINE_NUM, 0),
      COALESCE(SUBLEDGER_DOC_SEQUENCE_ID, 0),
      COALESCE(SUBLEDGER_DOC_SEQUENCE_VALUE, 0),
      COALESCE(GL_SL_LINK_ID, 0)
  );