DROP TABLE IF EXISTS BEC_ODS_STG.MTL_TRANSACTION_TYPES;
CREATE TABLE BEC_ODS_STG.MTL_TRANSACTION_TYPES AS
SELECT
  *
FROM BEC_RAW_DL_EXT.MTL_TRANSACTION_TYPES
WHERE
  KCA_OPERATION <> 'DELETE'
  AND (COALESCE(TRANSACTION_TYPE_ID, 0), COALESCE(TRANSACTION_TYPE_NAME, 'NA'), LAST_UPDATE_DATE) IN (
    SELECT
      COALESCE(TRANSACTION_TYPE_ID, 0) AS TRANSACTION_TYPE_ID,
      COALESCE(TRANSACTION_TYPE_NAME, 'NA') AS TRANSACTION_TYPE_NAME,
      MAX(LAST_UPDATE_DATE)
    FROM BEC_RAW_DL_EXT.MTL_TRANSACTION_TYPES
    WHERE
      KCA_OPERATION <> 'DELETE' AND COALESCE(KCA_SEQ_ID, '') = ''
    GROUP BY
      COALESCE(TRANSACTION_TYPE_ID, 0),
      COALESCE(TRANSACTION_TYPE_NAME, 'NA')
  );