TRUNCATE table gold_bec_dwh.FACT_RAPA_POREQ_TMP3;
INSERT INTO gold_bec_dwh.FACT_RAPA_POREQ_TMP3
(
  SELECT
    inventory_item_id,
    organization_id,
    cost_type,
    plan_name,
    data_type,
    order_group,
    order_type_text,
    requisition_number,
    need_by_date,
    aging_period,
    dock_promised_date,
    part_number,
    description,
    planning_make_buy_code,
    category_name,
    so_ship_qty,
    primary_quantity,
    unit_price,
    primary_unit_of_measure,
    CAST(extended_cost AS DECIMAL(38, 10)),
    po_line_type,
    vendor_name,
    std_cost,
    CAST(ext_std_cost AS DECIMAL(38, 10)),
    variance,
    source_organization_id,
    planner_code,
    buyer_name,
    transactional_uom_code,
    release_num,
    inventory_item_id_KEY,
    organization_id_KEY,
    source_organization_id_KEY,
    is_deleted_flg,
    source_app_id,
    dw_load_id,
    dw_insert_date,
    dw_update_date
  FROM gold_bec_dwh.FACT_RAPA_STG7
  UNION ALL
  SELECT
    inventory_item_id,
    organization_id,
    cost_type,
    plan_name,
    data_type,
    order_group,
    order_type_text,
    requisition_number,
    need_by_date,
    aging_period,
    dock_promised_date,
    part_number,
    description,
    planning_make_buy_code,
    category_name,
    pr_open_qty,
    Primary_quantity,
    unit_price,
    primary_unit_of_measure,
    CAST(extended_cost AS DECIMAL(38, 10)),
    po_line_type,
    vendor_name,
    std_cost,
    CAST(ext_std_cost AS DECIMAL(38, 10)),
    CAST(variance AS DECIMAL(38, 10)),
    source_organization_id,
    planner_code,
    buyer_name,
    transactional_uom_code,
    release_num,
    inventory_item_id_KEY,
    organization_id_KEY,
    source_organization_id_KEY,
    is_deleted_flg,
    source_app_id,
    dw_load_id,
    dw_insert_date,
    dw_update_date
  FROM gold_bec_dwh.FACT_RAPA_STG8
  UNION ALL
  SELECT
    inventory_item_id,
    organization_id,
    cost_type,
    plan_name,
    data_type,
    order_group,
    order_type_text,
    po_number,
    promised_date1,
    aging_period,
    promised_date,
    purchase_item,
    item_description,
    planning_make_buy_code,
    category_name,
    po_open_qty,
    primary_quantity,
    unit_price,
    primary_unit_of_measure,
    CAST(po_open_amount AS DECIMAL(38, 10)),
    po_line_type,
    suggested_vendor_name,
    material_cost,
    CAST(ext_mtl_cost AS DECIMAL(38, 10)),
    CAST(VARIANCE AS DECIMAL(38, 10)),
    source_organization_id,
    planner_code,
    buyer_name,
    transactional_uom_code,
    release_num,
    inventory_item_id_KEY,
    organization_id_KEY,
    source_organization_id_KEY,
    is_deleted_flg,
    source_app_id,
    dw_load_id,
    dw_insert_date,
    dw_update_date
  FROM gold_bec_dwh.FACT_RAPA_STG9
);
UPDATE bec_etl_ctrl.batch_dw_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  dw_table_name = 'fact_rapa_poreq_tmp3' AND batch_name = 'ascp';