TRUNCATE table gold_bec_dwh.FACT_RAPA_PO_TMP2;
INSERT INTO gold_bec_dwh.FACT_RAPA_PO_TMP2
(
  SELECT
    a.inventory_item_id,
    a.organization_id,
    a.cost_type,
    a.plan_name,
    a.data_type,
    a.order_group,
    a.order_type_text,
    a.po_number,
    a.promised_date1,
    a.aging_period,
    a.promised_date,
    a.purchase_item,
    a.item_description,
    a.planning_make_buy_code,
    diics.item_category_segment1 || '.' || diics.item_category_segment2 AS category_name,
    a.po_open_qty,
    CAST(a.primary_quantity AS DECIMAL(38, 10)),
    a.unit_price,
    a.primary_unit_of_measure,
    CAST(a.po_open_amount AS DECIMAL(38, 10)),
    a.po_line_type,
    a.vendor_name,
    a.mtl_cost,
    CAST(a.ext_mtl_cost AS DECIMAL(38, 10)),
    CAST(a.VARIANCE AS DECIMAL(38, 10)),
    a.source_organization_id,
    a.planner_code,
    a.buyer_name,
    a.transactional_uom_code,
    a.release_num,
    a.inventory_item_id_KEY,
    a.organization_id_KEY,
    a.source_organization_id_KEY,
    a.is_deleted_flg,
    a.source_app_id,
    a.dw_load_id,
    a.dw_insert_date,
    a.dw_update_date
  FROM gold_bec_dwh.FACT_RAPA_STG3 AS a
  LEFT OUTER JOIN bec_Dwh.dim_inv_item_category_set AS diics
    ON a.inventory_item_id = diics.inventory_item_id
    AND a.organization_id = diics.organization_id
    AND diics.category_set_id = 1
  UNION ALL
  SELECT
    inventory_item_id,
    organization_id,
    cost_type,
    plan_name,
    data_type,
    order_group,
    order_type_text,
    order_number,
    promised_date,
    aging_period,
    receipt_date,
    part_number,
    item_description,
    planning_make_buy_code,
    category_name,
    rcv_quantity_received,
    CAST(primary_quantity AS DECIMAL(38, 10)),
    po_unit_price,
    primary_unit_of_measure,
    CAST(extended_po_rcv_price AS DECIMAL(38, 10)),
    po_line_type,
    vendor_name,
    mtl_cost,
    CAST(ext_mtl_cost AS DECIMAL(38, 10)),
    CAST(variance AS DECIMAL(38, 10)),
    source_organization_id,
    planner_code,
    buyer_name,
    po_unit_of_measure,
    po_release_number,
    inventory_item_id_KEY,
    organization_id_KEY,
    source_organization_id_KEY,
    is_deleted_flg,
    source_app_id,
    dw_load_id,
    dw_insert_date,
    dw_update_date
  FROM gold_bec_dwh.FACT_RAPA_STG4
  UNION ALL
  SELECT
    inventory_item_id,
    organization_id,
    cost_type,
    plan_name,
    data_type,
    order_group,
    order_type_text,
    po_number,
    consumption_date1,
    aging_period,
    consumption_date,
    item,
    description,
    planning_make_buy_code,
    category_name,
    consumption_quantity,
    primary_quantity,
    unit_price,
    uom_code,
    consumption_value,
    po_line_type,
    vendor_name,
    material_cost,
    extended_cost,
    consigned_ppv,
    source_organization_id,
    planner_code,
    buyer_name,
    primary_unit_of_measure,
    release_num,
    inventory_item_id_KEY,
    organization_id_KEY,
    source_organization_id_KEY,
    is_deleted_flg,
    source_app_id,
    dw_load_id,
    dw_insert_date,
    dw_update_date
  FROM gold_bec_dwh.FACT_RAPA_STG5
);
UPDATE bec_etl_ctrl.batch_dw_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  dw_table_name = 'fact_rapa_po_tmp2' AND batch_name = 'ascp';