/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for stage.
# File Version: KPI v1.0
*/
begin;

truncate table bec_ods_stg.BOM_OPERATION_SEQUENCES;

insert into bec_ods_stg.bom_operation_sequences (
  OPERATION_SEQUENCE_ID, 
  ROUTING_SEQUENCE_ID, 
  OPERATION_SEQ_NUM, 
  LAST_UPDATE_DATE, 
  LAST_UPDATED_BY, 
  CREATION_DATE, 
  CREATED_BY, 
  LAST_UPDATE_LOGIN, 
  STANDARD_OPERATION_ID, 
  DEPARTMENT_ID, 
  OPERATION_LEAD_TIME_PERCENT, 
  MINIMUM_TRANSFER_QUANTITY, 
  COUNT_POINT_TYPE, 
  OPERATION_DESCRIPTION, 
  EFFECTIVITY_DATE, 
  DISABLE_DATE, 
  BACKFLUSH_FLAG, 
  OPTION_DEPENDENT_FLAG, 
  ATTRIBUTE_CATEGORY, 
  ATTRIBUTE1, 
  ATTRIBUTE2, 
  ATTRIBUTE3, 
  ATTRIBUTE4, 
  ATTRIBUTE5, 
  ATTRIBUTE6, 
  ATTRIBUTE7, 
  ATTRIBUTE8, 
  ATTRIBUTE9, 
  ATTRIBUTE10, 
  ATTRIBUTE11, 
  ATTRIBUTE12, 
  ATTRIBUTE13, 
  ATTRIBUTE14, 
  ATTRIBUTE15, 
  REQUEST_ID, 
  PROGRAM_APPLICATION_ID, 
  PROGRAM_ID, 
  PROGRAM_UPDATE_DATE, 
  OPERATION_TYPE, 
  REFERENCE_FLAG, 
  PROCESS_OP_SEQ_ID, 
  LINE_OP_SEQ_ID, 
  YIELD, 
  CUMULATIVE_YIELD, 
  REVERSE_CUMULATIVE_YIELD, 
  LABOR_TIME_CALC, 
  MACHINE_TIME_CALC, 
  TOTAL_TIME_CALC, 
  LABOR_TIME_USER, 
  MACHINE_TIME_USER, 
  TOTAL_TIME_USER, 
  NET_PLANNING_PERCENT, 
  X_COORDINATE, 
  Y_COORDINATE, 
  INCLUDE_IN_ROLLUP, 
  OPERATION_YIELD_ENABLED, 
  OLD_OPERATION_SEQUENCE_ID, 
  ACD_TYPE, 
  REVISED_ITEM_SEQUENCE_ID, 
  ORIGINAL_SYSTEM_REFERENCE, 
  CHANGE_NOTICE, 
  IMPLEMENTATION_DATE, 
  ECO_FOR_PRODUCTION, 
  SHUTDOWN_TYPE, 
  ACTUAL_IPK, 
  CRITICAL_TO_QUALITY, 
  VALUE_ADDED, 
  MACHINE_PROCESS_EFFICIENCY, 
  LABOR_PROCESS_EFFICIENCY, 
  TOTAL_PROCESS_EFFICIENCY, 
  LONG_DESCRIPTION, 
  CONFIG_ROUTING_ID, 
  MODEL_OP_SEQ_ID, 
  LOWEST_ACCEPTABLE_YIELD, 
  USE_ORG_SETTINGS, 
  QUEUE_MANDATORY_FLAG, 
  RUN_MANDATORY_FLAG, 
  TO_MOVE_MANDATORY_FLAG, 
  SHOW_NEXT_OP_BY_DEFAULT, 
  SHOW_SCRAP_CODE, 
  SHOW_LOT_ATTRIB, 
  TRACK_MULTIPLE_RES_USAGE_DATES, 
  CHECK_SKILL, 
  KCA_OPERATION, 
  kca_seq_id, 
  kca_seq_date
) (
  select 
    OPERATION_SEQUENCE_ID, 
	ROUTING_SEQUENCE_ID, 
	OPERATION_SEQ_NUM, 
	LAST_UPDATE_DATE, 
	LAST_UPDATED_BY, 
	CREATION_DATE, 
	CREATED_BY, 
	LAST_UPDATE_LOGIN, 
	STANDARD_OPERATION_ID, 
	DEPARTMENT_ID, 
	OPERATION_LEAD_TIME_PERCENT, 
	MINIMUM_TRANSFER_QUANTITY, 
	COUNT_POINT_TYPE, 
	OPERATION_DESCRIPTION, 
	EFFECTIVITY_DATE, 
	DISABLE_DATE, 
	BACKFLUSH_FLAG, 
	OPTION_DEPENDENT_FLAG, 
	ATTRIBUTE_CATEGORY, 
	ATTRIBUTE1, 
	ATTRIBUTE2, 
	ATTRIBUTE3, 
	ATTRIBUTE4, 
	ATTRIBUTE5, 
	ATTRIBUTE6, 
	ATTRIBUTE7, 
	ATTRIBUTE8, 
	ATTRIBUTE9, 
	ATTRIBUTE10, 
	ATTRIBUTE11, 
	ATTRIBUTE12, 
	ATTRIBUTE13, 
	ATTRIBUTE14, 
	ATTRIBUTE15, 
	REQUEST_ID, 
	PROGRAM_APPLICATION_ID, 
	PROGRAM_ID, 
	PROGRAM_UPDATE_DATE, 
	OPERATION_TYPE, 
	REFERENCE_FLAG, 
	PROCESS_OP_SEQ_ID, 
	LINE_OP_SEQ_ID, 
	YIELD, 
	CUMULATIVE_YIELD, 
	REVERSE_CUMULATIVE_YIELD, 
	LABOR_TIME_CALC, 
	MACHINE_TIME_CALC, 
	TOTAL_TIME_CALC, 
	LABOR_TIME_USER, 
	MACHINE_TIME_USER, 
	TOTAL_TIME_USER, 
	NET_PLANNING_PERCENT, 
	X_COORDINATE, 
	Y_COORDINATE, 
	INCLUDE_IN_ROLLUP, 
	OPERATION_YIELD_ENABLED, 
	OLD_OPERATION_SEQUENCE_ID, 
	ACD_TYPE, 
	REVISED_ITEM_SEQUENCE_ID, 
	ORIGINAL_SYSTEM_REFERENCE, 
	CHANGE_NOTICE, 
	IMPLEMENTATION_DATE, 
	ECO_FOR_PRODUCTION, 
	SHUTDOWN_TYPE, 
	ACTUAL_IPK, 
	CRITICAL_TO_QUALITY, 
	VALUE_ADDED, 
	MACHINE_PROCESS_EFFICIENCY, 
	LABOR_PROCESS_EFFICIENCY, 
	TOTAL_PROCESS_EFFICIENCY, 
	LONG_DESCRIPTION, 
	CONFIG_ROUTING_ID, 
	MODEL_OP_SEQ_ID, 
	LOWEST_ACCEPTABLE_YIELD, 
	USE_ORG_SETTINGS, 
	QUEUE_MANDATORY_FLAG, 
	RUN_MANDATORY_FLAG, 
	TO_MOVE_MANDATORY_FLAG, 
	SHOW_NEXT_OP_BY_DEFAULT, 
	SHOW_SCRAP_CODE, 
	SHOW_LOT_ATTRIB, 
	TRACK_MULTIPLE_RES_USAGE_DATES, 
	CHECK_SKILL, 
    KCA_OPERATION, 
    kca_seq_id, 
    kca_seq_date 
  from 
    bec_raw_dl_ext.bom_operation_sequences 
  where 
    kca_operation != 'DELETE' 
    and nvl(kca_seq_id, '')!= '' 
    and (
      nvl(OPERATION_SEQUENCE_ID, '0'), 
      kca_seq_id
    ) in (
      select 
        nvl(OPERATION_SEQUENCE_ID, '0') as OPERATION_SEQUENCE_ID, 
        max(kca_seq_id) 
      from 
        bec_raw_dl_ext.bom_operation_sequences 
      where 
        kca_operation != 'DELETE' 
        and nvl(kca_seq_id, '')!= '' 
      group by 
        nvl(OPERATION_SEQUENCE_ID, '0')
    ) 
    and kca_seq_date > (
      select 
        (executebegints - prune_days) 
      from 
        bec_etl_ctrl.batch_ods_info 
      where 
        ods_table_name = 'bom_operation_sequences'
    )
);
end;
