/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for stage.
# File Version: KPI v1.0
*/
begin;

truncate
	table bec_ods_stg.CE_PAYMENT_DOCUMENTS;

INSERT
	INTO
	bec_ods_stg.CE_PAYMENT_DOCUMENTS
(PAYMENT_DOCUMENT_ID,
	PAYMENT_DOC_CATEGORY,
	PAYMENT_DOCUMENT_NAME,
	PAYMENT_INSTRUCTION_ID,
	INTERNAL_BANK_ACCOUNT_ID,
	PAPER_STOCK_TYPE,
	ATTACHED_REMITTANCE_STUB_FLAG,
	NUMBER_OF_LINES_PER_REMIT_STUB,
	NUMBER_OF_SETUP_DOCUMENTS,
	FORMAT_CODE,
	FIRST_AVAILABLE_DOCUMENT_NUM,
	LAST_AVAILABLE_DOCUMENT_NUMBER,
	LAST_ISSUED_DOCUMENT_NUMBER,
	MANUAL_PAYMENTS_ONLY_FLAG,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	INACTIVE_DATE,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATE_LOGIN,
	OBJECT_VERSION_NUMBER
	,KCA_OPERATION
	,kca_seq_id
	,kca_seq_date)
SELECT
	PAYMENT_DOCUMENT_ID,
	PAYMENT_DOC_CATEGORY,
	PAYMENT_DOCUMENT_NAME,
	PAYMENT_INSTRUCTION_ID,
	INTERNAL_BANK_ACCOUNT_ID,
	PAPER_STOCK_TYPE,
	ATTACHED_REMITTANCE_STUB_FLAG,
	NUMBER_OF_LINES_PER_REMIT_STUB,
	NUMBER_OF_SETUP_DOCUMENTS,
	FORMAT_CODE,
	FIRST_AVAILABLE_DOCUMENT_NUM,
	LAST_AVAILABLE_DOCUMENT_NUMBER,
	LAST_ISSUED_DOCUMENT_NUMBER,
	MANUAL_PAYMENTS_ONLY_FLAG,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	INACTIVE_DATE,
	CREATED_BY,
	CREATION_DATE,
	LAST_UPDATED_BY,
	LAST_UPDATE_DATE,
	LAST_UPDATE_LOGIN,
	OBJECT_VERSION_NUMBER
	,KCA_OPERATION
	,kca_seq_id
	,kca_seq_date
FROM
	bec_raw_dl_ext.CE_PAYMENT_DOCUMENTS
where  kca_operation != 'DELETE' and nvl(kca_seq_id,'')!= ''
and (PAYMENT_DOCUMENT_ID,kca_seq_id) in (select PAYMENT_DOCUMENT_ID,max(kca_seq_id) from bec_raw_dl_ext.CE_PAYMENT_DOCUMENTS 
where kca_operation != 'DELETE' and nvl(kca_seq_id,'')!= ''
group by PAYMENT_DOCUMENT_ID) and
		kca_seq_date > (
		select
			(executebegints-prune_days)
		from
			bec_etl_ctrl.batch_ods_info
		where
			ods_table_name = 'ce_payment_documents')
			;
end;
