/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for stage.
# File Version: KPI v1.0
*/
begin;

truncate table bec_ods_stg.FA_CATEGORIES_B;

insert into	bec_ods_stg.FA_CATEGORIES_B
   (	
	CATEGORY_ID, 
	SUMMARY_FLAG, 
	ENABLED_FLAG, 
	OWNED_LEASED, 
	PRODUCTION_CAPACITY, 
	LAST_UPDATE_DATE, 
	LAST_UPDATED_BY, 
	CATEGORY_TYPE, 
	CAPITALIZE_FLAG, 
	SEGMENT1, 
	SEGMENT2, 
	SEGMENT3, 
	SEGMENT4, 
	SEGMENT5, 
	SEGMENT6, 
	SEGMENT7, 
	START_DATE_ACTIVE, 
	END_DATE_ACTIVE, 
	PROPERTY_TYPE_CODE, 
	PROPERTY_1245_1250_CODE, 
	DATE_INEFFECTIVE, 
	INVENTORIAL, 
	CREATED_BY, 
	CREATION_DATE, 
	LAST_UPDATE_LOGIN, 
	ATTRIBUTE1, 
	ATTRIBUTE2, 
	ATTRIBUTE3, 
	ATTRIBUTE4, 
	ATTRIBUTE5, 
	ATTRIBUTE6, 
	ATTRIBUTE7, 
	ATTRIBUTE8, 
	ATTRIBUTE9, 
	ATTRIBUTE10, 
	ATTRIBUTE11, 
	ATTRIBUTE12, 
	ATTRIBUTE13, 
	ATTRIBUTE14, 
	ATTRIBUTE15, 
	ATTRIBUTE_CATEGORY_CODE, 
	GLOBAL_ATTRIBUTE1, 
	GLOBAL_ATTRIBUTE2, 
	GLOBAL_ATTRIBUTE3, 
	GLOBAL_ATTRIBUTE4, 
	GLOBAL_ATTRIBUTE5, 
	GLOBAL_ATTRIBUTE6, 
	GLOBAL_ATTRIBUTE7, 
	GLOBAL_ATTRIBUTE8, 
	GLOBAL_ATTRIBUTE9, 
	GLOBAL_ATTRIBUTE10, 
	GLOBAL_ATTRIBUTE11, 
	GLOBAL_ATTRIBUTE12, 
	GLOBAL_ATTRIBUTE13, 
	GLOBAL_ATTRIBUTE14, 
	GLOBAL_ATTRIBUTE15, 
	GLOBAL_ATTRIBUTE16, 
	GLOBAL_ATTRIBUTE17, 
	GLOBAL_ATTRIBUTE18, 
	GLOBAL_ATTRIBUTE19, 
	GLOBAL_ATTRIBUTE20, 
	GLOBAL_ATTRIBUTE_CATEGORY,  
    KCA_OPERATION,
	kca_seq_id,
	kca_seq_date)
(
	select
		CATEGORY_ID, 
		SUMMARY_FLAG, 
		ENABLED_FLAG, 
		OWNED_LEASED, 
		PRODUCTION_CAPACITY, 
		LAST_UPDATE_DATE, 
		LAST_UPDATED_BY, 
		CATEGORY_TYPE, 
		CAPITALIZE_FLAG, 
		SEGMENT1, 
		SEGMENT2, 
		SEGMENT3, 
		SEGMENT4, 
		SEGMENT5, 
		SEGMENT6, 
		SEGMENT7, 
		START_DATE_ACTIVE, 
		END_DATE_ACTIVE, 
		PROPERTY_TYPE_CODE, 
		PROPERTY_1245_1250_CODE, 
		DATE_INEFFECTIVE, 
		INVENTORIAL, 
		CREATED_BY, 
		CREATION_DATE, 
		LAST_UPDATE_LOGIN, 
		ATTRIBUTE1, 
		ATTRIBUTE2, 
		ATTRIBUTE3, 
		ATTRIBUTE4, 
		ATTRIBUTE5, 
		ATTRIBUTE6, 
		ATTRIBUTE7, 
		ATTRIBUTE8, 
		ATTRIBUTE9, 
		ATTRIBUTE10, 
		ATTRIBUTE11, 
		ATTRIBUTE12, 
		ATTRIBUTE13, 
		ATTRIBUTE14, 
		ATTRIBUTE15, 
		ATTRIBUTE_CATEGORY_CODE, 
		GLOBAL_ATTRIBUTE1, 
		GLOBAL_ATTRIBUTE2, 
		GLOBAL_ATTRIBUTE3, 
		GLOBAL_ATTRIBUTE4, 
		GLOBAL_ATTRIBUTE5, 
		GLOBAL_ATTRIBUTE6, 
		GLOBAL_ATTRIBUTE7, 
		GLOBAL_ATTRIBUTE8, 
		GLOBAL_ATTRIBUTE9, 
		GLOBAL_ATTRIBUTE10, 
		GLOBAL_ATTRIBUTE11, 
		GLOBAL_ATTRIBUTE12, 
		GLOBAL_ATTRIBUTE13, 
		GLOBAL_ATTRIBUTE14, 
		GLOBAL_ATTRIBUTE15, 
		GLOBAL_ATTRIBUTE16, 
		GLOBAL_ATTRIBUTE17, 
		GLOBAL_ATTRIBUTE18, 
		GLOBAL_ATTRIBUTE19, 
		GLOBAL_ATTRIBUTE20, 
		GLOBAL_ATTRIBUTE_CATEGORY, 
        KCA_OPERATION,
		kca_seq_id,
		kca_seq_date
	from bec_raw_dl_ext.FA_CATEGORIES_B
	where kca_operation != 'DELETE' and nvl(kca_seq_id,'')!= '' 
	and (nvl(CATEGORY_ID,0),kca_seq_id) in 
	(select nvl(CATEGORY_ID,0) as CATEGORY_ID,max(kca_seq_id) from bec_raw_dl_ext.FA_CATEGORIES_B 
     where kca_operation != 'DELETE' and nvl(kca_seq_id,'')!= ''
     group by nvl(CATEGORY_ID,0))
        and	kca_seq_date > (
		select
			(executebegints-prune_days)
		from
			bec_etl_ctrl.batch_ods_info
		where
			ods_table_name = 'fa_categories_b')
);
end;