/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for stage.
# File Version: KPI v1.0
*/
begin;

truncate
	table bec_ods_stg.hr_all_organization_units;

insert
	into
	bec_ods_stg.hr_all_organization_units
(ORGANIZATION_ID,
BUSINESS_GROUP_ID,
COST_ALLOCATION_KEYFLEX_ID,
LOCATION_ID,
SOFT_CODING_KEYFLEX_ID,
DATE_FROM,
NAME,
DATE_TO,
INTERNAL_EXTERNAL_FLAG,
INTERNAL_ADDRESS_LINE,
TYPE,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
ATTRIBUTE16,
ATTRIBUTE17,
ATTRIBUTE18,
ATTRIBUTE19,
ATTRIBUTE20,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_LOGIN,
CREATED_BY,
CREATION_DATE,
OBJECT_VERSION_NUMBER,
PARTY_ID,
ATTRIBUTE21,
ATTRIBUTE22,
ATTRIBUTE23,
ATTRIBUTE24,
ATTRIBUTE25,
ATTRIBUTE26,
ATTRIBUTE27,
ATTRIBUTE28,
ATTRIBUTE29,
ATTRIBUTE30,
COMMENTS
,KCA_OPERATION
,kca_seq_id,
	kca_seq_date
)
(
	select
	ORGANIZATION_ID,
BUSINESS_GROUP_ID,
COST_ALLOCATION_KEYFLEX_ID,
LOCATION_ID,
SOFT_CODING_KEYFLEX_ID,
DATE_FROM,
NAME,
DATE_TO,
INTERNAL_EXTERNAL_FLAG,
INTERNAL_ADDRESS_LINE,
TYPE,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
ATTRIBUTE16,
ATTRIBUTE17,
ATTRIBUTE18,
ATTRIBUTE19,
ATTRIBUTE20,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_LOGIN,
CREATED_BY,
CREATION_DATE,
OBJECT_VERSION_NUMBER,
PARTY_ID,
ATTRIBUTE21,
ATTRIBUTE22,
ATTRIBUTE23,
ATTRIBUTE24,
ATTRIBUTE25,
ATTRIBUTE26,
ATTRIBUTE27,
ATTRIBUTE28,
ATTRIBUTE29,
ATTRIBUTE30,
COMMENTS
,KCA_OPERATION
,kca_seq_id,
	kca_seq_date
	from
		bec_raw_dl_ext.hr_all_organization_units
where kca_operation != 'DELETE'  and nvl(kca_seq_id,'')!= '' and (organization_id,kca_seq_id) in (select organization_id,max(kca_seq_id) from bec_raw_dl_ext.hr_all_organization_units 
where kca_operation != 'DELETE'  and nvl(kca_seq_id,'')!= ''
group by organization_id) and
		( kca_seq_date > (
		select
			(executebegints-prune_days)
		from
			bec_etl_ctrl.batch_ods_info
		where
			ods_table_name = 'hr_all_organization_units')
		 
            )
);
end;
