/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for stage.
# File Version: KPI v1.0
*/
BEGIN;

TRUNCATE TABLE bec_ods_stg.wip_transactions;

insert into	bec_ods_stg.wip_transactions
    (
	TRANSACTION_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    ORGANIZATION_ID,
    WIP_ENTITY_ID,
    PRIMARY_ITEM_ID,
    ACCT_PERIOD_ID,
    DEPARTMENT_ID,
    TRANSACTION_TYPE,
    TRANSACTION_DATE,
    GROUP_ID,
    LINE_ID,
    SOURCE_CODE,
    SOURCE_LINE_ID,
    OPERATION_SEQ_NUM,
    RESOURCE_SEQ_NUM,
    EMPLOYEE_ID,
    RESOURCE_ID,
    AUTOCHARGE_TYPE,
    STANDARD_RATE_FLAG,
    USAGE_RATE_OR_AMOUNT,
    BASIS_TYPE,
    TRANSACTION_QUANTITY,
    TRANSACTION_UOM,
    PRIMARY_QUANTITY,
    PRIMARY_UOM,
    ACTUAL_RESOURCE_RATE,
    STANDARD_RESOURCE_RATE,
    CURRENCY_CODE,
    CURRENCY_CONVERSION_DATE,
    CURRENCY_CONVERSION_TYPE,
    CURRENCY_CONVERSION_RATE,
    CURRENCY_ACTUAL_RESOURCE_RATE,
    ACTIVITY_ID,
    REASON_ID,
    REFERENCE,
    MOVE_TRANSACTION_ID,
    PO_HEADER_ID,
    PO_LINE_ID,
    RCV_TRANSACTION_ID,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    COST_UPDATE_ID,
    PM_COST_COLLECTED,
    PM_COST_COLLECTOR_GROUP_ID,
    PROJECT_ID,
    TASK_ID,
    COMPLETION_TRANSACTION_ID,
    CHARGE_DEPARTMENT_ID,
    INSTANCE_ID,
    ENCUMBRANCE_TYPE_ID,
    ENCUMBRANCE_AMOUNT,
    ENCUMBRANCE_QUANTITY,
    ENCUMBRANCE_CCID,
	KCA_OPERATION,
	KCA_SEQ_ID
	,KCA_SEQ_DATE
	)
(select
	TRANSACTION_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    ORGANIZATION_ID,
    WIP_ENTITY_ID,
    PRIMARY_ITEM_ID,
    ACCT_PERIOD_ID,
    DEPARTMENT_ID,
    TRANSACTION_TYPE,
    TRANSACTION_DATE,
    GROUP_ID,
    LINE_ID,
    SOURCE_CODE,
    SOURCE_LINE_ID,
    OPERATION_SEQ_NUM,
    RESOURCE_SEQ_NUM,
    EMPLOYEE_ID,
    RESOURCE_ID,
    AUTOCHARGE_TYPE,
    STANDARD_RATE_FLAG,
    USAGE_RATE_OR_AMOUNT,
    BASIS_TYPE,
    TRANSACTION_QUANTITY,
    TRANSACTION_UOM,
    PRIMARY_QUANTITY,
    PRIMARY_UOM,
    ACTUAL_RESOURCE_RATE,
    STANDARD_RESOURCE_RATE,
    CURRENCY_CODE,
    CURRENCY_CONVERSION_DATE,
    CURRENCY_CONVERSION_TYPE,
    CURRENCY_CONVERSION_RATE,
    CURRENCY_ACTUAL_RESOURCE_RATE,
    ACTIVITY_ID,
    REASON_ID,
    REFERENCE,
    MOVE_TRANSACTION_ID,
    PO_HEADER_ID,
    PO_LINE_ID,
    RCV_TRANSACTION_ID,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    COST_UPDATE_ID,
    PM_COST_COLLECTED,
    PM_COST_COLLECTOR_GROUP_ID,
    PROJECT_ID,
    TASK_ID,
    COMPLETION_TRANSACTION_ID,
    CHARGE_DEPARTMENT_ID,
    INSTANCE_ID,
    ENCUMBRANCE_TYPE_ID,
    ENCUMBRANCE_AMOUNT,
    ENCUMBRANCE_QUANTITY,
    ENCUMBRANCE_CCID,
	KCA_OPERATION,
	KCA_SEQ_ID
	,KCA_SEQ_DATE
from
	bec_raw_dl_ext.wip_transactions 
	where kca_operation != 'DELETE'  and nvl(kca_seq_id,'') != '' 
	and (TRANSACTION_ID,KCA_SEQ_ID) in 
	(select TRANSACTION_ID,max(KCA_SEQ_ID) from bec_raw_dl_ext.wip_transactions 
     where kca_operation != 'DELETE'  and nvl(kca_seq_id,'') != ''
     group by TRANSACTION_ID)
     and (KCA_SEQ_DATE > (select (executebegints-prune_days) 
	from bec_etl_ctrl.batch_ods_info where ods_table_name ='wip_transactions')

            )
);
END;

