/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for stage.
# File Version: KPI v1.0
*/
BEGIN;

TRUNCATE TABLE bec_ods_stg.WIP_OPERATION_RESOURCES;

insert into	bec_ods_stg.WIP_OPERATION_RESOURCES
    (
	 WIP_ENTITY_ID 
	,OPERATION_SEQ_NUM 
	,RESOURCE_SEQ_NUM 
	,ORGANIZATION_ID 
	,REPETITIVE_SCHEDULE_ID 
	,LAST_UPDATE_DATE   
	,LAST_UPDATED_BY 
	,CREATION_DATE   
	,CREATED_BY 
	,LAST_UPDATE_LOGIN 
	,REQUEST_ID 
	,PROGRAM_APPLICATION_ID  
	,PROGRAM_ID  
	,PROGRAM_UPDATE_DATE   
	,RESOURCE_ID 
	,UOM_CODE 
	,BASIS_TYPE 
	,USAGE_RATE_OR_AMOUNT 
	,ACTIVITY_ID  
	,SCHEDULED_FLAG 
	,ASSIGNED_UNITS  
	,AUTOCHARGE_TYPE 
	,STANDARD_RATE_FLAG 
	,APPLIED_RESOURCE_UNITS  
	,APPLIED_RESOURCE_VALUE  
	,START_DATE    
	,COMPLETION_DATE  
	,ATTRIBUTE_CATEGORY 
	,ATTRIBUTE1 
	,ATTRIBUTE2 
	,ATTRIBUTE3 
	,ATTRIBUTE4 
	,ATTRIBUTE5 
	,ATTRIBUTE6 
	,ATTRIBUTE7 
	,ATTRIBUTE8 
	,ATTRIBUTE9 
	,ATTRIBUTE10 
	,ATTRIBUTE11 
	,ATTRIBUTE12 
	,ATTRIBUTE13 
	,ATTRIBUTE14 
	,ATTRIBUTE15 
	,RELIEVED_RES_COMPLETION_UNITS  
	,RELIEVED_RES_SCRAP_UNITS  
	,RELIEVED_RES_COMPLETION_VALUE  
	,RELIEVED_RES_SCRAP_VALUE  
	,RELIEVED_VARIANCE_VALUE  
	,TEMP_RELIEVED_VALUE  
	,RELIEVED_RES_FINAL_COMP_UNITS  
	,DEPARTMENT_ID  
	,PHANTOM_FLAG  
	,PHANTOM_OP_SEQ_NUM  
	,PHANTOM_ITEM_ID  
	,SCHEDULE_SEQ_NUM  
	,SUBSTITUTE_GROUP_NUM  
	,REPLACEMENT_GROUP_NUM  
	,PRINCIPLE_FLAG  
	,SETUP_ID  
	,PARENT_RESOURCE_SEQ  
	,BATCH_ID  
	,RELIEVED_RES_UNITS  
	,RELIEVED_RES_VALUE  
	,MAXIMUM_ASSIGNED_UNITS  
	,FIRM_FLAG  
	,GROUP_SEQUENCE_ID  
	,GROUP_SEQUENCE_NUMBER  
	,ACTUAL_START_DATE 
	,ACTUAL_COMPLETION_DATE 
	,PROJECTED_COMPLETION_DATE  
	,KCA_OPERATION
	,KCA_SEQ_ID
	,KCA_SEQ_DATE)
(select
	 WIP_ENTITY_ID 
	,OPERATION_SEQ_NUM 
	,RESOURCE_SEQ_NUM 
	,ORGANIZATION_ID 
	,REPETITIVE_SCHEDULE_ID 
	,LAST_UPDATE_DATE   
	,LAST_UPDATED_BY 
	,CREATION_DATE   
	,CREATED_BY 
	,LAST_UPDATE_LOGIN 
	,REQUEST_ID 
	,PROGRAM_APPLICATION_ID  
	,PROGRAM_ID  
	,PROGRAM_UPDATE_DATE  
	,RESOURCE_ID 
	,UOM_CODE 
	,BASIS_TYPE 
	,USAGE_RATE_OR_AMOUNT 
	,ACTIVITY_ID  
	,SCHEDULED_FLAG 
	,ASSIGNED_UNITS  
	,AUTOCHARGE_TYPE 
	,STANDARD_RATE_FLAG 
	,APPLIED_RESOURCE_UNITS  
	,APPLIED_RESOURCE_VALUE  
	,START_DATE    
	,COMPLETION_DATE  
	,ATTRIBUTE_CATEGORY 
	,ATTRIBUTE1 
	,ATTRIBUTE2 
	,ATTRIBUTE3 
	,ATTRIBUTE4 
	,ATTRIBUTE5 
	,ATTRIBUTE6 
	,ATTRIBUTE7 
	,ATTRIBUTE8 
	,ATTRIBUTE9 
	,ATTRIBUTE10 
	,ATTRIBUTE11 
	,ATTRIBUTE12 
	,ATTRIBUTE13 
	,ATTRIBUTE14 
	,ATTRIBUTE15 
	,RELIEVED_RES_COMPLETION_UNITS  
	,RELIEVED_RES_SCRAP_UNITS  
	,RELIEVED_RES_COMPLETION_VALUE  
	,RELIEVED_RES_SCRAP_VALUE  
	,RELIEVED_VARIANCE_VALUE  
	,TEMP_RELIEVED_VALUE  
	,RELIEVED_RES_FINAL_COMP_UNITS  
	,DEPARTMENT_ID  
	,PHANTOM_FLAG  
	,PHANTOM_OP_SEQ_NUM  
	,PHANTOM_ITEM_ID  
	,SCHEDULE_SEQ_NUM  
	,SUBSTITUTE_GROUP_NUM  
	,REPLACEMENT_GROUP_NUM  
	,PRINCIPLE_FLAG  
	,SETUP_ID  
	,PARENT_RESOURCE_SEQ  
	,BATCH_ID  
	,RELIEVED_RES_UNITS  
	,RELIEVED_RES_VALUE  
	,MAXIMUM_ASSIGNED_UNITS  
	,FIRM_FLAG  
	,GROUP_SEQUENCE_ID  
	,GROUP_SEQUENCE_NUMBER  
	,ACTUAL_START_DATE 
	,ACTUAL_COMPLETION_DATE 
	,PROJECTED_COMPLETION_DATE  
	,KCA_OPERATION
	,KCA_SEQ_ID
	,KCA_SEQ_DATE
from
	bec_raw_dl_ext.WIP_OPERATION_RESOURCES
where kca_operation != 'DELETE'  and nvl(kca_seq_id,'') != '' 
	and (nvl(WIP_ENTITY_ID,0) ,nvl(OPERATION_SEQ_NUM,0),nvl(RESOURCE_SEQ_NUM,0),nvl(REPETITIVE_SCHEDULE_ID,0),KCA_SEQ_ID) in 
	(select 
	    nvl(WIP_ENTITY_ID,0) as WIP_ENTITY_ID,nvl(OPERATION_SEQ_NUM,0) as OPERATION_SEQ_NUM,
		nvl(RESOURCE_SEQ_NUM,0) as RESOURCE_SEQ_NUM,nvl(REPETITIVE_SCHEDULE_ID,0) as REPETITIVE_SCHEDULE_ID
		,max(KCA_SEQ_ID) from bec_raw_dl_ext.WIP_OPERATION_RESOURCES
     where kca_operation != 'DELETE'  and nvl(kca_seq_id,'') != ''
     group by nvl(WIP_ENTITY_ID,0) ,nvl(OPERATION_SEQ_NUM,0),nvl(RESOURCE_SEQ_NUM,0),nvl(REPETITIVE_SCHEDULE_ID,0))
     and (KCA_SEQ_DATE > (select (executebegints-prune_days) from bec_etl_ctrl.batch_ods_info where ods_table_name ='wip_operation_resources')

            )
	 );
END;