/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for stage.
# File Version: KPI v1.0
*/
begin;

truncate
	table bec_ods_stg.xle_entity_profiles;

insert
	into
	bec_ods_stg.xle_entity_profiles
(LEGAL_ENTITY_ID,
PARTY_ID,
LEGAL_ENTITY_IDENTIFIER,
NAME,
GEOGRAPHY_ID,
TRANSACTING_ENTITY_FLAG,
EFFECTIVE_FROM,
EFFECTIVE_TO,
LE_INFORMATION_CONTEXT,
LE_INFORMATION1,
LE_INFORMATION2,
LE_INFORMATION3,
LE_INFORMATION4,
LE_INFORMATION5,
LE_INFORMATION6,
LE_INFORMATION7,
LE_INFORMATION8,
LE_INFORMATION9,
LE_INFORMATION10,
LE_INFORMATION11,
LE_INFORMATION12,
LE_INFORMATION13,
LE_INFORMATION14,
LE_INFORMATION15,
LE_INFORMATION16,
LE_INFORMATION17,
LE_INFORMATION18,
LE_INFORMATION19,
LE_INFORMATION20,
LAST_UPDATED_BY,
CREATION_DATE,
LAST_UPDATE_LOGIN,
LAST_UPDATE_DATE,
CREATED_BY,
OBJECT_VERSION_NUMBER,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
ATTRIBUTE16,
ATTRIBUTE17,
ATTRIBUTE18,
ATTRIBUTE19,
ATTRIBUTE20,
ACTIVITY_CODE,
SUB_ACTIVITY_CODE,
TYPE_OF_COMPANY,
KCA_OPERATION
,kca_seq_id
,KCA_SEQ_DATE)
(
	select
	LEGAL_ENTITY_ID,
PARTY_ID,
LEGAL_ENTITY_IDENTIFIER,
NAME,
GEOGRAPHY_ID,
TRANSACTING_ENTITY_FLAG,
EFFECTIVE_FROM,
EFFECTIVE_TO,
LE_INFORMATION_CONTEXT,
LE_INFORMATION1,
LE_INFORMATION2,
LE_INFORMATION3,
LE_INFORMATION4,
LE_INFORMATION5,
LE_INFORMATION6,
LE_INFORMATION7,
LE_INFORMATION8,
LE_INFORMATION9,
LE_INFORMATION10,
LE_INFORMATION11,
LE_INFORMATION12,
LE_INFORMATION13,
LE_INFORMATION14,
LE_INFORMATION15,
LE_INFORMATION16,
LE_INFORMATION17,
LE_INFORMATION18,
LE_INFORMATION19,
LE_INFORMATION20,
LAST_UPDATED_BY,
CREATION_DATE,
LAST_UPDATE_LOGIN,
LAST_UPDATE_DATE,
CREATED_BY,
OBJECT_VERSION_NUMBER,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
ATTRIBUTE16,
ATTRIBUTE17,
ATTRIBUTE18,
ATTRIBUTE19,
ATTRIBUTE20,
ACTIVITY_CODE,
SUB_ACTIVITY_CODE,
TYPE_OF_COMPANY,
KCA_OPERATION
,kca_seq_id
,KCA_SEQ_DATE
	from
		bec_raw_dl_ext.xle_entity_profiles
where kca_operation != 'DELETE'  and nvl(kca_seq_id,'') != '' and (LEGAL_ENTITY_ID,kca_seq_id) in (select LEGAL_ENTITY_ID,max(kca_seq_id) 
from bec_raw_dl_ext.xle_entity_profiles 
where kca_operation != 'DELETE'  and nvl(kca_seq_id,'') != ''
group by LEGAL_ENTITY_ID)
and 
(KCA_SEQ_DATE > (
select (executebegints-prune_days) from bec_etl_ctrl.batch_ods_info where ods_table_name = 'xle_entity_profiles')
     )
);
end;
