/* Delete Records   */
DELETE FROM silver_bec_ods.MSC_SUB_INVENTORIES
WHERE
  (COALESCE(PLAN_ID, 0), COALESCE(SR_INSTANCE_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(SUB_INVENTORY_CODE, 'NA')) IN (
    SELECT
      COALESCE(stg.PLAN_ID, 0) AS PLAN_ID,
      COALESCE(stg.SR_INSTANCE_ID, 0) AS SR_INSTANCE_ID,
      COALESCE(stg.ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
      COALESCE(stg.SUB_INVENTORY_CODE, 'NA') AS SUB_INVENTORY_CODE
    FROM silver_bec_ods.MSC_SUB_INVENTORIES AS ods, bronze_bec_ods_stg.MSC_SUB_INVENTORIES AS stg
    WHERE
      COALESCE(ods.PLAN_ID, 0) = COALESCE(stg.PLAN_ID, 0)
      AND COALESCE(ods.SR_INSTANCE_ID, 0) = COALESCE(stg.SR_INSTANCE_ID, 0)
      AND COALESCE(ods.ORGANIZATION_ID, 0) = COALESCE(stg.ORGANIZATION_ID, 0)
      AND COALESCE(ods.SUB_INVENTORY_CODE, 'NA') = COALESCE(stg.SUB_INVENTORY_CODE, 'NA')
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.MSC_SUB_INVENTORIES (
  PLAN_ID,
  ORGANIZATION_ID,
  SUB_INVENTORY_CODE,
  NETTING_TYPE,
  SR_INSTANCE_ID,
  DESCRIPTION,
  REFRESH_NUMBER,
  INVENTORY_ATP_CODE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  INCLUDE_NON_NETTABLE,
  SR_RESOURCE_NAME,
  SR_CUSTOMER_ACCT_ID,
  CONDITION_TYPE,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    PLAN_ID,
    ORGANIZATION_ID,
    SUB_INVENTORY_CODE,
    NETTING_TYPE,
    SR_INSTANCE_ID,
    DESCRIPTION,
    REFRESH_NUMBER,
    INVENTORY_ATP_CODE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    INCLUDE_NON_NETTABLE,
    SR_RESOURCE_NAME,
    SR_CUSTOMER_ACCT_ID,
    CONDITION_TYPE,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MSC_SUB_INVENTORIES
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(PLAN_ID, 0), COALESCE(SR_INSTANCE_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(SUB_INVENTORY_CODE, 'NA'), KCA_SEQ_ID) IN (
      SELECT
        COALESCE(PLAN_ID, 0) AS PLAN_ID,
        COALESCE(SR_INSTANCE_ID, 0) AS SR_INSTANCE_ID,
        COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
        COALESCE(SUB_INVENTORY_CODE, 'NA') AS SUB_INVENTORY_CODE,
        MAX(KCA_SEQ_ID)
      FROM bronze_bec_ods_stg.MSC_SUB_INVENTORIES
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(PLAN_ID, 0),
        COALESCE(SR_INSTANCE_ID, 0),
        COALESCE(ORGANIZATION_ID, 0),
        COALESCE(SUB_INVENTORY_CODE, 'NA')
    )
);
/* Soft delete */
UPDATE silver_bec_ods.MSC_SUB_INVENTORIES SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.MSC_SUB_INVENTORIES SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(PLAN_ID, 0), COALESCE(SR_INSTANCE_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(SUB_INVENTORY_CODE, 'NA')) IN (
    SELECT
      COALESCE(PLAN_ID, 0),
      COALESCE(SR_INSTANCE_ID, 0),
      COALESCE(ORGANIZATION_ID, 0),
      COALESCE(SUB_INVENTORY_CODE, 'NA')
    FROM bec_raw_dl_ext.MSC_SUB_INVENTORIES
    WHERE
      (COALESCE(PLAN_ID, 0), COALESCE(SR_INSTANCE_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(SUB_INVENTORY_CODE, 'NA'), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(PLAN_ID, 0),
          COALESCE(SR_INSTANCE_ID, 0),
          COALESCE(ORGANIZATION_ID, 0),
          COALESCE(SUB_INVENTORY_CODE, 'NA'),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.MSC_SUB_INVENTORIES
        GROUP BY
          COALESCE(PLAN_ID, 0),
          COALESCE(SR_INSTANCE_ID, 0),
          COALESCE(ORGANIZATION_ID, 0),
          COALESCE(SUB_INVENTORY_CODE, 'NA')
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_sub_inventories';