TRUNCATE table silver_bec_ods.BEC_CVMI_AGING_VIEW;
INSERT INTO silver_bec_ods.BEC_CVMI_AGING_VIEW (
  as_of_date,
  organization_id,
  vendor_id,
  vendor_site_id,
  item_id,
  primary_vendor_item,
  `name`,
  vendorname,
  vendorsitecode,
  items,
  description,
  uom,
  subinventory,
  `locator`,
  revision,
  receipt_date,
  consumebefore,
  quantity,
  aging_period,
  aging_days,
  aging_bucket,
  received_date_time,
  serial_lot_number,
  unit_price,
  extended_cost,
  percent_aging,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  as_of_date,
  organization_id,
  vendor_id,
  vendor_site_id,
  item_id,
  primary_vendor_item,
  `name`,
  vendorname,
  vendorsitecode,
  items,
  description,
  uom,
  subinventory,
  `locator`,
  revision,
  receipt_date,
  consumebefore,
  quantity,
  aging_period,
  aging_days,
  aging_bucket,
  received_date_time,
  serial_lot_number,
  unit_price,
  extended_cost,
  percent_aging,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.BEC_CVMI_AGING_VIEW;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'bec_cvmi_aging_view';