DROP TABLE IF EXISTS silver_bec_ods.MSC_TRADING_PARTNERS;
CREATE TABLE IF NOT EXISTS silver_bec_ods.MSC_TRADING_PARTNERS (
  partner_id DECIMAL(15, 0),
  sr_tp_id DECIMAL(15, 0),
  sr_instance_id DECIMAL(15, 0),
  organization_code STRING,
  disable_date TIMESTAMP,
  status STRING,
  master_organization DECIMAL(15, 0),
  weight_uom STRING,
  maximum_weight DECIMAL(28, 10),
  volume_uom STRING,
  maximum_volume DECIMAL(28, 10),
  partner_type DECIMAL(15, 0),
  partner_name STRING,
  partner_number STRING,
  calendar_code STRING,
  calendar_exception_set_id DECIMAL(15, 0),
  operating_unit DECIMAL(15, 0),
  project_reference_enabled DECIMAL(15, 0),
  project_control_level DECIMAL(15, 0),
  source_org_id DECIMAL(15, 0),
  demand_lateness_cost DECIMAL(28, 10),
  supplier_cap_overutil_cost DECIMAL(28, 10),
  resource_cap_overutil_cost DECIMAL(28, 10),
  default_demand_class STRING,
  modeled_customer_id DECIMAL(15, 0),
  modeled_customer_site_id DECIMAL(15, 0),
  modeled_supplier_id DECIMAL(15, 0),
  modeled_supplier_site_id DECIMAL(15, 0),
  transport_cap_over_util_cost DECIMAL(28, 10),
  refresh_number DECIMAL(15, 0),
  last_update_date TIMESTAMP,
  last_updated_by DECIMAL(15, 0),
  creation_date TIMESTAMP,
  created_by DECIMAL(15, 0),
  last_update_login DECIMAL(15, 0),
  request_id DECIMAL(15, 0),
  program_application_id DECIMAL(15, 0),
  program_id DECIMAL(15, 0),
  program_update_date TIMESTAMP,
  attribute_category STRING,
  attribute1 STRING,
  attribute2 STRING,
  attribute3 STRING,
  attribute4 STRING,
  attribute5 STRING,
  attribute6 STRING,
  attribute7 STRING,
  attribute8 STRING,
  attribute9 STRING,
  attribute10 STRING,
  attribute11 STRING,
  attribute12 STRING,
  attribute13 STRING,
  attribute14 STRING,
  attribute15 STRING,
  use_phantom_routings DECIMAL(15, 0),
  inherit_phantom_op_seq DECIMAL(15, 0),
  default_atp_rule_id DECIMAL(15, 0),
  material_account DECIMAL(15, 0),
  expense_account DECIMAL(15, 0),
  organization_type DECIMAL(15, 0),
  service_level DECIMAL(15, 0),
  customer_class_code STRING,
  company_id DECIMAL(15, 0),
  org_supplier_mapped STRING,
  accept_demands_from_unmet_po DECIMAL(15, 0),
  inherit_oc_op_seq_num DECIMAL(15, 0),
  sr_business_group_id DECIMAL(15, 0),
  sr_legal_entity DECIMAL(15, 0),
  sr_set_of_books_id DECIMAL(15, 0),
  sr_chart_of_accounts_id DECIMAL(15, 0),
  customer_type STRING,
  business_group_name STRING,
  legal_entity_name STRING,
  operating_unit_name STRING,
  currency_code STRING,
  SUBCONTRACTING_SOURCE_ORG DECIMAL(15, 0),
  TRADING_PARTNER_ORG_FLAG STRING,
  KCA_OPERATION STRING,
  IS_DELETED_FLG STRING,
  kca_seq_id DECIMAL(36, 0),
  kca_seq_date TIMESTAMP
);
INSERT INTO silver_bec_ods.MSC_TRADING_PARTNERS (
  partner_id,
  sr_tp_id,
  sr_instance_id,
  organization_code,
  disable_date,
  status,
  master_organization,
  weight_uom,
  maximum_weight,
  volume_uom,
  maximum_volume,
  partner_type,
  partner_name,
  partner_number,
  calendar_code,
  calendar_exception_set_id,
  operating_unit,
  project_reference_enabled,
  project_control_level,
  source_org_id,
  demand_lateness_cost,
  supplier_cap_overutil_cost,
  resource_cap_overutil_cost,
  default_demand_class,
  modeled_customer_id,
  modeled_customer_site_id,
  modeled_supplier_id,
  modeled_supplier_site_id,
  transport_cap_over_util_cost,
  refresh_number,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  use_phantom_routings,
  inherit_phantom_op_seq,
  default_atp_rule_id,
  material_account,
  expense_account,
  organization_type,
  service_level,
  customer_class_code,
  company_id,
  org_supplier_mapped,
  accept_demands_from_unmet_po,
  inherit_oc_op_seq_num,
  sr_business_group_id,
  sr_legal_entity,
  sr_set_of_books_id,
  sr_chart_of_accounts_id,
  customer_type,
  business_group_name,
  legal_entity_name,
  operating_unit_name,
  currency_code,
  SUBCONTRACTING_SOURCE_ORG,
  TRADING_PARTNER_ORG_FLAG,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  partner_id,
  sr_tp_id,
  sr_instance_id,
  organization_code,
  disable_date,
  status,
  master_organization,
  weight_uom,
  maximum_weight,
  volume_uom,
  maximum_volume,
  partner_type,
  partner_name,
  partner_number,
  calendar_code,
  calendar_exception_set_id,
  operating_unit,
  project_reference_enabled,
  project_control_level,
  source_org_id,
  demand_lateness_cost,
  supplier_cap_overutil_cost,
  resource_cap_overutil_cost,
  default_demand_class,
  modeled_customer_id,
  modeled_customer_site_id,
  modeled_supplier_id,
  modeled_supplier_site_id,
  transport_cap_over_util_cost,
  refresh_number,
  last_update_date,
  last_updated_by,
  creation_date,
  created_by,
  last_update_login,
  request_id,
  program_application_id,
  program_id,
  program_update_date,
  attribute_category,
  attribute1,
  attribute2,
  attribute3,
  attribute4,
  attribute5,
  attribute6,
  attribute7,
  attribute8,
  attribute9,
  attribute10,
  attribute11,
  attribute12,
  attribute13,
  attribute14,
  attribute15,
  use_phantom_routings,
  inherit_phantom_op_seq,
  default_atp_rule_id,
  material_account,
  expense_account,
  organization_type,
  service_level,
  customer_class_code,
  company_id,
  org_supplier_mapped,
  accept_demands_from_unmet_po,
  inherit_oc_op_seq_num,
  sr_business_group_id,
  sr_legal_entity,
  sr_set_of_books_id,
  sr_chart_of_accounts_id,
  customer_type,
  business_group_name,
  legal_entity_name,
  operating_unit_name,
  currency_code,
  SUBCONTRACTING_SOURCE_ORG,
  TRADING_PARTNER_ORG_FLAG,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.MSC_TRADING_PARTNERS;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_trading_partners';