/* Delete Records */
DELETE FROM silver_bec_ods.WSH_DOCUMENT_INSTANCES
WHERE
  (
    COALESCE(DOCUMENT_INSTANCE_ID, 0)
  ) IN (
    SELECT
      COALESCE(stg.DOCUMENT_INSTANCE_ID, 0) AS DOCUMENT_INSTANCE_ID
    FROM silver_bec_ods.WSH_DOCUMENT_INSTANCES AS ods, bronze_bec_ods_stg.WSH_DOCUMENT_INSTANCES AS stg
    WHERE
      COALESCE(ods.DOCUMENT_INSTANCE_ID, 0) = COALESCE(stg.DOCUMENT_INSTANCE_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.WSH_DOCUMENT_INSTANCES (
  DOCUMENT_INSTANCE_ID,
  ENTITY_NAME,
  ENTITY_ID,
  DOCUMENT_TYPE,
  SEQUENCE_NUMBER,
  STATUS,
  FINAL_PRINT_DATE,
  DOC_SEQUENCE_CATEGORY_ID,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  REQUEST_ID,
  POD_FLAG,
  POD_BY,
  POD_DATE,
  REASON_OF_TRANSPORT,
  DESCRIPTION,
  COD_AMOUNT,
  COD_CURRENCY_CODE,
  COD_REMIT_TO,
  COD_CHARGE_PAID_BY,
  PROBLEM_CONTACT_REFERENCE,
  BILL_FREIGHT_TO,
  CARRIED_BY,
  PORT_OF_LOADING,
  PORT_OF_DISCHARGE,
  BOOKING_OFFICE,
  BOOKING_NUMBER,
  SERVICE_CONTRACT,
  SHIPPER_EXPORT_REF,
  CARRIER_EXPORT_REF,
  BOL_NOTIFY_PARTY,
  SUPPLIER_CODE,
  AETC_NUMBER,
  SHIPPER_SIGNED_BY,
  SHIPPER_DATE,
  CARRIER_SIGNED_BY,
  CARRIER_DATE,
  BOL_ISSUE_OFFICE,
  BOL_ISSUED_BY,
  BOL_DATE_ISSUED,
  SHIPPER_HM_BY,
  SHIPPER_HM_DATE,
  CARRIER_HM_BY,
  CARRIER_HM_DATE,
  EXPECTED_POD_DATE,
  FUNC_AMOUNT,
  GROSS_AMOUNT,
  CURRENCY_CODE,
  CERTIFICATE_NUMBER,
  KEY_VERSION,
  SYSTEM_ENTRY_DATE,
  DOCUMENT_SEQ_ID,
  SIGNATURE,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    DOCUMENT_INSTANCE_ID,
    ENTITY_NAME,
    ENTITY_ID,
    DOCUMENT_TYPE,
    SEQUENCE_NUMBER,
    STATUS,
    FINAL_PRINT_DATE,
    DOC_SEQUENCE_CATEGORY_ID,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    REQUEST_ID,
    POD_FLAG,
    POD_BY,
    POD_DATE,
    REASON_OF_TRANSPORT,
    DESCRIPTION,
    COD_AMOUNT,
    COD_CURRENCY_CODE,
    COD_REMIT_TO,
    COD_CHARGE_PAID_BY,
    PROBLEM_CONTACT_REFERENCE,
    BILL_FREIGHT_TO,
    CARRIED_BY,
    PORT_OF_LOADING,
    PORT_OF_DISCHARGE,
    BOOKING_OFFICE,
    BOOKING_NUMBER,
    SERVICE_CONTRACT,
    SHIPPER_EXPORT_REF,
    CARRIER_EXPORT_REF,
    BOL_NOTIFY_PARTY,
    SUPPLIER_CODE,
    AETC_NUMBER,
    SHIPPER_SIGNED_BY,
    SHIPPER_DATE,
    CARRIER_SIGNED_BY,
    CARRIER_DATE,
    BOL_ISSUE_OFFICE,
    BOL_ISSUED_BY,
    BOL_DATE_ISSUED,
    SHIPPER_HM_BY,
    SHIPPER_HM_DATE,
    CARRIER_HM_BY,
    CARRIER_HM_DATE,
    EXPECTED_POD_DATE,
    FUNC_AMOUNT,
    GROSS_AMOUNT,
    CURRENCY_CODE,
    CERTIFICATE_NUMBER,
    KEY_VERSION,
    SYSTEM_ENTRY_DATE,
    DOCUMENT_SEQ_ID,
    SIGNATURE,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.WSH_DOCUMENT_INSTANCES
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(DOCUMENT_INSTANCE_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(DOCUMENT_INSTANCE_ID, 0) AS DOCUMENT_INSTANCE_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.WSH_DOCUMENT_INSTANCES
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(DOCUMENT_INSTANCE_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.WSH_DOCUMENT_INSTANCES SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.WSH_DOCUMENT_INSTANCES SET IS_DELETED_FLG = 'Y'
WHERE
  (
    DOCUMENT_INSTANCE_ID
  ) IN (
    SELECT
      DOCUMENT_INSTANCE_ID
    FROM bec_raw_dl_ext.WSH_DOCUMENT_INSTANCES
    WHERE
      (DOCUMENT_INSTANCE_ID, KCA_SEQ_ID) IN (
        SELECT
          DOCUMENT_INSTANCE_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.WSH_DOCUMENT_INSTANCES
        GROUP BY
          DOCUMENT_INSTANCE_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wsh_document_instances';