/* Delete Records */
DELETE FROM silver_bec_ods.wsh_carriers
WHERE
  (
    COALESCE(CARRIER_ID, 0)
  ) IN (
    SELECT
      COALESCE(stg.CARRIER_ID, 0) AS CARRIER_ID
    FROM silver_bec_ods.wsh_carriers AS ods, bronze_bec_ods_stg.wsh_carriers AS stg
    WHERE
      COALESCE(ods.CARRIER_ID, 0) = COALESCE(stg.CARRIER_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.wsh_carriers (
  CARRIER_ID,
  FREIGHT_CODE,
  SCAC_CODE,
  MANIFESTING_ENABLED_FLAG,
  CURRENCY_CODE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  GENERIC_FLAG,
  FREIGHT_BILL_AUTO_APPROVAL,
  FREIGHT_AUDIT_LINE_LEVEL,
  SUPPLIER_ID,
  SUPPLIER_SITE_ID,
  MAX_NUM_STOPS_PERMITTED,
  MAX_TOTAL_DISTANCE,
  MAX_TOTAL_TIME,
  ALLOW_INTERSPERSE_LOAD,
  MIN_LAYOVER_TIME,
  MAX_LAYOVER_TIME,
  MAX_TOTAL_DISTANCE_IN_24HR,
  MAX_DRIVING_TIME_IN_24HR,
  MAX_DUTY_TIME_IN_24HR,
  ALLOW_CONTINUOUS_MOVE,
  MAX_CM_DISTANCE,
  MAX_CM_TIME,
  MAX_CM_DH_DISTANCE,
  MAX_CM_DH_TIME,
  MIN_CM_DISTANCE,
  MIN_CM_TIME,
  CM_FREE_DH_MILEAGE,
  CM_FIRST_LOAD_DISCOUNT,
  CM_RATE_VARIANT,
  MAX_SIZE_WIDTH,
  MAX_SIZE_HEIGHT,
  MAX_SIZE_LENGTH,
  MIN_SIZE_WIDTH,
  MIN_SIZE_HEIGHT,
  MIN_SIZE_LENGTH,
  TIME_UOM,
  DIMENSION_UOM,
  DISTANCE_UOM,
  WEIGHT_UOM,
  VOLUME_UOM,
  MAX_OUT_OF_ROUTE,
  DISTANCE_CALCULATION_METHOD,
  ORIGIN_DSTN_SURCHARGE_LEVEL,
  UNIT_RATE_BASIS,
  DIM_DIMENSIONAL_FACTOR,
  DIM_WEIGHT_UOM,
  DIM_VOLUME_UOM,
  DIM_DIMENSION_UOM,
  DIM_MIN_PACK_VOL,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    CARRIER_ID,
    FREIGHT_CODE,
    SCAC_CODE,
    MANIFESTING_ENABLED_FLAG,
    CURRENCY_CODE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    GENERIC_FLAG,
    FREIGHT_BILL_AUTO_APPROVAL,
    FREIGHT_AUDIT_LINE_LEVEL,
    SUPPLIER_ID,
    SUPPLIER_SITE_ID,
    MAX_NUM_STOPS_PERMITTED,
    MAX_TOTAL_DISTANCE,
    MAX_TOTAL_TIME,
    ALLOW_INTERSPERSE_LOAD,
    MIN_LAYOVER_TIME,
    MAX_LAYOVER_TIME,
    MAX_TOTAL_DISTANCE_IN_24HR,
    MAX_DRIVING_TIME_IN_24HR,
    MAX_DUTY_TIME_IN_24HR,
    ALLOW_CONTINUOUS_MOVE,
    MAX_CM_DISTANCE,
    MAX_CM_TIME,
    MAX_CM_DH_DISTANCE,
    MAX_CM_DH_TIME,
    MIN_CM_DISTANCE,
    MIN_CM_TIME,
    CM_FREE_DH_MILEAGE,
    CM_FIRST_LOAD_DISCOUNT,
    CM_RATE_VARIANT,
    MAX_SIZE_WIDTH,
    MAX_SIZE_HEIGHT,
    MAX_SIZE_LENGTH,
    MIN_SIZE_WIDTH,
    MIN_SIZE_HEIGHT,
    MIN_SIZE_LENGTH,
    TIME_UOM,
    DIMENSION_UOM,
    DISTANCE_UOM,
    WEIGHT_UOM,
    VOLUME_UOM,
    MAX_OUT_OF_ROUTE,
    DISTANCE_CALCULATION_METHOD,
    ORIGIN_DSTN_SURCHARGE_LEVEL,
    UNIT_RATE_BASIS,
    DIM_DIMENSIONAL_FACTOR,
    DIM_WEIGHT_UOM,
    DIM_VOLUME_UOM,
    DIM_DIMENSION_UOM,
    DIM_MIN_PACK_VOL,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.wsh_carriers
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(CARRIER_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(CARRIER_ID, 0) AS CARRIER_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.wsh_carriers
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(CARRIER_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.wsh_carriers SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.wsh_carriers SET IS_DELETED_FLG = 'Y'
WHERE
  (
    CARRIER_ID
  ) IN (
    SELECT
      CARRIER_ID
    FROM bec_raw_dl_ext.wsh_carriers
    WHERE
      (CARRIER_ID, KCA_SEQ_ID) IN (
        SELECT
          CARRIER_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.wsh_carriers
        GROUP BY
          CARRIER_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'wsh_carriers';