/* Delete Records */
DELETE FROM silver_bec_ods.FND_RESPONSIBILITY
WHERE
  (COALESCE(APPLICATION_ID, 0), COALESCE(RESPONSIBILITY_ID, 0)) IN (
    SELECT
      COALESCE(stg.APPLICATION_ID, 0) AS APPLICATION_ID,
      COALESCE(stg.RESPONSIBILITY_ID, 0) AS RESPONSIBILITY_ID
    FROM silver_bec_ods.FND_RESPONSIBILITY AS ods, bronze_bec_ods_stg.FND_RESPONSIBILITY AS stg
    WHERE
      COALESCE(ods.APPLICATION_ID, 0) = COALESCE(stg.APPLICATION_ID, 0)
      AND COALESCE(ods.RESPONSIBILITY_ID, 0) = COALESCE(stg.RESPONSIBILITY_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.FND_RESPONSIBILITY (
  APPLICATION_ID,
  RESPONSIBILITY_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  DATA_GROUP_APPLICATION_ID,
  DATA_GROUP_ID,
  MENU_ID,
  TERM_SECURITY_ENABLED_FLAG,
  START_DATE,
  END_DATE,
  GROUP_APPLICATION_ID,
  REQUEST_GROUP_ID,
  VERSION,
  WEB_HOST_NAME,
  WEB_AGENT_NAME,
  RESPONSIBILITY_KEY,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    APPLICATION_ID,
    RESPONSIBILITY_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    DATA_GROUP_APPLICATION_ID,
    DATA_GROUP_ID,
    MENU_ID,
    TERM_SECURITY_ENABLED_FLAG,
    START_DATE,
    END_DATE,
    GROUP_APPLICATION_ID,
    REQUEST_GROUP_ID,
    VERSION,
    WEB_HOST_NAME,
    WEB_AGENT_NAME,
    RESPONSIBILITY_KEY,
    ZD_EDITION_NAME,
    ZD_SYNC,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.FND_RESPONSIBILITY
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(APPLICATION_ID, 0), COALESCE(RESPONSIBILITY_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(APPLICATION_ID, 0) AS APPLICATION_ID,
        COALESCE(RESPONSIBILITY_ID, 0) AS RESPONSIBILITY_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.FND_RESPONSIBILITY
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(APPLICATION_ID, 0),
        COALESCE(RESPONSIBILITY_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.FND_RESPONSIBILITY SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.FND_RESPONSIBILITY SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(APPLICATION_ID, 0), COALESCE(RESPONSIBILITY_ID, 0)) IN (
    SELECT
      COALESCE(APPLICATION_ID, 0),
      COALESCE(RESPONSIBILITY_ID, 0)
    FROM bec_raw_dl_ext.FND_RESPONSIBILITY
    WHERE
      (COALESCE(APPLICATION_ID, 0), COALESCE(RESPONSIBILITY_ID, 0), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(APPLICATION_ID, 0),
          COALESCE(RESPONSIBILITY_ID, 0),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.FND_RESPONSIBILITY
        GROUP BY
          COALESCE(APPLICATION_ID, 0),
          COALESCE(RESPONSIBILITY_ID, 0)
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fnd_responsibility';