/* Delete Records */
DELETE FROM silver_bec_ods.GL_LEDGER_RELATIONSHIPS
WHERE
  (
    RELATIONSHIP_ID
  ) IN (
    SELECT
      stg.RELATIONSHIP_ID
    FROM silver_bec_ods.GL_LEDGER_RELATIONSHIPS AS ods, bronze_bec_ods_stg.GL_LEDGER_RELATIONSHIPS AS stg
    WHERE
      ods.RELATIONSHIP_ID = stg.RELATIONSHIP_ID
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.GL_LEDGER_RELATIONSHIPS (
  RELATIONSHIP_ID,
  SOURCE_LEDGER_ID,
  TARGET_LEDGER_ID,
  SLA_LEDGER_ID,
  PRIMARY_LEDGER_ID,
  TARGET_CURRENCY_CODE,
  TARGET_LEDGER_NAME,
  TARGET_LEDGER_SHORT_NAME,
  TARGET_LEDGER_CATEGORY_CODE,
  RELATIONSHIP_TYPE_CODE,
  RELATIONSHIP_ENABLED_FLAG,
  INHERIT_CREATION_USER_FLAG,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  GL_JE_CONVERSION_SET_ID,
  SL_COA_MAPPING_ID,
  AUTOMATIC_POST_FLAG,
  ALC_DEFAULT_CONV_RATE_TYPE,
  ALC_NO_RATE_ACTION_CODE,
  ALC_MAX_DAYS_ROLL_RATE,
  ALC_INHERIT_CONVERSION_TYPE,
  ALC_INIT_CONV_OPTION_CODE,
  ALC_INIT_PERIOD,
  ALC_INIT_DATE,
  ALC_INITIALIZING_RATE_DATE,
  ALC_INITIALIZING_RATE_TYPE,
  ALC_PERIOD_AVERAGE_RATE_TYPE,
  ALC_PERIOD_END_RATE_TYPE,
  APPLICATION_ID,
  ORG_ID,
  DISABLE_CONVERSION_DATE,
  STATUS_CODE,
  HIST_CONV_STATUS_CODE,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    RELATIONSHIP_ID,
    SOURCE_LEDGER_ID,
    TARGET_LEDGER_ID,
    SLA_LEDGER_ID,
    PRIMARY_LEDGER_ID,
    TARGET_CURRENCY_CODE,
    TARGET_LEDGER_NAME,
    TARGET_LEDGER_SHORT_NAME,
    TARGET_LEDGER_CATEGORY_CODE,
    RELATIONSHIP_TYPE_CODE,
    RELATIONSHIP_ENABLED_FLAG,
    INHERIT_CREATION_USER_FLAG,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    GL_JE_CONVERSION_SET_ID,
    SL_COA_MAPPING_ID,
    AUTOMATIC_POST_FLAG,
    ALC_DEFAULT_CONV_RATE_TYPE,
    ALC_NO_RATE_ACTION_CODE,
    ALC_MAX_DAYS_ROLL_RATE,
    ALC_INHERIT_CONVERSION_TYPE,
    ALC_INIT_CONV_OPTION_CODE,
    ALC_INIT_PERIOD,
    ALC_INIT_DATE,
    ALC_INITIALIZING_RATE_DATE,
    ALC_INITIALIZING_RATE_TYPE,
    ALC_PERIOD_AVERAGE_RATE_TYPE,
    ALC_PERIOD_END_RATE_TYPE,
    APPLICATION_ID,
    ORG_ID,
    DISABLE_CONVERSION_DATE,
    STATUS_CODE,
    HIST_CONV_STATUS_CODE,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.GL_LEDGER_RELATIONSHIPS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (RELATIONSHIP_ID, kca_seq_id) IN (
      SELECT
        RELATIONSHIP_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.GL_LEDGER_RELATIONSHIPS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        RELATIONSHIP_ID
    )
);
/* Soft delete */
UPDATE silver_bec_ods.GL_LEDGER_RELATIONSHIPS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.GL_LEDGER_RELATIONSHIPS SET IS_DELETED_FLG = 'Y'
WHERE
  (
    RELATIONSHIP_ID
  ) IN (
    SELECT
      RELATIONSHIP_ID
    FROM bec_raw_dl_ext.GL_LEDGER_RELATIONSHIPS
    WHERE
      (RELATIONSHIP_ID, KCA_SEQ_ID) IN (
        SELECT
          RELATIONSHIP_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.GL_LEDGER_RELATIONSHIPS
        GROUP BY
          RELATIONSHIP_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_ledger_relationships';