/* Delete Records */
DELETE FROM silver_bec_ods.XLA_EVENTS
WHERE
  (EVENT_ID, APPLICATION_ID) IN (
    SELECT
      stg.EVENT_ID,
      stg.APPLICATION_ID
    FROM silver_bec_ods.XLA_EVENTS AS ods, bronze_bec_ods_stg.XLA_EVENTS AS stg
    WHERE
      ods.EVENT_ID = stg.EVENT_ID
      AND ods.APPLICATION_ID = stg.APPLICATION_ID
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.XLA_EVENTS (
  EVENT_ID,
  APPLICATION_ID,
  EVENT_TYPE_CODE,
  EVENT_DATE,
  ENTITY_ID,
  EVENT_STATUS_CODE,
  PROCESS_STATUS_CODE,
  REFERENCE_NUM_1,
  REFERENCE_NUM_2,
  REFERENCE_NUM_3,
  REFERENCE_NUM_4,
  REFERENCE_CHAR_1,
  REFERENCE_CHAR_2,
  REFERENCE_CHAR_3,
  REFERENCE_CHAR_4,
  REFERENCE_DATE_1,
  REFERENCE_DATE_2,
  REFERENCE_DATE_3,
  REFERENCE_DATE_4,
  EVENT_NUMBER,
  ON_HOLD_FLAG,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  PROGRAM_UPDATE_DATE,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  REQUEST_ID,
  UPG_BATCH_ID,
  UPG_SOURCE_APPLICATION_ID,
  UPG_VALID_FLAG,
  TRANSACTION_DATE,
  BUDGETARY_CONTROL_FLAG,
  MERGE_EVENT_SET_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  kca_seq_date
)
(
  SELECT
    EVENT_ID,
    APPLICATION_ID,
    EVENT_TYPE_CODE,
    EVENT_DATE,
    ENTITY_ID,
    EVENT_STATUS_CODE,
    PROCESS_STATUS_CODE,
    REFERENCE_NUM_1,
    REFERENCE_NUM_2,
    REFERENCE_NUM_3,
    REFERENCE_NUM_4,
    REFERENCE_CHAR_1,
    REFERENCE_CHAR_2,
    REFERENCE_CHAR_3,
    REFERENCE_CHAR_4,
    REFERENCE_DATE_1,
    REFERENCE_DATE_2,
    REFERENCE_DATE_3,
    REFERENCE_DATE_4,
    EVENT_NUMBER,
    ON_HOLD_FLAG,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    PROGRAM_UPDATE_DATE,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    REQUEST_ID,
    UPG_BATCH_ID,
    UPG_SOURCE_APPLICATION_ID,
    UPG_VALID_FLAG,
    TRANSACTION_DATE,
    BUDGETARY_CONTROL_FLAG,
    MERGE_EVENT_SET_ID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.XLA_EVENTS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (EVENT_ID, APPLICATION_ID, kca_seq_id) IN (
      SELECT
        EVENT_ID,
        APPLICATION_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.XLA_EVENTS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        EVENT_ID,
        APPLICATION_ID
    )
);
/* Soft delete */
UPDATE silver_bec_ods.XLA_EVENTS SET IS_DELETED_FLG = 'Y'
WHERE
  (EVENT_ID, APPLICATION_ID) IN (
    SELECT
      ext.EVENT_ID,
      ext.APPLICATION_ID
    FROM silver_bec_ods.XLA_EVENTS AS ods, bec_raw_dl_ext.XLA_EVENTS AS ext
    WHERE
      ods.EVENT_ID = ext.EVENT_ID
      AND ods.APPLICATION_ID = ext.APPLICATION_ID
      AND ext.kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP(), load_type = 'I'
WHERE
  ods_table_name = 'xla_events';