/* Delete Records */
DELETE FROM silver_bec_ods.XLA_EVENT_CLASSES_TL
WHERE
  (COALESCE(APPLICATION_ID, 0), COALESCE(ENTITY_CODE, 'NA'), COALESCE(EVENT_CLASS_CODE, 'NA'), COALESCE(LANGUAGE, 'NA')) IN (
    SELECT
      COALESCE(stg.APPLICATION_ID, 0) AS APPLICATION_ID,
      COALESCE(stg.ENTITY_CODE, 'NA') AS ENTITY_CODE,
      COALESCE(stg.EVENT_CLASS_CODE, 'NA') AS EVENT_CLASS_CODE,
      COALESCE(stg.LANGUAGE, 'NA') AS LANGUAGE
    FROM silver_bec_ods.XLA_EVENT_CLASSES_TL AS ods, bronze_bec_ods_stg.XLA_EVENT_CLASSES_TL AS stg
    WHERE
      COALESCE(ods.APPLICATION_ID, 0) = COALESCE(stg.APPLICATION_ID, 0)
      AND COALESCE(ods.ENTITY_CODE, 'NA') = COALESCE(stg.ENTITY_CODE, 'NA')
      AND COALESCE(ods.EVENT_CLASS_CODE, 'NA') = COALESCE(stg.EVENT_CLASS_CODE, 'NA')
      AND COALESCE(ods.LANGUAGE, 'NA') = COALESCE(stg.LANGUAGE, 'NA')
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.XLA_EVENT_CLASSES_TL (
  APPLICATION_ID,
  ENTITY_CODE,
  EVENT_CLASS_CODE,
  LANGUAGE,
  NAME,
  DESCRIPTION,
  SOURCE_LANG,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    APPLICATION_ID,
    ENTITY_CODE,
    EVENT_CLASS_CODE,
    LANGUAGE,
    NAME,
    DESCRIPTION,
    SOURCE_LANG,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    ZD_EDITION_NAME,
    ZD_SYNC,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.XLA_EVENT_CLASSES_TL
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(APPLICATION_ID, 0), COALESCE(ENTITY_CODE, 'NA'), COALESCE(EVENT_CLASS_CODE, 'NA'), COALESCE(LANGUAGE, 'NA'), kca_seq_id) IN (
      SELECT
        COALESCE(APPLICATION_ID, 0) AS APPLICATION_ID,
        COALESCE(ENTITY_CODE, 'NA') AS ENTITY_CODE,
        COALESCE(EVENT_CLASS_CODE, 'NA') AS EVENT_CLASS_CODE,
        COALESCE(LANGUAGE, 'NA') AS LANGUAGE,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.XLA_EVENT_CLASSES_TL
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(APPLICATION_ID, 0),
        COALESCE(ENTITY_CODE, 'NA'),
        COALESCE(EVENT_CLASS_CODE, 'NA'),
        COALESCE(LANGUAGE, 'NA')
    )
);
/* Soft delete */
UPDATE silver_bec_ods.XLA_EVENT_CLASSES_TL SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.XLA_EVENT_CLASSES_TL SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(APPLICATION_ID, 0), COALESCE(ENTITY_CODE, 'NA'), COALESCE(EVENT_CLASS_CODE, 'NA'), COALESCE(LANGUAGE, 'NA')) IN (
    SELECT
      COALESCE(APPLICATION_ID, 0),
      COALESCE(ENTITY_CODE, 'NA'),
      COALESCE(EVENT_CLASS_CODE, 'NA'),
      COALESCE(LANGUAGE, 'NA')
    FROM bec_raw_dl_ext.XLA_EVENT_CLASSES_TL
    WHERE
      (COALESCE(APPLICATION_ID, 0), COALESCE(ENTITY_CODE, 'NA'), COALESCE(EVENT_CLASS_CODE, 'NA'), COALESCE(LANGUAGE, 'NA'), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(APPLICATION_ID, 0),
          COALESCE(ENTITY_CODE, 'NA'),
          COALESCE(EVENT_CLASS_CODE, 'NA'),
          COALESCE(LANGUAGE, 'NA'),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.XLA_EVENT_CLASSES_TL
        GROUP BY
          COALESCE(APPLICATION_ID, 0),
          COALESCE(ENTITY_CODE, 'NA'),
          COALESCE(EVENT_CLASS_CODE, 'NA'),
          COALESCE(LANGUAGE, 'NA')
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'xla_event_classes_tl';