/* Delete Records */
DELETE FROM silver_bec_ods.CSI_COUNTER_ASSOCIATIONS
WHERE
  (
    COALESCE(INSTANCE_ASSOCIATION_ID, 0)
  ) IN (
    SELECT
      COALESCE(stg.INSTANCE_ASSOCIATION_ID, 0) AS INSTANCE_ASSOCIATION_ID
    FROM silver_bec_ods.CSI_COUNTER_ASSOCIATIONS AS ods, bronze_bec_ods_stg.CSI_COUNTER_ASSOCIATIONS AS stg
    WHERE
      COALESCE(ods.INSTANCE_ASSOCIATION_ID, 0) = COALESCE(stg.INSTANCE_ASSOCIATION_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.CSI_COUNTER_ASSOCIATIONS (
  INSTANCE_ASSOCIATION_ID,
  SOURCE_OBJECT_CODE,
  SOURCE_OBJECT_ID,
  COUNTER_ID,
  START_DATE_ACTIVE,
  END_DATE_ACTIVE,
  SECURITY_GROUP_ID,
  OBJECT_VERSION_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  MIGRATED_FLAG,
  MAINT_ORGANIZATION_ID,
  PRIMARY_FAILURE_FLAG,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    INSTANCE_ASSOCIATION_ID,
    SOURCE_OBJECT_CODE,
    SOURCE_OBJECT_ID,
    COUNTER_ID,
    START_DATE_ACTIVE,
    END_DATE_ACTIVE,
    SECURITY_GROUP_ID,
    OBJECT_VERSION_NUMBER,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    MIGRATED_FLAG,
    MAINT_ORGANIZATION_ID,
    PRIMARY_FAILURE_FLAG,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.CSI_COUNTER_ASSOCIATIONS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(INSTANCE_ASSOCIATION_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(INSTANCE_ASSOCIATION_ID, 0) AS INSTANCE_ASSOCIATION_ID,
        MAX(kca_seq_id) AS kca_seq_id
      FROM bronze_bec_ods_stg.CSI_COUNTER_ASSOCIATIONS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(INSTANCE_ASSOCIATION_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.CSI_COUNTER_ASSOCIATIONS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.CSI_COUNTER_ASSOCIATIONS SET IS_DELETED_FLG = 'Y'
WHERE
  (
    INSTANCE_ASSOCIATION_ID
  ) IN (
    SELECT
      INSTANCE_ASSOCIATION_ID
    FROM bec_raw_dl_ext.CSI_COUNTER_ASSOCIATIONS
    WHERE
      (INSTANCE_ASSOCIATION_ID, KCA_SEQ_ID) IN (
        SELECT
          INSTANCE_ASSOCIATION_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.CSI_COUNTER_ASSOCIATIONS
        GROUP BY
          INSTANCE_ASSOCIATION_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'csi_counter_associations';