/* Delete Records */
DELETE FROM silver_bec_ods.gl_je_batches
WHERE
  je_batch_ID IN (
    SELECT
      stg.je_batch_ID
    FROM silver_bec_ods.gl_je_batches AS ods, bronze_bec_ods_stg.gl_je_batches AS stg
    WHERE
      ods.je_batch_ID = stg.je_batch_ID AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.gl_je_batches (
  JE_BATCH_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  SET_OF_BOOKS_ID_11I,
  NAME,
  STATUS,
  STATUS_VERIFIED,
  ACTUAL_FLAG,
  DEFAULT_EFFECTIVE_DATE,
  BUDGETARY_CONTROL_STATUS,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  STATUS_RESET_FLAG,
  DEFAULT_PERIOD_NAME,
  UNIQUE_DATE,
  EARLIEST_POSTABLE_DATE,
  POSTED_DATE,
  DATE_CREATED,
  DESCRIPTION,
  CONTROL_TOTAL,
  RUNNING_TOTAL_DR,
  RUNNING_TOTAL_CR,
  RUNNING_TOTAL_ACCOUNTED_DR,
  RUNNING_TOTAL_ACCOUNTED_CR,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  CONTEXT,
  PACKET_ID,
  USSGL_TRANSACTION_CODE,
  CONTEXT2,
  POSTING_RUN_ID,
  REQUEST_ID,
  UNRESERVATION_PACKET_ID,
  AVERAGE_JOURNAL_FLAG,
  ORG_ID,
  APPROVAL_STATUS_CODE,
  PARENT_JE_BATCH_ID,
  POSTED_BY,
  CHART_OF_ACCOUNTS_ID,
  PERIOD_SET_NAME,
  ACCOUNTED_PERIOD_TYPE,
  GROUP_ID,
  APPROVER_EMPLOYEE_ID,
  GLOBAL_ATTRIBUTE_CATEGORY,
  GLOBAL_ATTRIBUTE1,
  GLOBAL_ATTRIBUTE2,
  GLOBAL_ATTRIBUTE3,
  GLOBAL_ATTRIBUTE4,
  GLOBAL_ATTRIBUTE5,
  GLOBAL_ATTRIBUTE6,
  GLOBAL_ATTRIBUTE7,
  GLOBAL_ATTRIBUTE8,
  GLOBAL_ATTRIBUTE9,
  GLOBAL_ATTRIBUTE10,
  GLOBAL_ATTRIBUTE11,
  GLOBAL_ATTRIBUTE12,
  GLOBAL_ATTRIBUTE13,
  GLOBAL_ATTRIBUTE14,
  GLOBAL_ATTRIBUTE15,
  GLOBAL_ATTRIBUTE16,
  GLOBAL_ATTRIBUTE17,
  GLOBAL_ATTRIBUTE18,
  GLOBAL_ATTRIBUTE19,
  GLOBAL_ATTRIBUTE20,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  kca_seq_date
)
(
  SELECT
    JE_BATCH_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    SET_OF_BOOKS_ID_11I,
    NAME,
    STATUS,
    STATUS_VERIFIED,
    ACTUAL_FLAG,
    DEFAULT_EFFECTIVE_DATE,
    BUDGETARY_CONTROL_STATUS,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    STATUS_RESET_FLAG,
    DEFAULT_PERIOD_NAME,
    UNIQUE_DATE,
    EARLIEST_POSTABLE_DATE,
    POSTED_DATE,
    DATE_CREATED,
    DESCRIPTION,
    CONTROL_TOTAL,
    RUNNING_TOTAL_DR,
    RUNNING_TOTAL_CR,
    RUNNING_TOTAL_ACCOUNTED_DR,
    RUNNING_TOTAL_ACCOUNTED_CR,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    CONTEXT,
    PACKET_ID,
    USSGL_TRANSACTION_CODE,
    CONTEXT2,
    POSTING_RUN_ID,
    REQUEST_ID,
    UNRESERVATION_PACKET_ID,
    AVERAGE_JOURNAL_FLAG,
    ORG_ID,
    APPROVAL_STATUS_CODE,
    PARENT_JE_BATCH_ID,
    POSTED_BY,
    CHART_OF_ACCOUNTS_ID,
    PERIOD_SET_NAME,
    ACCOUNTED_PERIOD_TYPE,
    GROUP_ID,
    APPROVER_EMPLOYEE_ID,
    GLOBAL_ATTRIBUTE_CATEGORY,
    GLOBAL_ATTRIBUTE1,
    GLOBAL_ATTRIBUTE2,
    GLOBAL_ATTRIBUTE3,
    GLOBAL_ATTRIBUTE4,
    GLOBAL_ATTRIBUTE5,
    GLOBAL_ATTRIBUTE6,
    GLOBAL_ATTRIBUTE7,
    GLOBAL_ATTRIBUTE8,
    GLOBAL_ATTRIBUTE9,
    GLOBAL_ATTRIBUTE10,
    GLOBAL_ATTRIBUTE11,
    GLOBAL_ATTRIBUTE12,
    GLOBAL_ATTRIBUTE13,
    GLOBAL_ATTRIBUTE14,
    GLOBAL_ATTRIBUTE15,
    GLOBAL_ATTRIBUTE16,
    GLOBAL_ATTRIBUTE17,
    GLOBAL_ATTRIBUTE18,
    GLOBAL_ATTRIBUTE19,
    GLOBAL_ATTRIBUTE20,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.gl_je_batches
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (je_batch_ID, kca_seq_id) IN (
      SELECT
        je_batch_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.gl_je_batches
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        je_batch_ID
    )
);
/* Soft delete */
UPDATE silver_bec_ods.gl_je_batches SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.gl_je_batches SET IS_DELETED_FLG = 'Y'
WHERE
  (
    je_batch_ID
  ) IN (
    SELECT
      je_batch_ID
    FROM bec_raw_dl_ext.gl_je_batches
    WHERE
      (je_batch_ID, KCA_SEQ_ID) IN (
        SELECT
          je_batch_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.gl_je_batches
        GROUP BY
          je_batch_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_je_batches';