/* Delete Records */
DELETE FROM silver_bec_ods.BOM_OPERATION_SEQUENCES
WHERE
  (
    COALESCE(OPERATION_SEQUENCE_ID, '0')
  ) IN (
    SELECT
      COALESCE(stg.OPERATION_SEQUENCE_ID, '0') AS OPERATION_SEQUENCE_ID
    FROM silver_bec_ods.bom_operation_sequences AS ods, bronze_bec_ods_stg.bom_operation_sequences AS stg
    WHERE
      COALESCE(ods.OPERATION_SEQUENCE_ID, '0') = COALESCE(stg.OPERATION_SEQUENCE_ID, '0')
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.bom_operation_sequences (
  OPERATION_SEQUENCE_ID,
  ROUTING_SEQUENCE_ID,
  OPERATION_SEQ_NUM,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  STANDARD_OPERATION_ID,
  DEPARTMENT_ID,
  OPERATION_LEAD_TIME_PERCENT,
  MINIMUM_TRANSFER_QUANTITY,
  COUNT_POINT_TYPE,
  OPERATION_DESCRIPTION,
  EFFECTIVITY_DATE,
  DISABLE_DATE,
  BACKFLUSH_FLAG,
  OPTION_DEPENDENT_FLAG,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  OPERATION_TYPE,
  REFERENCE_FLAG,
  PROCESS_OP_SEQ_ID,
  LINE_OP_SEQ_ID,
  YIELD,
  CUMULATIVE_YIELD,
  REVERSE_CUMULATIVE_YIELD,
  LABOR_TIME_CALC,
  MACHINE_TIME_CALC,
  TOTAL_TIME_CALC,
  LABOR_TIME_USER,
  MACHINE_TIME_USER,
  TOTAL_TIME_USER,
  NET_PLANNING_PERCENT,
  X_COORDINATE,
  Y_COORDINATE,
  INCLUDE_IN_ROLLUP,
  OPERATION_YIELD_ENABLED,
  OLD_OPERATION_SEQUENCE_ID,
  ACD_TYPE,
  REVISED_ITEM_SEQUENCE_ID,
  ORIGINAL_SYSTEM_REFERENCE,
  CHANGE_NOTICE,
  IMPLEMENTATION_DATE,
  ECO_FOR_PRODUCTION,
  SHUTDOWN_TYPE,
  ACTUAL_IPK,
  CRITICAL_TO_QUALITY,
  VALUE_ADDED,
  MACHINE_PROCESS_EFFICIENCY,
  LABOR_PROCESS_EFFICIENCY,
  TOTAL_PROCESS_EFFICIENCY,
  LONG_DESCRIPTION,
  CONFIG_ROUTING_ID,
  MODEL_OP_SEQ_ID,
  LOWEST_ACCEPTABLE_YIELD,
  USE_ORG_SETTINGS,
  QUEUE_MANDATORY_FLAG,
  RUN_MANDATORY_FLAG,
  TO_MOVE_MANDATORY_FLAG,
  SHOW_NEXT_OP_BY_DEFAULT,
  SHOW_SCRAP_CODE,
  SHOW_LOT_ATTRIB,
  TRACK_MULTIPLE_RES_USAGE_DATES,
  CHECK_SKILL,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    OPERATION_SEQUENCE_ID,
    ROUTING_SEQUENCE_ID,
    OPERATION_SEQ_NUM,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    STANDARD_OPERATION_ID,
    DEPARTMENT_ID,
    OPERATION_LEAD_TIME_PERCENT,
    MINIMUM_TRANSFER_QUANTITY,
    COUNT_POINT_TYPE,
    OPERATION_DESCRIPTION,
    EFFECTIVITY_DATE,
    DISABLE_DATE,
    BACKFLUSH_FLAG,
    OPTION_DEPENDENT_FLAG,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    OPERATION_TYPE,
    REFERENCE_FLAG,
    PROCESS_OP_SEQ_ID,
    LINE_OP_SEQ_ID,
    YIELD,
    CUMULATIVE_YIELD,
    REVERSE_CUMULATIVE_YIELD,
    LABOR_TIME_CALC,
    MACHINE_TIME_CALC,
    TOTAL_TIME_CALC,
    LABOR_TIME_USER,
    MACHINE_TIME_USER,
    TOTAL_TIME_USER,
    NET_PLANNING_PERCENT,
    X_COORDINATE,
    Y_COORDINATE,
    INCLUDE_IN_ROLLUP,
    OPERATION_YIELD_ENABLED,
    OLD_OPERATION_SEQUENCE_ID,
    ACD_TYPE,
    REVISED_ITEM_SEQUENCE_ID,
    ORIGINAL_SYSTEM_REFERENCE,
    CHANGE_NOTICE,
    IMPLEMENTATION_DATE,
    ECO_FOR_PRODUCTION,
    SHUTDOWN_TYPE,
    ACTUAL_IPK,
    CRITICAL_TO_QUALITY,
    VALUE_ADDED,
    MACHINE_PROCESS_EFFICIENCY,
    LABOR_PROCESS_EFFICIENCY,
    TOTAL_PROCESS_EFFICIENCY,
    LONG_DESCRIPTION,
    CONFIG_ROUTING_ID,
    MODEL_OP_SEQ_ID,
    LOWEST_ACCEPTABLE_YIELD,
    USE_ORG_SETTINGS,
    QUEUE_MANDATORY_FLAG,
    RUN_MANDATORY_FLAG,
    TO_MOVE_MANDATORY_FLAG,
    SHOW_NEXT_OP_BY_DEFAULT,
    SHOW_SCRAP_CODE,
    SHOW_LOT_ATTRIB,
    TRACK_MULTIPLE_RES_USAGE_DATES,
    CHECK_SKILL,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.bom_operation_sequences
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(OPERATION_SEQUENCE_ID, '0'), kca_seq_id) IN (
      SELECT
        COALESCE(OPERATION_SEQUENCE_ID, '0') AS OPERATION_SEQUENCE_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.bom_operation_sequences
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(OPERATION_SEQUENCE_ID, '0')
    )
);
/* Soft delete */
UPDATE silver_bec_ods.bom_operation_sequences SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.bom_operation_sequences SET IS_DELETED_FLG = 'Y'
WHERE
  (
    OPERATION_SEQUENCE_ID
  ) IN (
    SELECT
      OPERATION_SEQUENCE_ID
    FROM bec_raw_dl_ext.bom_operation_sequences
    WHERE
      (OPERATION_SEQUENCE_ID, KCA_SEQ_ID) IN (
        SELECT
          OPERATION_SEQUENCE_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.bom_operation_sequences
        GROUP BY
          OPERATION_SEQUENCE_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'bom_operation_sequences';