/* Delete Records */
DELETE FROM silver_bec_ods.XLA_DISTRIBUTION_LINKS
WHERE
  (COALESCE(APPLICATION_ID, 0), COALESCE(REF_AE_HEADER_ID, 0), COALESCE(TEMP_LINE_NUM, 0), COALESCE(AE_HEADER_ID, 0)) IN (
    SELECT
      COALESCE(stg.APPLICATION_ID, 0),
      COALESCE(stg.REF_AE_HEADER_ID, 0),
      COALESCE(stg.TEMP_LINE_NUM, 0),
      COALESCE(stg.AE_HEADER_ID, 0)
    FROM silver_bec_ods.XLA_DISTRIBUTION_LINKS AS ods, bronze_bec_ods_stg.XLA_DISTRIBUTION_LINKS AS stg
    WHERE
      COALESCE(ods.APPLICATION_ID, 0) = COALESCE(stg.APPLICATION_ID, 0)
      AND COALESCE(ods.REF_AE_HEADER_ID, 0) = COALESCE(stg.REF_AE_HEADER_ID, 0)
      AND COALESCE(ods.TEMP_LINE_NUM, 0) = COALESCE(stg.TEMP_LINE_NUM, 0)
      AND COALESCE(ods.AE_HEADER_ID, 0) = COALESCE(stg.AE_HEADER_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.XLA_DISTRIBUTION_LINKS (
  APPLICATION_ID,
  EVENT_ID,
  AE_HEADER_ID,
  AE_LINE_NUM,
  SOURCE_DISTRIBUTION_TYPE,
  SOURCE_DISTRIBUTION_ID_CHAR_1,
  SOURCE_DISTRIBUTION_ID_CHAR_2,
  SOURCE_DISTRIBUTION_ID_CHAR_3,
  SOURCE_DISTRIBUTION_ID_CHAR_4,
  SOURCE_DISTRIBUTION_ID_CHAR_5,
  SOURCE_DISTRIBUTION_ID_NUM_1,
  SOURCE_DISTRIBUTION_ID_NUM_2,
  SOURCE_DISTRIBUTION_ID_NUM_3,
  SOURCE_DISTRIBUTION_ID_NUM_4,
  SOURCE_DISTRIBUTION_ID_NUM_5,
  TAX_LINE_REF_ID,
  TAX_SUMMARY_LINE_REF_ID,
  TAX_REC_NREC_DIST_REF_ID,
  STATISTICAL_AMOUNT,
  REF_AE_HEADER_ID,
  REF_TEMP_LINE_NUM,
  ACCOUNTING_LINE_CODE,
  ACCOUNTING_LINE_TYPE_CODE,
  MERGE_DUPLICATE_CODE,
  TEMP_LINE_NUM,
  REF_EVENT_ID,
  LINE_DEFINITION_OWNER_CODE,
  LINE_DEFINITION_CODE,
  EVENT_CLASS_CODE,
  EVENT_TYPE_CODE,
  UPG_BATCH_ID,
  CALCULATE_ACCTD_AMTS_FLAG,
  CALCULATE_G_L_AMTS_FLAG,
  ROUNDING_CLASS_CODE,
  DOCUMENT_ROUNDING_LEVEL,
  UNROUNDED_ENTERED_DR,
  UNROUNDED_ENTERED_CR,
  DOC_ROUNDING_ENTERED_AMT,
  DOC_ROUNDING_ACCTD_AMT,
  UNROUNDED_ACCOUNTED_CR,
  UNROUNDED_ACCOUNTED_DR,
  APPLIED_TO_APPLICATION_ID,
  APPLIED_TO_ENTITY_CODE,
  APPLIED_TO_ENTITY_ID,
  APPLIED_TO_SOURCE_ID_NUM_1,
  APPLIED_TO_SOURCE_ID_NUM_2,
  APPLIED_TO_SOURCE_ID_NUM_3,
  APPLIED_TO_SOURCE_ID_NUM_4,
  APPLIED_TO_SOURCE_ID_CHAR_1,
  APPLIED_TO_SOURCE_ID_CHAR_2,
  APPLIED_TO_SOURCE_ID_CHAR_3,
  APPLIED_TO_SOURCE_ID_CHAR_4,
  APPLIED_TO_DISTRIBUTION_TYPE,
  APPLIED_TO_DIST_ID_NUM_1,
  APPLIED_TO_DIST_ID_NUM_2,
  APPLIED_TO_DIST_ID_NUM_3,
  APPLIED_TO_DIST_ID_NUM_4,
  APPLIED_TO_DIST_ID_NUM_5,
  APPLIED_TO_DIST_ID_CHAR_1,
  APPLIED_TO_DIST_ID_CHAR_2,
  APPLIED_TO_DIST_ID_CHAR_3,
  APPLIED_TO_DIST_ID_CHAR_4,
  APPLIED_TO_DIST_ID_CHAR_5,
  ALLOC_TO_APPLICATION_ID,
  ALLOC_TO_ENTITY_CODE,
  ALLOC_TO_SOURCE_ID_NUM_1,
  ALLOC_TO_SOURCE_ID_NUM_2,
  ALLOC_TO_SOURCE_ID_NUM_3,
  ALLOC_TO_SOURCE_ID_NUM_4,
  ALLOC_TO_SOURCE_ID_CHAR_1,
  ALLOC_TO_SOURCE_ID_CHAR_2,
  ALLOC_TO_SOURCE_ID_CHAR_3,
  ALLOC_TO_SOURCE_ID_CHAR_4,
  ALLOC_TO_DISTRIBUTION_TYPE,
  ALLOC_TO_DIST_ID_NUM_1,
  ALLOC_TO_DIST_ID_NUM_2,
  ALLOC_TO_DIST_ID_NUM_3,
  ALLOC_TO_DIST_ID_NUM_4,
  ALLOC_TO_DIST_ID_NUM_5,
  ALLOC_TO_DIST_ID_CHAR_1,
  ALLOC_TO_DIST_ID_CHAR_2,
  ALLOC_TO_DIST_ID_CHAR_3,
  ALLOC_TO_DIST_ID_CHAR_4,
  ALLOC_TO_DIST_ID_CHAR_5,
  GAIN_OR_LOSS_REF,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  kca_seq_date
)
(
  SELECT
    APPLICATION_ID,
    EVENT_ID,
    AE_HEADER_ID,
    AE_LINE_NUM,
    SOURCE_DISTRIBUTION_TYPE,
    SOURCE_DISTRIBUTION_ID_CHAR_1,
    SOURCE_DISTRIBUTION_ID_CHAR_2,
    SOURCE_DISTRIBUTION_ID_CHAR_3,
    SOURCE_DISTRIBUTION_ID_CHAR_4,
    SOURCE_DISTRIBUTION_ID_CHAR_5,
    SOURCE_DISTRIBUTION_ID_NUM_1,
    SOURCE_DISTRIBUTION_ID_NUM_2,
    SOURCE_DISTRIBUTION_ID_NUM_3,
    SOURCE_DISTRIBUTION_ID_NUM_4,
    SOURCE_DISTRIBUTION_ID_NUM_5,
    TAX_LINE_REF_ID,
    TAX_SUMMARY_LINE_REF_ID,
    TAX_REC_NREC_DIST_REF_ID,
    STATISTICAL_AMOUNT,
    REF_AE_HEADER_ID,
    REF_TEMP_LINE_NUM,
    ACCOUNTING_LINE_CODE,
    ACCOUNTING_LINE_TYPE_CODE,
    MERGE_DUPLICATE_CODE,
    TEMP_LINE_NUM,
    REF_EVENT_ID,
    LINE_DEFINITION_OWNER_CODE,
    LINE_DEFINITION_CODE,
    EVENT_CLASS_CODE,
    EVENT_TYPE_CODE,
    UPG_BATCH_ID,
    CALCULATE_ACCTD_AMTS_FLAG,
    CALCULATE_G_L_AMTS_FLAG,
    ROUNDING_CLASS_CODE,
    DOCUMENT_ROUNDING_LEVEL,
    UNROUNDED_ENTERED_DR,
    UNROUNDED_ENTERED_CR,
    DOC_ROUNDING_ENTERED_AMT,
    DOC_ROUNDING_ACCTD_AMT,
    UNROUNDED_ACCOUNTED_CR,
    UNROUNDED_ACCOUNTED_DR,
    APPLIED_TO_APPLICATION_ID,
    APPLIED_TO_ENTITY_CODE,
    APPLIED_TO_ENTITY_ID,
    APPLIED_TO_SOURCE_ID_NUM_1,
    APPLIED_TO_SOURCE_ID_NUM_2,
    APPLIED_TO_SOURCE_ID_NUM_3,
    APPLIED_TO_SOURCE_ID_NUM_4,
    APPLIED_TO_SOURCE_ID_CHAR_1,
    APPLIED_TO_SOURCE_ID_CHAR_2,
    APPLIED_TO_SOURCE_ID_CHAR_3,
    APPLIED_TO_SOURCE_ID_CHAR_4,
    APPLIED_TO_DISTRIBUTION_TYPE,
    APPLIED_TO_DIST_ID_NUM_1,
    APPLIED_TO_DIST_ID_NUM_2,
    APPLIED_TO_DIST_ID_NUM_3,
    APPLIED_TO_DIST_ID_NUM_4,
    APPLIED_TO_DIST_ID_NUM_5,
    APPLIED_TO_DIST_ID_CHAR_1,
    APPLIED_TO_DIST_ID_CHAR_2,
    APPLIED_TO_DIST_ID_CHAR_3,
    APPLIED_TO_DIST_ID_CHAR_4,
    APPLIED_TO_DIST_ID_CHAR_5,
    ALLOC_TO_APPLICATION_ID,
    ALLOC_TO_ENTITY_CODE,
    ALLOC_TO_SOURCE_ID_NUM_1,
    ALLOC_TO_SOURCE_ID_NUM_2,
    ALLOC_TO_SOURCE_ID_NUM_3,
    ALLOC_TO_SOURCE_ID_NUM_4,
    ALLOC_TO_SOURCE_ID_CHAR_1,
    ALLOC_TO_SOURCE_ID_CHAR_2,
    ALLOC_TO_SOURCE_ID_CHAR_3,
    ALLOC_TO_SOURCE_ID_CHAR_4,
    ALLOC_TO_DISTRIBUTION_TYPE,
    ALLOC_TO_DIST_ID_NUM_1,
    ALLOC_TO_DIST_ID_NUM_2,
    ALLOC_TO_DIST_ID_NUM_3,
    ALLOC_TO_DIST_ID_NUM_4,
    ALLOC_TO_DIST_ID_NUM_5,
    ALLOC_TO_DIST_ID_CHAR_1,
    ALLOC_TO_DIST_ID_CHAR_2,
    ALLOC_TO_DIST_ID_CHAR_3,
    ALLOC_TO_DIST_ID_CHAR_4,
    ALLOC_TO_DIST_ID_CHAR_5,
    GAIN_OR_LOSS_REF,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.XLA_DISTRIBUTION_LINKS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(APPLICATION_ID, 0), COALESCE(REF_AE_HEADER_ID, 0), COALESCE(TEMP_LINE_NUM, 0), COALESCE(AE_HEADER_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(APPLICATION_ID, 0),
        COALESCE(REF_AE_HEADER_ID, 0),
        COALESCE(TEMP_LINE_NUM, 0),
        COALESCE(AE_HEADER_ID, 0),
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.XLA_DISTRIBUTION_LINKS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(APPLICATION_ID, 0),
        COALESCE(REF_AE_HEADER_ID, 0),
        COALESCE(TEMP_LINE_NUM, 0),
        COALESCE(AE_HEADER_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.XLA_DISTRIBUTION_LINKS SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(APPLICATION_ID, 0), COALESCE(REF_AE_HEADER_ID, 0), COALESCE(TEMP_LINE_NUM, 0), COALESCE(AE_HEADER_ID, 0)) IN (
    SELECT
      COALESCE(ext.APPLICATION_ID, 0),
      COALESCE(ext.REF_AE_HEADER_ID, 0),
      COALESCE(ext.TEMP_LINE_NUM, 0),
      COALESCE(ext.AE_HEADER_ID, 0)
    FROM silver_bec_ods.XLA_DISTRIBUTION_LINKS AS ods, bec_raw_dl_ext.XLA_DISTRIBUTION_LINKS AS ext
    WHERE
      COALESCE(ods.APPLICATION_ID, 0) = COALESCE(ext.APPLICATION_ID, 0)
      AND COALESCE(ods.REF_AE_HEADER_ID, 0) = COALESCE(ext.REF_AE_HEADER_ID, 0)
      AND COALESCE(ods.TEMP_LINE_NUM, 0) = COALESCE(ext.TEMP_LINE_NUM, 0)
      AND COALESCE(ods.AE_HEADER_ID, 0) = COALESCE(ext.AE_HEADER_ID, 0)
      AND ext.kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP(), load_type = 'I'
WHERE
  ods_table_name = 'xla_distribution_links';