/* Delete Records */
DELETE FROM silver_bec_ods.MTL_PLANNERS
WHERE
  (COALESCE(ORGANIZATION_ID, 0), COALESCE(PLANNER_CODE, 'NA')) IN (
    SELECT
      COALESCE(stg.ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
      COALESCE(stg.PLANNER_CODE, 'NA') AS PLANNER_CODE
    FROM silver_bec_ods.MTL_PLANNERS AS ods, bronze_bec_ods_stg.MTL_PLANNERS AS stg
    WHERE
      COALESCE(ods.ORGANIZATION_ID, 0) = COALESCE(stg.ORGANIZATION_ID, 0)
      AND COALESCE(ods.PLANNER_CODE, 'NA') = COALESCE(stg.PLANNER_CODE, 'NA')
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.MTL_PLANNERS (
  PLANNER_CODE,
  ORGANIZATION_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  DESCRIPTION,
  DISABLE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ELECTRONIC_MAIL_ADDRESS,
  EMPLOYEE_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_ID,
  kca_seq_date
)
(
  SELECT
    PLANNER_CODE,
    ORGANIZATION_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    DESCRIPTION,
    DISABLE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ELECTRONIC_MAIL_ADDRESS,
    EMPLOYEE_ID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MTL_PLANNERS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(ORGANIZATION_ID, 0), COALESCE(PLANNER_CODE, 'NA'), kca_seq_ID) IN (
      SELECT
        COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
        COALESCE(PLANNER_CODE, 'NA') AS PLANNER_CODE,
        MAX(kca_seq_ID) AS kca_seq_ID
      FROM bronze_bec_ods_stg.MTL_PLANNERS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(ORGANIZATION_ID, 0),
        COALESCE(PLANNER_CODE, 'NA')
    )
);
/* Soft delete */
UPDATE silver_bec_ods.MTL_PLANNERS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.MTL_PLANNERS SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(ORGANIZATION_ID, 0), COALESCE(PLANNER_CODE, 'NA')) IN (
    SELECT
      COALESCE(ORGANIZATION_ID, 0),
      COALESCE(PLANNER_CODE, 'NA')
    FROM bec_raw_dl_ext.MTL_PLANNERS
    WHERE
      (COALESCE(ORGANIZATION_ID, 0), COALESCE(PLANNER_CODE, 'NA'), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(ORGANIZATION_ID, 0),
          COALESCE(PLANNER_CODE, 'NA'),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.MTL_PLANNERS
        GROUP BY
          COALESCE(ORGANIZATION_ID, 0),
          COALESCE(PLANNER_CODE, 'NA')
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_planners';