/* Delete Records   */
DELETE FROM silver_bec_ods.MSC_CALENDAR_DATES
WHERE
  (SR_INSTANCE_ID, CALENDAR_DATE, CALENDAR_CODE, EXCEPTION_SET_ID) IN (
    SELECT
      stg.SR_INSTANCE_ID,
      stg.CALENDAR_DATE,
      stg.CALENDAR_CODE,
      stg.EXCEPTION_SET_ID
    FROM silver_bec_ods.MSC_CALENDAR_DATES AS ods, bronze_bec_ods_stg.MSC_CALENDAR_DATES AS stg
    WHERE
      ods.SR_INSTANCE_ID = stg.SR_INSTANCE_ID
      AND ods.CALENDAR_DATE = stg.CALENDAR_DATE
      AND ods.CALENDAR_CODE = stg.CALENDAR_CODE
      AND ods.EXCEPTION_SET_ID = stg.EXCEPTION_SET_ID
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.MSC_CALENDAR_DATES (
  CALENDAR_DATE,
  CALENDAR_CODE,
  SEQ_NUM,
  NEXT_SEQ_NUM,
  PRIOR_SEQ_NUM,
  NEXT_DATE,
  PRIOR_DATE,
  CALENDAR_START_DATE,
  CALENDAR_END_DATE,
  DESCRIPTION,
  EXCEPTION_SET_ID,
  SR_INSTANCE_ID,
  REFRESH_NUMBER,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  DELETED_FLAG,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    CALENDAR_DATE,
    CALENDAR_CODE,
    SEQ_NUM,
    NEXT_SEQ_NUM,
    PRIOR_SEQ_NUM,
    NEXT_DATE,
    PRIOR_DATE,
    CALENDAR_START_DATE,
    CALENDAR_END_DATE,
    DESCRIPTION,
    EXCEPTION_SET_ID,
    SR_INSTANCE_ID,
    REFRESH_NUMBER,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    DELETED_FLAG,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MSC_CALENDAR_DATES
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (SR_INSTANCE_ID, CALENDAR_DATE, CALENDAR_CODE, EXCEPTION_SET_ID, KCA_SEQ_ID) IN (
      SELECT
        SR_INSTANCE_ID,
        CALENDAR_DATE,
        CALENDAR_CODE,
        EXCEPTION_SET_ID,
        MAX(KCA_SEQ_ID)
      FROM bronze_bec_ods_stg.MSC_CALENDAR_DATES
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        SR_INSTANCE_ID,
        CALENDAR_DATE,
        CALENDAR_CODE,
        EXCEPTION_SET_ID
    )
);
/* Soft delete */
UPDATE silver_bec_ods.MSC_CALENDAR_DATES SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.MSC_CALENDAR_DATES SET IS_DELETED_FLG = 'Y'
WHERE
  (SR_INSTANCE_ID, CALENDAR_DATE, CALENDAR_CODE, EXCEPTION_SET_ID) IN (
    SELECT
      SR_INSTANCE_ID,
      CALENDAR_DATE,
      CALENDAR_CODE,
      EXCEPTION_SET_ID
    FROM bec_raw_dl_ext.MSC_CALENDAR_DATES
    WHERE
      (SR_INSTANCE_ID, CALENDAR_DATE, CALENDAR_CODE, EXCEPTION_SET_ID, KCA_SEQ_ID) IN (
        SELECT
          SR_INSTANCE_ID,
          CALENDAR_DATE,
          CALENDAR_CODE,
          EXCEPTION_SET_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.MSC_CALENDAR_DATES
        GROUP BY
          SR_INSTANCE_ID,
          CALENDAR_DATE,
          CALENDAR_CODE,
          EXCEPTION_SET_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'msc_calendar_dates';