/* Delete Records */
DELETE FROM silver_bec_ods.MRP_SR_RECEIPT_ORG
WHERE
  COALESCE(SR_RECEIPT_ID, 0) IN (
    SELECT
      COALESCE(stg.SR_RECEIPT_ID, 0) AS SR_RECEIPT_ID
    FROM silver_bec_ods.MRP_SR_RECEIPT_ORG AS ods, bronze_bec_ods_stg.MRP_SR_RECEIPT_ORG AS stg
    WHERE
      ods.SR_RECEIPT_ID = stg.SR_RECEIPT_ID AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.MRP_SR_RECEIPT_ORG (
  SR_RECEIPT_ID,
  SOURCING_RULE_ID,
  RECEIPT_ORGANIZATION_ID,
  EFFECTIVE_DATE,
  DISABLE_DATE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  kca_seq_date
)
(
  SELECT
    SR_RECEIPT_ID,
    SOURCING_RULE_ID,
    RECEIPT_ORGANIZATION_ID,
    EFFECTIVE_DATE,
    DISABLE_DATE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    LAST_UPDATE_LOGIN,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.MRP_SR_RECEIPT_ORG
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(SR_RECEIPT_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(SR_RECEIPT_ID, 0) AS SR_RECEIPT_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.MRP_SR_RECEIPT_ORG
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(SR_RECEIPT_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.MRP_SR_RECEIPT_ORG SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.MRP_SR_RECEIPT_ORG SET IS_DELETED_FLG = 'Y'
WHERE
  (
    SR_RECEIPT_ID
  ) IN (
    SELECT
      SR_RECEIPT_ID
    FROM bec_raw_dl_ext.MRP_SR_RECEIPT_ORG
    WHERE
      (SR_RECEIPT_ID, KCA_SEQ_ID) IN (
        SELECT
          SR_RECEIPT_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.MRP_SR_RECEIPT_ORG
        GROUP BY
          SR_RECEIPT_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mrp_sr_receipt_org';