/* Delete Records */
DELETE FROM silver_bec_ods.PA_PROJECT_ACCUM_HEADERS
WHERE
  (
    COALESCE(PROJECT_ACCUM_ID, 0)
  ) IN (
    SELECT
      COALESCE(stg.PROJECT_ACCUM_ID, 0) AS PROJECT_ACCUM_ID
    FROM silver_bec_ods.PA_PROJECT_ACCUM_HEADERS AS ods, bronze_bec_ods_stg.PA_PROJECT_ACCUM_HEADERS AS stg
    WHERE
      COALESCE(ods.PROJECT_ACCUM_ID, 0) = COALESCE(stg.PROJECT_ACCUM_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.PA_PROJECT_ACCUM_HEADERS (
  PROJECT_ACCUM_ID,
  PROJECT_ID,
  TASK_ID,
  ACCUM_PERIOD,
  RESOURCE_ID,
  RESOURCE_LIST_ASSIGNMENT_ID,
  RESOURCE_LIST_ID,
  RESOURCE_LIST_MEMBER_ID,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  TASKS_RESTRUCTURED_FLAG,
  SUM_EXCEPTION_CODE,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    PROJECT_ACCUM_ID,
    PROJECT_ID,
    TASK_ID,
    ACCUM_PERIOD,
    RESOURCE_ID,
    RESOURCE_LIST_ASSIGNMENT_ID,
    RESOURCE_LIST_ID,
    RESOURCE_LIST_MEMBER_ID,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    TASKS_RESTRUCTURED_FLAG,
    SUM_EXCEPTION_CODE,
    kca_operation,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.PA_PROJECT_ACCUM_HEADERS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(PROJECT_ACCUM_ID, 0), KCA_SEQ_ID) IN (
      SELECT
        COALESCE(PROJECT_ACCUM_ID, 0) AS PROJECT_ACCUM_ID,
        MAX(KCA_SEQ_ID)
      FROM bronze_bec_ods_stg.PA_PROJECT_ACCUM_HEADERS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(PROJECT_ACCUM_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.PA_PROJECT_ACCUM_HEADERS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.PA_PROJECT_ACCUM_HEADERS SET IS_DELETED_FLG = 'Y'
WHERE
  (
    PROJECT_ACCUM_ID
  ) IN (
    SELECT
      PROJECT_ACCUM_ID
    FROM bec_raw_dl_ext.PA_PROJECT_ACCUM_HEADERS
    WHERE
      (PROJECT_ACCUM_ID, KCA_SEQ_ID) IN (
        SELECT
          PROJECT_ACCUM_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.PA_PROJECT_ACCUM_HEADERS
        GROUP BY
          PROJECT_ACCUM_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'pa_project_accum_headers';