/* Delete Records */
DELETE FROM silver_bec_ods.mtl_category_sets_b
WHERE
  CATEGORY_SET_ID IN (
    SELECT
      stg.CATEGORY_SET_ID
    FROM silver_bec_ods.mtl_category_sets_b AS ods, bronze_bec_ods_stg.mtl_category_sets_b AS stg
    WHERE
      ods.CATEGORY_SET_ID = stg.CATEGORY_SET_ID
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.MTL_CATEGORY_SETS_B (
  CATEGORY_SET_ID,
  STRUCTURE_ID,
  VALIDATE_FLAG,
  CONTROL_LEVEL,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  DEFAULT_CATEGORY_ID,
  MULT_ITEM_CAT_ASSIGN_FLAG,
  CONTROL_LEVEL_UPDATEABLE_FLAG,
  MULT_ITEM_CAT_UPDATEABLE_FLAG,
  HIERARCHY_ENABLED,
  VALIDATE_FLAG_UPDATEABLE_FLAG,
  USER_CREATION_ALLOWED_FLAG,
  RAISE_ITEM_CAT_ASSIGN_EVENT,
  RAISE_ALT_CAT_HIER_CHG_EVENT,
  RAISE_CATALOG_CAT_CHG_EVENT,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
SELECT
  CATEGORY_SET_ID,
  STRUCTURE_ID,
  VALIDATE_FLAG,
  CONTROL_LEVEL,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  DEFAULT_CATEGORY_ID,
  MULT_ITEM_CAT_ASSIGN_FLAG,
  CONTROL_LEVEL_UPDATEABLE_FLAG,
  MULT_ITEM_CAT_UPDATEABLE_FLAG,
  HIERARCHY_ENABLED,
  VALIDATE_FLAG_UPDATEABLE_FLAG,
  USER_CREATION_ALLOWED_FLAG,
  RAISE_ITEM_CAT_ASSIGN_EVENT,
  RAISE_ALT_CAT_HIER_CHG_EVENT,
  RAISE_CATALOG_CAT_CHG_EVENT,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.mtl_category_sets_b
WHERE
  kca_operation IN ('INSERT', 'UPDATE')
  AND (CATEGORY_SET_ID, kca_seq_id) IN (
    SELECT
      CATEGORY_SET_ID,
      MAX(kca_seq_id)
    FROM bronze_bec_ods_stg.mtl_category_sets_b
    WHERE
      kca_operation IN ('INSERT', 'UPDATE')
    GROUP BY
      CATEGORY_SET_ID
  );
/* Soft delete */
UPDATE silver_bec_ods.mtl_category_sets_b SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.mtl_category_sets_b SET IS_DELETED_FLG = 'Y'
WHERE
  (
    CATEGORY_SET_ID
  ) IN (
    SELECT
      CATEGORY_SET_ID
    FROM bec_raw_dl_ext.mtl_category_sets_b
    WHERE
      (CATEGORY_SET_ID, KCA_SEQ_ID) IN (
        SELECT
          CATEGORY_SET_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.mtl_category_sets_b
        GROUP BY
          CATEGORY_SET_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_category_sets_b';