/* Delete Records */
DELETE FROM silver_bec_ods.MTL_SAFETY_STOCKS
WHERE
  (COALESCE(INVENTORY_ITEM_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00')) IN (
    SELECT
      COALESCE(stg.INVENTORY_ITEM_ID, 0) AS INVENTORY_ITEM_ID,
      COALESCE(stg.ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
      COALESCE(stg.EFFECTIVITY_DATE, '1900-01-01 12:00:00') AS EFFECTIVITY_DATE
    FROM silver_bec_ods.MTL_SAFETY_STOCKS AS ods, bronze_bec_ods_stg.MTL_SAFETY_STOCKS AS stg
    WHERE
      COALESCE(ods.INVENTORY_ITEM_ID, 0) = COALESCE(stg.INVENTORY_ITEM_ID, 0)
      AND COALESCE(ods.ORGANIZATION_ID, 0) = COALESCE(stg.ORGANIZATION_ID, 0)
      AND COALESCE(ods.EFFECTIVITY_DATE, '1900-01-01 12:00:00') = COALESCE(stg.EFFECTIVITY_DATE, '1900-01-01 12:00:00')
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.MTL_SAFETY_STOCKS (
  INVENTORY_ITEM_ID,
  ORGANIZATION_ID,
  EFFECTIVITY_DATE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  SAFETY_STOCK_CODE,
  SAFETY_STOCK_QUANTITY,
  SAFETY_STOCK_PERCENT,
  SERVICE_LEVEL,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  FORECAST_DESIGNATOR,
  PROJECT_ID,
  TASK_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_ID,
  kca_seq_date
)
(
  SELECT
    INVENTORY_ITEM_ID,
    ORGANIZATION_ID,
    EFFECTIVITY_DATE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    SAFETY_STOCK_CODE,
    SAFETY_STOCK_QUANTITY,
    SAFETY_STOCK_PERCENT,
    SERVICE_LEVEL,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    FORECAST_DESIGNATOR,
    PROJECT_ID,
    TASK_ID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.MTL_SAFETY_STOCKS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(INVENTORY_ITEM_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00'), kca_seq_ID) IN (
      SELECT
        COALESCE(INVENTORY_ITEM_ID, 0) AS INVENTORY_ITEM_ID,
        COALESCE(ORGANIZATION_ID, 0) AS ORGANIZATION_ID,
        COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00') AS EFFECTIVITY_DATE,
        MAX(kca_seq_ID) AS kca_seq_ID
      FROM bronze_bec_ods_stg.MTL_SAFETY_STOCKS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(INVENTORY_ITEM_ID, 0),
        COALESCE(ORGANIZATION_ID, 0),
        COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00')
    )
);
/* Soft delete */
UPDATE silver_bec_ods.MTL_SAFETY_STOCKS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.MTL_SAFETY_STOCKS SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(INVENTORY_ITEM_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00')) IN (
    SELECT
      COALESCE(INVENTORY_ITEM_ID, 0),
      COALESCE(ORGANIZATION_ID, 0),
      COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00')
    FROM bec_raw_dl_ext.MTL_SAFETY_STOCKS
    WHERE
      (COALESCE(INVENTORY_ITEM_ID, 0), COALESCE(ORGANIZATION_ID, 0), COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00'), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(INVENTORY_ITEM_ID, 0),
          COALESCE(ORGANIZATION_ID, 0),
          COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00'),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.MTL_SAFETY_STOCKS
        GROUP BY
          COALESCE(INVENTORY_ITEM_ID, 0),
          COALESCE(ORGANIZATION_ID, 0),
          COALESCE(EFFECTIVITY_DATE, '1900-01-01 12:00:00')
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'mtl_safety_stocks';