/* Delete Records */
DELETE FROM silver_bec_ods.BOM_STANDARD_OPERATIONS
WHERE
  (COALESCE(LINE_ID, 0), COALESCE(OPERATION_TYPE, 0), COALESCE(STANDARD_OPERATION_ID, 0)) IN (
    SELECT
      COALESCE(stg.LINE_ID, 0) AS LINE_ID,
      COALESCE(stg.OPERATION_TYPE, 0) AS OPERATION_TYPE,
      COALESCE(stg.STANDARD_OPERATION_ID, 0) AS STANDARD_OPERATION_ID
    FROM silver_bec_ods.bom_standard_operations AS ods, bronze_bec_ods_stg.bom_standard_operations AS stg
    WHERE
      COALESCE(ods.LINE_ID, 0) = COALESCE(stg.LINE_ID, 0)
      AND COALESCE(ods.OPERATION_TYPE, 0) = COALESCE(stg.OPERATION_TYPE, 0)
      AND COALESCE(ods.STANDARD_OPERATION_ID, 0) = COALESCE(stg.STANDARD_OPERATION_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.bom_standard_operations (
  SEQUENCE_NUM,
  LINE_ID,
  OPERATION_TYPE,
  STANDARD_OPERATION_ID,
  OPERATION_CODE,
  ORGANIZATION_ID,
  DEPARTMENT_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  MINIMUM_TRANSFER_QUANTITY,
  COUNT_POINT_TYPE,
  OPERATION_DESCRIPTION,
  OPTION_DEPENDENT_FLAG,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  BACKFLUSH_FLAG,
  WMS_TASK_TYPE,
  INCLUDE_IN_ROLLUP,
  YIELD,
  OPERATION_YIELD_ENABLED,
  SHUTDOWN_TYPE,
  ACTUAL_IPK,
  CRITICAL_TO_QUALITY,
  VALUE_ADDED,
  DEFAULT_SUBINVENTORY,
  DEFAULT_LOCATOR_ID,
  LOWEST_ACCEPTABLE_YIELD,
  USE_ORG_SETTINGS,
  QUEUE_MANDATORY_FLAG,
  RUN_MANDATORY_FLAG,
  TO_MOVE_MANDATORY_FLAG,
  SHOW_NEXT_OP_BY_DEFAULT,
  SHOW_SCRAP_CODE,
  SHOW_LOT_ATTRIB,
  TRACK_MULTIPLE_RES_USAGE_DATES,
  CHECK_SKILL,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_ID,
  kca_seq_date
)
(
  SELECT
    SEQUENCE_NUM,
    LINE_ID,
    OPERATION_TYPE,
    STANDARD_OPERATION_ID,
    OPERATION_CODE,
    ORGANIZATION_ID,
    DEPARTMENT_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    MINIMUM_TRANSFER_QUANTITY,
    COUNT_POINT_TYPE,
    OPERATION_DESCRIPTION,
    OPTION_DEPENDENT_FLAG,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    BACKFLUSH_FLAG,
    WMS_TASK_TYPE,
    INCLUDE_IN_ROLLUP,
    YIELD,
    OPERATION_YIELD_ENABLED,
    SHUTDOWN_TYPE,
    ACTUAL_IPK,
    CRITICAL_TO_QUALITY,
    VALUE_ADDED,
    DEFAULT_SUBINVENTORY,
    DEFAULT_LOCATOR_ID,
    LOWEST_ACCEPTABLE_YIELD,
    USE_ORG_SETTINGS,
    QUEUE_MANDATORY_FLAG,
    RUN_MANDATORY_FLAG,
    TO_MOVE_MANDATORY_FLAG,
    SHOW_NEXT_OP_BY_DEFAULT,
    SHOW_SCRAP_CODE,
    SHOW_LOT_ATTRIB,
    TRACK_MULTIPLE_RES_USAGE_DATES,
    CHECK_SKILL,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.bom_standard_operations
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(LINE_ID, 0), COALESCE(OPERATION_TYPE, 0), COALESCE(STANDARD_OPERATION_ID, 0), kca_seq_ID) IN (
      SELECT
        COALESCE(LINE_ID, 0) AS LINE_ID,
        COALESCE(OPERATION_TYPE, 0) AS OPERATION_TYPE,
        COALESCE(STANDARD_OPERATION_ID, 0) AS STANDARD_OPERATION_ID,
        MAX(kca_seq_ID) AS kca_seq_ID
      FROM bronze_bec_ods_stg.bom_standard_operations
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(LINE_ID, 0),
        COALESCE(OPERATION_TYPE, 0),
        COALESCE(STANDARD_OPERATION_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.bom_standard_operations SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.bom_standard_operations SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(LINE_ID, 0), COALESCE(OPERATION_TYPE, 0), COALESCE(STANDARD_OPERATION_ID, 0)) IN (
    SELECT
      COALESCE(LINE_ID, 0),
      COALESCE(OPERATION_TYPE, 0),
      COALESCE(STANDARD_OPERATION_ID, 0)
    FROM bec_raw_dl_ext.bom_standard_operations
    WHERE
      (COALESCE(LINE_ID, 0), COALESCE(OPERATION_TYPE, 0), COALESCE(STANDARD_OPERATION_ID, 0), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(LINE_ID, 0),
          COALESCE(OPERATION_TYPE, 0),
          COALESCE(STANDARD_OPERATION_ID, 0),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.bom_standard_operations
        GROUP BY
          COALESCE(LINE_ID, 0),
          COALESCE(OPERATION_TYPE, 0),
          COALESCE(STANDARD_OPERATION_ID, 0)
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'bom_standard_operations';