/* Delete Records */
DELETE FROM silver_bec_ods.xle_entity_profiles
WHERE
  LEGAL_ENTITY_ID IN (
    SELECT
      stg.LEGAL_ENTITY_ID
    FROM silver_bec_ods.xle_entity_profiles AS ods, bronze_bec_ods_stg.xle_entity_profiles AS stg
    WHERE
      ods.LEGAL_ENTITY_ID = stg.LEGAL_ENTITY_ID
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.xle_entity_profiles (
  LEGAL_ENTITY_ID,
  PARTY_ID,
  LEGAL_ENTITY_IDENTIFIER,
  NAME,
  GEOGRAPHY_ID,
  TRANSACTING_ENTITY_FLAG,
  EFFECTIVE_FROM,
  EFFECTIVE_TO,
  LE_INFORMATION_CONTEXT,
  LE_INFORMATION1,
  LE_INFORMATION2,
  LE_INFORMATION3,
  LE_INFORMATION4,
  LE_INFORMATION5,
  LE_INFORMATION6,
  LE_INFORMATION7,
  LE_INFORMATION8,
  LE_INFORMATION9,
  LE_INFORMATION10,
  LE_INFORMATION11,
  LE_INFORMATION12,
  LE_INFORMATION13,
  LE_INFORMATION14,
  LE_INFORMATION15,
  LE_INFORMATION16,
  LE_INFORMATION17,
  LE_INFORMATION18,
  LE_INFORMATION19,
  LE_INFORMATION20,
  LAST_UPDATED_BY,
  CREATION_DATE,
  LAST_UPDATE_LOGIN,
  LAST_UPDATE_DATE,
  CREATED_BY,
  OBJECT_VERSION_NUMBER,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE16,
  ATTRIBUTE17,
  ATTRIBUTE18,
  ATTRIBUTE19,
  ATTRIBUTE20,
  ACTIVITY_CODE,
  SUB_ACTIVITY_CODE,
  TYPE_OF_COMPANY,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  KCA_SEQ_DATE
)
(
  SELECT
    LEGAL_ENTITY_ID,
    PARTY_ID,
    LEGAL_ENTITY_IDENTIFIER,
    NAME,
    GEOGRAPHY_ID,
    TRANSACTING_ENTITY_FLAG,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    LE_INFORMATION_CONTEXT,
    LE_INFORMATION1,
    LE_INFORMATION2,
    LE_INFORMATION3,
    LE_INFORMATION4,
    LE_INFORMATION5,
    LE_INFORMATION6,
    LE_INFORMATION7,
    LE_INFORMATION8,
    LE_INFORMATION9,
    LE_INFORMATION10,
    LE_INFORMATION11,
    LE_INFORMATION12,
    LE_INFORMATION13,
    LE_INFORMATION14,
    LE_INFORMATION15,
    LE_INFORMATION16,
    LE_INFORMATION17,
    LE_INFORMATION18,
    LE_INFORMATION19,
    LE_INFORMATION20,
    LAST_UPDATED_BY,
    CREATION_DATE,
    LAST_UPDATE_LOGIN,
    LAST_UPDATE_DATE,
    CREATED_BY,
    OBJECT_VERSION_NUMBER,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE16,
    ATTRIBUTE17,
    ATTRIBUTE18,
    ATTRIBUTE19,
    ATTRIBUTE20,
    ACTIVITY_CODE,
    SUB_ACTIVITY_CODE,
    TYPE_OF_COMPANY,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.xle_entity_profiles
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (LEGAL_ENTITY_ID, kca_seq_id) IN (
      SELECT
        LEGAL_ENTITY_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.xle_entity_profiles
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        LEGAL_ENTITY_ID
    )
);
/* Soft delete */
UPDATE silver_bec_ods.xle_entity_profiles SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.xle_entity_profiles SET IS_DELETED_FLG = 'Y'
WHERE
  (
    LEGAL_ENTITY_ID
  ) IN (
    SELECT
      LEGAL_ENTITY_ID
    FROM bec_raw_dl_ext.xle_entity_profiles
    WHERE
      (LEGAL_ENTITY_ID, KCA_SEQ_ID) IN (
        SELECT
          LEGAL_ENTITY_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.xle_entity_profiles
        GROUP BY
          LEGAL_ENTITY_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'xle_entity_profiles';