/* Delete Records */
DELETE FROM silver_bec_ods.OKC_K_LINES_B
WHERE
  (COALESCE(ID, 'NA'), COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0), COALESCE(CLE_ID, 'NA'), COALESCE(LINE_NUMBER, 'NA')) IN (
    SELECT
      COALESCE(stg.ID, 'NA') AS ID,
      COALESCE(CAST(stg.CHR_ID AS DECIMAL(15, 0)), 0) AS CHR_ID,
      COALESCE(stg.CLE_ID, 'NA') AS CLE_ID,
      COALESCE(stg.LINE_NUMBER, 'NA') AS LINE_NUMBER
    FROM silver_bec_ods.OKC_K_LINES_B AS ods, bronze_bec_ods_stg.OKC_K_LINES_B AS stg
    WHERE
      COALESCE(ods.ID, 'NA') = COALESCE(stg.ID, 'NA')
      AND COALESCE(ods.CHR_ID, 0) = COALESCE(CAST(stg.CHR_ID AS DECIMAL(15, 0)), 0)
      AND COALESCE(ods.CLE_ID, 'NA') = COALESCE(stg.CLE_ID, 'NA')
      AND COALESCE(ods.LINE_NUMBER, 'NA') = COALESCE(stg.LINE_NUMBER, 'NA')
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.OKC_K_LINES_B (
  ID,
  LINE_NUMBER,
  CHR_ID,
  CLE_ID,
  CLE_ID_RENEWED,
  DNZ_CHR_ID,
  DISPLAY_SEQUENCE,
  STS_CODE,
  TRN_CODE,
  LSE_ID,
  EXCEPTION_YN,
  OBJECT_VERSION_NUMBER,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  HIDDEN_IND,
  PRICE_NEGOTIATED,
  PRICE_LEVEL_IND,
  PRICE_UNIT,
  PRICE_UNIT_PERCENT,
  INVOICE_LINE_LEVEL_IND,
  DPAS_RATING,
  TEMPLATE_USED,
  PRICE_TYPE,
  CURRENCY_CODE,
  LAST_UPDATE_LOGIN,
  DATE_TERMINATED,
  START_DATE,
  END_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  SECURITY_GROUP_ID,
  CLE_ID_RENEWED_TO,
  PRICE_NEGOTIATED_RENEWED,
  CURRENCY_CODE_RENEWED,
  UPG_ORIG_SYSTEM_REF,
  UPG_ORIG_SYSTEM_REF_ID,
  DATE_RENEWED,
  ORIG_SYSTEM_SOURCE_CODE,
  ORIG_SYSTEM_ID1,
  ORIG_SYSTEM_REFERENCE1,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  REQUEST_ID,
  PRICE_LIST_ID,
  PRICE_LIST_LINE_ID,
  LINE_LIST_PRICE,
  ITEM_TO_PRICE_YN,
  PRICING_DATE,
  PRICE_BASIS_YN,
  CONFIG_HEADER_ID,
  CONFIG_REVISION_NUMBER,
  CONFIG_COMPLETE_YN,
  CONFIG_VALID_YN,
  CONFIG_TOP_MODEL_LINE_ID,
  CONFIG_ITEM_TYPE,
  CONFIG_ITEM_ID,
  SERVICE_ITEM_YN,
  PH_PRICING_TYPE,
  PH_PRICE_BREAK_BASIS,
  PH_MIN_QTY,
  PH_MIN_AMT,
  PH_QP_REFERENCE_ID,
  PH_VALUE,
  PH_ENFORCE_PRICE_LIST_YN,
  PH_ADJUSTMENT,
  PH_INTEGRATED_WITH_QP,
  CUST_ACCT_ID,
  BILL_TO_SITE_USE_ID,
  INV_RULE_ID,
  LINE_RENEWAL_TYPE_CODE,
  SHIP_TO_SITE_USE_ID,
  PAYMENT_TERM_ID,
  DATE_CANCELLED,
  TERM_CANCEL_SOURCE,
  PAYMENT_INSTRUCTION_TYPE,
  ANNUALIZED_FACTOR,
  CANCELLED_AMOUNT,
  GROUP_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    ID,
    LINE_NUMBER,
    CHR_ID,
    CLE_ID,
    CLE_ID_RENEWED,
    DNZ_CHR_ID,
    DISPLAY_SEQUENCE,
    STS_CODE,
    TRN_CODE,
    LSE_ID,
    EXCEPTION_YN,
    OBJECT_VERSION_NUMBER,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    HIDDEN_IND,
    PRICE_NEGOTIATED,
    PRICE_LEVEL_IND,
    PRICE_UNIT,
    PRICE_UNIT_PERCENT,
    INVOICE_LINE_LEVEL_IND,
    DPAS_RATING,
    TEMPLATE_USED,
    PRICE_TYPE,
    CURRENCY_CODE,
    LAST_UPDATE_LOGIN,
    DATE_TERMINATED,
    START_DATE,
    END_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    SECURITY_GROUP_ID,
    CLE_ID_RENEWED_TO,
    PRICE_NEGOTIATED_RENEWED,
    CURRENCY_CODE_RENEWED,
    UPG_ORIG_SYSTEM_REF,
    UPG_ORIG_SYSTEM_REF_ID,
    DATE_RENEWED,
    ORIG_SYSTEM_SOURCE_CODE,
    ORIG_SYSTEM_ID1,
    ORIG_SYSTEM_REFERENCE1,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    REQUEST_ID,
    PRICE_LIST_ID,
    PRICE_LIST_LINE_ID,
    LINE_LIST_PRICE,
    ITEM_TO_PRICE_YN,
    PRICING_DATE,
    PRICE_BASIS_YN,
    CONFIG_HEADER_ID,
    CONFIG_REVISION_NUMBER,
    CONFIG_COMPLETE_YN,
    CONFIG_VALID_YN,
    CONFIG_TOP_MODEL_LINE_ID,
    CONFIG_ITEM_TYPE,
    CONFIG_ITEM_ID,
    SERVICE_ITEM_YN,
    PH_PRICING_TYPE,
    PH_PRICE_BREAK_BASIS,
    PH_MIN_QTY,
    PH_MIN_AMT,
    PH_QP_REFERENCE_ID,
    PH_VALUE,
    PH_ENFORCE_PRICE_LIST_YN,
    PH_ADJUSTMENT,
    PH_INTEGRATED_WITH_QP,
    CUST_ACCT_ID,
    BILL_TO_SITE_USE_ID,
    INV_RULE_ID,
    LINE_RENEWAL_TYPE_CODE,
    SHIP_TO_SITE_USE_ID,
    PAYMENT_TERM_ID,
    DATE_CANCELLED,
    TERM_CANCEL_SOURCE,
    PAYMENT_INSTRUCTION_TYPE,
    ANNUALIZED_FACTOR,
    CANCELLED_AMOUNT,
    GROUP_ID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.OKC_K_LINES_B
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(ID, 'NA'), COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0), COALESCE(CLE_ID, 'NA'), COALESCE(LINE_NUMBER, 'NA'), kca_seq_id) IN (
      SELECT
        COALESCE(ID, 'NA') AS ID,
        COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0) AS CHR_ID,
        COALESCE(CLE_ID, 'NA') AS CLE_ID,
        COALESCE(LINE_NUMBER, 'NA') AS LINE_NUMBER,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.OKC_K_LINES_B
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(ID, 'NA'),
        COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0),
        COALESCE(CLE_ID, 'NA'),
        COALESCE(LINE_NUMBER, 'NA')
    )
);
/* Soft delete */
UPDATE silver_bec_ods.OKC_K_LINES_B SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.OKC_K_LINES_B SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(ID, 'NA'), COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0), COALESCE(CLE_ID, 'NA'), COALESCE(LINE_NUMBER, 'NA')) IN (
    SELECT
      COALESCE(ID, 'NA'),
      COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0),
      COALESCE(CLE_ID, 'NA'),
      COALESCE(LINE_NUMBER, 'NA')
    FROM bec_raw_dl_ext.OKC_K_LINES_B
    WHERE
      (COALESCE(ID, 'NA'), COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0), COALESCE(CLE_ID, 'NA'), COALESCE(LINE_NUMBER, 'NA'), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(ID, 'NA'),
          COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0),
          COALESCE(CLE_ID, 'NA'),
          COALESCE(LINE_NUMBER, 'NA'),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.OKC_K_LINES_B
        GROUP BY
          COALESCE(ID, 'NA'),
          COALESCE(CAST(CHR_ID AS DECIMAL(15, 0)), 0),
          COALESCE(CLE_ID, 'NA'),
          COALESCE(LINE_NUMBER, 'NA')
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'okc_k_lines_b';