/* Delete Records */
DELETE FROM silver_bec_ods.JTF_TASK_ASSIGNMENTS
WHERE
  (
    COALESCE(TASK_ASSIGNMENT_ID, 0)
  ) IN (
    SELECT
      COALESCE(stg.TASK_ASSIGNMENT_ID, 0) AS TASK_ASSIGNMENT_ID
    FROM silver_bec_ods.JTF_TASK_ASSIGNMENTS AS ods, bronze_bec_ods_stg.JTF_TASK_ASSIGNMENTS AS stg
    WHERE
      COALESCE(ods.TASK_ASSIGNMENT_ID, 0) = COALESCE(stg.TASK_ASSIGNMENT_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.JTF_TASK_ASSIGNMENTS (
  TASK_ASSIGNMENT_ID,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  OBJECT_VERSION_NUMBER,
  TASK_ID,
  RESOURCE_TYPE_CODE,
  RESOURCE_ID,
  ASSIGNMENT_STATUS_ID,
  ACTUAL_EFFORT,
  RESOURCE_TERRITORY_ID,
  ACTUAL_EFFORT_UOM,
  SCHEDULE_FLAG,
  ALARM_TYPE_CODE,
  ALARM_CONTACT,
  SHIFT_CONSTRUCT_ID,
  SCHED_TRAVEL_DISTANCE,
  SCHED_TRAVEL_DURATION,
  SCHED_TRAVEL_DURATION_UOM,
  ACTUAL_TRAVEL_DISTANCE,
  ACTUAL_TRAVEL_DURATION,
  ACTUAL_TRAVEL_DURATION_UOM,
  ACTUAL_START_DATE,
  ACTUAL_END_DATE,
  PALM_FLAG,
  WINCE_FLAG,
  LAPTOP_FLAG,
  DEVICE1_FLAG,
  DEVICE2_FLAG,
  DEVICE3_FLAG,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE_CATEGORY,
  SECURITY_GROUP_ID,
  ORIG_SYSTEM_REFERENCE,
  ORIG_SYSTEM_REFERENCE_ID,
  UPDATE_STATUS_FLAG,
  ASSIGNEE_ROLE,
  SHOW_ON_CALENDAR,
  CATEGORY_ID,
  REMINDER_WF_ITEM_TYPE,
  REMINDER_WF_ITEM_KEY,
  FREE_BUSY_TYPE,
  BOOKING_START_DATE,
  BOOKING_END_DATE,
  OBJECT_CAPACITY_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_ID,
  kca_seq_date
)
(
  SELECT
    TASK_ASSIGNMENT_ID,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    OBJECT_VERSION_NUMBER,
    TASK_ID,
    RESOURCE_TYPE_CODE,
    RESOURCE_ID,
    ASSIGNMENT_STATUS_ID,
    ACTUAL_EFFORT,
    RESOURCE_TERRITORY_ID,
    ACTUAL_EFFORT_UOM,
    SCHEDULE_FLAG,
    ALARM_TYPE_CODE,
    ALARM_CONTACT,
    SHIFT_CONSTRUCT_ID,
    SCHED_TRAVEL_DISTANCE,
    SCHED_TRAVEL_DURATION,
    SCHED_TRAVEL_DURATION_UOM,
    ACTUAL_TRAVEL_DISTANCE,
    ACTUAL_TRAVEL_DURATION,
    ACTUAL_TRAVEL_DURATION_UOM,
    ACTUAL_START_DATE,
    ACTUAL_END_DATE,
    PALM_FLAG,
    WINCE_FLAG,
    LAPTOP_FLAG,
    DEVICE1_FLAG,
    DEVICE2_FLAG,
    DEVICE3_FLAG,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE_CATEGORY,
    SECURITY_GROUP_ID,
    ORIG_SYSTEM_REFERENCE,
    ORIG_SYSTEM_REFERENCE_ID,
    UPDATE_STATUS_FLAG,
    ASSIGNEE_ROLE,
    SHOW_ON_CALENDAR,
    CATEGORY_ID,
    REMINDER_WF_ITEM_TYPE,
    REMINDER_WF_ITEM_KEY,
    FREE_BUSY_TYPE,
    BOOKING_START_DATE,
    BOOKING_END_DATE,
    OBJECT_CAPACITY_ID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.JTF_TASK_ASSIGNMENTS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(TASK_ASSIGNMENT_ID, 0), kca_seq_ID) IN (
      SELECT
        COALESCE(TASK_ASSIGNMENT_ID, 0) AS TASK_ASSIGNMENT_ID,
        MAX(kca_seq_ID) AS kca_seq_ID
      FROM bronze_bec_ods_stg.JTF_TASK_ASSIGNMENTS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(TASK_ASSIGNMENT_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.JTF_TASK_ASSIGNMENTS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.JTF_TASK_ASSIGNMENTS SET IS_DELETED_FLG = 'Y'
WHERE
  (
    TASK_ASSIGNMENT_ID
  ) IN (
    SELECT
      TASK_ASSIGNMENT_ID
    FROM bec_raw_dl_ext.JTF_TASK_ASSIGNMENTS
    WHERE
      (TASK_ASSIGNMENT_ID, KCA_SEQ_ID) IN (
        SELECT
          TASK_ASSIGNMENT_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.JTF_TASK_ASSIGNMENTS
        GROUP BY
          TASK_ASSIGNMENT_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'jtf_task_assignments';