/* Delete Records */
DELETE FROM silver_bec_ods.fa_category_books
WHERE
  (COALESCE(CATEGORY_ID, 0), COALESCE(BOOK_TYPE_CODE, 'NA')) IN (
    SELECT
      COALESCE(stg.CATEGORY_ID, 0) AS CATEGORY_ID,
      COALESCE(stg.BOOK_TYPE_CODE, 'NA') AS BOOK_TYPE_CODE
    FROM silver_bec_ods.fa_category_books AS ods, bronze_bec_ods_stg.fa_category_books AS stg
    WHERE
      COALESCE(ods.CATEGORY_ID, 0) = COALESCE(stg.CATEGORY_ID, 0)
      AND COALESCE(ods.BOOK_TYPE_CODE, 'NA') = COALESCE(stg.BOOK_TYPE_CODE, 'NA')
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.fa_category_books (
  CATEGORY_ID,
  BOOK_TYPE_CODE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATE_LOGIN,
  ASSET_CLEARING_ACCT,
  ASSET_COST_ACCT,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE_CATEGORY_CODE,
  CIP_CLEARING_ACCT,
  CIP_COST_ACCT,
  DEPRN_EXPENSE_ACCT,
  DEPRN_RESERVE_ACCT,
  REVAL_AMORTIZATION_ACCT,
  REVAL_RESERVE_ACCT,
  ASSET_COST_ACCOUNT_CCID,
  ASSET_CLEARING_ACCOUNT_CCID,
  WIP_COST_ACCOUNT_CCID,
  WIP_CLEARING_ACCOUNT_CCID,
  RESERVE_ACCOUNT_CCID,
  REVAL_AMORT_ACCOUNT_CCID,
  REVAL_RESERVE_ACCOUNT_CCID,
  LIFE_EXTENSION_CEILING,
  LIFE_EXTENSION_FACTOR,
  PERCENT_SALVAGE_VALUE,
  GLOBAL_ATTRIBUTE1,
  GLOBAL_ATTRIBUTE2,
  GLOBAL_ATTRIBUTE3,
  GLOBAL_ATTRIBUTE4,
  GLOBAL_ATTRIBUTE5,
  GLOBAL_ATTRIBUTE6,
  GLOBAL_ATTRIBUTE7,
  GLOBAL_ATTRIBUTE8,
  GLOBAL_ATTRIBUTE9,
  GLOBAL_ATTRIBUTE10,
  GLOBAL_ATTRIBUTE11,
  GLOBAL_ATTRIBUTE12,
  GLOBAL_ATTRIBUTE13,
  GLOBAL_ATTRIBUTE14,
  GLOBAL_ATTRIBUTE15,
  GLOBAL_ATTRIBUTE16,
  GLOBAL_ATTRIBUTE17,
  GLOBAL_ATTRIBUTE18,
  GLOBAL_ATTRIBUTE19,
  GLOBAL_ATTRIBUTE20,
  GLOBAL_ATTRIBUTE_CATEGORY,
  DEFAULT_GROUP_ASSET_ID,
  BONUS_DEPRN_EXPENSE_ACCT,
  BONUS_DEPRN_RESERVE_ACCT,
  BONUS_RESERVE_ACCT_CCID,
  UNPLAN_EXPENSE_ACCOUNT_CCID,
  UNPLAN_EXPENSE_ACCT,
  DEPRN_EXPENSE_ACCOUNT_CCID,
  BONUS_EXPENSE_ACCOUNT_CCID,
  ALT_COST_ACCOUNT_CCID,
  ALT_COST_ACCT,
  WRITE_OFF_ACCOUNT_CCID,
  WRITE_OFF_ACCT,
  IMPAIR_EXPENSE_ACCOUNT_CCID,
  IMPAIR_EXPENSE_ACCT,
  IMPAIR_RESERVE_ACCOUNT_CCID,
  IMPAIR_RESERVE_ACCT,
  CAPITAL_ADJ_ACCT,
  CAPITAL_ADJ_ACCOUNT_CCID,
  GENERAL_FUND_ACCT,
  GENERAL_FUND_ACCOUNT_CCID,
  REVAL_LOSS_ACCT,
  REVAL_LOSS_ACCOUNT_CCID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    CATEGORY_ID,
    BOOK_TYPE_CODE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATE_LOGIN,
    ASSET_CLEARING_ACCT,
    ASSET_COST_ACCT,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    ATTRIBUTE_CATEGORY_CODE,
    CIP_CLEARING_ACCT,
    CIP_COST_ACCT,
    DEPRN_EXPENSE_ACCT,
    DEPRN_RESERVE_ACCT,
    REVAL_AMORTIZATION_ACCT,
    REVAL_RESERVE_ACCT,
    ASSET_COST_ACCOUNT_CCID,
    ASSET_CLEARING_ACCOUNT_CCID,
    WIP_COST_ACCOUNT_CCID,
    WIP_CLEARING_ACCOUNT_CCID,
    RESERVE_ACCOUNT_CCID,
    REVAL_AMORT_ACCOUNT_CCID,
    REVAL_RESERVE_ACCOUNT_CCID,
    LIFE_EXTENSION_CEILING,
    LIFE_EXTENSION_FACTOR,
    PERCENT_SALVAGE_VALUE,
    GLOBAL_ATTRIBUTE1,
    GLOBAL_ATTRIBUTE2,
    GLOBAL_ATTRIBUTE3,
    GLOBAL_ATTRIBUTE4,
    GLOBAL_ATTRIBUTE5,
    GLOBAL_ATTRIBUTE6,
    GLOBAL_ATTRIBUTE7,
    GLOBAL_ATTRIBUTE8,
    GLOBAL_ATTRIBUTE9,
    GLOBAL_ATTRIBUTE10,
    GLOBAL_ATTRIBUTE11,
    GLOBAL_ATTRIBUTE12,
    GLOBAL_ATTRIBUTE13,
    GLOBAL_ATTRIBUTE14,
    GLOBAL_ATTRIBUTE15,
    GLOBAL_ATTRIBUTE16,
    GLOBAL_ATTRIBUTE17,
    GLOBAL_ATTRIBUTE18,
    GLOBAL_ATTRIBUTE19,
    GLOBAL_ATTRIBUTE20,
    GLOBAL_ATTRIBUTE_CATEGORY,
    DEFAULT_GROUP_ASSET_ID,
    BONUS_DEPRN_EXPENSE_ACCT,
    BONUS_DEPRN_RESERVE_ACCT,
    BONUS_RESERVE_ACCT_CCID,
    UNPLAN_EXPENSE_ACCOUNT_CCID,
    UNPLAN_EXPENSE_ACCT,
    DEPRN_EXPENSE_ACCOUNT_CCID,
    BONUS_EXPENSE_ACCOUNT_CCID,
    ALT_COST_ACCOUNT_CCID,
    ALT_COST_ACCT,
    WRITE_OFF_ACCOUNT_CCID,
    WRITE_OFF_ACCT,
    IMPAIR_EXPENSE_ACCOUNT_CCID,
    IMPAIR_EXPENSE_ACCT,
    IMPAIR_RESERVE_ACCOUNT_CCID,
    IMPAIR_RESERVE_ACCT,
    CAPITAL_ADJ_ACCT,
    CAPITAL_ADJ_ACCOUNT_CCID,
    GENERAL_FUND_ACCT,
    GENERAL_FUND_ACCOUNT_CCID,
    REVAL_LOSS_ACCT,
    REVAL_LOSS_ACCOUNT_CCID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.fa_category_books
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(CATEGORY_ID, 0), COALESCE(BOOK_TYPE_CODE, 'NA'), kca_seq_id) IN (
      SELECT
        COALESCE(CATEGORY_ID, 0) AS CATEGORY_ID,
        COALESCE(BOOK_TYPE_CODE, 'NA') AS BOOK_TYPE_CODE,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.fa_category_books
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(CATEGORY_ID, 0),
        COALESCE(BOOK_TYPE_CODE, 'NA')
    )
);
/* Soft delete */
UPDATE silver_bec_ods.fa_category_books SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.fa_category_books SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(CATEGORY_ID, 0), COALESCE(BOOK_TYPE_CODE, 'NA')) IN (
    SELECT
      COALESCE(CATEGORY_ID, 0),
      COALESCE(BOOK_TYPE_CODE, 'NA')
    FROM bec_raw_dl_ext.fa_category_books
    WHERE
      (COALESCE(CATEGORY_ID, 0), COALESCE(BOOK_TYPE_CODE, 'NA'), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(CATEGORY_ID, 0),
          COALESCE(BOOK_TYPE_CODE, 'NA'),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.fa_category_books
        GROUP BY
          COALESCE(CATEGORY_ID, 0),
          COALESCE(BOOK_TYPE_CODE, 'NA')
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'fa_category_books';