/* Delete Records */
DELETE FROM silver_bec_ods.GL_LE_VALUE_SETS
WHERE
  (COALESCE(LEGAL_ENTITY_ID, 0), COALESCE(FLEX_VALUE_SET_ID, 0)) IN (
    SELECT
      COALESCE(stg.LEGAL_ENTITY_ID, 0) AS LEGAL_ENTITY_ID,
      COALESCE(stg.FLEX_VALUE_SET_ID, 0) AS FLEX_VALUE_SET_ID
    FROM silver_bec_ods.GL_LE_VALUE_SETS AS ods, bronze_bec_ods_stg.GL_LE_VALUE_SETS AS stg
    WHERE
      COALESCE(ods.LEGAL_ENTITY_ID, 0) = COALESCE(stg.LEGAL_ENTITY_ID, 0)
      AND COALESCE(ods.FLEX_VALUE_SET_ID, 0) = COALESCE(stg.FLEX_VALUE_SET_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.GL_LE_VALUE_SETS (
  LEGAL_ENTITY_ID,
  FLEX_VALUE_SET_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  CREATION_DATE,
  CREATED_BY,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    LEGAL_ENTITY_ID,
    FLEX_VALUE_SET_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATION_DATE,
    CREATED_BY,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.GL_LE_VALUE_SETS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(LEGAL_ENTITY_ID, 0), COALESCE(FLEX_VALUE_SET_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(LEGAL_ENTITY_ID, 0) AS LEGAL_ENTITY_ID,
        COALESCE(FLEX_VALUE_SET_ID, 0) AS FLEX_VALUE_SET_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.GL_LE_VALUE_SETS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(LEGAL_ENTITY_ID, 0),
        COALESCE(FLEX_VALUE_SET_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.GL_LE_VALUE_SETS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.GL_LE_VALUE_SETS SET IS_DELETED_FLG = 'Y'
WHERE
  (COALESCE(LEGAL_ENTITY_ID, 0), COALESCE(FLEX_VALUE_SET_ID, 0)) IN (
    SELECT
      COALESCE(LEGAL_ENTITY_ID, 0),
      COALESCE(FLEX_VALUE_SET_ID, 0)
    FROM bec_raw_dl_ext.GL_LE_VALUE_SETS
    WHERE
      (COALESCE(LEGAL_ENTITY_ID, 0), COALESCE(FLEX_VALUE_SET_ID, 0), KCA_SEQ_ID) IN (
        SELECT
          COALESCE(LEGAL_ENTITY_ID, 0),
          COALESCE(FLEX_VALUE_SET_ID, 0),
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.GL_LE_VALUE_SETS
        GROUP BY
          COALESCE(LEGAL_ENTITY_ID, 0),
          COALESCE(FLEX_VALUE_SET_ID, 0)
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_le_value_sets';