/* Delete Records */
DELETE FROM silver_bec_ods.CST_COST_GROUPS
WHERE
  (
    COST_GROUP_ID
  ) IN (
    SELECT
      stg.COST_GROUP_ID
    FROM silver_bec_ods.CST_COST_GROUPS AS ods, bronze_bec_ods_stg.CST_COST_GROUPS AS stg
    WHERE
      ods.COST_GROUP_ID = stg.COST_GROUP_ID AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.CST_COST_GROUPS (
  COST_GROUP_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  ORGANIZATION_ID,
  COST_GROUP,
  DESCRIPTION,
  DISABLE_DATE,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  LEGAL_ENTITY,
  COST_GROUP_TYPE,
  ZD_EDITION_NAME,
  ZD_SYNC,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    COST_GROUP_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    ORGANIZATION_ID,
    COST_GROUP,
    DESCRIPTION,
    DISABLE_DATE,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    LEGAL_ENTITY,
    COST_GROUP_TYPE,
    ZD_EDITION_NAME,
    ZD_SYNC,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.CST_COST_GROUPS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COST_GROUP_ID, kca_seq_id) IN (
      SELECT
        COST_GROUP_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.CST_COST_GROUPS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COST_GROUP_ID
    )
);
/* Soft delete */
UPDATE silver_bec_ods.CST_COST_GROUPS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.CST_COST_GROUPS SET IS_DELETED_FLG = 'Y'
WHERE
  (
    COST_GROUP_ID
  ) IN (
    SELECT
      COST_GROUP_ID
    FROM bec_raw_dl_ext.CST_COST_GROUPS
    WHERE
      (COST_GROUP_ID, KCA_SEQ_ID) IN (
        SELECT
          COST_GROUP_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.CST_COST_GROUPS
        GROUP BY
          COST_GROUP_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'cst_cost_groups';