/* Delete Records */
DELETE FROM silver_bec_ods.GL_LEGAL_ENTITIES_BSVS
WHERE
  (LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID, FLEX_SEGMENT_VALUE) IN (
    SELECT
      stg.LEGAL_ENTITY_ID,
      stg.FLEX_VALUE_SET_ID,
      stg.FLEX_SEGMENT_VALUE
    FROM silver_bec_ods.GL_LEGAL_ENTITIES_BSVS AS ods, bronze_bec_ods_stg.GL_LEGAL_ENTITIES_BSVS AS stg
    WHERE
      ods.LEGAL_ENTITY_ID = stg.LEGAL_ENTITY_ID
      AND ods.FLEX_VALUE_SET_ID = stg.FLEX_VALUE_SET_ID
      AND ods.FLEX_SEGMENT_VALUE = stg.FLEX_SEGMENT_VALUE
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.GL_LEGAL_ENTITIES_BSVS (
  LEGAL_ENTITY_ID,
  FLEX_VALUE_SET_ID,
  FLEX_SEGMENT_VALUE,
  START_DATE,
  END_DATE,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  CREATION_DATE,
  CREATED_BY,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    LEGAL_ENTITY_ID,
    FLEX_VALUE_SET_ID,
    FLEX_SEGMENT_VALUE,
    START_DATE,
    END_DATE,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATION_DATE,
    CREATED_BY,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.GL_LEGAL_ENTITIES_BSVS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID, FLEX_SEGMENT_VALUE, kca_seq_id) IN (
      SELECT
        LEGAL_ENTITY_ID,
        FLEX_VALUE_SET_ID,
        FLEX_SEGMENT_VALUE,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.GL_LEGAL_ENTITIES_BSVS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        LEGAL_ENTITY_ID,
        FLEX_VALUE_SET_ID,
        FLEX_SEGMENT_VALUE
    )
);
/* Soft delete */
UPDATE silver_bec_ods.GL_LEGAL_ENTITIES_BSVS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.GL_LEGAL_ENTITIES_BSVS SET IS_DELETED_FLG = 'Y'
WHERE
  (LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID, FLEX_SEGMENT_VALUE) IN (
    SELECT
      LEGAL_ENTITY_ID,
      FLEX_VALUE_SET_ID,
      FLEX_SEGMENT_VALUE
    FROM bec_raw_dl_ext.GL_LEGAL_ENTITIES_BSVS
    WHERE
      (LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID, FLEX_SEGMENT_VALUE, KCA_SEQ_ID) IN (
        SELECT
          LEGAL_ENTITY_ID,
          FLEX_VALUE_SET_ID,
          FLEX_SEGMENT_VALUE,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.GL_LEGAL_ENTITIES_BSVS
        GROUP BY
          LEGAL_ENTITY_ID,
          FLEX_VALUE_SET_ID,
          FLEX_SEGMENT_VALUE
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_legal_entities_bsvs';