/* Delete Records */
DELETE FROM silver_bec_ods.AR_RECEIVABLES_TRX_ALL
WHERE
  (RECEIVABLES_TRX_ID, COALESCE(org_id, 0)) IN (
    SELECT
      stg.RECEIVABLES_TRX_ID,
      COALESCE(stg.org_id, 0)
    FROM silver_bec_ods.AR_RECEIVABLES_TRX_ALL AS ods, bronze_bec_ods_stg.AR_RECEIVABLES_TRX_ALL AS stg
    WHERE
      ods.RECEIVABLES_TRX_ID = stg.RECEIVABLES_TRX_ID
      AND COALESCE(ods.org_id, 0) = COALESCE(stg.org_id, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.AR_RECEIVABLES_TRX_ALL (
  ACCOUNTING_AFFECT_FLAG,
  ASSET_TAX_CODE,
  ATTRIBUTE1,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE_CATEGORY,
  CODE_COMBINATION_ID,
  CREATED_BY,
  CREATION_DATE,
  DEFAULT_ACCTG_DISTRIBUTION_SET,
  DESCRIPTION,
  END_DATE_ACTIVE,
  GLOBAL_ATTRIBUTE1,
  GLOBAL_ATTRIBUTE10,
  GLOBAL_ATTRIBUTE11,
  GLOBAL_ATTRIBUTE12,
  GLOBAL_ATTRIBUTE13,
  GLOBAL_ATTRIBUTE14,
  GLOBAL_ATTRIBUTE15,
  GLOBAL_ATTRIBUTE16,
  GLOBAL_ATTRIBUTE17,
  GLOBAL_ATTRIBUTE18,
  GLOBAL_ATTRIBUTE19,
  GLOBAL_ATTRIBUTE2,
  GLOBAL_ATTRIBUTE20,
  GLOBAL_ATTRIBUTE3,
  GLOBAL_ATTRIBUTE4,
  GLOBAL_ATTRIBUTE5,
  GLOBAL_ATTRIBUTE6,
  GLOBAL_ATTRIBUTE7,
  GLOBAL_ATTRIBUTE8,
  GLOBAL_ATTRIBUTE9,
  GLOBAL_ATTRIBUTE_CATEGORY,
  GL_ACCOUNT_SOURCE,
  INACTIVE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  LIABILITY_TAX_CODE,
  NAME,
  ORG_ID,
  RECEIVABLES_TRX_ID,
  RISK_ELIMINATION_DAYS,
  SET_OF_BOOKS_ID,
  START_DATE_ACTIVE,
  STATUS,
  TAX_CODE_SOURCE,
  TAX_RECOVERABLE_FLAG,
  TYPE,
  ZD_EDITION_NAME,
  ZD_SYNC,
  IS_DELETED_FLG,
  KCA_OPERATION,
  KCA_SEQ_ID,
  kca_seq_date
)
SELECT
  ACCOUNTING_AFFECT_FLAG,
  ASSET_TAX_CODE,
  ATTRIBUTE1,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE_CATEGORY,
  CODE_COMBINATION_ID,
  CREATED_BY,
  CREATION_DATE,
  DEFAULT_ACCTG_DISTRIBUTION_SET,
  DESCRIPTION,
  END_DATE_ACTIVE,
  GLOBAL_ATTRIBUTE1,
  GLOBAL_ATTRIBUTE10,
  GLOBAL_ATTRIBUTE11,
  GLOBAL_ATTRIBUTE12,
  GLOBAL_ATTRIBUTE13,
  GLOBAL_ATTRIBUTE14,
  GLOBAL_ATTRIBUTE15,
  GLOBAL_ATTRIBUTE16,
  GLOBAL_ATTRIBUTE17,
  GLOBAL_ATTRIBUTE18,
  GLOBAL_ATTRIBUTE19,
  GLOBAL_ATTRIBUTE2,
  GLOBAL_ATTRIBUTE20,
  GLOBAL_ATTRIBUTE3,
  GLOBAL_ATTRIBUTE4,
  GLOBAL_ATTRIBUTE5,
  GLOBAL_ATTRIBUTE6,
  GLOBAL_ATTRIBUTE7,
  GLOBAL_ATTRIBUTE8,
  GLOBAL_ATTRIBUTE9,
  GLOBAL_ATTRIBUTE_CATEGORY,
  GL_ACCOUNT_SOURCE,
  INACTIVE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  LIABILITY_TAX_CODE,
  NAME,
  ORG_ID,
  RECEIVABLES_TRX_ID,
  RISK_ELIMINATION_DAYS,
  SET_OF_BOOKS_ID,
  START_DATE_ACTIVE,
  STATUS,
  TAX_CODE_SOURCE,
  TAX_RECOVERABLE_FLAG,
  TYPE,
  ZD_EDITION_NAME,
  ZD_SYNC,
  'N' AS IS_DELETED_FLG,
  KCA_OPERATION,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.AR_RECEIVABLES_TRX_ALL
WHERE
  kca_operation IN ('INSERT', 'UPDATE')
  AND (RECEIVABLES_TRX_ID, COALESCE(org_id, 0), kca_seq_id) IN (
    SELECT
      RECEIVABLES_TRX_ID,
      COALESCE(org_id, 0),
      MAX(kca_seq_id)
    FROM bronze_bec_ods_stg.AR_RECEIVABLES_TRX_ALL
    WHERE
      kca_operation IN ('INSERT', 'UPDATE')
    GROUP BY
      RECEIVABLES_TRX_ID,
      COALESCE(org_id, 0)
  );
COMMIT;
/* Soft delete */
UPDATE silver_bec_ods.AR_RECEIVABLES_TRX_ALL SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.AR_RECEIVABLES_TRX_ALL SET IS_DELETED_FLG = 'Y'
WHERE
  (RECEIVABLES_TRX_ID, COALESCE(org_id, 0)) IN (
    SELECT
      RECEIVABLES_TRX_ID,
      COALESCE(org_id, 0) AS org_id
    FROM bec_raw_dl_ext.AR_RECEIVABLES_TRX_ALL
    WHERE
      (RECEIVABLES_TRX_ID, COALESCE(org_id, 0), KCA_SEQ_ID) IN (
        SELECT
          RECEIVABLES_TRX_ID,
          COALESCE(org_id, 0) AS org_id,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.AR_RECEIVABLES_TRX_ALL
        GROUP BY
          RECEIVABLES_TRX_ID,
          COALESCE(org_id, 0)
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'ar_receivables_trx_all';