/* Delete Records */
DELETE FROM silver_bec_ods.OE_ORDER_HOLDS_ALL
WHERE
  COALESCE(ORDER_HOLD_ID, 0) IN (
    SELECT
      COALESCE(stg.ORDER_HOLD_ID, 0) AS ORDER_HOLD_ID
    FROM silver_bec_ods.OE_ORDER_HOLDS_ALL AS ods, bronze_bec_ods_stg.OE_ORDER_HOLDS_ALL AS stg
    WHERE
      COALESCE(ods.ORDER_HOLD_ID, 0) = COALESCE(stg.ORDER_HOLD_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.OE_ORDER_HOLDS_ALL (
  ORDER_HOLD_ID,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  REQUEST_ID,
  HOLD_SOURCE_ID,
  HOLD_RELEASE_ID,
  HEADER_ID,
  LINE_ID,
  ORG_ID,
  CONTEXT,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  RELEASED_FLAG,
  INST_ID,
  CREDIT_PROFILE_LEVEL,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    ORDER_HOLD_ID,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    REQUEST_ID,
    HOLD_SOURCE_ID,
    HOLD_RELEASE_ID,
    HEADER_ID,
    LINE_ID,
    ORG_ID,
    CONTEXT,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    RELEASED_FLAG,
    INST_ID,
    CREDIT_PROFILE_LEVEL,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.OE_ORDER_HOLDS_ALL
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(ORDER_HOLD_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(ORDER_HOLD_ID, 0) AS ORDER_HOLD_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.OE_ORDER_HOLDS_ALL
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(ORDER_HOLD_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.OE_ORDER_HOLDS_ALL SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.OE_ORDER_HOLDS_ALL SET IS_DELETED_FLG = 'Y'
WHERE
  (
    ORDER_HOLD_ID
  ) IN (
    SELECT
      ORDER_HOLD_ID
    FROM bec_raw_dl_ext.OE_ORDER_HOLDS_ALL
    WHERE
      (ORDER_HOLD_ID, KCA_SEQ_ID) IN (
        SELECT
          ORDER_HOLD_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.OE_ORDER_HOLDS_ALL
        GROUP BY
          ORDER_HOLD_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'oe_order_holds_all';