TRUNCATE table silver_bec_ods.OE_LINES_IFACE_ALL;
INSERT INTO silver_bec_ods.OE_LINES_IFACE_ALL (
  REQUEST_ID,
  ORIG_SHIP_ADDRESS_REF,
  ORIG_BILL_ADDRESS_REF,
  ORIG_DELIVER_ADDRESS_REF,
  SHIP_TO_CONTACT_REF,
  BILL_TO_CONTACT_REF,
  DELIVER_TO_CONTACT_REF,
  ORDER_SOURCE_ID,
  ORIG_SYS_DOCUMENT_REF,
  ORIG_SYS_LINE_REF,
  ORIG_SYS_SHIPMENT_REF,
  SOLD_TO_ORG_ID,
  SOLD_TO_ORG,
  CHANGE_SEQUENCE,
  kca_operation,
  is_deleted_flg,
  kca_seq_id,
  kca_seq_date
)
SELECT
  REQUEST_ID,
  ORIG_SHIP_ADDRESS_REF,
  ORIG_BILL_ADDRESS_REF,
  ORIG_DELIVER_ADDRESS_REF,
  SHIP_TO_CONTACT_REF,
  BILL_TO_CONTACT_REF,
  DELIVER_TO_CONTACT_REF,
  ORDER_SOURCE_ID,
  ORIG_SYS_DOCUMENT_REF,
  ORIG_SYS_LINE_REF,
  ORIG_SYS_SHIPMENT_REF,
  SOLD_TO_ORG_ID,
  SOLD_TO_ORG,
  CHANGE_SEQUENCE,
  kca_operation,
  'N' AS IS_DELETED_FLG,
  CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
  kca_seq_date
FROM bronze_bec_ods_stg.OE_LINES_IFACE_ALL;
UPDATE bec_etl_ctrl.batch_ods_info SET load_type = 'I', last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'oe_lines_iface_all';