/* Delete Records */
DELETE FROM silver_bec_ods.gl_je_headers
WHERE
  je_header_ID IN (
    SELECT
      stg.je_header_ID
    FROM silver_bec_ods.gl_je_headers AS ods, bronze_bec_ods_stg.gl_je_headers AS stg
    WHERE
      ods.je_header_ID = stg.je_header_ID AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.gl_je_headers (
  JE_HEADER_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LEDGER_ID,
  JE_CATEGORY,
  JE_SOURCE,
  PERIOD_NAME,
  NAME,
  CURRENCY_CODE,
  STATUS,
  DATE_CREATED,
  ACCRUAL_REV_FLAG,
  MULTI_BAL_SEG_FLAG,
  ACTUAL_FLAG,
  DEFAULT_EFFECTIVE_DATE,
  CONVERSION_FLAG,
  CREATION_DATE,
  CREATED_BY,
  LAST_UPDATE_LOGIN,
  ENCUMBRANCE_TYPE_ID,
  BUDGET_VERSION_ID,
  BALANCED_JE_FLAG,
  BALANCING_SEGMENT_VALUE,
  JE_BATCH_ID,
  FROM_RECURRING_HEADER_ID,
  UNIQUE_DATE,
  EARLIEST_POSTABLE_DATE,
  POSTED_DATE,
  ACCRUAL_REV_EFFECTIVE_DATE,
  ACCRUAL_REV_PERIOD_NAME,
  ACCRUAL_REV_STATUS,
  ACCRUAL_REV_JE_HEADER_ID,
  ACCRUAL_REV_CHANGE_SIGN_FLAG,
  DESCRIPTION,
  CONTROL_TOTAL,
  RUNNING_TOTAL_DR,
  RUNNING_TOTAL_CR,
  RUNNING_TOTAL_ACCOUNTED_DR,
  RUNNING_TOTAL_ACCOUNTED_CR,
  CURRENCY_CONVERSION_RATE,
  CURRENCY_CONVERSION_TYPE,
  CURRENCY_CONVERSION_DATE,
  EXTERNAL_REFERENCE,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  CONTEXT,
  USSGL_TRANSACTION_CODE,
  CONTEXT2,
  DOC_SEQUENCE_ID,
  DOC_SEQUENCE_VALUE,
  JGZZ_RECON_CONTEXT,
  JGZZ_RECON_REF,
  GLOBAL_ATTRIBUTE_CATEGORY,
  GLOBAL_ATTRIBUTE1,
  GLOBAL_ATTRIBUTE2,
  GLOBAL_ATTRIBUTE3,
  GLOBAL_ATTRIBUTE4,
  GLOBAL_ATTRIBUTE5,
  GLOBAL_ATTRIBUTE6,
  GLOBAL_ATTRIBUTE7,
  GLOBAL_ATTRIBUTE8,
  GLOBAL_ATTRIBUTE9,
  GLOBAL_ATTRIBUTE10,
  TAX_STATUS_CODE,
  PARENT_JE_HEADER_ID,
  REVERSED_JE_HEADER_ID,
  ORIGINATING_BAL_SEG_VALUE,
  INTERCOMPANY_MODE,
  DR_BAL_SEG_VALUE,
  CR_BAL_SEG_VALUE,
  REFERENCE_DATE,
  LOCAL_DOC_SEQUENCE_ID,
  LOCAL_DOC_SEQUENCE_VALUE,
  DISPLAY_ALC_JOURNAL_FLAG,
  JE_FROM_SLA_FLAG,
  POSTING_ACCT_SEQ_VERSION_ID,
  POSTING_ACCT_SEQ_ASSIGN_ID,
  POSTING_ACCT_SEQ_VALUE,
  CLOSE_ACCT_SEQ_VERSION_ID,
  CLOSE_ACCT_SEQ_ASSIGN_ID,
  CLOSE_ACCT_SEQ_VALUE,
  KCA_OPERATION,
  IS_DELETED_FLG,
  KCA_SEQ_ID,
  kca_seq_date
)
(
  SELECT
    JE_HEADER_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LEDGER_ID,
    JE_CATEGORY,
    JE_SOURCE,
    PERIOD_NAME,
    NAME,
    CURRENCY_CODE,
    STATUS,
    DATE_CREATED,
    ACCRUAL_REV_FLAG,
    MULTI_BAL_SEG_FLAG,
    ACTUAL_FLAG,
    DEFAULT_EFFECTIVE_DATE,
    CONVERSION_FLAG,
    CREATION_DATE,
    CREATED_BY,
    LAST_UPDATE_LOGIN,
    ENCUMBRANCE_TYPE_ID,
    BUDGET_VERSION_ID,
    BALANCED_JE_FLAG,
    BALANCING_SEGMENT_VALUE,
    JE_BATCH_ID,
    FROM_RECURRING_HEADER_ID,
    UNIQUE_DATE,
    EARLIEST_POSTABLE_DATE,
    POSTED_DATE,
    ACCRUAL_REV_EFFECTIVE_DATE,
    ACCRUAL_REV_PERIOD_NAME,
    ACCRUAL_REV_STATUS,
    ACCRUAL_REV_JE_HEADER_ID,
    ACCRUAL_REV_CHANGE_SIGN_FLAG,
    DESCRIPTION,
    CONTROL_TOTAL,
    RUNNING_TOTAL_DR,
    RUNNING_TOTAL_CR,
    RUNNING_TOTAL_ACCOUNTED_DR,
    RUNNING_TOTAL_ACCOUNTED_CR,
    CURRENCY_CONVERSION_RATE,
    CURRENCY_CONVERSION_TYPE,
    CURRENCY_CONVERSION_DATE,
    EXTERNAL_REFERENCE,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    CONTEXT,
    USSGL_TRANSACTION_CODE,
    CONTEXT2,
    DOC_SEQUENCE_ID,
    DOC_SEQUENCE_VALUE,
    JGZZ_RECON_CONTEXT,
    JGZZ_RECON_REF,
    GLOBAL_ATTRIBUTE_CATEGORY,
    GLOBAL_ATTRIBUTE1,
    GLOBAL_ATTRIBUTE2,
    GLOBAL_ATTRIBUTE3,
    GLOBAL_ATTRIBUTE4,
    GLOBAL_ATTRIBUTE5,
    GLOBAL_ATTRIBUTE6,
    GLOBAL_ATTRIBUTE7,
    GLOBAL_ATTRIBUTE8,
    GLOBAL_ATTRIBUTE9,
    GLOBAL_ATTRIBUTE10,
    TAX_STATUS_CODE,
    PARENT_JE_HEADER_ID,
    REVERSED_JE_HEADER_ID,
    ORIGINATING_BAL_SEG_VALUE,
    INTERCOMPANY_MODE,
    DR_BAL_SEG_VALUE,
    CR_BAL_SEG_VALUE,
    REFERENCE_DATE,
    LOCAL_DOC_SEQUENCE_ID,
    LOCAL_DOC_SEQUENCE_VALUE,
    DISPLAY_ALC_JOURNAL_FLAG,
    JE_FROM_SLA_FLAG,
    POSTING_ACCT_SEQ_VERSION_ID,
    POSTING_ACCT_SEQ_ASSIGN_ID,
    POSTING_ACCT_SEQ_VALUE,
    CLOSE_ACCT_SEQ_VERSION_ID,
    CLOSE_ACCT_SEQ_ASSIGN_ID,
    CLOSE_ACCT_SEQ_VALUE,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.gl_je_headers
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (je_header_ID, kca_seq_id) IN (
      SELECT
        je_header_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.gl_je_headers
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        je_header_ID
    )
);
/* Soft Delete */
UPDATE silver_bec_ods.gl_je_headers SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.gl_je_headers SET IS_DELETED_FLG = 'Y'
WHERE
  (
    je_header_ID
  ) IN (
    SELECT
      je_header_ID
    FROM bec_raw_dl_ext.gl_je_headers
    WHERE
      (je_header_ID, KCA_SEQ_ID) IN (
        SELECT
          je_header_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.gl_je_headers
        GROUP BY
          je_header_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'gl_je_headers';