/* Delete Records */
DELETE FROM silver_bec_ods.IBY_EXT_BANK_ACCOUNTS
WHERE
  (
    COALESCE(EXT_BANK_ACCOUNT_ID, 0)
  ) IN (
    SELECT
      COALESCE(stg.EXT_BANK_ACCOUNT_ID, 0) AS EXT_BANK_ACCOUNT_ID
    FROM silver_bec_ods.IBY_EXT_BANK_ACCOUNTS AS ods, bronze_bec_ods_stg.IBY_EXT_BANK_ACCOUNTS AS stg
    WHERE
      COALESCE(ods.EXT_BANK_ACCOUNT_ID, 0) = COALESCE(stg.EXT_BANK_ACCOUNT_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.IBY_EXT_BANK_ACCOUNTS (
  EXT_BANK_ACCOUNT_ID,
  COUNTRY_CODE,
  BRANCH_ID,
  BANK_ID,
  BANK_ACCOUNT_NUM,
  MASKED_BANK_ACCOUNT_NUM,
  BA_MASK_SETTING,
  BA_UNMASK_LENGTH,
  CURRENCY_CODE,
  IBAN,
  IBAN_HASH1,
  IBAN_HASH2,
  MASKED_IBAN,
  CHECK_DIGITS,
  BANK_ACCOUNT_TYPE,
  ACCOUNT_CLASSIFICATION,
  ACCOUNT_SUFFIX,
  AGENCY_LOCATION_CODE,
  PAYMENT_FACTOR_FLAG,
  FOREIGN_PAYMENT_USE_FLAG,
  EXCHANGE_RATE_AGREEMENT_NUM,
  EXCHANGE_RATE_AGREEMENT_TYPE,
  EXCHANGE_RATE,
  HEDGING_CONTRACT_REFERENCE,
  SECONDARY_ACCOUNT_REFERENCE,
  BA_NUM_SEC_SEGMENT_ID,
  ENCRYPTED,
  IBAN_SEC_SEGMENT_ID,
  ATTRIBUTE_CATEGORY,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  REQUEST_ID,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  START_DATE,
  END_DATE,
  CREATED_BY,
  CREATION_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_DATE,
  LAST_UPDATE_LOGIN,
  OBJECT_VERSION_NUMBER,
  BANK_ACCOUNT_NAME,
  BANK_ACCOUNT_NAME_ALT,
  SHORT_ACCT_NAME,
  DESCRIPTION,
  BANK_ACCOUNT_NUM_ELECTRONIC,
  BA_NUM_ELEC_SEC_SEGMENT_ID,
  SALT_VERSION,
  CONTACT_NAME,
  CONTACT_PHONE,
  CONTACT_FAX,
  CONTACT_EMAIL,
  kca_operation,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    EXT_BANK_ACCOUNT_ID,
    COUNTRY_CODE,
    BRANCH_ID,
    BANK_ID,
    BANK_ACCOUNT_NUM,
    MASKED_BANK_ACCOUNT_NUM,
    BA_MASK_SETTING,
    BA_UNMASK_LENGTH,
    CURRENCY_CODE,
    IBAN,
    IBAN_HASH1,
    IBAN_HASH2,
    MASKED_IBAN,
    CHECK_DIGITS,
    BANK_ACCOUNT_TYPE,
    ACCOUNT_CLASSIFICATION,
    ACCOUNT_SUFFIX,
    AGENCY_LOCATION_CODE,
    PAYMENT_FACTOR_FLAG,
    FOREIGN_PAYMENT_USE_FLAG,
    EXCHANGE_RATE_AGREEMENT_NUM,
    EXCHANGE_RATE_AGREEMENT_TYPE,
    EXCHANGE_RATE,
    HEDGING_CONTRACT_REFERENCE,
    SECONDARY_ACCOUNT_REFERENCE,
    BA_NUM_SEC_SEGMENT_ID,
    ENCRYPTED,
    IBAN_SEC_SEGMENT_ID,
    ATTRIBUTE_CATEGORY,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    REQUEST_ID,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    START_DATE,
    END_DATE,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    LAST_UPDATE_LOGIN,
    OBJECT_VERSION_NUMBER,
    BANK_ACCOUNT_NAME,
    BANK_ACCOUNT_NAME_ALT,
    SHORT_ACCT_NAME,
    DESCRIPTION,
    BANK_ACCOUNT_NUM_ELECTRONIC,
    BA_NUM_ELEC_SEC_SEGMENT_ID,
    SALT_VERSION,
    CONTACT_NAME,
    CONTACT_PHONE,
    CONTACT_FAX,
    CONTACT_EMAIL,
    kca_operation,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    kca_seq_date
  FROM bronze_bec_ods_stg.IBY_EXT_BANK_ACCOUNTS
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(EXT_BANK_ACCOUNT_ID, 0), KCA_SEQ_ID) IN (
      SELECT
        COALESCE(EXT_BANK_ACCOUNT_ID, 0) AS EXT_BANK_ACCOUNT_ID,
        MAX(KCA_SEQ_ID)
      FROM bronze_bec_ods_stg.IBY_EXT_BANK_ACCOUNTS
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(EXT_BANK_ACCOUNT_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.IBY_EXT_BANK_ACCOUNTS SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.IBY_EXT_BANK_ACCOUNTS SET IS_DELETED_FLG = 'Y'
WHERE
  (
    EXT_BANK_ACCOUNT_ID
  ) IN (
    SELECT
      EXT_BANK_ACCOUNT_ID
    FROM bec_raw_dl_ext.IBY_EXT_BANK_ACCOUNTS
    WHERE
      (EXT_BANK_ACCOUNT_ID, KCA_SEQ_ID) IN (
        SELECT
          EXT_BANK_ACCOUNT_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.IBY_EXT_BANK_ACCOUNTS
        GROUP BY
          EXT_BANK_ACCOUNT_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'iby_ext_bank_accounts';