/* Delete Records */
DELETE FROM silver_bec_ods.OE_HOLD_SOURCES_ALL
WHERE
  COALESCE(HOLD_SOURCE_ID, 0) IN (
    SELECT
      COALESCE(stg.HOLD_SOURCE_ID, 0) AS HOLD_SOURCE_ID
    FROM silver_bec_ods.OE_HOLD_SOURCES_ALL AS ods, bronze_bec_ods_stg.OE_HOLD_SOURCES_ALL AS stg
    WHERE
      COALESCE(ods.HOLD_SOURCE_ID, 0) = COALESCE(stg.HOLD_SOURCE_ID, 0)
      AND stg.kca_operation IN ('INSERT', 'UPDATE')
  );
/* Insert records */
INSERT INTO silver_bec_ods.OE_HOLD_SOURCES_ALL (
  HOLD_SOURCE_ID,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  LAST_UPDATE_LOGIN,
  CREATION_DATE,
  CREATED_BY,
  PROGRAM_APPLICATION_ID,
  PROGRAM_ID,
  PROGRAM_UPDATE_DATE,
  REQUEST_ID,
  HOLD_ID,
  HOLD_ENTITY_CODE,
  HOLD_ENTITY_ID,
  HOLD_ENTITY_CODE2,
  HOLD_ENTITY_ID2,
  HOLD_UNTIL_DATE,
  RELEASED_FLAG,
  HOLD_COMMENT,
  ORG_ID,
  CONTEXT,
  ATTRIBUTE1,
  ATTRIBUTE2,
  ATTRIBUTE3,
  ATTRIBUTE4,
  ATTRIBUTE5,
  ATTRIBUTE6,
  ATTRIBUTE7,
  ATTRIBUTE8,
  ATTRIBUTE9,
  ATTRIBUTE10,
  ATTRIBUTE11,
  ATTRIBUTE12,
  ATTRIBUTE13,
  ATTRIBUTE14,
  ATTRIBUTE15,
  HOLD_RELEASE_ID,
  KCA_OPERATION,
  IS_DELETED_FLG,
  kca_seq_id,
  kca_seq_date
)
(
  SELECT
    HOLD_SOURCE_ID,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_LOGIN,
    CREATION_DATE,
    CREATED_BY,
    PROGRAM_APPLICATION_ID,
    PROGRAM_ID,
    PROGRAM_UPDATE_DATE,
    REQUEST_ID,
    HOLD_ID,
    HOLD_ENTITY_CODE,
    HOLD_ENTITY_ID,
    HOLD_ENTITY_CODE2,
    HOLD_ENTITY_ID2,
    HOLD_UNTIL_DATE,
    RELEASED_FLAG,
    HOLD_COMMENT,
    ORG_ID,
    CONTEXT,
    ATTRIBUTE1,
    ATTRIBUTE2,
    ATTRIBUTE3,
    ATTRIBUTE4,
    ATTRIBUTE5,
    ATTRIBUTE6,
    ATTRIBUTE7,
    ATTRIBUTE8,
    ATTRIBUTE9,
    ATTRIBUTE10,
    ATTRIBUTE11,
    ATTRIBUTE12,
    ATTRIBUTE13,
    ATTRIBUTE14,
    ATTRIBUTE15,
    HOLD_RELEASE_ID,
    KCA_OPERATION,
    'N' AS IS_DELETED_FLG,
    CAST(NULLIF(KCA_SEQ_ID, '') AS DECIMAL(36, 0)) AS KCA_SEQ_ID,
    KCA_SEQ_DATE
  FROM bronze_bec_ods_stg.OE_HOLD_SOURCES_ALL
  WHERE
    kca_operation IN ('INSERT', 'UPDATE')
    AND (COALESCE(HOLD_SOURCE_ID, 0), kca_seq_id) IN (
      SELECT
        COALESCE(HOLD_SOURCE_ID, 0) AS HOLD_SOURCE_ID,
        MAX(kca_seq_id)
      FROM bronze_bec_ods_stg.OE_HOLD_SOURCES_ALL
      WHERE
        kca_operation IN ('INSERT', 'UPDATE')
      GROUP BY
        COALESCE(HOLD_SOURCE_ID, 0)
    )
);
/* Soft delete */
UPDATE silver_bec_ods.OE_HOLD_SOURCES_ALL SET IS_DELETED_FLG = 'N';
UPDATE silver_bec_ods.OE_HOLD_SOURCES_ALL SET IS_DELETED_FLG = 'Y'
WHERE
  (
    HOLD_SOURCE_ID
  ) IN (
    SELECT
      HOLD_SOURCE_ID
    FROM bec_raw_dl_ext.OE_HOLD_SOURCES_ALL
    WHERE
      (HOLD_SOURCE_ID, KCA_SEQ_ID) IN (
        SELECT
          HOLD_SOURCE_ID,
          MAX(KCA_SEQ_ID) AS KCA_SEQ_ID
        FROM bec_raw_dl_ext.OE_HOLD_SOURCES_ALL
        GROUP BY
          HOLD_SOURCE_ID
      )
      AND kca_operation = 'DELETE'
  );
UPDATE bec_etl_ctrl.batch_ods_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  ods_table_name = 'oe_hold_sources_all';