/* Delete Records */
DELETE FROM gold_bec_dwh_rpt.FACT_GL_ACCOUNT_ANALYSIS_RT
WHERE
  dw_load_id IN (
    SELECT
      dw_load_id
    FROM gold_bec_dwh.fact_gl_account_analysis
    WHERE
      Update_flg = 'Y'
  );
/* Insert records */
INSERT INTO gold_bec_dwh_rpt.FACT_GL_ACCOUNT_ANALYSIS_RT (
  `accounted_cr`,
  `accounted_dr`,
  `accounted_period_type`,
  `accounting_class_code`,
  `accounting_class_name`,
  `accounting_code_combination`,
  `accounting_sequence_name`,
  `accounting_sequence_number`,
  `accounting_sequence_version`,
  `application_id`,
  `application_name`,
  `approver_name`,
  `bal_seg_column_name`,
  `bal_seg_value_set_id`,
  `balance_type`,
  `balance_type_code`,
  `balancing_segment`,
  `balancing_segment_desc`,
  `be_project_desc`,
  `be_project_no`,
  `be_task_desc`,
  `be_task_no`,
  `begin_balance_cr`,
  `begin_balance_dr`,
  `begin_running_total_cr`,
  `begin_running_total_dr`,
  `budget_name`,
  `chart_of_accounts_id (dim_ledgers)`,
  `code_combination_description`,
  `code_combination_id`,
  `code_combination_id_key`,
  `completed_date`,
  `control_account`,
  `control_account_flag`,
  `conversion_rate`,
  `conversion_rate_date`,
  `conversion_rate_type`,
  `conversion_rate_type_code`,
  `cost_center_desc`,
  `cost_center_segment`,
  `created_by_id`,
  `creation_date`,
  `currency_code`,
  `daily_translation_rate_type`,
  `document_category`,
  `document_sequence_name`,
  `document_sequence_number`,
  `dw_insert_date (dim_ledgers)`,
  `dw_insert_date`,
  `dw_load_id (dim_ledgers)`,
  `dw_load_id`,
  `dw_update_date (dim_ledgers)`,
  `dw_update_date`,
  `effective_date`,
  `encumbrance_type`,
  `end_running_total_cr`,
  `end_running_total_dr`,
  `entered_cr`,
  `entered_currency`,
  `entered_dr`,
  `event_class_code`,
  `event_class_name`,
  `event_date`,
  `event_id`,
  `event_number`,
  `event_type_code`,
  `event_type_name`,
  `external_reference`,
  `fund_status`,
  `gl_batch_name`,
  `gl_date`,
  `gl_je_name`,
  `gl_line_number`,
  `gl_transfer_date`,
  `header_description`,
  `header_id`,
  `intercompany_segment`,
  `intercompany_segment_desc`,
  `invoice_id`,
  `invoice_id_key`,
  `invoice_num`,
  `is_deleted_flg (dim_ledgers)`,
  `is_deleted_flg`,
  `je_category`,
  `je_category_key`,
  `je_header_id`,
  `je_header_id_key`,
  `je_source_name`,
  `last_update_date`,
  `le_address_line_1`,
  `le_address_line_2`,
  `le_address_line_3`,
  `le_br_accountant_name`,
  `le_br_accountant_number`,
  `le_br_daily_entity`,
  `le_br_daily_inscription_date`,
  `le_br_daily_inscription_number`,
  `le_br_daily_location`,
  `le_br_director_number`,
  `le_city`,
  `le_country`,
  `le_postal_code`,
  `le_region_1`,
  `le_region_2`,
  `le_region_3`,
  `le_registration_effective_from`,
  `le_registration_number`,
  `ledger_category_code`,
  `ledger_currency`,
  `ledger_description (dim_ledgers)`,
  `ledger_description`,
  `ledger_id (dim_ledgers)`,
  `ledger_id`,
  `ledger_id_key`,
  `ledger_name (dim_ledgers)`,
  `ledger_name`,
  `ledger_short_name (dim_ledgers)`,
  `ledger_short_name`,
  `legal_entity_id`,
  `legal_entity_id_key`,
  `legal_entity_name`,
  `line_description`,
  `line_number`,
  `management_segment`,
  `management_segment_desc`,
  `natural_account_desc`,
  `natural_account_segment`,
  `orig_line_number`,
  `party_type`,
  `party_type_code`,
  `period_end_date`,
  `period_name`,
  `period_net_cr`,
  `period_net_dr`,
  `period_number`,
  `period_set_name`,
  `period_start_date`,
  `period_year`,
  `po_number`,
  `posted_date`,
  `reconciliation_reference`,
  `reference_date`,
  `reporting_sequence_name`,
  `reporting_sequence_number`,
  `reporting_sequence_version`,
  `ret_earn_code_combination_id`,
  `reversal_period`,
  `reversal_status`,
  `segment10`,
  `segment1`,
  `segment2`,
  `segment3`,
  `segment4`,
  `segment5`,
  `segment6`,
  `segment7`,
  `segment8`,
  `segment9`,
  `sla_description_language`,
  `source_app_id (dim_ledgers)`,
  `source_app_id`,
  `statistical_amount`,
  `temp_line_num`,
  `transaction_date`,
  `transaction_number`,
  `translated_flag`,
  `unrounded_accounted_cr`,
  `unrounded_accounted_dr`,
  `vendor_id`,
  `vendor_id_key`,
  `vendor_site_id`,
  `user`,
  net_amount,
  `Include_Zero_Amount_Lines`
)
(
  SELECT
    `fact_gl_account_analysis`.`accounted_cr` AS `accounted_cr`,
    `fact_gl_account_analysis`.`accounted_dr` AS `accounted_dr`,
    `t0`.`accounted_period_type` AS `accounted_period_type`,
    `fact_gl_account_analysis`.`accounting_class_code` AS `accounting_class_code`,
    `fact_gl_account_analysis`.`accounting_class_name` AS `accounting_class_name`,
    `fact_gl_account_analysis`.`accounting_code_combination` AS `accounting_code_combination`,
    `fact_gl_account_analysis`.`accounting_sequence_name` AS `accounting_sequence_name`,
    `fact_gl_account_analysis`.`accounting_sequence_number` AS `accounting_sequence_number`,
    `fact_gl_account_analysis`.`accounting_sequence_version` AS `accounting_sequence_version`,
    `fact_gl_account_analysis`.`application_id` AS `application_id`,
    `fact_gl_account_analysis`.`application_name` AS `application_name`,
    `fact_gl_account_analysis`.`approver_name` AS `approver_name`,
    `t0`.`bal_seg_column_name` AS `bal_seg_column_name`,
    `t0`.`bal_seg_value_set_id` AS `bal_seg_value_set_id`,
    `fact_gl_account_analysis`.`balance_type` AS `balance_type`,
    `fact_gl_account_analysis`.`balance_type_code` AS `balance_type_code`,
    `fact_gl_account_analysis`.`balancing_segment` AS `balancing_segment`,
    `fact_gl_account_analysis`.`balancing_segment_desc` AS `balancing_segment_desc`,
    `fact_gl_account_analysis`.`be_project_desc` AS `be_project_desc`,
    `fact_gl_account_analysis`.`be_project_no` AS `be_project_no`,
    `fact_gl_account_analysis`.`be_task_desc` AS `be_task_desc`,
    `fact_gl_account_analysis`.`be_task_no` AS `be_task_no`,
    `fact_gl_account_analysis`.`begin_balance_cr` AS `begin_balance_cr`,
    `fact_gl_account_analysis`.`begin_balance_dr` AS `begin_balance_dr`,
    `fact_gl_account_analysis`.`begin_running_total_cr` AS `begin_running_total_cr`,
    `fact_gl_account_analysis`.`begin_running_total_dr` AS `begin_running_total_dr`,
    `fact_gl_account_analysis`.`budget_name` AS `budget_name`,
    `t0`.`chart_of_accounts_id` AS `chart_of_accounts_id (dim_ledgers)`,
    `fact_gl_account_analysis`.`code_combination_description` AS `code_combination_description`,
    `fact_gl_account_analysis`.`code_combination_id` AS `code_combination_id`,
    `fact_gl_account_analysis`.`code_combination_id_key` AS `code_combination_id_key`,
    `fact_gl_account_analysis`.`completed_date` AS `completed_date`,
    `fact_gl_account_analysis`.`control_account` AS `control_account`,
    `fact_gl_account_analysis`.`control_account_flag` AS `control_account_flag`,
    `fact_gl_account_analysis`.`conversion_rate` AS `conversion_rate`,
    `fact_gl_account_analysis`.`conversion_rate_date` AS `conversion_rate_date`,
    `fact_gl_account_analysis`.`conversion_rate_type` AS `conversion_rate_type`,
    `fact_gl_account_analysis`.`conversion_rate_type_code` AS `conversion_rate_type_code`,
    `fact_gl_account_analysis`.`cost_center_desc` AS `cost_center_desc`,
    `fact_gl_account_analysis`.`cost_center_segment` AS `cost_center_segment`,
    `fact_gl_account_analysis`.`created_by_id` AS `created_by_id`,
    `fact_gl_account_analysis`.`creation_date` AS `creation_date`,
    `t0`.`currency_code` AS `currency_code`,
    `t0`.`daily_translation_rate_type` AS `daily_translation_rate_type`,
    `fact_gl_account_analysis`.`document_category` AS `document_category`,
    `fact_gl_account_analysis`.`document_sequence_name` AS `document_sequence_name`,
    `fact_gl_account_analysis`.`document_sequence_number` AS `document_sequence_number`,
    `t0`.`dw_insert_date` AS `dw_insert_date (dim_ledgers)`,
    `fact_gl_account_analysis`.`dw_insert_date` AS `dw_insert_date`,
    `t0`.`dw_load_id` AS `dw_load_id (dim_ledgers)`,
    `fact_gl_account_analysis`.`dw_load_id` AS `dw_load_id`,
    `t0`.`dw_update_date` AS `dw_update_date (dim_ledgers)`,
    `fact_gl_account_analysis`.`dw_update_date` AS `dw_update_date`,
    `fact_gl_account_analysis`.`effective_date` AS `effective_date`,
    `fact_gl_account_analysis`.`encumbrance_type` AS `encumbrance_type`,
    `fact_gl_account_analysis`.`end_running_total_cr` AS `end_running_total_cr`,
    `fact_gl_account_analysis`.`end_running_total_dr` AS `end_running_total_dr`,
    `fact_gl_account_analysis`.`entered_cr` AS `entered_cr`,
    `fact_gl_account_analysis`.`entered_currency` AS `entered_currency`,
    `fact_gl_account_analysis`.`entered_dr` AS `entered_dr`,
    `fact_gl_account_analysis`.`event_class_code` AS `event_class_code`,
    `fact_gl_account_analysis`.`event_class_name` AS `event_class_name`,
    `fact_gl_account_analysis`.`event_date` AS `event_date`,
    `fact_gl_account_analysis`.`event_id` AS `event_id`,
    `fact_gl_account_analysis`.`event_number` AS `event_number`,
    `fact_gl_account_analysis`.`event_type_code` AS `event_type_code`,
    `fact_gl_account_analysis`.`event_type_name` AS `event_type_name`,
    `fact_gl_account_analysis`.`external_reference` AS `external_reference`,
    `fact_gl_account_analysis`.`fund_status` AS `fund_status`,
    `fact_gl_account_analysis`.`gl_batch_name` AS `gl_batch_name`,
    `fact_gl_account_analysis`.`gl_date` AS `gl_date`,
    `fact_gl_account_analysis`.`gl_je_name` AS `gl_je_name`,
    `fact_gl_account_analysis`.`gl_line_number` AS `gl_line_number`,
    `fact_gl_account_analysis`.`gl_transfer_date` AS `gl_transfer_date`,
    CAST(`fact_gl_account_analysis`.`header_description` AS STRING) AS `header_description`,
    `fact_gl_account_analysis`.`header_id` AS `header_id`,
    `fact_gl_account_analysis`.`intercompany_segment` AS `intercompany_segment`,
    `fact_gl_account_analysis`.`intercompany_segment_desc` AS `intercompany_segment_desc`,
    `fact_gl_account_analysis`.`invoice_id` AS `invoice_id`,
    `fact_gl_account_analysis`.`invoice_id_key` AS `invoice_id_key`,
    `fact_gl_account_analysis`.`invoice_num` AS `invoice_num`,
    `t0`.`is_deleted_flg` AS `is_deleted_flg (dim_ledgers)`,
    `fact_gl_account_analysis`.`is_deleted_flg` AS `is_deleted_flg`,
    `fact_gl_account_analysis`.`je_category` AS `je_category`,
    `fact_gl_account_analysis`.`je_category_key` AS `je_category_key`,
    `fact_gl_account_analysis`.`je_header_id` AS `je_header_id`,
    `fact_gl_account_analysis`.`je_header_id_key` AS `je_header_id_key`,
    `fact_gl_account_analysis`.`je_source_name` AS `je_source_name`,
    `fact_gl_account_analysis`.`last_update_date` AS `last_update_date`,
    `fact_gl_account_analysis`.`le_address_line_1` AS `le_address_line_1`,
    `fact_gl_account_analysis`.`le_address_line_2` AS `le_address_line_2`,
    `fact_gl_account_analysis`.`le_address_line_3` AS `le_address_line_3`,
    `fact_gl_account_analysis`.`le_br_accountant_name` AS `le_br_accountant_name`,
    `fact_gl_account_analysis`.`le_br_accountant_number` AS `le_br_accountant_number`,
    `fact_gl_account_analysis`.`le_br_daily_entity` AS `le_br_daily_entity`,
    `fact_gl_account_analysis`.`le_br_daily_inscription_date` AS `le_br_daily_inscription_date`,
    `fact_gl_account_analysis`.`le_br_daily_inscription_number` AS `le_br_daily_inscription_number`,
    `fact_gl_account_analysis`.`le_br_daily_location` AS `le_br_daily_location`,
    `fact_gl_account_analysis`.`le_br_director_number` AS `le_br_director_number`,
    `fact_gl_account_analysis`.`le_city` AS `le_city`,
    `fact_gl_account_analysis`.`le_country` AS `le_country`,
    `fact_gl_account_analysis`.`le_postal_code` AS `le_postal_code`,
    `fact_gl_account_analysis`.`le_region_1` AS `le_region_1`,
    `fact_gl_account_analysis`.`le_region_2` AS `le_region_2`,
    `fact_gl_account_analysis`.`le_region_3` AS `le_region_3`,
    `fact_gl_account_analysis`.`le_registration_effective_from` AS `le_registration_effective_from`,
    `fact_gl_account_analysis`.`le_registration_number` AS `le_registration_number`,
    `t0`.`ledger_category_code` AS `ledger_category_code`,
    `fact_gl_account_analysis`.`ledger_currency` AS `ledger_currency`,
    `t0`.`ledger_description` AS `ledger_description (dim_ledgers)`,
    `fact_gl_account_analysis`.`ledger_description` AS `ledger_description`,
    `t0`.`ledger_id` AS `ledger_id (dim_ledgers)`,
    `fact_gl_account_analysis`.`ledger_id` AS `ledger_id`,
    `fact_gl_account_analysis`.`ledger_id_key` AS `ledger_id_key`,
    `t0`.`ledger_name` AS `ledger_name (dim_ledgers)`,
    `fact_gl_account_analysis`.`ledger_name` AS `ledger_name`,
    `t0`.`ledger_short_name` AS `ledger_short_name (dim_ledgers)`,
    `fact_gl_account_analysis`.`ledger_short_name` AS `ledger_short_name`,
    `fact_gl_account_analysis`.`legal_entity_id` AS `legal_entity_id`,
    `fact_gl_account_analysis`.`legal_entity_id_key` AS `legal_entity_id_key`,
    `fact_gl_account_analysis`.`legal_entity_name` AS `legal_entity_name`,
    CAST(`fact_gl_account_analysis`.`line_description` AS STRING) AS `line_description`,
    `fact_gl_account_analysis`.`line_number` AS `line_number`,
    `fact_gl_account_analysis`.`management_segment` AS `management_segment`,
    `fact_gl_account_analysis`.`management_segment_desc` AS `management_segment_desc`,
    `fact_gl_account_analysis`.`natural_account_desc` AS `natural_account_desc`,
    `fact_gl_account_analysis`.`natural_account_segment` AS `natural_account_segment`,
    `fact_gl_account_analysis`.`orig_line_number` AS `orig_line_number`,
    `fact_gl_account_analysis`.`party_type` AS `party_type`,
    `fact_gl_account_analysis`.`party_type_code` AS `party_type_code`,
    `fact_gl_account_analysis`.`period_end_date` AS `period_end_date`,
    `fact_gl_account_analysis`.`period_name` AS `period_name`,
    `fact_gl_account_analysis`.`period_net_cr` AS `period_net_cr`,
    `fact_gl_account_analysis`.`period_net_dr` AS `period_net_dr`,
    `fact_gl_account_analysis`.`period_number` AS `period_number`,
    `t0`.`period_set_name` AS `period_set_name`,
    `fact_gl_account_analysis`.`period_start_date` AS `period_start_date`,
    `fact_gl_account_analysis`.`period_year` AS `period_year`,
    `fact_gl_account_analysis`.`po_number` AS `po_number`,
    `fact_gl_account_analysis`.`posted_date` AS `posted_date`,
    `fact_gl_account_analysis`.`reconciliation_reference` AS `reconciliation_reference`,
    `fact_gl_account_analysis`.`reference_date` AS `reference_date`,
    `fact_gl_account_analysis`.`reporting_sequence_name` AS `reporting_sequence_name`,
    `fact_gl_account_analysis`.`reporting_sequence_number` AS `reporting_sequence_number`,
    `fact_gl_account_analysis`.`reporting_sequence_version` AS `reporting_sequence_version`,
    `t0`.`ret_earn_code_combination_id` AS `ret_earn_code_combination_id`,
    `fact_gl_account_analysis`.`reversal_period` AS `reversal_period`,
    `fact_gl_account_analysis`.`reversal_status` AS `reversal_status`,
    `fact_gl_account_analysis`.`segment10` AS `segment10`,
    `fact_gl_account_analysis`.`segment1` AS `segment1`,
    `fact_gl_account_analysis`.`segment2` AS `segment2`,
    `fact_gl_account_analysis`.`segment3` AS `segment3`,
    `fact_gl_account_analysis`.`segment4` AS `segment4`,
    `fact_gl_account_analysis`.`segment5` AS `segment5`,
    `fact_gl_account_analysis`.`segment6` AS `segment6`,
    `fact_gl_account_analysis`.`segment7` AS `segment7`,
    `fact_gl_account_analysis`.`segment8` AS `segment8`,
    `fact_gl_account_analysis`.`segment9` AS `segment9`,
    `t0`.`sla_description_language` AS `sla_description_language`,
    `t0`.`source_app_id` AS `source_app_id (dim_ledgers)`,
    `fact_gl_account_analysis`.`source_app_id` AS `source_app_id`,
    `fact_gl_account_analysis`.`statistical_amount` AS `statistical_amount`,
    `fact_gl_account_analysis`.`temp_line_num` AS `temp_line_num`,
    `fact_gl_account_analysis`.`transaction_date` AS `transaction_date`,
    `fact_gl_account_analysis`.`transaction_number` AS `transaction_number`,
    `fact_gl_account_analysis`.`translated_flag` AS `translated_flag`,
    `fact_gl_account_analysis`.`unrounded_accounted_cr` AS `unrounded_accounted_cr`,
    `fact_gl_account_analysis`.`unrounded_accounted_dr` AS `unrounded_accounted_dr`,
    `fact_gl_account_analysis`.`vendor_id` AS `vendor_id`,
    `fact_gl_account_analysis`.`vendor_id_key` AS `vendor_id_key`,
    `fact_gl_account_analysis`.`vendor_site_id` AS `vendor_site_id`,
    CASE
      WHEN `fact_gl_account_analysis`.`approver_name` IS NULL
      THEN 'SYSADMIN'
      ELSE `fact_gl_account_analysis`.`approver_name`
    END AS `user`,
    COALESCE(`fact_gl_account_analysis`.`accounted_dr`, 0) - COALESCE(`fact_gl_account_analysis`.`accounted_cr`, 0) AS net_amount,
    CASE
      WHEN COALESCE(`fact_gl_account_analysis`.`accounted_dr`, 0) - COALESCE(`fact_gl_account_analysis`.`accounted_cr`, 0) = 0
      THEN 'Y'
      ELSE 'N'
    END AS `Include_Zero_Amount_Lines`
  FROM (
    SELECT
      *
    FROM gold_bec_dwh.fact_gl_account_analysis
    WHERE
      Update_flg = 'Y'
  ) AS fact_gl_account_analysis
  INNER JOIN (
    SELECT
      `dim_ledgers`.`ledger_id` AS `ledger_id`,
      `dim_ledgers`.`dw_insert_date` AS `dw_insert_date`,
      `dim_ledgers`.`ledger_description` AS `ledger_description`,
      `dim_ledgers`.`ledger_name` AS `ledger_name`,
      `dim_ledgers`.`ledger_short_name` AS `ledger_short_name`,
      `dim_ledgers`.`ledger_category_code` AS `ledger_category_code`,
      `dim_ledgers`.`bal_seg_value_set_id` AS `bal_seg_value_set_id`,
      `dim_ledgers`.`chart_of_accounts_id` AS `chart_of_accounts_id`,
      `dim_ledgers`.`currency_code` AS `currency_code`,
      `dim_ledgers`.`accounted_period_type` AS `accounted_period_type`,
      `dim_ledgers`.`ret_earn_code_combination_id` AS `ret_earn_code_combination_id`,
      `dim_ledgers`.`daily_translation_rate_type` AS `daily_translation_rate_type`,
      `dim_ledgers`.`bal_seg_column_name` AS `bal_seg_column_name`,
      `dim_ledgers`.`is_deleted_flg` AS `is_deleted_flg`,
      `dim_ledgers`.`sla_description_language` AS `sla_description_language`,
      `dim_ledgers`.`period_set_name` AS `period_set_name`,
      `dim_ledgers`.`source_app_id` AS `source_app_id`,
      `dim_ledgers`.`dw_load_id` AS `dw_load_id`,
      `dim_ledgers`.`dw_update_date` AS `dw_update_date`,
      (
        `dim_ledgers`.`ledger_category_code` = 'PRIMARY'
      ) AS `$temp1`
    FROM `bec_dwh`.`dim_ledgers` AS `dim_ledgers`
  ) AS `t0`
    ON (
      (
        `fact_gl_account_analysis`.`ledger_id` = `t0`.`ledger_id`
      )
      AND (
        TRUE = `t0`.`$temp1`
      )
    )
);
UPDATE gold_bec_dwh.fact_gl_account_analysis SET Update_flg = 'N'
WHERE
  Update_flg = 'Y';
UPDATE bec_etl_ctrl.batch_dw_info SET last_refresh_date = CURRENT_TIMESTAMP()
WHERE
  dw_table_name = 'fact_gl_account_analysis_rt' AND batch_name = 'gl';