-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
--drop table bec_dwh.FACT_ASCP_FORECAST_SNP;
CREATE TABLE bec_dwh.fact_ascp_forecast_snp (
	organization_id numeric(15) ,
	inventory_item_id numeric(15) ,
	transaction_id numeric(15) ,
	part_number varchar(100) ,
	item_description varchar(2000) ,
	primary_uom_code varchar(10) ,
	bom_item_type_desc varchar(2000) ,
	ato_forecast_control_desc varchar(2000) ,
	mrp_planning_code_desc varchar(2000) ,
	pick_components_flag varchar(3) ,
	forecast_designator varchar(100) ,
	bucket_type numeric(15) ,
	forecast_date timestamp ,
	current_forecast_quantity numeric(28, 10) ,
	original_forecast_quantity numeric(28, 10) ,
	comments varchar(240) ,
	header_attribute1 varchar(150) ,
	line_attribute1 varchar(150) ,
	datestamp timestamp ,
	source_app_id int4,
	dw_load_id varchar(414),
	snp_date date
);
