-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
DROP TABLE bec_dwh.fact_ascp_horizontal_plan_snp;
CREATE TABLE IF NOT EXISTS bec_dwh.fact_ascp_horizontal_plan_snp
(
	inventory_item_id NUMERIC(15,0)   ENCODE az64
	,organization_id NUMERIC(15,0)   ENCODE az64
	,plan_id NUMERIC(15,0)   ENCODE az64
	,category_set_id NUMERIC(15,0)   ENCODE az64
	,sr_instance_id NUMERIC(15,0)   ENCODE az64
	,fill_kill_flag NUMERIC(15,0)   ENCODE az64
	,so_line_split NUMERIC(28,10)   ENCODE az64
	,quantity_rate NUMERIC(38,10)   ENCODE az64
	,new_due_date DATE   ENCODE az64
	,order_type_entity VARCHAR(2000)   ENCODE lzo
	,plan_id_key VARCHAR(33)   ENCODE lzo
	,organization_id_key VARCHAR(33)   ENCODE lzo
	,inventory_item_id_key VARCHAR(33)   ENCODE lzo
	,is_deleted_flg VARCHAR(1)   ENCODE lzo
	,source_app_id INTEGER   ENCODE az64
	,dw_load_id VARCHAR(180)   ENCODE lzo
	,snp_date DATE   ENCODE az64
	,plan_name_archive_date VARCHAR(2000)   ENCODE lzo
)
DISTSTYLE AUTO
;