/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents full load approach for RT reports.
# File Version: KPI v1.0
*/
begin;

drop table if exists bec_dwh_rpt.FACT_GL_ACCOUNT_ANALYSIS_RT;

create table bec_dwh_rpt.FACT_GL_ACCOUNT_ANALYSIS_RT 
	diststyle all as 
(
SELECT "fact_gl_account_analysis"."accounted_cr" AS "accounted_cr",
  "fact_gl_account_analysis"."accounted_dr" AS "accounted_dr",
  "t0"."accounted_period_type" AS "accounted_period_type",
  "fact_gl_account_analysis"."accounting_class_code" AS "accounting_class_code",
  "fact_gl_account_analysis"."accounting_class_name" AS "accounting_class_name",
  "fact_gl_account_analysis"."accounting_code_combination" AS "accounting_code_combination",
  "fact_gl_account_analysis"."accounting_sequence_name" AS "accounting_sequence_name",
  "fact_gl_account_analysis"."accounting_sequence_number" AS "accounting_sequence_number",
  "fact_gl_account_analysis"."accounting_sequence_version" AS "accounting_sequence_version",
  "fact_gl_account_analysis"."application_id" AS "application_id",
  "fact_gl_account_analysis"."application_name" AS "application_name",
  "fact_gl_account_analysis"."approver_name" AS "approver_name",
  "t0"."bal_seg_column_name" AS "bal_seg_column_name",
  "t0"."bal_seg_value_set_id" AS "bal_seg_value_set_id",
  "fact_gl_account_analysis"."balance_type" AS "balance_type",
  "fact_gl_account_analysis"."balance_type_code" AS "balance_type_code",
  "fact_gl_account_analysis"."balancing_segment" AS "balancing_segment",
  "fact_gl_account_analysis"."balancing_segment_desc" AS "balancing_segment_desc",
  "fact_gl_account_analysis"."be_project_desc" AS "be_project_desc",
  "fact_gl_account_analysis"."be_project_no" AS "be_project_no",
  "fact_gl_account_analysis"."be_task_desc" AS "be_task_desc",
  "fact_gl_account_analysis"."be_task_no" AS "be_task_no",
  "fact_gl_account_analysis"."begin_balance_cr" AS "begin_balance_cr",
  "fact_gl_account_analysis"."begin_balance_dr" AS "begin_balance_dr",
  "fact_gl_account_analysis"."begin_running_total_cr" AS "begin_running_total_cr",
  "fact_gl_account_analysis"."begin_running_total_dr" AS "begin_running_total_dr",
  "fact_gl_account_analysis"."budget_name" AS "budget_name",
  "t0"."chart_of_accounts_id" AS "chart_of_accounts_id (dim_ledgers)",
  "fact_gl_account_analysis"."code_combination_description" AS "code_combination_description",
  "fact_gl_account_analysis"."code_combination_id" AS "code_combination_id",
  "fact_gl_account_analysis"."code_combination_id_key" AS "code_combination_id_key",
  "fact_gl_account_analysis"."completed_date" AS "completed_date",
  "fact_gl_account_analysis"."control_account" AS "control_account",
  "fact_gl_account_analysis"."control_account_flag" AS "control_account_flag",
  "fact_gl_account_analysis"."conversion_rate" AS "conversion_rate",
  "fact_gl_account_analysis"."conversion_rate_date" AS "conversion_rate_date",
  "fact_gl_account_analysis"."conversion_rate_type" AS "conversion_rate_type",
  "fact_gl_account_analysis"."conversion_rate_type_code" AS "conversion_rate_type_code",
  "fact_gl_account_analysis"."cost_center_desc" AS "cost_center_desc",
  "fact_gl_account_analysis"."cost_center_segment" AS "cost_center_segment",
  "fact_gl_account_analysis"."created_by_id" AS "created_by_id",
  "fact_gl_account_analysis"."creation_date" AS "creation_date",
  "t0"."currency_code" AS "currency_code",
  "t0"."daily_translation_rate_type" AS "daily_translation_rate_type",
  "fact_gl_account_analysis"."document_category" AS "document_category",
  "fact_gl_account_analysis"."document_sequence_name" AS "document_sequence_name",
  "fact_gl_account_analysis"."document_sequence_number" AS "document_sequence_number",
  "t0"."dw_insert_date" AS "dw_insert_date (dim_ledgers)",
  "fact_gl_account_analysis"."dw_insert_date" AS "dw_insert_date",
  "t0"."dw_load_id" AS "dw_load_id (dim_ledgers)",
  "fact_gl_account_analysis"."dw_load_id" AS "dw_load_id",
  "t0"."dw_update_date" AS "dw_update_date (dim_ledgers)",
  "fact_gl_account_analysis"."dw_update_date" AS "dw_update_date",
  "fact_gl_account_analysis"."effective_date" AS "effective_date",
  "fact_gl_account_analysis"."encumbrance_type" AS "encumbrance_type",
  "fact_gl_account_analysis"."end_running_total_cr" AS "end_running_total_cr",
  "fact_gl_account_analysis"."end_running_total_dr" AS "end_running_total_dr",
  "fact_gl_account_analysis"."entered_cr" AS "entered_cr",
  "fact_gl_account_analysis"."entered_currency" AS "entered_currency",
  "fact_gl_account_analysis"."entered_dr" AS "entered_dr",
  "fact_gl_account_analysis"."event_class_code" AS "event_class_code",
  "fact_gl_account_analysis"."event_class_name" AS "event_class_name",
  "fact_gl_account_analysis"."event_date" AS "event_date",
  "fact_gl_account_analysis"."event_id" AS "event_id",
  "fact_gl_account_analysis"."event_number" AS "event_number",
  "fact_gl_account_analysis"."event_type_code" AS "event_type_code",
  "fact_gl_account_analysis"."event_type_name" AS "event_type_name",
  "fact_gl_account_analysis"."external_reference" AS "external_reference",
  "fact_gl_account_analysis"."fund_status" AS "fund_status",
  "fact_gl_account_analysis"."gl_batch_name" AS "gl_batch_name",
  "fact_gl_account_analysis"."gl_date" AS "gl_date",
  "fact_gl_account_analysis"."gl_je_name" AS "gl_je_name",
  "fact_gl_account_analysis"."gl_line_number" AS "gl_line_number",
  "fact_gl_account_analysis"."gl_transfer_date" AS "gl_transfer_date",
  CAST("fact_gl_account_analysis"."header_description" AS TEXT) AS "header_description",
  "fact_gl_account_analysis"."header_id" AS "header_id",
  "fact_gl_account_analysis"."intercompany_segment" AS "intercompany_segment",
  "fact_gl_account_analysis"."intercompany_segment_desc" AS "intercompany_segment_desc",
  "fact_gl_account_analysis"."invoice_id" AS "invoice_id",
  "fact_gl_account_analysis"."invoice_id_key" AS "invoice_id_key",
  "fact_gl_account_analysis"."invoice_num" AS "invoice_num",
  "t0"."is_deleted_flg" AS "is_deleted_flg (dim_ledgers)",
  "fact_gl_account_analysis"."is_deleted_flg" AS "is_deleted_flg",
  "fact_gl_account_analysis"."je_category" AS "je_category",
  "fact_gl_account_analysis"."je_category_key" AS "je_category_key",
  "fact_gl_account_analysis"."je_header_id" AS "je_header_id",
  "fact_gl_account_analysis"."je_header_id_key" AS "je_header_id_key",
  "fact_gl_account_analysis"."je_source_name" AS "je_source_name",
  "fact_gl_account_analysis"."last_update_date" AS "last_update_date",
  "fact_gl_account_analysis"."le_address_line_1" AS "le_address_line_1",
  "fact_gl_account_analysis"."le_address_line_2" AS "le_address_line_2",
  "fact_gl_account_analysis"."le_address_line_3" AS "le_address_line_3",
  "fact_gl_account_analysis"."le_br_accountant_name" AS "le_br_accountant_name",
  "fact_gl_account_analysis"."le_br_accountant_number" AS "le_br_accountant_number",
  "fact_gl_account_analysis"."le_br_daily_entity" AS "le_br_daily_entity",
  "fact_gl_account_analysis"."le_br_daily_inscription_date" AS "le_br_daily_inscription_date",
  "fact_gl_account_analysis"."le_br_daily_inscription_number" AS "le_br_daily_inscription_number",
  "fact_gl_account_analysis"."le_br_daily_location" AS "le_br_daily_location",
  "fact_gl_account_analysis"."le_br_director_number" AS "le_br_director_number",
  "fact_gl_account_analysis"."le_city" AS "le_city",
  "fact_gl_account_analysis"."le_country" AS "le_country",
  "fact_gl_account_analysis"."le_postal_code" AS "le_postal_code",
  "fact_gl_account_analysis"."le_region_1" AS "le_region_1",
  "fact_gl_account_analysis"."le_region_2" AS "le_region_2",
  "fact_gl_account_analysis"."le_region_3" AS "le_region_3",
  "fact_gl_account_analysis"."le_registration_effective_from" AS "le_registration_effective_from",
  "fact_gl_account_analysis"."le_registration_number" AS "le_registration_number",
  "t0"."ledger_category_code" AS "ledger_category_code",
  "fact_gl_account_analysis"."ledger_currency" AS "ledger_currency",
  "t0"."ledger_description" AS "ledger_description (dim_ledgers)",
  "fact_gl_account_analysis"."ledger_description" AS "ledger_description",
  "t0"."ledger_id" AS "ledger_id (dim_ledgers)",
  "fact_gl_account_analysis"."ledger_id" AS "ledger_id",
  "fact_gl_account_analysis"."ledger_id_key" AS "ledger_id_key",
  "t0"."ledger_name" AS "ledger_name (dim_ledgers)",
  "fact_gl_account_analysis"."ledger_name" AS "ledger_name",
  "t0"."ledger_short_name" AS "ledger_short_name (dim_ledgers)",
  "fact_gl_account_analysis"."ledger_short_name" AS "ledger_short_name",
  "fact_gl_account_analysis"."legal_entity_id" AS "legal_entity_id",
  "fact_gl_account_analysis"."legal_entity_id_key" AS "legal_entity_id_key",
  "fact_gl_account_analysis"."legal_entity_name" AS "legal_entity_name",
  CAST("fact_gl_account_analysis"."line_description" AS TEXT) AS "line_description",
  "fact_gl_account_analysis"."line_number" AS "line_number",
  "fact_gl_account_analysis"."management_segment" AS "management_segment",
  "fact_gl_account_analysis"."management_segment_desc" AS "management_segment_desc",
  "fact_gl_account_analysis"."natural_account_desc" AS "natural_account_desc",
  "fact_gl_account_analysis"."natural_account_segment" AS "natural_account_segment",
  "fact_gl_account_analysis"."orig_line_number" AS "orig_line_number",
  "fact_gl_account_analysis"."party_type" AS "party_type",
  "fact_gl_account_analysis"."party_type_code" AS "party_type_code",
  "fact_gl_account_analysis"."period_end_date" AS "period_end_date",
  "fact_gl_account_analysis"."period_name" AS "period_name",
  "fact_gl_account_analysis"."period_net_cr" AS "period_net_cr",
  "fact_gl_account_analysis"."period_net_dr" AS "period_net_dr",
  "fact_gl_account_analysis"."period_number" AS "period_number",
  "t0"."period_set_name" AS "period_set_name",
  "fact_gl_account_analysis"."period_start_date" AS "period_start_date",
  "fact_gl_account_analysis"."period_year" AS "period_year",
  "fact_gl_account_analysis"."po_number" AS "po_number",
  "fact_gl_account_analysis"."posted_date" AS "posted_date",
  "fact_gl_account_analysis"."reconciliation_reference" AS "reconciliation_reference",
  "fact_gl_account_analysis"."reference_date" AS "reference_date",
  "fact_gl_account_analysis"."reporting_sequence_name" AS "reporting_sequence_name",
  "fact_gl_account_analysis"."reporting_sequence_number" AS "reporting_sequence_number",
  "fact_gl_account_analysis"."reporting_sequence_version" AS "reporting_sequence_version",
  "t0"."ret_earn_code_combination_id" AS "ret_earn_code_combination_id",
  "fact_gl_account_analysis"."reversal_period" AS "reversal_period",
  "fact_gl_account_analysis"."reversal_status" AS "reversal_status",
  "fact_gl_account_analysis"."segment10" AS "segment10",
  "fact_gl_account_analysis"."segment1" AS "segment1",
  "fact_gl_account_analysis"."segment2" AS "segment2",
  "fact_gl_account_analysis"."segment3" AS "segment3",
  "fact_gl_account_analysis"."segment4" AS "segment4",
  "fact_gl_account_analysis"."segment5" AS "segment5",
  "fact_gl_account_analysis"."segment6" AS "segment6",
  "fact_gl_account_analysis"."segment7" AS "segment7",
  "fact_gl_account_analysis"."segment8" AS "segment8",
  "fact_gl_account_analysis"."segment9" AS "segment9",
  "t0"."sla_description_language" AS "sla_description_language",
  "t0"."source_app_id" AS "source_app_id (dim_ledgers)",
  "fact_gl_account_analysis"."source_app_id" AS "source_app_id",
  "fact_gl_account_analysis"."statistical_amount" AS "statistical_amount",
  "fact_gl_account_analysis"."temp_line_num" AS "temp_line_num",
  "fact_gl_account_analysis"."transaction_date" AS "transaction_date",
  "fact_gl_account_analysis"."transaction_number" AS "transaction_number",
  "fact_gl_account_analysis"."translated_flag" AS "translated_flag",
  "fact_gl_account_analysis"."unrounded_accounted_cr" AS "unrounded_accounted_cr",
  "fact_gl_account_analysis"."unrounded_accounted_dr" AS "unrounded_accounted_dr",
  "fact_gl_account_analysis"."vendor_id" AS "vendor_id",
  "fact_gl_account_analysis"."vendor_id_key" AS "vendor_id_key",
  "fact_gl_account_analysis"."vendor_site_id" AS "vendor_site_id",
decode("fact_gl_account_analysis"."approver_name",null, 'SYSADMIN'
  ,"fact_gl_account_analysis"."approver_name" )  as "user",
  nvl("fact_gl_account_analysis"."accounted_dr",0)-nvl("fact_gl_account_analysis"."accounted_cr",0) as net_amount,
  case when nvl("fact_gl_account_analysis"."accounted_dr",0) - nvl("fact_gl_account_analysis"."accounted_cr",0) = 0
  then 'Y' else 'N' end as "Include_Zero_Amount_Lines"
FROM "bec_dwh"."fact_gl_account_analysis" "fact_gl_account_analysis"
  INNER JOIN (
  SELECT "dim_ledgers"."ledger_id" AS "ledger_id",
    "dim_ledgers"."dw_insert_date" AS "dw_insert_date",
    "dim_ledgers"."ledger_description" AS "ledger_description",
    "dim_ledgers"."ledger_name" AS "ledger_name",
    "dim_ledgers"."ledger_short_name" AS "ledger_short_name",
    "dim_ledgers"."ledger_category_code" AS "ledger_category_code",
    "dim_ledgers"."bal_seg_value_set_id" AS "bal_seg_value_set_id",
    "dim_ledgers"."chart_of_accounts_id" AS "chart_of_accounts_id",
    "dim_ledgers"."currency_code" AS "currency_code",
    "dim_ledgers"."accounted_period_type" AS "accounted_period_type",
    "dim_ledgers"."ret_earn_code_combination_id" AS "ret_earn_code_combination_id",
    "dim_ledgers"."daily_translation_rate_type" AS "daily_translation_rate_type",
    "dim_ledgers"."bal_seg_column_name" AS "bal_seg_column_name",
    "dim_ledgers"."is_deleted_flg" AS "is_deleted_flg",
    "dim_ledgers"."sla_description_language" AS "sla_description_language",
    "dim_ledgers"."period_set_name" AS "period_set_name",
    "dim_ledgers"."source_app_id" AS "source_app_id",
    "dim_ledgers"."dw_load_id" AS "dw_load_id",
    "dim_ledgers"."dw_update_date" AS "dw_update_date",
    ("dim_ledgers"."ledger_category_code" = 'PRIMARY') AS "$temp1"
  FROM "bec_dwh"."dim_ledgers" "dim_ledgers"
) "t0" ON (("fact_gl_account_analysis"."ledger_id" = "t0"."ledger_id") AND (TRUE = "t0"."$temp1"))
);
end;

update
	bec_etl_ctrl.batch_dw_info
set
	load_type = 'I',
	last_refresh_date = getdate()
where
	dw_table_name = 'fact_gl_account_analysis_rt'
	and batch_name = 'gl';

commit;