/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.ap_supplier_sites_all
where vendor_site_id in (
select stg.vendor_site_id
from bec_ods.ap_supplier_sites_all ods, bec_ods_stg.ap_supplier_sites_all stg
where ods.vendor_site_id = stg.vendor_site_id
and stg.kca_operation IN ('INSERT','UPDATE')
);

commit;

-- Insert records

insert
	into
	bec_ods.ap_supplier_sites_all
(vendor_site_id,
	last_update_date,
	last_updated_by,
	vendor_id,
	vendor_site_code,
	vendor_site_code_alt,
	last_update_login,
	creation_date,
	created_by,
	purchasing_site_flag,
	rfq_only_site_flag,
	pay_site_flag,
	attention_ar_flag,
	address_line1,
	address_lines_alt,
	address_line2,
	address_line3,
	city,
	state,
	zip,
	province,
	country,
	area_code,
	phone,
	customer_num,
	ship_to_location_id,
	bill_to_location_id,
	ship_via_lookup_code,
	freight_terms_lookup_code,
	fob_lookup_code,
	inactive_date,
	fax,
	fax_area_code,
	telex,
	payment_method_lookup_code,
	bank_account_name,
	bank_account_num,
	bank_num,
	bank_account_type,
	terms_date_basis,
	current_catalog_num,
	vat_code,
	distribution_set_id,
	accts_pay_code_combination_id,
	prepay_code_combination_id,
	pay_group_lookup_code,
	payment_priority,
	terms_id,
	invoice_amount_limit,
	pay_date_basis_lookup_code,
	always_take_disc_flag,
	invoice_currency_code,
	payment_currency_code,
	hold_all_payments_flag,
	hold_future_payments_flag,
	hold_reason,
	hold_unmatched_invoices_flag,
	ap_tax_rounding_rule,
	auto_tax_calc_flag,
	auto_tax_calc_override,
	amount_includes_tax_flag,
	exclusive_payment_flag,
	tax_reporting_site_flag,
	attribute_category,
	attribute1,
	attribute2,
	attribute3,
	attribute4,
	attribute5,
	attribute6,
	attribute7,
	attribute8,
	attribute9,
	attribute10,
	attribute11,
	attribute12,
	attribute13,
	attribute14,
	attribute15,
	request_id,
	program_application_id,
	program_id,
	program_update_date,
	validation_number,
	exclude_freight_from_discount,
	vat_registration_num,
	offset_vat_code,
	org_id,
	check_digits,
	bank_number,
	address_line4,
	county,
	address_style,
	language,
	allow_awt_flag,
	awt_group_id,
	global_attribute1,
	global_attribute2,
	global_attribute3,
	global_attribute4,
	global_attribute5,
	global_attribute6,
	global_attribute7,
	global_attribute8,
	global_attribute9,
	global_attribute10,
	global_attribute11,
	global_attribute12,
	global_attribute13,
	global_attribute14,
	global_attribute15,
	global_attribute16,
	global_attribute17,
	global_attribute18,
	global_attribute19,
	global_attribute20,
	global_attribute_category,
	edi_transaction_handling,
	edi_id_number,
	edi_payment_method,
	edi_payment_format,
	edi_remittance_method,
	bank_charge_bearer,
	edi_remittance_instruction,
	bank_branch_type,
	pay_on_code,
	default_pay_site_id,
	pay_on_receipt_summary_code,
	tp_header_id,
	ece_tp_location_code,
	pcard_site_flag,
	match_option,
	country_of_origin_code,
	future_dated_payment_ccid,
	create_debit_memo_flag,
	offset_tax_flag,
	supplier_notif_method,
	email_address,
	remittance_email,
	primary_pay_site_flag,
	shipping_control,
	selling_company_identifier,
	gapless_inv_num_flag,
	duns_number,
	tolerance_id,
	location_id,
	party_site_id,
	services_tolerance_id,
	retainage_rate,
	tca_sync_state,
	tca_sync_province,
	tca_sync_county,
	tca_sync_city,
	tca_sync_zip,
	tca_sync_country,
	pay_awt_group_id,
	CAGE_CODE,
	LEGAL_BUSINESS_NAME,
	DOING_BUS_AS_NAME,
	DIVISION_NAME,
	SMALL_BUSINESS_CODE,
	CCR_COMMENTS,
	DEBARMENT_START_DATE,
	DEBARMENT_END_DATE,
	ACK_LEAD_TIME,
	"VAT_REGISTRATION_NUM#1",
	KCA_OPERATION,
	IS_DELETED_FLG,
	kca_seq_id,
	kca_seq_date)
(
	select
		vendor_site_id,
		last_update_date,
		last_updated_by,
		vendor_id,
		vendor_site_code,
		vendor_site_code_alt,
		last_update_login,
		creation_date,
		created_by,
		purchasing_site_flag,
		rfq_only_site_flag,
		pay_site_flag,
		attention_ar_flag,
		address_line1,
		address_lines_alt,
		address_line2,
		address_line3,
		city,
		state,
		zip,
		province,
		country,
		area_code,
		phone,
		customer_num,
		ship_to_location_id,
		bill_to_location_id,
		ship_via_lookup_code,
		freight_terms_lookup_code,
		fob_lookup_code,
		inactive_date,
		fax,
		fax_area_code,
		telex,
		payment_method_lookup_code,
		bank_account_name,
		bank_account_num,
		bank_num,
		bank_account_type,
		terms_date_basis,
		current_catalog_num,
		vat_code,
		distribution_set_id,
		accts_pay_code_combination_id,
		prepay_code_combination_id,
		pay_group_lookup_code,
		payment_priority,
		terms_id,
		invoice_amount_limit,
		pay_date_basis_lookup_code,
		always_take_disc_flag,
		invoice_currency_code,
		payment_currency_code,
		hold_all_payments_flag,
		hold_future_payments_flag,
		hold_reason,
		hold_unmatched_invoices_flag,
		ap_tax_rounding_rule,
		auto_tax_calc_flag,
		auto_tax_calc_override,
		amount_includes_tax_flag,
		exclusive_payment_flag,
		tax_reporting_site_flag,
		attribute_category,
		attribute1,
		attribute2,
		attribute3,
		attribute4,
		attribute5,
		attribute6,
		attribute7,
		attribute8,
		attribute9,
		attribute10,
		attribute11,
		attribute12,
		attribute13,
		attribute14,
		attribute15,
		request_id,
		program_application_id,
		program_id,
		program_update_date,
		validation_number,
		exclude_freight_from_discount,
		vat_registration_num,
		offset_vat_code,
		org_id,
		check_digits,
		bank_number,
		address_line4,
		county,
		address_style,
		language,
		allow_awt_flag,
		awt_group_id,
		global_attribute1,
		global_attribute2,
		global_attribute3,
		global_attribute4,
		global_attribute5,
		global_attribute6,
		global_attribute7,
		global_attribute8,
		global_attribute9,
		global_attribute10,
		global_attribute11,
		global_attribute12,
		global_attribute13,
		global_attribute14,
		global_attribute15,
		global_attribute16,
		global_attribute17,
		global_attribute18,
		global_attribute19,
		global_attribute20,
		global_attribute_category,
		edi_transaction_handling,
		edi_id_number,
		edi_payment_method,
		edi_payment_format,
		edi_remittance_method,
		bank_charge_bearer,
		edi_remittance_instruction,
		bank_branch_type,
		pay_on_code,
		default_pay_site_id,
		pay_on_receipt_summary_code,
		tp_header_id,
		ece_tp_location_code,
		pcard_site_flag,
		match_option,
		country_of_origin_code,
		future_dated_payment_ccid,
		create_debit_memo_flag,
		offset_tax_flag,
		supplier_notif_method,
		email_address,
		remittance_email,
		primary_pay_site_flag,
		shipping_control,
		selling_company_identifier,
		gapless_inv_num_flag,
		duns_number,
		tolerance_id,
		location_id,
		party_site_id,
		services_tolerance_id,
		retainage_rate,
		tca_sync_state,
		tca_sync_province,
		tca_sync_county,
		tca_sync_city,
		tca_sync_zip,
		tca_sync_country,
		pay_awt_group_id,
		CAGE_CODE,
		LEGAL_BUSINESS_NAME,
		DOING_BUS_AS_NAME,
		DIVISION_NAME,
		SMALL_BUSINESS_CODE,
		CCR_COMMENTS,
		DEBARMENT_START_DATE,
		DEBARMENT_END_DATE,
		ACK_LEAD_TIME,
		"VAT_REGISTRATION_NUM#1",
		KCA_OPERATION,
		'N' AS IS_DELETED_FLG,
		cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
	from
		bec_ods_stg.ap_supplier_sites_all
	where kca_operation IN ('INSERT','UPDATE') 
	and (vendor_site_id,KCA_SEQ_ID) in 
	(select vendor_site_id,max(KCA_SEQ_ID) from bec_ods_stg.ap_supplier_sites_all 
     where kca_operation IN ('INSERT','UPDATE')
     group by vendor_site_id)	
);

commit;

-- Soft delete
update bec_ods.ap_supplier_sites_all set IS_DELETED_FLG = 'N';
commit;
update bec_ods.ap_supplier_sites_all set IS_DELETED_FLG = 'Y'
where (vendor_site_id)  in
(
select vendor_site_id from bec_raw_dl_ext.ap_supplier_sites_all
where (vendor_site_id,KCA_SEQ_ID)
in 
(
select vendor_site_id,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.ap_supplier_sites_all
group by vendor_site_id
) 
and kca_operation= 'DELETE'
);
commit;


end;

update
	bec_etl_ctrl.batch_ods_info
set
	last_refresh_date = getdate()
where
	ods_table_name = 'ap_supplier_sites_all';

commit;