/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/


begin;


-- Delete Records

delete from bec_ods.AR_RECEIVABLES_TRX_ALL
where (RECEIVABLES_TRX_ID,nvl(org_id,0)) in (
select stg.RECEIVABLES_TRX_ID,nvl(stg.org_id,0)
from bec_ods.AR_RECEIVABLES_TRX_ALL ods, bec_ods_stg.AR_RECEIVABLES_TRX_ALL stg
where 
ods.RECEIVABLES_TRX_ID = stg.RECEIVABLES_TRX_ID  
and  nvl(ods.org_id,0) = nvl(stg.org_id,0)
and stg.kca_operation IN ('INSERT','UPDATE')
);

commit;

-- Insert records

INSERT INTO bec_ods.AR_RECEIVABLES_TRX_ALL (
ACCOUNTING_AFFECT_FLAG
,ASSET_TAX_CODE
,ATTRIBUTE1
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE_CATEGORY
,CODE_COMBINATION_ID
,CREATED_BY
,CREATION_DATE
,DEFAULT_ACCTG_DISTRIBUTION_SET
,DESCRIPTION
,END_DATE_ACTIVE
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE10
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE20
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE_CATEGORY
,GL_ACCOUNT_SOURCE
,INACTIVE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_DATE
,LAST_UPDATE_LOGIN
,LIABILITY_TAX_CODE
,NAME
,ORG_ID
,RECEIVABLES_TRX_ID
,RISK_ELIMINATION_DAYS
,SET_OF_BOOKS_ID
,START_DATE_ACTIVE
,STATUS
,TAX_CODE_SOURCE
,TAX_RECOVERABLE_FLAG
,TYPE
,ZD_EDITION_NAME
,ZD_SYNC
,IS_DELETED_FLG
,KCA_OPERATION
,KCA_SEQ_ID
,kca_seq_date
)
    SELECT
ACCOUNTING_AFFECT_FLAG
,ASSET_TAX_CODE
,ATTRIBUTE1
,ATTRIBUTE10
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE_CATEGORY
,CODE_COMBINATION_ID
,CREATED_BY
,CREATION_DATE
,DEFAULT_ACCTG_DISTRIBUTION_SET
,DESCRIPTION
,END_DATE_ACTIVE
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE10
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE20
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE_CATEGORY
,GL_ACCOUNT_SOURCE
,INACTIVE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_DATE
,LAST_UPDATE_LOGIN
,LIABILITY_TAX_CODE
,NAME
,ORG_ID
,RECEIVABLES_TRX_ID
,RISK_ELIMINATION_DAYS
,SET_OF_BOOKS_ID
,START_DATE_ACTIVE
,STATUS
,TAX_CODE_SOURCE
,TAX_RECOVERABLE_FLAG
,TYPE
,ZD_EDITION_NAME
,ZD_SYNC
,'N' AS IS_DELETED_FLG
,KCA_OPERATION
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
    FROM
        bec_ods_stg.AR_RECEIVABLES_TRX_ALL 
		where kca_operation IN ('INSERT','UPDATE')
	and (RECEIVABLES_TRX_ID,nvl(org_id,0) ,kca_seq_id) in 
	(select RECEIVABLES_TRX_ID,nvl(org_id,0)  ,max(kca_seq_id) from bec_ods_stg.AR_RECEIVABLES_TRX_ALL 
     where kca_operation IN ('INSERT','UPDATE')
     group by RECEIVABLES_TRX_ID ,nvl(org_id,0)  ) ;
	 
    commit ;
	
-- Soft delete
update bec_ods.AR_RECEIVABLES_TRX_ALL set IS_DELETED_FLG = 'N';
commit;
update bec_ods.AR_RECEIVABLES_TRX_ALL set IS_DELETED_FLG = 'Y'
where (RECEIVABLES_TRX_ID,nvl(org_id,0) )  in
(
select RECEIVABLES_TRX_ID,nvl(org_id,0) as org_id  from bec_raw_dl_ext.AR_RECEIVABLES_TRX_ALL
where (RECEIVABLES_TRX_ID,nvl(org_id,0) ,KCA_SEQ_ID)
in 
(
select RECEIVABLES_TRX_ID,nvl(org_id,0) as org_id ,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.AR_RECEIVABLES_TRX_ALL
group by RECEIVABLES_TRX_ID,nvl(org_id,0) 
) 
and kca_operation= 'DELETE'
);
commit;

 end;
update bec_etl_ctrl.batch_ods_info
set	last_refresh_date = getdate()
where ods_table_name = 'ar_receivables_trx_all';
 
