/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.CSF_DEBRIEF_LINES
where (nvl(DEBRIEF_LINE_ID,0)) in (
select nvl(stg.DEBRIEF_LINE_ID,0) as DEBRIEF_LINE_ID from bec_ods.CSF_DEBRIEF_LINES ods, bec_ods_stg.CSF_DEBRIEF_LINES stg
where nvl(ods.DEBRIEF_LINE_ID,0) = nvl(stg.DEBRIEF_LINE_ID,0) 
and stg.kca_operation IN ('INSERT','UPDATE')
);

commit;

-- Insert records

insert into	bec_ods.CSF_DEBRIEF_LINES
       (	
		DEBRIEF_LINE_ID, 
		DEBRIEF_HEADER_ID, 
		DEBRIEF_LINE_NUMBER, 
		SERVICE_DATE, 
		TXN_BILLING_TYPE_ID, 
		INVENTORY_ITEM_ID, 
		ISSUING_INVENTORY_ORG_ID, 
		RECEIVING_INVENTORY_ORG_ID, 
		ISSUING_SUB_INVENTORY_CODE, 
		RECEIVING_SUB_INVENTORY_CODE, 
		ISSUING_LOCATOR_ID, 
		RECEIVING_LOCATOR_ID, 
		PARENT_PRODUCT_ID, 
		REMOVED_PRODUCT_ID, 
		STATUS_OF_RECEIVED_PART, 
		ITEM_SERIAL_NUMBER, 
		ITEM_REVISION, 
		ITEM_LOTNUMBER, 
		UOM_CODE, 
		QUANTITY, 
		RMA_HEADER_ID, 
		DISPOSITION_CODE, 
		MATERIAL_REASON_CODE, 
		LABOR_REASON_CODE, 
		EXPENSE_REASON_CODE, 
		LABOR_START_DATE, 
		LABOR_END_DATE, 
		STARTING_MILEAGE, 
		ENDING_MILEAGE, 
		EXPENSE_AMOUNT, 
		CURRENCY_CODE, 
		DEBRIEF_LINE_STATUS_ID, 
		CHANNEL_CODE, 
		CHARGE_UPLOAD_STATUS, 
		CHARGE_UPLOAD_MSG_CODE, 
		CHARGE_UPLOAD_MESSAGE, 
		IB_UPDATE_STATUS, 
		IB_UPDATE_MSG_CODE, 
		IB_UPDATE_MESSAGE, 
		SPARE_UPDATE_STATUS, 
		SPARE_UPDATE_MSG_CODE, 
		SPARE_UPDATE_MESSAGE, 
		CREATED_BY, 
		CREATION_DATE, 
		LAST_UPDATED_BY, 
		LAST_UPDATE_DATE, 
		LAST_UPDATE_LOGIN, 
		ATTRIBUTE1, 
		ATTRIBUTE2, 
		ATTRIBUTE3, 
		ATTRIBUTE4, 
		ATTRIBUTE5, 
		ATTRIBUTE6, 
		ATTRIBUTE7, 
		ATTRIBUTE8, 
		ATTRIBUTE9, 
		ATTRIBUTE10, 
		ATTRIBUTE11, 
		ATTRIBUTE12, 
		ATTRIBUTE13, 
		ATTRIBUTE14, 
		ATTRIBUTE15, 
		ATTRIBUTE_CATEGORY, 
		SECURITY_GROUP_ID, 
		UPG_ORIG_SYSTEM_REF, 
		UPG_ORIG_SYSTEM_REF_ID, 
		BUSINESS_PROCESS_ID, 
		RETURN_REASON_CODE, 
		INSTANCE_ID, 
		STATISTICS_UPDATED, 
		ERROR_TEXT, 
		TRANSACTION_TYPE_ID, 
		RETURN_DATE, 
		OBJECT_VERSION_NUMBER, 
		ITEM_OPERATIONAL_STATUS_CODE, 
		MATERIAL_TRANSACTION_ID, 
		USAGE_TYPE, 
		RETURN_ORGANIZATION_ID, 
		RETURN_SUBINVENTORY_NAME, 
		CARRIER_CODE, 
		SHIPPING_METHOD, 
		SHIPPING_NUMBER, 
		WAYBILL, 
		EXPENDITURE_ORG_ID, 
		PROJECT_ID, 
		PROJECT_TASK_ID, 
        KCA_OPERATION,
        IS_DELETED_FLG,
		kca_seq_ID,
		kca_seq_date)	
(
	select
		DEBRIEF_LINE_ID, 
		DEBRIEF_HEADER_ID, 
		DEBRIEF_LINE_NUMBER, 
		SERVICE_DATE, 
		TXN_BILLING_TYPE_ID, 
		INVENTORY_ITEM_ID, 
		ISSUING_INVENTORY_ORG_ID, 
		RECEIVING_INVENTORY_ORG_ID, 
		ISSUING_SUB_INVENTORY_CODE, 
		RECEIVING_SUB_INVENTORY_CODE, 
		ISSUING_LOCATOR_ID, 
		RECEIVING_LOCATOR_ID, 
		PARENT_PRODUCT_ID, 
		REMOVED_PRODUCT_ID, 
		STATUS_OF_RECEIVED_PART, 
		ITEM_SERIAL_NUMBER, 
		ITEM_REVISION, 
		ITEM_LOTNUMBER, 
		UOM_CODE, 
		QUANTITY, 
		RMA_HEADER_ID, 
		DISPOSITION_CODE, 
		MATERIAL_REASON_CODE, 
		LABOR_REASON_CODE, 
		EXPENSE_REASON_CODE, 
		LABOR_START_DATE, 
		LABOR_END_DATE, 
		STARTING_MILEAGE, 
		ENDING_MILEAGE, 
		EXPENSE_AMOUNT, 
		CURRENCY_CODE, 
		DEBRIEF_LINE_STATUS_ID, 
		CHANNEL_CODE, 
		CHARGE_UPLOAD_STATUS, 
		CHARGE_UPLOAD_MSG_CODE, 
		CHARGE_UPLOAD_MESSAGE, 
		IB_UPDATE_STATUS, 
		IB_UPDATE_MSG_CODE, 
		IB_UPDATE_MESSAGE, 
		SPARE_UPDATE_STATUS, 
		SPARE_UPDATE_MSG_CODE, 
		SPARE_UPDATE_MESSAGE, 
		CREATED_BY, 
		CREATION_DATE, 
		LAST_UPDATED_BY, 
		LAST_UPDATE_DATE, 
		LAST_UPDATE_LOGIN, 
		ATTRIBUTE1, 
		ATTRIBUTE2, 
		ATTRIBUTE3, 
		ATTRIBUTE4, 
		ATTRIBUTE5, 
		ATTRIBUTE6, 
		ATTRIBUTE7, 
		ATTRIBUTE8, 
		ATTRIBUTE9, 
		ATTRIBUTE10, 
		ATTRIBUTE11, 
		ATTRIBUTE12, 
		ATTRIBUTE13, 
		ATTRIBUTE14, 
		ATTRIBUTE15, 
		ATTRIBUTE_CATEGORY, 
		SECURITY_GROUP_ID, 
		UPG_ORIG_SYSTEM_REF, 
		UPG_ORIG_SYSTEM_REF_ID, 
		BUSINESS_PROCESS_ID, 
		RETURN_REASON_CODE, 
		INSTANCE_ID, 
		STATISTICS_UPDATED, 
		ERROR_TEXT, 
		TRANSACTION_TYPE_ID, 
		RETURN_DATE, 
		OBJECT_VERSION_NUMBER, 
		ITEM_OPERATIONAL_STATUS_CODE, 
		MATERIAL_TRANSACTION_ID, 
		USAGE_TYPE, 
		RETURN_ORGANIZATION_ID, 
		RETURN_SUBINVENTORY_NAME, 
		CARRIER_CODE, 
		SHIPPING_METHOD, 
		SHIPPING_NUMBER, 
		WAYBILL, 
		EXPENDITURE_ORG_ID, 
		PROJECT_ID, 
		PROJECT_TASK_ID, 
        KCA_OPERATION,
       'N' AS IS_DELETED_FLG,
	    cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
	from bec_ods_stg.CSF_DEBRIEF_LINES
	where kca_operation IN ('INSERT','UPDATE') 
	and (nvl(DEBRIEF_LINE_ID,0),kca_seq_ID) in 
	(select nvl(DEBRIEF_LINE_ID,0) as DEBRIEF_LINE_ID,max(kca_seq_ID) as kca_seq_ID from bec_ods_stg.CSF_DEBRIEF_LINES 
     where kca_operation IN ('INSERT','UPDATE')
     group by nvl(DEBRIEF_LINE_ID,0))
);

commit;

-- Soft delete
update bec_ods.CSF_DEBRIEF_LINES set IS_DELETED_FLG = 'N';
commit;
update bec_ods.CSF_DEBRIEF_LINES set IS_DELETED_FLG = 'Y'
where (DEBRIEF_LINE_ID )  in
(
select DEBRIEF_LINE_ID  from bec_raw_dl_ext.CSF_DEBRIEF_LINES
where (DEBRIEF_LINE_ID ,KCA_SEQ_ID)
in 
(
select DEBRIEF_LINE_ID ,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.CSF_DEBRIEF_LINES
group by DEBRIEF_LINE_ID 
) 
and kca_operation= 'DELETE'
);
commit;


end;

update bec_etl_ctrl.batch_ods_info
set	last_refresh_date = getdate()
where ods_table_name = 'csf_debrief_lines';

commit;