/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.FA_BOOKS
where (nvl(TRANSACTION_HEADER_ID_IN,0)) in (
select nvl(stg.TRANSACTION_HEADER_ID_IN,0) as TRANSACTION_HEADER_ID_IN from bec_ods.FA_BOOKS ods, bec_ods_stg.FA_BOOKS stg
where nvl(ods.TRANSACTION_HEADER_ID_IN,0) = nvl(stg.TRANSACTION_HEADER_ID_IN,0) and stg.kca_operation IN ('INSERT','UPDATE')
);

commit;

-- Insert records

insert into	bec_ods.FA_BOOKS
       (	
		BOOK_TYPE_CODE, 
		ASSET_ID, 
		DATE_PLACED_IN_SERVICE, 
		DATE_EFFECTIVE, 
		DEPRN_START_DATE, 
		DEPRN_METHOD_CODE, 
		LIFE_IN_MONTHS, 
		RATE_ADJUSTMENT_FACTOR, 
		ADJUSTED_COST, 
		COST, 
		ORIGINAL_COST, 
		SALVAGE_VALUE, 
		PRORATE_CONVENTION_CODE, 
		PRORATE_DATE, 
		COST_CHANGE_FLAG, 
		ADJUSTMENT_REQUIRED_STATUS, 
		CAPITALIZE_FLAG, 
		RETIREMENT_PENDING_FLAG, 
		DEPRECIATE_FLAG, 
		LAST_UPDATE_DATE, 
		LAST_UPDATED_BY, 
		DATE_INEFFECTIVE, 
		TRANSACTION_HEADER_ID_IN, 
		TRANSACTION_HEADER_ID_OUT, 
		ITC_AMOUNT_ID, 
		ITC_AMOUNT,
		RETIREMENT_ID, 
		TAX_REQUEST_ID, 
		ITC_BASIS, 
		BASIC_RATE, 
		ADJUSTED_RATE, 
		BONUS_RULE, 
		CEILING_NAME, 
		RECOVERABLE_COST, 
		LAST_UPDATE_LOGIN, 
		ADJUSTED_CAPACITY, 
		FULLY_RSVD_REVALS_COUNTER, 
		IDLED_FLAG, 
		PERIOD_COUNTER_CAPITALIZED, 
		PERIOD_COUNTER_FULLY_RESERVED, 
		PERIOD_COUNTER_FULLY_RETIRED, 
		PRODUCTION_CAPACITY, 
		REVAL_AMORTIZATION_BASIS,  
		REVAL_CEILING, 
		UNIT_OF_MEASURE, 
		UNREVALUED_COST, 
		ANNUAL_DEPRN_ROUNDING_FLAG, 
		PERCENT_SALVAGE_VALUE, 
		ALLOWED_DEPRN_LIMIT, 
		ALLOWED_DEPRN_LIMIT_AMOUNT, 
		PERIOD_COUNTER_LIFE_COMPLETE, 
		ADJUSTED_RECOVERABLE_COST,
		ANNUAL_ROUNDING_FLAG, 
		GLOBAL_ATTRIBUTE1, 
		GLOBAL_ATTRIBUTE2, 
		GLOBAL_ATTRIBUTE3, 
		GLOBAL_ATTRIBUTE4, 
		GLOBAL_ATTRIBUTE5, 
		GLOBAL_ATTRIBUTE6, 
		GLOBAL_ATTRIBUTE7, 
		GLOBAL_ATTRIBUTE8, 
		GLOBAL_ATTRIBUTE9, 
		GLOBAL_ATTRIBUTE10, 
		GLOBAL_ATTRIBUTE11, 
		GLOBAL_ATTRIBUTE12, 
		GLOBAL_ATTRIBUTE13, 
		GLOBAL_ATTRIBUTE14, 
		GLOBAL_ATTRIBUTE15, 
		GLOBAL_ATTRIBUTE16, 
		GLOBAL_ATTRIBUTE17, 
		GLOBAL_ATTRIBUTE18, 
		GLOBAL_ATTRIBUTE19, 
		GLOBAL_ATTRIBUTE20, 
		GLOBAL_ATTRIBUTE_CATEGORY, 
		EOFY_ADJ_COST, 
		EOFY_FORMULA_FACTOR, 
		SHORT_FISCAL_YEAR_FLAG, 
		CONVERSION_DATE, 
		ORIGINAL_DEPRN_START_DATE, 
		REMAINING_LIFE1, 
		REMAINING_LIFE2, 
		OLD_ADJUSTED_COST, 
		FORMULA_FACTOR, 
		GROUP_ASSET_ID, 
		SALVAGE_TYPE, 
		DEPRN_LIMIT_TYPE, 
		REDUCTION_RATE,
		REDUCE_ADDITION_FLAG, 
		REDUCE_ADJUSTMENT_FLAG, 
		REDUCE_RETIREMENT_FLAG, 
		RECOGNIZE_GAIN_LOSS, 
		RECAPTURE_RESERVE_FLAG, 
		LIMIT_PROCEEDS_FLAG, 
		TERMINAL_GAIN_LOSS, 
		TRACKING_METHOD, 
		EXCLUDE_FULLY_RSV_FLAG, 
		EXCESS_ALLOCATION_OPTION, 
		DEPRECIATION_OPTION, 
		MEMBER_ROLLUP_FLAG, 
		ALLOCATE_TO_FULLY_RSV_FLAG, 
		ALLOCATE_TO_FULLY_RET_FLAG, 
		TERMINAL_GAIN_LOSS_AMOUNT, 
		CIP_COST, 
		YTD_PROCEEDS, 
		LTD_PROCEEDS, 
		LTD_COST_OF_REMOVAL, 
		EOFY_RESERVE, 
		PRIOR_EOFY_RESERVE,
		EOP_ADJ_COST, 
		EOP_FORMULA_FACTOR, 
		EXCLUDE_PROCEEDS_FROM_BASIS, 
		RETIREMENT_DEPRN_OPTION, 
		TERMINAL_GAIN_LOSS_FLAG, 
		SUPER_GROUP_ID, 
		OVER_DEPRECIATE_OPTION, 
		DISABLED_FLAG, 
		OLD_ADJUSTED_CAPACITY, 
		DRY_HOLE_FLAG, 
		CASH_GENERATING_UNIT_ID, 
		CONTRACT_ID,  
		RATE_IN_USE, 
		EXTENDED_DEPRN_FLAG, 
		EXTENDED_DEPRECIATION_PERIOD, 
		PERIOD_COUNTER_FULLY_EXTENDED, 
		NBV_AT_SWITCH,
		PRIOR_DEPRN_LIMIT_TYPE, 
		PRIOR_DEPRN_LIMIT_AMOUNT, 
		PRIOR_DEPRN_LIMIT, 
		PRIOR_DEPRN_METHOD, 
		PRIOR_LIFE_IN_MONTHS, 
		PRIOR_BASIC_RATE, 
		PRIOR_ADJUSTED_RATE,
        KCA_OPERATION,
        IS_DELETED_FLG,
		kca_seq_id,
		kca_seq_date)	
(
	select
		BOOK_TYPE_CODE, 
		ASSET_ID, 
		DATE_PLACED_IN_SERVICE, 
		DATE_EFFECTIVE, 
		DEPRN_START_DATE, 
		DEPRN_METHOD_CODE, 
		LIFE_IN_MONTHS, 
		RATE_ADJUSTMENT_FACTOR, 
		ADJUSTED_COST, 
		COST, 
		ORIGINAL_COST, 
		SALVAGE_VALUE, 
		PRORATE_CONVENTION_CODE, 
		PRORATE_DATE, 
		COST_CHANGE_FLAG, 
		ADJUSTMENT_REQUIRED_STATUS, 
		CAPITALIZE_FLAG, 
		RETIREMENT_PENDING_FLAG, 
		DEPRECIATE_FLAG, 
		LAST_UPDATE_DATE, 
		LAST_UPDATED_BY, 
		DATE_INEFFECTIVE, 
		TRANSACTION_HEADER_ID_IN, 
		TRANSACTION_HEADER_ID_OUT, 
		ITC_AMOUNT_ID, 
		ITC_AMOUNT,
		RETIREMENT_ID, 
		TAX_REQUEST_ID, 
		ITC_BASIS, 
		BASIC_RATE, 
		ADJUSTED_RATE, 
		BONUS_RULE, 
		CEILING_NAME, 
		RECOVERABLE_COST, 
		LAST_UPDATE_LOGIN, 
		ADJUSTED_CAPACITY, 
		FULLY_RSVD_REVALS_COUNTER, 
		IDLED_FLAG, 
		PERIOD_COUNTER_CAPITALIZED, 
		PERIOD_COUNTER_FULLY_RESERVED, 
		PERIOD_COUNTER_FULLY_RETIRED, 
		PRODUCTION_CAPACITY, 
		REVAL_AMORTIZATION_BASIS,  
		REVAL_CEILING, 
		UNIT_OF_MEASURE, 
		UNREVALUED_COST, 
		ANNUAL_DEPRN_ROUNDING_FLAG, 
		PERCENT_SALVAGE_VALUE, 
		ALLOWED_DEPRN_LIMIT, 
		ALLOWED_DEPRN_LIMIT_AMOUNT, 
		PERIOD_COUNTER_LIFE_COMPLETE, 
		ADJUSTED_RECOVERABLE_COST,
		ANNUAL_ROUNDING_FLAG, 
		GLOBAL_ATTRIBUTE1, 
		GLOBAL_ATTRIBUTE2, 
		GLOBAL_ATTRIBUTE3, 
		GLOBAL_ATTRIBUTE4, 
		GLOBAL_ATTRIBUTE5, 
		GLOBAL_ATTRIBUTE6, 
		GLOBAL_ATTRIBUTE7, 
		GLOBAL_ATTRIBUTE8, 
		GLOBAL_ATTRIBUTE9, 
		GLOBAL_ATTRIBUTE10, 
		GLOBAL_ATTRIBUTE11, 
		GLOBAL_ATTRIBUTE12, 
		GLOBAL_ATTRIBUTE13, 
		GLOBAL_ATTRIBUTE14, 
		GLOBAL_ATTRIBUTE15, 
		GLOBAL_ATTRIBUTE16, 
		GLOBAL_ATTRIBUTE17, 
		GLOBAL_ATTRIBUTE18, 
		GLOBAL_ATTRIBUTE19, 
		GLOBAL_ATTRIBUTE20, 
		GLOBAL_ATTRIBUTE_CATEGORY, 
		EOFY_ADJ_COST, 
		EOFY_FORMULA_FACTOR, 
		SHORT_FISCAL_YEAR_FLAG, 
		CONVERSION_DATE, 
		ORIGINAL_DEPRN_START_DATE, 
		REMAINING_LIFE1, 
		REMAINING_LIFE2, 
		OLD_ADJUSTED_COST, 
		FORMULA_FACTOR, 
		GROUP_ASSET_ID, 
		SALVAGE_TYPE, 
		DEPRN_LIMIT_TYPE, 
		REDUCTION_RATE,
		REDUCE_ADDITION_FLAG, 
		REDUCE_ADJUSTMENT_FLAG, 
		REDUCE_RETIREMENT_FLAG, 
		RECOGNIZE_GAIN_LOSS, 
		RECAPTURE_RESERVE_FLAG, 
		LIMIT_PROCEEDS_FLAG, 
		TERMINAL_GAIN_LOSS, 
		TRACKING_METHOD, 
		EXCLUDE_FULLY_RSV_FLAG, 
		EXCESS_ALLOCATION_OPTION, 
		DEPRECIATION_OPTION, 
		MEMBER_ROLLUP_FLAG, 
		ALLOCATE_TO_FULLY_RSV_FLAG, 
		ALLOCATE_TO_FULLY_RET_FLAG, 
		TERMINAL_GAIN_LOSS_AMOUNT, 
		CIP_COST, 
		YTD_PROCEEDS, 
		LTD_PROCEEDS, 
		LTD_COST_OF_REMOVAL, 
		EOFY_RESERVE, 
		PRIOR_EOFY_RESERVE,
		EOP_ADJ_COST, 
		EOP_FORMULA_FACTOR, 
		EXCLUDE_PROCEEDS_FROM_BASIS, 
		RETIREMENT_DEPRN_OPTION, 
		TERMINAL_GAIN_LOSS_FLAG, 
		SUPER_GROUP_ID, 
		OVER_DEPRECIATE_OPTION, 
		DISABLED_FLAG, 
		OLD_ADJUSTED_CAPACITY, 
		DRY_HOLE_FLAG, 
		CASH_GENERATING_UNIT_ID, 
		CONTRACT_ID,  
		RATE_IN_USE, 
		EXTENDED_DEPRN_FLAG, 
		EXTENDED_DEPRECIATION_PERIOD, 
		PERIOD_COUNTER_FULLY_EXTENDED, 
		NBV_AT_SWITCH,
		PRIOR_DEPRN_LIMIT_TYPE, 
		PRIOR_DEPRN_LIMIT_AMOUNT, 
		PRIOR_DEPRN_LIMIT, 
		PRIOR_DEPRN_METHOD, 
		PRIOR_LIFE_IN_MONTHS, 
		PRIOR_BASIC_RATE, 
		PRIOR_ADJUSTED_RATE,
        KCA_OPERATION,
       'N' AS IS_DELETED_FLG,
	    cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
		kca_seq_date
	from bec_ods_stg.FA_BOOKS
	where kca_operation IN ('INSERT','UPDATE') 
	and (nvl(TRANSACTION_HEADER_ID_IN,0),kca_seq_id) in 
	(select nvl(TRANSACTION_HEADER_ID_IN,0) as TRANSACTION_HEADER_ID_IN,max(kca_seq_id) from bec_ods_stg.FA_BOOKS 
     where kca_operation IN ('INSERT','UPDATE')
     group by nvl(TRANSACTION_HEADER_ID_IN,0))
);

commit;

-- Soft delete
update bec_ods.FA_BOOKS set IS_DELETED_FLG = 'N';
commit;
update bec_ods.FA_BOOKS set IS_DELETED_FLG = 'Y'
where (TRANSACTION_HEADER_ID_IN)  in
(
select TRANSACTION_HEADER_ID_IN from bec_raw_dl_ext.FA_BOOKS
where (TRANSACTION_HEADER_ID_IN,KCA_SEQ_ID)
in 
(
select TRANSACTION_HEADER_ID_IN,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.FA_BOOKS
group by TRANSACTION_HEADER_ID_IN
) 
and kca_operation= 'DELETE'
);
commit;

end;

update bec_etl_ctrl.batch_ods_info
set	last_refresh_date = getdate()
where ods_table_name = 'fa_books';

commit;