/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.GL_LEDGER_RELATIONSHIPS
where (RELATIONSHIP_ID) in (
select stg.RELATIONSHIP_ID from bec_ods.GL_LEDGER_RELATIONSHIPS ods, bec_ods_stg.GL_LEDGER_RELATIONSHIPS stg
where ods.RELATIONSHIP_ID = stg.RELATIONSHIP_ID and stg.kca_operation IN ('INSERT','UPDATE')
);

commit;

-- Insert records

insert into	bec_ods.GL_LEDGER_RELATIONSHIPS
(
 RELATIONSHIP_ID,
 SOURCE_LEDGER_ID, 
 TARGET_LEDGER_ID,
 SLA_LEDGER_ID, 
 PRIMARY_LEDGER_ID,
 TARGET_CURRENCY_CODE,
 TARGET_LEDGER_NAME, 
 TARGET_LEDGER_SHORT_NAME,
 TARGET_LEDGER_CATEGORY_CODE, 
 RELATIONSHIP_TYPE_CODE,
 RELATIONSHIP_ENABLED_FLAG,
 INHERIT_CREATION_USER_FLAG,
 LAST_UPDATE_DATE, 
 LAST_UPDATED_BY, 
 CREATION_DATE, 
 CREATED_BY, 
 LAST_UPDATE_LOGIN,
 GL_JE_CONVERSION_SET_ID, 
 SL_COA_MAPPING_ID,
 AUTOMATIC_POST_FLAG, 
 ALC_DEFAULT_CONV_RATE_TYPE,
 ALC_NO_RATE_ACTION_CODE,
 ALC_MAX_DAYS_ROLL_RATE, 
 ALC_INHERIT_CONVERSION_TYPE,
 ALC_INIT_CONV_OPTION_CODE,
 ALC_INIT_PERIOD,
 ALC_INIT_DATE, 
 ALC_INITIALIZING_RATE_DATE,
 ALC_INITIALIZING_RATE_TYPE,
 ALC_PERIOD_AVERAGE_RATE_TYPE, 
 ALC_PERIOD_END_RATE_TYPE,
 APPLICATION_ID, 
 ORG_ID, 
 DISABLE_CONVERSION_DATE,
 STATUS_CODE, 
 HIST_CONV_STATUS_CODE,
 KCA_OPERATION,
 IS_DELETED_FLG,
 kca_seq_id,
	kca_seq_date
)

(SELECT
 RELATIONSHIP_ID,
 SOURCE_LEDGER_ID, 
 TARGET_LEDGER_ID,
 SLA_LEDGER_ID, 
 PRIMARY_LEDGER_ID,
 TARGET_CURRENCY_CODE,
 TARGET_LEDGER_NAME, 
 TARGET_LEDGER_SHORT_NAME,
 TARGET_LEDGER_CATEGORY_CODE, 
 RELATIONSHIP_TYPE_CODE,
 RELATIONSHIP_ENABLED_FLAG,
 INHERIT_CREATION_USER_FLAG,
 LAST_UPDATE_DATE, 
 LAST_UPDATED_BY, 
 CREATION_DATE, 
 CREATED_BY, 
 LAST_UPDATE_LOGIN,
 GL_JE_CONVERSION_SET_ID, 
 SL_COA_MAPPING_ID,
 AUTOMATIC_POST_FLAG, 
 ALC_DEFAULT_CONV_RATE_TYPE,
 ALC_NO_RATE_ACTION_CODE,
 ALC_MAX_DAYS_ROLL_RATE, 
 ALC_INHERIT_CONVERSION_TYPE,
 ALC_INIT_CONV_OPTION_CODE,
 ALC_INIT_PERIOD,
 ALC_INIT_DATE, 
 ALC_INITIALIZING_RATE_DATE,
 ALC_INITIALIZING_RATE_TYPE,
 ALC_PERIOD_AVERAGE_RATE_TYPE, 
 ALC_PERIOD_END_RATE_TYPE,
 APPLICATION_ID, 
 ORG_ID, 
 DISABLE_CONVERSION_DATE,
 STATUS_CODE, 
 HIST_CONV_STATUS_CODE,
 KCA_OPERATION,
 'N' AS IS_DELETED_FLG,
cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
	kca_seq_date
from
	bec_ods_stg.GL_LEDGER_RELATIONSHIPS
where kca_operation IN ('INSERT','UPDATE') 
	and (RELATIONSHIP_ID,kca_seq_id) in 
	(select RELATIONSHIP_ID,max(kca_seq_id) from bec_ods_stg.GL_LEDGER_RELATIONSHIPS 
     where kca_operation IN ('INSERT','UPDATE')
     group by RELATIONSHIP_ID)
);
	
commit;
-- Soft delete
update bec_ods.GL_LEDGER_RELATIONSHIPS set IS_DELETED_FLG = 'N';
commit;
update bec_ods.GL_LEDGER_RELATIONSHIPS set IS_DELETED_FLG = 'Y'
where (RELATIONSHIP_ID)  in
(
select RELATIONSHIP_ID from bec_raw_dl_ext.GL_LEDGER_RELATIONSHIPS
where (RELATIONSHIP_ID,KCA_SEQ_ID)
in 
(
select RELATIONSHIP_ID,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.GL_LEDGER_RELATIONSHIPS
group by RELATIONSHIP_ID
) 
and kca_operation= 'DELETE'
);
commit;

end;

update
	bec_etl_ctrl.batch_ods_info
set
	last_refresh_date = getdate()
where
	ods_table_name = 'gl_ledger_relationships';

commit;