/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.pa_tasks
where TASK_ID in (
select stg.TASK_ID from bec_ods.pa_tasks ods, bec_ods_stg.pa_tasks stg
where ods.TASK_ID = stg.TASK_ID and stg.kca_operation in ('INSERT','UPDATE'));

commit;

-- Insert records

insert into bec_ods.pa_tasks
(TASK_ID
,PROJECT_ID
,TASK_NUMBER
,CREATION_DATE
,CREATED_BY
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,LAST_UPDATE_LOGIN
,TASK_NAME
,TOP_TASK_ID
,WBS_LEVEL
,READY_TO_BILL_FLAG
,READY_TO_DISTRIBUTE_FLAG
,PARENT_TASK_ID
,DESCRIPTION
,CARRYING_OUT_ORGANIZATION_ID
,SERVICE_TYPE_CODE
,TASK_MANAGER_PERSON_ID
,CHARGEABLE_FLAG
,BILLABLE_FLAG
,LIMIT_TO_TXN_CONTROLS_FLAG
,START_DATE
,COMPLETION_DATE
,ADDRESS_ID
,LABOR_BILL_RATE_ORG_ID
,LABOR_STD_BILL_RATE_SCHDL
,LABOR_SCHEDULE_FIXED_DATE
,LABOR_SCHEDULE_DISCOUNT
,NON_LABOR_BILL_RATE_ORG_ID
,NON_LABOR_STD_BILL_RATE_SCHDL
,NON_LABOR_SCHEDULE_FIXED_DATE
,NON_LABOR_SCHEDULE_DISCOUNT
,LABOR_COST_MULTIPLIER_NAME
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,COST_IND_RATE_SCH_ID
,REV_IND_RATE_SCH_ID
,INV_IND_RATE_SCH_ID
,COST_IND_SCH_FIXED_DATE
,REV_IND_SCH_FIXED_DATE
,INV_IND_SCH_FIXED_DATE
,LABOR_SCH_TYPE
,NON_LABOR_SCH_TYPE
,OVR_COST_IND_RATE_SCH_ID
,OVR_INV_IND_RATE_SCH_ID
,OVR_REV_IND_RATE_SCH_ID
,PM_PRODUCT_CODE
,PM_TASK_REFERENCE
,ACTUAL_START_DATE
,ACTUAL_FINISH_DATE
,EARLY_START_DATE
,EARLY_FINISH_DATE
,LATE_START_DATE
,LATE_FINISH_DATE
,SCHEDULED_START_DATE
,SCHEDULED_FINISH_DATE
,ADW_NOTIFY_FLAG
,ALLOW_CROSS_CHARGE_FLAG
,PROJECT_RATE_DATE
,PROJECT_RATE_TYPE
,CC_PROCESS_LABOR_FLAG
,LABOR_TP_SCHEDULE_ID
,LABOR_TP_FIXED_DATE
,CC_PROCESS_NL_FLAG
,NL_TP_SCHEDULE_ID
,NL_TP_FIXED_DATE
,RECEIVE_PROJECT_INVOICE_FLAG
,WORK_TYPE_ID
,RECORD_VERSION_NUMBER
,JOB_BILL_RATE_SCHEDULE_ID
,EMP_BILL_RATE_SCHEDULE_ID
,TASKFUNC_COST_RATE_TYPE
,TASKFUNC_COST_RATE_DATE
,NON_LAB_STD_BILL_RT_SCH_ID
,LABOR_DISC_REASON_CODE
,NON_LABOR_DISC_REASON_CODE
,LONG_TASK_NAME
,RETIREMENT_COST_FLAG
,CINT_ELIGIBLE_FLAG
,CINT_STOP_DATE
,REVENUE_ACCRUAL_METHOD
,INVOICE_METHOD
,CUSTOMER_ID
,GEN_ETC_SOURCE_CODE
,BILL_SCHE_OVRD_FLAG
,ADJ_ON_STD_INV
,ALT_LIQUIDATION_RATE_PER
,BILL_GROUP_ID
,COST_PLUS_FIXED_FEE_FLAG
,FEE_PERCENTAGE
,FEE_RATE
,FEE_RATE_SCHEDULE_ID
,FEE_REVENUE_SCHEDULE_ID
,IC_LABOR_TP_FIXED_DATE
,IC_LABOR_TP_SCHEDULE_ID
,IC_NL_TP_FIXED_DATE
,IC_NL_TP_SCHEDULE_ID
,INV_LINE_GROUP
,LIQUIDATION_RATE_PERCENTAGE
,OVR_FEE_RATE_SCHEDULE_ID
,PROGRESS_PAYMENT_FLAG
,RATE_PERCENTAGE
,RETENTION_PERCENTAGE
,SUBCONTRACT_FLAG
,WITHHOLD_AMOUNT
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date)
(
select TASK_ID,
PROJECT_ID,
TASK_NUMBER,
CREATION_DATE,
CREATED_BY,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_LOGIN,
TASK_NAME,
TOP_TASK_ID,
WBS_LEVEL,
READY_TO_BILL_FLAG,
READY_TO_DISTRIBUTE_FLAG,
PARENT_TASK_ID,
DESCRIPTION,
CARRYING_OUT_ORGANIZATION_ID,
SERVICE_TYPE_CODE,
TASK_MANAGER_PERSON_ID,
CHARGEABLE_FLAG,
BILLABLE_FLAG,
LIMIT_TO_TXN_CONTROLS_FLAG,
START_DATE,
COMPLETION_DATE,
ADDRESS_ID,
LABOR_BILL_RATE_ORG_ID,
LABOR_STD_BILL_RATE_SCHDL,
LABOR_SCHEDULE_FIXED_DATE,
LABOR_SCHEDULE_DISCOUNT,
NON_LABOR_BILL_RATE_ORG_ID,
NON_LABOR_STD_BILL_RATE_SCHDL,
NON_LABOR_SCHEDULE_FIXED_DATE,
NON_LABOR_SCHEDULE_DISCOUNT,
LABOR_COST_MULTIPLIER_NAME,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
COST_IND_RATE_SCH_ID,
REV_IND_RATE_SCH_ID,
INV_IND_RATE_SCH_ID,
COST_IND_SCH_FIXED_DATE,
REV_IND_SCH_FIXED_DATE,
INV_IND_SCH_FIXED_DATE,
LABOR_SCH_TYPE,
NON_LABOR_SCH_TYPE,
OVR_COST_IND_RATE_SCH_ID,
OVR_INV_IND_RATE_SCH_ID,
OVR_REV_IND_RATE_SCH_ID,
PM_PRODUCT_CODE,
PM_TASK_REFERENCE,
ACTUAL_START_DATE,
ACTUAL_FINISH_DATE,
EARLY_START_DATE,
EARLY_FINISH_DATE,
LATE_START_DATE,
LATE_FINISH_DATE,
SCHEDULED_START_DATE,
SCHEDULED_FINISH_DATE,
ADW_NOTIFY_FLAG,
ALLOW_CROSS_CHARGE_FLAG,
PROJECT_RATE_DATE,
PROJECT_RATE_TYPE,
CC_PROCESS_LABOR_FLAG,
LABOR_TP_SCHEDULE_ID,
LABOR_TP_FIXED_DATE,
CC_PROCESS_NL_FLAG,
NL_TP_SCHEDULE_ID,
NL_TP_FIXED_DATE,
RECEIVE_PROJECT_INVOICE_FLAG,
WORK_TYPE_ID,
RECORD_VERSION_NUMBER,
JOB_BILL_RATE_SCHEDULE_ID,
EMP_BILL_RATE_SCHEDULE_ID,
TASKFUNC_COST_RATE_TYPE,
TASKFUNC_COST_RATE_DATE,
NON_LAB_STD_BILL_RT_SCH_ID,
LABOR_DISC_REASON_CODE,
NON_LABOR_DISC_REASON_CODE,
LONG_TASK_NAME,
RETIREMENT_COST_FLAG,
CINT_ELIGIBLE_FLAG,
CINT_STOP_DATE,
REVENUE_ACCRUAL_METHOD,
INVOICE_METHOD,
CUSTOMER_ID,
GEN_ETC_SOURCE_CODE,
BILL_SCHE_OVRD_FLAG,
ADJ_ON_STD_INV,
ALT_LIQUIDATION_RATE_PER,
BILL_GROUP_ID,
COST_PLUS_FIXED_FEE_FLAG,
FEE_PERCENTAGE,
FEE_RATE,
FEE_RATE_SCHEDULE_ID,
FEE_REVENUE_SCHEDULE_ID,
IC_LABOR_TP_FIXED_DATE,
IC_LABOR_TP_SCHEDULE_ID,
IC_NL_TP_FIXED_DATE,
IC_NL_TP_SCHEDULE_ID,
INV_LINE_GROUP,
LIQUIDATION_RATE_PERCENTAGE,
OVR_FEE_RATE_SCHEDULE_ID,
PROGRESS_PAYMENT_FLAG,
RATE_PERCENTAGE,
RETENTION_PERCENTAGE,
SUBCONTRACT_FLAG,
WITHHOLD_AMOUNT,
KCA_OPERATION,
'N' AS IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
  KCA_SEQ_DATE
from bec_ods_stg.pa_tasks
where kca_operation in ('INSERT','UPDATE') and (TASK_ID,kca_seq_id) in (select TASK_ID,max(kca_seq_id) from bec_ods_stg.pa_tasks 
where kca_operation in ('INSERT','UPDATE')
group by TASK_ID)
);

commit;

-- Soft delete
update bec_ods.pa_tasks set IS_DELETED_FLG = 'N';
commit;
update bec_ods.pa_tasks set IS_DELETED_FLG = 'Y'
where (TASK_ID)  in
(
select TASK_ID from bec_raw_dl_ext.pa_tasks
where (TASK_ID,KCA_SEQ_ID)
in 
(
select TASK_ID,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.pa_tasks
group by TASK_ID
) 
and kca_operation= 'DELETE'
);
commit;

end;


update bec_etl_ctrl.batch_ods_info set last_refresh_date = getdate() where ods_table_name='pa_tasks';
commit;