/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.po_lines_all
where PO_LINE_ID in (
select stg.PO_LINE_ID from bec_ods.po_lines_all ods, bec_ods_stg.po_lines_all stg
where ods.PO_LINE_ID = stg.PO_LINE_ID and stg.kca_operation in ('INSERT','UPDATE'));

commit;

-- Insert records

insert into bec_ods.po_lines_all
(PO_LINE_ID
,LAST_UPDATE_DATE
,LAST_UPDATED_BY
,PO_HEADER_ID
,LINE_TYPE_ID
,LINE_NUM
,LAST_UPDATE_LOGIN
,CREATION_DATE
,CREATED_BY
,ITEM_ID
,ITEM_REVISION
,CATEGORY_ID
,ITEM_DESCRIPTION
,UNIT_MEAS_LOOKUP_CODE
,QUANTITY_COMMITTED
,COMMITTED_AMOUNT
,ALLOW_PRICE_OVERRIDE_FLAG
,NOT_TO_EXCEED_PRICE
,LIST_PRICE_PER_UNIT
,UNIT_PRICE
,QUANTITY
,UN_NUMBER_ID
,HAZARD_CLASS_ID
,NOTE_TO_VENDOR
,FROM_HEADER_ID
,FROM_LINE_ID
,MIN_ORDER_QUANTITY
,MAX_ORDER_QUANTITY
,QTY_RCV_TOLERANCE
,OVER_TOLERANCE_ERROR_FLAG
,MARKET_PRICE
,UNORDERED_FLAG
,CLOSED_FLAG
,USER_HOLD_FLAG
,CANCEL_FLAG
,CANCELLED_BY
,CANCEL_DATE
,CANCEL_REASON
,FIRM_STATUS_LOOKUP_CODE
,FIRM_DATE
,VENDOR_PRODUCT_NUM
,CONTRACT_NUM
,TAXABLE_FLAG
,TAX_NAME
,TYPE_1099
,CAPITAL_EXPENSE_FLAG
,NEGOTIATED_BY_PREPARER_FLAG
,ATTRIBUTE_CATEGORY
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE6
,ATTRIBUTE7
,ATTRIBUTE8
,ATTRIBUTE9
,ATTRIBUTE10
,REFERENCE_NUM
,ATTRIBUTE11
,ATTRIBUTE12
,ATTRIBUTE13
,ATTRIBUTE14
,ATTRIBUTE15
,MIN_RELEASE_AMOUNT
,PRICE_TYPE_LOOKUP_CODE
,CLOSED_CODE
,PRICE_BREAK_LOOKUP_CODE
,USSGL_TRANSACTION_CODE
,GOVERNMENT_CONTEXT
,REQUEST_ID
,PROGRAM_APPLICATION_ID
,PROGRAM_ID
,PROGRAM_UPDATE_DATE
,CLOSED_DATE
,CLOSED_REASON
,CLOSED_BY
,TRANSACTION_REASON_CODE
,ORG_ID
,QC_GRADE
,BASE_UOM
,BASE_QTY
,SECONDARY_UOM
,SECONDARY_QTY
,GLOBAL_ATTRIBUTE_CATEGORY
,GLOBAL_ATTRIBUTE1
,GLOBAL_ATTRIBUTE2
,GLOBAL_ATTRIBUTE3
,GLOBAL_ATTRIBUTE4
,GLOBAL_ATTRIBUTE5
,GLOBAL_ATTRIBUTE6
,GLOBAL_ATTRIBUTE7
,GLOBAL_ATTRIBUTE8
,GLOBAL_ATTRIBUTE9
,GLOBAL_ATTRIBUTE10
,GLOBAL_ATTRIBUTE11
,GLOBAL_ATTRIBUTE12
,GLOBAL_ATTRIBUTE13
,GLOBAL_ATTRIBUTE14
,GLOBAL_ATTRIBUTE15
,GLOBAL_ATTRIBUTE16
,GLOBAL_ATTRIBUTE17
,GLOBAL_ATTRIBUTE18
,GLOBAL_ATTRIBUTE19
,GLOBAL_ATTRIBUTE20
,LINE_REFERENCE_NUM
,PROJECT_ID
,TASK_ID
,EXPIRATION_DATE
,TAX_CODE_ID
,OKE_CONTRACT_HEADER_ID
,OKE_CONTRACT_VERSION_ID
,SECONDARY_QUANTITY
,SECONDARY_UNIT_OF_MEASURE
,PREFERRED_GRADE
,AUCTION_HEADER_ID
,AUCTION_DISPLAY_NUMBER
,AUCTION_LINE_NUMBER
,BID_NUMBER
,BID_LINE_NUMBER
,RETROACTIVE_DATE
,SUPPLIER_REF_NUMBER
,CONTRACT_ID
,START_DATE
,AMOUNT
,JOB_ID
,CONTRACTOR_FIRST_NAME
,CONTRACTOR_LAST_NAME
,FROM_LINE_LOCATION_ID
,ORDER_TYPE_LOOKUP_CODE
,PURCHASE_BASIS
,MATCHING_BASIS
,SVC_AMOUNT_NOTIF_SENT
,SVC_COMPLETION_NOTIF_SENT
,BASE_UNIT_PRICE
,MANUAL_PRICE_CHANGE_FLAG
,RETAINAGE_RATE
,MAX_RETAINAGE_AMOUNT
,PROGRESS_PAYMENT_RATE
,RECOUPMENT_RATE
,CATALOG_NAME
,SUPPLIER_PART_AUXID
,IP_CATEGORY_ID
,TAX_ATTRIBUTE_UPDATE_CODE
,LAST_UPDATED_PROGRAM,
	group_line_id,
	line_num_display,
	clm_info_flag,
	clm_option_indicator,
	clm_base_line_num,
	clm_option_num,
	clm_option_from_date,
	clm_option_to_date,
	clm_funded_flag,
	contract_type,
	cost_constraint,
	clm_idc_type,
	uda_template_id,
	user_document_status,
	draft_id,
	clm_exercised_flag,
	clm_exercised_date,
	clm_min_total_amount,
	clm_max_total_amount,
	clm_min_total_quantity,
	clm_max_total_quantity,
	clm_min_order_amount,
	clm_max_order_amount,
	clm_min_order_quantity,
	clm_max_order_quantity,
	clm_total_amount_ordered,
	clm_total_quantity_ordered,
	clm_fsc_psc,
	clm_mdaps_mais,
	clm_naics,
	clm_order_start_date,
	clm_order_end_date,
	revision_num,
	clm_approved_undef_amount,
	clm_delivery_event_code,
	clm_exhibit_name,
	clm_payment_instr_code,
	clm_pop_exception_reason,
	clm_uda_pricing_total,
	clm_undef_action_code,
	clm_undef_flag,
	schedules_required_flag,
	"cancel_reason#1",
	"closed_reason#1"
	--igt_line_status
,KCA_OPERATION
,IS_DELETED_FLG
,KCA_SEQ_ID
,kca_seq_date)
(
select PO_LINE_ID,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
PO_HEADER_ID,
LINE_TYPE_ID,
LINE_NUM,
LAST_UPDATE_LOGIN,
CREATION_DATE,
CREATED_BY,
ITEM_ID,
ITEM_REVISION,
CATEGORY_ID,
ITEM_DESCRIPTION,
UNIT_MEAS_LOOKUP_CODE,
QUANTITY_COMMITTED,
COMMITTED_AMOUNT,
ALLOW_PRICE_OVERRIDE_FLAG,
NOT_TO_EXCEED_PRICE,
LIST_PRICE_PER_UNIT,
UNIT_PRICE,
QUANTITY,
UN_NUMBER_ID,
HAZARD_CLASS_ID,
NOTE_TO_VENDOR,
FROM_HEADER_ID,
FROM_LINE_ID,
MIN_ORDER_QUANTITY,
MAX_ORDER_QUANTITY,
QTY_RCV_TOLERANCE,
OVER_TOLERANCE_ERROR_FLAG,
MARKET_PRICE,
UNORDERED_FLAG,
CLOSED_FLAG,
USER_HOLD_FLAG,
CANCEL_FLAG,
CANCELLED_BY,
CANCEL_DATE,
CANCEL_REASON,
FIRM_STATUS_LOOKUP_CODE,
FIRM_DATE,
VENDOR_PRODUCT_NUM,
CONTRACT_NUM,
TAXABLE_FLAG,
TAX_NAME,
TYPE_1099,
CAPITAL_EXPENSE_FLAG,
NEGOTIATED_BY_PREPARER_FLAG,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
REFERENCE_NUM,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
MIN_RELEASE_AMOUNT,
PRICE_TYPE_LOOKUP_CODE,
CLOSED_CODE,
PRICE_BREAK_LOOKUP_CODE,
USSGL_TRANSACTION_CODE,
GOVERNMENT_CONTEXT,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
CLOSED_DATE,
CLOSED_REASON,
CLOSED_BY,
TRANSACTION_REASON_CODE,
ORG_ID,
QC_GRADE,
BASE_UOM,
BASE_QTY,
SECONDARY_UOM,
SECONDARY_QTY,
GLOBAL_ATTRIBUTE_CATEGORY,
GLOBAL_ATTRIBUTE1,
GLOBAL_ATTRIBUTE2,
GLOBAL_ATTRIBUTE3,
GLOBAL_ATTRIBUTE4,
GLOBAL_ATTRIBUTE5,
GLOBAL_ATTRIBUTE6,
GLOBAL_ATTRIBUTE7,
GLOBAL_ATTRIBUTE8,
GLOBAL_ATTRIBUTE9,
GLOBAL_ATTRIBUTE10,
GLOBAL_ATTRIBUTE11,
GLOBAL_ATTRIBUTE12,
GLOBAL_ATTRIBUTE13,
GLOBAL_ATTRIBUTE14,
GLOBAL_ATTRIBUTE15,
GLOBAL_ATTRIBUTE16,
GLOBAL_ATTRIBUTE17,
GLOBAL_ATTRIBUTE18,
GLOBAL_ATTRIBUTE19,
GLOBAL_ATTRIBUTE20,
LINE_REFERENCE_NUM,
PROJECT_ID,
TASK_ID,
EXPIRATION_DATE,
TAX_CODE_ID,
OKE_CONTRACT_HEADER_ID,
OKE_CONTRACT_VERSION_ID,
SECONDARY_QUANTITY,
SECONDARY_UNIT_OF_MEASURE,
PREFERRED_GRADE,
AUCTION_HEADER_ID,
AUCTION_DISPLAY_NUMBER,
AUCTION_LINE_NUMBER,
BID_NUMBER,
BID_LINE_NUMBER,
RETROACTIVE_DATE,
SUPPLIER_REF_NUMBER,
CONTRACT_ID,
START_DATE,
AMOUNT,
JOB_ID,
CONTRACTOR_FIRST_NAME,
CONTRACTOR_LAST_NAME,
FROM_LINE_LOCATION_ID,
ORDER_TYPE_LOOKUP_CODE,
PURCHASE_BASIS,
MATCHING_BASIS,
SVC_AMOUNT_NOTIF_SENT,
SVC_COMPLETION_NOTIF_SENT,
BASE_UNIT_PRICE,
MANUAL_PRICE_CHANGE_FLAG,
RETAINAGE_RATE,
MAX_RETAINAGE_AMOUNT,
PROGRESS_PAYMENT_RATE,
RECOUPMENT_RATE,
CATALOG_NAME,
SUPPLIER_PART_AUXID,
IP_CATEGORY_ID,
TAX_ATTRIBUTE_UPDATE_CODE,
LAST_UPDATED_PROGRAM,
	group_line_id,
	line_num_display,
	clm_info_flag,
	clm_option_indicator,
	clm_base_line_num,
	clm_option_num,
	clm_option_from_date,
	clm_option_to_date,
	clm_funded_flag,
	contract_type,
	cost_constraint,
	clm_idc_type,
	uda_template_id,
	user_document_status,
	draft_id,
	clm_exercised_flag,
	clm_exercised_date,
	clm_min_total_amount,
	clm_max_total_amount,
	clm_min_total_quantity,
	clm_max_total_quantity,
	clm_min_order_amount,
	clm_max_order_amount,
	clm_min_order_quantity,
	clm_max_order_quantity,
	clm_total_amount_ordered,
	clm_total_quantity_ordered,
	clm_fsc_psc,
	clm_mdaps_mais,
	clm_naics,
	clm_order_start_date,
	clm_order_end_date,
	revision_num,
	clm_approved_undef_amount,
	clm_delivery_event_code,
	clm_exhibit_name,
	clm_payment_instr_code,
	clm_pop_exception_reason,
	clm_uda_pricing_total,
	clm_undef_action_code,
	clm_undef_flag,
	schedules_required_flag,
	"cancel_reason#1",
	"closed_reason#1",
	--igt_line_status,
KCA_OPERATION,
'N' AS IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
  KCA_SEQ_DATE
from bec_ods_stg.po_lines_all
where kca_operation in ('INSERT','UPDATE') and (PO_LINE_ID,kca_seq_id) in (select PO_LINE_ID,max(kca_seq_id) from bec_ods_stg.po_lines_all 
where kca_operation in ('INSERT','UPDATE')
group by PO_LINE_ID)
);

commit;


-- Soft delete
update bec_ods.po_lines_all set IS_DELETED_FLG = 'N';
commit;
update bec_ods.po_lines_all set IS_DELETED_FLG = 'Y'
where (PO_LINE_ID)  in
(
select PO_LINE_ID from bec_raw_dl_ext.po_lines_all
where (PO_LINE_ID,KCA_SEQ_ID)
in 
(
select PO_LINE_ID,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.po_lines_all
group by PO_LINE_ID
) 
and kca_operation= 'DELETE'
);
commit;

end;


update bec_etl_ctrl.batch_ods_info 
set last_refresh_date = getdate() 
where ods_table_name='po_lines_all';

commit;