/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.po_line_locations_all
where LINE_LOCATION_ID in (
select stg.LINE_LOCATION_ID from bec_ods.po_line_locations_all ods, bec_ods_stg.po_line_locations_all stg
where ods.LINE_LOCATION_ID = stg.LINE_LOCATION_ID and stg.kca_operation in ('INSERT','UPDATE'));

commit;

-- Insert records

insert
	into
	bec_ods.PO_LINE_LOCATIONS_ALL
(LINE_LOCATION_ID,
	LAST_UPDATE_DATE,
	LAST_UPDATED_BY,
	PO_HEADER_ID,
	PO_LINE_ID,
	LAST_UPDATE_LOGIN,
	CREATION_DATE,
	CREATED_BY,
	QUANTITY,
	QUANTITY_RECEIVED,
	QUANTITY_ACCEPTED,
	QUANTITY_REJECTED,
	QUANTITY_BILLED,
	QUANTITY_CANCELLED,
	UNIT_MEAS_LOOKUP_CODE,
	PO_RELEASE_ID,
	SHIP_TO_LOCATION_ID,
	SHIP_VIA_LOOKUP_CODE,
	NEED_BY_DATE,
	PROMISED_DATE,
	LAST_ACCEPT_DATE,
	PRICE_OVERRIDE,
	ENCUMBERED_FLAG,
	ENCUMBERED_DATE,
	UNENCUMBERED_QUANTITY,
	FOB_LOOKUP_CODE,
	FREIGHT_TERMS_LOOKUP_CODE,
	TAXABLE_FLAG,
	TAX_NAME,
	ESTIMATED_TAX_AMOUNT,
	FROM_HEADER_ID,
	FROM_LINE_ID,
	FROM_LINE_LOCATION_ID,
	START_DATE,
	END_DATE,
	LEAD_TIME,
	LEAD_TIME_UNIT,
	PRICE_DISCOUNT,
	TERMS_ID,
	APPROVED_FLAG,
	APPROVED_DATE,
	CLOSED_FLAG,
	CANCEL_FLAG,
	CANCELLED_BY,
	CANCEL_DATE,
	CANCEL_REASON,
	FIRM_STATUS_LOOKUP_CODE,
	FIRM_DATE,
	ATTRIBUTE_CATEGORY,
	ATTRIBUTE1,
	ATTRIBUTE2,
	ATTRIBUTE3,
	ATTRIBUTE4,
	ATTRIBUTE5,
	ATTRIBUTE6,
	ATTRIBUTE7,
	ATTRIBUTE8,
	ATTRIBUTE9,
	ATTRIBUTE10,
	UNIT_OF_MEASURE_CLASS,
	ENCUMBER_NOW,
	ATTRIBUTE11,
	ATTRIBUTE12,
	ATTRIBUTE13,
	ATTRIBUTE14,
	ATTRIBUTE15,
	INSPECTION_REQUIRED_FLAG,
	RECEIPT_REQUIRED_FLAG,
	QTY_RCV_TOLERANCE,
	QTY_RCV_EXCEPTION_CODE,
	ENFORCE_SHIP_TO_LOCATION_CODE,
	ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
	DAYS_EARLY_RECEIPT_ALLOWED,
	DAYS_LATE_RECEIPT_ALLOWED,
	RECEIPT_DAYS_EXCEPTION_CODE,
	INVOICE_CLOSE_TOLERANCE,
	RECEIVE_CLOSE_TOLERANCE,
	SHIP_TO_ORGANIZATION_ID,
	SHIPMENT_NUM,
	SOURCE_SHIPMENT_ID,
	SHIPMENT_TYPE,
	CLOSED_CODE,
	REQUEST_ID,
	PROGRAM_APPLICATION_ID,
	PROGRAM_ID,
	PROGRAM_UPDATE_DATE,
	USSGL_TRANSACTION_CODE,
	GOVERNMENT_CONTEXT,
	RECEIVING_ROUTING_ID,
	ACCRUE_ON_RECEIPT_FLAG,
	CLOSED_REASON,
	CLOSED_DATE,
	CLOSED_BY,
	ORG_ID,
	QUANTITY_SHIPPED,
	GLOBAL_ATTRIBUTE_CATEGORY,
	GLOBAL_ATTRIBUTE1,
	GLOBAL_ATTRIBUTE2,
	GLOBAL_ATTRIBUTE3,
	GLOBAL_ATTRIBUTE4,
	GLOBAL_ATTRIBUTE5,
	GLOBAL_ATTRIBUTE6,
	GLOBAL_ATTRIBUTE7,
	GLOBAL_ATTRIBUTE8,
	GLOBAL_ATTRIBUTE9,
	GLOBAL_ATTRIBUTE10,
	GLOBAL_ATTRIBUTE11,
	GLOBAL_ATTRIBUTE12,
	GLOBAL_ATTRIBUTE13,
	GLOBAL_ATTRIBUTE14,
	GLOBAL_ATTRIBUTE15,
	GLOBAL_ATTRIBUTE16,
	GLOBAL_ATTRIBUTE17,
	GLOBAL_ATTRIBUTE18,
	GLOBAL_ATTRIBUTE19,
	GLOBAL_ATTRIBUTE20,
	COUNTRY_OF_ORIGIN_CODE,
	TAX_USER_OVERRIDE_FLAG,
	MATCH_OPTION,
	TAX_CODE_ID,
	CALCULATE_TAX_FLAG,
	CHANGE_PROMISED_DATE_REASON,
	NOTE_TO_RECEIVER,
	SECONDARY_QUANTITY,
	SECONDARY_UNIT_OF_MEASURE,
	PREFERRED_GRADE,
	SECONDARY_QUANTITY_RECEIVED,
	SECONDARY_QUANTITY_ACCEPTED,
	SECONDARY_QUANTITY_REJECTED,
	SECONDARY_QUANTITY_CANCELLED,
	VMI_FLAG,
	CONSIGNED_FLAG,
	RETROACTIVE_DATE,
	SUPPLIER_ORDER_LINE_NUMBER,
	AMOUNT,
	AMOUNT_RECEIVED,
	AMOUNT_BILLED,
	AMOUNT_CANCELLED,
	AMOUNT_REJECTED,
	AMOUNT_ACCEPTED,
	DROP_SHIP_FLAG,
	SALES_ORDER_UPDATE_DATE,
	TRANSACTION_FLOW_HEADER_ID,
	FINAL_MATCH_FLAG,
	MANUAL_PRICE_CHANGE_FLAG,
	SHIPMENT_CLOSED_DATE,
	CLOSED_FOR_RECEIVING_DATE,
	CLOSED_FOR_INVOICE_DATE,
	SECONDARY_QUANTITY_SHIPPED,
	VALUE_BASIS,
	MATCHING_BASIS,
	PAYMENT_TYPE,
	DESCRIPTION,
	WORK_APPROVER_ID,
	BID_PAYMENT_ID,
	QUANTITY_FINANCED,
	AMOUNT_FINANCED,
	QUANTITY_RECOUPED,
	AMOUNT_RECOUPED,
	RETAINAGE_WITHHELD_AMOUNT,
	RETAINAGE_RELEASED_AMOUNT,
	AMOUNT_SHIPPED,
	OUTSOURCED_ASSEMBLY,
	TAX_ATTRIBUTE_UPDATE_CODE,
	ORIGINAL_SHIPMENT_ID,
	LCM_FLAG,
	KCA_OPERATION,
	IS_DELETED_FLG
	,kca_seq_id
	,kca_seq_date
	)	
(
select
	line_location_id,
	last_update_date,
	last_updated_by,
	po_header_id,
	po_line_id,
	last_update_login,
	creation_date,
	created_by,
	quantity,
	quantity_received,
	quantity_accepted,
	quantity_rejected,
	quantity_billed,
	quantity_cancelled,
	unit_meas_lookup_code,
	po_release_id,
	ship_to_location_id,
	ship_via_lookup_code,
	need_by_date,
	promised_date,
	last_accept_date,
	price_override,
	encumbered_flag,
	encumbered_date,
	unencumbered_quantity,
	fob_lookup_code,
	freight_terms_lookup_code,
	taxable_flag,
	tax_name,
	estimated_tax_amount,
	from_header_id,
	from_line_id,
	from_line_location_id,
	start_date,
	end_date,
	lead_time,
	lead_time_unit,
	price_discount,
	terms_id,
	approved_flag,
	approved_date,
	closed_flag,
	cancel_flag,
	cancelled_by,
	cancel_date,
	cancel_reason,
	firm_status_lookup_code,
	firm_date,
	attribute_category,
	attribute1,
	attribute2,
	attribute3,
	attribute4,
	attribute5,
	attribute6,
	attribute7,
	attribute8,
	attribute9,
	attribute10,
	unit_of_measure_class,
	encumber_now,
	attribute11,
	attribute12,
	attribute13,
	attribute14,
	attribute15,
	inspection_required_flag,
	receipt_required_flag,
	qty_rcv_tolerance,
	qty_rcv_exception_code,
	enforce_ship_to_location_code,
	allow_substitute_receipts_flag,
	days_early_receipt_allowed,
	days_late_receipt_allowed,
	receipt_days_exception_code,
	invoice_close_tolerance,
	receive_close_tolerance,
	ship_to_organization_id,
	shipment_num,
	source_shipment_id,
	shipment_type,
	closed_code,
	request_id,
	program_application_id,
	program_id,
	program_update_date,
	ussgl_transaction_code,
	government_context,
	receiving_routing_id,
	accrue_on_receipt_flag,
	closed_reason,
	closed_date,
	closed_by,
	org_id,
	quantity_shipped,
	global_attribute_category,
	global_attribute1,
	global_attribute2,
	global_attribute3,
	global_attribute4,
	global_attribute5,
	global_attribute6,
	global_attribute7,
	global_attribute8,
	global_attribute9,
	global_attribute10,
	global_attribute11,
	global_attribute12,
	global_attribute13,
	global_attribute14,
	global_attribute15,
	global_attribute16,
	global_attribute17,
	global_attribute18,
	global_attribute19,
	global_attribute20,
	country_of_origin_code,
	tax_user_override_flag,
	match_option,
	tax_code_id,
	calculate_tax_flag,
	change_promised_date_reason,
	note_to_receiver,
	secondary_quantity,
	secondary_unit_of_measure,
	preferred_grade,
	secondary_quantity_received,
	secondary_quantity_accepted,
	secondary_quantity_rejected,
	secondary_quantity_cancelled,
	vmi_flag,
	consigned_flag,
	retroactive_date,
	supplier_order_line_number,
	amount,
	amount_received,
	amount_billed,
	amount_cancelled,
	amount_rejected,
	amount_accepted,
	drop_ship_flag,
	sales_order_update_date,
	transaction_flow_header_id,
	final_match_flag,
	manual_price_change_flag,
	shipment_closed_date,
	closed_for_receiving_date,
	closed_for_invoice_date,
	secondary_quantity_shipped,
	value_basis,
	matching_basis,
	payment_type,
	description,
	work_approver_id,
	bid_payment_id,
	quantity_financed,
	amount_financed,
	quantity_recouped,
	amount_recouped,
	retainage_withheld_amount,
	retainage_released_amount,
	amount_shipped,
	outsourced_assembly,
	tax_attribute_update_code,
	original_shipment_id,
	lcm_flag,
	KCA_OPERATION,
'N' AS IS_DELETED_FLG
,cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
  KCA_SEQ_DATE
from
	bec_ods_stg.po_line_locations_all
where kca_operation in ('INSERT','UPDATE') and (LINE_LOCATION_ID,kca_seq_id) in (select LINE_LOCATION_ID,max(kca_seq_id) from bec_ods_stg.po_line_locations_all 
where kca_operation in ('INSERT','UPDATE')
group by LINE_LOCATION_ID)


);
commit;



-- Soft delete
update bec_ods.po_line_locations_all set IS_DELETED_FLG = 'N';
commit;
update bec_ods.po_line_locations_all set IS_DELETED_FLG = 'Y'
where (LINE_LOCATION_ID)  in
(
select LINE_LOCATION_ID from bec_raw_dl_ext.po_line_locations_all
where (LINE_LOCATION_ID,KCA_SEQ_ID)
in 
(
select LINE_LOCATION_ID,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.po_line_locations_all
group by LINE_LOCATION_ID
) 
and kca_operation= 'DELETE'
);
commit;

end;

update
	bec_etl_ctrl.batch_ods_info
set load_type = 'I',
	last_refresh_date = getdate()
where
	ods_table_name = 'po_line_locations_all';

commit;