/*
# Copyright(c) 2022 KPI Partners, Inc. All Rights Reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# author: KPI Partners, Inc.
# version: 2022.06
# description: This script represents Incremental load approach for ODS.
# File Version: KPI v1.0
*/
begin;

-- Delete Records

delete from bec_ods.wip_transactions
where TRANSACTION_ID in (
select stg.TRANSACTION_ID from bec_ods.wip_transactions ods, bec_ods_stg.wip_transactions stg
where ods.TRANSACTION_ID = stg.TRANSACTION_ID and stg.kca_operation IN ('INSERT','UPDATE')
);

commit;

-- Insert records

insert into	bec_ods.wip_transactions
(
TRANSACTION_ID,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
CREATION_DATE,
CREATED_BY,
LAST_UPDATE_LOGIN,
ORGANIZATION_ID,
WIP_ENTITY_ID,
PRIMARY_ITEM_ID,
ACCT_PERIOD_ID,
DEPARTMENT_ID,
TRANSACTION_TYPE,
TRANSACTION_DATE,
GROUP_ID,
LINE_ID,
SOURCE_CODE,
SOURCE_LINE_ID,
OPERATION_SEQ_NUM,
RESOURCE_SEQ_NUM,
EMPLOYEE_ID,
RESOURCE_ID,
AUTOCHARGE_TYPE,
STANDARD_RATE_FLAG,
USAGE_RATE_OR_AMOUNT,
BASIS_TYPE,
TRANSACTION_QUANTITY,
TRANSACTION_UOM,
PRIMARY_QUANTITY,
PRIMARY_UOM,
ACTUAL_RESOURCE_RATE,
STANDARD_RESOURCE_RATE,
CURRENCY_CODE,
CURRENCY_CONVERSION_DATE,
CURRENCY_CONVERSION_TYPE,
CURRENCY_CONVERSION_RATE,
CURRENCY_ACTUAL_RESOURCE_RATE,
ACTIVITY_ID,
REASON_ID,
REFERENCE,
MOVE_TRANSACTION_ID,
PO_HEADER_ID,
PO_LINE_ID,
RCV_TRANSACTION_ID,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
COST_UPDATE_ID,
PM_COST_COLLECTED,
PM_COST_COLLECTOR_GROUP_ID,
PROJECT_ID,
TASK_ID,
COMPLETION_TRANSACTION_ID,
CHARGE_DEPARTMENT_ID,
INSTANCE_ID,
ENCUMBRANCE_TYPE_ID,
ENCUMBRANCE_AMOUNT,
ENCUMBRANCE_QUANTITY,
ENCUMBRANCE_CCID,
KCA_OPERATION,
IS_DELETED_FLG,
kca_seq_id
,kca_seq_date
)

(SELECT
TRANSACTION_ID,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
CREATION_DATE,
CREATED_BY,
LAST_UPDATE_LOGIN,
ORGANIZATION_ID,
WIP_ENTITY_ID,
PRIMARY_ITEM_ID,
ACCT_PERIOD_ID,
DEPARTMENT_ID,
TRANSACTION_TYPE,
TRANSACTION_DATE,
GROUP_ID,
LINE_ID,
SOURCE_CODE,
SOURCE_LINE_ID,
OPERATION_SEQ_NUM,
RESOURCE_SEQ_NUM,
EMPLOYEE_ID,
RESOURCE_ID,
AUTOCHARGE_TYPE,
STANDARD_RATE_FLAG,
USAGE_RATE_OR_AMOUNT,
BASIS_TYPE,
TRANSACTION_QUANTITY,
TRANSACTION_UOM,
PRIMARY_QUANTITY,
PRIMARY_UOM,
ACTUAL_RESOURCE_RATE,
STANDARD_RESOURCE_RATE,
CURRENCY_CODE,
CURRENCY_CONVERSION_DATE,
CURRENCY_CONVERSION_TYPE,
CURRENCY_CONVERSION_RATE,
CURRENCY_ACTUAL_RESOURCE_RATE,
ACTIVITY_ID,
REASON_ID,
REFERENCE,
MOVE_TRANSACTION_ID,
PO_HEADER_ID,
PO_LINE_ID,
RCV_TRANSACTION_ID,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
REQUEST_ID,
PROGRAM_APPLICATION_ID,
PROGRAM_ID,
PROGRAM_UPDATE_DATE,
COST_UPDATE_ID,
PM_COST_COLLECTED,
PM_COST_COLLECTOR_GROUP_ID,
PROJECT_ID,
TASK_ID,
COMPLETION_TRANSACTION_ID,
CHARGE_DEPARTMENT_ID,
INSTANCE_ID,
ENCUMBRANCE_TYPE_ID,
ENCUMBRANCE_AMOUNT,
ENCUMBRANCE_QUANTITY,
ENCUMBRANCE_CCID,
KCA_OPERATION,
'N' AS IS_DELETED_FLG,
cast(NULLIF(KCA_SEQ_ID,'') as numeric(36,0)) as KCA_SEQ_ID,
  KCA_SEQ_DATE
from
	bec_ods_stg.wip_transactions
where kca_operation in ('INSERT','UPDATE') 
	and (TRANSACTION_ID,kca_seq_id) in 
	(select TRANSACTION_ID,max(kca_seq_id) from bec_ods_stg.wip_transactions 
     where kca_operation in ('INSERT','UPDATE')
     group by TRANSACTION_ID)
);
	
commit;



-- Soft delete
update bec_ods.wip_transactions set IS_DELETED_FLG = 'N';
commit;
update bec_ods.wip_transactions set IS_DELETED_FLG = 'Y'
where (TRANSACTION_ID)  in
(
select TRANSACTION_ID from bec_raw_dl_ext.wip_transactions
where (TRANSACTION_ID,KCA_SEQ_ID)
in 
(
select TRANSACTION_ID,max(KCA_SEQ_ID) as KCA_SEQ_ID 
from bec_raw_dl_ext.wip_transactions
group by TRANSACTION_ID
) 
and kca_operation= 'DELETE'
);
commit;

end;

update
	bec_etl_ctrl.batch_ods_info
set
	last_refresh_date = getdate()
where
	ods_table_name = 'wip_transactions';

commit;